// lib/language_keys/lang_sw_swahili.dart
//
// Swahili (Kiswahili) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> swSwahili = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Hakuna lugha zilizopatikana',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Ruka',
  'onboarding_next'                     : 'Endelea',
  'onboarding_get_started'              : 'Anza',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Karibu',
  'ob1_title'                           : 'Tengeneza CV Inayofungua\nMilango',
  'ob1_body'                            : 'Jitofautishe kati ya mamia ya waombaji. Jenga CV nzuri inayoshinda kazi kwa dakika chache — bila ujuzi wa muundo.',
  'ob1_pill_label'                      : 'Mtengenezaji wa CV wa Kitaalamu',
  'ob1_chip_templates'                  : 'Violezo 24+',
  'ob1_chip_pdf'                        : 'Tuma PDF',
  'ob1_chip_free'                       : 'Bure Kutumia',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Violezo',
  'ob2_title'                           : 'Kila Sekta.\nKila Ndoto.',
  'ob2_body'                            : 'Kutoka miundo ya mkutano hadi miundo ya ubunifu — kiolezo kinachosema hadithi yako.',
  'ob2_tap_hint'                        : 'Gusa kiolezo chochote kukiona',
  'ob2_tpl_executive'                   : 'Mtendaji',
  'ob2_tpl_vibrant'                     : 'Hai',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Nyeusi',
  'ob2_tpl_luxury'                      : 'Anasa',
  'ob2_tag_corporate'                   : 'Kampuni',
  'ob2_tag_creative'                    : 'Ubunifu',
  'ob2_tag_minimal'                     : 'Rahisi',
  'ob2_tag_modern'                      : 'Ya Kisasa',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Mpangilio Mahiri',
  'ob3_title'                           : 'CV Yako.\nImepangwa Vizuri.',
  'ob3_body'                            : 'Mpangilio Mahiri upanga upya sehemu zako kwa athari kubwa — ukiweka maudhui yako bora ambapo waajiriwa wanaangalia kwanza.',
  'ob3_badge_smart_layout'              : 'Mpangilio Mahiri',
  'ob3_badge_cv_ready'                  : 'CV Iko Tayari!',
  'ob3_step1_label'                     : 'Chagua Kiolezo',
  'ob3_step1_desc'                      : 'Chagua kutoka miundo 24+ ya kupendeza.',
  'ob3_step2_label'                     : 'Jaza Maelezo Yako',
  'ob3_step2_desc'                      : 'Sehemu zote zina mwongozo.',
  'ob3_step3_label'                     : 'Mpangilio Mahiri',
  'ob3_step3_desc'                      : 'Gusa mara moja kupanga CV yako vizuri.',
  'ob3_step4_label'                     : 'Tuma kama PDF',
  'ob3_step4_desc'                      : 'PDF kamili tayari kutuma.',
  'ob3_section_work'                    : 'Uzoefu wa Kazi',
  'ob3_section_education'               : 'Elimu',
  'ob3_section_skills'                  : 'Ujuzi',
  'ob3_section_references'              : 'Marejeleo',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Tayari Kuanza',
  'ob4_title'                           : 'Kwa Nini Wagombea Bora\nWanachagua CV Builder',
  'ob4_visual_headline'                 : 'Uko Tayari Kabisa!',
  'ob4_visual_subline'                  : 'Kila kitu unachohitaji kupata kazi.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Violezo',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'CV Nyingi Zaidi',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Tuma',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Siri',
  'ob4_hl1_title'                       : 'Siri na Salama',
  'ob4_hl1_sub'                         : 'Data inabaki kwenye kifaa chako.',
  'ob4_hl2_title'                       : 'Hifadhi Otomatiki',
  'ob4_hl2_sub'                         : 'Kila herufi inahifadhiwa mara moja.',
  'ob4_hl3_title'                       : 'Hadi CV 30',
  'ob4_hl3_sub'                         : 'CV ya kipekee kwa kila nafasi.',
  'ob4_hl4_title'                       : 'Shiriki kwa Mguso Mmoja',
  'ob4_hl4_sub'                         : 'Tuma PDF bila kuacha programu.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Jitofautishe na umati',
  'home_hero_title'                     : 'Tengeneza CV Yako\nya Kitaalamu',
  'home_hero_sub'                       : 'Jenga wasifu wa kupendeza\nkwa dakika chache',
  'home_hero_cta'                       : 'Anza Kujenga',
  'home_premium_soon'                   : 'Panda daraja hadi Pro hivi karibuni!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Mpya Zaidi',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Iliyohaririwa Mwisho',
  'history_sort_by_template'            : 'Kwa Kiolezo',
  'history_sort_sheet_title'            : 'Panga Kwa',
  'history_sort_alphabetical_full'      : 'Alfabeti (A–Z)',
  'history_premium_soon'                : 'Panda daraja hadi Pro hivi karibuni!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Mipangilio',
  'settings_section_preferences'        : 'Mapendeleo',
  'settings_section_support'            : 'Msaada',
  'settings_section_legal'              : 'Kisheria',
  'settings_section_about'              : 'Kuhusu',
  'settings_language_tile_title'        : 'Lugha',
  'settings_dark_mode_title'            : 'Hali ya Giza',
  'settings_dark_mode_on'               : 'Mandhari ya giza imewezeshwa',
  'settings_dark_mode_off'              : 'Mandhari ya mwanga imewezeshwa',
  'settings_help_faq_title'             : 'Msaada na Maswali',
  'settings_help_faq_sub'               : 'Maswali ya kawaida yamejibiwa',
  'settings_contact_support_title'      : 'Wasiliana na Msaada',
  'settings_rate_app_title'             : 'Kadiria Programu',
  'settings_rate_app_sub'               : 'Unafurahia programu? Acha tathmini!',
  'settings_privacy_policy_title'       : 'Sera ya Faragha',
  'settings_terms_title'                : 'Masharti ya Huduma',
  'settings_app_version_title'          : 'Toleo la Programu',
  'settings_email_error'                : 'Imeshindwa kufungua programu ya barua pepe. Tafadhali tuma barua pepe kwa cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Hakiki CV',
  'preview_header_sub'                  : 'Tayari kutuma',
  'preview_generating'                  : 'Inatengeneza CV yako...',
  'preview_failed_title'                : 'Hakiki Imeshindwa',
  'preview_failed_error'                : 'Hitilafu: {error}',
  'preview_go_back'                     : 'Rudi Nyuma',
  'preview_no_data'                     : 'Hakuna data inayopatikana',
  'preview_btn_print'                   : 'Chapisha',
  'preview_btn_download'                : 'Pakua na Shiriki',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Msaada na Maswali',
  'faq_category_all'                    : 'Yote',
  'faq_empty'                           : 'Hakuna matokeo',
  'faq_contact_headline'                : 'Bado unahitaji msaada?',
  'faq_contact_sub'                     : 'Timu yetu iko hapa kukusaidia.',
  'faq_contact_btn'                     : 'Wasiliana',
  'faq_email_error'                     : 'Imeshindwa kufungua programu ya barua pepe. Tafadhali tuma barua pepe kwa cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Kuanza',
  'faq_cat_templates'                   : 'Violezo',
  'faq_cat_editing'                     : 'Kuhariri',
  'faq_cat_exporting'                   : 'Kutuma',
  'faq_cat_data_privacy'                : 'Data na Faragha',
  'faq_cat_troubleshooting'             : 'Kutatua Matatizo',
  'faq_q1'  : 'Ninatengenezaje CV yangu ya kwanza?',
  'faq_a1'  : 'Gusa kitufe cha "+" kwenye skrini ya nyumbani kuanza CV mpya. Chagua kiolezo kinachokufaa, kisha jaza maelezo yako ya kibinafsi, uzoefu wa kazi, elimu na ujuzi hatua kwa hatua. Maendeleo yako yanahifadhiwa otomatiki.',
  'faq_q2'  : 'Ninaweza kutengeneza CV zaidi ya moja?',
  'faq_a2'  : 'Ndiyo! Unaweza kutengeneza CV nyingi kwa majukumu au sekta tofauti. Kila CV inahifadhiwa kando, ili uweze kuzirekebisha kwa maombi maalum ya kazi.',
  'faq_q3'  : 'Ninabadilishaje kiolezo cha CV yangu?',
  'faq_a3'  : 'Fungua CV yako, gusa ikoni ya kiolezo juu ya skrini, na vinjari violezo vilivyopo. Gusa kiolezo chochote kukiona na maudhui yako yaliyopo. Thibitisha kulitumia.',
  'faq_q4'  : 'Kuna violezo vya bure na vya premium?',
  'faq_a4'  : 'Ndiyo. Mkusanyiko wa violezo vya kitaalamu vipo bure. Violezo vya premium vyenye miundo ya kisasa na paleti za rangi vinapatikana kupitia ununuzi wa mara moja au usajili.',
  'faq_q5'  : 'Ninawezaje kuongeza au kuondoa sehemu?',
  'faq_a5'  : 'Katika kihariri cha CV, telezesha hadi chini ya skrini na uguse "Ongeza Sehemu" kujumuisha ziada kama Lugha, Vyeti, au Kazi ya Kujitolea. Kuondoa sehemu, gusa kichwa cha sehemu na uchague "Ondoa."',
  'faq_q6'  : 'Ninawezaje kupanga upya sehemu?',
  'faq_a6'  : 'Shikilia mpini wa kukokota (≡) karibu na kichwa cha sehemu yoyote na uikokote hadi nafasi unayopendelea. Mabadiliko yanahifadhiwa otomatiki.',
  'faq_q7'  : 'Ninawezaje kutuma CV yangu kama PDF?',
  'faq_a7'  : 'Fungua CV yako na uguse kitufe cha kutuma (ikoni ya kushiriki) kwenye kona ya juu kulia. Chagua "Tuma kama PDF." Unaweza kuihifadhi kwenye kifaa chako, kuishiriki kupitia barua pepe, WhatsApp, au kuipakia moja kwa moja kwenye mabodi ya kazi.',
  'faq_q8'  : 'Ni muundo gani wa faili unaosaidiwa?',
  'faq_a8'  : 'Kwa sasa Programu inasaidia kutuma CV yako kama PDF ya ubora wa juu. Miundo ya ziada inaweza kuongezwa katika masasisho ya baadaye.',
  'faq_q9'  : 'Data ya CV yangu inahifadhiwa wapi?',
  'faq_a9'  : 'Data yako yote ya CV inahifadhiwa ndani ya kifaa chako. Hatupakii maelezo yako ya kibinafsi kwenye seva zetu. Hii inamaanisha data yako inabaki kuwa siri na inapatikana nje ya mtandao.',
  'faq_q10' : 'Ninawezaje kuhifadhi nakala ya CV zangu?',
  'faq_a10' : 'CV zako zimejumuishwa katika hifadhi ya kawaida ya kifaa chako (hifadhi ya Google Drive kwenye Android, iCloud kwenye iOS) ikiwa una hifadhi imewezeshwa katika mipangilio ya kifaa chako. Pia unaweza kutuma CV moja moja kama PDF kuhifadhi nakala.',
  'faq_q11' : 'Programu inakwenda polepole. Nifanye nini?',
  'faq_a11' : 'Jaribu kufunga na kufungua tena programu. Ikiwa tatizo linaendelea, anzisha upya kifaa chako. Hakikisha una toleo jipya zaidi la programu iliyosanikishwa kutoka Play Store / App Store.',
  'faq_q12' : 'CV yangu haitumi vizuri. Nifanye nini?',
  'faq_a12' : 'Hakikisha una nafasi ya kutosha ya kuhifadhi kwenye kifaa chako. Jaribu kupunguza picha kubwa katika CV yako. Ikiwa tatizo linaendelea, tafadhali wasiliana na timu yetu ya msaada.',
  'faq_q13' : 'Nilisahau kuhifadhi — kazi yangu imepotea?',
  'faq_a13' : 'Hata kidogo! Programu inahifadhi maendeleo yako kila wakati unapohariri.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Kazi yako, imekamilishwa',
  'header_tooltip_back'                 : 'Rudi',
  'header_tooltip_my_cvs'               : 'CV Zangu',
  'header_tooltip_settings'             : 'Mipangilio',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV Zangu',
  'saved_count_single'                  : 'hati {n}',
  'saved_count_plural'                  : 'hati {n}',
  'saved_limit_reached'                 : 'Kikomo kimefikiwa',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Zote',
  'saved_filter_draft'                  : 'Rasimu',
  'saved_filter_complete'               : 'Kamili',
  'saved_status_complete'               : 'Kamili',
  'saved_status_saved'                  : 'Imehifadhiwa',
  'saved_status_draft'                  : 'Rasimu',
  'saved_empty_title'                   : 'Bado hakuna CV hapa',
  'saved_empty_sub'                     : 'Anza kujenga CV yako ya kwanza hapo juu',
  'saved_search_empty_title'            : 'Hakuna matokeo',
  'saved_search_empty_sub'              : 'Jaribu neno tofauti la kutafuta',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Mchoro wa Rangi',
  'custom_font_settings_title'          : 'Mipangilio ya Fonti',
  'custom_font_family_label'            : 'Familia ya Fonti',
  'custom_font_size_label'              : 'Ukubwa wa Fonti: ',
  'custom_current_template_title'       : 'Kiolezo cha Sasa',
  'custom_change_template_btn'          : 'Badilisha Kiolezo',
  'custom_tpl_modern'                   : 'Ya Kisasa',
  'custom_tpl_classic'                  : 'Klasiki',
  'custom_tpl_professional'             : 'Kitaalamu',
  'custom_tpl_creative'                 : 'Ubunifu',
  'custom_tpl_minimal'                  : 'Rahisi',
  'custom_tpl_modern_desc'              : 'Muundo safi na wa kisasa',
  'custom_tpl_classic_desc'             : 'Mpangilio wa kitaalamu wa jadi',
  'custom_tpl_professional_desc'        : 'Kiolezo kinacholenga biashara',
  'custom_tpl_creative_desc'            : 'Jitofautishe na muundo wa kipekee',
  'custom_tpl_minimal_desc'             : 'Mtindo rahisi na wa kifahari',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Chagua Kiolezo',
  'swipe_photo_badge'                   : 'Picha',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Mtendaji',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Hai',
  'tpl_tech_dark_name'                  : 'Tech Nyeusi',
  'tpl_luxury_name'                     : 'Anasa',
  'tpl_executive_tag'                   : 'Maarufu Zaidi',
  'tpl_nordic_tag'                      : 'Safi',
  'tpl_vibrant_tag'                     : 'Ubunifu',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Bora',
  'tpl_executive_desc'                  : 'Hodari na wenye mamlaka kwa nafasi za juu',
  'tpl_nordic_desc'                     : 'Uwazi wa chini unaoweza kuaminiwa na makampuni bora',
  'tpl_vibrant_desc'                    : 'Jitofautishe kwa nguvu na rangi',
  'tpl_tech_dark_desc'                  : 'Muonekano wa terminal kwa wasanidi',
  'tpl_luxury_desc'                     : 'Hadhi ya dhahabu kwenye mandhari nyeusi',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Kiolezo',
  'detail_step_personal'                : 'Kibinafsi',
  'detail_step_experience'              : 'Uzoefu',
  'detail_step_education'               : 'Elimu',
  'detail_step_skills'                  : 'Ujuzi',
  'detail_step_additional'              : 'Ziada',
  'detail_step_references'              : 'Marejeleo',
  'detail_step_customize'               : 'Rekebisha',
  'detail_banner_heading'               : 'Karibu kukamilika!',
  'detail_banner_btn'                   : 'Endelea',
  'detail_banner_completion_label'      : 'Ukamilishaji',
  'detail_stat_created_label'           : 'Iliundwa',
  'detail_stat_steps_label'             : 'Hatua zilizofanywa',
  'detail_section_template_style'       : 'Mtindo wa Kiolezo',
  'detail_section_steps'                : 'Hatua',
  'detail_steps_counter'                : '{done} kati ya {total} zimekamilika',
  'detail_step_sub'                     : 'Hatua {n} kati ya {total}',
  'detail_section_activity'             : 'Shughuli',
  'detail_activity_created'             : 'Iliundwa',
  'detail_activity_last_edited'         : 'Iliyohaririwa Mwisho',
  'detail_activity_template'            : 'Kiolezo',
  'detail_btn_continue_editing'         : 'Endelea Kuhariri',
  'detail_btn_edit_cv'                  : 'Hariri CV',
  'detail_option_rename'                : 'Badilisha Jina la CV',
  'detail_option_delete'                : 'Futa CV',
  'detail_rename_title'                 : 'Badilisha Jina la CV',
  'detail_rename_hint'                  : 'mf. CV ya Mhandisi wa Programu',
  'detail_rename_error_empty'           : 'Jina haliwezi kuwa tupu',
  'detail_rename_btn_cancel'            : 'Ghairi',
  'detail_rename_btn_save'              : 'Hifadhi',
  'detail_rename_snackbar'              : 'Imebadilishwa jina hadi "{name}"',
  'detail_delete_title'                 : 'Futa CV?',
  'detail_delete_body'                  : 'Hii itafuta "{name}" milele. Kitendo hiki hakiwezi kutendwa upya.',
  'detail_delete_btn_cancel'            : 'Ghairi',
  'detail_delete_btn_confirm'           : 'Futa',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Imekamilika',
  'detail_check_tile_incomplete'        : 'Bado haijajazwa',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Chagua Kiolezo Chako',
  'chooser_subtitle'                    : 'Telezesha kuvinjari  ·  Gusa kuchagua  ·  Shikilia kukiona',
  'chooser_card_hold_hint'              : 'Shikilia kukiona',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Imechaguliwa',
  'chooser_modal_heading'               : 'Ipe CV Yako Jina',
  'chooser_modal_sub'                   : 'Ipe jina ili uweze kuipata kwa urahisi katika CV Zangu na Historia.',
  'chooser_modal_field_label'           : 'Jina la CV',
  'chooser_modal_save_btn'              : 'Hifadhi na Anza Kujenga',
  'chooser_modal_divider'               : 'au endelea na CV iliyopo',
  'chooser_nav_selected_sub'            : 'Kiolezo kilichochaguliwa',
  'chooser_nav_cta'                     : 'Hifadhi na Endelea',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Idadi ya Juu ya Maingizo Imefikiwa',
  'editor_show_hide'                    : 'Onyesha/Ficha',
  'editor_editing_badge'                : 'Inahaririwa',
  'editor_field_required'               : 'Inahitajika',
  'editor_tooltip_edit'                 : 'Hariri',
  'editor_tooltip_delete'               : 'Futa',
  'editor_date_start'                   : 'Tarehe ya Kuanza *',
  'editor_date_end'                     : 'Tarehe ya Kumalizika *',
  'editor_date_tap_hint'                : 'Gusa kuchagua',
  'editor_date_dialog_title'            : 'Chagua Mwezi na Mwaka',
  'editor_date_confirm'                 : 'Thibitisha',
  'editor_panel_hide'                   : 'Ficha',
  'editor_panel_show'                   : 'Onyesha',
  'editor_validator_max_chars'          : 'Herufi {n} nyingi zaidi',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Jenga CV Yako',
  'editor_header_step_sub'              : 'Hatua {current} kati ya {total} · {label}',
  'editor_step_template'                : 'Kiolezo',
  'editor_step_personal'                : 'Kibinafsi',
  'editor_step_experience'              : 'Uzoefu',
  'editor_step_education'               : 'Elimu',
  'editor_step_skills'                  : 'Ujuzi',
  'editor_step_additional'              : 'Ziada',
  'editor_step_references'              : 'Marejeleo',
  'editor_step_customize'               : 'Rekebisha',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Rekebisha',
  'customize_subtitle'                  : 'Fanya CV yako iwe ya kipekee',
  'customize_smart_layout_btn'          : 'Mpangilio Mahiri',
  'customize_back_to_top'               : 'Rudi Juu',
  'customize_done_title'                : 'Uko Tayari Kabisa!',
  'customize_done_sub'                  : 'Gusa Hakiki CV hapa chini kuona CV yako iliyokamilika',
  'customize_preview_btn'               : 'Hakiki CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Mchoro wa Rangi',
  'color_black'                         : 'Nyeusi',
  'color_blue'                          : 'Bluu',
  'color_nordic_blue'                   : 'Bluu ya Nordic',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Kijani Bluu',
  'color_green'                         : 'Kijani',
  'color_purple'                        : 'Zambarau',
  'color_orange'                        : 'Chungwa',
  'color_red'                           : 'Nyekundu',
  'color_executive_gold'                : 'Dhahabu ya Mtendaji',
  'color_vibrant_coral'                 : 'Korali Hai',
  'color_white'                         : 'Nyeupe',
  'color_white_bg'                      : 'Mandhari Nyeupe',
  'color_maroon'                        : 'Maroon',
  'color_brutalist_yellow'              : 'Njano ya Brutalist',
  'color_neon_blue'                     : 'Bluu ya Neon',
  'color_blueprint_navy'                : 'Bluu ya Navy ya Ramani',
  'color_light_grey'                    : 'Kijivu Hafifu',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Familia ya Fonti',
  'customize_font_picker_title'         : 'Chagua Fonti',
  'customize_font_picker_sub'           : 'Kila fonti inaonyeshwa katika muundo wake',
  'customize_font_preview_sample'       : 'Mbweha mwepesi wa kahawia',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Ukubwa wa Fonti',
  'customize_font_size_label'           : 'Ukubwa wa Maandishi',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Ukubwa wa Picha',
  'customize_image_size_label'          : 'Ukubwa wa Picha',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Hakiki ya Moja kwa Moja',
  'preview_page_count_singular'         : 'ukurasa 1',
  'preview_page_count_plural'           : 'kurasa {n}',
  'preview_page_of'                     : 'Ukurasa {page} kati ya {total}',
  'preview_live_hint'                   : 'Mabadiliko yanatekelezwa mara moja',
  'preview_template_unregistered'       : 'Bado haijasajiliwa katika customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Inakuandalia CV yako…',
  'preview_bar_print'                   : 'Chapisha',
  'preview_bar_save_pdf'                : 'Hifadhi kama PDF',
  'preview_bar_share'                   : 'Shiriki',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Hakiki CV',
  'preview_screen_sub'                  : '{n} {unit} · kama ilivyochapishwa',
  'preview_page_singular'               : 'ukurasa',
  'preview_page_plural'                 : 'kurasa',
  'preview_pdf_filename'                : 'CV_Yangu',
  'preview_share_subject'               : 'CV Yangu',
  'preview_snack_print_failed'          : 'Kuchapisha kumeshindwa: {e}',
  'preview_snack_saved'                 : 'CV imehifadhiwa kwenye Vipakuliwa ✓',
  'preview_snack_export_failed'         : 'Kutuma kumeshindwa: {e}',
  'preview_snack_share_failed'          : 'Kushiriki kumeshindwa: {e}',
  'preview_template_not_registered'     : 'Kiolezo hakijasajiliwa',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Funga hakiki',
  'preview_modal_hint_photo'            : 'Inasaidia picha ya wasifu  ·  Gusa kadi kuchagua',
  'preview_modal_hint_no_photo'         : 'Gusa kadi ya kiolezo kuichagua',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV Yangu',
  'time_just_now'                       : 'Sasa hivi',
  'time_minutes_ago'                    : 'Dakika {n} zilizopita',
  'time_hours_ago'                      : 'Saa {n} zilizopita',
  'time_yesterday'                      : 'Jana',
  'time_days_ago'                       : 'Siku {n} zilizopita',
  'time_one_week_ago'                   : 'Wiki 1 iliyopita',
  'time_weeks_ago'                      : 'Wiki {n} zilizopita',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Kifahari',
  'tpl_tag_classic'                     : 'Klasiki',
  'tpl_tag_minimal'                     : 'Rahisi',
  'tpl_tag_creative'                    : 'Ubunifu',
  'tpl_tag_bold'                        : 'Jasiri',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradiani',
  'tpl_gradient_desc'                   : 'Kadi za gradiani kutoka kijani bluu hadi zambarau',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Uhariri',
  'tpl_editorial_desc'                  : 'Mtindo wa jarida nyekundu na cream',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Laini',
  'tpl_pastel_soft_desc'                : 'Upande wa lavenda, kadi laini',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Gridi ghafi, mipaka imara na njano',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Zamaradi',
  'tpl_emerald_desc'                    : 'Kijani cha msitu na mstari wa wakati',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografia',
  'tpl_infographic_desc'                : 'Turubai nyeusi na chati za pete',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Anasa ya kijiometri ya dhahabu ya miaka ya 1920',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Nyeusi',
  'tpl_wina_dark_desc'                  : 'Infografia nyeusi na pete',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Chungwa',
  'tpl_rio_orange_desc'                 : 'Upande nyeusi na mwangaza wa chungwa',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Kiangazi',
  'tpl_summer_desc'                     : 'Rahisi safi, vivuli laini vya kijivu',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Vivuli vya kifahari vya beige joto',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Klasiki kali nyeusi na nyeupe',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Mpangilio wa klasiki unaofaa ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Nyeusi',
  'tpl_tony_dark_desc'                  : 'Mtindo wa infografia ya chungwa nyeusi',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Mitindo',
  'tpl_fashion_desc'                    : 'Mchoro wa kiufundi kwenye gridi',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Mkumbusho',
  'tpl_archivist_desc'                  : 'Mpangilio wa klasiki wa safu mbili na lebo',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Balozi',
  'tpl_diplomat_desc'                   : 'Vichwa vya kivuli na alama za almasi',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Vichwa vya katikati, makampuni ya mwangaza',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Kasi',
  'tpl_momentum_desc'                   : 'Jina imara, nukta za mstari wa wakati na mafanikio',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Maelezo ya Kibinafsi',
  'personal_subtitle'                   : 'Mwambie mwajiri ni nani wewe',
  'personal_profile_counter'            : 'mawasifu {n}/{max}',
  'personal_info_banner'                : 'Hifadhi hadi mawasifu 5 na uchague moja kwa kila CV. Uchaguzi wako unakumbukwa kwa kila CV kando.',
  'personal_snack_max'                  : 'Idadi ya juu ya mawasifu {n} imefikiwa.',
  'personal_add_btn'                    : 'Ongeza Wasifu Mpya',
  'personal_library_title'              : 'Mawasifu Yaliyohifadhiwa',
  'personal_selected_one'               : '1 imechaguliwa',
  'personal_selected_none'              : 'hakuna kilichochaguliwa',
  'personal_library_hint'               : 'Gusa kadi kuichagua kwa CV hii peke yake. CV zingine zinaweka uchaguzi wao wa kujitegemea.',
  'personal_empty_message'              : 'Bado hakuna mawasifu yaliyohifadhiwa',
  'personal_empty_sub'                  : 'Gusa hapo juu kuongeza maelezo yako ya kibinafsi',
  'personal_nav_next'                   : 'Hifadhi na Endelea',
  'personal_card_active_badge'          : 'Inafanya kazi kwa CV hii',
  'personal_sheet_title_add'            : 'Wasifu Mpya',
  'personal_sheet_title_edit'           : 'Hariri Wasifu',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Kiolezo cha Brutalist kina sehemu fupi za mawasiliano. Maadili mafupi (mf. jiji peke yake) yanaonekana vizuri zaidi.',
  'personal_section_photo'              : 'Picha ya Wasifu',
  'personal_section_basic'              : 'Maelezo ya Msingi',
  'personal_section_contact'            : 'Mawasiliano',
  'personal_section_online'             : 'Uwepo wa Mtandaoni',
  'personal_section_summary'            : 'Muhtasari wa Kitaalamu',
  'personal_field_first_name'           : 'Jina la Kwanza *',
  'personal_field_last_name'            : 'Jina la Ukoo',
  'personal_field_job_title'            : 'Cheo cha Kazi *',
  'personal_field_email'                : 'Anwani ya Barua Pepe *',
  'personal_field_phone'                : 'Nambari ya Simu *',
  'personal_field_location'             : 'Mahali',
  'personal_field_location_brut'        : 'Mahali (jiji peke yake)',
  'personal_field_website'              : 'Tovuti / Kwingineko',
  'personal_field_linkedin'             : 'URL ya LinkedIn',
  'personal_hint_first_name'            : 'mf. Amina',
  'personal_hint_last_name'             : 'mf. Hassan',
  'personal_hint_job_title'             : 'mf. Mhandisi Mkuu',
  'personal_hint_email'                 : 'mf. amina@mfano.com',
  'personal_hint_phone'                 : 'mf. +255 712 345 678',
  'personal_hint_location'              : 'mf. Dar es Salaam, Tanzania',
  'personal_hint_location_brut'         : 'mf. Dar es Salaam, TZ',
  'personal_hint_website'               : 'mf. github.com/aminahassan',
  'personal_hint_website_brut'          : 'mf. github.com/amina',
  'personal_hint_linkedin'              : 'mf. linkedin.com/in/aminahassan',
  'personal_hint_linkedin_brut'         : 'mf. linkedin.com/in/amina',
  'personal_summary_hint_label'         : 'Iwe fupi — hii inaonekana juu ya CV yako.',
  'personal_hint_summary'               : 'Muhtasari mfupi wa sentensi 2–3 za historia na malengo yako...',
  'personal_validator_email'            : 'Ingiza barua pepe sahihi',
  'personal_field_char_limit_tooltip'   : 'Kikomo cha herufi kimefikiwa',
  'personal_sheet_btn_save'             : 'Hifadhi Wasifu',
  'personal_sheet_btn_update'           : 'Hifadhi Mabadiliko',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Chagua Picha',
  'photo_option_gallery'                : 'Chagua kutoka Galari',
  'photo_option_camera'                 : 'Piga Picha',
  'photo_option_reposition'             : 'Weka Upya Picha',
  'photo_option_remove'                 : 'Ondoa Picha',
  'photo_status_added'                  : 'Picha imeongezwa ✓',
  'photo_status_empty'                  : 'Ongeza picha ya kitaalamu',
  'photo_chip_gallery'                  : 'Galari',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Weka Upya',
  'photo_reposition_title'              : 'Weka Upya Picha',
  'photo_reposition_sub'                : 'Kokota picha kubadilisha nafasi',
  'photo_reposition_reset'              : 'Rudisha katikati',
  'photo_reposition_apply'              : 'Tekeleza',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Ujuzi',
  'skills_subtitle'                     : 'Onyesha uwezo wako mkuu',
  'skills_add_btn'                      : 'Ongeza Ujuzi Mpya',
  'skills_snack_max_icons'              : 'Ikoni 10 nyingi zaidi zimechaguliwa.',
  'skills_snack_max_skills'             : 'Ujuzi 15 wa juu umefikiwa.',
  'skills_library_title'                : 'Ujuzi Uliohifadhiwa',
  'skills_library_hint'                 : 'Ujuzi uliowekwa alama umejumuishwa katika CV hii. Uchaguzi wako unahifadhiwa otomatiki.',
  'skills_nav_next'                     : 'Endelea hadi Ziada',
  'skills_wina_header_icon_bar'         : 'Mstari wa Ikoni wa Kichwa',
  'skills_wina_on'                      : 'IMEWASHWA',
  'skills_wina_off'                     : 'IMEZIMWA',
  'skills_wina_bar_on_sub'              : 'Miduara ya ikoni yenye rangi inaonyeshwa kwenye kichwa cha CV.',
  'skills_wina_bar_off_sub'             : 'Mstari wa ikoni umefichwa — nafasi zaidi ya maelezo ya mawasiliano.',
  'skills_wina_palette_hint'            : 'Ikoni zinaonekana kama miduara yenye rangi katika mpangilio wa paleti.',
  'skills_wina_preview_label'           : 'Hakiki',
  'skills_wina_disabled_hint'           : 'Wezesha mstari wa ikoni hapo juu kuchagua ikoni zinazoonyeshwa kwenye kichwa cha CV.',
  'skills_sheet_title_add'              : 'Ongeza Ujuzi',
  'skills_sheet_title_edit'             : 'Hariri Ujuzi',
  'skills_sheet_field_name'             : 'Jina la Ujuzi *',
  'skills_sheet_hint_short'             : 'mf. Flutter, Muundo',
  'skills_sheet_hint_long'              : 'mf. Flutter, Usimamizi wa Miradi',
  'skills_sheet_validator_max'          : 'Herufi {n} nyingi zaidi',
  'skills_sheet_proficiency'            : 'Kiwango cha Ustadi',
  'skills_sheet_beginner'               : 'Mwanzo',
  'skills_sheet_expert'                 : 'Mtaalamu',
  'skills_sheet_btn_save'               : 'Hifadhi Ujuzi',
  'skills_sheet_btn_update'             : 'Sasisha Ujuzi',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Marejeleo ya Kibinafsi',
  'refs_subtitle'                       : 'Watu wanaoweza kukushuhudia kibinafsi',
  'refs_add_btn'                        : 'Ongeza Kumbukumbu Mpya ya Kibinafsi',
  'refs_snack_max_selected'             : 'Marejeleo 4 ya juu yanaweza kuchaguliwa kwa CV.',
  'refs_snack_max_saved'                : 'Marejeleo 10 ya juu yaliyohifadhiwa yamefikiwa.',
  'refs_library_title'                  : 'Marejeleo Yaliyohifadhiwa',
  'refs_library_hint'                   : 'Marejeleo yenye alama yamejumuishwa katika CV hii. Juu ya 4 kwa CV. Uchaguzi wako unahifadhiwa otomatiki.',
  'refs_nav_next'                       : 'Endelea hadi Kurekebisha',
  'refs_sheet_title_add'                : 'Ongeza Kumbukumbu ya Kibinafsi',
  'refs_sheet_title_edit'               : 'Hariri Kumbukumbu ya Kibinafsi',
  'refs_sheet_sub_add'                  : 'Mtu anayeweza kukupendekeza kibinafsi kwa waajiri.',
  'refs_sheet_sub_edit'                 : 'Sasisha maelezo ya kumbukumbu hii hapa chini.',
  'refs_sheet_field_name'               : 'Jina Kamili *',
  'refs_sheet_field_title'              : 'Cheo cha Kazi *',
  'refs_sheet_field_company'            : 'Kampuni (hiari)',
  'refs_sheet_field_email'              : 'Anwani ya Barua Pepe *',
  'refs_sheet_field_phone'              : 'Nambari ya Simu *',
  'refs_sheet_hint_name'                : 'mf. James Smith',
  'refs_sheet_hint_title'               : 'mf. Meneja wa Uhandisi',
  'refs_sheet_hint_company'             : 'mf. Acme Corp',
  'refs_sheet_hint_email'               : 'mf. james@acme.com',
  'refs_sheet_hint_phone'               : 'mf. +255 712 345 678',
  'refs_sheet_validator_email'          : 'Ingiza anwani sahihi ya barua pepe',
  'refs_sheet_btn_save'                 : 'Hifadhi Kumbukumbu ya Kibinafsi',
  'refs_sheet_btn_update'               : 'Sasisha Kumbukumbu ya Kibinafsi',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Uzoefu wa Kazi',
  'exp_subtitle'                        : 'Ongeza historia yako ya kazi',
  'exp_banner_info'                     : 'Hadi majukumu {n} kwa kila nafasi yataonekana kwenye CV. Nafasi 3–6 kawaida zinafaa kwenye kurasa 1–2.',
  'exp_add_btn'                         : 'Ongeza Uzoefu Mpya',
  'exp_snack_max_selected'              : 'Uzoefu 8 wa juu unaweza kuchaguliwa kwa CV.',
  'exp_snack_max_saved'                 : 'Uzoefu 12 wa juu uliohifadhiwa umefikiwa.',
  'exp_library_title'                   : 'Uzoefu Uliohifadhiwa',
  'exp_library_hint'                    : 'Maingizo yenye alama yamejumuishwa katika CV hii peke yake. CV zingine zinaweka uchaguzi wao wa kujitegemea.',
  'exp_nav_next'                        : 'Endelea hadi Elimu',
  'exp_empty_message'                   : 'Bado hakuna uzoefu ulioongezwa',
  'exp_empty_sub'                       : 'Gusa hapo juu kuongeza nafasi yako ya kwanza',
  'exp_card_resp_singular'              : 'jukumu',
  'exp_card_resp_plural'                : 'majukumu',
  'exp_card_resp_tooltip'               : 'Majukumu 8 ya kwanza tu yataonekana kwenye CV',
  'exp_sheet_title_add'                 : 'Ongeza Uzoefu',
  'exp_sheet_title_edit'                : 'Hariri Uzoefu',
  'exp_sheet_field_job_title'           : 'Cheo cha Kazi *',
  'exp_sheet_field_company'             : 'Kampuni *',
  'exp_sheet_field_location'            : 'Mahali',
  'exp_sheet_section_responsibilities'  : 'Majukumu Makuu',
  'exp_sheet_resp_hint_info'            : 'Alama 8 za mstari nyingi zaidi · herufi 200 kila moja',
  'exp_sheet_resp_label'                : 'Jukumu {n}',
  'exp_sheet_resp_hint'                 : 'mf. Aliongoza timu ya wahandisi 5',
  'exp_sheet_resp_add_btn'              : 'Ongeza Jukumu',
  'exp_sheet_resp_max_info'             : 'Majukumu {n} ya juu yamefikiwa',
  'exp_sheet_resp_validator_max'        : 'Herufi 200 nyingi zaidi',
  'exp_sheet_hint_job_title'            : 'mf. Msanidi Mkuu',
  'exp_sheet_hint_location'             : 'mf. Nairobi, Kenya',
  'exp_sheet_btn_save'                  : 'Hifadhi Uzoefu',
  'exp_sheet_btn_update'                : 'Hifadhi Mabadiliko',
  'exp_date_present'                    : 'Sasa / Nafasi ya Sasa',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Elimu',
  'edu_subtitle'                        : 'Ongeza historia yako ya kitaaluma',
  'edu_add_btn'                         : 'Ongeza Elimu Mpya',
  'edu_snack_max_selected'              : 'Maingizo 8 ya juu ya elimu yanaweza kuchaguliwa kwa CV.',
  'edu_snack_max_saved'                 : 'Maingizo 12 ya juu ya elimu yaliyohifadhiwa yamefikiwa.',
  'edu_library_title'                   : 'Elimu Iliyohifadhiwa',
  'edu_library_hint'                    : 'Maingizo yenye alama yamejumuishwa katika CV hii. Uchaguzi wako unahifadhiwa otomatiki.',
  'edu_nav_next'                        : 'Endelea hadi Ujuzi',
  'edu_empty_message'                   : 'Bado hakuna elimu iliyoongezwa',
  'edu_empty_sub'                       : 'Gusa hapo juu kuongeza sifa zako',
  'edu_card_bullet_singular'            : 'alama ya mstari',
  'edu_card_bullet_plural'              : 'alama za mstari',
  'edu_sheet_title_add'                 : 'Ongeza Elimu',
  'edu_sheet_title_edit'                : 'Hariri Elimu',
  'edu_sheet_field_degree'              : 'Shahada / Sifa *',
  'edu_sheet_field_institution'         : 'Taasisi *',
  'edu_sheet_section_key_points'        : 'Mambo Makuu',
  'edu_sheet_key_points_hint_info'      : 'Hiari · alama 1 ya mstari · herufi 100 nyingi zaidi',
  'edu_sheet_point_label'               : 'Pointi {n}',
  'edu_sheet_point_add_btn'             : 'Ongeza Alama ya Mstari',
  'edu_sheet_point_max_info'            : 'Alama {n} za mstari nyingi zaidi zimefikiwa',
  'edu_sheet_point_validator_max'       : 'Herufi {n} nyingi zaidi',
  'edu_sheet_hint_degree'               : 'mf. BSc Sayansi ya Kompyuta',
  'edu_sheet_hint_institution'          : 'mf. Chuo Kikuu cha Dar es Salaam',
  'edu_sheet_hint_bullet'               : 'mf. Darasa la Kwanza',
  'edu_sheet_btn_save'                  : 'Hifadhi Elimu',
  'edu_sheet_btn_update'                : 'Hifadhi Mabadiliko',
  'edu_date_present'                    : 'Sasa / Masomo ya Sasa',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Maelezo ya Ziada',
  'additional_subtitle'                 : 'Vyeti, lugha na zaidi',
  'additional_cert_section_title'       : 'Vyeti',
  'additional_cert_counter'             : '{sel}/{total} vilichaguliwa · juu {max}',
  'additional_cert_hide'                : 'Ficha',
  'additional_cert_show'                : 'Onyesha',
  'additional_cert_add_btn'             : 'Ongeza',
  'additional_cert_snack_max'           : 'Maingizo {n} ya juu ya vyeti yamefikiwa.',
  'additional_cert_hint'                : 'Maingizo yenye alama yamejumuishwa katika CV hii. Uchaguzi wako unahifadhiwa otomatiki.',
  'additional_cert_empty'               : 'Bado hakuna vyeti vilivyoongezwa',
  'additional_lang_section_title'       : 'Lugha',
  'additional_lang_add_hint'            : 'mf. Kiingereza',
  'additional_lang_snack_max'           : 'Maingizo {n} ya juu ya lugha yamefikiwa.',
  'additional_lang_empty'               : 'Bado hakuna lugha zilizoongezwa',
  'additional_hobby_section_title'      : 'Mambo ya Kupendeza',
  'additional_hobby_add_hint'           : 'mf. Upigaji Picha',
  'additional_hobby_snack_max'          : 'Maingizo {n} ya juu ya burudani yamefikiwa.',
  'additional_hobby_empty'              : 'Bado hakuna burudani zilizoongezwa',
  'additional_section_hint'             : 'Maingizo yenye alama yamejumuishwa katika CV hii. Uchaguzi wako unahifadhiwa otomatiki.',
  'additional_nav_next'                 : 'Endelea hadi Washauri',
  'cert_sheet_title_add'                : 'Ongeza Cheti',
  'cert_sheet_title_edit'               : 'Hariri Cheti',
  'cert_sheet_sub'                      : 'Ongeza sifa, cheti au hati ya kitaalamu.',
  'cert_sheet_field_name'               : 'Jina la Cheti *',
  'cert_sheet_field_issued_by'          : 'Imetolewa Na (hiari)',
  'cert_sheet_field_short_desc'         : 'Maelezo Mafupi (hiari)',
  'cert_sheet_hint_name'                : 'mf. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'mf. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'mf. Ilipatikana 2024',
  'cert_sheet_btn_save'                 : 'Hifadhi Cheti',
  'cert_sheet_btn_update'               : 'Sasisha Cheti',
  'simple_sheet_title_add_language'     : 'Ongeza Lugha',
  'simple_sheet_title_edit_language'    : 'Hariri Lugha',
  'simple_sheet_title_add_hobby'        : 'Ongeza Burudani',
  'simple_sheet_title_edit_hobby'       : 'Hariri Burudani',
  'simple_sheet_btn_save'               : 'Hifadhi',
  'simple_sheet_btn_update'             : 'Sasisha',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Mawasiliano',
  'pdf_section_about_me'                : 'Kuhusu Mimi',
  'pdf_section_summary'                 : 'Muhtasari',
  'pdf_section_summary_short'           : 'Muhtasari',
  'pdf_section_profile'                 : 'Wasifu',
  'pdf_section_experience'              : 'Uzoefu',
  'pdf_section_experience_short'        : 'Uzoefu',
  'pdf_section_education'               : 'Elimu',
  'pdf_section_skills'                  : 'Ujuzi',
  'pdf_section_languages'               : 'Lugha',
  'pdf_label_email'                     : 'Barua Pepe',
  'pdf_label_phone'                     : 'Simu',
  'pdf_label_location'                  : 'Mahali',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Kikomo cha CV Kimefikiwa',
  'limit_dialog_body'                   : 'Umefika kiwango cha juu cha CV 30. Tafadhali futa CV iliyopo kabla ya kuunda mpya.',
  'limit_dialog_go_to_my_cvs'           : 'Nenda kwa CV Zangu',
  'limit_dialog_cancel'                 : 'Ghairi',
  'refs_count_summary'                  : '{checked}/{maxChecked} zilizochaguliwa · {saved}/{maxSaved} zilizohifadhiwa',
  'refs_selected_badge'                 : '{n} zilizochaguliwa',
  'refs_empty_message'                  : 'Hakuna marejeo yaliyohifadhiwa bado',
  'refs_empty_sub'                      : 'Gusa hapo juu kuongeza kumbukumbu ya kibinafsi',
};