// lib/language_keys/lang_ru_russian.dart
//
// Russian (Россия) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> ruRussian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Языки не найдены',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Пропустить',
  'onboarding_next'                     : 'Далее',
  'onboarding_get_started'              : 'Начать',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Добро пожаловать',
  'ob1_title'                           : 'Создайте резюме,\nкоторое открывает двери',
  'ob1_body'                            : 'Выделитесь среди сотен соискателей. Создайте профессиональное резюме за считанные минуты — без навыков дизайна.',
  'ob1_pill_label'                      : 'Профессиональный конструктор резюме',
  'ob1_chip_templates'                  : '24+ шаблонов',
  'ob1_chip_pdf'                        : 'Экспорт в PDF',
  'ob1_chip_free'                       : 'Бесплатно',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Шаблоны',
  'ob2_title'                           : 'Любая отрасль.\nЛюбые амбиции.',
  'ob2_body'                            : 'От строгих корпоративных макетов до смелых творческих дизайнов — шаблон, который расскажет вашу историю.',
  'ob2_tap_hint'                        : 'Нажмите на шаблон для предпросмотра',
  'ob2_tpl_executive'                   : 'Руководитель',
  'ob2_tpl_vibrant'                     : 'Яркий',
  'ob2_tpl_nordic'                      : 'Скандинавский',
  'ob2_tpl_tech_dark'                   : 'Тёмный технический',
  'ob2_tpl_luxury'                      : 'Люкс',
  'ob2_tag_corporate'                   : 'Корпоративный',
  'ob2_tag_creative'                    : 'Творческий',
  'ob2_tag_minimal'                     : 'Минималистичный',
  'ob2_tag_modern'                      : 'Современный',
  'ob2_tag_premium'                     : 'Премиум',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Умная раскладка',
  'ob3_title'                           : 'Ваше резюме.\nИдеально структурировано.',
  'ob3_body'                            : 'Умная раскладка переставляет разделы для максимального эффекта — помещая самый сильный контент туда, куда рекрутеры смотрят в первую очередь.',
  'ob3_badge_smart_layout'              : 'Умная раскладка',
  'ob3_badge_cv_ready'                  : 'Резюме готово!',
  'ob3_step1_label'                     : 'Выберите шаблон',
  'ob3_step1_desc'                      : 'Выбирайте из 24+ потрясающих дизайнов.',
  'ob3_step2_label'                     : 'Заполните данные',
  'ob3_step2_desc'                      : 'Удобные поля для всех разделов.',
  'ob3_step3_label'                     : 'Умная раскладка',
  'ob3_step3_desc'                      : 'Одно нажатие — идеальное резюме.',
  'ob3_step4_label'                     : 'Экспорт в PDF',
  'ob3_step4_desc'                      : 'Идеальный PDF готов к отправке.',
  'ob3_section_work'                    : 'Опыт работы',
  'ob3_section_education'               : 'Образование',
  'ob3_section_skills'                  : 'Навыки',
  'ob3_section_references'              : 'Рекомендации',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Готово к работе',
  'ob4_title'                           : 'Почему лучшие кандидаты\nвыбирают CV Builder',
  'ob4_visual_headline'                 : 'Вы готовы!',
  'ob4_visual_subline'                  : 'Всё, что нужно, чтобы получить работу.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Шаблонов',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Макс. резюме',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Экспорт',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Приватно',
  'ob4_hl1_title'                       : 'Приватно и безопасно',
  'ob4_hl1_sub'                         : 'Данные хранятся на вашем устройстве.',
  'ob4_hl2_title'                       : 'Автосохранение',
  'ob4_hl2_sub'                         : 'Каждое нажатие сохраняется мгновенно.',
  'ob4_hl3_title'                       : 'До 30 резюме',
  'ob4_hl3_sub'                         : 'Уникальное резюме для каждой должности.',
  'ob4_hl4_title'                       : 'Поделиться одним касанием',
  'ob4_hl4_sub'                         : 'Отправьте PDF, не покидая приложение.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Выделитесь из толпы',
  'home_hero_title'                     : 'Создайте своё\nпрофессиональное резюме',
  'home_hero_sub'                       : 'Создайте впечатляющее резюме\nза считанные минуты',
  'home_hero_cta'                       : 'Начать создание',
  'home_premium_soon'                   : 'Обновление до Pro скоро!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Сначала новые',
  'history_sort_alphabetical'           : 'А–Я',
  'history_sort_last_edited'            : 'По дате редактирования',
  'history_sort_by_template'            : 'По шаблону',
  'history_sort_sheet_title'            : 'Сортировать по',
  'history_sort_alphabetical_full'      : 'По алфавиту (А–Я)',
  'history_premium_soon'                : 'Обновление до Pro скоро!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Настройки',
  'settings_section_preferences'        : 'Предпочтения',
  'settings_section_support'            : 'Поддержка',
  'settings_section_legal'              : 'Юридическая информация',
  'settings_section_about'              : 'О приложении',
  'settings_language_tile_title'        : 'Язык',
  'settings_dark_mode_title'            : 'Тёмный режим',
  'settings_dark_mode_on'               : 'Тёмная тема включена',
  'settings_dark_mode_off'              : 'Светлая тема включена',
  'settings_help_faq_title'             : 'Помощь и FAQ',
  'settings_help_faq_sub'               : 'Ответы на частые вопросы',
  'settings_contact_support_title'      : 'Связаться с поддержкой',
  'settings_rate_app_title'             : 'Оценить приложение',
  'settings_rate_app_sub'               : 'Нравится приложение? Оставьте отзыв!',
  'settings_privacy_policy_title'       : 'Политика конфиденциальности',
  'settings_terms_title'                : 'Условия использования',
  'settings_app_version_title'          : 'Версия приложения',
  'settings_email_error'                : 'Не удалось открыть почтовое приложение. Напишите на cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Предпросмотр резюме',
  'preview_header_sub'                  : 'Готово к экспорту',
  'preview_generating'                  : 'Создание резюме...',
  'preview_failed_title'                : 'Ошибка предпросмотра',
  'preview_failed_error'                : 'Ошибка: {error}',
  'preview_go_back'                     : 'Назад',
  'preview_no_data'                     : 'Нет доступных данных',
  'preview_btn_print'                   : 'Печать',
  'preview_btn_download'                : 'Скачать и поделиться',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Помощь и FAQ',
  'faq_category_all'                    : 'Все',
  'faq_empty'                           : 'Результаты не найдены',
  'faq_contact_headline'                : 'Нужна дополнительная помощь?',
  'faq_contact_sub'                     : 'Наша команда всегда готова помочь.',
  'faq_contact_btn'                     : 'Контакты',
  'faq_email_error'                     : 'Не удалось открыть почтовое приложение. Напишите на cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Начало работы',
  'faq_cat_templates'                   : 'Шаблоны',
  'faq_cat_editing'                     : 'Редактирование',
  'faq_cat_exporting'                   : 'Экспорт',
  'faq_cat_data_privacy'                : 'Данные и конфиденциальность',
  'faq_cat_troubleshooting'             : 'Устранение неполадок',
  'faq_q1'  : 'Как создать первое резюме?',
  'faq_a1'  : 'Нажмите кнопку "+" на главном экране, чтобы создать новое резюме. Выберите подходящий шаблон, затем заполните личные данные, опыт работы, образование и навыки шаг за шагом. Прогресс сохраняется автоматически.',
  'faq_q2'  : 'Можно ли создать несколько резюме?',
  'faq_a2'  : 'Да! Вы можете создать несколько резюме для разных должностей или отраслей. Каждое резюме сохраняется отдельно, чтобы вы могли адаптировать их под конкретные вакансии.',
  'faq_q3'  : 'Как изменить шаблон резюме?',
  'faq_a3'  : 'Откройте резюме, нажмите на иконку шаблона вверху экрана и просмотрите доступные шаблоны. Нажмите на любой шаблон для предпросмотра с вашими данными. Подтвердите применение.',
  'faq_q4'  : 'Есть ли бесплатные и платные шаблоны?',
  'faq_a4'  : 'Да. Выборка профессиональных шаблонов доступна бесплатно. Премиум-шаблоны с расширенными дизайнами и цветовыми палитрами доступны через разовую покупку или подписку.',
  'faq_q5'  : 'Как добавить или удалить разделы?',
  'faq_a5'  : 'В редакторе резюме прокрутите вниз и нажмите "Добавить раздел", чтобы включить дополнительные разделы, такие как Языки, Сертификаты или Волонтёрство. Чтобы удалить раздел, нажмите на его заголовок и выберите "Удалить".',
  'faq_q6'  : 'Как изменить порядок разделов?',
  'faq_a6'  : 'Удерживайте маркер перетаскивания (≡) рядом с заголовком раздела и перетащите его в нужное место. Изменения сохраняются автоматически.',
  'faq_q7'  : 'Как экспортировать резюме в PDF?',
  'faq_a7'  : 'Откройте резюме и нажмите кнопку экспорта (иконка поделиться) в правом верхнем углу. Выберите "Экспортировать как PDF". Затем вы можете сохранить его на устройстве, поделиться по email, WhatsApp или загрузить на сайты поиска работы.',
  'faq_q8'  : 'Какие форматы файлов поддерживаются?',
  'faq_a8'  : 'В настоящее время приложение поддерживает экспорт резюме в формате высококачественного PDF. Дополнительные форматы могут быть добавлены в будущих обновлениях.',
  'faq_q9'  : 'Где хранятся данные моего резюме?',
  'faq_a9'  : 'Все данные резюме хранятся локально на вашем устройстве. Мы не загружаем вашу личную информацию на наши серверы. Это означает, что ваши данные остаются приватными и доступны без интернета.',
  'faq_q10' : 'Как создать резервную копию резюме?',
  'faq_a10' : 'Ваши резюме включены в стандартное резервное копирование устройства (Google Drive на Android, iCloud на iOS), если резервное копирование включено в настройках устройства. Вы также можете экспортировать резюме в PDF для сохранения копии.',
  'faq_q11' : 'Приложение работает медленно. Что делать?',
  'faq_a11' : 'Попробуйте закрыть и снова открыть приложение. Если проблема сохраняется, перезагрузите устройство. Убедитесь, что у вас установлена последняя версия приложения из Play Store / App Store.',
  'faq_q12' : 'Резюме не экспортируется правильно. Что делать?',
  'faq_a12' : 'Убедитесь, что на устройстве достаточно места для хранения. Попробуйте уменьшить большие изображения в резюме. Если проблема продолжается, обратитесь в нашу службу поддержки.',
  'faq_q13' : 'Я забыл сохранить — моя работа потеряна?',
  'faq_a13' : 'Нет! Приложение непрерывно сохраняет ваш прогресс во время редактирования.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Ваша карьера, доведённая до совершенства',
  'header_tooltip_back'                 : 'Назад',
  'header_tooltip_my_cvs'               : 'Мои резюме',
  'header_tooltip_settings'             : 'Настройки',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Мои резюме',
  'saved_count_single'                  : '{n} документ',
  'saved_count_plural'                  : '{n} документов',
  'saved_limit_reached'                 : 'Достигнут лимит',
  'saved_footer_count'                  : '{n} / 30 резюме',
  'saved_filter_all'                    : 'Все',
  'saved_filter_draft'                  : 'Черновик',
  'saved_filter_complete'               : 'Завершено',
  'saved_status_complete'               : 'Завершено',
  'saved_status_saved'                  : 'Сохранено',
  'saved_status_draft'                  : 'Черновик',
  'saved_empty_title'                   : 'Резюме пока нет',
  'saved_empty_sub'                     : 'Начните создавать первое резюме выше',
  'saved_search_empty_title'            : 'Результаты не найдены',
  'saved_search_empty_sub'              : 'Попробуйте другой поисковый запрос',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Цветовая схема',
  'custom_font_settings_title'          : 'Настройки шрифта',
  'custom_font_family_label'            : 'Семейство шрифтов',
  'custom_font_size_label'              : 'Размер шрифта: ',
  'custom_current_template_title'       : 'Текущий шаблон',
  'custom_change_template_btn'          : 'Сменить шаблон',
  'custom_tpl_modern'                   : 'Современный',
  'custom_tpl_classic'                  : 'Классический',
  'custom_tpl_professional'             : 'Профессиональный',
  'custom_tpl_creative'                 : 'Творческий',
  'custom_tpl_minimal'                  : 'Минималистичный',
  'custom_tpl_modern_desc'              : 'Чистый и современный дизайн',
  'custom_tpl_classic_desc'             : 'Традиционный профессиональный макет',
  'custom_tpl_professional_desc'        : 'Деловой шаблон',
  'custom_tpl_creative_desc'            : 'Выделитесь уникальным дизайном',
  'custom_tpl_minimal_desc'             : 'Простой и элегантный стиль',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Выберите шаблон',
  'swipe_photo_badge'                   : 'Фото',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Руководитель',
  'tpl_nordic_name'                     : 'Скандинавский',
  'tpl_vibrant_name'                    : 'Яркий',
  'tpl_tech_dark_name'                  : 'Тёмный технический',
  'tpl_luxury_name'                     : 'Люкс',
  'tpl_executive_tag'                   : 'Самый популярный',
  'tpl_nordic_tag'                      : 'Чистый',
  'tpl_vibrant_tag'                     : 'Творческий',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Элитный',
  'tpl_executive_desc'                  : 'Жирный и авторитетный для старших должностей',
  'tpl_nordic_desc'                     : 'Минималистичная чёткость, которой доверяют ведущие компании',
  'tpl_vibrant_desc'                    : 'Выделитесь с энергией и цветом',
  'tpl_tech_dark_desc'                  : 'Терминальная эстетика для разработчиков',
  'tpl_luxury_desc'                     : 'Золотые акценты и престиж на чёрном фоне',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Шаблон',
  'detail_step_personal'                : 'Личные данные',
  'detail_step_experience'              : 'Опыт работы',
  'detail_step_education'               : 'Образование',
  'detail_step_skills'                  : 'Навыки',
  'detail_step_additional'              : 'Дополнительно',
  'detail_step_references'              : 'Рекомендации',
  'detail_step_customize'               : 'Настройка',
  'detail_banner_heading'               : 'Почти готово!',
  'detail_banner_btn'                   : 'Продолжить',
  'detail_banner_completion_label'      : 'Завершённость',
  'detail_stat_created_label'           : 'Создано',
  'detail_stat_steps_label'             : 'Шагов выполнено',
  'detail_section_template_style'       : 'Стиль шаблона',
  'detail_section_steps'                : 'Шаги',
  'detail_steps_counter'                : '{done} из {total} выполнено',
  'detail_step_sub'                     : 'Шаг {n} из {total}',
  'detail_section_activity'             : 'Активность',
  'detail_activity_created'             : 'Создано',
  'detail_activity_last_edited'         : 'Последнее редактирование',
  'detail_activity_template'            : 'Шаблон',
  'detail_btn_continue_editing'         : 'Продолжить редактирование',
  'detail_btn_edit_cv'                  : 'Редактировать резюме',
  'detail_option_rename'                : 'Переименовать резюме',
  'detail_option_delete'                : 'Удалить резюме',
  'detail_rename_title'                 : 'Переименовать резюме',
  'detail_rename_hint'                  : 'напр. Резюме инженера-программиста',
  'detail_rename_error_empty'           : 'Название не может быть пустым',
  'detail_rename_btn_cancel'            : 'Отмена',
  'detail_rename_btn_save'              : 'Сохранить',
  'detail_rename_snackbar'              : 'Переименовано в "{name}"',
  'detail_delete_title'                 : 'Удалить резюме?',
  'detail_delete_body'                  : 'Это навсегда удалит "{name}". Действие нельзя отменить.',
  'detail_delete_btn_cancel'            : 'Отмена',
  'detail_delete_btn_confirm'           : 'Удалить',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Завершено',
  'detail_check_tile_incomplete'        : 'Ещё не заполнено',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Выберите шаблон',
  'chooser_subtitle'                    : 'Листайте для просмотра  ·  Нажмите для выбора  ·  Удерживайте для предпросмотра',
  'chooser_card_hold_hint'              : 'Удерживайте для предпросмотра',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Выбрано',
  'chooser_modal_heading'               : 'Назовите резюме',
  'chooser_modal_sub'                   : 'Дайте ему название, чтобы легко найти в разделах "Мои резюме" и "История".',
  'chooser_modal_field_label'           : 'Название резюме',
  'chooser_modal_save_btn'              : 'Сохранить и начать создание',
  'chooser_modal_divider'               : 'или продолжить с существующим резюме',
  'chooser_nav_selected_sub'            : 'Выбранный шаблон',
  'chooser_nav_cta'                     : 'Сохранить и продолжить',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Достигнуто максимальное количество записей',
  'editor_show_hide'                    : 'Показать/Скрыть',
  'editor_editing_badge'                : 'Редактирование',
  'editor_field_required'               : 'Обязательное поле',
  'editor_tooltip_edit'                 : 'Редактировать',
  'editor_tooltip_delete'               : 'Удалить',
  'editor_date_start'                   : 'Дата начала *',
  'editor_date_end'                     : 'Дата окончания *',
  'editor_date_tap_hint'                : 'Нажмите для выбора',
  'editor_date_dialog_title'            : 'Выберите месяц и год',
  'editor_date_confirm'                 : 'Подтвердить',
  'editor_panel_hide'                   : 'Скрыть',
  'editor_panel_show'                   : 'Показать',
  'editor_validator_max_chars'          : 'Максимум {n} символов',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Создайте резюме',
  'editor_header_step_sub'              : 'Шаг {current} из {total} · {label}',
  'editor_step_template'                : 'Шаблон',
  'editor_step_personal'                : 'Личные данные',
  'editor_step_experience'              : 'Опыт работы',
  'editor_step_education'               : 'Образование',
  'editor_step_skills'                  : 'Навыки',
  'editor_step_additional'              : 'Дополнительно',
  'editor_step_references'              : 'Рекомендации',
  'editor_step_customize'               : 'Настройка',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Настройка',
  'customize_subtitle'                  : 'Сделайте резюме по-настоящему своим',
  'customize_smart_layout_btn'          : 'Умная раскладка',
  'customize_back_to_top'               : 'Наверх',
  'customize_done_title'                : 'Всё готово!',
  'customize_done_sub'                  : 'Нажмите "Предпросмотр резюме" ниже, чтобы увидеть готовое резюме',
  'customize_preview_btn'               : 'Предпросмотр резюме',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Цветовая схема',
  'color_black'                         : 'Чёрный',
  'color_blue'                          : 'Синий',
  'color_nordic_blue'                   : 'Скандинавский синий',
  'color_indigo'                        : 'Индиго',
  'color_teal'                          : 'Сине-зелёный',
  'color_green'                         : 'Зелёный',
  'color_purple'                        : 'Фиолетовый',
  'color_orange'                        : 'Оранжевый',
  'color_red'                           : 'Красный',
  'color_executive_gold'                : 'Золото руководителя',
  'color_vibrant_coral'                 : 'Яркий коралловый',
  'color_white'                         : 'Белый',
  'color_white_bg'                      : 'Белый фон',
  'color_maroon'                        : 'Тёмно-красный',
  'color_brutalist_yellow'              : 'Брутальный жёлтый',
  'color_neon_blue'                     : 'Неоновый синий',
  'color_blueprint_navy'                : 'Тёмно-синий',
  'color_light_grey'                    : 'Светло-серый',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Семейство шрифтов',
  'customize_font_picker_title'         : 'Выберите шрифт',
  'customize_font_picker_sub'           : 'Каждый шрифт отображается в своём стиле',
  'customize_font_preview_sample'       : 'Быстрая коричневая лиса',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Размер шрифта',
  'customize_font_size_label'           : 'Размер текста',
  'customize_font_size_value'           : '{n} пт',
  'customize_font_size_min'             : '10 пт',
  'customize_font_size_max'             : '16 пт',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Размер изображения',
  'customize_image_size_label'          : 'Размер изображения',
  'customize_image_size_value'          : '{n} пкс',
  'customize_image_size_min'            : '10 пкс',
  'customize_image_size_max'            : '16 пкс',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Предпросмотр в реальном времени',
  'preview_page_count_singular'         : '1 страница',
  'preview_page_count_plural'           : '{n} страниц',
  'preview_page_of'                     : 'Страница {page} из {total}',
  'preview_live_hint'                   : 'Изменения применяются мгновенно',
  'preview_template_unregistered'       : 'Ещё не зарегистрировано в customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Подготовка резюме…',
  'preview_bar_print'                   : 'Печать',
  'preview_bar_save_pdf'                : 'Сохранить как PDF',
  'preview_bar_share'                   : 'Поделиться',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Предпросмотр резюме',
  'preview_screen_sub'                  : '{n} {unit} · точно как при печати',
  'preview_page_singular'               : 'страница',
  'preview_page_plural'                 : 'страниц',
  'preview_pdf_filename'                : 'Моё_резюме',
  'preview_share_subject'               : 'Моё резюме',
  'preview_snack_print_failed'          : 'Ошибка печати: {e}',
  'preview_snack_saved'                 : 'Резюме сохранено в Загрузки ✓',
  'preview_snack_export_failed'         : 'Ошибка экспорта: {e}',
  'preview_snack_share_failed'          : 'Ошибка отправки: {e}',
  'preview_template_not_registered'     : 'Шаблон не зарегистрирован',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Закрыть предпросмотр',
  'preview_modal_hint_photo'            : 'Поддерживает фото профиля  ·  Нажмите на карточку для выбора',
  'preview_modal_hint_no_photo'         : 'Нажмите на карточку шаблона для выбора',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Моё резюме',
  'time_just_now'                       : 'Только что',
  'time_minutes_ago'                    : '{n} мин. назад',
  'time_hours_ago'                      : '{n} ч. назад',
  'time_yesterday'                      : 'Вчера',
  'time_days_ago'                       : '{n} дн. назад',
  'time_one_week_ago'                   : '1 неделю назад',
  'time_weeks_ago'                      : '{n} нед. назад',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Элегантный',
  'tpl_tag_classic'                     : 'Классический',
  'tpl_tag_minimal'                     : 'Минималистичный',
  'tpl_tag_creative'                    : 'Творческий',
  'tpl_tag_bold'                        : 'Жирный',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Градиент',
  'tpl_gradient_desc'                   : 'Переход от морской волны к фиолетовому',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Редакционный',
  'tpl_editorial_desc'                  : 'Стиль журнала: красный и кремовый',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Мягкий пастель',
  'tpl_pastel_soft_desc'                : 'Лавандовая боковая панель, мягкие карточки',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Брутализм',
  'tpl_brutalist_desc'                  : 'Сетка, жирные рамки и жёлтый',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Изумрудный',
  'tpl_emerald_desc'                    : 'Тёмно-зелёный с временной шкалой',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Инфографика',
  'tpl_infographic_desc'                : 'Тёмный фон с кольцевыми диаграммами',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Ар-деко',
  'tpl_art_deco_desc'                   : 'Геометрическая золотая роскошь 1920-х',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Тёмный',
  'tpl_wina_dark_desc'                  : 'Тёмная инфографика с кольцами',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Рио Оранжевый',
  'tpl_rio_orange_desc'                 : 'Тёмная боковая панель с оранжевым акцентом',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Летний',
  'tpl_summer_desc'                     : 'Чистый минимализм, мягкие серые тона',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Тёплые бежевые элегантные тона',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Строгая чёрно-белая классика',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Классический макет, совместимый с ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Тёмный',
  'tpl_tony_dark_desc'                  : 'Тёмный оранжевый стиль инфографики',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Мода',
  'tpl_fashion_desc'                    : 'Технический чертёж на сетке',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Архивист',
  'tpl_archivist_desc'                  : 'Классический двухколоночный макет с метками',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Дипломат',
  'tpl_diplomat_desc'                   : 'Затенённые заголовки с ромбовидными разделителями',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Меридиан',
  'tpl_meridian_desc'                   : 'Центрированные заголовки, акцентные компании',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Моментум',
  'tpl_momentum_desc'                   : 'Жирное имя, точки временной шкалы и достижения',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Личные данные',
  'personal_subtitle'                   : 'Расскажите работодателям о себе',
  'personal_profile_counter'            : '{n}/{max} профилей',
  'personal_info_banner'                : 'Сохраните до 5 профилей и выберите один для каждого резюме. Выбор запоминается для каждого резюме отдельно.',
  'personal_snack_max'                  : 'Достигнуто максимальное количество профилей: {n}.',
  'personal_add_btn'                    : 'Добавить новый профиль',
  'personal_library_title'              : 'Сохранённые профили',
  'personal_selected_one'               : '1 выбран',
  'personal_selected_none'              : 'ничего не выбрано',
  'personal_library_hint'               : 'Нажмите на карточку, чтобы выбрать её только для этого резюме. Другие резюме сохраняют свои независимые выборы.',
  'personal_empty_message'              : 'Профили пока не сохранены',
  'personal_empty_sub'                  : 'Нажмите выше, чтобы добавить личные данные',
  'personal_nav_next'                   : 'Сохранить и продолжить',
  'personal_card_active_badge'          : 'Активно для этого резюме',
  'personal_sheet_title_add'            : 'Новый профиль',
  'personal_sheet_title_edit'           : 'Редактировать профиль',
  'personal_sheet_brutalist_badge'      : 'БРУТАЛИЗМ',
  'personal_sheet_brutalist_banner'     : 'Шаблон Brutalist имеет компактные контактные поля. Лучше отображаются короткие значения (напр., только город).',
  'personal_section_photo'              : 'Фото профиля',
  'personal_section_basic'              : 'Основные данные',
  'personal_section_contact'            : 'Контакты',
  'personal_section_online'             : 'Онлайн-присутствие',
  'personal_section_summary'            : 'Профессиональное резюме',
  'personal_field_first_name'           : 'Имя *',
  'personal_field_last_name'            : 'Фамилия',
  'personal_field_job_title'            : 'Должность *',
  'personal_field_email'                : 'Адрес электронной почты *',
  'personal_field_phone'                : 'Номер телефона *',
  'personal_field_location'             : 'Местоположение',
  'personal_field_location_brut'        : 'Местоположение (только город)',
  'personal_field_website'              : 'Сайт / Портфолио',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'напр. Анна',
  'personal_hint_last_name'             : 'напр. Иванова',
  'personal_hint_job_title'             : 'напр. Старший инженер',
  'personal_hint_email'                 : 'напр. anna@example.com',
  'personal_hint_phone'                 : 'напр. +7 900 123-45-67',
  'personal_hint_location'              : 'напр. Москва, Россия',
  'personal_hint_location_brut'         : 'напр. Москва',
  'personal_hint_website'               : 'напр. github.com/annaivanova',
  'personal_hint_website_brut'          : 'напр. github.com/anna',
  'personal_hint_linkedin'              : 'напр. linkedin.com/in/annaivanova',
  'personal_hint_linkedin_brut'         : 'напр. linkedin.com/in/anna',
  'personal_summary_hint_label'         : 'Будьте краткими — это отображается вверху резюме.',
  'personal_hint_summary'               : 'Краткое резюме из 2–3 предложений о вашем опыте и целях...',
  'personal_validator_email'            : 'Введите корректный адрес электронной почты',
  'personal_field_char_limit_tooltip'   : 'Достигнут лимит символов',
  'personal_sheet_btn_save'             : 'Сохранить профиль',
  'personal_sheet_btn_update'           : 'Сохранить изменения',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Выберите фото',
  'photo_option_gallery'                : 'Выбрать из галереи',
  'photo_option_camera'                 : 'Сделать фото',
  'photo_option_reposition'             : 'Переместить фото',
  'photo_option_remove'                 : 'Удалить фото',
  'photo_status_added'                  : 'Фото добавлено ✓',
  'photo_status_empty'                  : 'Добавьте профессиональный портрет',
  'photo_chip_gallery'                  : 'Галерея',
  'photo_chip_camera'                   : 'Камера',
  'photo_chip_reposition'               : 'Переместить',
  'photo_reposition_title'              : 'Переместить фото',
  'photo_reposition_sub'                : 'Перетащите фото для настройки положения',
  'photo_reposition_reset'              : 'Сбросить по центру',
  'photo_reposition_apply'              : 'Применить',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Навыки',
  'skills_subtitle'                     : 'Выделите ваши ключевые способности',
  'skills_add_btn'                      : 'Добавить навык',
  'skills_snack_max_icons'              : 'Выбрано максимум 10 иконок.',
  'skills_snack_max_skills'             : 'Достигнут максимум: 15 навыков.',
  'skills_library_title'                : 'Сохранённые навыки',
  'skills_library_hint'                 : 'Отмеченные навыки включены в это резюме. Выборы сохраняются автоматически.',
  'skills_nav_next'                     : 'Перейти к разделу "Дополнительно"',
  'skills_wina_header_icon_bar'         : 'Панель иконок в шапке',
  'skills_wina_on'                      : 'ВКЛ',
  'skills_wina_off'                     : 'ВЫКЛ',
  'skills_wina_bar_on_sub'              : 'Цветные иконки отображаются в шапке резюме.',
  'skills_wina_bar_off_sub'             : 'Панель иконок скрыта — больше места для контактов.',
  'skills_wina_palette_hint'            : 'Иконки отображаются как цветные круги в порядке палитры.',
  'skills_wina_preview_label'           : 'Предпросмотр',
  'skills_wina_disabled_hint'           : 'Включите панель иконок выше, чтобы выбрать, какие иконки отображаются в шапке резюме.',
  'skills_sheet_title_add'              : 'Добавить навык',
  'skills_sheet_title_edit'             : 'Редактировать навык',
  'skills_sheet_field_name'             : 'Название навыка *',
  'skills_sheet_hint_short'             : 'напр. Flutter, Дизайн',
  'skills_sheet_hint_long'              : 'напр. Flutter, Управление проектами',
  'skills_sheet_validator_max'          : 'Максимум {n} символов',
  'skills_sheet_proficiency'            : 'Уровень владения',
  'skills_sheet_beginner'               : 'Начинающий',
  'skills_sheet_expert'                 : 'Эксперт',
  'skills_sheet_btn_save'               : 'Сохранить навык',
  'skills_sheet_btn_update'             : 'Обновить навык',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Личные рекомендации',
  'refs_subtitle'                       : 'Люди, которые могут лично поручиться за вас',
  'refs_add_btn'                        : 'Добавить личную рекомендацию',
  'refs_snack_max_selected'             : 'Для резюме можно выбрать не более 4 рекомендаций.',
  'refs_snack_max_saved'                : 'Достигнуто максимальное количество сохранённых рекомендаций: 10.',
  'refs_library_title'                  : 'Сохранённые рекомендации',
  'refs_library_hint'                   : 'Отмеченные рекомендации включены в это резюме. Макс. 4 на резюме. Выборы сохраняются автоматически.',
  'refs_nav_next'                       : 'Перейти к настройке',
  'refs_sheet_title_add'                : 'Добавить личную рекомендацию',
  'refs_sheet_title_edit'               : 'Редактировать личную рекомендацию',
  'refs_sheet_sub_add'                  : 'Тот, кто может лично рекомендовать вас работодателям.',
  'refs_sheet_sub_edit'                 : 'Обновите данные этой рекомендации ниже.',
  'refs_sheet_field_name'               : 'Полное имя *',
  'refs_sheet_field_title'              : 'Должность *',
  'refs_sheet_field_company'            : 'Компания (необязательно)',
  'refs_sheet_field_email'              : 'Адрес электронной почты *',
  'refs_sheet_field_phone'              : 'Номер телефона *',
  'refs_sheet_hint_name'                : 'напр. Иван Иванов',
  'refs_sheet_hint_title'               : 'напр. Технический директор',
  'refs_sheet_hint_company'             : 'напр. Acme Corp',
  'refs_sheet_hint_email'               : 'напр. ivan@acme.ru',
  'refs_sheet_hint_phone'               : 'напр. +7 900 123-45-67',
  'refs_sheet_validator_email'          : 'Введите корректный адрес электронной почты',
  'refs_sheet_btn_save'                 : 'Сохранить рекомендацию',
  'refs_sheet_btn_update'               : 'Обновить рекомендацию',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Опыт работы',
  'exp_subtitle'                        : 'Добавьте историю вашей работы',
  'exp_banner_info'                     : 'На резюме будет отображаться до {n} обязанностей для каждой должности. 3–6 должностей обычно помещаются на 1–2 страницах.',
  'exp_add_btn'                         : 'Добавить опыт работы',
  'exp_snack_max_selected'              : 'Для резюме можно выбрать не более 8 записей опыта работы.',
  'exp_snack_max_saved'                 : 'Достигнуто максимальное количество сохранённых записей: 12.',
  'exp_library_title'                   : 'Сохранённый опыт работы',
  'exp_library_hint'                    : 'Отмеченные записи включены только в это резюме. Другие резюме сохраняют свои независимые выборы.',
  'exp_nav_next'                        : 'Перейти к образованию',
  'exp_empty_message'                   : 'Опыт работы ещё не добавлен',
  'exp_empty_sub'                       : 'Нажмите выше, чтобы добавить первую должность',
  'exp_card_resp_singular'              : 'обязанность',
  'exp_card_resp_plural'                : 'обязанностей',
  'exp_card_resp_tooltip'               : 'На резюме отобразятся только первые 8 обязанностей',
  'exp_sheet_title_add'                 : 'Добавить опыт работы',
  'exp_sheet_title_edit'                : 'Редактировать опыт работы',
  'exp_sheet_field_job_title'           : 'Должность *',
  'exp_sheet_field_company'             : 'Компания *',
  'exp_sheet_field_location'            : 'Местоположение',
  'exp_sheet_section_responsibilities'  : 'Ключевые обязанности',
  'exp_sheet_resp_hint_info'            : 'Макс. 8 пунктов · 200 символов каждый',
  'exp_sheet_resp_label'                : 'Обязанность {n}',
  'exp_sheet_resp_hint'                 : 'напр. Руководил командой из 5 инженеров',
  'exp_sheet_resp_add_btn'              : 'Добавить обязанность',
  'exp_sheet_resp_max_info'             : 'Достигнуто максимальное количество обязанностей: {n}',
  'exp_sheet_resp_validator_max'        : 'Максимум 200 символов',
  'exp_sheet_hint_job_title'            : 'напр. Старший разработчик',
  'exp_sheet_hint_location'             : 'напр. Москва, Россия',
  'exp_sheet_btn_save'                  : 'Сохранить опыт работы',
  'exp_sheet_btn_update'                : 'Сохранить изменения',
  'exp_date_present'                    : 'По настоящее время',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Образование',
  'edu_subtitle'                        : 'Добавьте академическое образование',
  'edu_add_btn'                         : 'Добавить образование',
  'edu_snack_max_selected'              : 'Для резюме можно выбрать не более 8 записей об образовании.',
  'edu_snack_max_saved'                 : 'Достигнуто максимальное количество сохранённых записей: 12.',
  'edu_library_title'                   : 'Сохранённое образование',
  'edu_library_hint'                    : 'Отмеченные записи включены в это резюме. Выборы сохраняются автоматически.',
  'edu_nav_next'                        : 'Перейти к навыкам',
  'edu_empty_message'                   : 'Образование ещё не добавлено',
  'edu_empty_sub'                       : 'Нажмите выше, чтобы добавить квалификации',
  'edu_card_bullet_singular'            : 'пункт',
  'edu_card_bullet_plural'              : 'пунктов',
  'edu_sheet_title_add'                 : 'Добавить образование',
  'edu_sheet_title_edit'                : 'Редактировать образование',
  'edu_sheet_field_degree'              : 'Степень / Квалификация *',
  'edu_sheet_field_institution'         : 'Учебное заведение *',
  'edu_sheet_section_key_points'        : 'Ключевые моменты',
  'edu_sheet_key_points_hint_info'      : 'Необязательно · 1 пункт · макс. 100 символов',
  'edu_sheet_point_label'               : 'Пункт {n}',
  'edu_sheet_point_add_btn'             : 'Добавить пункт',
  'edu_sheet_point_max_info'            : 'Достигнуто максимальное количество пунктов: {n}',
  'edu_sheet_point_validator_max'       : 'Максимум {n} символов',
  'edu_sheet_hint_degree'               : 'напр. Бакалавр информатики',
  'edu_sheet_hint_institution'          : 'напр. Московский государственный университет',
  'edu_sheet_hint_bullet'               : 'напр. Диплом с отличием',
  'edu_sheet_btn_save'                  : 'Сохранить образование',
  'edu_sheet_btn_update'                : 'Сохранить изменения',
  'edu_date_present'                    : 'По настоящее время',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Дополнительная информация',
  'additional_subtitle'                 : 'Сертификаты, языки и многое другое',
  'additional_cert_section_title'       : 'Сертификаты',
  'additional_cert_counter'             : '{sel}/{total} выбрано · макс. {max}',
  'additional_cert_hide'                : 'Скрыть',
  'additional_cert_show'                : 'Показать',
  'additional_cert_add_btn'             : 'Добавить',
  'additional_cert_snack_max'           : 'Достигнуто максимальное количество сертификатов: {n}.',
  'additional_cert_hint'                : 'Отмеченные записи включены в это резюме. Выборы сохраняются автоматически.',
  'additional_cert_empty'               : 'Сертификаты ещё не добавлены',
  'additional_lang_section_title'       : 'Языки',
  'additional_lang_add_hint'            : 'напр. Испанский',
  'additional_lang_snack_max'           : 'Достигнуто максимальное количество языков: {n}.',
  'additional_lang_empty'               : 'Языки ещё не добавлены',
  'additional_hobby_section_title'      : 'Хобби и интересы',
  'additional_hobby_add_hint'           : 'напр. Фотография',
  'additional_hobby_snack_max'          : 'Достигнуто максимальное количество хобби: {n}.',
  'additional_hobby_empty'              : 'Хобби ещё не добавлены',
  'additional_section_hint'             : 'Отмеченные записи включены в это резюме. Выборы сохраняются автоматически.',
  'additional_nav_next'                 : 'Перейти к рекомендациям',
  'cert_sheet_title_add'                : 'Добавить сертификат',
  'cert_sheet_title_edit'               : 'Редактировать сертификат',
  'cert_sheet_sub'                      : 'Добавьте квалификацию, сертификат или профессиональное удостоверение.',
  'cert_sheet_field_name'               : 'Название сертификата *',
  'cert_sheet_field_issued_by'          : 'Выдан кем (необязательно)',
  'cert_sheet_field_short_desc'         : 'Краткое описание (необязательно)',
  'cert_sheet_hint_name'                : 'напр. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'напр. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'напр. Получен в 2024 г.',
  'cert_sheet_btn_save'                 : 'Сохранить сертификат',
  'cert_sheet_btn_update'               : 'Обновить сертификат',
  'simple_sheet_title_add_language'     : 'Добавить язык',
  'simple_sheet_title_edit_language'    : 'Редактировать язык',
  'simple_sheet_title_add_hobby'        : 'Добавить хобби',
  'simple_sheet_title_edit_hobby'       : 'Редактировать хобби',
  'simple_sheet_btn_save'               : 'Сохранить',
  'simple_sheet_btn_update'             : 'Обновить',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Контакты',
  'pdf_section_about_me'                : 'Обо мне',
  'pdf_section_summary'                 : 'Резюме',
  'pdf_section_summary_short'           : 'Резюме',
  'pdf_section_profile'                 : 'Профиль',
  'pdf_section_experience'              : 'Опыт работы',
  'pdf_section_experience_short'        : 'Опыт работы',
  'pdf_section_education'               : 'Образование',
  'pdf_section_skills'                  : 'Навыки',
  'pdf_section_languages'               : 'Языки',
  'pdf_label_email'                     : 'Email',
  'pdf_label_phone'                     : 'Телефон',
  'pdf_label_location'                  : 'Местоположение',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Достигнут лимит резюме',
  'limit_dialog_body'                   : 'Вы достигли максимального количества в 30 резюме. Удалите существующее резюме, прежде чем создать новое.',
  'limit_dialog_go_to_my_cvs'           : 'Перейти к моим резюме',
  'limit_dialog_cancel'                 : 'Отмена',
  'refs_count_summary'                  : '{checked}/{maxChecked} выбрано · {saved}/{maxSaved} сохранено',
  'refs_selected_badge'                 : '{n} выбрано',
  'refs_empty_message'                  : 'Рекомендации пока не сохранены',
  'refs_empty_sub'                      : 'Нажмите выше, чтобы добавить личную рекомендацию',
};