// lib/language_keys/lang_zh_chinese.dart
//
// Chinese (Simplified) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> zhChinese = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : '未找到语言',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : '跳过',
  'onboarding_next'                     : '下一步',
  'onboarding_get_started'              : '立即开始',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  欢迎',
  'ob1_title'                           : '打造一份\n敲开机会之门的简历',
  'ob1_body'                            : '从众多求职者中脱颖而出。几分钟内制作一份精美的求职简历——无需任何设计技能。',
  'ob1_pill_label'                      : '专业简历制作工具',
  'ob1_chip_templates'                  : '24+ 模板',
  'ob1_chip_pdf'                        : 'PDF 导出',
  'ob1_chip_free'                       : '免费使用',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  模板',
  'ob2_title'                           : '适合每个行业。\n满足每种抱负。',
  'ob2_body'                            : '从商务专业版面到大胆创意设计——总有一款模板能讲述您的故事。',
  'ob2_tap_hint'                        : '点击任意模板预览',
  'ob2_tpl_executive'                   : '高管版',
  'ob2_tpl_vibrant'                     : '活力版',
  'ob2_tpl_nordic'                      : '北欧简约版',
  'ob2_tpl_tech_dark'                   : '科技暗色版',
  'ob2_tpl_luxury'                      : '奢华版',
  'ob2_tag_corporate'                   : '商务',
  'ob2_tag_creative'                    : '创意',
  'ob2_tag_minimal'                     : '简约',
  'ob2_tag_modern'                      : '现代',
  'ob2_tag_premium'                     : '高端',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  智能排版',
  'ob3_title'                           : '您的简历。\n完美呈现。',
  'ob3_body'                            : '智能排版自动重排您的版块，最大化视觉冲击力——将最强内容放在招聘官最先关注的位置。',
  'ob3_badge_smart_layout'              : '智能排版',
  'ob3_badge_cv_ready'                  : '简历就绪！',
  'ob3_step1_label'                     : '选择模板',
  'ob3_step1_desc'                      : '从 24+ 款精美设计中选择。',
  'ob3_step2_label'                     : '填写详情',
  'ob3_step2_desc'                      : '引导式输入，覆盖所有版块。',
  'ob3_step3_label'                     : '智能排版',
  'ob3_step3_desc'                      : '一键完美重排您的简历。',
  'ob3_step4_label'                     : '导出为 PDF',
  'ob3_step4_desc'                      : '像素级完美 PDF，随时发送。',
  'ob3_section_work'                    : '工作经历',
  'ob3_section_education'               : '教育背景',
  'ob3_section_skills'                  : '技能',
  'ob3_section_references'              : '推荐人',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  准备就绪',
  'ob4_title'                           : '顶尖求职者\n选择简历制作工具的理由',
  'ob4_visual_headline'                 : '一切就绪！',
  'ob4_visual_subline'                  : '求职所需的一切，尽在掌握。',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : '模板数量',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : '最多简历数',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : '导出格式',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : '隐私保护',
  'ob4_hl1_title'                       : '私密安全',
  'ob4_hl1_sub'                         : '数据仅保存在您的设备上。',
  'ob4_hl2_title'                       : '自动保存',
  'ob4_hl2_sub'                         : '每次输入即时保存。',
  'ob4_hl3_title'                       : '最多 30 份简历',
  'ob4_hl3_sub'                         : '针对不同职位创建专属简历。',
  'ob4_hl4_title'                       : '一键分享',
  'ob4_hl4_sub'                         : '无需离开应用即可发送 PDF。',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ 从求职者中脱颖而出',
  'home_hero_title'                     : '打造您的\n专业简历',
  'home_hero_sub'                       : '几分钟内制作一份\n令人印象深刻的简历',
  'home_hero_cta'                       : '开始制作',
  'home_premium_soon'                   : '专业版升级即将推出！',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : '最近创建',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : '最近编辑',
  'history_sort_by_template'            : '按模板排序',
  'history_sort_sheet_title'            : '排序方式',
  'history_sort_alphabetical_full'      : '按字母顺序（A–Z）',
  'history_premium_soon'                : '专业版升级即将推出！',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : '设置',
  'settings_section_preferences'        : '偏好设置',
  'settings_section_support'            : '帮助与支持',
  'settings_section_legal'              : '法律条款',
  'settings_section_about'              : '关于',
  'settings_language_tile_title'        : '语言',
  'settings_dark_mode_title'            : '深色模式',
  'settings_dark_mode_on'               : '深色主题已启用',
  'settings_dark_mode_off'              : '浅色主题已启用',
  'settings_help_faq_title'             : '帮助与常见问题',
  'settings_help_faq_sub'               : '常见问题解答',
  'settings_contact_support_title'      : '联系客服',
  'settings_rate_app_title'             : '评价应用',
  'settings_rate_app_sub'               : '喜欢这款应用？请留下评价！',
  'settings_privacy_policy_title'       : '隐私政策',
  'settings_terms_title'                : '服务条款',
  'settings_app_version_title'          : '应用版本',
  'settings_email_error'                : '无法打开邮件应用。请发送邮件至 cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : '简历预览',
  'preview_header_sub'                  : '随时可导出',
  'preview_generating'                  : '正在生成您的简历...',
  'preview_failed_title'                : '预览失败',
  'preview_failed_error'                : '错误：{error}',
  'preview_go_back'                     : '返回',
  'preview_no_data'                     : '暂无数据',
  'preview_btn_print'                   : '打印',
  'preview_btn_download'                : '下载并分享',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : '帮助与常见问题',
  'faq_category_all'                    : '全部',
  'faq_empty'                           : '未找到相关结果',
  'faq_contact_headline'                : '还需要帮助？',
  'faq_contact_sub'                     : '我们的团队随时为您服务。',
  'faq_contact_btn'                     : '联系我们',
  'faq_email_error'                     : '无法打开邮件应用。请发送邮件至 cyberinc101@gmail.com',
  'faq_cat_getting_started'             : '入门指南',
  'faq_cat_templates'                   : '模板',
  'faq_cat_editing'                     : '编辑',
  'faq_cat_exporting'                   : '导出',
  'faq_cat_data_privacy'                : '数据与隐私',
  'faq_cat_troubleshooting'             : '故障排除',
  'faq_q1'  : '如何创建我的第一份简历？',
  'faq_a1'  : '点击主页上的"+"按钮开始创建新简历。选择适合您风格的模板，然后逐步填写个人信息、工作经历、教育背景和技能。您的进度会自动保存。',
  'faq_q2'  : '我可以创建多份简历吗？',
  'faq_a2'  : '可以！您可以为不同职位或行业创建多份简历。每份简历单独保存，方便针对特定职位申请进行定制。',
  'faq_q3'  : '如何更改简历模板？',
  'faq_a3'  : '打开您的简历，点击屏幕顶部的模板图标，浏览可用模板。点击任意模板可用您现有内容预览效果，确认后即可应用。',
  'faq_q4'  : '有免费模板和付费模板吗？',
  'faq_a4'  : '有。部分专业模板免费提供。具有高级设计和配色方案的付费模板可通过一次性购买或订阅获取。',
  'faq_q5'  : '如何添加或删除版块？',
  'faq_a5'  : '在简历编辑器中，滚动到屏幕底部，点击"添加版块"以添加语言、证书或志愿工作等内容。要删除某个版块，点击版块标题并选择"删除"。',
  'faq_q6'  : '如何对版块重新排序？',
  'faq_a6'  : '长按任意版块标题旁的拖动手柄（≡），将其拖动到您想要的位置。更改会自动保存。',
  'faq_q7'  : '如何将简历导出为 PDF？',
  'faq_a7'  : '打开您的简历，点击右上角的导出按钮（分享图标），选择"导出为 PDF"。然后您可以将其保存到设备、通过电子邮件或微信分享，或直接上传到招聘平台。',
  'faq_q8'  : '支持哪些文件格式？',
  'faq_a8'  : '目前应用支持将简历导出为高质量 PDF。后续更新可能会添加更多格式。',
  'faq_q9'  : '我的简历数据存储在哪里？',
  'faq_a9'  : '您的所有简历数据都存储在您的设备本地。我们不会将您的个人信息上传到服务器。这意味着您的数据保持私密，并可离线访问。',
  'faq_q10' : '如何备份我的简历？',
  'faq_a10' : '如果您在设备设置中启用了备份，您的简历将包含在设备的标准备份中（Android 使用 Google Drive 备份，iOS 使用 iCloud）。您也可以将单份简历导出为 PDF 以保留副本。',
  'faq_q11' : '应用运行缓慢，该怎么办？',
  'faq_a11' : '请尝试关闭并重新打开应用。如果问题仍然存在，请重启设备。确保您已从 Play 商店/App Store 安装了最新版本的应用。',
  'faq_q12' : '我的简历无法正确导出，该怎么办？',
  'faq_a12' : '请确保您的设备有足够的存储空间。尝试减小简历中的大图像。如果问题持续存在，请联系我们的客服团队。',
  'faq_q13' : '我忘记保存了——我的内容丢失了吗？',
  'faq_a13' : '完全不会！应用会在您编辑时持续自动保存您的进度。',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : '您的职业生涯，精益求精',
  'header_tooltip_back'                 : '返回',
  'header_tooltip_my_cvs'               : '我的简历',
  'header_tooltip_settings'             : '设置',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : '我的简历',
  'saved_count_single'                  : '{n} 份文档',
  'saved_count_plural'                  : '{n} 份文档',
  'saved_limit_reached'                 : '已达上限',
  'saved_footer_count'                  : '{n} / 30 份简历',
  'saved_filter_all'                    : '全部',
  'saved_filter_draft'                  : '草稿',
  'saved_filter_complete'               : '已完成',
  'saved_status_complete'               : '已完成',
  'saved_status_saved'                  : '已保存',
  'saved_status_draft'                  : '草稿',
  'saved_empty_title'                   : '暂无简历',
  'saved_empty_sub'                     : '点击上方开始制作您的第一份简历',
  'saved_search_empty_title'            : '未找到结果',
  'saved_search_empty_sub'              : '请尝试其他搜索词',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : '配色方案',
  'custom_font_settings_title'          : '字体设置',
  'custom_font_family_label'            : '字体族',
  'custom_font_size_label'              : '字体大小：',
  'custom_current_template_title'       : '当前模板',
  'custom_change_template_btn'          : '更换模板',
  'custom_tpl_modern'                   : '现代',
  'custom_tpl_classic'                  : '经典',
  'custom_tpl_professional'             : '专业',
  'custom_tpl_creative'                 : '创意',
  'custom_tpl_minimal'                  : '简约',
  'custom_tpl_modern_desc'              : '简洁现代的设计',
  'custom_tpl_classic_desc'             : '传统专业版面',
  'custom_tpl_professional_desc'        : '以商务为核心的模板',
  'custom_tpl_creative_desc'            : '独特设计让您与众不同',
  'custom_tpl_minimal_desc'             : '简单优雅的风格',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : '选择模板',
  'swipe_photo_badge'                   : '照片',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : '高管版',
  'tpl_nordic_name'                     : '北欧简约版',
  'tpl_vibrant_name'                    : '活力版',
  'tpl_tech_dark_name'                  : '科技暗色版',
  'tpl_luxury_name'                     : '奢华版',
  'tpl_executive_tag'                   : '最受欢迎',
  'tpl_nordic_tag'                      : '简洁',
  'tpl_vibrant_tag'                     : '创意',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : '精英',
  'tpl_executive_desc'                  : '大气权威，适合高级职位',
  'tpl_nordic_desc'                     : '简约清晰，受顶级公司信赖',
  'tpl_vibrant_desc'                    : '以活力与色彩脱颖而出',
  'tpl_tech_dark_desc'                  : '终端美学，专为开发者设计',
  'tpl_luxury_desc'                     : '黑底金饰，彰显尊贵',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : '模板',
  'detail_step_personal'                : '个人信息',
  'detail_step_experience'              : '工作经历',
  'detail_step_education'               : '教育背景',
  'detail_step_skills'                  : '技能',
  'detail_step_additional'              : '附加信息',
  'detail_step_references'              : '推荐人',
  'detail_step_customize'               : '自定义',
  'detail_banner_heading'               : '即将完成！',
  'detail_banner_btn'                   : '继续',
  'detail_banner_completion_label'      : '完成度',
  'detail_stat_created_label'           : '创建时间',
  'detail_stat_steps_label'             : '已完成步骤',
  'detail_section_template_style'       : '模板样式',
  'detail_section_steps'                : '步骤',
  'detail_steps_counter'                : '{done} / {total} 已完成',
  'detail_step_sub'                     : '第 {n} 步，共 {total} 步',
  'detail_section_activity'             : '活动记录',
  'detail_activity_created'             : '创建于',
  'detail_activity_last_edited'         : '最后编辑',
  'detail_activity_template'            : '模板',
  'detail_btn_continue_editing'         : '继续编辑',
  'detail_btn_edit_cv'                  : '编辑简历',
  'detail_option_rename'                : '重命名简历',
  'detail_option_delete'                : '删除简历',
  'detail_rename_title'                 : '重命名简历',
  'detail_rename_hint'                  : '例如：软件工程师简历',
  'detail_rename_error_empty'           : '名称不能为空',
  'detail_rename_btn_cancel'            : '取消',
  'detail_rename_btn_save'              : '保存',
  'detail_rename_snackbar'              : '已重命名为"{name}"',
  'detail_delete_title'                 : '删除简历？',
  'detail_delete_body'                  : '此操作将永久删除"{name}"，且无法撤销。',
  'detail_delete_btn_cancel'            : '取消',
  'detail_delete_btn_confirm'           : '删除',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : '已完成',
  'detail_check_tile_incomplete'        : '尚未填写',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : '选择模板',
  'chooser_subtitle'                    : '滑动浏览  ·  点击选择  ·  长按预览',
  'chooser_card_hold_hint'              : '长按预览',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : '已选择',
  'chooser_modal_heading'               : '为简历命名',
  'chooser_modal_sub'                   : '给它起个名字，方便在"我的简历"和历史记录中找到它。',
  'chooser_modal_field_label'           : '简历名称',
  'chooser_modal_save_btn'              : '保存并开始制作',
  'chooser_modal_divider'               : '或继续已有简历',
  'chooser_nav_selected_sub'            : '已选模板',
  'chooser_nav_cta'                     : '保存并继续',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : '已达最大条目数',
  'editor_show_hide'                    : '显示/隐藏',
  'editor_editing_badge'                : '编辑中',
  'editor_field_required'               : '必填',
  'editor_tooltip_edit'                 : '编辑',
  'editor_tooltip_delete'               : '删除',
  'editor_date_start'                   : '开始日期 *',
  'editor_date_end'                     : '结束日期 *',
  'editor_date_tap_hint'                : '点击选择',
  'editor_date_dialog_title'            : '选择月份和年份',
  'editor_date_confirm'                 : '确认',
  'editor_panel_hide'                   : '隐藏',
  'editor_panel_show'                   : '显示',
  'editor_validator_max_chars'          : '最多 {n} 个字符',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : '制作您的简历',
  'editor_header_step_sub'              : '第 {current} 步，共 {total} 步 · {label}',
  'editor_step_template'                : '模板',
  'editor_step_personal'                : '个人信息',
  'editor_step_experience'              : '工作经历',
  'editor_step_education'               : '教育背景',
  'editor_step_skills'                  : '技能',
  'editor_step_additional'              : '附加信息',
  'editor_step_references'              : '推荐人',
  'editor_step_customize'               : '自定义',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : '自定义',
  'customize_subtitle'                  : '让您的简历独一无二',
  'customize_smart_layout_btn'          : '智能排版',
  'customize_back_to_top'               : '返回顶部',
  'customize_done_title'                : '一切就绪！',
  'customize_done_sub'                  : '点击下方"预览简历"查看您完成的简历',
  'customize_preview_btn'               : '预览简历',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : '配色方案',
  'color_black'                         : '黑色',
  'color_blue'                          : '蓝色',
  'color_nordic_blue'                   : '北欧蓝',
  'color_indigo'                        : '靛蓝色',
  'color_teal'                          : '青色',
  'color_green'                         : '绿色',
  'color_purple'                        : '紫色',
  'color_orange'                        : '橙色',
  'color_red'                           : '红色',
  'color_executive_gold'                : '高管金',
  'color_vibrant_coral'                 : '活力珊瑚色',
  'color_white'                         : '白色',
  'color_white_bg'                      : '白色背景',
  'color_maroon'                        : '栗色',
  'color_brutalist_yellow'              : '粗犷黄',
  'color_neon_blue'                     : '霓虹蓝',
  'color_blueprint_navy'                : '蓝图海军蓝',
  'color_light_grey'                    : '浅灰色',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : '字体族',
  'customize_font_picker_title'         : '选择字体',
  'customize_font_picker_sub'           : '每种字体以其自身字形预览',
  'customize_font_preview_sample'       : '敏捷的棕色狐狸',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : '字体大小',
  'customize_font_size_label'           : '文字大小',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : '图片大小',
  'customize_image_size_label'          : '图片大小',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : '实时预览',
  'preview_page_count_singular'         : '1 页',
  'preview_page_count_plural'           : '{n} 页',
  'preview_page_of'                     : '第 {page} 页，共 {total} 页',
  'preview_live_hint'                   : '更改即时生效',
  'preview_template_unregistered'       : '尚未在 customize_preview.dart 中注册',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : '正在准备您的简历…',
  'preview_bar_print'                   : '打印',
  'preview_bar_save_pdf'                : '保存为 PDF',
  'preview_bar_share'                   : '分享',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : '简历预览',
  'preview_screen_sub'                  : '{n} {unit} · 与打印效果完全一致',
  'preview_page_singular'               : '页',
  'preview_page_plural'                 : '页',
  'preview_pdf_filename'                : '我的简历',
  'preview_share_subject'               : '我的简历',
  'preview_snack_print_failed'          : '打印失败：{e}',
  'preview_snack_saved'                 : '简历已保存至下载文件夹 ✓',
  'preview_snack_export_failed'         : '导出失败：{e}',
  'preview_snack_share_failed'          : '分享失败：{e}',
  'preview_template_not_registered'     : '模板未注册',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : '关闭预览',
  'preview_modal_hint_photo'            : '支持个人头像  ·  点击卡片选择',
  'preview_modal_hint_no_photo'         : '点击模板卡片以选择',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : '我的简历',
  'time_just_now'                       : '刚刚',
  'time_minutes_ago'                    : '{n} 分钟前',
  'time_hours_ago'                      : '{n} 小时前',
  'time_yesterday'                      : '昨天',
  'time_days_ago'                       : '{n} 天前',
  'time_one_week_ago'                   : '1 周前',
  'time_weeks_ago'                      : '{n} 周前',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : '优雅',
  'tpl_tag_classic'                     : '经典',
  'tpl_tag_minimal'                     : '简约',
  'tpl_tag_creative'                    : '创意',
  'tpl_tag_bold'                        : '醒目',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : '渐变版',
  'tpl_gradient_desc'                   : '青蓝到紫罗兰的渐变卡片',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : '杂志版',
  'tpl_editorial_desc'                  : '杂志风格红色与奶油色',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : '粉彩柔和版',
  'tpl_pastel_soft_desc'                : '薰衣草侧边栏，柔和卡片',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : '粗犷风',
  'tpl_brutalist_desc'                  : '原始网格、粗边框与黄色',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : '翡翠绿版',
  'tpl_emerald_desc'                    : '森林绿配时间轴',

  // ID 11 · Infographic
  'tpl_infographic_name'                : '信息图表版',
  'tpl_infographic_desc'                : '深色画布配环形图表',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : '装饰艺术版',
  'tpl_art_deco_desc'                   : '1920 年代几何金色奢华风',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina 暗色版',
  'tpl_wina_dark_desc'                  : '深色信息图表配环形图',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio 橙色版',
  'tpl_rio_orange_desc'                 : '深色侧边栏配橙色点缀',

  // ID 15 · Summer
  'tpl_summer_name'                     : '夏日版',
  'tpl_summer_desc'                     : '简洁极简，柔和灰色调',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : '温暖米色优雅色调',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : '鲜明黑白经典风格',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : '经典 ATS 友好版面',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony 暗色版',
  'tpl_tony_dark_desc'                  : '深色橙色信息图风格',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : '时尚版',
  'tpl_fashion_desc'                    : '网格上的技术绘图风格',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : '档案版',
  'tpl_archivist_desc'                  : '经典双栏标签版面',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : '外交官版',
  'tpl_diplomat_desc'                   : '阴影标题配菱形引导线',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : '子午线版',
  'tpl_meridian_desc'                   : '居中标题，高亮公司名',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : '动力版',
  'tpl_momentum_desc'                   : '粗体名称、时间轴圆点与成就展示',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : '个人信息',
  'personal_subtitle'                   : '让雇主了解您是谁',
  'personal_profile_counter'            : '{n}/{max} 个档案',
  'personal_info_banner'                : '最多保存 5 个档案，每份简历选择一个。每份简历的选择会独立记忆。',
  'personal_snack_max'                  : '最多 {n} 个档案，已达上限。',
  'personal_add_btn'                    : '添加新档案',
  'personal_library_title'              : '已保存档案',
  'personal_selected_one'               : '已选 1 个',
  'personal_selected_none'              : '未选择',
  'personal_library_hint'               : '点击卡片仅为当前简历选择。其他简历保持各自独立的选择。',
  'personal_empty_message'              : '尚未保存任何档案',
  'personal_empty_sub'                  : '点击上方添加您的个人信息',
  'personal_nav_next'                   : '保存并继续',
  'personal_card_active_badge'          : '当前简历使用中',
  'personal_sheet_title_add'            : '新建档案',
  'personal_sheet_title_edit'           : '编辑档案',
  'personal_sheet_brutalist_badge'      : '粗犷风',
  'personal_sheet_brutalist_banner'     : '粗犷风模板联系字段较为紧凑，建议填写简短内容（如仅填城市）以获得最佳显示效果。',
  'personal_section_photo'              : '个人头像',
  'personal_section_basic'              : '基本信息',
  'personal_section_contact'            : '联系方式',
  'personal_section_online'             : '在线主页',
  'personal_section_summary'            : '个人简介',
  'personal_field_first_name'           : '名 *',
  'personal_field_last_name'            : '姓',
  'personal_field_job_title'            : '职位名称 *',
  'personal_field_email'                : '电子邮箱 *',
  'personal_field_phone'                : '手机号码 *',
  'personal_field_location'             : '所在地',
  'personal_field_location_brut'        : '所在地（仅城市）',
  'personal_field_website'              : '网站 / 作品集',
  'personal_field_linkedin'             : 'LinkedIn 链接',
  'personal_hint_first_name'            : '例如：明',
  'personal_hint_last_name'             : '例如：张',
  'personal_hint_job_title'             : '例如：高级工程师',
  'personal_hint_email'                 : '例如：zhang@example.com',
  'personal_hint_phone'                 : '例如：+86 138 1234 5678',
  'personal_hint_location'              : '例如：上海，中国',
  'personal_hint_location_brut'         : '例如：上海',
  'personal_hint_website'               : '例如：github.com/zhangming',
  'personal_hint_website_brut'          : '例如：github.com/zhang',
  'personal_hint_linkedin'              : '例如：linkedin.com/in/zhangming',
  'personal_hint_linkedin_brut'         : '例如：linkedin.com/in/zhang',
  'personal_summary_hint_label'         : '保持简洁——这将显示在简历顶部。',
  'personal_hint_summary'               : '简短的 2–3 句话，概述您的背景和目标...',
  'personal_validator_email'            : '请输入有效的电子邮箱',
  'personal_field_char_limit_tooltip'   : '已达字符上限',
  'personal_sheet_btn_save'             : '保存档案',
  'personal_sheet_btn_update'           : '保存更改',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : '选择照片',
  'photo_option_gallery'                : '从相册选择',
  'photo_option_camera'                 : '拍摄照片',
  'photo_option_reposition'             : '调整照片位置',
  'photo_option_remove'                 : '删除照片',
  'photo_status_added'                  : '照片已添加 ✓',
  'photo_status_empty'                  : '添加一张专业头像',
  'photo_chip_gallery'                  : '相册',
  'photo_chip_camera'                   : '相机',
  'photo_chip_reposition'               : '调整位置',
  'photo_reposition_title'              : '调整照片位置',
  'photo_reposition_sub'                : '拖动照片以调整位置',
  'photo_reposition_reset'              : '重置到中心',
  'photo_reposition_apply'              : '应用',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : '技能',
  'skills_subtitle'                     : '突出您的核心能力',
  'skills_add_btn'                      : '添加新技能',
  'skills_snack_max_icons'              : '最多选择 10 个图标。',
  'skills_snack_max_skills'             : '最多 15 项技能，已达上限。',
  'skills_library_title'                : '已保存技能',
  'skills_library_hint'                 : '勾选的技能将包含在此份简历中，选择会自动保存。',
  'skills_nav_next'                     : '继续填写附加信息',
  'skills_wina_header_icon_bar'         : '标题图标栏',
  'skills_wina_on'                      : '开启',
  'skills_wina_off'                     : '关闭',
  'skills_wina_bar_on_sub'              : '简历标题中显示彩色图标圆圈。',
  'skills_wina_bar_off_sub'             : '图标行隐藏——为联系信息留出更多空间。',
  'skills_wina_palette_hint'            : '图标将按调色板顺序以彩色圆圈显示。',
  'skills_wina_preview_label'           : '预览',
  'skills_wina_disabled_hint'           : '请先开启上方的图标栏，以选择在简历标题中显示哪些图标。',
  'skills_sheet_title_add'              : '添加技能',
  'skills_sheet_title_edit'             : '编辑技能',
  'skills_sheet_field_name'             : '技能名称 *',
  'skills_sheet_hint_short'             : '例如：Flutter、设计',
  'skills_sheet_hint_long'              : '例如：Flutter、项目管理',
  'skills_sheet_validator_max'          : '最多 {n} 个字符',
  'skills_sheet_proficiency'            : '熟练程度',
  'skills_sheet_beginner'               : '初级',
  'skills_sheet_expert'                 : '专家',
  'skills_sheet_btn_save'               : '保存技能',
  'skills_sheet_btn_update'             : '更新技能',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : '个人推荐人',
  'refs_subtitle'                       : '可以为您作证的人',
  'refs_add_btn'                        : '添加新推荐人',
  'refs_snack_max_selected'             : '每份简历最多选择 4 位推荐人。',
  'refs_snack_max_saved'                : '最多保存 10 位推荐人，已达上限。',
  'refs_library_title'                  : '已保存推荐人',
  'refs_library_hint'                   : '勾选的推荐人将包含在此份简历中，每份最多 4 位，选择会自动保存。',
  'refs_nav_next'                       : '继续自定义',
  'refs_sheet_title_add'                : '添加推荐人',
  'refs_sheet_title_edit'               : '编辑推荐人',
  'refs_sheet_sub_add'                  : '可以向雇主个人推荐您的人。',
  'refs_sheet_sub_edit'                 : '在下方更新此推荐人的详细信息。',
  'refs_sheet_field_name'               : '全名 *',
  'refs_sheet_field_title'              : '职位名称 *',
  'refs_sheet_field_company'            : '公司（可选）',
  'refs_sheet_field_email'              : '电子邮箱 *',
  'refs_sheet_field_phone'              : '手机号码 *',
  'refs_sheet_hint_name'                : '例如：李伟',
  'refs_sheet_hint_title'               : '例如：工程部经理',
  'refs_sheet_hint_company'             : '例如：某某科技有限公司',
  'refs_sheet_hint_email'               : '例如：liwei@company.com',
  'refs_sheet_hint_phone'               : '例如：+86 138 1234 5678',
  'refs_sheet_validator_email'          : '请输入有效的电子邮箱',
  'refs_sheet_btn_save'                 : '保存推荐人',
  'refs_sheet_btn_update'               : '更新推荐人',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : '工作经历',
  'exp_subtitle'                        : '添加您的工作历史',
  'exp_banner_info'                     : '每个职位最多显示 {n} 条职责。通常 3–6 段经历可填满 1–2 页。',
  'exp_add_btn'                         : '添加新工作经历',
  'exp_snack_max_selected'              : '每份简历最多选择 8 段工作经历。',
  'exp_snack_max_saved'                 : '最多保存 12 段工作经历，已达上限。',
  'exp_library_title'                   : '已保存工作经历',
  'exp_library_hint'                    : '勾选的条目仅包含在此份简历中，其他简历保持各自独立的选择。',
  'exp_nav_next'                        : '继续填写教育背景',
  'exp_empty_message'                   : '尚未添加工作经历',
  'exp_empty_sub'                       : '点击上方添加您的第一段经历',
  'exp_card_resp_singular'              : '条职责',
  'exp_card_resp_plural'                : '条职责',
  'exp_card_resp_tooltip'               : '简历上最多显示前 8 条职责',
  'exp_sheet_title_add'                 : '添加工作经历',
  'exp_sheet_title_edit'                : '编辑工作经历',
  'exp_sheet_field_job_title'           : '职位名称 *',
  'exp_sheet_field_company'             : '公司名称 *',
  'exp_sheet_field_location'            : '工作地点',
  'exp_sheet_section_responsibilities'  : '主要职责',
  'exp_sheet_resp_hint_info'            : '最多 8 条 · 每条最多 200 字',
  'exp_sheet_resp_label'                : '职责 {n}',
  'exp_sheet_resp_hint'                 : '例如：带领 5 名工程师的团队',
  'exp_sheet_resp_add_btn'              : '添加职责',
  'exp_sheet_resp_max_info'             : '最多 {n} 条职责，已达上限',
  'exp_sheet_resp_validator_max'        : '最多 200 字',
  'exp_sheet_hint_job_title'            : '例如：高级开发工程师',
  'exp_sheet_hint_location'             : '例如：北京，中国',
  'exp_sheet_btn_save'                  : '保存工作经历',
  'exp_sheet_btn_update'                : '保存更改',
  'exp_date_present'                    : '至今 / 当前职位',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : '教育背景',
  'edu_subtitle'                        : '添加您的学术经历',
  'edu_add_btn'                         : '添加新教育经历',
  'edu_snack_max_selected'              : '每份简历最多选择 8 段教育经历。',
  'edu_snack_max_saved'                 : '最多保存 12 段教育经历，已达上限。',
  'edu_library_title'                   : '已保存教育经历',
  'edu_library_hint'                    : '勾选的条目将包含在此份简历中，选择会自动保存。',
  'edu_nav_next'                        : '继续填写技能',
  'edu_empty_message'                   : '尚未添加教育经历',
  'edu_empty_sub'                       : '点击上方添加您的学历信息',
  'edu_card_bullet_singular'            : '条要点',
  'edu_card_bullet_plural'              : '条要点',
  'edu_sheet_title_add'                 : '添加教育经历',
  'edu_sheet_title_edit'                : '编辑教育经历',
  'edu_sheet_field_degree'              : '学位 / 资质 *',
  'edu_sheet_field_institution'         : '院校名称 *',
  'edu_sheet_section_key_points'        : '要点',
  'edu_sheet_key_points_hint_info'      : '可选 · 1 条要点 · 最多 100 字',
  'edu_sheet_point_label'               : '要点 {n}',
  'edu_sheet_point_add_btn'             : '添加要点',
  'edu_sheet_point_max_info'            : '最多 {n} 条要点，已达上限',
  'edu_sheet_point_validator_max'       : '最多 {n} 字',
  'edu_sheet_hint_degree'               : '例如：计算机科学学士',
  'edu_sheet_hint_institution'          : '例如：北京大学',
  'edu_sheet_hint_bullet'               : '例如：以优异成绩毕业',
  'edu_sheet_btn_save'                  : '保存教育经历',
  'edu_sheet_btn_update'                : '保存更改',
  'edu_date_present'                    : '至今 / 在读',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : '附加信息',
  'additional_subtitle'                 : '证书、语言等更多内容',
  'additional_cert_section_title'       : '证书',
  'additional_cert_counter'             : '已选 {sel}/{total} · 最多 {max}',
  'additional_cert_hide'                : '隐藏',
  'additional_cert_show'                : '显示',
  'additional_cert_add_btn'             : '添加',
  'additional_cert_snack_max'           : '最多 {n} 条证书记录，已达上限。',
  'additional_cert_hint'                : '勾选的条目将包含在此份简历中，选择会自动保存。',
  'additional_cert_empty'               : '尚未添加任何证书',
  'additional_lang_section_title'       : '语言能力',
  'additional_lang_add_hint'            : '例如：英语',
  'additional_lang_snack_max'           : '最多 {n} 条语言记录，已达上限。',
  'additional_lang_empty'               : '尚未添加任何语言',
  'additional_hobby_section_title'      : '兴趣爱好',
  'additional_hobby_add_hint'           : '例如：摄影',
  'additional_hobby_snack_max'          : '最多 {n} 条兴趣爱好，已达上限。',
  'additional_hobby_empty'              : '尚未添加任何兴趣爱好',
  'additional_section_hint'             : '勾选的条目将包含在此份简历中，选择会自动保存。',
  'additional_nav_next'                 : '继续填写推荐人',
  'cert_sheet_title_add'                : '添加证书',
  'cert_sheet_title_edit'               : '编辑证书',
  'cert_sheet_sub'                      : '添加学历证书、资格证书或专业资质。',
  'cert_sheet_field_name'               : '证书名称 *',
  'cert_sheet_field_issued_by'          : '颁发机构（可选）',
  'cert_sheet_field_short_desc'         : '简短描述（可选）',
  'cert_sheet_hint_name'                : '例如：AWS 解决方案架构师',
  'cert_sheet_hint_issued_by'           : '例如：亚马逊云科技',
  'cert_sheet_hint_short_desc'          : '例如：2024 年获得',
  'cert_sheet_btn_save'                 : '保存证书',
  'cert_sheet_btn_update'               : '更新证书',
  'simple_sheet_title_add_language'     : '添加语言',
  'simple_sheet_title_edit_language'    : '编辑语言',
  'simple_sheet_title_add_hobby'        : '添加兴趣爱好',
  'simple_sheet_title_edit_hobby'       : '编辑兴趣爱好',
  'simple_sheet_btn_save'               : '保存',
  'simple_sheet_btn_update'             : '更新',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : '联系方式',
  'pdf_section_about_me'                : '关于我',
  'pdf_section_summary'                 : '个人简介',
  'pdf_section_summary_short'           : '简介',
  'pdf_section_profile'                 : '个人档案',
  'pdf_section_experience'              : '工作经历',
  'pdf_section_experience_short'        : '经历',
  'pdf_section_education'               : '教育背景',
  'pdf_section_skills'                  : '技能',
  'pdf_section_languages'               : '语言能力',
  'pdf_label_email'                     : '邮箱',
  'pdf_label_phone'                     : '电话',
  'pdf_label_location'                  : '地址',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : '已达简历上限',
  'limit_dialog_body'                   : '您已创建了最多 30 份简历。请删除一份现有简历后再新建。',
  'limit_dialog_go_to_my_cvs'           : '前往我的简历',
  'limit_dialog_cancel'                 : '取消',
  'refs_count_summary'                  : '已选 {checked}/{maxChecked} · 已保存 {saved}/{maxSaved}',
  'refs_selected_badge'                 : '已选 {n}',
  'refs_empty_message'                  : '尚未保存任何推荐人',
  'refs_empty_sub'                      : '点击上方添加推荐人',
};