// lib/language_keys/lang_tr_turkish.dart
//
// Turkish (Türkçe) translation map.
// All user-visible strings matching lang_en_english.dart

const Map<String, String> trTurkish = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Dil bulunamadı',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Atla',
  'onboarding_next'                     : 'İleri',
  'onboarding_get_started'              : 'Başla',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Hoş Geldiniz',
  'ob1_title'                           : 'Kapıları Açan Bir\nÖzgeçmiş Oluşturun',
  'ob1_body'                            : 'Yüzlerce başvuru arasından sıyrılın. Tasarım bilgisine gerek duymadan dakikalar içinde göz alıcı, işe alımda fark yaratan bir özgeçmiş hazırlayın.',
  'ob1_pill_label'                      : 'Profesyonel Özgeçmiş Oluşturucu',
  'ob1_chip_templates'                  : '24+ Şablon',
  'ob1_chip_pdf'                        : 'PDF Dışa Aktarma',
  'ob1_chip_free'                       : 'Ücretsiz Kullanım',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Şablonlar',
  'ob2_title'                           : 'Her Sektör.\nHer Hedef.',
  'ob2_body'                            : 'Yönetim odasına hazır düzenlerden cesur yaratıcı tasarımlara — hikayenizi anlatan bir şablon.',
  'ob2_tap_hint'                        : 'Önizlemek için bir şablona dokunun',
  'ob2_tpl_executive'                   : 'Yönetici',
  'ob2_tpl_vibrant'                     : 'Canlı',
  'ob2_tpl_nordic'                      : 'İskandinav',
  'ob2_tpl_tech_dark'                   : 'Teknoloji Koyu',
  'ob2_tpl_luxury'                      : 'Lüks',
  'ob2_tag_corporate'                   : 'Kurumsal',
  'ob2_tag_creative'                    : 'Yaratıcı',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Akıllı Düzen',
  'ob3_title'                           : 'Özgeçmişiniz.\nMükemmel Düzenlenmiş.',
  'ob3_body'                            : 'Akıllı Düzen, bölümlerinizi maksimum etki için yeniden sıralar — en güçlü içeriğinizi işe alım uzmanlarının önce baktığı yere koyar.',
  'ob3_badge_smart_layout'              : 'Akıllı Düzen',
  'ob3_badge_cv_ready'                  : 'Özgeçmiş Hazır!',
  'ob3_step1_label'                     : 'Şablon Seç',
  'ob3_step1_desc'                      : '24+ etkileyici tasarım arasından seçin.',
  'ob3_step2_label'                     : 'Bilgilerini Gir',
  'ob3_step2_desc'                      : 'Tüm bölümler için rehberli alanlar.',
  'ob3_step3_label'                     : 'Akıllı Düzen',
  'ob3_step3_desc'                      : 'Tek dokunuşla özgeçmişiniz mükemmel düzenlenir.',
  'ob3_step4_label'                     : 'PDF Olarak Dışa Aktar',
  'ob3_step4_desc'                      : 'Göndermeye hazır mükemmel PDF.',
  'ob3_section_work'                    : 'İş Deneyimi',
  'ob3_section_education'               : 'Eğitim',
  'ob3_section_skills'                  : 'Beceriler',
  'ob3_section_references'              : 'Referanslar',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Hazır',
  'ob4_title'                           : 'Neden En İyi Adaylar\nÖzgeçmiş Oluşturucuyu Seçiyor',
  'ob4_visual_headline'                 : 'Hazırsınız!',
  'ob4_visual_subline'                  : 'İşe girmeniz için ihtiyacınız olan her şey.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Şablonlar',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Maks. Özgeçmiş',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Dışa Aktar',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Gizli',
  'ob4_hl1_title'                       : 'Gizli ve Güvenli',
  'ob4_hl1_sub'                         : 'Veriler cihazınızda kalır.',
  'ob4_hl2_title'                       : 'Otomatik Kayıt',
  'ob4_hl2_sub'                         : 'Her tuş vuruşu anında kaydedilir.',
  'ob4_hl3_title'                       : '30\'a Kadar Özgeçmiş',
  'ob4_hl3_sub'                         : 'Her rol için ayrı özgeçmiş.',
  'ob4_hl4_title'                       : 'Tek Dokunuşla Paylaş',
  'ob4_hl4_sub'                         : 'Uygulamadan çıkmadan PDF gönderin.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Kalabalıktan sıyrılın',
  'home_hero_title'                     : 'Profesyonel\nÖzgeçmişinizi Oluşturun',
  'home_hero_sub'                       : 'Dakikalar içinde etkileyici\nbir özgeçmiş hazırlayın',
  'home_hero_cta'                       : 'Oluşturmaya Başla',
  'home_premium_soon'                   : 'Pro\'ya yükseltme yakında geliyor!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'En Yeni',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Son Düzenlenen',
  'history_sort_by_template'            : 'Şablona Göre',
  'history_sort_sheet_title'            : 'Sırala',
  'history_sort_alphabetical_full'      : 'Alfabetik (A–Z)',
  'history_premium_soon'                : 'Pro\'ya yükseltme yakında geliyor!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Ayarlar',
  'settings_section_preferences'        : 'Tercihler',
  'settings_section_support'            : 'Destek',
  'settings_section_legal'              : 'Yasal',
  'settings_section_about'              : 'Hakkında',
  'settings_language_tile_title'        : 'Dil',
  'settings_dark_mode_title'            : 'Karanlık Mod',
  'settings_dark_mode_on'               : 'Koyu tema etkin',
  'settings_dark_mode_off'              : 'Açık tema etkin',
  'settings_help_faq_title'             : 'Yardım ve SSS',
  'settings_help_faq_sub'               : 'Sık sorulan sorular yanıtlandı',
  'settings_contact_support_title'      : 'Destek ile İletişim',
  'settings_rate_app_title'             : 'Uygulamayı Puanlayın',
  'settings_rate_app_sub'               : 'Uygulamayı beğeniyor musunuz? Yorum bırakın!',
  'settings_privacy_policy_title'       : 'Gizlilik Politikası',
  'settings_terms_title'                : 'Kullanım Koşulları',
  'settings_app_version_title'          : 'Uygulama Sürümü',
  'settings_email_error'                : 'E-posta uygulaması açılamadı. Lütfen cyberinc101@gmail.com adresine e-posta gönderin',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Özgeçmiş Önizleme',
  'preview_header_sub'                  : 'Dışa aktarmaya hazır',
  'preview_generating'                  : 'Özgeçmişiniz oluşturuluyor...',
  'preview_failed_title'                : 'Önizleme Başarısız',
  'preview_failed_error'                : 'Hata: {error}',
  'preview_go_back'                     : 'Geri Dön',
  'preview_no_data'                     : 'Veri mevcut değil',
  'preview_btn_print'                   : 'Yazdır',
  'preview_btn_download'                : 'İndir ve Paylaş',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Yardım ve SSS',
  'faq_category_all'                    : 'Tümü',
  'faq_empty'                           : 'Sonuç bulunamadı',
  'faq_contact_headline'                : 'Hâlâ yardıma mı ihtiyacınız var?',
  'faq_contact_sub'                     : 'Ekibimiz size yardımcı olmak için burada.',
  'faq_contact_btn'                     : 'İletişim',
  'faq_email_error'                     : 'E-posta uygulaması açılamadı. Lütfen cyberinc101@gmail.com adresine e-posta gönderin',
  'faq_cat_getting_started'             : 'Başlangıç',
  'faq_cat_templates'                   : 'Şablonlar',
  'faq_cat_editing'                     : 'Düzenleme',
  'faq_cat_exporting'                   : 'Dışa Aktarma',
  'faq_cat_data_privacy'                : 'Veri ve Gizlilik',
  'faq_cat_troubleshooting'             : 'Sorun Giderme',
  'faq_q1'  : 'İlk özgeçmişimi nasıl oluştururum?',
  'faq_a1'  : 'Yeni bir özgeçmiş başlatmak için ana ekrandaki "+" düğmesine dokunun. Tarzınıza uygun bir şablon seçin, ardından kişisel bilgilerinizi, iş deneyiminizi, eğitiminizi ve becerilerinizi adım adım doldurun. İlerlemeniz otomatik olarak kaydedilir.',
  'faq_q2'  : 'Birden fazla özgeçmiş oluşturabilir miyim?',
  'faq_a2'  : 'Evet! Farklı roller veya sektörler için birden fazla özgeçmiş oluşturabilirsiniz. Her özgeçmiş ayrı olarak kaydedilir, böylece belirli iş başvurularına göre özelleştirebilirsiniz.',
  'faq_q3'  : 'Özgeçmiş şablonumu nasıl değiştiririm?',
  'faq_a3'  : 'Özgeçmişinizi açın, ekranın üst kısmındaki şablon simgesine dokunun ve mevcut şablonlara göz atın. Mevcut içeriğinizle önizlemek için herhangi bir şablona dokunun. Uygulamak için onaylayın.',
  'faq_q4'  : 'Ücretsiz ve premium şablonlar var mı?',
  'faq_a4'  : 'Evet. Profesyonel şablonların bir kısmı ücretsiz olarak sunulmaktadır. Gelişmiş tasarımlara ve renk paletlerine sahip premium şablonlar tek seferlik satın alma veya abonelik yoluyla kullanılabilir.',
  'faq_q5'  : 'Bölümleri nasıl ekler veya kaldırırım?',
  'faq_a5'  : 'Özgeçmiş düzenleyicisinde ekranın altına kaydırın ve Diller, Sertifikalar veya Gönüllü Çalışma gibi ekstralar eklemek için "Bölüm Ekle"ye dokunun. Bir bölümü kaldırmak için bölüm başlığına dokunun ve "Kaldır"ı seçin.',
  'faq_q6'  : 'Bölümleri nasıl yeniden sıralarım?',
  'faq_a6'  : 'Herhangi bir bölüm başlığının yanındaki sürükleme tutamacına (≡) uzun basın ve tercih ettiğiniz konuma sürükleyin. Değişiklikler otomatik olarak kaydedilir.',
  'faq_q7'  : 'Özgeçmişimi PDF olarak nasıl dışa aktarırım?',
  'faq_a7'  : 'Özgeçmişinizi açın ve sağ üst köşedeki dışa aktarma düğmesine (paylaşım simgesi) dokunun. "PDF olarak Dışa Aktar"ı seçin. Ardından cihazınıza kaydedebilir, e-posta veya WhatsApp aracılığıyla paylaşabilir ya da doğrudan iş ilanı sitelerine yükleyebilirsiniz.',
  'faq_q8'  : 'Hangi dosya biçimleri destekleniyor?',
  'faq_a8'  : 'Şu anda uygulama özgeçmişinizi yüksek kaliteli PDF olarak dışa aktarmayı desteklemektedir. Gelecekteki güncellemelerde ek biçimler eklenebilir.',
  'faq_q9'  : 'Özgeçmiş verilerim nerede saklanıyor?',
  'faq_a9'  : 'Tüm özgeçmiş verileriniz cihazınızda yerel olarak saklanır. Kişisel bilgilerinizi sunucularımıza yüklemiyoruz. Bu, verilerinizin gizli kalmasını ve çevrimdışı erişilebilir olmasını sağlar.',
  'faq_q10' : 'Özgeçmişlerimi nasıl yedeklerim?',
  'faq_a10' : 'Cihaz ayarlarınızda yedeklemeyi etkinleştirdiyseniz özgeçmişleriniz cihazınızın standart yedeğine dahil edilir (Android\'de Google Drive, iOS\'ta iCloud). Ayrıca her özgeçmişi PDF olarak dışa aktararak bir kopyasını saklayabilirsiniz.',
  'faq_q11' : 'Uygulama yavaş çalışıyor. Ne yapmalıyım?',
  'faq_a11' : 'Uygulamayı kapatıp yeniden açmayı deneyin. Sorun devam ederse cihazınızı yeniden başlatın. Play Store / App Store\'dan uygulamanın en son sürümünü yüklediğinizden emin olun.',
  'faq_q12' : 'Özgeçmişim doğru dışa aktarılmıyor. Ne yapmalıyım?',
  'faq_a12' : 'Cihazınızda yeterli depolama alanı olduğundan emin olun. Özgeçmişinizdeki büyük resimleri küçültmeyi deneyin. Sorun devam ederse lütfen destek ekibimizle iletişime geçin.',
  'faq_q13' : 'Kaydetmeyi unuttuysam çalışmam kayboldu mu?',
  'faq_a13' : 'Hayır! Uygulama siz düzenlerken ilerlemenizi sürekli olarak kaydeder.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'Özgeçmiş Oluşturucu Pro',
  'header_app_subtitle'                 : 'Kariyeriniz, mükemmelleştirildi',
  'header_tooltip_back'                 : 'Geri',
  'header_tooltip_my_cvs'               : 'Özgeçmişlerim',
  'header_tooltip_settings'             : 'Ayarlar',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Özgeçmişlerim',
  'saved_count_single'                  : '{n} belge',
  'saved_count_plural'                  : '{n} belge',
  'saved_limit_reached'                 : 'Limite ulaşıldı',
  'saved_footer_count'                  : '{n} / 30 Özgeçmiş',
  'saved_filter_all'                    : 'Tümü',
  'saved_filter_draft'                  : 'Taslak',
  'saved_filter_complete'               : 'Tamamlandı',
  'saved_status_complete'               : 'Tamamlandı',
  'saved_status_saved'                  : 'Kaydedildi',
  'saved_status_draft'                  : 'Taslak',
  'saved_empty_title'                   : 'Henüz özgeçmiş yok',
  'saved_empty_sub'                     : 'Yukarıdan ilk özgeçmişinizi oluşturmaya başlayın',
  'saved_search_empty_title'            : 'Sonuç bulunamadı',
  'saved_search_empty_sub'              : 'Farklı bir arama terimi deneyin',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Renk Şeması',
  'custom_font_settings_title'          : 'Yazı Tipi Ayarları',
  'custom_font_family_label'            : 'Yazı Tipi Ailesi',
  'custom_font_size_label'              : 'Yazı Tipi Boyutu: ',
  'custom_current_template_title'       : 'Mevcut Şablon',
  'custom_change_template_btn'          : 'Şablonu Değiştir',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klasik',
  'custom_tpl_professional'             : 'Profesyonel',
  'custom_tpl_creative'                 : 'Yaratıcı',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Temiz ve çağdaş tasarım',
  'custom_tpl_classic_desc'             : 'Geleneksel profesyonel düzen',
  'custom_tpl_professional_desc'        : 'İş odaklı şablon',
  'custom_tpl_creative_desc'            : 'Benzersiz tasarımla öne çıkın',
  'custom_tpl_minimal_desc'             : 'Sade ve zarif stil',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Şablon Seçin',
  'swipe_photo_badge'                   : 'Fotoğraf',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Yönetici',
  'tpl_nordic_name'                     : 'İskandinav',
  'tpl_vibrant_name'                    : 'Canlı',
  'tpl_tech_dark_name'                  : 'Teknoloji Koyu',
  'tpl_luxury_name'                     : 'Lüks',
  'tpl_executive_tag'                   : 'En Popüler',
  'tpl_nordic_tag'                      : 'Temiz',
  'tpl_vibrant_tag'                     : 'Yaratıcı',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elit',
  'tpl_executive_desc'                  : 'Üst düzey roller için güçlü ve otoriter',
  'tpl_nordic_desc'                     : 'Önde gelen firmaların güvendiği minimal netlik',
  'tpl_vibrant_desc'                    : 'Enerji ve renkle öne çıkın',
  'tpl_tech_dark_desc'                  : 'Geliştiriciler için terminal estetiği',
  'tpl_luxury_desc'                     : 'Siyah üzerine altın akışlı prestij',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Şablon',
  'detail_step_personal'                : 'Kişisel',
  'detail_step_experience'              : 'Deneyim',
  'detail_step_education'               : 'Eğitim',
  'detail_step_skills'                  : 'Beceriler',
  'detail_step_additional'              : 'Ek Bilgi',
  'detail_step_references'              : 'Referanslar',
  'detail_step_customize'               : 'Özelleştir',
  'detail_banner_heading'               : 'Neredeyse bitti!',
  'detail_banner_btn'                   : 'Devam Et',
  'detail_banner_completion_label'      : 'Tamamlanma',
  'detail_stat_created_label'           : 'Oluşturuldu',
  'detail_stat_steps_label'             : 'Tamamlanan adımlar',
  'detail_section_template_style'       : 'Şablon Stili',
  'detail_section_steps'                : 'Adımlar',
  'detail_steps_counter'                : '{done} / {total} tamamlandı',
  'detail_step_sub'                     : 'Adım {n} / {total}',
  'detail_section_activity'             : 'Etkinlik',
  'detail_activity_created'             : 'Oluşturuldu',
  'detail_activity_last_edited'         : 'Son Düzenleme',
  'detail_activity_template'            : 'Şablon',
  'detail_btn_continue_editing'         : 'Düzenlemeye Devam Et',
  'detail_btn_edit_cv'                  : 'Özgeçmişi Düzenle',
  'detail_option_rename'                : 'Özgeçmişi Yeniden Adlandır',
  'detail_option_delete'                : 'Özgeçmişi Sil',
  'detail_rename_title'                 : 'Özgeçmişi Yeniden Adlandır',
  'detail_rename_hint'                  : 'Örn. Yazılım Mühendisi Özgeçmişi',
  'detail_rename_error_empty'           : 'Ad boş olamaz',
  'detail_rename_btn_cancel'            : 'İptal',
  'detail_rename_btn_save'              : 'Kaydet',
  'detail_rename_snackbar'              : '"{name}" olarak yeniden adlandırıldı',
  'detail_delete_title'                 : 'Özgeçmiş Silinsin mi?',
  'detail_delete_body'                  : '"{name}" kalıcı olarak silinecek. Bu işlem geri alınamaz.',
  'detail_delete_btn_cancel'            : 'İptal',
  'detail_delete_btn_confirm'           : 'Sil',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Tamamlandı',
  'detail_check_tile_incomplete'        : 'Henüz doldurulmadı',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Şablonunuzu Seçin',
  'chooser_subtitle'                    : 'Kaydırarak göz atın  ·  Seçmek için dokunun  ·  Önizlemek için basılı tutun',
  'chooser_card_hold_hint'              : 'Önizlemek için basılı tutun',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Seçildi',
  'chooser_modal_heading'               : 'Özgeçmişinizi Adlandırın',
  'chooser_modal_sub'                   : 'Özgeçmişlerim ve Geçmişte kolayca bulabilmek için bir ad verin.',
  'chooser_modal_field_label'           : 'Özgeçmiş Adı',
  'chooser_modal_save_btn'              : 'Kaydet ve Oluşturmaya Başla',
  'chooser_modal_divider'               : 'veya mevcut bir özgeçmişe devam edin',
  'chooser_nav_selected_sub'            : 'Seçilen şablon',
  'chooser_nav_cta'                     : 'Kaydet ve Devam Et',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maksimum Giriş Sayısına Ulaşıldı',
  'editor_show_hide'                    : 'Göster/Gizle',
  'editor_editing_badge'                : 'Düzenleniyor',
  'editor_field_required'               : 'Zorunlu',
  'editor_tooltip_edit'                 : 'Düzenle',
  'editor_tooltip_delete'               : 'Sil',
  'editor_date_start'                   : 'Başlangıç Tarihi *',
  'editor_date_end'                     : 'Bitiş Tarihi *',
  'editor_date_tap_hint'                : 'Seçmek için dokunun',
  'editor_date_dialog_title'            : 'Ay ve Yıl Seçin',
  'editor_date_confirm'                 : 'Onayla',
  'editor_panel_hide'                   : 'Gizle',
  'editor_panel_show'                   : 'Göster',
  'editor_validator_max_chars'          : 'Maks. {n} karakter',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Özgeçmişinizi Oluşturun',
  'editor_header_step_sub'              : 'Adım {current} / {total} · {label}',
  'editor_step_template'                : 'Şablon',
  'editor_step_personal'                : 'Kişisel',
  'editor_step_experience'              : 'Deneyim',
  'editor_step_education'               : 'Eğitim',
  'editor_step_skills'                  : 'Beceriler',
  'editor_step_additional'              : 'Ek Bilgi',
  'editor_step_references'              : 'Referanslar',
  'editor_step_customize'               : 'Özelleştir',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Özelleştir',
  'customize_subtitle'                  : 'Özgeçmişinizi size özel yapın',
  'customize_smart_layout_btn'          : 'Akıllı Düzen',
  'customize_back_to_top'               : 'Başa Dön',
  'customize_done_title'                : 'Her şey hazır!',
  'customize_done_sub'                  : 'Bitmiş özgeçmişinizi görmek için aşağıda Özgeçmişi Önizle\'ye dokunun',
  'customize_preview_btn'               : 'Özgeçmişi Önizle',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Renk Şeması',
  'color_black'                         : 'Siyah',
  'color_blue'                          : 'Mavi',
  'color_nordic_blue'                   : 'İskandinav Mavisi',
  'color_indigo'                        : 'İndigo',
  'color_teal'                          : 'Deniz Mavisi',
  'color_green'                         : 'Yeşil',
  'color_purple'                        : 'Mor',
  'color_orange'                        : 'Turuncu',
  'color_red'                           : 'Kırmızı',
  'color_executive_gold'                : 'Yönetici Altını',
  'color_vibrant_coral'                 : 'Canlı Mercan',
  'color_white'                         : 'Beyaz',
  'color_white_bg'                      : 'Beyaz Arka Plan',
  'color_maroon'                        : 'Bordo',
  'color_brutalist_yellow'              : 'Brutalist Sarı',
  'color_neon_blue'                     : 'Neon Mavi',
  'color_blueprint_navy'                : 'Blueprint Lacivert',
  'color_light_grey'                    : 'Açık Gri',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Yazı Tipi Ailesi',
  'customize_font_picker_title'         : 'Yazı Tipi Seçin',
  'customize_font_picker_sub'           : 'Her yazı tipi kendi karakteriyle önizlenir',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Yazı Tipi Boyutu',
  'customize_font_size_label'           : 'Metin Boyutu',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Resim Boyutu',
  'customize_image_size_label'          : 'Resim Boyutu',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Canlı Önizleme',
  'preview_page_count_singular'         : '1 sayfa',
  'preview_page_count_plural'           : '{n} sayfa',
  'preview_page_of'                     : 'Sayfa {page} / {total}',
  'preview_live_hint'                   : 'Değişiklikler anında uygulanır',
  'preview_template_unregistered'       : 'customize_preview.dart içinde henüz kayıtlı değil',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Özgeçmişiniz hazırlanıyor…',
  'preview_bar_print'                   : 'Yazdır',
  'preview_bar_save_pdf'                : 'PDF Olarak Kaydet',
  'preview_bar_share'                   : 'Paylaş',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Özgeçmiş Önizleme',
  'preview_screen_sub'                  : '{n} {unit} · tam olarak yazdırıldığı gibi',
  'preview_page_singular'               : 'sayfa',
  'preview_page_plural'                 : 'sayfa',
  'preview_pdf_filename'                : 'Ozgecmisim',
  'preview_share_subject'               : 'Özgeçmişim',
  'preview_snack_print_failed'          : 'Yazdırma başarısız: {e}',
  'preview_snack_saved'                 : 'Özgeçmiş İndirilenler\'e kaydedildi ✓',
  'preview_snack_export_failed'         : 'Dışa aktarma başarısız: {e}',
  'preview_snack_share_failed'          : 'Paylaşım başarısız: {e}',
  'preview_template_not_registered'     : 'Şablon kayıtlı değil',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Önizlemeyi kapat',
  'preview_modal_hint_photo'            : 'Profil fotoğrafını destekler  ·  Seçmek için bir karta dokunun',
  'preview_modal_hint_no_photo'         : 'Seçmek için bir şablon kartına dokunun',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Özgeçmişim',
  'time_just_now'                       : 'Az önce',
  'time_minutes_ago'                    : '{n} dk önce',
  'time_hours_ago'                      : '{n} sa önce',
  'time_yesterday'                      : 'Dün',
  'time_days_ago'                       : '{n} gün önce',
  'time_one_week_ago'                   : '1 hafta önce',
  'time_weeks_ago'                      : '{n} hafta önce',

  // ─── preview_registry.dart — tag labels ─────────────────────────────────
  'tpl_tag_elegant'                     : 'Zarif',
  'tpl_tag_classic'                     : 'Klasik',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Yaratıcı',
  'tpl_tag_bold'                        : 'Cesur',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────
  'tpl_gradient_name'                   : 'Gradyan',
  'tpl_gradient_desc'                   : 'Deniz mavisi ile mora gradyan kartlar',
  'tpl_editorial_name'                  : 'Editoryal',
  'tpl_editorial_desc'                  : 'Dergi stili kırmızı ve krem',
  'tpl_pastel_soft_name'                : 'Pastel Yumuşak',
  'tpl_pastel_soft_desc'                : 'Lavanta kenar çubuğu, yumuşak kartlar',
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Ham ızgara, kalın kenarlıklar ve sarı',
  'tpl_emerald_name'                    : 'Zümrüt',
  'tpl_emerald_desc'                    : 'Zaman çizelgeli orman yeşili',
  'tpl_infographic_name'                : 'İnfografik',
  'tpl_infographic_desc'                : 'Halka grafikli koyu arka plan',
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920\'ler geometrik altın lüksü',
  'tpl_wina_dark_name'                  : 'Wina Koyu',
  'tpl_wina_dark_desc'                  : 'Halkalı koyu infografik',
  'tpl_rio_orange_name'                 : 'Rio Turuncu',
  'tpl_rio_orange_desc'                 : 'Turuncu vurgulu koyu kenar çubuğu',
  'tpl_summer_name'                     : 'Yaz',
  'tpl_summer_desc'                     : 'Temiz minimal, yumuşak gri tonlar',
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Sıcak bej zarif tonlar',
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Sert siyah ve beyaz klasik',
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'ATS uyumlu klasik düzen',
  'tpl_tony_dark_name'                  : 'Tony Koyu',
  'tpl_tony_dark_desc'                  : 'Koyu turuncu infografik stil',
  'tpl_fashion_name'                    : 'Moda',
  'tpl_fashion_desc'                    : 'Izgara üzerinde teknik çizim',
  'tpl_archivist_name'                  : 'Arşivci',
  'tpl_archivist_desc'                  : 'Klasik iki sütunlu etiket düzeni',
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Elmas başlıklı gölgeli üstbilgiler',
  'tpl_meridian_name'                   : 'Meridyen',
  'tpl_meridian_desc'                   : 'Ortalanmış üstbilgiler, vurgulu şirketler',
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Kalın isim, zaman çizelgesi noktaları ve başarılar',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Kişisel Bilgiler',
  'personal_subtitle'                   : 'İşverenlere kendinizi tanıtın',
  'personal_profile_counter'            : '{n}/{max} profil',
  'personal_info_banner'                : '5\'e kadar profil kaydedin ve her özgeçmiş için birini seçin. Seçiminiz her özgeçmiş için ayrı ayrı hatırlanır.',
  'personal_snack_max'                  : 'Maksimum {n} profile ulaşıldı.',
  'personal_add_btn'                    : 'Yeni Profil Ekle',
  'personal_library_title'              : 'Kayıtlı Profiller',
  'personal_selected_one'               : '1 seçili',
  'personal_selected_none'              : 'hiçbiri seçili değil',
  'personal_library_hint'               : 'Yalnızca bu özgeçmiş için seçmek üzere bir karta dokunun. Diğer özgeçmişler kendi bağımsız seçimlerini korur.',
  'personal_empty_message'              : 'Henüz profil kaydedilmedi',
  'personal_empty_sub'                  : 'Kişisel bilgilerinizi eklemek için yukarıya dokunun',
  'personal_nav_next'                   : 'Kaydet ve Devam Et',
  'personal_card_active_badge'          : 'Bu Özgeçmiş için Aktif',
  'personal_sheet_title_add'            : 'Yeni Profil',
  'personal_sheet_title_edit'           : 'Profili Düzenle',
  'personal_sheet_brutalist_badge'      : 'BRUTALİST',
  'personal_sheet_brutalist_banner'     : 'Brutalist şablon kompakt iletişim alanlarına sahiptir. Kısa değerler (örn. yalnızca şehir) en iyi görünümü sağlar.',
  'personal_section_photo'              : 'Profil Fotoğrafı',
  'personal_section_basic'              : 'Temel Bilgiler',
  'personal_section_contact'            : 'İletişim',
  'personal_section_online'             : 'Çevrimiçi Varlık',
  'personal_section_summary'            : 'Profesyonel Özet',
  'personal_field_first_name'           : 'Ad *',
  'personal_field_last_name'            : 'Soyad',
  'personal_field_job_title'            : 'İş Unvanı *',
  'personal_field_email'                : 'E-posta Adresi *',
  'personal_field_phone'                : 'Telefon Numarası *',
  'personal_field_location'             : 'Konum',
  'personal_field_location_brut'        : 'Konum (yalnızca şehir)',
  'personal_field_website'              : 'Web Sitesi / Portfolyo',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'Örn. Ayşe',
  'personal_hint_last_name'             : 'Örn. Yılmaz',
  'personal_hint_job_title'             : 'Örn. Kıdemli Mühendis',
  'personal_hint_email'                 : 'Örn. ayse@example.com',
  'personal_hint_phone'                 : 'Örn. +90 532 123 45 67',
  'personal_hint_location'              : 'Örn. İstanbul, Türkiye',
  'personal_hint_location_brut'         : 'Örn. İstanbul, TR',
  'personal_hint_website'               : 'Örn. github.com/ayseyilmaz',
  'personal_hint_website_brut'          : 'Örn. github.com/ayse',
  'personal_hint_linkedin'              : 'Örn. linkedin.com/in/ayseyilmaz',
  'personal_hint_linkedin_brut'         : 'Örn. linkedin.com/in/ayse',
  'personal_summary_hint_label'         : 'Kısa tutun — bu özgeçmişinizin en üstünde görünür.',
  'personal_hint_summary'               : 'Geçmişinizin ve hedeflerinizin kısa 2–3 cümlelik özeti...',
  'personal_validator_email'            : 'Geçerli bir e-posta girin',
  'personal_field_char_limit_tooltip'   : 'Karakter sınırına ulaşıldı',
  'personal_sheet_btn_save'             : 'Profili Kaydet',
  'personal_sheet_btn_update'           : 'Değişiklikleri Kaydet',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Fotoğraf Seç',
  'photo_option_gallery'                : 'Galeriden Seç',
  'photo_option_camera'                 : 'Fotoğraf Çek',
  'photo_option_reposition'             : 'Fotoğrafı Yeniden Konumlandır',
  'photo_option_remove'                 : 'Fotoğrafı Kaldır',
  'photo_status_added'                  : 'Fotoğraf eklendi ✓',
  'photo_status_empty'                  : 'Profesyonel bir vesikalık ekleyin',
  'photo_chip_gallery'                  : 'Galeri',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Yeniden Konumlandır',
  'photo_reposition_title'              : 'Fotoğrafı Yeniden Konumlandır',
  'photo_reposition_sub'                : 'Konumu ayarlamak için fotoğrafı sürükleyin',
  'photo_reposition_reset'              : 'Ortaya sıfırla',
  'photo_reposition_apply'              : 'Uygula',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Beceriler',
  'skills_subtitle'                     : 'Temel yeteneklerinizi öne çıkarın',
  'skills_add_btn'                      : 'Yeni Beceri Ekle',
  'skills_snack_max_icons'              : 'Maksimum 10 simge seçildi.',
  'skills_snack_max_skills'             : 'Maksimum 15 beceriye ulaşıldı.',
  'skills_library_title'                : 'Kayıtlı Beceriler',
  'skills_library_hint'                 : 'İşaretli beceriler bu özgeçmişe dahil edilir. Seçimleriniz otomatik olarak kaydedilir.',
  'skills_nav_next'                     : 'Ek Bilgilere Devam Et',
  'skills_wina_header_icon_bar'         : 'Başlık Simge Çubuğu',
  'skills_wina_on'                      : 'AÇIK',
  'skills_wina_off'                     : 'KAPALI',
  'skills_wina_bar_on_sub'              : 'Renkli simge daireleri özgeçmiş başlığında gösterilir.',
  'skills_wina_bar_off_sub'             : 'Simge satırı gizli — iletişim bilgileri için daha fazla alan.',
  'skills_wina_palette_hint'            : 'Simgeler paletteki sıralamaya göre renkli daireler olarak görünür.',
  'skills_wina_preview_label'           : 'Önizleme',
  'skills_wina_disabled_hint'           : 'Özgeçmiş başlığında hangi simgelerin görüneceğini seçmek için yukarıdaki simge çubuğunu etkinleştirin.',
  'skills_sheet_title_add'              : 'Beceri Ekle',
  'skills_sheet_title_edit'             : 'Beceriyi Düzenle',
  'skills_sheet_field_name'             : 'Beceri Adı *',
  'skills_sheet_hint_short'             : 'Örn. Flutter, Tasarım',
  'skills_sheet_hint_long'              : 'Örn. Flutter, Proje Yönetimi',
  'skills_sheet_validator_max'          : 'Maks. {n} karakter',
  'skills_sheet_proficiency'            : 'Yeterlilik Düzeyi',
  'skills_sheet_beginner'               : 'Başlangıç',
  'skills_sheet_expert'                 : 'Uzman',
  'skills_sheet_btn_save'               : 'Beceriyi Kaydet',
  'skills_sheet_btn_update'             : 'Beceriyi Güncelle',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Kişisel Referanslar',
  'refs_subtitle'                       : 'Sizin için kişisel olarak kefil olabilecek kişiler',
  'refs_add_btn'                        : 'Yeni Kişisel Referans Ekle',
  'refs_snack_max_selected'             : 'Bir özgeçmiş için en fazla 4 referans seçilebilir.',
  'refs_snack_max_saved'                : 'Maksimum 10 kayıtlı referansa ulaşıldı.',
  'refs_library_title'                  : 'Kayıtlı Referanslar',
  'refs_library_hint'                   : 'İşaretli referanslar bu özgeçmişe dahil edilir. Özgeçmiş başına maks. 4. Seçimleriniz otomatik olarak kaydedilir.',
  'refs_nav_next'                       : 'Özelleştirmeye Devam Et',
  'refs_sheet_title_add'                : 'Kişisel Referans Ekle',
  'refs_sheet_title_edit'               : 'Kişisel Referansı Düzenle',
  'refs_sheet_sub_add'                  : 'Sizi işverenlere kişisel olarak önerebilecek biri.',
  'refs_sheet_sub_edit'                 : 'Bu referansın bilgilerini aşağıda güncelleyin.',
  'refs_sheet_field_name'               : 'Ad Soyad *',
  'refs_sheet_field_title'              : 'İş Unvanı *',
  'refs_sheet_field_company'            : 'Şirket (isteğe bağlı)',
  'refs_sheet_field_email'              : 'E-posta Adresi *',
  'refs_sheet_field_phone'              : 'Telefon Numarası *',
  'refs_sheet_hint_name'                : 'Örn. Ahmet Yıldız',
  'refs_sheet_hint_title'               : 'Örn. Mühendislik Müdürü',
  'refs_sheet_hint_company'             : 'Örn. Acme Corp',
  'refs_sheet_hint_email'               : 'Örn. ahmet@acme.com',
  'refs_sheet_hint_phone'               : 'Örn. +90 532 123 45 67',
  'refs_sheet_validator_email'          : 'Geçerli bir e-posta adresi girin',
  'refs_sheet_btn_save'                 : 'Kişisel Referansı Kaydet',
  'refs_sheet_btn_update'               : 'Kişisel Referansı Güncelle',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'İş Deneyimi',
  'exp_subtitle'                        : 'İş geçmişinizi ekleyin',
  'exp_banner_info'                     : 'Rol başına en fazla {n} sorumluluk özgeçmişte görünecektir. 3–6 rol genellikle 1–2 sayfaya sığar.',
  'exp_add_btn'                         : 'Yeni Deneyim Ekle',
  'exp_snack_max_selected'              : 'Bir özgeçmiş için en fazla 8 deneyim seçilebilir.',
  'exp_snack_max_saved'                 : 'Maksimum 12 kayıtlı deneyime ulaşıldı.',
  'exp_library_title'                   : 'Kayıtlı Deneyimler',
  'exp_library_hint'                    : 'İşaretli girişler yalnızca bu özgeçmişe dahil edilir. Diğer özgeçmişler kendi bağımsız seçimlerini korur.',
  'exp_nav_next'                        : 'Eğitime Devam Et',
  'exp_empty_message'                   : 'Henüz deneyim eklenmedi',
  'exp_empty_sub'                       : 'İlk rolünüzü eklemek için yukarıya dokunun',
  'exp_card_resp_singular'              : 'sorumluluk',
  'exp_card_resp_plural'                : 'sorumluluk',
  'exp_card_resp_tooltip'               : 'Yalnızca ilk 8 sorumluluk özgeçmişte görünecektir',
  'exp_sheet_title_add'                 : 'Deneyim Ekle',
  'exp_sheet_title_edit'                : 'Deneyimi Düzenle',
  'exp_sheet_field_job_title'           : 'İş Unvanı *',
  'exp_sheet_field_company'             : 'Şirket *',
  'exp_sheet_field_location'            : 'Konum',
  'exp_sheet_section_responsibilities'  : 'Temel Sorumluluklar',
  'exp_sheet_resp_hint_info'            : 'Maks. 8 madde · her biri 200 karakter',
  'exp_sheet_resp_label'                : 'Sorumluluk {n}',
  'exp_sheet_resp_hint'                 : 'Örn. 5 kişilik mühendis ekibine liderlik etti',
  'exp_sheet_resp_add_btn'              : 'Sorumluluk Ekle',
  'exp_sheet_resp_max_info'             : 'Maksimum {n} sorumluluğa ulaşıldı',
  'exp_sheet_resp_validator_max'        : 'Maks. 200 karakter',
  'exp_sheet_hint_job_title'            : 'Örn. Kıdemli Geliştirici',
  'exp_sheet_hint_location'             : 'Örn. İstanbul, Türkiye',
  'exp_sheet_btn_save'                  : 'Deneyimi Kaydet',
  'exp_sheet_btn_update'                : 'Değişiklikleri Kaydet',
  'exp_date_present'                    : 'Şu An / Devam Eden Görev',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Eğitim',
  'edu_subtitle'                        : 'Akademik geçmişinizi ekleyin',
  'edu_add_btn'                         : 'Yeni Eğitim Ekle',
  'edu_snack_max_selected'              : 'Bir özgeçmiş için en fazla 8 eğitim girişi seçilebilir.',
  'edu_snack_max_saved'                 : 'Maksimum 12 kayıtlı eğitim girişine ulaşıldı.',
  'edu_library_title'                   : 'Kayıtlı Eğitimler',
  'edu_library_hint'                    : 'İşaretli girişler bu özgeçmişe dahil edilir. Seçimleriniz otomatik olarak kaydedilir.',
  'edu_nav_next'                        : 'Becerilere Devam Et',
  'edu_empty_message'                   : 'Henüz eğitim eklenmedi',
  'edu_empty_sub'                       : 'Niteliklerinizi eklemek için yukarıya dokunun',
  'edu_card_bullet_singular'            : 'madde',
  'edu_card_bullet_plural'              : 'madde',
  'edu_sheet_title_add'                 : 'Eğitim Ekle',
  'edu_sheet_title_edit'                : 'Eğitimi Düzenle',
  'edu_sheet_field_degree'              : 'Derece / Nitelik *',
  'edu_sheet_field_institution'         : 'Kurum *',
  'edu_sheet_section_key_points'        : 'Önemli Noktalar',
  'edu_sheet_key_points_hint_info'      : 'İsteğe bağlı · 1 madde · maks. 100 karakter',
  'edu_sheet_point_label'               : 'Madde {n}',
  'edu_sheet_point_add_btn'             : 'Madde Ekle',
  'edu_sheet_point_max_info'            : 'Maksimum {n} maddeye ulaşıldı',
  'edu_sheet_point_validator_max'       : 'Maks. {n} karakter',
  'edu_sheet_hint_degree'               : 'Örn. Bilgisayar Mühendisliği Lisansı',
  'edu_sheet_hint_institution'          : 'Örn. İstanbul Teknik Üniversitesi',
  'edu_sheet_hint_bullet'               : 'Örn. Birinci Sınıf Onur',
  'edu_sheet_btn_save'                  : 'Eğitimi Kaydet',
  'edu_sheet_btn_update'                : 'Değişiklikleri Kaydet',
  'edu_date_present'                    : 'Şu An / Devam Eden Eğitim',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Ek Bilgiler',
  'additional_subtitle'                 : 'Sertifikalar, diller ve daha fazlası',
  'additional_cert_section_title'       : 'Sertifikalar',
  'additional_cert_counter'             : '{sel}/{total} seçili · maks. {max}',
  'additional_cert_hide'                : 'Gizle',
  'additional_cert_show'                : 'Göster',
  'additional_cert_add_btn'             : 'Ekle',
  'additional_cert_snack_max'           : 'Maksimum {n} sertifika girişine ulaşıldı.',
  'additional_cert_hint'                : 'İşaretli girişler bu özgeçmişe dahil edilir. Seçimleriniz otomatik olarak kaydedilir.',
  'additional_cert_empty'               : 'Henüz sertifika eklenmedi',
  'additional_lang_section_title'       : 'Diller',
  'additional_lang_add_hint'            : 'Örn. İspanyolca',
  'additional_lang_snack_max'           : 'Maksimum {n} dil girişine ulaşıldı.',
  'additional_lang_empty'               : 'Henüz dil eklenmedi',
  'additional_hobby_section_title'      : 'Hobiler ve İlgi Alanları',
  'additional_hobby_add_hint'           : 'Örn. Fotoğrafçılık',
  'additional_hobby_snack_max'          : 'Maksimum {n} hobi girişine ulaşıldı.',
  'additional_hobby_empty'              : 'Henüz hobi eklenmedi',
  'additional_section_hint'             : 'İşaretli girişler bu özgeçmişe dahil edilir. Seçimleriniz otomatik olarak kaydedilir.',
  'additional_nav_next'                 : 'Referanslara Devam Et',
  'cert_sheet_title_add'                : 'Sertifika Ekle',
  'cert_sheet_title_edit'               : 'Sertifikayı Düzenle',
  'cert_sheet_sub'                      : 'Bir nitelik, sertifika veya profesyonel kimlik bilgisi ekleyin.',
  'cert_sheet_field_name'               : 'Sertifika Adı *',
  'cert_sheet_field_issued_by'          : 'Veren Kurum (isteğe bağlı)',
  'cert_sheet_field_short_desc'         : 'Kısa Açıklama (isteğe bağlı)',
  'cert_sheet_hint_name'                : 'Örn. AWS Çözüm Mimarı',
  'cert_sheet_hint_issued_by'           : 'Örn. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'Örn. 2024\'te alındı',
  'cert_sheet_btn_save'                 : 'Sertifikayı Kaydet',
  'cert_sheet_btn_update'               : 'Sertifikayı Güncelle',
  'simple_sheet_title_add_language'     : 'Dil Ekle',
  'simple_sheet_title_edit_language'    : 'Dili Düzenle',
  'simple_sheet_title_add_hobby'        : 'Hobi Ekle',
  'simple_sheet_title_edit_hobby'       : 'Hobiyi Düzenle',
  'simple_sheet_btn_save'               : 'Kaydet',
  'simple_sheet_btn_update'             : 'Güncelle',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'İletişim',
  'pdf_section_about_me'                : 'Hakkımda',
  'pdf_section_summary'                 : 'Özet',
  'pdf_section_summary_short'           : 'Özet',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Deneyim',
  'pdf_section_experience_short'        : 'Deneyim',
  'pdf_section_education'               : 'Eğitim',
  'pdf_section_skills'                  : 'Beceriler',
  'pdf_section_languages'               : 'Diller',
  'pdf_label_email'                     : 'E-posta',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Konum',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV Limiti Aşıldı',
  'limit_dialog_body'                   : '30 CV limitine ulaştınız. Yeni bir tane oluşturmadan önce mevcut bir CV\'yi silin.',
  'limit_dialog_go_to_my_cvs'           : 'CV\'lerime Git',
  'limit_dialog_cancel'                 : 'İptal',
  'refs_count_summary'                  : '{checked}/{maxChecked} seçildi · {saved}/{maxSaved} kaydedildi',
  'refs_selected_badge'                 : '{n} seçildi',
  'refs_empty_message'                  : 'Henüz kayıtlı referans yok',
  'refs_empty_sub'                      : 'Kişisel referans eklemek için yukarıya dokunun',
};