// lib/language_keys/lang_no_norwegian.dart
//
// Norwegian (Bokmål) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> noNorwegian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Ingen språk funnet',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Hopp over',
  'onboarding_next'                     : 'Neste',
  'onboarding_get_started'              : 'Kom i gang',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Velkommen',
  'ob1_title'                           : 'Lag en CV som\nåpner dører',
  'ob1_body'                            : 'Skill deg ut blant hundrevis av søkere. Bygg en polert, jobbvinnende CV på minutter — ingen designferdigheter nødvendig.',
  'ob1_pill_label'                      : 'Profesjonell CV-bygger',
  'ob1_chip_templates'                  : '24+ maler',
  'ob1_chip_pdf'                        : 'PDF-eksport',
  'ob1_chip_free'                       : 'Gratis å bruke',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Maler',
  'ob2_title'                           : 'Hver bransje.\nEver ambisjon.',
  'ob2_body'                            : 'Fra styreromklare oppsett til dristige kreative design — en mal som forteller din historie.',
  'ob2_tap_hint'                        : 'Trykk på en mal for å forhåndsvise',
  'ob2_tpl_executive'                   : 'Leder',
  'ob2_tpl_vibrant'                     : 'Livlig',
  'ob2_tpl_nordic'                      : 'Nordisk',
  'ob2_tpl_tech_dark'                   : 'Tech Mørk',
  'ob2_tpl_luxury'                      : 'Luksus',
  'ob2_tag_corporate'                   : 'Bedrift',
  'ob2_tag_creative'                    : 'Kreativ',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Moderne',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart oppsett',
  'ob3_title'                           : 'Din CV.\nPerfekt arrangert.',
  'ob3_body'                            : 'Smart oppsett omorganiserer seksjonene dine for maksimal effekt — og plasserer det sterkeste innholdet der rekrutterere ser først.',
  'ob3_badge_smart_layout'              : 'Smart oppsett',
  'ob3_badge_cv_ready'                  : 'CV klar!',
  'ob3_step1_label'                     : 'Velg en mal',
  'ob3_step1_desc'                      : 'Velg blant 24+ flotte design.',
  'ob3_step2_label'                     : 'Fyll inn detaljer',
  'ob3_step2_desc'                      : 'Guidede felt for alle seksjoner.',
  'ob3_step3_label'                     : 'Smart oppsett',
  'ob3_step3_desc'                      : 'Ett trykk omformer CV-en din perfekt.',
  'ob3_step4_label'                     : 'Eksporter som PDF',
  'ob3_step4_desc'                      : 'Piksel-perfekt PDF klar til sending.',
  'ob3_section_work'                    : 'Arbeidserfaring',
  'ob3_section_education'               : 'Utdanning',
  'ob3_section_skills'                  : 'Ferdigheter',
  'ob3_section_references'              : 'Referanser',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Klar til bruk',
  'ob4_title'                           : 'Hvorfor toppkandidater\nvelger CV Builder',
  'ob4_visual_headline'                 : 'Alt er klart!',
  'ob4_visual_subline'                  : 'Alt du trenger for å få jobben.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Maler',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Maks CV-er',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Eksport',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privat',
  'ob4_hl1_title'                       : 'Privat og sikker',
  'ob4_hl1_sub'                         : 'Data lagres på enheten din.',
  'ob4_hl2_title'                       : 'Automatisk lagring',
  'ob4_hl2_sub'                         : 'Hvert tastetrykk lagres umiddelbart.',
  'ob4_hl3_title'                       : 'Opptil 30 CV-er',
  'ob4_hl3_sub'                         : 'Unik CV for hver stilling.',
  'ob4_hl4_title'                       : 'Del med ett trykk',
  'ob4_hl4_sub'                         : 'Send PDF uten å forlate appen.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Skill deg ut fra mengden',
  'home_hero_title'                     : 'Lag din\nprofesjonelle CV',
  'home_hero_sub'                       : 'Bygg en imponerende CV\npå minutter',
  'home_hero_cta'                       : 'Begynn å bygge',
  'home_premium_soon'                   : 'Oppgradering til Pro kommer snart!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Nyeste først',
  'history_sort_alphabetical'           : 'A–Å',
  'history_sort_last_edited'            : 'Sist redigert',
  'history_sort_by_template'            : 'Etter mal',
  'history_sort_sheet_title'            : 'Sorter etter',
  'history_sort_alphabetical_full'      : 'Alfabetisk (A–Å)',
  'history_premium_soon'                : 'Oppgradering til Pro kommer snart!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Innstillinger',
  'settings_section_preferences'        : 'Preferanser',
  'settings_section_support'            : 'Støtte',
  'settings_section_legal'              : 'Juridisk',
  'settings_section_about'              : 'Om',
  'settings_language_tile_title'        : 'Språk',
  'settings_dark_mode_title'            : 'Mørk modus',
  'settings_dark_mode_on'               : 'Mørkt tema aktivert',
  'settings_dark_mode_off'              : 'Lyst tema aktivert',
  'settings_help_faq_title'             : 'Hjelp og FAQ',
  'settings_help_faq_sub'               : 'Vanlige spørsmål besvart',
  'settings_contact_support_title'      : 'Kontakt støtte',
  'settings_rate_app_title'             : 'Vurder appen',
  'settings_rate_app_sub'               : 'Liker du appen? Legg igjen en anmeldelse!',
  'settings_privacy_policy_title'       : 'Personvernregler',
  'settings_terms_title'                : 'Vilkår for bruk',
  'settings_app_version_title'          : 'Appversjon',
  'settings_email_error'                : 'Kunne ikke åpne e-postappen. Send e-post til cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CV-forhåndsvisning',
  'preview_header_sub'                  : 'Klar til eksport',
  'preview_generating'                  : 'Genererer CV-en din...',
  'preview_failed_title'                : 'Forhåndsvisning mislyktes',
  'preview_failed_error'                : 'Feil: {error}',
  'preview_go_back'                     : 'Gå tilbake',
  'preview_no_data'                     : 'Ingen data tilgjengelig',
  'preview_btn_print'                   : 'Skriv ut',
  'preview_btn_download'                : 'Last ned og del',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Hjelp og FAQ',
  'faq_category_all'                    : 'Alle',
  'faq_empty'                           : 'Ingen resultater funnet',
  'faq_contact_headline'                : 'Trenger du fortsatt hjelp?',
  'faq_contact_sub'                     : 'Teamet vårt er her for deg.',
  'faq_contact_btn'                     : 'Kontakt',
  'faq_email_error'                     : 'Kunne ikke åpne e-postappen. Send e-post til cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Kom i gang',
  'faq_cat_templates'                   : 'Maler',
  'faq_cat_editing'                     : 'Redigering',
  'faq_cat_exporting'                   : 'Eksport',
  'faq_cat_data_privacy'                : 'Data og personvern',
  'faq_cat_troubleshooting'             : 'Feilsøking',
  'faq_q1'  : 'Hvordan lager jeg min første CV?',
  'faq_a1'  : 'Trykk på "+"-knappen på startskjermen for å starte en ny CV. Velg en mal som passer din stil, og fyll deretter inn personlige opplysninger, arbeidserfaring, utdanning og ferdigheter steg for steg. Fremdriften din lagres automatisk.',
  'faq_q2'  : 'Kan jeg lage mer enn én CV?',
  'faq_a2'  : 'Ja! Du kan lage flere CV-er for ulike roller eller bransjer. Hver CV lagres separat, slik at du kan tilpasse dem til spesifikke jobbsøknader.',
  'faq_q3'  : 'Hvordan endrer jeg CV-malen?',
  'faq_a3'  : 'Åpne CV-en din, trykk på malminiaturikonet øverst på skjermen, og bla gjennom tilgjengelige maler. Trykk på en mal for å forhåndsvise den med ditt eksisterende innhold. Bekreft for å bruke den.',
  'faq_q4'  : 'Finnes det gratis og premium-maler?',
  'faq_a4'  : 'Ja. Et utvalg profesjonelle maler er tilgjengelig gratis. Premium-maler med avanserte design og fargepaletter er tilgjengelige via et engangskjøp eller abonnement.',
  'faq_q5'  : 'Hvordan legger jeg til eller fjerner seksjoner?',
  'faq_a5'  : 'I CV-redigereren ruller du til bunnen av skjermen og trykker på "Legg til seksjon" for å inkludere ekstra som Språk, Sertifiseringer eller Frivillig arbeid. For å fjerne en seksjon trykker du på seksjonsoverskriften og velger "Fjern".',
  'faq_q6'  : 'Hvordan omordner jeg seksjoner?',
  'faq_a6'  : 'Trykk lenge på drahåndtaket (≡) ved siden av en seksjonsoverskrift og dra det til ønsket posisjon. Endringer lagres automatisk.',
  'faq_q7'  : 'Hvordan eksporterer jeg CV-en som PDF?',
  'faq_a7'  : 'Åpne CV-en og trykk på eksportknappen (delingsikon) øverst til høyre. Velg "Eksporter som PDF". Du kan deretter lagre den på enheten din, dele den via e-post, WhatsApp, eller laste den opp direkte til jobbportaler.',
  'faq_q8'  : 'Hvilke filformater støttes?',
  'faq_a8'  : 'Appen støtter for øyeblikket eksport av CV-en som en høykvalitets PDF. Ytterligere formater kan bli lagt til i fremtidige oppdateringer.',
  'faq_q9'  : 'Hvor lagres CV-dataene mine?',
  'faq_a9'  : 'Alle CV-dataene dine lagres lokalt på enheten din. Vi laster ikke opp personlig informasjon til serverne våre. Det betyr at dataene dine forblir private og tilgjengelige uten internett.',
  'faq_q10' : 'Hvordan sikkerhetskopierer jeg CV-ene mine?',
  'faq_a10' : 'CV-ene dine er inkludert i enhetens standardsikkerhetskopi (Google Drive-sikkerhetskopi på Android, iCloud på iOS) hvis du har aktivert sikkerhetskopiering i enhetsinnstillingene. Du kan også eksportere individuelle CV-er som PDF-er for å beholde en kopi.',
  'faq_q11' : 'Appen går sakte. Hva bør jeg gjøre?',
  'faq_a11' : 'Prøv å lukke og åpne appen på nytt. Hvis problemet vedvarer, start enheten på nytt. Sørg for at du har den nyeste versjonen av appen installert fra Play Store / App Store.',
  'faq_q12' : 'CV-en min eksporteres ikke riktig. Hva bør jeg gjøre?',
  'faq_a12' : 'Sørg for at du har nok lagringsplass på enheten. Prøv å redusere store bilder i CV-en. Hvis problemet fortsetter, vennligst kontakt supportteamet vårt.',
  'faq_q13' : 'Jeg glemte å lagre — er arbeidet mitt tapt?',
  'faq_a13' : 'Ikke i det hele tatt! Appen lagrer fremdriften din kontinuerlig mens du redigerer.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Din karriere, perfeksjonert',
  'header_tooltip_back'                 : 'Tilbake',
  'header_tooltip_my_cvs'               : 'Mine CV-er',
  'header_tooltip_settings'             : 'Innstillinger',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Mine CV-er',
  'saved_count_single'                  : '{n} dokument',
  'saved_count_plural'                  : '{n} dokumenter',
  'saved_limit_reached'                 : 'Grense nådd',
  'saved_footer_count'                  : '{n} / 30 CV-er',
  'saved_filter_all'                    : 'Alle',
  'saved_filter_draft'                  : 'Utkast',
  'saved_filter_complete'               : 'Fullstendig',
  'saved_status_complete'               : 'Fullstendig',
  'saved_status_saved'                  : 'Lagret',
  'saved_status_draft'                  : 'Utkast',
  'saved_empty_title'                   : 'Ingen CV-er her ennå',
  'saved_empty_sub'                     : 'Begynn å bygge din første CV ovenfor',
  'saved_search_empty_title'            : 'Ingen resultater funnet',
  'saved_search_empty_sub'              : 'Prøv et annet søkeord',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Fargevalg',
  'custom_font_settings_title'          : 'Skriftinnstillinger',
  'custom_font_family_label'            : 'Skriftfamilie',
  'custom_font_size_label'              : 'Skriftstørrelse: ',
  'custom_current_template_title'       : 'Gjeldende mal',
  'custom_change_template_btn'          : 'Bytt mal',
  'custom_tpl_modern'                   : 'Moderne',
  'custom_tpl_classic'                  : 'Klassisk',
  'custom_tpl_professional'             : 'Profesjonell',
  'custom_tpl_creative'                 : 'Kreativ',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Rent og tidløst design',
  'custom_tpl_classic_desc'             : 'Tradisjonelt profesjonelt oppsett',
  'custom_tpl_professional_desc'        : 'Bedriftsfokusert mal',
  'custom_tpl_creative_desc'            : 'Skill deg ut med unikt design',
  'custom_tpl_minimal_desc'             : 'Enkel og elegant stil',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Velg mal',
  'swipe_photo_badge'                   : 'Bilde',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Leder',
  'tpl_nordic_name'                     : 'Nordisk',
  'tpl_vibrant_name'                    : 'Livlig',
  'tpl_tech_dark_name'                  : 'Tech Mørk',
  'tpl_luxury_name'                     : 'Luksus',
  'tpl_executive_tag'                   : 'Mest populær',
  'tpl_nordic_tag'                      : 'Ren',
  'tpl_vibrant_tag'                     : 'Kreativ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Dristig og autoritativ for seniorroller',
  'tpl_nordic_desc'                     : 'Minimal klarhet betrodd av toppfirmaer',
  'tpl_vibrant_desc'                    : 'Skill deg ut med energi og farge',
  'tpl_tech_dark_desc'                  : 'Terminaldesign for utviklere',
  'tpl_luxury_desc'                     : 'Gulldekorert prestisje på sort',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Mal',
  'detail_step_personal'                : 'Personlig',
  'detail_step_experience'              : 'Erfaring',
  'detail_step_education'               : 'Utdanning',
  'detail_step_skills'                  : 'Ferdigheter',
  'detail_step_additional'              : 'Tillegg',
  'detail_step_references'              : 'Referanser',
  'detail_step_customize'               : 'Tilpass',
  'detail_banner_heading'               : 'Nesten ferdig!',
  'detail_banner_btn'                   : 'Fortsett',
  'detail_banner_completion_label'      : 'Fullføring',
  'detail_stat_created_label'           : 'Opprettet',
  'detail_stat_steps_label'             : 'Steg fullført',
  'detail_section_template_style'       : 'Malstil',
  'detail_section_steps'                : 'Steg',
  'detail_steps_counter'                : '{done} av {total} fullført',
  'detail_step_sub'                     : 'Steg {n} av {total}',
  'detail_section_activity'             : 'Aktivitet',
  'detail_activity_created'             : 'Opprettet',
  'detail_activity_last_edited'         : 'Sist redigert',
  'detail_activity_template'            : 'Mal',
  'detail_btn_continue_editing'         : 'Fortsett redigering',
  'detail_btn_edit_cv'                  : 'Rediger CV',
  'detail_option_rename'                : 'Gi CV-en nytt navn',
  'detail_option_delete'                : 'Slett CV',
  'detail_rename_title'                 : 'Gi CV-en nytt navn',
  'detail_rename_hint'                  : 'f.eks. Programvareutvikler CV',
  'detail_rename_error_empty'           : 'Navn kan ikke være tomt',
  'detail_rename_btn_cancel'            : 'Avbryt',
  'detail_rename_btn_save'              : 'Lagre',
  'detail_rename_snackbar'              : 'Omdøpt til "{name}"',
  'detail_delete_title'                 : 'Slett CV?',
  'detail_delete_body'                  : 'Dette vil permanent slette "{name}". Denne handlingen kan ikke angres.',
  'detail_delete_btn_cancel'            : 'Avbryt',
  'detail_delete_btn_confirm'           : 'Slett',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Fullført',
  'detail_check_tile_incomplete'        : 'Ikke fylt ut ennå',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Velg din mal',
  'chooser_subtitle'                    : 'Sveip for å bla  ·  Trykk for å velge  ·  Hold for forhåndsvisning',
  'chooser_card_hold_hint'              : 'Hold for forhåndsvisning',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Valgt',
  'chooser_modal_heading'               : 'Gi CV-en et navn',
  'chooser_modal_sub'                   : 'Gi den et navn slik at du enkelt finner den i Mine CV-er og Historikk.',
  'chooser_modal_field_label'           : 'CV-navn',
  'chooser_modal_save_btn'              : 'Lagre og begynn å bygge',
  'chooser_modal_divider'               : 'eller fortsett med en eksisterende CV',
  'chooser_nav_selected_sub'            : 'Valgt mal',
  'chooser_nav_cta'                     : 'Lagre og fortsett',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maksimalt antall oppføringer nådd',
  'editor_show_hide'                    : 'Vis/skjul',
  'editor_editing_badge'                : 'Redigerer',
  'editor_field_required'               : 'Obligatorisk',
  'editor_tooltip_edit'                 : 'Rediger',
  'editor_tooltip_delete'               : 'Slett',
  'editor_date_start'                   : 'Startdato *',
  'editor_date_end'                     : 'Sluttdato *',
  'editor_date_tap_hint'                : 'Trykk for å velge',
  'editor_date_dialog_title'            : 'Velg måned og år',
  'editor_date_confirm'                 : 'Bekreft',
  'editor_panel_hide'                   : 'Skjul',
  'editor_panel_show'                   : 'Vis',
  'editor_validator_max_chars'          : 'Maks {n} tegn',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Bygg CV-en din',
  'editor_header_step_sub'              : 'Steg {current} av {total} · {label}',
  'editor_step_template'                : 'Mal',
  'editor_step_personal'                : 'Personlig',
  'editor_step_experience'              : 'Erfaring',
  'editor_step_education'               : 'Utdanning',
  'editor_step_skills'                  : 'Ferdigheter',
  'editor_step_additional'              : 'Tillegg',
  'editor_step_references'              : 'Referanser',
  'editor_step_customize'               : 'Tilpass',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Tilpass',
  'customize_subtitle'                  : 'Gjør CV-en din unikt din',
  'customize_smart_layout_btn'          : 'Smart oppsett',
  'customize_back_to_top'               : 'Tilbake til toppen',
  'customize_done_title'                : 'Alt er klart!',
  'customize_done_sub'                  : 'Trykk på Forhåndsvis CV nedenfor for å se den ferdige CV-en din',
  'customize_preview_btn'               : 'Forhåndsvis CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Fargevalg',
  'color_black'                         : 'Sort',
  'color_blue'                          : 'Blå',
  'color_nordic_blue'                   : 'Nordisk blå',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Blågrønn',
  'color_green'                         : 'Grønn',
  'color_purple'                        : 'Lilla',
  'color_orange'                        : 'Oransje',
  'color_red'                           : 'Rød',
  'color_executive_gold'                : 'Ledergull',
  'color_vibrant_coral'                 : 'Livlig korall',
  'color_white'                         : 'Hvit',
  'color_white_bg'                      : 'Hvit bakgrunn',
  'color_maroon'                        : 'Mørkerød',
  'color_brutalist_yellow'              : 'Brutalistisk gul',
  'color_neon_blue'                     : 'Neonblå',
  'color_blueprint_navy'                : 'Blueprint marineblå',
  'color_light_grey'                    : 'Lysgrå',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Skriftfamilie',
  'customize_font_picker_title'         : 'Velg skrift',
  'customize_font_picker_sub'           : 'Hver skrift forhåndsvises i sin egen skrifttype',
  'customize_font_preview_sample'       : 'Den raske brune reven',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Skriftstørrelse',
  'customize_font_size_label'           : 'Tekststørrelse',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Bildestørrelse',
  'customize_image_size_label'          : 'Bildestørrelse',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Direkteforhåndsvisning',
  'preview_page_count_singular'         : '1 side',
  'preview_page_count_plural'           : '{n} sider',
  'preview_page_of'                     : 'Side {page} av {total}',
  'preview_live_hint'                   : 'Endringer gjelder umiddelbart',
  'preview_template_unregistered'       : 'Ikke registrert i customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Forbereder CV-en din…',
  'preview_bar_print'                   : 'Skriv ut',
  'preview_bar_save_pdf'                : 'Lagre som PDF',
  'preview_bar_share'                   : 'Del',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CV-forhåndsvisning',
  'preview_screen_sub'                  : '{n} {unit} · nøyaktig som utskrift',
  'preview_page_singular'               : 'side',
  'preview_page_plural'                 : 'sider',
  'preview_pdf_filename'                : 'Min_CV',
  'preview_share_subject'               : 'Min CV',
  'preview_snack_print_failed'          : 'Utskrift mislyktes: {e}',
  'preview_snack_saved'                 : 'CV lagret til Nedlastinger ✓',
  'preview_snack_export_failed'         : 'Eksport mislyktes: {e}',
  'preview_snack_share_failed'          : 'Deling mislyktes: {e}',
  'preview_template_not_registered'     : 'Mal ikke registrert',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Lukk forhåndsvisning',
  'preview_modal_hint_photo'            : 'Støtter profilbilde  ·  Trykk på et kort for å velge',
  'preview_modal_hint_no_photo'         : 'Trykk på et malkort for å velge det',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Min CV',
  'time_just_now'                       : 'Akkurat nå',
  'time_minutes_ago'                    : '{n}m siden',
  'time_hours_ago'                      : '{n}t siden',
  'time_yesterday'                      : 'I går',
  'time_days_ago'                       : '{n} dager siden',
  'time_one_week_ago'                   : '1 uke siden',
  'time_weeks_ago'                      : '{n} uker siden',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegant',
  'tpl_tag_classic'                     : 'Klassisk',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Kreativ',
  'tpl_tag_bold'                        : 'Dristig',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Blågrønn til fiolett gradientkort',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Redaksjonell',
  'tpl_editorial_desc'                  : 'Magasinstil i rødt og krem',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastell Myk',
  'tpl_pastel_soft_desc'                : 'Lavendel sidepanel, myke kort',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalistisk',
  'tpl_brutalist_desc'                  : 'Råt rutenett, tykke kanter og gult',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragd',
  'tpl_emerald_desc'                    : 'Skogrønn med tidslinje',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografisk',
  'tpl_infographic_desc'                : 'Mørkt lerret med ringdiagrammer',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920-tallets geometriske gulldesign',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Mørk',
  'tpl_wina_dark_desc'                  : 'Mørk infografisk med ringer',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Oransje',
  'tpl_rio_orange_desc'                 : 'Mørkt sidepanel med oransje aksent',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Sommer',
  'tpl_summer_desc'                     : 'Ren minimal, myke grå toner',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Varme beige elegante toner',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Markant sort og hvit klassiker',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klassisk ATS-vennlig oppsett',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Mørk',
  'tpl_tony_dark_desc'                  : 'Mørk oransje infografisk stil',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Mote',
  'tpl_fashion_desc'                    : 'Teknisk tegning på rutenett',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Klassisk tokolonnes etikettoppsett',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Skyggelagte overskrifter med diamantledere',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Sentrerte overskrifter, aksent på firmanavn',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Dristig navn, tidslinjepunkter og prestasjoner',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Personlig informasjon',
  'personal_subtitle'                   : 'Fortell arbeidsgivere hvem du er',
  'personal_profile_counter'            : '{n}/{max} profiler',
  'personal_info_banner'                : 'Lagre opptil 5 profiler og velg én per CV. Valget ditt huskes for hver CV separat.',
  'personal_snack_max'                  : 'Maksimalt {n} profiler nådd.',
  'personal_add_btn'                    : 'Legg til ny profil',
  'personal_library_title'              : 'Lagrede profiler',
  'personal_selected_one'               : '1 valgt',
  'personal_selected_none'              : 'ingen valgt',
  'personal_library_hint'               : 'Trykk på et kort for å velge det kun for denne CV-en. Andre CV-er beholder sine egne uavhengige valg.',
  'personal_empty_message'              : 'Ingen profiler lagret ennå',
  'personal_empty_sub'                  : 'Trykk ovenfor for å legge til personlig informasjon',
  'personal_nav_next'                   : 'Lagre og fortsett',
  'personal_card_active_badge'          : 'Aktiv for denne CV-en',
  'personal_sheet_title_add'            : 'Ny profil',
  'personal_sheet_title_edit'           : 'Rediger profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTISK',
  'personal_sheet_brutalist_banner'     : 'Brutalistisk mal har kompakte kontaktfelt. Kortere verdier (f.eks. bare by) vises best.',
  'personal_section_photo'              : 'Profilbilde',
  'personal_section_basic'              : 'Grunnleggende detaljer',
  'personal_section_contact'            : 'Kontakt',
  'personal_section_online'             : 'Nettilstedeværelse',
  'personal_section_summary'            : 'Profesjonelt sammendrag',
  'personal_field_first_name'           : 'Fornavn *',
  'personal_field_last_name'            : 'Etternavn',
  'personal_field_job_title'            : 'Stillingstittel *',
  'personal_field_email'                : 'E-postadresse *',
  'personal_field_phone'                : 'Telefonnummer *',
  'personal_field_location'             : 'Sted',
  'personal_field_location_brut'        : 'Sted (kun by)',
  'personal_field_website'              : 'Nettsted / portefølje',
  'personal_field_linkedin'             : 'LinkedIn-URL',
  'personal_hint_first_name'            : 'f.eks. Kari',
  'personal_hint_last_name'             : 'f.eks. Nordmann',
  'personal_hint_job_title'             : 'f.eks. Senior ingeniør',
  'personal_hint_email'                 : 'f.eks. kari@eksempel.com',
  'personal_hint_phone'                 : 'f.eks. +47 900 12 345',
  'personal_hint_location'              : 'f.eks. Oslo, Norge',
  'personal_hint_location_brut'         : 'f.eks. Oslo, NO',
  'personal_hint_website'               : 'f.eks. github.com/karinordmann',
  'personal_hint_website_brut'          : 'f.eks. github.com/kari',
  'personal_hint_linkedin'              : 'f.eks. linkedin.com/in/karinordmann',
  'personal_hint_linkedin_brut'         : 'f.eks. linkedin.com/in/kari',
  'personal_summary_hint_label'         : 'Hold det kortfattet — dette vises øverst i CV-en din.',
  'personal_hint_summary'               : 'Et kort sammendrag på 2–3 setninger om din bakgrunn og mål...',
  'personal_validator_email'            : 'Skriv inn en gyldig e-postadresse',
  'personal_field_char_limit_tooltip'   : 'Tegngrense nådd',
  'personal_sheet_btn_save'             : 'Lagre profil',
  'personal_sheet_btn_update'           : 'Lagre endringer',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Velg bilde',
  'photo_option_gallery'                : 'Velg fra galleri',
  'photo_option_camera'                 : 'Ta et bilde',
  'photo_option_reposition'             : 'Flytt bilde',
  'photo_option_remove'                 : 'Fjern bilde',
  'photo_status_added'                  : 'Bilde lagt til ✓',
  'photo_status_empty'                  : 'Legg til et profesjonelt portrettbilde',
  'photo_chip_gallery'                  : 'Galleri',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Flytt',
  'photo_reposition_title'              : 'Flytt bilde',
  'photo_reposition_sub'                : 'Dra bildet for å justere posisjonen',
  'photo_reposition_reset'              : 'Tilbakestill til midten',
  'photo_reposition_apply'              : 'Bruk',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Ferdigheter',
  'skills_subtitle'                     : 'Fremhev dine viktigste evner',
  'skills_add_btn'                      : 'Legg til ny ferdighet',
  'skills_snack_max_icons'              : 'Maksimalt 10 ikoner valgt.',
  'skills_snack_max_skills'             : 'Maksimalt 15 ferdigheter nådd.',
  'skills_library_title'                : 'Lagrede ferdigheter',
  'skills_library_hint'                 : 'Merkede ferdigheter er inkludert i denne CV-en. Valgene dine lagres automatisk.',
  'skills_nav_next'                     : 'Fortsett til Tillegg',
  'skills_wina_header_icon_bar'         : 'Overskrift-ikonsøyle',
  'skills_wina_on'                      : 'PÅ',
  'skills_wina_off'                     : 'AV',
  'skills_wina_bar_on_sub'              : 'Fargede ikonsirkler vises i CV-overskriften.',
  'skills_wina_bar_off_sub'             : 'Ikonraden er skjult — mer plass til kontaktinfo.',
  'skills_wina_palette_hint'            : 'Ikoner vises som fargede sirkler i palettrekkefølge.',
  'skills_wina_preview_label'           : 'Forhåndsvisning',
  'skills_wina_disabled_hint'           : 'Aktiver ikonsøylen ovenfor for å velge hvilke ikoner som vises i CV-overskriften.',
  'skills_sheet_title_add'              : 'Legg til ferdighet',
  'skills_sheet_title_edit'             : 'Rediger ferdighet',
  'skills_sheet_field_name'             : 'Ferdighetsnavn *',
  'skills_sheet_hint_short'             : 'f.eks. Flutter, Design',
  'skills_sheet_hint_long'              : 'f.eks. Flutter, Prosjektledelse',
  'skills_sheet_validator_max'          : 'Maks {n} tegn',
  'skills_sheet_proficiency'            : 'Ferdighetsnivå',
  'skills_sheet_beginner'               : 'Nybegynner',
  'skills_sheet_expert'                 : 'Ekspert',
  'skills_sheet_btn_save'               : 'Lagre ferdighet',
  'skills_sheet_btn_update'             : 'Oppdater ferdighet',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Personlige referanser',
  'refs_subtitle'                       : 'Personer som kan gå god for deg personlig',
  'refs_add_btn'                        : 'Legg til ny personlig referanse',
  'refs_snack_max_selected'             : 'Maksimalt 4 referanser kan velges for én CV.',
  'refs_snack_max_saved'                : 'Maksimalt 10 lagrede referanser nådd.',
  'refs_library_title'                  : 'Lagrede referanser',
  'refs_library_hint'                   : 'Merkede referanser er inkludert i denne CV-en. Maks 4 per CV. Valgene dine lagres automatisk.',
  'refs_nav_next'                       : 'Fortsett til Tilpass',
  'refs_sheet_title_add'                : 'Legg til personlig referanse',
  'refs_sheet_title_edit'               : 'Rediger personlig referanse',
  'refs_sheet_sub_add'                  : 'Noen som personlig kan anbefale deg til arbeidsgivere.',
  'refs_sheet_sub_edit'                 : 'Oppdater denne referansens detaljer nedenfor.',
  'refs_sheet_field_name'               : 'Fullt navn *',
  'refs_sheet_field_title'              : 'Stillingstittel *',
  'refs_sheet_field_company'            : 'Selskap (valgfritt)',
  'refs_sheet_field_email'              : 'E-postadresse *',
  'refs_sheet_field_phone'              : 'Telefonnummer *',
  'refs_sheet_hint_name'                : 'f.eks. Ola Nordmann',
  'refs_sheet_hint_title'               : 'f.eks. Ingeniørleder',
  'refs_sheet_hint_company'             : 'f.eks. Acme AS',
  'refs_sheet_hint_email'               : 'f.eks. ola@acme.no',
  'refs_sheet_hint_phone'               : 'f.eks. +47 900 12 345',
  'refs_sheet_validator_email'          : 'Skriv inn en gyldig e-postadresse',
  'refs_sheet_btn_save'                 : 'Lagre personlig referanse',
  'refs_sheet_btn_update'               : 'Oppdater personlig referanse',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Arbeidserfaring',
  'exp_subtitle'                        : 'Legg til din arbeidshistorikk',
  'exp_banner_info'                     : 'Opptil {n} ansvarsområder per rolle vil vises på CV-en. 3–6 roller får typisk plass på 1–2 sider.',
  'exp_add_btn'                         : 'Legg til ny erfaring',
  'exp_snack_max_selected'              : 'Maksimalt 8 erfaringer kan velges for én CV.',
  'exp_snack_max_saved'                 : 'Maksimalt 12 lagrede erfaringer nådd.',
  'exp_library_title'                   : 'Lagrede erfaringer',
  'exp_library_hint'                    : 'Merkede oppføringer er inkludert kun i denne CV-en. Andre CV-er beholder sine egne uavhengige valg.',
  'exp_nav_next'                        : 'Fortsett til Utdanning',
  'exp_empty_message'                   : 'Ingen erfaring lagt til ennå',
  'exp_empty_sub'                       : 'Trykk ovenfor for å legge til din første rolle',
  'exp_card_resp_singular'              : 'ansvarsområde',
  'exp_card_resp_plural'                : 'ansvarsområder',
  'exp_card_resp_tooltip'               : 'Kun de første 8 ansvarsområdene vises på CV-en',
  'exp_sheet_title_add'                 : 'Legg til erfaring',
  'exp_sheet_title_edit'                : 'Rediger erfaring',
  'exp_sheet_field_job_title'           : 'Stillingstittel *',
  'exp_sheet_field_company'             : 'Selskap *',
  'exp_sheet_field_location'            : 'Sted',
  'exp_sheet_section_responsibilities'  : 'Viktige ansvarsområder',
  'exp_sheet_resp_hint_info'            : 'Maks 8 kulepunkter · 200 tegn hvert',
  'exp_sheet_resp_label'                : 'Ansvarsområde {n}',
  'exp_sheet_resp_hint'                 : 'f.eks. Ledet et team på 5 ingeniører',
  'exp_sheet_resp_add_btn'              : 'Legg til ansvarsområde',
  'exp_sheet_resp_max_info'             : 'Maksimalt {n} ansvarsområder nådd',
  'exp_sheet_resp_validator_max'        : 'Maks 200 tegn',
  'exp_sheet_hint_job_title'            : 'f.eks. Senior utvikler',
  'exp_sheet_hint_location'             : 'f.eks. Oslo, Norge',
  'exp_sheet_btn_save'                  : 'Lagre erfaring',
  'exp_sheet_btn_update'                : 'Lagre endringer',
  'exp_date_present'                    : 'Nåværende stilling',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Utdanning',
  'edu_subtitle'                        : 'Legg til din akademiske bakgrunn',
  'edu_add_btn'                         : 'Legg til ny utdanning',
  'edu_snack_max_selected'              : 'Maksimalt 8 utdanningsoppføringer kan velges for én CV.',
  'edu_snack_max_saved'                 : 'Maksimalt 12 lagrede utdanningsoppføringer nådd.',
  'edu_library_title'                   : 'Lagret utdanning',
  'edu_library_hint'                    : 'Merkede oppføringer er inkludert i denne CV-en. Valgene dine lagres automatisk.',
  'edu_nav_next'                        : 'Fortsett til Ferdigheter',
  'edu_empty_message'                   : 'Ingen utdanning lagt til ennå',
  'edu_empty_sub'                       : 'Trykk ovenfor for å legge til kvalifikasjonene dine',
  'edu_card_bullet_singular'            : 'kulepunkt',
  'edu_card_bullet_plural'              : 'kulepunkter',
  'edu_sheet_title_add'                 : 'Legg til utdanning',
  'edu_sheet_title_edit'                : 'Rediger utdanning',
  'edu_sheet_field_degree'              : 'Grad / Kvalifikasjon *',
  'edu_sheet_field_institution'         : 'Institusjon *',
  'edu_sheet_section_key_points'        : 'Nøkkelpunkter',
  'edu_sheet_key_points_hint_info'      : 'Valgfritt · 1 kulepunkt · maks 100 tegn',
  'edu_sheet_point_label'               : 'Punkt {n}',
  'edu_sheet_point_add_btn'             : 'Legg til kulepunkt',
  'edu_sheet_point_max_info'            : 'Maksimalt {n} kulepunkter nådd',
  'edu_sheet_point_validator_max'       : 'Maks {n} tegn',
  'edu_sheet_hint_degree'               : 'f.eks. BSc Informatikk',
  'edu_sheet_hint_institution'          : 'f.eks. Universitetet i Oslo',
  'edu_sheet_hint_bullet'               : 'f.eks. Utmerket bestått',
  'edu_sheet_btn_save'                  : 'Lagre utdanning',
  'edu_sheet_btn_update'                : 'Lagre endringer',
  'edu_date_present'                    : 'Pågående studier',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Tilleggsinformasjon',
  'additional_subtitle'                 : 'Sertifiseringer, språk og mer',
  'additional_cert_section_title'       : 'Sertifiseringer',
  'additional_cert_counter'             : '{sel}/{total} valgt · maks {max}',
  'additional_cert_hide'                : 'Skjul',
  'additional_cert_show'                : 'Vis',
  'additional_cert_add_btn'             : 'Legg til',
  'additional_cert_snack_max'           : 'Maksimalt {n} sertifiseringsoppføringer nådd.',
  'additional_cert_hint'                : 'Merkede oppføringer er inkludert i denne CV-en. Valgene dine lagres automatisk.',
  'additional_cert_empty'               : 'Ingen sertifiseringer lagt til ennå',
  'additional_lang_section_title'       : 'Språk',
  'additional_lang_add_hint'            : 'f.eks. Spansk',
  'additional_lang_snack_max'           : 'Maksimalt {n} språkoppføringer nådd.',
  'additional_lang_empty'               : 'Ingen språk lagt til ennå',
  'additional_hobby_section_title'      : 'Hobbyer og interesser',
  'additional_hobby_add_hint'           : 'f.eks. Fotografi',
  'additional_hobby_snack_max'          : 'Maksimalt {n} hobbyoppføringer nådd.',
  'additional_hobby_empty'              : 'Ingen hobbyer lagt til ennå',
  'additional_section_hint'             : 'Merkede oppføringer er inkludert i denne CV-en. Valgene dine lagres automatisk.',
  'additional_nav_next'                 : 'Fortsett til Referanser',
  'cert_sheet_title_add'                : 'Legg til sertifisering',
  'cert_sheet_title_edit'               : 'Rediger sertifisering',
  'cert_sheet_sub'                      : 'Legg til en kvalifikasjon, sertifikat eller profesjonell akkreditering.',
  'cert_sheet_field_name'               : 'Sertifiseringsnavn *',
  'cert_sheet_field_issued_by'          : 'Utstedt av (valgfritt)',
  'cert_sheet_field_short_desc'         : 'Kort beskrivelse (valgfritt)',
  'cert_sheet_hint_name'                : 'f.eks. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'f.eks. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'f.eks. Oppnådd 2024',
  'cert_sheet_btn_save'                 : 'Lagre sertifisering',
  'cert_sheet_btn_update'               : 'Oppdater sertifisering',
  'simple_sheet_title_add_language'     : 'Legg til språk',
  'simple_sheet_title_edit_language'    : 'Rediger språk',
  'simple_sheet_title_add_hobby'        : 'Legg til hobby',
  'simple_sheet_title_edit_hobby'       : 'Rediger hobby',
  'simple_sheet_btn_save'               : 'Lagre',
  'simple_sheet_btn_update'             : 'Oppdater',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontakt',
  'pdf_section_about_me'                : 'Om meg',
  'pdf_section_summary'                 : 'Sammendrag',
  'pdf_section_summary_short'           : 'Sammendrag',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Erfaring',
  'pdf_section_experience_short'        : 'Erfaring',
  'pdf_section_education'               : 'Utdanning',
  'pdf_section_skills'                  : 'Ferdigheter',
  'pdf_section_languages'               : 'Språk',
  'pdf_label_email'                     : 'E-post',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Localisation',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV-grense nådd',
  'limit_dialog_body'                   : 'Du har nådd maksimalt antall på 30 CVer. Slett en eksisterende CV før du oppretter en ny.',
  'limit_dialog_go_to_my_cvs'           : 'Gå til Mine CVer',
  'limit_dialog_cancel'                 : 'Avbryt',
  'refs_count_summary'                  : '{checked}/{maxChecked} valgt · {saved}/{maxSaved} lagret',
  'refs_selected_badge'                 : '{n} valgt',
  'refs_empty_message'                  : 'Ingen referanser lagret ennå',
  'refs_empty_sub'                      : 'Trykk ovenfor for å legge til en personlig referanse',
};