// lib/language_keys/lang_de_german.dart
//
// German (Deutsch) translation map.
// Translated from lang_en_english.dart.

const Map<String, String> deGerman = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Keine Sprachen gefunden',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Überspringen',
  'onboarding_next'                     : 'Weiter',
  'onboarding_get_started'              : 'Loslegen',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Willkommen',
  'ob1_title'                           : 'Erstelle einen Lebenslauf,\nder Türen öffnet',
  'ob1_body'                            : 'Hebe dich von hunderten Bewerbern ab. Erstelle in Minuten einen professionellen Lebenslauf – ohne Designkenntnisse.',
  'ob1_pill_label'                      : 'Professioneller Lebenslauf-Ersteller',
  'ob1_chip_templates'                  : '24+ Vorlagen',
  'ob1_chip_pdf'                        : 'PDF-Export',
  'ob1_chip_free'                       : 'Kostenlos',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Vorlagen',
  'ob2_title'                           : 'Jede Branche.\nJeder Anspruch.',
  'ob2_body'                            : 'Von sachlichen Layouts bis zu kreativen Designs – eine Vorlage, die deine Geschichte erzählt.',
  'ob2_tap_hint'                        : 'Vorlage antippen zum Vorschauen',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Korporativ',
  'ob2_tag_creative'                    : 'Kreativ',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart Layout',
  'ob3_title'                           : 'Dein Lebenslauf.\nPerfekt angeordnet.',
  'ob3_body'                            : 'Smart Layout ordnet deine Abschnitte für maximale Wirkung neu – und stellt deine stärksten Inhalte dort vor, wo Recruiter zuerst hinschauen.',
  'ob3_badge_smart_layout'              : 'Smart Layout',
  'ob3_badge_cv_ready'                  : 'Lebenslauf fertig!',
  'ob3_step1_label'                     : 'Vorlage wählen',
  'ob3_step1_desc'                      : 'Wähle aus 24+ beeindruckenden Designs.',
  'ob3_step2_label'                     : 'Daten eingeben',
  'ob3_step2_desc'                      : 'Geführte Felder für alle Abschnitte.',
  'ob3_step3_label'                     : 'Smart Layout',
  'ob3_step3_desc'                      : 'Ein Tippen ordnet deinen Lebenslauf perfekt.',
  'ob3_step4_label'                     : 'Als PDF exportieren',
  'ob3_step4_desc'                      : 'Pixelgenaues PDF zum Versenden.',
  'ob3_section_work'                    : 'Berufserfahrung',
  'ob3_section_education'               : 'Ausbildung',
  'ob3_section_skills'                  : 'Fähigkeiten',
  'ob3_section_references'              : 'Referenzen',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Bereit loszulegen',
  'ob4_title'                           : 'Warum Top-Bewerber\nden CV Builder wählen',
  'ob4_visual_headline'                 : 'Du bist startklar!',
  'ob4_visual_subline'                  : 'Alles, was du für den Job brauchst.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Vorlagen',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Max. Lebensläufe',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privat',
  'ob4_hl1_title'                       : 'Privat & Sicher',
  'ob4_hl1_sub'                         : 'Daten bleiben auf deinem Gerät.',
  'ob4_hl2_title'                       : 'Auto-Speichern',
  'ob4_hl2_sub'                         : 'Jeder Tastendruck sofort gespeichert.',
  'ob4_hl3_title'                       : 'Bis zu 30 Lebensläufe',
  'ob4_hl3_sub'                         : 'Einzigartiger Lebenslauf für jede Stelle.',
  'ob4_hl4_title'                       : 'Teilen mit einem Tippen',
  'ob4_hl4_sub'                         : 'PDF senden ohne die App zu verlassen.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Hebe dich von der Masse ab',
  'home_hero_title'                     : 'Erstelle deinen\nprofessionellen Lebenslauf',
  'home_hero_sub'                       : 'Baue in Minuten einen\nbeeindruckenden Lebenslauf',
  'home_hero_cta'                       : 'Jetzt erstellen',
  'home_premium_soon'                   : 'Upgrade auf Pro kommt bald!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Neueste zuerst',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Zuletzt bearbeitet',
  'history_sort_by_template'            : 'Nach Vorlage',
  'history_sort_sheet_title'            : 'Sortieren nach',
  'history_sort_alphabetical_full'      : 'Alphabetisch (A–Z)',
  'history_premium_soon'                : 'Upgrade auf Pro kommt bald!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Einstellungen',
  'settings_section_preferences'        : 'Einstellungen',
  'settings_section_support'            : 'Support',
  'settings_section_legal'              : 'Rechtliches',
  'settings_section_about'              : 'Über die App',
  'settings_language_tile_title'        : 'Sprache',
  'settings_dark_mode_title'            : 'Dunkelmodus',
  'settings_dark_mode_on'               : 'Dunkles Design aktiviert',
  'settings_dark_mode_off'              : 'Helles Design aktiviert',
  'settings_help_faq_title'             : 'Hilfe & FAQ',
  'settings_help_faq_sub'               : 'Häufig gestellte Fragen beantwortet',
  'settings_contact_support_title'      : 'Support kontaktieren',
  'settings_rate_app_title'             : 'App bewerten',
  'settings_rate_app_sub'               : 'Gefällt dir die App? Hinterlasse eine Bewertung!',
  'settings_privacy_policy_title'       : 'Datenschutzrichtlinie',
  'settings_terms_title'                : 'Nutzungsbedingungen',
  'settings_app_version_title'          : 'App-Version',
  'settings_email_error'                : 'E-Mail-App konnte nicht geöffnet werden. Bitte schreibe an cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Lebenslauf-Vorschau',
  'preview_header_sub'                  : 'Bereit zum Exportieren',
  'preview_generating'                  : 'Lebenslauf wird erstellt...',
  'preview_failed_title'                : 'Vorschau fehlgeschlagen',
  'preview_failed_error'                : 'Fehler: {error}',
  'preview_go_back'                     : 'Zurück',
  'preview_no_data'                     : 'Keine Daten verfügbar',
  'preview_btn_print'                   : 'Drucken',
  'preview_btn_download'                : 'Herunterladen & Teilen',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Hilfe & FAQ',
  'faq_category_all'                    : 'Alle',
  'faq_empty'                           : 'Keine Ergebnisse gefunden',
  'faq_contact_headline'                : 'Noch Fragen?',
  'faq_contact_sub'                     : 'Unser Team ist für dich da.',
  'faq_contact_btn'                     : 'Kontakt',
  'faq_email_error'                     : 'E-Mail-App konnte nicht geöffnet werden. Bitte schreibe an cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Erste Schritte',
  'faq_cat_templates'                   : 'Vorlagen',
  'faq_cat_editing'                     : 'Bearbeitung',
  'faq_cat_exporting'                   : 'Exportieren',
  'faq_cat_data_privacy'                : 'Daten & Datenschutz',
  'faq_cat_troubleshooting'             : 'Fehlerbehebung',
  'faq_q1'  : 'Wie erstelle ich meinen ersten Lebenslauf?',
  'faq_a1'  : 'Tippe auf dem Startbildschirm auf die "+"-Schaltfläche, um einen neuen Lebenslauf zu beginnen. Wähle eine passende Vorlage und fülle dann deine persönlichen Daten, Berufserfahrung, Ausbildung und Fähigkeiten Schritt für Schritt aus. Dein Fortschritt wird automatisch gespeichert.',
  'faq_q2'  : 'Kann ich mehr als einen Lebenslauf erstellen?',
  'faq_a2'  : 'Ja! Du kannst mehrere Lebensläufe für verschiedene Stellen oder Branchen erstellen. Jeder Lebenslauf wird separat gespeichert, sodass du ihn auf spezifische Bewerbungen zuschneiden kannst.',
  'faq_q3'  : 'Wie ändere ich die Vorlage meines Lebenslaufs?',
  'faq_a3'  : 'Öffne deinen Lebenslauf, tippe oben auf das Vorlagen-Symbol und durchsuche die verfügbaren Vorlagen. Tippe auf eine Vorlage, um sie mit deinen Inhalten vorab anzuzeigen. Bestätige, um sie anzuwenden.',
  'faq_q4'  : 'Gibt es kostenlose und kostenpflichtige Vorlagen?',
  'faq_a4'  : 'Ja. Eine Auswahl professioneller Vorlagen ist kostenlos verfügbar. Premium-Vorlagen mit erweiterten Designs und Farbpaletten sind über einen einmaligen Kauf oder ein Abonnement erhältlich.',
  'faq_q5'  : 'Wie füge ich Abschnitte hinzu oder entferne sie?',
  'faq_a5'  : 'Scrolle im Lebenslauf-Editor nach unten und tippe auf „Abschnitt hinzufügen", um Extras wie Sprachen, Zertifizierungen oder Ehrenamt hinzuzufügen. Um einen Abschnitt zu entfernen, tippe auf die Abschnittsüberschrift und wähle „Entfernen".',
  'faq_q6'  : 'Wie ordne ich Abschnitte neu an?',
  'faq_a6'  : 'Drücke lange auf den Ziehpunkt (≡) neben einer Abschnittsüberschrift und ziehe ihn an die gewünschte Position. Änderungen werden automatisch gespeichert.',
  'faq_q7'  : 'Wie exportiere ich meinen Lebenslauf als PDF?',
  'faq_a7'  : 'Öffne deinen Lebenslauf und tippe oben rechts auf die Export-Schaltfläche (Teilen-Symbol). Wähle „Als PDF exportieren". Du kannst es dann auf deinem Gerät speichern, per E-Mail oder WhatsApp teilen oder direkt auf Jobportale hochladen.',
  'faq_q8'  : 'Welche Dateiformate werden unterstützt?',
  'faq_a8'  : 'Die App unterstützt derzeit den Export deines Lebenslaufs als hochwertiges PDF. Weitere Formate können in zukünftigen Updates hinzugefügt werden.',
  'faq_q9'  : 'Wo werden meine Lebenslauf-Daten gespeichert?',
  'faq_a9'  : 'Alle Lebenslauf-Daten werden lokal auf deinem Gerät gespeichert. Wir laden deine persönlichen Informationen nicht auf unsere Server hoch. Deine Daten bleiben privat und offline verfügbar.',
  'faq_q10' : 'Wie sichere ich meine Lebensläufe?',
  'faq_a10' : 'Deine Lebensläufe sind in der Standard-Sicherung deines Geräts enthalten (Google Drive auf Android, iCloud auf iOS), wenn du die Sicherung in den Geräteeinstellungen aktiviert hast. Du kannst einzelne Lebensläufe auch als PDFs exportieren.',
  'faq_q11' : 'Die App läuft langsam. Was soll ich tun?',
  'faq_a11' : 'Versuche, die App zu schließen und neu zu öffnen. Falls das Problem bestehen bleibt, starte dein Gerät neu. Stelle sicher, dass du die neueste Version der App aus dem Play Store / App Store installiert hast.',
  'faq_q12' : 'Mein Lebenslauf wird nicht korrekt exportiert. Was soll ich tun?',
  'faq_a12' : 'Stelle sicher, dass genügend Speicherplatz auf deinem Gerät vorhanden ist. Versuche, große Bilder in deinem Lebenslauf zu verkleinern. Wenn das Problem weiterhin besteht, kontaktiere bitte unser Support-Team.',
  'faq_q13' : 'Ich habe vergessen zu speichern – ist meine Arbeit verloren?',
  'faq_a13' : 'Überhaupt nicht! Die App speichert deinen Fortschritt während des Bearbeitens kontinuierlich.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Deine Karriere, perfektioniert',
  'header_tooltip_back'                 : 'Zurück',
  'header_tooltip_my_cvs'               : 'Meine Lebensläufe',
  'header_tooltip_settings'             : 'Einstellungen',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Meine Lebensläufe',
  'saved_count_single'                  : '{n} Dokument',
  'saved_count_plural'                  : '{n} Dokumente',
  'saved_limit_reached'                 : 'Limit erreicht',
  'saved_footer_count'                  : '{n} / 30 Lebensläufe',
  'saved_filter_all'                    : 'Alle',
  'saved_filter_draft'                  : 'Entwurf',
  'saved_filter_complete'               : 'Vollständig',
  'saved_status_complete'               : 'Vollständig',
  'saved_status_saved'                  : 'Gespeichert',
  'saved_status_draft'                  : 'Entwurf',
  'saved_empty_title'                   : 'Noch keine Lebensläufe',
  'saved_empty_sub'                     : 'Erstelle oben deinen ersten Lebenslauf',
  'saved_search_empty_title'            : 'Keine Ergebnisse gefunden',
  'saved_search_empty_sub'              : 'Versuche einen anderen Suchbegriff',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Farbschema',
  'custom_font_settings_title'          : 'Schrifteinstellungen',
  'custom_font_family_label'            : 'Schriftfamilie',
  'custom_font_size_label'              : 'Schriftgröße: ',
  'custom_current_template_title'       : 'Aktuelle Vorlage',
  'custom_change_template_btn'          : 'Vorlage ändern',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klassisch',
  'custom_tpl_professional'             : 'Professionell',
  'custom_tpl_creative'                 : 'Kreativ',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Klares und zeitgemäßes Design',
  'custom_tpl_classic_desc'             : 'Traditionelles professionelles Layout',
  'custom_tpl_professional_desc'        : 'Geschäftsorientierte Vorlage',
  'custom_tpl_creative_desc'            : 'Mit einzigartigem Design auffallen',
  'custom_tpl_minimal_desc'             : 'Einfacher und eleganter Stil',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Vorlage wählen',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Beliebteste',
  'tpl_nordic_tag'                      : 'Klar',
  'tpl_vibrant_tag'                     : 'Kreativ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Markant und autoritär für Führungspositionen',
  'tpl_nordic_desc'                     : 'Klare Schlichtheit bei Top-Unternehmen gefragt',
  'tpl_vibrant_desc'                    : 'Mit Energie und Farbe auffallen',
  'tpl_tech_dark_desc'                  : 'Terminal-Ästhetik für Entwickler',
  'tpl_luxury_desc'                     : 'Goldakzente auf schwarzem Hintergrund',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Vorlage',
  'detail_step_personal'                : 'Persönlich',
  'detail_step_experience'              : 'Erfahrung',
  'detail_step_education'               : 'Ausbildung',
  'detail_step_skills'                  : 'Fähigkeiten',
  'detail_step_additional'              : 'Zusätzlich',
  'detail_step_references'              : 'Referenzen',
  'detail_step_customize'               : 'Anpassen',
  'detail_banner_heading'               : 'Fast geschafft!',
  'detail_banner_btn'                   : 'Weiter',
  'detail_banner_completion_label'      : 'Fertigstellung',
  'detail_stat_created_label'           : 'Erstellt',
  'detail_stat_steps_label'             : 'Schritte erledigt',
  'detail_section_template_style'       : 'Vorlagenstil',
  'detail_section_steps'                : 'Schritte',
  'detail_steps_counter'                : '{done} von {total} abgeschlossen',
  'detail_step_sub'                     : 'Schritt {n} von {total}',
  'detail_section_activity'             : 'Aktivität',
  'detail_activity_created'             : 'Erstellt',
  'detail_activity_last_edited'         : 'Zuletzt bearbeitet',
  'detail_activity_template'            : 'Vorlage',
  'detail_btn_continue_editing'         : 'Weiter bearbeiten',
  'detail_btn_edit_cv'                  : 'Lebenslauf bearbeiten',
  'detail_option_rename'                : 'Lebenslauf umbenennen',
  'detail_option_delete'                : 'Lebenslauf löschen',
  'detail_rename_title'                 : 'Lebenslauf umbenennen',
  'detail_rename_hint'                  : 'z.B. Softwareentwickler Lebenslauf',
  'detail_rename_error_empty'           : 'Name darf nicht leer sein',
  'detail_rename_btn_cancel'            : 'Abbrechen',
  'detail_rename_btn_save'              : 'Speichern',
  'detail_rename_snackbar'              : 'Umbenannt in „{name}"',
  'detail_delete_title'                 : 'Lebenslauf löschen?',
  'detail_delete_body'                  : 'Dadurch wird „{name}" dauerhaft gelöscht. Diese Aktion kann nicht rückgängig gemacht werden.',
  'detail_delete_btn_cancel'            : 'Abbrechen',
  'detail_delete_btn_confirm'           : 'Löschen',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Abgeschlossen',
  'detail_check_tile_incomplete'        : 'Noch nicht ausgefüllt',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Vorlage wählen',
  'chooser_subtitle'                    : 'Wischen zum Stöbern  ·  Tippen zum Auswählen  ·  Halten zum Vorschauen',
  'chooser_card_hold_hint'              : 'Halten zum Vorschauen',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Ausgewählt',
  'chooser_modal_heading'               : 'Lebenslauf benennen',
  'chooser_modal_sub'                   : 'Gib ihm einen Namen, damit du ihn in Meine Lebensläufe und Verlauf leicht findest.',
  'chooser_modal_field_label'           : 'Name des Lebenslaufs',
  'chooser_modal_save_btn'              : 'Speichern & Erstellen starten',
  'chooser_modal_divider'               : 'oder einen vorhandenen Lebenslauf fortsetzen',
  'chooser_nav_selected_sub'            : 'Ausgewählte Vorlage',
  'chooser_nav_cta'                     : 'Speichern & Weiter',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maximale Anzahl an Einträgen erreicht',
  'editor_show_hide'                    : 'Ein-/Ausblenden',
  'editor_editing_badge'                : 'Bearbeitung',
  'editor_field_required'               : 'Pflichtfeld',
  'editor_tooltip_edit'                 : 'Bearbeiten',
  'editor_tooltip_delete'               : 'Löschen',
  'editor_date_start'                   : 'Startdatum *',
  'editor_date_end'                     : 'Enddatum *',
  'editor_date_tap_hint'                : 'Tippen zum Auswählen',
  'editor_date_dialog_title'            : 'Monat & Jahr wählen',
  'editor_date_confirm'                 : 'Bestätigen',
  'editor_panel_hide'                   : 'Ausblenden',
  'editor_panel_show'                   : 'Einblenden',
  'editor_validator_max_chars'          : 'Max. {n} Zeichen',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Lebenslauf erstellen',
  'editor_header_step_sub'              : 'Schritt {current} von {total} · {label}',
  'editor_step_template'                : 'Vorlage',
  'editor_step_personal'                : 'Persönlich',
  'editor_step_experience'              : 'Erfahrung',
  'editor_step_education'               : 'Ausbildung',
  'editor_step_skills'                  : 'Fähigkeiten',
  'editor_step_additional'              : 'Zusätzlich',
  'editor_step_references'              : 'Referenzen',
  'editor_step_customize'               : 'Anpassen',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Anpassen',
  'customize_subtitle'                  : 'Mach deinen Lebenslauf einzigartig',
  'customize_smart_layout_btn'          : 'Smart Layout',
  'customize_back_to_top'               : 'Nach oben',
  'customize_done_title'                : 'Du bist fertig!',
  'customize_done_sub'                  : 'Tippe unten auf „Lebenslauf vorschauen", um deinen fertigen Lebenslauf zu sehen',
  'customize_preview_btn'               : 'Lebenslauf vorschauen',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Farbschema',
  'color_black'                         : 'Schwarz',
  'color_blue'                          : 'Blau',
  'color_nordic_blue'                   : 'Nordisches Blau',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Blaugrün',
  'color_green'                         : 'Grün',
  'color_purple'                        : 'Lila',
  'color_orange'                        : 'Orange',
  'color_red'                           : 'Rot',
  'color_executive_gold'                : 'Executive-Gold',
  'color_vibrant_coral'                 : 'Lebhaftes Koralle',
  'color_white'                         : 'Weiß',
  'color_white_bg'                      : 'Weißer Hintergrund',
  'color_maroon'                        : 'Kastanienbraun',
  'color_brutalist_yellow'              : 'Brutalistisches Gelb',
  'color_neon_blue'                     : 'Neonblau',
  'color_blueprint_navy'                : 'Blueprint-Marine',
  'color_light_grey'                    : 'Hellgrau',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Schriftfamilie',
  'customize_font_picker_title'         : 'Schrift wählen',
  'customize_font_picker_sub'           : 'Jede Schrift wird in ihrer eigenen Schriftart vorgeschaut',
  'customize_font_preview_sample'       : 'Der schnelle braune Fuchs',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Schriftgröße',
  'customize_font_size_label'           : 'Textgröße',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Bildgröße',
  'customize_image_size_label'          : 'Bildgröße',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Live-Vorschau',
  'preview_page_count_singular'         : '1 Seite',
  'preview_page_count_plural'           : '{n} Seiten',
  'preview_page_of'                     : 'Seite {page} von {total}',
  'preview_live_hint'                   : 'Änderungen werden sofort übernommen',
  'preview_template_unregistered'       : 'Noch nicht in customize_preview.dart registriert',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Lebenslauf wird vorbereitet…',
  'preview_bar_print'                   : 'Drucken',
  'preview_bar_save_pdf'                : 'Als PDF speichern',
  'preview_bar_share'                   : 'Teilen',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Lebenslauf-Vorschau',
  'preview_screen_sub'                  : '{n} {unit} · genau wie gedruckt',
  'preview_page_singular'               : 'Seite',
  'preview_page_plural'                 : 'Seiten',
  'preview_pdf_filename'                : 'Mein_Lebenslauf',
  'preview_share_subject'               : 'Mein Lebenslauf',
  'preview_snack_print_failed'          : 'Drucken fehlgeschlagen: {e}',
  'preview_snack_saved'                 : 'Lebenslauf in Downloads gespeichert ✓',
  'preview_snack_export_failed'         : 'Export fehlgeschlagen: {e}',
  'preview_snack_share_failed'          : 'Teilen fehlgeschlagen: {e}',
  'preview_template_not_registered'     : 'Vorlage nicht registriert',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Vorschau schließen',
  'preview_modal_hint_photo'            : 'Unterstützt Profilfoto  ·  Karte antippen zum Auswählen',
  'preview_modal_hint_no_photo'         : 'Vorlagenkarte antippen zum Auswählen',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Mein Lebenslauf',
  'time_just_now'                       : 'Gerade eben',
  'time_minutes_ago'                    : 'vor {n} Min.',
  'time_hours_ago'                      : 'vor {n} Std.',
  'time_yesterday'                      : 'Gestern',
  'time_days_ago'                       : 'vor {n} Tagen',
  'time_one_week_ago'                   : 'vor 1 Woche',
  'time_weeks_ago'                      : 'vor {n} Wochen',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegant',
  'tpl_tag_classic'                     : 'Klassisch',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Kreativ',
  'tpl_tag_bold'                        : 'Markant',

  // ─── preview_registry.dart — template names ─────────────────────────────
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Karten mit Farbverlauf von Blaugrün bis Violett',
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Magazinstil in Rot und Creme',
  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'Lavendel-Seitenleiste, sanfte Karten',
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Rohes Raster, fette Ränder und Gelb',
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Waldgrün mit Zeitstrahl',
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Dunkle Leinwand mit Ringdiagrammen',
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Geometrischer Goldluxus der 1920er',
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Dunkles Infografik mit Ringen',
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Dunkle Seitenleiste mit orangem Akzent',
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Klar und minimal in sanften Grautönen',
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Warme Beigetöne, elegant',
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Klassisch in Schwarz-Weiß',
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klassisches ATS-freundliches Layout',
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Dunkles Infografik im Orangestil',
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Technische Zeichnung auf Raster',
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Klassisches zweispaltiges Layout mit Beschriftungen',
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Schattierte Überschriften mit Rautenlinien',
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Zentrierte Überschriften, akzentuierte Firmen',
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Markanter Name, Zeitstrahl-Punkte und Erfolge',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Persönliche Informationen',
  'personal_subtitle'                   : 'Erzähle Arbeitgebern, wer du bist',
  'personal_profile_counter'            : '{n}/{max} Profile',
  'personal_info_banner'                : 'Speichere bis zu 5 Profile und wähle eines pro Lebenslauf. Deine Auswahl wird für jeden Lebenslauf separat gespeichert.',
  'personal_snack_max'                  : 'Maximale Anzahl von {n} Profilen erreicht.',
  'personal_add_btn'                    : 'Neues Profil hinzufügen',
  'personal_library_title'              : 'Gespeicherte Profile',
  'personal_selected_one'               : '1 ausgewählt',
  'personal_selected_none'              : 'keines ausgewählt',
  'personal_library_hint'               : 'Tippe auf eine Karte, um sie nur für diesen Lebenslauf auszuwählen. Andere Lebensläufe behalten ihre eigenen Auswahlen.',
  'personal_empty_message'              : 'Noch keine Profile gespeichert',
  'personal_empty_sub'                  : 'Tippe oben, um deine persönlichen Informationen hinzuzufügen',
  'personal_nav_next'                   : 'Speichern & Weiter',
  'personal_card_active_badge'          : 'Aktiv für diesen Lebenslauf',
  'personal_sheet_title_add'            : 'Neues Profil',
  'personal_sheet_title_edit'           : 'Profil bearbeiten',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Die Brutalist-Vorlage hat kompakte Kontaktfelder. Kürzere Werte (z.B. nur Stadt) werden am besten dargestellt.',
  'personal_section_photo'              : 'Profilfoto',
  'personal_section_basic'              : 'Grunddaten',
  'personal_section_contact'            : 'Kontakt',
  'personal_section_online'             : 'Online-Präsenz',
  'personal_section_summary'            : 'Berufliches Profil',
  'personal_field_first_name'           : 'Vorname *',
  'personal_field_last_name'            : 'Nachname',
  'personal_field_job_title'            : 'Berufsbezeichnung *',
  'personal_field_email'                : 'E-Mail-Adresse *',
  'personal_field_phone'                : 'Telefonnummer *',
  'personal_field_location'             : 'Ort',
  'personal_field_location_brut'        : 'Ort (nur Stadt)',
  'personal_field_website'              : 'Website / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn-URL',
  'personal_hint_first_name'            : 'z.B. Max',
  'personal_hint_last_name'             : 'z.B. Mustermann',
  'personal_hint_job_title'             : 'z.B. Senior-Ingenieur',
  'personal_hint_email'                 : 'z.B. max@beispiel.de',
  'personal_hint_phone'                 : 'z.B. +49 151 123 45678',
  'personal_hint_location'              : 'z.B. Berlin, Deutschland',
  'personal_hint_location_brut'         : 'z.B. Berlin',
  'personal_hint_website'               : 'z.B. github.com/maxmustermann',
  'personal_hint_website_brut'          : 'z.B. github.com/max',
  'personal_hint_linkedin'              : 'z.B. linkedin.com/in/maxmustermann',
  'personal_hint_linkedin_brut'         : 'z.B. linkedin.com/in/max',
  'personal_summary_hint_label'         : 'Halte es kurz – das erscheint oben in deinem Lebenslauf.',
  'personal_hint_summary'               : 'Eine kurze Zusammenfassung in 2–3 Sätzen über deinen Hintergrund und deine Ziele...',
  'personal_validator_email'            : 'Gültige E-Mail-Adresse eingeben',
  'personal_field_char_limit_tooltip'   : 'Zeichenlimit erreicht',
  'personal_sheet_btn_save'             : 'Profil speichern',
  'personal_sheet_btn_update'           : 'Änderungen speichern',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Foto wählen',
  'photo_option_gallery'                : 'Aus Galerie wählen',
  'photo_option_camera'                 : 'Foto aufnehmen',
  'photo_option_reposition'             : 'Foto neu positionieren',
  'photo_option_remove'                 : 'Foto entfernen',
  'photo_status_added'                  : 'Foto hinzugefügt ✓',
  'photo_status_empty'                  : 'Professionelles Foto hinzufügen',
  'photo_chip_gallery'                  : 'Galerie',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Neu positionieren',
  'photo_reposition_title'              : 'Foto neu positionieren',
  'photo_reposition_sub'                : 'Foto ziehen, um die Position anzupassen',
  'photo_reposition_reset'              : 'Auf Mitte zurücksetzen',
  'photo_reposition_apply'              : 'Anwenden',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Fähigkeiten',
  'skills_subtitle'                     : 'Hebe deine Kernkompetenzen hervor',
  'skills_add_btn'                      : 'Neue Fähigkeit hinzufügen',
  'skills_snack_max_icons'              : 'Maximale Anzahl von 10 Icons ausgewählt.',
  'skills_snack_max_skills'             : 'Maximale Anzahl von 15 Fähigkeiten erreicht.',
  'skills_library_title'                : 'Gespeicherte Fähigkeiten',
  'skills_library_hint'                 : 'Ausgewählte Fähigkeiten sind in diesem Lebenslauf enthalten. Deine Auswahl wird automatisch gespeichert.',
  'skills_nav_next'                     : 'Weiter zu Zusätzlich',
  'skills_wina_header_icon_bar'         : 'Kopfzeilen-Icon-Leiste',
  'skills_wina_on'                      : 'AN',
  'skills_wina_off'                     : 'AUS',
  'skills_wina_bar_on_sub'              : 'Farbige Icon-Kreise werden in der Lebenslauf-Kopfzeile angezeigt.',
  'skills_wina_bar_off_sub'             : 'Icon-Leiste ausgeblendet – mehr Platz für Kontaktdaten.',
  'skills_wina_palette_hint'            : 'Icons erscheinen als farbige Kreise in der Palettenreihenfolge.',
  'skills_wina_preview_label'           : 'Vorschau',
  'skills_wina_disabled_hint'           : 'Aktiviere die Icon-Leiste oben, um zu wählen, welche Icons in der Lebenslauf-Kopfzeile erscheinen.',
  'skills_sheet_title_add'              : 'Fähigkeit hinzufügen',
  'skills_sheet_title_edit'             : 'Fähigkeit bearbeiten',
  'skills_sheet_field_name'             : 'Name der Fähigkeit *',
  'skills_sheet_hint_short'             : 'z.B. Flutter, Design',
  'skills_sheet_hint_long'              : 'z.B. Flutter, Projektmanagement',
  'skills_sheet_validator_max'          : 'Max. {n} Zeichen',
  'skills_sheet_proficiency'            : 'Kenntnisstand',
  'skills_sheet_beginner'               : 'Anfänger',
  'skills_sheet_expert'                 : 'Experte',
  'skills_sheet_btn_save'               : 'Fähigkeit speichern',
  'skills_sheet_btn_update'             : 'Fähigkeit aktualisieren',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Persönliche Referenzen',
  'refs_subtitle'                       : 'Personen, die persönlich für dich bürgen können',
  'refs_add_btn'                        : 'Neue persönliche Referenz hinzufügen',
  'refs_snack_max_selected'             : 'Maximal 4 Referenzen können für einen Lebenslauf ausgewählt werden.',
  'refs_snack_max_saved'                : 'Maximale Anzahl von 10 gespeicherten Referenzen erreicht.',
  'refs_library_title'                  : 'Gespeicherte Referenzen',
  'refs_library_hint'                   : 'Ausgewählte Referenzen sind in diesem Lebenslauf enthalten. Max. 4 pro Lebenslauf. Deine Auswahl wird automatisch gespeichert.',
  'refs_nav_next'                       : 'Weiter zu Anpassen',
  'refs_sheet_title_add'                : 'Persönliche Referenz hinzufügen',
  'refs_sheet_title_edit'               : 'Persönliche Referenz bearbeiten',
  'refs_sheet_sub_add'                  : 'Jemand, der dich persönlich bei Arbeitgebern empfehlen kann.',
  'refs_sheet_sub_edit'                 : 'Aktualisiere die Details dieser Referenz unten.',
  'refs_sheet_field_name'               : 'Vollständiger Name *',
  'refs_sheet_field_title'              : 'Berufsbezeichnung *',
  'refs_sheet_field_company'            : 'Unternehmen (optional)',
  'refs_sheet_field_email'              : 'E-Mail-Adresse *',
  'refs_sheet_field_phone'              : 'Telefonnummer *',
  'refs_sheet_hint_name'                : 'z.B. Hans Müller',
  'refs_sheet_hint_title'               : 'z.B. Technischer Leiter',
  'refs_sheet_hint_company'             : 'z.B. Musterfirma GmbH',
  'refs_sheet_hint_email'               : 'z.B. hans@musterfirma.de',
  'refs_sheet_hint_phone'               : 'z.B. +49 151 123 45678',
  'refs_sheet_validator_email'          : 'Gültige E-Mail-Adresse eingeben',
  'refs_sheet_btn_save'                 : 'Persönliche Referenz speichern',
  'refs_sheet_btn_update'               : 'Persönliche Referenz aktualisieren',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Berufserfahrung',
  'exp_subtitle'                        : 'Füge deinen beruflichen Werdegang hinzu',
  'exp_banner_info'                     : 'Bis zu {n} Aufgaben pro Stelle erscheinen im Lebenslauf. 3–6 Stellen passen typischerweise auf 1–2 Seiten.',
  'exp_add_btn'                         : 'Neue Erfahrung hinzufügen',
  'exp_snack_max_selected'              : 'Maximal 8 Erfahrungen können für einen Lebenslauf ausgewählt werden.',
  'exp_snack_max_saved'                 : 'Maximale Anzahl von 12 gespeicherten Erfahrungen erreicht.',
  'exp_library_title'                   : 'Gespeicherte Erfahrungen',
  'exp_library_hint'                    : 'Ausgewählte Einträge sind nur in diesem Lebenslauf enthalten. Andere Lebensläufe behalten ihre eigenen Auswahlen.',
  'exp_nav_next'                        : 'Weiter zu Ausbildung',
  'exp_empty_message'                   : 'Noch keine Erfahrung hinzugefügt',
  'exp_empty_sub'                       : 'Tippe oben, um deine erste Stelle hinzuzufügen',
  'exp_card_resp_singular'              : 'Aufgabe',
  'exp_card_resp_plural'                : 'Aufgaben',
  'exp_card_resp_tooltip'               : 'Nur die ersten 8 Aufgaben erscheinen im Lebenslauf',
  'exp_sheet_title_add'                 : 'Erfahrung hinzufügen',
  'exp_sheet_title_edit'                : 'Erfahrung bearbeiten',
  'exp_sheet_field_job_title'           : 'Berufsbezeichnung *',
  'exp_sheet_field_company'             : 'Unternehmen *',
  'exp_sheet_field_location'            : 'Ort',
  'exp_sheet_section_responsibilities'  : 'Hauptaufgaben',
  'exp_sheet_resp_hint_info'            : 'Max. 8 Punkte · je 200 Zeichen',
  'exp_sheet_resp_label'                : 'Aufgabe {n}',
  'exp_sheet_resp_hint'                 : 'z.B. Leitete ein Team von 5 Ingenieuren',
  'exp_sheet_resp_add_btn'              : 'Aufgabe hinzufügen',
  'exp_sheet_resp_max_info'             : 'Maximale Anzahl von {n} Aufgaben erreicht',
  'exp_sheet_resp_validator_max'        : 'Max. 200 Zeichen',
  'exp_sheet_hint_job_title'            : 'z.B. Senior-Entwickler',
  'exp_sheet_hint_location'             : 'z.B. München, Deutschland',
  'exp_sheet_btn_save'                  : 'Erfahrung speichern',
  'exp_sheet_btn_update'                : 'Änderungen speichern',
  'exp_date_present'                    : 'Heute / Aktuelle Stelle',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Ausbildung',
  'edu_subtitle'                        : 'Füge deinen Bildungsweg hinzu',
  'edu_add_btn'                         : 'Neue Ausbildung hinzufügen',
  'edu_snack_max_selected'              : 'Maximal 8 Ausbildungseinträge können für einen Lebenslauf ausgewählt werden.',
  'edu_snack_max_saved'                 : 'Maximale Anzahl von 12 gespeicherten Ausbildungseinträgen erreicht.',
  'edu_library_title'                   : 'Gespeicherte Ausbildung',
  'edu_library_hint'                    : 'Ausgewählte Einträge sind in diesem Lebenslauf enthalten. Deine Auswahl wird automatisch gespeichert.',
  'edu_nav_next'                        : 'Weiter zu Fähigkeiten',
  'edu_empty_message'                   : 'Noch keine Ausbildung hinzugefügt',
  'edu_empty_sub'                       : 'Tippe oben, um deine Qualifikationen hinzuzufügen',
  'edu_card_bullet_singular'            : 'Punkt',
  'edu_card_bullet_plural'              : 'Punkte',
  'edu_sheet_title_add'                 : 'Ausbildung hinzufügen',
  'edu_sheet_title_edit'                : 'Ausbildung bearbeiten',
  'edu_sheet_field_degree'              : 'Abschluss / Qualifikation *',
  'edu_sheet_field_institution'         : 'Institution *',
  'edu_sheet_section_key_points'        : 'Wichtige Punkte',
  'edu_sheet_key_points_hint_info'      : 'Optional · 1 Stichpunkt · max. 100 Zeichen',
  'edu_sheet_point_label'               : 'Punkt {n}',
  'edu_sheet_point_add_btn'             : 'Stichpunkt hinzufügen',
  'edu_sheet_point_max_info'            : 'Maximale Anzahl von {n} Stichpunkten erreicht',
  'edu_sheet_point_validator_max'       : 'Max. {n} Zeichen',
  'edu_sheet_hint_degree'               : 'z.B. B.Sc. Informatik',
  'edu_sheet_hint_institution'          : 'z.B. Technische Universität München',
  'edu_sheet_hint_bullet'               : 'z.B. Mit Auszeichnung abgeschlossen',
  'edu_sheet_btn_save'                  : 'Ausbildung speichern',
  'edu_sheet_btn_update'                : 'Änderungen speichern',
  'edu_date_present'                    : 'Heute / Aktuelles Studium',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Zusätzliche Informationen',
  'additional_subtitle'                 : 'Zertifikate, Sprachen und mehr',
  'additional_cert_section_title'       : 'Zertifizierungen',
  'additional_cert_counter'             : '{sel}/{total} ausgewählt · max. {max}',
  'additional_cert_hide'                : 'Ausblenden',
  'additional_cert_show'                : 'Einblenden',
  'additional_cert_add_btn'             : 'Hinzufügen',
  'additional_cert_snack_max'           : 'Maximale Anzahl von {n} Zertifizierungseinträgen erreicht.',
  'additional_cert_hint'                : 'Ausgewählte Einträge sind in diesem Lebenslauf enthalten. Deine Auswahl wird automatisch gespeichert.',
  'additional_cert_empty'               : 'Noch keine Zertifizierungen hinzugefügt',
  'additional_lang_section_title'       : 'Sprachen',
  'additional_lang_add_hint'            : 'z.B. Spanisch',
  'additional_lang_snack_max'           : 'Maximale Anzahl von {n} Spracheinträgen erreicht.',
  'additional_lang_empty'               : 'Noch keine Sprachen hinzugefügt',
  'additional_hobby_section_title'      : 'Hobbys & Interessen',
  'additional_hobby_add_hint'           : 'z.B. Fotografie',
  'additional_hobby_snack_max'          : 'Maximale Anzahl von {n} Hobbyeinträgen erreicht.',
  'additional_hobby_empty'              : 'Noch keine Hobbys hinzugefügt',
  'additional_section_hint'             : 'Ausgewählte Einträge sind in diesem Lebenslauf enthalten. Deine Auswahl wird automatisch gespeichert.',
  'additional_nav_next'                 : 'Weiter zu Referenzen',
  'cert_sheet_title_add'                : 'Zertifizierung hinzufügen',
  'cert_sheet_title_edit'               : 'Zertifizierung bearbeiten',
  'cert_sheet_sub'                      : 'Füge eine Qualifikation, ein Zertifikat oder einen Berufsnachweis hinzu.',
  'cert_sheet_field_name'               : 'Name der Zertifizierung *',
  'cert_sheet_field_issued_by'          : 'Ausgestellt von (optional)',
  'cert_sheet_field_short_desc'         : 'Kurzbeschreibung (optional)',
  'cert_sheet_hint_name'                : 'z.B. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'z.B. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'z.B. Erhalten 2024',
  'cert_sheet_btn_save'                 : 'Zertifizierung speichern',
  'cert_sheet_btn_update'               : 'Zertifizierung aktualisieren',
  'simple_sheet_title_add_language'     : 'Sprache hinzufügen',
  'simple_sheet_title_edit_language'    : 'Sprache bearbeiten',
  'simple_sheet_title_add_hobby'        : 'Hobby hinzufügen',
  'simple_sheet_title_edit_hobby'       : 'Hobby bearbeiten',
  'simple_sheet_btn_save'               : 'Speichern',
  'simple_sheet_btn_update'             : 'Aktualisieren',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontakt',
  'pdf_section_about_me'                : 'Über mich',
  'pdf_section_summary'                 : 'Zusammenfassung',
  'pdf_section_summary_short'           : 'Zusammenfassung',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Berufserfahrung',
  'pdf_section_experience_short'        : 'Erfahrung',
  'pdf_section_education'               : 'Ausbildung',
  'pdf_section_skills'                  : 'Fähigkeiten',
  'pdf_section_languages'               : 'Sprachen',
  'pdf_label_email'                     : 'E-Mail',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Ort',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV-Limit erreicht',
  'limit_dialog_body'                   : 'Sie haben das Maximum von 30 Lebensläufen erreicht. Bitte löschen Sie einen vorhandenen Lebenslauf, bevor Sie einen neuen erstellen.',
  'limit_dialog_go_to_my_cvs'           : 'Zu Meine Lebensläufe',
  'limit_dialog_cancel'                 : 'Abbrechen',
  'refs_count_summary'                  : '{checked}/{maxChecked} ausgewählt · {saved}/{maxSaved} gespeichert',
  'refs_selected_badge'                 : '{n} ausgewählt',
  'refs_empty_message'                  : 'Noch keine Referenzen gespeichert',
  'refs_empty_sub'                      : 'Tippe oben, um eine persönliche Referenz hinzuzufügen',
};