// lib/language_keys/lang_sv_swedish.dart
//
// Swedish (Sweden) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> svSwedish = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Inga språk hittades',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Hoppa över',
  'onboarding_next'                     : 'Nästa',
  'onboarding_get_started'              : 'Kom igång',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Välkommen',
  'ob1_title'                           : 'Skapa ett CV som\nÖppnar Dörrar',
  'ob1_body'                            : 'Sticka ut bland hundratals sökande. Bygg ett polerat, jobbvinnande CV på minuter — inga designkunskaper behövs.',
  'ob1_pill_label'                      : 'Professionell CV-byggare',
  'ob1_chip_templates'                  : '24+ Mallar',
  'ob1_chip_pdf'                        : 'PDF-export',
  'ob1_chip_free'                       : 'Gratis att använda',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Mallar',
  'ob2_title'                           : 'Varje Bransch.\nVarje Ambition.',
  'ob2_body'                            : 'Från styrelserumsklara layouter till djärva kreativa designer — en mall som berättar din historia.',
  'ob2_tap_hint'                        : 'Tryck på en mall för förhandsgranskning',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Företag',
  'ob2_tag_creative'                    : 'Kreativ',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart layout',
  'ob3_title'                           : 'Ditt CV.\nPerfekt Arrangerat.',
  'ob3_body'                            : 'Smart layout ordnar om dina avsnitt för maximal effekt — och placerar ditt starkaste innehåll där rekryterare tittar först.',
  'ob3_badge_smart_layout'              : 'Smart layout',
  'ob3_badge_cv_ready'                  : 'CV klart!',
  'ob3_step1_label'                     : 'Välj en mall',
  'ob3_step1_desc'                      : 'Välj bland 24+ fantastiska designer.',
  'ob3_step2_label'                     : 'Fyll i dina uppgifter',
  'ob3_step2_desc'                      : 'Guidade fält för alla avsnitt.',
  'ob3_step3_label'                     : 'Smart layout',
  'ob3_step3_desc'                      : 'Ett tryck flödar om ditt CV perfekt.',
  'ob3_step4_label'                     : 'Exportera som PDF',
  'ob3_step4_desc'                      : 'Pixelperfekt PDF redo att skicka.',
  'ob3_section_work'                    : 'Arbetslivserfarenhet',
  'ob3_section_education'               : 'Utbildning',
  'ob3_section_skills'                  : 'Färdigheter',
  'ob3_section_references'              : 'Referenser',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Redo att sätta igång',
  'ob4_title'                           : 'Varför Toppkandidater\nVäljer CV Builder',
  'ob4_visual_headline'                 : 'Du är redo!',
  'ob4_visual_subline'                  : 'Allt du behöver för att få jobbet.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Mallar',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Max CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privat',
  'ob4_hl1_title'                       : 'Privat och säkert',
  'ob4_hl1_sub'                         : 'Data stannar på din enhet.',
  'ob4_hl2_title'                       : 'Autosparning',
  'ob4_hl2_sub'                         : 'Varje knapptryckning sparas direkt.',
  'ob4_hl3_title'                       : 'Upp till 30 CV',
  'ob4_hl3_sub'                         : 'Unikt CV för varje roll.',
  'ob4_hl4_title'                       : 'Dela med ett tryck',
  'ob4_hl4_sub'                         : 'Skicka PDF utan att lämna appen.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Sticka ut ur mängden',
  'home_hero_title'                     : 'Skapa ditt\nProfessionella CV',
  'home_hero_sub'                       : 'Bygg ett imponerande CV\npå minuter',
  'home_hero_cta'                       : 'Börja bygga',
  'home_premium_soon'                   : 'Uppgradering till Pro kommer snart!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Senaste',
  'history_sort_alphabetical'           : 'A–Ö',
  'history_sort_last_edited'            : 'Senast redigerad',
  'history_sort_by_template'            : 'Efter mall',
  'history_sort_sheet_title'            : 'Sortera efter',
  'history_sort_alphabetical_full'      : 'Alfabetisk (A–Ö)',
  'history_premium_soon'                : 'Uppgradering till Pro kommer snart!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Inställningar',
  'settings_section_preferences'        : 'Inställningar',
  'settings_section_support'            : 'Support',
  'settings_section_legal'              : 'Juridik',
  'settings_section_about'              : 'Om',
  'settings_language_tile_title'        : 'Språk',
  'settings_dark_mode_title'            : 'Mörkt läge',
  'settings_dark_mode_on'               : 'Mörkt tema aktiverat',
  'settings_dark_mode_off'              : 'Ljust tema aktiverat',
  'settings_help_faq_title'             : 'Hjälp och vanliga frågor',
  'settings_help_faq_sub'               : 'Vanliga frågor besvarade',
  'settings_contact_support_title'      : 'Kontakta support',
  'settings_rate_app_title'             : 'Betygsätt appen',
  'settings_rate_app_sub'               : 'Gillar du appen? Lämna ett omdöme!',
  'settings_privacy_policy_title'       : 'Integritetspolicy',
  'settings_terms_title'                : 'Användarvillkor',
  'settings_app_version_title'          : 'Appversion',
  'settings_email_error'                : 'Det gick inte att öppna e-postappen. Skicka e-post till cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CV-förhandsgranskning',
  'preview_header_sub'                  : 'Redo att exportera',
  'preview_generating'                  : 'Genererar ditt CV...',
  'preview_failed_title'                : 'Förhandsgranskning misslyckades',
  'preview_failed_error'                : 'Fel: {error}',
  'preview_go_back'                     : 'Gå tillbaka',
  'preview_no_data'                     : 'Inga data tillgängliga',
  'preview_btn_print'                   : 'Skriv ut',
  'preview_btn_download'                : 'Ladda ner och dela',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Hjälp och vanliga frågor',
  'faq_category_all'                    : 'Alla',
  'faq_empty'                           : 'Inga resultat hittades',
  'faq_contact_headline'                : 'Behöver du fortfarande hjälp?',
  'faq_contact_sub'                     : 'Vårt team finns här för dig.',
  'faq_contact_btn'                     : 'Kontakt',
  'faq_email_error'                     : 'Det gick inte att öppna e-postappen. Skicka e-post till cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Kom igång',
  'faq_cat_templates'                   : 'Mallar',
  'faq_cat_editing'                     : 'Redigering',
  'faq_cat_exporting'                   : 'Exportering',
  'faq_cat_data_privacy'                : 'Data och integritet',
  'faq_cat_troubleshooting'             : 'Felsökning',
  'faq_q1'  : 'Hur skapar jag mitt första CV?',
  'faq_a1'  : 'Tryck på "+"-knappen på startskärmen för att starta ett nytt CV. Välj en mall som passar din stil och fyll sedan i dina personuppgifter, arbetslivserfarenhet, utbildning och färdigheter steg för steg. Din framsteg sparas automatiskt.',
  'faq_q2'  : 'Kan jag skapa mer än ett CV?',
  'faq_a2'  : 'Ja! Du kan skapa flera CV för olika roller eller branscher. Varje CV sparas separat så att du kan anpassa dem till specifika jobbansökningar.',
  'faq_q3'  : 'Hur byter jag CV-mall?',
  'faq_a3'  : 'Öppna ditt CV, tryck på mallikonen längst upp på skärmen och bläddra bland tillgängliga mallar. Tryck på en mall för att förhandsgranska den med ditt befintliga innehåll. Bekräfta för att tillämpa den.',
  'faq_q4'  : 'Finns det gratis och premiummallar?',
  'faq_a4'  : 'Ja. Ett urval av professionella mallar är tillgängliga gratis. Premiummallar med avancerade designer och färgpaletter finns tillgängliga via ett engångsköp eller prenumeration.',
  'faq_q5'  : 'Hur lägger jag till eller tar bort avsnitt?',
  'faq_a5'  : 'Scrolla till botten av skärmen i CV-redigeraren och tryck på "Lägg till avsnitt" för att inkludera extras som Språk, Certifieringar eller Volontärarbete. För att ta bort ett avsnitt trycker du på avsnittsrubriken och väljer "Ta bort".',
  'faq_q6'  : 'Hur ordnar jag om avsnitt?',
  'faq_a6'  : 'Håll in draghandtaget (≡) bredvid en avsnittsrubrik och dra det till önskad position. Ändringar sparas automatiskt.',
  'faq_q7'  : 'Hur exporterar jag mitt CV som PDF?',
  'faq_a7'  : 'Öppna ditt CV och tryck på exportknappen (delningsikonen) i det övre högra hörnet. Välj "Exportera som PDF". Du kan sedan spara det på din enhet, dela det via e-post, WhatsApp eller ladda upp det direkt till jobbsajter.',
  'faq_q8'  : 'Vilka filformat stöds?',
  'faq_a8'  : 'Appen stöder för närvarande export av ditt CV som en högkvalitativ PDF. Ytterligare format kan läggas till i framtida uppdateringar.',
  'faq_q9'  : 'Var lagras mina CV-data?',
  'faq_a9'  : 'Alla dina CV-data lagras lokalt på din enhet. Vi laddar inte upp din personliga information till våra servrar. Det innebär att dina data förblir privata och tillgängliga offline.',
  'faq_q10' : 'Hur säkerhetskopierar jag mina CV?',
  'faq_a10' : 'Dina CV ingår i enhetens standardsäkerhetskopiering (Google Drive-säkerhetskopiering på Android, iCloud på iOS) om du har säkerhetskopiering aktiverad i enhetsinställningarna. Du kan även exportera enskilda CV som PDF för att behålla en kopia.',
  'faq_q11' : 'Appen är långsam. Vad ska jag göra?',
  'faq_a11' : 'Prova att stänga och öppna appen igen. Om problemet kvarstår, starta om enheten. Se till att du har den senaste versionen av appen installerad från Play Store / App Store.',
  'faq_q12' : 'Mitt CV exporteras inte korrekt. Vad ska jag göra?',
  'faq_a12' : 'Se till att du har tillräckligt med lagringsutrymme på enheten. Prova att minska stora bilder i ditt CV. Om problemet fortsätter, kontakta vårt supportteam.',
  'faq_q13' : 'Jag glömde att spara — är mitt arbete förlorat?',
  'faq_a13' : 'Inte alls! Appen sparar dina framsteg kontinuerligt medan du redigerar.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Din karriär, perfektionerad',
  'header_tooltip_back'                 : 'Tillbaka',
  'header_tooltip_my_cvs'               : 'Mina CV',
  'header_tooltip_settings'             : 'Inställningar',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Mina CV',
  'saved_count_single'                  : '{n} dokument',
  'saved_count_plural'                  : '{n} dokument',
  'saved_limit_reached'                 : 'Gräns nådd',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Alla',
  'saved_filter_draft'                  : 'Utkast',
  'saved_filter_complete'               : 'Klar',
  'saved_status_complete'               : 'Klar',
  'saved_status_saved'                  : 'Sparad',
  'saved_status_draft'                  : 'Utkast',
  'saved_empty_title'                   : 'Inga CV här ännu',
  'saved_empty_sub'                     : 'Börja bygga ditt första CV ovan',
  'saved_search_empty_title'            : 'Inga resultat hittades',
  'saved_search_empty_sub'              : 'Prova ett annat sökord',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Färgschema',
  'custom_font_settings_title'          : 'Teckensnittsinställningar',
  'custom_font_family_label'            : 'Teckensnittsfamilj',
  'custom_font_size_label'              : 'Teckenstorlek: ',
  'custom_current_template_title'       : 'Aktuell mall',
  'custom_change_template_btn'          : 'Byt mall',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klassisk',
  'custom_tpl_professional'             : 'Professionell',
  'custom_tpl_creative'                 : 'Kreativ',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Rent och modernt design',
  'custom_tpl_classic_desc'             : 'Traditionell professionell layout',
  'custom_tpl_professional_desc'        : 'Affärsinriktad mall',
  'custom_tpl_creative_desc'            : 'Sticka ut med unikt design',
  'custom_tpl_minimal_desc'             : 'Enkel och elegant stil',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Välj mall',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Mest populär',
  'tpl_nordic_tag'                      : 'Ren',
  'tpl_vibrant_tag'                     : 'Kreativ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elit',
  'tpl_executive_desc'                  : 'Djärv och auktoritativ för seniora roller',
  'tpl_nordic_desc'                     : 'Minimalistisk tydlighet betrodd av toppföretag',
  'tpl_vibrant_desc'                    : 'Sticka ut med energi och färg',
  'tpl_tech_dark_desc'                  : 'Terminalestetik för utvecklare',
  'tpl_luxury_desc'                     : 'Guldaccenter och prestige på svart',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Mall',
  'detail_step_personal'                : 'Personligt',
  'detail_step_experience'              : 'Erfarenhet',
  'detail_step_education'               : 'Utbildning',
  'detail_step_skills'                  : 'Färdigheter',
  'detail_step_additional'              : 'Övrigt',
  'detail_step_references'              : 'Referenser',
  'detail_step_customize'               : 'Anpassa',
  'detail_banner_heading'               : 'Nästan klart!',
  'detail_banner_btn'                   : 'Fortsätt',
  'detail_banner_completion_label'      : 'Färdigställande',
  'detail_stat_created_label'           : 'Skapad',
  'detail_stat_steps_label'             : 'Steg klara',
  'detail_section_template_style'       : 'Mallstil',
  'detail_section_steps'                : 'Steg',
  'detail_steps_counter'                : '{done} av {total} klara',
  'detail_step_sub'                     : 'Steg {n} av {total}',
  'detail_section_activity'             : 'Aktivitet',
  'detail_activity_created'             : 'Skapad',
  'detail_activity_last_edited'         : 'Senast redigerad',
  'detail_activity_template'            : 'Mall',
  'detail_btn_continue_editing'         : 'Fortsätt redigera',
  'detail_btn_edit_cv'                  : 'Redigera CV',
  'detail_option_rename'                : 'Byt namn på CV',
  'detail_option_delete'                : 'Ta bort CV',
  'detail_rename_title'                 : 'Byt namn på CV',
  'detail_rename_hint'                  : 't.ex. Mjukvaruingenjör CV',
  'detail_rename_error_empty'           : 'Namnet får inte vara tomt',
  'detail_rename_btn_cancel'            : 'Avbryt',
  'detail_rename_btn_save'              : 'Spara',
  'detail_rename_snackbar'              : 'Omdöpt till "{name}"',
  'detail_delete_title'                 : 'Ta bort CV?',
  'detail_delete_body'                  : 'Detta tar bort "{name}" permanent. Denna åtgärd kan inte ångras.',
  'detail_delete_btn_cancel'            : 'Avbryt',
  'detail_delete_btn_confirm'           : 'Ta bort',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Klar',
  'detail_check_tile_incomplete'        : 'Inte ifyllt ännu',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Välj din mall',
  'chooser_subtitle'                    : 'Svep för att bläddra  ·  Tryck för att välja  ·  Håll in för förhandsgranskning',
  'chooser_card_hold_hint'              : 'Håll in för förhandsgranskning',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Vald',
  'chooser_modal_heading'               : 'Namnge ditt CV',
  'chooser_modal_sub'                   : 'Ge det ett namn så att du enkelt hittar det i Mina CV och Historik.',
  'chooser_modal_field_label'           : 'CV-namn',
  'chooser_modal_save_btn'              : 'Spara och börja bygga',
  'chooser_modal_divider'               : 'eller fortsätt med ett befintligt CV',
  'chooser_nav_selected_sub'            : 'Vald mall',
  'chooser_nav_cta'                     : 'Spara och fortsätt',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maximalt antal poster nått',
  'editor_show_hide'                    : 'Visa/Dölj',
  'editor_editing_badge'                : 'Redigerar',
  'editor_field_required'               : 'Obligatoriskt',
  'editor_tooltip_edit'                 : 'Redigera',
  'editor_tooltip_delete'               : 'Ta bort',
  'editor_date_start'                   : 'Startdatum *',
  'editor_date_end'                     : 'Slutdatum *',
  'editor_date_tap_hint'                : 'Tryck för att välja',
  'editor_date_dialog_title'            : 'Välj månad och år',
  'editor_date_confirm'                 : 'Bekräfta',
  'editor_panel_hide'                   : 'Dölj',
  'editor_panel_show'                   : 'Visa',
  'editor_validator_max_chars'          : 'Max {n} tecken',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Bygg ditt CV',
  'editor_header_step_sub'              : 'Steg {current} av {total} · {label}',
  'editor_step_template'                : 'Mall',
  'editor_step_personal'                : 'Personligt',
  'editor_step_experience'              : 'Erfarenhet',
  'editor_step_education'               : 'Utbildning',
  'editor_step_skills'                  : 'Färdigheter',
  'editor_step_additional'              : 'Övrigt',
  'editor_step_references'              : 'Referenser',
  'editor_step_customize'               : 'Anpassa',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Anpassa',
  'customize_subtitle'                  : 'Gör ditt CV unikt ditt',
  'customize_smart_layout_btn'          : 'Smart layout',
  'customize_back_to_top'               : 'Tillbaka till toppen',
  'customize_done_title'                : 'Du är redo!',
  'customize_done_sub'                  : 'Tryck på Förhandsgranska CV nedan för att se ditt färdiga CV',
  'customize_preview_btn'               : 'Förhandsgranska CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Färgschema',
  'color_black'                         : 'Svart',
  'color_blue'                          : 'Blå',
  'color_nordic_blue'                   : 'Nordisk blå',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Blågrön',
  'color_green'                         : 'Grön',
  'color_purple'                        : 'Lila',
  'color_orange'                        : 'Orange',
  'color_red'                           : 'Röd',
  'color_executive_gold'                : 'Executive guld',
  'color_vibrant_coral'                 : 'Vibrant korall',
  'color_white'                         : 'Vit',
  'color_white_bg'                      : 'Vit bakgrund',
  'color_maroon'                        : 'Kastanjebrun',
  'color_brutalist_yellow'              : 'Brutalistisk gul',
  'color_neon_blue'                     : 'Neonblå',
  'color_blueprint_navy'                : 'Blueprint marinblå',
  'color_light_grey'                    : 'Ljusgrå',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Teckensnittsfamilj',
  'customize_font_picker_title'         : 'Välj teckensnitt',
  'customize_font_picker_sub'           : 'Varje teckensnitt visas i sin egen stil',
  'customize_font_preview_sample'       : 'Den snabba bruna räven',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Teckenstorlek',
  'customize_font_size_label'           : 'Textstorlek',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Bildstorlek',
  'customize_image_size_label'          : 'Bildstorlek',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Liveförhandsgranskning',
  'preview_page_count_singular'         : '1 sida',
  'preview_page_count_plural'           : '{n} sidor',
  'preview_page_of'                     : 'Sida {page} av {total}',
  'preview_live_hint'                   : 'Ändringar tillämpas direkt',
  'preview_template_unregistered'       : 'Inte registrerad i customize_preview.dart ännu',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Förbereder ditt CV…',
  'preview_bar_print'                   : 'Skriv ut',
  'preview_bar_save_pdf'                : 'Spara som PDF',
  'preview_bar_share'                   : 'Dela',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CV-förhandsgranskning',
  'preview_screen_sub'                  : '{n} {unit} · exakt som utskrivet',
  'preview_page_singular'               : 'sida',
  'preview_page_plural'                 : 'sidor',
  'preview_pdf_filename'                : 'Mitt_CV',
  'preview_share_subject'               : 'Mitt CV',
  'preview_snack_print_failed'          : 'Utskrift misslyckades: {e}',
  'preview_snack_saved'                 : 'CV sparat i Nedladdningar ✓',
  'preview_snack_export_failed'         : 'Export misslyckades: {e}',
  'preview_snack_share_failed'          : 'Delning misslyckades: {e}',
  'preview_template_not_registered'     : 'Mallen är inte registrerad',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Stäng förhandsgranskning',
  'preview_modal_hint_photo'            : 'Stöder profilfoto  ·  Tryck på ett kort för att välja',
  'preview_modal_hint_no_photo'         : 'Tryck på ett mallkort för att välja det',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Mitt CV',
  'time_just_now'                       : 'Just nu',
  'time_minutes_ago'                    : 'för {n} min sedan',
  'time_hours_ago'                      : 'för {n} tim sedan',
  'time_yesterday'                      : 'Igår',
  'time_days_ago'                       : 'för {n} dagar sedan',
  'time_one_week_ago'                   : 'för 1 vecka sedan',
  'time_weeks_ago'                      : 'för {n} veckor sedan',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegant',
  'tpl_tag_classic'                     : 'Klassisk',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Kreativ',
  'tpl_tag_bold'                        : 'Djärv',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Blågrön till violett gradientkort',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Redaktionell',
  'tpl_editorial_desc'                  : 'Tidningsstil i rött och gräddvitt',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastell Mjuk',
  'tpl_pastel_soft_desc'                : 'Lavendelsidobalk, mjuka kort',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalistisk',
  'tpl_brutalist_desc'                  : 'Råt rutnät, djärva ramar och gult',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragd',
  'tpl_emerald_desc'                    : 'Skogsgrönt med tidslinje',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografik',
  'tpl_infographic_desc'                : 'Mörk duk med ringdiagram',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920-talets geometriska guldlyx',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Mörk',
  'tpl_wina_dark_desc'                  : 'Mörk infografik med ringar',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Mörk sidobalk med orangeaccent',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Sommar',
  'tpl_summer_desc'                     : 'Rent minimalt, mjuka grå toner',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Varma beige eleganta toner',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Stark svartvit klassiker',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klassisk ATS-vänlig layout',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Mörk',
  'tpl_tony_dark_desc'                  : 'Mörk orange infografikstil',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Mode',
  'tpl_fashion_desc'                    : 'Teknisk ritning på rutnät',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arkivarie',
  'tpl_archivist_desc'                  : 'Klassisk tvåkolumns etikettlayout',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Skuggade rubriker med diamantledare',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Centrerade rubriker, accentföretag',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Djärvt namn, tidslinjepunkter och prestationer',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Personuppgifter',
  'personal_subtitle'                   : 'Berätta för arbetsgivare vem du är',
  'personal_profile_counter'            : '{n}/{max} profiler',
  'personal_info_banner'                : 'Spara upp till 5 profiler och välj en per CV. Ditt val sparas för varje CV separat.',
  'personal_snack_max'                  : 'Maximalt {n} profiler nått.',
  'personal_add_btn'                    : 'Lägg till ny profil',
  'personal_library_title'              : 'Sparade profiler',
  'personal_selected_one'               : '1 vald',
  'personal_selected_none'              : 'ingen vald',
  'personal_library_hint'               : 'Tryck på ett kort för att välja det endast för detta CV. Andra CV behåller sina egna oberoende val.',
  'personal_empty_message'              : 'Inga profiler sparade ännu',
  'personal_empty_sub'                  : 'Tryck ovan för att lägga till dina personuppgifter',
  'personal_nav_next'                   : 'Spara och fortsätt',
  'personal_card_active_badge'          : 'Aktiv för detta CV',
  'personal_sheet_title_add'            : 'Ny profil',
  'personal_sheet_title_edit'           : 'Redigera profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTISK',
  'personal_sheet_brutalist_banner'     : 'Brutalistisk mall har kompakta kontaktfält. Kortare värden (t.ex. bara stad) visas bäst.',
  'personal_section_photo'              : 'Profilfoto',
  'personal_section_basic'              : 'Grunduppgifter',
  'personal_section_contact'            : 'Kontakt',
  'personal_section_online'             : 'Online-närvaro',
  'personal_section_summary'            : 'Professionell sammanfattning',
  'personal_field_first_name'           : 'Förnamn *',
  'personal_field_last_name'            : 'Efternamn',
  'personal_field_job_title'            : 'Jobbtitel *',
  'personal_field_email'                : 'E-postadress *',
  'personal_field_phone'                : 'Telefonnummer *',
  'personal_field_location'             : 'Plats',
  'personal_field_location_brut'        : 'Plats (bara stad)',
  'personal_field_website'              : 'Webbplats / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn-URL',
  'personal_hint_first_name'            : 't.ex. Anna',
  'personal_hint_last_name'             : 't.ex. Andersson',
  'personal_hint_job_title'             : 't.ex. Senior ingenjör',
  'personal_hint_email'                 : 't.ex. anna@exempel.se',
  'personal_hint_phone'                 : 't.ex. +46 70 123 45 67',
  'personal_hint_location'              : 't.ex. Stockholm, Sverige',
  'personal_hint_location_brut'         : 't.ex. Stockholm, SE',
  'personal_hint_website'               : 't.ex. github.com/annaandersson',
  'personal_hint_website_brut'          : 't.ex. github.com/anna',
  'personal_hint_linkedin'              : 't.ex. linkedin.com/in/annaandersson',
  'personal_hint_linkedin_brut'         : 't.ex. linkedin.com/in/anna',
  'personal_summary_hint_label'         : 'Håll det kortfattat — detta visas längst upp i ditt CV.',
  'personal_hint_summary'               : 'En kort sammanfattning på 2–3 meningar om din bakgrund och dina mål...',
  'personal_validator_email'            : 'Ange en giltig e-postadress',
  'personal_field_char_limit_tooltip'   : 'Teckengräns nådd',
  'personal_sheet_btn_save'             : 'Spara profil',
  'personal_sheet_btn_update'           : 'Spara ändringar',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Välj foto',
  'photo_option_gallery'                : 'Välj från galleri',
  'photo_option_camera'                 : 'Ta ett foto',
  'photo_option_reposition'             : 'Flytta foto',
  'photo_option_remove'                 : 'Ta bort foto',
  'photo_status_added'                  : 'Foto tillagt ✓',
  'photo_status_empty'                  : 'Lägg till ett professionellt porträttfoto',
  'photo_chip_gallery'                  : 'Galleri',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Flytta',
  'photo_reposition_title'              : 'Flytta foto',
  'photo_reposition_sub'                : 'Dra fotot för att justera positionen',
  'photo_reposition_reset'              : 'Återställ till mitten',
  'photo_reposition_apply'              : 'Tillämpa',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Färdigheter',
  'skills_subtitle'                     : 'Lyft fram dina viktigaste förmågor',
  'skills_add_btn'                      : 'Lägg till ny färdighet',
  'skills_snack_max_icons'              : 'Maximalt 10 ikoner valda.',
  'skills_snack_max_skills'             : 'Maximalt 15 färdigheter nått.',
  'skills_library_title'                : 'Sparade färdigheter',
  'skills_library_hint'                 : 'Markerade färdigheter ingår i detta CV. Dina val sparas automatiskt.',
  'skills_nav_next'                     : 'Fortsätt till Övrigt',
  'skills_wina_header_icon_bar'         : 'Rubrikens ikonrad',
  'skills_wina_on'                      : 'PÅ',
  'skills_wina_off'                     : 'AV',
  'skills_wina_bar_on_sub'              : 'Färgade ikoncirklar visas i CV-rubriken.',
  'skills_wina_bar_off_sub'             : 'Ikonrad dold — mer utrymme för kontaktuppgifter.',
  'skills_wina_palette_hint'            : 'Ikoner visas som färgade cirklar i palettordningen.',
  'skills_wina_preview_label'           : 'Förhandsgranskning',
  'skills_wina_disabled_hint'           : 'Aktivera ikonraden ovan för att välja vilka ikoner som visas i CV-rubriken.',
  'skills_sheet_title_add'              : 'Lägg till färdighet',
  'skills_sheet_title_edit'             : 'Redigera färdighet',
  'skills_sheet_field_name'             : 'Färdighetsnamn *',
  'skills_sheet_hint_short'             : 't.ex. Flutter, Design',
  'skills_sheet_hint_long'              : 't.ex. Flutter, Projektledning',
  'skills_sheet_validator_max'          : 'Max {n} tecken',
  'skills_sheet_proficiency'            : 'Kunskapsnivå',
  'skills_sheet_beginner'               : 'Nybörjare',
  'skills_sheet_expert'                 : 'Expert',
  'skills_sheet_btn_save'               : 'Spara färdighet',
  'skills_sheet_btn_update'             : 'Uppdatera färdighet',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Personliga referenser',
  'refs_subtitle'                       : 'Personer som personligen kan gå i god för dig',
  'refs_add_btn'                        : 'Lägg till ny personlig referens',
  'refs_snack_max_selected'             : 'Maximalt 4 referenser kan väljas för ett CV.',
  'refs_snack_max_saved'                : 'Maximalt 10 sparade referenser nått.',
  'refs_library_title'                  : 'Sparade referenser',
  'refs_library_hint'                   : 'Markerade referenser ingår i detta CV. Max 4 per CV. Dina val sparas automatiskt.',
  'refs_nav_next'                       : 'Fortsätt till Anpassa',
  'refs_sheet_title_add'                : 'Lägg till personlig referens',
  'refs_sheet_title_edit'               : 'Redigera personlig referens',
  'refs_sheet_sub_add'                  : 'Någon som personligen kan rekommendera dig till arbetsgivare.',
  'refs_sheet_sub_edit'                 : 'Uppdatera den här referensens uppgifter nedan.',
  'refs_sheet_field_name'               : 'Fullständigt namn *',
  'refs_sheet_field_title'              : 'Jobbtitel *',
  'refs_sheet_field_company'            : 'Företag (valfritt)',
  'refs_sheet_field_email'              : 'E-postadress *',
  'refs_sheet_field_phone'              : 'Telefonnummer *',
  'refs_sheet_hint_name'                : 't.ex. Erik Johansson',
  'refs_sheet_hint_title'               : 't.ex. Teknikchef',
  'refs_sheet_hint_company'             : 't.ex. Acme AB',
  'refs_sheet_hint_email'               : 't.ex. erik@acme.se',
  'refs_sheet_hint_phone'               : 't.ex. +46 70 123 45 67',
  'refs_sheet_validator_email'          : 'Ange en giltig e-postadress',
  'refs_sheet_btn_save'                 : 'Spara personlig referens',
  'refs_sheet_btn_update'               : 'Uppdatera personlig referens',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Arbetslivserfarenhet',
  'exp_subtitle'                        : 'Lägg till din arbetshistorik',
  'exp_banner_info'                     : 'Upp till {n} ansvarsområden per roll visas på CV:t. 3–6 roller ryms vanligtvis på 1–2 sidor.',
  'exp_add_btn'                         : 'Lägg till ny erfarenhet',
  'exp_snack_max_selected'              : 'Maximalt 8 erfarenheter kan väljas för ett CV.',
  'exp_snack_max_saved'                 : 'Maximalt 12 sparade erfarenheter nått.',
  'exp_library_title'                   : 'Sparade erfarenheter',
  'exp_library_hint'                    : 'Markerade poster ingår bara i detta CV. Andra CV behåller sina egna oberoende val.',
  'exp_nav_next'                        : 'Fortsätt till Utbildning',
  'exp_empty_message'                   : 'Ingen erfarenhet tillagd ännu',
  'exp_empty_sub'                       : 'Tryck ovan för att lägga till din första roll',
  'exp_card_resp_singular'              : 'ansvarsområde',
  'exp_card_resp_plural'                : 'ansvarsområden',
  'exp_card_resp_tooltip'               : 'Bara de första 8 ansvarsområdena visas på CV:t',
  'exp_sheet_title_add'                 : 'Lägg till erfarenhet',
  'exp_sheet_title_edit'                : 'Redigera erfarenhet',
  'exp_sheet_field_job_title'           : 'Jobbtitel *',
  'exp_sheet_field_company'             : 'Företag *',
  'exp_sheet_field_location'            : 'Plats',
  'exp_sheet_section_responsibilities'  : 'Viktiga ansvarsområden',
  'exp_sheet_resp_hint_info'            : 'Max 8 punkter · 200 tecken var',
  'exp_sheet_resp_label'                : 'Ansvarsområde {n}',
  'exp_sheet_resp_hint'                 : 't.ex. Ledde ett team på 5 ingenjörer',
  'exp_sheet_resp_add_btn'              : 'Lägg till ansvarsområde',
  'exp_sheet_resp_max_info'             : 'Maximalt {n} ansvarsområden nått',
  'exp_sheet_resp_validator_max'        : 'Max 200 tecken',
  'exp_sheet_hint_job_title'            : 't.ex. Senior utvecklare',
  'exp_sheet_hint_location'             : 't.ex. Stockholm, Sverige',
  'exp_sheet_btn_save'                  : 'Spara erfarenhet',
  'exp_sheet_btn_update'                : 'Spara ändringar',
  'exp_date_present'                    : 'Nu / Nuvarande roll',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Utbildning',
  'edu_subtitle'                        : 'Lägg till din akademiska bakgrund',
  'edu_add_btn'                         : 'Lägg till ny utbildning',
  'edu_snack_max_selected'              : 'Maximalt 8 utbildningsposter kan väljas för ett CV.',
  'edu_snack_max_saved'                 : 'Maximalt 12 sparade utbildningsposter nått.',
  'edu_library_title'                   : 'Sparad utbildning',
  'edu_library_hint'                    : 'Markerade poster ingår i detta CV. Dina val sparas automatiskt.',
  'edu_nav_next'                        : 'Fortsätt till Färdigheter',
  'edu_empty_message'                   : 'Ingen utbildning tillagd ännu',
  'edu_empty_sub'                       : 'Tryck ovan för att lägga till dina kvalifikationer',
  'edu_card_bullet_singular'            : 'punkt',
  'edu_card_bullet_plural'              : 'punkter',
  'edu_sheet_title_add'                 : 'Lägg till utbildning',
  'edu_sheet_title_edit'                : 'Redigera utbildning',
  'edu_sheet_field_degree'              : 'Examen / Kvalifikation *',
  'edu_sheet_field_institution'         : 'Institution *',
  'edu_sheet_section_key_points'        : 'Viktiga punkter',
  'edu_sheet_key_points_hint_info'      : 'Valfritt · 1 punkt · max 100 tecken',
  'edu_sheet_point_label'               : 'Punkt {n}',
  'edu_sheet_point_add_btn'             : 'Lägg till punkt',
  'edu_sheet_point_max_info'            : 'Maximalt {n} punkter nått',
  'edu_sheet_point_validator_max'       : 'Max {n} tecken',
  'edu_sheet_hint_degree'               : 't.ex. Civilingenjör datateknik',
  'edu_sheet_hint_institution'          : 't.ex. Kungliga Tekniska Högskolan',
  'edu_sheet_hint_bullet'               : 't.ex. Utmärkelse med beröm',
  'edu_sheet_btn_save'                  : 'Spara utbildning',
  'edu_sheet_btn_update'                : 'Spara ändringar',
  'edu_date_present'                    : 'Nu / Pågående studier',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Övrig information',
  'additional_subtitle'                 : 'Certifieringar, språk och mer',
  'additional_cert_section_title'       : 'Certifieringar',
  'additional_cert_counter'             : '{sel}/{total} valda · max {max}',
  'additional_cert_hide'                : 'Dölj',
  'additional_cert_show'                : 'Visa',
  'additional_cert_add_btn'             : 'Lägg till',
  'additional_cert_snack_max'           : 'Maximalt {n} certifieringsposter nått.',
  'additional_cert_hint'                : 'Markerade poster ingår i detta CV. Dina val sparas automatiskt.',
  'additional_cert_empty'               : 'Inga certifieringar tillagda ännu',
  'additional_lang_section_title'       : 'Språk',
  'additional_lang_add_hint'            : 't.ex. Spanska',
  'additional_lang_snack_max'           : 'Maximalt {n} språkposter nått.',
  'additional_lang_empty'               : 'Inga språk tillagda ännu',
  'additional_hobby_section_title'      : 'Hobbyer och intressen',
  'additional_hobby_add_hint'           : 't.ex. Fotografi',
  'additional_hobby_snack_max'          : 'Maximalt {n} hobbyposter nått.',
  'additional_hobby_empty'              : 'Inga hobbyer tillagda ännu',
  'additional_section_hint'             : 'Markerade poster ingår i detta CV. Dina val sparas automatiskt.',
  'additional_nav_next'                 : 'Fortsätt till Referenser',
  'cert_sheet_title_add'                : 'Lägg till certifiering',
  'cert_sheet_title_edit'               : 'Redigera certifiering',
  'cert_sheet_sub'                      : 'Lägg till en kvalifikation, ett certifikat eller en professionell meritförteckning.',
  'cert_sheet_field_name'               : 'Certifieringsnamn *',
  'cert_sheet_field_issued_by'          : 'Utfärdad av (valfritt)',
  'cert_sheet_field_short_desc'         : 'Kort beskrivning (valfritt)',
  'cert_sheet_hint_name'                : 't.ex. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 't.ex. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 't.ex. Uppnådd 2024',
  'cert_sheet_btn_save'                 : 'Spara certifiering',
  'cert_sheet_btn_update'               : 'Uppdatera certifiering',
  'simple_sheet_title_add_language'     : 'Lägg till språk',
  'simple_sheet_title_edit_language'    : 'Redigera språk',
  'simple_sheet_title_add_hobby'        : 'Lägg till hobby',
  'simple_sheet_title_edit_hobby'       : 'Redigera hobby',
  'simple_sheet_btn_save'               : 'Spara',
  'simple_sheet_btn_update'             : 'Uppdatera',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontakt',
  'pdf_section_about_me'                : 'Om mig',
  'pdf_section_summary'                 : 'Sammanfattning',
  'pdf_section_summary_short'           : 'Sammanfattning',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Erfarenhet',
  'pdf_section_experience_short'        : 'Erfarenhet',
  'pdf_section_education'               : 'Utbildning',
  'pdf_section_skills'                  : 'Färdigheter',
  'pdf_section_languages'               : 'Språk',
  'pdf_label_email'                     : 'E-post',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Plats',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV-gräns uppnådd',
  'limit_dialog_body'                   : 'Du har nått det maximala antalet på 30 CVn. Ta bort ett befintligt CV innan du skapar ett nytt.',
  'limit_dialog_go_to_my_cvs'           : 'Gå till Mina CVn',
  'limit_dialog_cancel'                 : 'Avbryt',
  'refs_count_summary'                  : '{checked}/{maxChecked} valda · {saved}/{maxSaved} sparade',
  'refs_selected_badge'                 : '{n} valda',
  'refs_empty_message'                  : 'Inga referenser sparade ännu',
  'refs_empty_sub'                      : 'Tryck ovan för att lägga till en personlig referens',
};