// lib/language_keys/lang_ja_japanese.dart
//
// Japanese (日本語) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> jaJapanese = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : '言語が見つかりません',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'スキップ',
  'onboarding_next'                     : '次へ',
  'onboarding_get_started'              : 'はじめる',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  ようこそ',
  'ob1_title'                           : '扉を開く履歴書を\n作成しましょう',
  'ob1_body'                            : '数百人の応募者の中から際立ちましょう。デザインのスキルは不要。プロフェッショナルな履歴書を数分で作成できます。',
  'ob1_pill_label'                      : 'プロフェッショナル履歴書ビルダー',
  'ob1_chip_templates'                  : '24種以上のテンプレート',
  'ob1_chip_pdf'                        : 'PDFエクスポート',
  'ob1_chip_free'                       : '無料で使用可能',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  テンプレート',
  'ob2_title'                           : 'あらゆる業界。\nあらゆる目標に。',
  'ob2_body'                            : '役員向けのレイアウトから個性的なクリエイティブデザインまで、あなたのストーリーを伝えるテンプレートが揃っています。',
  'ob2_tap_hint'                        : 'テンプレートをタップしてプレビュー',
  'ob2_tpl_executive'                   : 'エグゼクティブ',
  'ob2_tpl_vibrant'                     : 'バイブラント',
  'ob2_tpl_nordic'                      : 'ノルディック',
  'ob2_tpl_tech_dark'                   : 'テックダーク',
  'ob2_tpl_luxury'                      : 'ラグジュアリー',
  'ob2_tag_corporate'                   : 'コーポレート',
  'ob2_tag_creative'                    : 'クリエイティブ',
  'ob2_tag_minimal'                     : 'ミニマル',
  'ob2_tag_modern'                      : 'モダン',
  'ob2_tag_premium'                     : 'プレミアム',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  スマートレイアウト',
  'ob3_title'                           : 'あなたの履歴書を\n完璧に整えましょう。',
  'ob3_body'                            : 'スマートレイアウトが最大限の効果を出すようにセクションを並び替え、採用担当者が最初に目にする場所に最も強力なコンテンツを配置します。',
  'ob3_badge_smart_layout'              : 'スマートレイアウト',
  'ob3_badge_cv_ready'                  : 'CV完成！',
  'ob3_step1_label'                     : 'テンプレートを選ぶ',
  'ob3_step1_desc'                      : '24種以上の魅力的なデザインから選択。',
  'ob3_step2_label'                     : '詳細を入力する',
  'ob3_step2_desc'                      : '全セクションのガイド付き入力欄。',
  'ob3_step3_label'                     : 'スマートレイアウト',
  'ob3_step3_desc'                      : 'ワンタップで履歴書を最適化。',
  'ob3_step4_label'                     : 'PDFとして出力',
  'ob3_step4_desc'                      : '送付可能な高品質PDFが完成。',
  'ob3_section_work'                    : '職歴',
  'ob3_section_education'               : '学歴',
  'ob3_section_skills'                  : 'スキル',
  'ob3_section_references'              : '推薦者',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  準備完了',
  'ob4_title'                           : 'トップ候補者が\n選ぶ理由',
  'ob4_visual_headline'                 : '準備完了です！',
  'ob4_visual_subline'                  : '就職に必要なすべてが揃っています。',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'テンプレート',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : '最大CV数',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'エクスポート',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'プライベート',
  'ob4_hl1_title'                       : 'プライバシーと安全性',
  'ob4_hl1_sub'                         : 'データはデバイスに保存されます。',
  'ob4_hl2_title'                       : '自動保存',
  'ob4_hl2_sub'                         : 'すべての変更が即時保存されます。',
  'ob4_hl3_title'                       : '最大30件のCV',
  'ob4_hl3_sub'                         : '各職種向けに個別のCVを作成。',
  'ob4_hl4_title'                       : 'ワンタップ共有',
  'ob4_hl4_sub'                         : 'アプリを離れずにPDFを送信。',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ 他の応募者と差をつけましょう',
  'home_hero_title'                     : 'プロフェッショナルな\n履歴書を作成しましょう',
  'home_hero_sub'                       : '数分で魅力的な\n履歴書を作成',
  'home_hero_cta'                       : '作成を開始',
  'home_premium_soon'                   : 'Proへのアップグレードは近日公開！',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : '最新順',
  'history_sort_alphabetical'           : 'A〜Z順',
  'history_sort_last_edited'            : '最終編集順',
  'history_sort_by_template'            : 'テンプレート別',
  'history_sort_sheet_title'            : '並び替え',
  'history_sort_alphabetical_full'      : 'アルファベット順 (A〜Z)',
  'history_premium_soon'                : 'Proへのアップグレードは近日公開！',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : '設定',
  'settings_section_preferences'        : '環境設定',
  'settings_section_support'            : 'サポート',
  'settings_section_legal'              : '法的情報',
  'settings_section_about'              : 'アプリについて',
  'settings_language_tile_title'        : '言語',
  'settings_dark_mode_title'            : 'ダークモード',
  'settings_dark_mode_on'               : 'ダークテーマ有効',
  'settings_dark_mode_off'              : 'ライトテーマ有効',
  'settings_help_faq_title'             : 'ヘルプとよくある質問',
  'settings_help_faq_sub'               : 'よくある質問への回答',
  'settings_contact_support_title'      : 'サポートに連絡',
  'settings_rate_app_title'             : 'アプリを評価する',
  'settings_rate_app_sub'               : 'アプリをお楽しみいただけていますか？レビューをお書きください！',
  'settings_privacy_policy_title'       : 'プライバシーポリシー',
  'settings_terms_title'                : '利用規約',
  'settings_app_version_title'          : 'アプリバージョン',
  'settings_email_error'                : 'メールアプリを開けませんでした。cyberinc101@gmail.com までメールをお送りください',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CVプレビュー',
  'preview_header_sub'                  : 'エクスポート準備完了',
  'preview_generating'                  : 'CVを生成中...',
  'preview_failed_title'                : 'プレビュー失敗',
  'preview_failed_error'                : 'エラー: {error}',
  'preview_go_back'                     : '戻る',
  'preview_no_data'                     : 'データがありません',
  'preview_btn_print'                   : '印刷',
  'preview_btn_download'                : 'ダウンロード＆共有',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'ヘルプとよくある質問',
  'faq_category_all'                    : 'すべて',
  'faq_empty'                           : '結果が見つかりません',
  'faq_contact_headline'                : 'それでもお困りですか？',
  'faq_contact_sub'                     : 'チームがサポートします。',
  'faq_contact_btn'                     : 'お問い合わせ',
  'faq_email_error'                     : 'メールアプリを開けませんでした。cyberinc101@gmail.com までメールをお送りください',
  'faq_cat_getting_started'             : 'はじめ方',
  'faq_cat_templates'                   : 'テンプレート',
  'faq_cat_editing'                     : '編集',
  'faq_cat_exporting'                   : 'エクスポート',
  'faq_cat_data_privacy'                : 'データとプライバシー',
  'faq_cat_troubleshooting'             : 'トラブルシューティング',
  'faq_q1'  : '最初の履歴書はどのように作成しますか？',
  'faq_a1'  : 'ホーム画面の「＋」ボタンをタップして新しいCVを作成します。スタイルに合ったテンプレートを選び、個人情報・職歴・学歴・スキルを順番に入力してください。進捗は自動的に保存されます。',
  'faq_q2'  : 'CVを複数作成できますか？',
  'faq_a2'  : 'はい！異なる職種や業界向けに複数のCVを作成できます。各CVは個別に保存されるため、特定の求人に合わせてカスタマイズできます。',
  'faq_q3'  : 'CVのテンプレートはどのように変更しますか？',
  'faq_a3'  : 'CVを開き、画面上部のテンプレートアイコンをタップして利用可能なテンプレートを閲覧します。テンプレートをタップすると現在の内容でプレビューできます。確認して適用してください。',
  'faq_q4'  : '無料テンプレートと有料テンプレートはありますか？',
  'faq_a4'  : 'はい。プロフェッショナルなテンプレートの一部は無料でご利用いただけます。高度なデザインとカラーパレットを持つプレミアムテンプレートは、一回限りの購入またはサブスクリプションでご利用いただけます。',
  'faq_q5'  : 'セクションの追加や削除はどうすればできますか？',
  'faq_a5'  : 'CVエディタで画面下部にスクロールし、「セクションを追加」をタップすると、語学・資格・ボランティア活動などを追加できます。セクションを削除するには、セクションヘッダーをタップして「削除」を選択してください。',
  'faq_q6'  : 'セクションの順序を変更するにはどうすればよいですか？',
  'faq_a6'  : 'セクションヘッダー横のドラッグハンドル（≡）を長押しして、希望の位置にドラッグしてください。変更は自動的に保存されます。',
  'faq_q7'  : 'CVをPDFとしてエクスポートするにはどうすればよいですか？',
  'faq_a7'  : 'CVを開き、右上角のエクスポートボタン（共有アイコン）をタップします。「PDFとしてエクスポート」を選択してください。デバイスへの保存、メール・WhatsApp経由での共有、または求人サイトへの直接アップロードが可能です。',
  'faq_q8'  : 'どのファイル形式に対応していますか？',
  'faq_a8'  : '現在、アプリは高品質PDFとしてのCVエクスポートに対応しています。今後のアップデートで他の形式が追加される場合があります。',
  'faq_q9'  : 'CVのデータはどこに保存されますか？',
  'faq_a9'  : 'すべてのCVデータはデバイスにローカル保存されます。個人情報をサーバーにアップロードすることはありません。データはプライベートに保たれ、オフラインでもアクセス可能です。',
  'faq_q10' : 'CVのバックアップはどのように取りますか？',
  'faq_a10' : 'デバイス設定でバックアップを有効にしている場合、CVはデバイスの標準バックアップ（AndroidはGoogle Driveバックアップ、iOSはiCloud）に含まれます。個別のCVをPDFとしてエクスポートしてコピーを保存することもできます。',
  'faq_q11' : 'アプリの動作が遅いです。どうすればよいですか？',
  'faq_a11' : 'アプリを閉じて再起動してみてください。問題が続く場合は、デバイスを再起動してください。Play Store / App Storeから最新バージョンのアプリがインストールされていることを確認してください。',
  'faq_q12' : 'CVが正しくエクスポートされません。どうすればよいですか？',
  'faq_a12' : 'デバイスに十分なストレージ容量があることを確認してください。CV内の大きな画像を縮小してみてください。問題が続く場合は、サポートチームにお問い合わせください。',
  'faq_q13' : '保存し忘れました。作業内容は失われましたか？',
  'faq_a13' : '大丈夫です！アプリは編集中に継続的に進捗を保存しています。',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'あなたのキャリアを磨きましょう',
  'header_tooltip_back'                 : '戻る',
  'header_tooltip_my_cvs'               : 'マイCV',
  'header_tooltip_settings'             : '設定',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'マイCV',
  'saved_count_single'                  : '{n}件',
  'saved_count_plural'                  : '{n}件',
  'saved_limit_reached'                 : '上限に達しました',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'すべて',
  'saved_filter_draft'                  : '下書き',
  'saved_filter_complete'               : '完成',
  'saved_status_complete'               : '完成',
  'saved_status_saved'                  : '保存済み',
  'saved_status_draft'                  : '下書き',
  'saved_empty_title'                   : 'CVがまだありません',
  'saved_empty_sub'                     : '上から最初のCVを作成してください',
  'saved_search_empty_title'            : '結果が見つかりません',
  'saved_search_empty_sub'              : '別の検索キーワードをお試しください',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'カラースキーム',
  'custom_font_settings_title'          : 'フォント設定',
  'custom_font_family_label'            : 'フォントファミリー',
  'custom_font_size_label'              : 'フォントサイズ: ',
  'custom_current_template_title'       : '現在のテンプレート',
  'custom_change_template_btn'          : 'テンプレートを変更',
  'custom_tpl_modern'                   : 'モダン',
  'custom_tpl_classic'                  : 'クラシック',
  'custom_tpl_professional'             : 'プロフェッショナル',
  'custom_tpl_creative'                 : 'クリエイティブ',
  'custom_tpl_minimal'                  : 'ミニマル',
  'custom_tpl_modern_desc'              : 'クリーンでコンテンポラリーなデザイン',
  'custom_tpl_classic_desc'             : '伝統的なプロフェッショナルレイアウト',
  'custom_tpl_professional_desc'        : 'ビジネス重視のテンプレート',
  'custom_tpl_creative_desc'            : 'ユニークなデザインで際立つ',
  'custom_tpl_minimal_desc'             : 'シンプルでエレガントなスタイル',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'テンプレートを選ぶ',
  'swipe_photo_badge'                   : '写真',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'エグゼクティブ',
  'tpl_nordic_name'                     : 'ノルディック',
  'tpl_vibrant_name'                    : 'バイブラント',
  'tpl_tech_dark_name'                  : 'テックダーク',
  'tpl_luxury_name'                     : 'ラグジュアリー',
  'tpl_executive_tag'                   : '人気No.1',
  'tpl_nordic_tag'                      : 'クリーン',
  'tpl_vibrant_tag'                     : 'クリエイティブ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'エリート',
  'tpl_executive_desc'                  : '上級職向けの力強い権威あるデザイン',
  'tpl_nordic_desc'                     : '一流企業に信頼されるミニマルな明快さ',
  'tpl_vibrant_desc'                    : 'エネルギーと色彩で際立つ',
  'tpl_tech_dark_desc'                  : '開発者向けターミナル風デザイン',
  'tpl_luxury_desc'                     : '黒地にゴールドアクセントの高級感',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'テンプレート',
  'detail_step_personal'                : '個人情報',
  'detail_step_experience'              : '職歴',
  'detail_step_education'               : '学歴',
  'detail_step_skills'                  : 'スキル',
  'detail_step_additional'              : '追加情報',
  'detail_step_references'              : '推薦者',
  'detail_step_customize'               : 'カスタマイズ',
  'detail_banner_heading'               : 'もう少しです！',
  'detail_banner_btn'                   : '続ける',
  'detail_banner_completion_label'      : '完成度',
  'detail_stat_created_label'           : '作成日',
  'detail_stat_steps_label'             : '完了ステップ',
  'detail_section_template_style'       : 'テンプレートスタイル',
  'detail_section_steps'                : 'ステップ',
  'detail_steps_counter'                : '{total}件中{done}件完了',
  'detail_step_sub'                     : 'ステップ {n} / {total}',
  'detail_section_activity'             : 'アクティビティ',
  'detail_activity_created'             : '作成日',
  'detail_activity_last_edited'         : '最終編集日',
  'detail_activity_template'            : 'テンプレート',
  'detail_btn_continue_editing'         : '編集を続ける',
  'detail_btn_edit_cv'                  : 'CVを編集',
  'detail_option_rename'                : 'CVの名前を変更',
  'detail_option_delete'                : 'CVを削除',
  'detail_rename_title'                 : 'CVの名前を変更',
  'detail_rename_hint'                  : '例：ソフトウェアエンジニア CV',
  'detail_rename_error_empty'           : '名前を入力してください',
  'detail_rename_btn_cancel'            : 'キャンセル',
  'detail_rename_btn_save'              : '保存',
  'detail_rename_snackbar'              : '「{name}」に名前を変更しました',
  'detail_delete_title'                 : 'CVを削除しますか？',
  'detail_delete_body'                  : '「{name}」を完全に削除します。この操作は取り消せません。',
  'detail_delete_btn_cancel'            : 'キャンセル',
  'detail_delete_btn_confirm'           : '削除',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : '完了済み',
  'detail_check_tile_incomplete'        : '未入力',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'テンプレートを選んでください',
  'chooser_subtitle'                    : 'スワイプして閲覧  ·  タップして選択  ·  長押しでプレビュー',
  'chooser_card_hold_hint'              : '長押しでプレビュー',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : '選択中',
  'chooser_modal_heading'               : 'CVに名前をつけましょう',
  'chooser_modal_sub'                   : 'マイCVや履歴で簡単に見つけられるよう名前をつけましょう。',
  'chooser_modal_field_label'           : 'CV名',
  'chooser_modal_save_btn'              : '保存して作成開始',
  'chooser_modal_divider'               : 'または既存のCVを続ける',
  'chooser_nav_selected_sub'            : '選択中のテンプレート',
  'chooser_nav_cta'                     : '保存して続ける',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : '最大入力数に達しました',
  'editor_show_hide'                    : '表示/非表示',
  'editor_editing_badge'                : '編集中',
  'editor_field_required'               : '必須',
  'editor_tooltip_edit'                 : '編集',
  'editor_tooltip_delete'               : '削除',
  'editor_date_start'                   : '開始日 *',
  'editor_date_end'                     : '終了日 *',
  'editor_date_tap_hint'                : 'タップして選択',
  'editor_date_dialog_title'            : '年月を選択',
  'editor_date_confirm'                 : '確認',
  'editor_panel_hide'                   : '非表示',
  'editor_panel_show'                   : '表示',
  'editor_validator_max_chars'          : '最大{n}文字',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'CVを作成する',
  'editor_header_step_sub'              : 'ステップ {current} / {total} · {label}',
  'editor_step_template'                : 'テンプレート',
  'editor_step_personal'                : '個人情報',
  'editor_step_experience'              : '職歴',
  'editor_step_education'               : '学歴',
  'editor_step_skills'                  : 'スキル',
  'editor_step_additional'              : '追加情報',
  'editor_step_references'              : '推薦者',
  'editor_step_customize'               : 'カスタマイズ',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'カスタマイズ',
  'customize_subtitle'                  : 'CVをあなただけのものに',
  'customize_smart_layout_btn'          : 'スマートレイアウト',
  'customize_back_to_top'               : 'トップに戻る',
  'customize_done_title'                : '準備完了です！',
  'customize_done_sub'                  : '下の「CVをプレビュー」をタップして完成したCVを確認してください',
  'customize_preview_btn'               : 'CVをプレビュー',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'カラースキーム',
  'color_black'                         : 'ブラック',
  'color_blue'                          : 'ブルー',
  'color_nordic_blue'                   : 'ノルディックブルー',
  'color_indigo'                        : 'インディゴ',
  'color_teal'                          : 'ティール',
  'color_green'                         : 'グリーン',
  'color_purple'                        : 'パープル',
  'color_orange'                        : 'オレンジ',
  'color_red'                           : 'レッド',
  'color_executive_gold'                : 'エグゼクティブゴールド',
  'color_vibrant_coral'                 : 'バイブラントコーラル',
  'color_white'                         : 'ホワイト',
  'color_white_bg'                      : 'ホワイト背景',
  'color_maroon'                        : 'マルーン',
  'color_brutalist_yellow'              : 'ブルータリストイエロー',
  'color_neon_blue'                     : 'ネオンブルー',
  'color_blueprint_navy'                : 'ブループリントネイビー',
  'color_light_grey'                    : 'ライトグレー',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'フォントファミリー',
  'customize_font_picker_title'         : 'フォントを選ぶ',
  'customize_font_picker_sub'           : '各フォントは独自の書体でプレビュー表示されます',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'フォントサイズ',
  'customize_font_size_label'           : 'テキストサイズ',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : '画像サイズ',
  'customize_image_size_label'          : '画像サイズ',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'ライブプレビュー',
  'preview_page_count_singular'         : '1ページ',
  'preview_page_count_plural'           : '{n}ページ',
  'preview_page_of'                     : '{total}ページ中 {page}ページ目',
  'preview_live_hint'                   : '変更は即時反映されます',
  'preview_template_unregistered'       : 'customize_preview.dartにまだ登録されていません',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'CVを準備中…',
  'preview_bar_print'                   : '印刷',
  'preview_bar_save_pdf'                : 'PDFとして保存',
  'preview_bar_share'                   : '共有',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CVプレビュー',
  'preview_screen_sub'                  : '{n} {unit} · 印刷時と同じ表示',
  'preview_page_singular'               : 'ページ',
  'preview_page_plural'                 : 'ページ',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : '私のCV',
  'preview_snack_print_failed'          : '印刷に失敗しました: {e}',
  'preview_snack_saved'                 : 'CVをダウンロードに保存しました ✓',
  'preview_snack_export_failed'         : 'エクスポートに失敗しました: {e}',
  'preview_snack_share_failed'          : '共有に失敗しました: {e}',
  'preview_template_not_registered'     : 'テンプレートが登録されていません',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'プレビューを閉じる',
  'preview_modal_hint_photo'            : 'プロフィール写真対応  ·  カードをタップして選択',
  'preview_modal_hint_no_photo'         : 'テンプレートカードをタップして選択',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'マイCV',
  'time_just_now'                       : 'たった今',
  'time_minutes_ago'                    : '{n}分前',
  'time_hours_ago'                      : '{n}時間前',
  'time_yesterday'                      : '昨日',
  'time_days_ago'                       : '{n}日前',
  'time_one_week_ago'                   : '1週間前',
  'time_weeks_ago'                      : '{n}週間前',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'エレガント',
  'tpl_tag_classic'                     : 'クラシック',
  'tpl_tag_minimal'                     : 'ミニマル',
  'tpl_tag_creative'                    : 'クリエイティブ',
  'tpl_tag_bold'                        : 'ボールド',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'グラデーション',
  'tpl_gradient_desc'                   : 'ティールからバイオレットへのグラデーションカード',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'エディトリアル',
  'tpl_editorial_desc'                  : '雑誌風のレッド＆クリームデザイン',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'パステルソフト',
  'tpl_pastel_soft_desc'                : 'ラベンダーサイドバーのやわらかいカード',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'ブルータリスト',
  'tpl_brutalist_desc'                  : 'ローグリッド、太いボーダーとイエロー',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'エメラルド',
  'tpl_emerald_desc'                    : 'タイムライン付きフォレストグリーン',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'インフォグラフィック',
  'tpl_infographic_desc'                : 'リングチャート付きダークキャンバス',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'アールデコ',
  'tpl_art_deco_desc'                   : '1920年代のジオメトリックゴールドラグジュアリー',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'ウィナダーク',
  'tpl_wina_dark_desc'                  : 'リング付きダークインフォグラフィック',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'リオオレンジ',
  'tpl_rio_orange_desc'                 : 'オレンジアクセントのダークサイドバー',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'サマー',
  'tpl_summer_desc'                     : 'クリーンなミニマル、ソフトグレートーン',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'ヘレーネ',
  'tpl_helene_desc'                     : 'ウォームベージュのエレガントなトーン',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'キャンフィールド',
  'tpl_canfield_desc'                   : 'モノクロのスタークなクラシックデザイン',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'コリンズ',
  'tpl_collins_desc'                    : 'ATS対応のクラシックレイアウト',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'トニーダーク',
  'tpl_tony_dark_desc'                  : 'ダークオレンジのインフォグラフィックスタイル',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'ファッション',
  'tpl_fashion_desc'                    : 'グリッド上の技術図面スタイル',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'アーキビスト',
  'tpl_archivist_desc'                  : 'クラシックな2カラムラベルレイアウト',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'ディプロマット',
  'tpl_diplomat_desc'                   : 'ダイヤモンドリーダー付きシェードヘッダー',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'メリディアン',
  'tpl_meridian_desc'                   : 'センタリングヘッダー、アクセント会社名',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'モメンタム',
  'tpl_momentum_desc'                   : '太字の名前、タイムラインドットと実績',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : '個人情報',
  'personal_subtitle'                   : '採用担当者にあなたを伝えましょう',
  'personal_profile_counter'            : '{n}/{max} 件のプロフィール',
  'personal_info_banner'                : '最大5件のプロフィールを保存して、CV毎に1件選択できます。選択はCVごとに個別に記憶されます。',
  'personal_snack_max'                  : 'プロフィールの上限 {n} 件に達しました。',
  'personal_add_btn'                    : '新しいプロフィールを追加',
  'personal_library_title'              : '保存済みプロフィール',
  'personal_selected_one'               : '1件選択中',
  'personal_selected_none'              : '未選択',
  'personal_library_hint'               : 'カードをタップするとこのCVのみに選択されます。他のCVは独立した選択を保持します。',
  'personal_empty_message'              : 'プロフィールがまだ保存されていません',
  'personal_empty_sub'                  : '上からタップして個人情報を追加してください',
  'personal_nav_next'                   : '保存して続ける',
  'personal_card_active_badge'          : 'このCVで有効',
  'personal_sheet_title_add'            : '新しいプロフィール',
  'personal_sheet_title_edit'           : 'プロフィールを編集',
  'personal_sheet_brutalist_badge'      : 'ブルータリスト',
  'personal_sheet_brutalist_banner'     : 'ブルータリストテンプレートはコンパクトな連絡先フィールドを使用しています。短い値（例：市区町村のみ）が最適に表示されます。',
  'personal_section_photo'              : 'プロフィール写真',
  'personal_section_basic'              : '基本情報',
  'personal_section_contact'            : '連絡先',
  'personal_section_online'             : 'オンラインプレゼンス',
  'personal_section_summary'            : '職務経歴概要',
  'personal_field_first_name'           : '名 *',
  'personal_field_last_name'            : '姓',
  'personal_field_job_title'            : '職種 *',
  'personal_field_email'                : 'メールアドレス *',
  'personal_field_phone'                : '電話番号 *',
  'personal_field_location'             : '所在地',
  'personal_field_location_brut'        : '所在地（市区町村のみ）',
  'personal_field_website'              : 'ウェブサイト / ポートフォリオ',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : '例：太郎',
  'personal_hint_last_name'             : '例：山田',
  'personal_hint_job_title'             : '例：シニアエンジニア',
  'personal_hint_email'                 : '例：taro@example.com',
  'personal_hint_phone'                 : '例：090-1234-5678',
  'personal_hint_location'              : '例：東京都、日本',
  'personal_hint_location_brut'         : '例：東京',
  'personal_hint_website'               : '例：github.com/taro',
  'personal_hint_website_brut'          : '例：github.com/taro',
  'personal_hint_linkedin'              : '例：linkedin.com/in/taro',
  'personal_hint_linkedin_brut'         : '例：linkedin.com/in/taro',
  'personal_summary_hint_label'         : '簡潔にまとめましょう — CVの冒頭に表示されます。',
  'personal_hint_summary'               : '経歴と目標を2〜3文で簡潔にまとめてください...',
  'personal_validator_email'            : '有効なメールアドレスを入力してください',
  'personal_field_char_limit_tooltip'   : '文字数の上限に達しました',
  'personal_sheet_btn_save'             : 'プロフィールを保存',
  'personal_sheet_btn_update'           : '変更を保存',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : '写真を選択',
  'photo_option_gallery'                : 'ギャラリーから選択',
  'photo_option_camera'                 : '写真を撮影',
  'photo_option_reposition'             : '写真の位置を調整',
  'photo_option_remove'                 : '写真を削除',
  'photo_status_added'                  : '写真を追加しました ✓',
  'photo_status_empty'                  : 'プロフェッショナルな証明写真を追加',
  'photo_chip_gallery'                  : 'ギャラリー',
  'photo_chip_camera'                   : 'カメラ',
  'photo_chip_reposition'               : '位置を調整',
  'photo_reposition_title'              : '写真の位置を調整',
  'photo_reposition_sub'                : '写真をドラッグして位置を調整してください',
  'photo_reposition_reset'              : '中央にリセット',
  'photo_reposition_apply'              : '適用',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'スキル',
  'skills_subtitle'                     : '主要なスキルをアピールしましょう',
  'skills_add_btn'                      : '新しいスキルを追加',
  'skills_snack_max_icons'              : '最大10件のアイコンを選択しました。',
  'skills_snack_max_skills'             : 'スキルの上限15件に達しました。',
  'skills_library_title'                : '保存済みスキル',
  'skills_library_hint'                 : 'チェックしたスキルがこのCVに含まれます。選択は自動的に保存されます。',
  'skills_nav_next'                     : '追加情報へ進む',
  'skills_wina_header_icon_bar'         : 'ヘッダーアイコンバー',
  'skills_wina_on'                      : 'ON',
  'skills_wina_off'                     : 'OFF',
  'skills_wina_bar_on_sub'              : 'CVヘッダーにカラーアイコンサークルが表示されます。',
  'skills_wina_bar_off_sub'             : 'アイコン行を非表示 — 連絡先情報のスペースを確保。',
  'skills_wina_palette_hint'            : 'アイコンはパレット順にカラーサークルとして表示されます。',
  'skills_wina_preview_label'           : 'プレビュー',
  'skills_wina_disabled_hint'           : '上のアイコンバーを有効にすると、CVヘッダーに表示するアイコンを選択できます。',
  'skills_sheet_title_add'              : 'スキルを追加',
  'skills_sheet_title_edit'             : 'スキルを編集',
  'skills_sheet_field_name'             : 'スキル名 *',
  'skills_sheet_hint_short'             : '例：Flutter、デザイン',
  'skills_sheet_hint_long'              : '例：Flutter、プロジェクトマネジメント',
  'skills_sheet_validator_max'          : '最大{n}文字',
  'skills_sheet_proficiency'            : '習熟度',
  'skills_sheet_beginner'               : '初心者',
  'skills_sheet_expert'                 : 'エキスパート',
  'skills_sheet_btn_save'               : 'スキルを保存',
  'skills_sheet_btn_update'             : 'スキルを更新',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : '個人推薦者',
  'refs_subtitle'                       : 'あなたを個人的に推薦できる方',
  'refs_add_btn'                        : '新しい個人推薦者を追加',
  'refs_snack_max_selected'             : 'CVに選択できる推薦者は最大4件です。',
  'refs_snack_max_saved'                : '保存済み推薦者の上限10件に達しました。',
  'refs_library_title'                  : '保存済み推薦者',
  'refs_library_hint'                   : 'チェックした推薦者がこのCVに含まれます。1CV最大4件。選択は自動的に保存されます。',
  'refs_nav_next'                       : 'カスタマイズへ進む',
  'refs_sheet_title_add'                : '個人推薦者を追加',
  'refs_sheet_title_edit'               : '個人推薦者を編集',
  'refs_sheet_sub_add'                  : '採用担当者にあなたを個人的に推薦できる方。',
  'refs_sheet_sub_edit'                 : '以下でこの推薦者の詳細を更新してください。',
  'refs_sheet_field_name'               : '氏名 *',
  'refs_sheet_field_title'              : '職種 *',
  'refs_sheet_field_company'            : '会社（任意）',
  'refs_sheet_field_email'              : 'メールアドレス *',
  'refs_sheet_field_phone'              : '電話番号 *',
  'refs_sheet_hint_name'                : '例：田中 一郎',
  'refs_sheet_hint_title'               : '例：エンジニアリングマネージャー',
  'refs_sheet_hint_company'             : '例：株式会社アクメ',
  'refs_sheet_hint_email'               : '例：taro@acme.com',
  'refs_sheet_hint_phone'               : '例：090-1234-5678',
  'refs_sheet_validator_email'          : '有効なメールアドレスを入力してください',
  'refs_sheet_btn_save'                 : '個人推薦者を保存',
  'refs_sheet_btn_update'               : '個人推薦者を更新',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : '職歴',
  'exp_subtitle'                        : '職務経歴を追加しましょう',
  'exp_banner_info'                     : '1つの職務につき最大{n}件の担当業務がCVに表示されます。3〜6件の職歴が1〜2ページに収まります。',
  'exp_add_btn'                         : '新しい職歴を追加',
  'exp_snack_max_selected'              : 'CVに選択できる職歴は最大8件です。',
  'exp_snack_max_saved'                 : '保存済み職歴の上限12件に達しました。',
  'exp_library_title'                   : '保存済み職歴',
  'exp_library_hint'                    : 'チェックした項目がこのCVのみに含まれます。他のCVは独立した選択を保持します。',
  'exp_nav_next'                        : '学歴へ進む',
  'exp_empty_message'                   : 'まだ職歴が追加されていません',
  'exp_empty_sub'                       : '上をタップして最初の職歴を追加してください',
  'exp_card_resp_singular'              : '件の担当業務',
  'exp_card_resp_plural'                : '件の担当業務',
  'exp_card_resp_tooltip'               : '最初の8件の担当業務のみCVに表示されます',
  'exp_sheet_title_add'                 : '職歴を追加',
  'exp_sheet_title_edit'                : '職歴を編集',
  'exp_sheet_field_job_title'           : '職種 *',
  'exp_sheet_field_company'             : '会社名 *',
  'exp_sheet_field_location'            : '勤務地',
  'exp_sheet_section_responsibilities'  : '主な担当業務',
  'exp_sheet_resp_hint_info'            : '最大8件の箇条書き · 各200文字以内',
  'exp_sheet_resp_label'                : '担当業務 {n}',
  'exp_sheet_resp_hint'                 : '例：5名のエンジニアチームをリード',
  'exp_sheet_resp_add_btn'              : '担当業務を追加',
  'exp_sheet_resp_max_info'             : '担当業務の上限{n}件に達しました',
  'exp_sheet_resp_validator_max'        : '最大200文字',
  'exp_sheet_hint_job_title'            : '例：シニアデベロッパー',
  'exp_sheet_hint_location'             : '例：東京都',
  'exp_sheet_btn_save'                  : '職歴を保存',
  'exp_sheet_btn_update'                : '変更を保存',
  'exp_date_present'                    : '現在 / 現職',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : '学歴',
  'edu_subtitle'                        : '学歴情報を追加しましょう',
  'edu_add_btn'                         : '新しい学歴を追加',
  'edu_snack_max_selected'              : 'CVに選択できる学歴は最大8件です。',
  'edu_snack_max_saved'                 : '保存済み学歴の上限12件に達しました。',
  'edu_library_title'                   : '保存済み学歴',
  'edu_library_hint'                    : 'チェックした項目がこのCVに含まれます。選択は自動的に保存されます。',
  'edu_nav_next'                        : 'スキルへ進む',
  'edu_empty_message'                   : 'まだ学歴が追加されていません',
  'edu_empty_sub'                       : '上をタップして学歴を追加してください',
  'edu_card_bullet_singular'            : '件の箇条書き',
  'edu_card_bullet_plural'              : '件の箇条書き',
  'edu_sheet_title_add'                 : '学歴を追加',
  'edu_sheet_title_edit'                : '学歴を編集',
  'edu_sheet_field_degree'              : '学位 / 資格 *',
  'edu_sheet_field_institution'         : '学校名 *',
  'edu_sheet_section_key_points'        : '重要事項',
  'edu_sheet_key_points_hint_info'      : '任意 · 1箇条書き · 最大100文字',
  'edu_sheet_point_label'               : 'ポイント {n}',
  'edu_sheet_point_add_btn'             : '箇条書きを追加',
  'edu_sheet_point_max_info'            : '箇条書きの上限{n}件に達しました',
  'edu_sheet_point_validator_max'       : '最大{n}文字',
  'edu_sheet_hint_degree'               : '例：情報科学学士',
  'edu_sheet_hint_institution'          : '例：東京大学',
  'edu_sheet_hint_bullet'               : '例：首席卒業',
  'edu_sheet_btn_save'                  : '学歴を保存',
  'edu_sheet_btn_update'                : '変更を保存',
  'edu_date_present'                    : '現在 / 在学中',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : '追加情報',
  'additional_subtitle'                 : '資格、語学力など',
  'additional_cert_section_title'       : '資格・認定',
  'additional_cert_counter'             : '{sel}/{total}件選択中 · 最大{max}件',
  'additional_cert_hide'                : '非表示',
  'additional_cert_show'                : '表示',
  'additional_cert_add_btn'             : '追加',
  'additional_cert_snack_max'           : '資格・認定の上限{n}件に達しました。',
  'additional_cert_hint'                : 'チェックした項目がこのCVに含まれます。選択は自動的に保存されます。',
  'additional_cert_empty'               : 'まだ資格・認定が追加されていません',
  'additional_lang_section_title'       : '語学',
  'additional_lang_add_hint'            : '例：スペイン語',
  'additional_lang_snack_max'           : '語学の上限{n}件に達しました。',
  'additional_lang_empty'               : 'まだ語学が追加されていません',
  'additional_hobby_section_title'      : '趣味・興味',
  'additional_hobby_add_hint'           : '例：写真撮影',
  'additional_hobby_snack_max'          : '趣味の上限{n}件に達しました。',
  'additional_hobby_empty'              : 'まだ趣味が追加されていません',
  'additional_section_hint'             : 'チェックした項目がこのCVに含まれます。選択は自動的に保存されます。',
  'additional_nav_next'                 : '推薦者へ進む',
  'cert_sheet_title_add'                : '資格・認定を追加',
  'cert_sheet_title_edit'               : '資格・認定を編集',
  'cert_sheet_sub'                      : '資格、認定証、または職業上の認定情報を追加してください。',
  'cert_sheet_field_name'               : '資格・認定名 *',
  'cert_sheet_field_issued_by'          : '発行機関（任意）',
  'cert_sheet_field_short_desc'         : '短い説明（任意）',
  'cert_sheet_hint_name'                : '例：AWSソリューションアーキテクト',
  'cert_sheet_hint_issued_by'           : '例：Amazon Web Services',
  'cert_sheet_hint_short_desc'          : '例：2024年取得',
  'cert_sheet_btn_save'                 : '資格・認定を保存',
  'cert_sheet_btn_update'               : '資格・認定を更新',
  'simple_sheet_title_add_language'     : '語学を追加',
  'simple_sheet_title_edit_language'    : '語学を編集',
  'simple_sheet_title_add_hobby'        : '趣味を追加',
  'simple_sheet_title_edit_hobby'       : '趣味を編集',
  'simple_sheet_btn_save'               : '保存',
  'simple_sheet_btn_update'             : '更新',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : '連絡先',
  'pdf_section_about_me'                : '自己紹介',
  'pdf_section_summary'                 : '概要',
  'pdf_section_summary_short'           : '概要',
  'pdf_section_profile'                 : 'プロフィール',
  'pdf_section_experience'              : '職歴',
  'pdf_section_experience_short'        : '職歴',
  'pdf_section_education'               : '学歴',
  'pdf_section_skills'                  : 'スキル',
  'pdf_section_languages'               : '語学',
  'pdf_label_email'                     : 'メール',
  'pdf_label_phone'                     : '電話',
  'pdf_label_location'                  : '所在地',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CVの上限に達しました',
  'limit_dialog_body'                   : '最大30件のCVに達しました。新しいCVを作成する前に既存のCVを削除してください。',
  'limit_dialog_go_to_my_cvs'           : 'マイCVへ',
  'limit_dialog_cancel'                 : 'キャンセル',
  'refs_count_summary'                  : '{checked}/{maxChecked}件選択中 · {saved}/{maxSaved}件保存済み',
  'refs_selected_badge'                 : '{n}件選択中',
  'refs_empty_message'                  : 'まだ推薦者が保存されていません',
  'refs_empty_sub'                      : '上をタップして個人推薦者を追加してください',
};