// lib/language_keys/lang_pt_portuguese.dart
//
// Portuguese (Portugal) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> ptPortuguese = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nenhum idioma encontrado',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Saltar',
  'onboarding_next'                     : 'Seguinte',
  'onboarding_get_started'              : 'Começar',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Bem-vindo',
  'ob1_title'                           : 'Crie um CV Que\nAbre Portas',
  'ob1_body'                            : 'Destaque-se entre centenas de candidatos. Crie um CV profissional e vencedor em minutos — sem necessidade de conhecimentos de design.',
  'ob1_pill_label'                      : 'Criador de CV Profissional',
  'ob1_chip_templates'                  : '24+ Modelos',
  'ob1_chip_pdf'                        : 'Exportar PDF',
  'ob1_chip_free'                       : 'Gratuito',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Modelos',
  'ob2_title'                           : 'Cada Setor.\nCada Ambição.',
  'ob2_body'                            : 'De layouts para sala de reuniões a designs criativos arrojados — um modelo que conta a sua história.',
  'ob2_tap_hint'                        : 'Toque em qualquer modelo para pré-visualizar',
  'ob2_tpl_executive'                   : 'Executivo',
  'ob2_tpl_vibrant'                     : 'Vibrante',
  'ob2_tpl_nordic'                      : 'Nórdico',
  'ob2_tpl_tech_dark'                   : 'Tech Escuro',
  'ob2_tpl_luxury'                      : 'Luxo',
  'ob2_tag_corporate'                   : 'Corporativo',
  'ob2_tag_creative'                    : 'Criativo',
  'ob2_tag_minimal'                     : 'Minimalista',
  'ob2_tag_modern'                      : 'Moderno',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Layout Inteligente',
  'ob3_title'                           : 'O Seu CV.\nOrganizado na Perfeição.',
  'ob3_body'                            : 'O Layout Inteligente reorganiza as suas secções para o máximo impacto — colocando o conteúdo mais forte onde os recrutadores olham primeiro.',
  'ob3_badge_smart_layout'              : 'Layout Inteligente',
  'ob3_badge_cv_ready'                  : 'CV Pronto!',
  'ob3_step1_label'                     : 'Escolha um Modelo',
  'ob3_step1_desc'                      : 'Escolha entre 24+ designs fantásticos.',
  'ob3_step2_label'                     : 'Preencha os Seus Dados',
  'ob3_step2_desc'                      : 'Campos guiados para todas as secções.',
  'ob3_step3_label'                     : 'Layout Inteligente',
  'ob3_step3_desc'                      : 'Um toque reorganiza o seu CV na perfeição.',
  'ob3_step4_label'                     : 'Exportar como PDF',
  'ob3_step4_desc'                      : 'PDF perfeito pronto para enviar.',
  'ob3_section_work'                    : 'Experiência Profissional',
  'ob3_section_education'               : 'Educação',
  'ob3_section_skills'                  : 'Competências',
  'ob3_section_references'              : 'Referências',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Pronto para Começar',
  'ob4_title'                           : 'Porquê os Melhores Candidatos\nEscolhem o CV Builder',
  'ob4_visual_headline'                 : 'Está Pronto!',
  'ob4_visual_subline'                  : 'Tudo o que precisa para conseguir o emprego.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Modelos',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'CVs Máx.',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Exportar',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privado',
  'ob4_hl1_title'                       : 'Privado e Seguro',
  'ob4_hl1_sub'                         : 'Os dados ficam no seu dispositivo.',
  'ob4_hl2_title'                       : 'Gravação Automática',
  'ob4_hl2_sub'                         : 'Cada tecla guardada instantaneamente.',
  'ob4_hl3_title'                       : 'Até 30 CVs',
  'ob4_hl3_sub'                         : 'CV único para cada vaga.',
  'ob4_hl4_title'                       : 'Partilha com Um Toque',
  'ob4_hl4_sub'                         : 'Envie o PDF sem sair da aplicação.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Destaque-se na multidão',
  'home_hero_title'                     : 'Crie o Seu\nCV Profissional',
  'home_hero_sub'                       : 'Crie um currículo impressionante\nem minutos',
  'home_hero_cta'                       : 'Começar a Criar',
  'home_premium_soon'                   : 'Upgrade para Pro em breve!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Mais Recente',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Última Edição',
  'history_sort_by_template'            : 'Por Modelo',
  'history_sort_sheet_title'            : 'Ordenar Por',
  'history_sort_alphabetical_full'      : 'Alfabético (A–Z)',
  'history_premium_soon'                : 'Upgrade para Pro em breve!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Definições',
  'settings_section_preferences'        : 'Preferências',
  'settings_section_support'            : 'Suporte',
  'settings_section_legal'              : 'Legal',
  'settings_section_about'              : 'Sobre',
  'settings_language_tile_title'        : 'Idioma',
  'settings_dark_mode_title'            : 'Modo Escuro',
  'settings_dark_mode_on'               : 'Tema escuro ativado',
  'settings_dark_mode_off'              : 'Tema claro ativado',
  'settings_help_faq_title'             : 'Ajuda e FAQ',
  'settings_help_faq_sub'               : 'Perguntas frequentes respondidas',
  'settings_contact_support_title'      : 'Contactar Suporte',
  'settings_rate_app_title'             : 'Avaliar a Aplicação',
  'settings_rate_app_sub'               : 'Está a gostar da aplicação? Deixe uma avaliação!',
  'settings_privacy_policy_title'       : 'Política de Privacidade',
  'settings_terms_title'                : 'Termos de Serviço',
  'settings_app_version_title'          : 'Versão da Aplicação',
  'settings_email_error'                : 'Não foi possível abrir a aplicação de e-mail. Por favor, envie e-mail para cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Pré-visualização do CV',
  'preview_header_sub'                  : 'Pronto para exportar',
  'preview_generating'                  : 'A gerar o seu CV...',
  'preview_failed_title'                : 'Falha na Pré-visualização',
  'preview_failed_error'                : 'Erro: {error}',
  'preview_go_back'                     : 'Voltar',
  'preview_no_data'                     : 'Sem dados disponíveis',
  'preview_btn_print'                   : 'Imprimir',
  'preview_btn_download'                : 'Transferir e Partilhar',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Ajuda e FAQ',
  'faq_category_all'                    : 'Tudo',
  'faq_empty'                           : 'Nenhum resultado encontrado',
  'faq_contact_headline'                : 'Ainda precisa de ajuda?',
  'faq_contact_sub'                     : 'A nossa equipa está aqui para si.',
  'faq_contact_btn'                     : 'Contactar',
  'faq_email_error'                     : 'Não foi possível abrir a aplicação de e-mail. Por favor, envie e-mail para cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Primeiros Passos',
  'faq_cat_templates'                   : 'Modelos',
  'faq_cat_editing'                     : 'Edição',
  'faq_cat_exporting'                   : 'Exportação',
  'faq_cat_data_privacy'                : 'Dados e Privacidade',
  'faq_cat_troubleshooting'             : 'Resolução de Problemas',
  'faq_q1'  : 'Como crio o meu primeiro CV?',
  'faq_a1'  : 'Toque no botão "+" no ecrã inicial para criar um novo CV. Escolha um modelo que se adapte ao seu estilo e preencha os seus dados pessoais, experiência profissional, educação e competências passo a passo. O seu progresso é guardado automaticamente.',
  'faq_q2'  : 'Posso criar mais do que um CV?',
  'faq_a2'  : 'Sim! Pode criar múltiplos CVs para diferentes funções ou setores. Cada CV é guardado separadamente, para que possa adaptá-los a candidaturas específicas.',
  'faq_q3'  : 'Como altero o modelo do meu CV?',
  'faq_a3'  : 'Abra o seu CV, toque no ícone de modelo no topo do ecrã e navegue pelos modelos disponíveis. Toque em qualquer modelo para o pré-visualizar com o conteúdo existente. Confirme para aplicar.',
  'faq_q4'  : 'Existem modelos gratuitos e premium?',
  'faq_a4'  : 'Sim. Uma seleção de modelos profissionais está disponível gratuitamente. Modelos premium com designs avançados e paletas de cores estão disponíveis através de uma compra única ou subscrição.',
  'faq_q5'  : 'Como adiciono ou removo secções?',
  'faq_a5'  : 'No editor de CV, faça scroll até ao fundo do ecrã e toque em "Adicionar Secção" para incluir extras como Idiomas, Certificações ou Voluntariado. Para remover uma secção, toque no cabeçalho da secção e selecione "Remover."',
  'faq_q6'  : 'Como reordeno as secções?',
  'faq_a6'  : 'Prima longamente a alça de arrastar (≡) junto ao cabeçalho de qualquer secção e arraste-a para a posição pretendida. As alterações são guardadas automaticamente.',
  'faq_q7'  : 'Como exporto o meu CV como PDF?',
  'faq_a7'  : 'Abra o seu CV e toque no botão de exportar (ícone de partilha) no canto superior direito. Selecione "Exportar como PDF." Pode depois guardá-lo no seu dispositivo, partilhá-lo por e-mail, WhatsApp, ou carregá-lo diretamente para portais de emprego.',
  'faq_q8'  : 'Que formatos de ficheiro são suportados?',
  'faq_a8'  : 'Atualmente a aplicação suporta a exportação do seu CV como PDF de alta qualidade. Formatos adicionais poderão ser adicionados em futuras atualizações.',
  'faq_q9'  : 'Onde são armazenados os dados do meu CV?',
  'faq_a9'  : 'Todos os dados do seu CV são armazenados localmente no seu dispositivo. Não carregamos as suas informações pessoais para os nossos servidores. Isto significa que os seus dados permanecem privados e acessíveis offline.',
  'faq_q10' : 'Como faço cópia de segurança dos meus CVs?',
  'faq_a10' : 'Os seus CVs são incluídos na cópia de segurança padrão do seu dispositivo (Google Drive no Android, iCloud no iOS) se tiver a cópia de segurança ativada nas definições do dispositivo. Também pode exportar CVs individuais como PDFs para manter uma cópia.',
  'faq_q11' : 'A aplicação está lenta. O que devo fazer?',
  'faq_a11' : 'Tente fechar e reabrir a aplicação. Se o problema persistir, reinicie o seu dispositivo. Certifique-se de que tem a versão mais recente da aplicação instalada na Play Store / App Store.',
  'faq_q12' : 'O meu CV não está a exportar corretamente. O que devo fazer?',
  'faq_a12' : 'Certifique-se de que tem espaço de armazenamento suficiente no seu dispositivo. Tente reduzir imagens grandes no seu CV. Se o problema continuar, por favor contacte a nossa equipa de suporte.',
  'faq_q13' : 'Esqueci-me de guardar — perdi o meu trabalho?',
  'faq_a13' : 'De modo algum! A aplicação guarda o seu progresso continuamente enquanto edita.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'A sua carreira, aperfeiçoada',
  'header_tooltip_back'                 : 'Voltar',
  'header_tooltip_my_cvs'               : 'Os Meus CVs',
  'header_tooltip_settings'             : 'Definições',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Os Meus CVs',
  'saved_count_single'                  : '{n} documento',
  'saved_count_plural'                  : '{n} documentos',
  'saved_limit_reached'                 : 'Limite atingido',
  'saved_footer_count'                  : '{n} / 30 CVs',
  'saved_filter_all'                    : 'Todos',
  'saved_filter_draft'                  : 'Rascunho',
  'saved_filter_complete'               : 'Completo',
  'saved_status_complete'               : 'Completo',
  'saved_status_saved'                  : 'Guardado',
  'saved_status_draft'                  : 'Rascunho',
  'saved_empty_title'                   : 'Ainda não tem CVs',
  'saved_empty_sub'                     : 'Comece a criar o seu primeiro CV acima',
  'saved_search_empty_title'            : 'Nenhum resultado encontrado',
  'saved_search_empty_sub'              : 'Tente um termo de pesquisa diferente',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Esquema de Cores',
  'custom_font_settings_title'          : 'Definições de Tipo de Letra',
  'custom_font_family_label'            : 'Família de Tipo de Letra',
  'custom_font_size_label'              : 'Tamanho do Tipo de Letra: ',
  'custom_current_template_title'       : 'Modelo Atual',
  'custom_change_template_btn'          : 'Alterar Modelo',
  'custom_tpl_modern'                   : 'Moderno',
  'custom_tpl_classic'                  : 'Clássico',
  'custom_tpl_professional'             : 'Profissional',
  'custom_tpl_creative'                 : 'Criativo',
  'custom_tpl_minimal'                  : 'Minimalista',
  'custom_tpl_modern_desc'              : 'Design limpo e contemporâneo',
  'custom_tpl_classic_desc'             : 'Layout profissional tradicional',
  'custom_tpl_professional_desc'        : 'Modelo orientado para negócios',
  'custom_tpl_creative_desc'            : 'Destaque-se com um design único',
  'custom_tpl_minimal_desc'             : 'Estilo simples e elegante',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Escolher Modelo',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executivo',
  'tpl_nordic_name'                     : 'Nórdico',
  'tpl_vibrant_name'                    : 'Vibrante',
  'tpl_tech_dark_name'                  : 'Tech Escuro',
  'tpl_luxury_name'                     : 'Luxo',
  'tpl_executive_tag'                   : 'Mais Popular',
  'tpl_nordic_tag'                      : 'Limpo',
  'tpl_vibrant_tag'                     : 'Criativo',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Arrojado e autoritário para funções sénior',
  'tpl_nordic_desc'                     : 'Clareza minimalista de confiança das melhores empresas',
  'tpl_vibrant_desc'                    : 'Destaque-se com energia e cor',
  'tpl_tech_dark_desc'                  : 'Estética terminal para programadores',
  'tpl_luxury_desc'                     : 'Prestígio dourado sobre fundo preto',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Modelo',
  'detail_step_personal'                : 'Pessoal',
  'detail_step_experience'              : 'Experiência',
  'detail_step_education'               : 'Educação',
  'detail_step_skills'                  : 'Competências',
  'detail_step_additional'              : 'Adicional',
  'detail_step_references'              : 'Referências',
  'detail_step_customize'               : 'Personalizar',
  'detail_banner_heading'               : 'Quase lá!',
  'detail_banner_btn'                   : 'Continuar',
  'detail_banner_completion_label'      : 'Conclusão',
  'detail_stat_created_label'           : 'Criado',
  'detail_stat_steps_label'             : 'Passos concluídos',
  'detail_section_template_style'       : 'Estilo do Modelo',
  'detail_section_steps'                : 'Passos',
  'detail_steps_counter'                : '{done} de {total} concluídos',
  'detail_step_sub'                     : 'Passo {n} de {total}',
  'detail_section_activity'             : 'Atividade',
  'detail_activity_created'             : 'Criado',
  'detail_activity_last_edited'         : 'Última Edição',
  'detail_activity_template'            : 'Modelo',
  'detail_btn_continue_editing'         : 'Continuar a Editar',
  'detail_btn_edit_cv'                  : 'Editar CV',
  'detail_option_rename'                : 'Renomear CV',
  'detail_option_delete'                : 'Eliminar CV',
  'detail_rename_title'                 : 'Renomear CV',
  'detail_rename_hint'                  : 'ex. CV Engenheiro de Software',
  'detail_rename_error_empty'           : 'O nome não pode estar vazio',
  'detail_rename_btn_cancel'            : 'Cancelar',
  'detail_rename_btn_save'              : 'Guardar',
  'detail_rename_snackbar'              : 'Renomeado para "{name}"',
  'detail_delete_title'                 : 'Eliminar CV?',
  'detail_delete_body'                  : 'Isto irá eliminar permanentemente "{name}". Esta ação não pode ser anulada.',
  'detail_delete_btn_cancel'            : 'Cancelar',
  'detail_delete_btn_confirm'           : 'Eliminar',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Concluído',
  'detail_check_tile_incomplete'        : 'Ainda não preenchido',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Escolha o Seu Modelo',
  'chooser_subtitle'                    : 'Deslize para navegar  ·  Toque para selecionar  ·  Prima para pré-visualizar',
  'chooser_card_hold_hint'              : 'Prima para pré-visualizar',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Selecionado',
  'chooser_modal_heading'               : 'Dê um Nome ao Seu CV',
  'chooser_modal_sub'                   : 'Dê-lhe um nome para o encontrar facilmente em Os Meus CVs e Histórico.',
  'chooser_modal_field_label'           : 'Nome do CV',
  'chooser_modal_save_btn'              : 'Guardar e Começar a Criar',
  'chooser_modal_divider'               : 'ou continuar um CV existente',
  'chooser_nav_selected_sub'            : 'Modelo selecionado',
  'chooser_nav_cta'                     : 'Guardar e Continuar',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Número Máximo de Entradas Atingido',
  'editor_show_hide'                    : 'Mostrar/Ocultar',
  'editor_editing_badge'                : 'A Editar',
  'editor_field_required'               : 'Obrigatório',
  'editor_tooltip_edit'                 : 'Editar',
  'editor_tooltip_delete'               : 'Eliminar',
  'editor_date_start'                   : 'Data de Início *',
  'editor_date_end'                     : 'Data de Fim *',
  'editor_date_tap_hint'                : 'Toque para selecionar',
  'editor_date_dialog_title'            : 'Selecionar Mês e Ano',
  'editor_date_confirm'                 : 'Confirmar',
  'editor_panel_hide'                   : 'Ocultar',
  'editor_panel_show'                   : 'Mostrar',
  'editor_validator_max_chars'          : 'Máx. {n} caracteres',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Criar o Seu CV',
  'editor_header_step_sub'              : 'Passo {current} de {total} · {label}',
  'editor_step_template'                : 'Modelo',
  'editor_step_personal'                : 'Pessoal',
  'editor_step_experience'              : 'Experiência',
  'editor_step_education'               : 'Educação',
  'editor_step_skills'                  : 'Competências',
  'editor_step_additional'              : 'Adicional',
  'editor_step_references'              : 'Referências',
  'editor_step_customize'               : 'Personalizar',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personalizar',
  'customize_subtitle'                  : 'Torne o seu CV único',
  'customize_smart_layout_btn'          : 'Layout Inteligente',
  'customize_back_to_top'               : 'Voltar ao Início',
  'customize_done_title'                : 'Está tudo pronto!',
  'customize_done_sub'                  : 'Toque em Pré-visualizar CV abaixo para ver o seu CV concluído',
  'customize_preview_btn'               : 'Pré-visualizar CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Esquema de Cores',
  'color_black'                         : 'Preto',
  'color_blue'                          : 'Azul',
  'color_nordic_blue'                   : 'Azul Nórdico',
  'color_indigo'                        : 'Índigo',
  'color_teal'                          : 'Verde-azulado',
  'color_green'                         : 'Verde',
  'color_purple'                        : 'Roxo',
  'color_orange'                        : 'Laranja',
  'color_red'                           : 'Vermelho',
  'color_executive_gold'                : 'Dourado Executivo',
  'color_vibrant_coral'                 : 'Coral Vibrante',
  'color_white'                         : 'Branco',
  'color_white_bg'                      : 'Fundo Branco',
  'color_maroon'                        : 'Bordô',
  'color_brutalist_yellow'              : 'Amarelo Brutalista',
  'color_neon_blue'                     : 'Azul Néon',
  'color_blueprint_navy'                : 'Azul Marinho Técnico',
  'color_light_grey'                    : 'Cinzento Claro',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Família de Tipo de Letra',
  'customize_font_picker_title'         : 'Escolher Tipo de Letra',
  'customize_font_picker_sub'           : 'Cada tipo de letra é pré-visualizado no seu próprio estilo',
  'customize_font_preview_sample'       : 'A raposa marrom veloz',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Tamanho do Tipo de Letra',
  'customize_font_size_label'           : 'Tamanho do Texto',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Tamanho da Imagem',
  'customize_image_size_label'          : 'Tamanho da Imagem',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Pré-visualização em Direto',
  'preview_page_count_singular'         : '1 página',
  'preview_page_count_plural'           : '{n} páginas',
  'preview_page_of'                     : 'Página {page} de {total}',
  'preview_live_hint'                   : 'As alterações aplicam-se instantaneamente',
  'preview_template_unregistered'       : 'Ainda não registado em customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'A preparar o seu CV…',
  'preview_bar_print'                   : 'Imprimir',
  'preview_bar_save_pdf'                : 'Guardar como PDF',
  'preview_bar_share'                   : 'Partilhar',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Pré-visualização do CV',
  'preview_screen_sub'                  : '{n} {unit} · exatamente como impresso',
  'preview_page_singular'               : 'página',
  'preview_page_plural'                 : 'páginas',
  'preview_pdf_filename'                : 'O_Meu_CV',
  'preview_share_subject'               : 'O Meu CV',
  'preview_snack_print_failed'          : 'Falha ao imprimir: {e}',
  'preview_snack_saved'                 : 'CV guardado em Transferências ✓',
  'preview_snack_export_failed'         : 'Falha ao exportar: {e}',
  'preview_snack_share_failed'          : 'Falha ao partilhar: {e}',
  'preview_template_not_registered'     : 'Modelo não registado',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Fechar pré-visualização',
  'preview_modal_hint_photo'            : 'Suporta foto de perfil  ·  Toque num cartão para selecionar',
  'preview_modal_hint_no_photo'         : 'Toque num cartão de modelo para o selecionar',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'O Meu CV',
  'time_just_now'                       : 'Agora mesmo',
  'time_minutes_ago'                    : 'Há {n}m',
  'time_hours_ago'                      : 'Há {n}h',
  'time_yesterday'                      : 'Ontem',
  'time_days_ago'                       : 'Há {n} dias',
  'time_one_week_ago'                   : 'Há 1 semana',
  'time_weeks_ago'                      : 'Há {n} semanas',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegante',
  'tpl_tag_classic'                     : 'Clássico',
  'tpl_tag_minimal'                     : 'Minimalista',
  'tpl_tag_creative'                    : 'Criativo',
  'tpl_tag_bold'                        : 'Arrojado',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradiente',
  'tpl_gradient_desc'                   : 'Cartões com gradiente de verde-azulado a violeta',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Estilo revista em vermelho e creme',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Suave',
  'tpl_pastel_soft_desc'                : 'Barra lateral lavanda, cartões suaves',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalista',
  'tpl_brutalist_desc'                  : 'Grelha crua, bordas marcadas e amarelo',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Esmeralda',
  'tpl_emerald_desc'                    : 'Verde floresta com linha do tempo',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infográfico',
  'tpl_infographic_desc'                : 'Tela escura com gráficos de anel',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Arte Déco',
  'tpl_art_deco_desc'                   : 'Luxo geométrico dourado dos anos 1920',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Escuro',
  'tpl_wina_dark_desc'                  : 'Infográfico escuro com anéis',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Laranja',
  'tpl_rio_orange_desc'                 : 'Barra lateral escura com toque laranja',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Verão',
  'tpl_summer_desc'                     : 'Minimalista limpo, tons cinzentos suaves',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Tons elegantes em bege quente',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Clássico a preto e branco marcante',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Layout clássico compatível com ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Escuro',
  'tpl_tony_dark_desc'                  : 'Estilo infográfico laranja escuro',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Moda',
  'tpl_fashion_desc'                    : 'Desenho técnico em grelha',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arquivista',
  'tpl_archivist_desc'                  : 'Layout clássico de duas colunas com etiquetas',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomata',
  'tpl_diplomat_desc'                   : 'Cabeçalhos sombreados com marcadores em diamante',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Cabeçalhos centrados, empresas em destaque',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nome arrojado, pontos de linha do tempo e conquistas',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informação Pessoal',
  'personal_subtitle'                   : 'Diga aos empregadores quem é',
  'personal_profile_counter'            : '{n}/{max} perfis',
  'personal_info_banner'                : 'Guarde até 5 perfis e selecione um por CV. A sua seleção é lembrada para cada CV separadamente.',
  'personal_snack_max'                  : 'Número máximo de {n} perfis atingido.',
  'personal_add_btn'                    : 'Adicionar Novo Perfil',
  'personal_library_title'              : 'Perfis Guardados',
  'personal_selected_one'               : '1 selecionado',
  'personal_selected_none'              : 'nenhum selecionado',
  'personal_library_hint'               : 'Toque num cartão para o selecionar apenas para este CV. Os outros CVs mantêm as suas próprias seleções independentes.',
  'personal_empty_message'              : 'Ainda não há perfis guardados',
  'personal_empty_sub'                  : 'Toque acima para adicionar as suas informações pessoais',
  'personal_nav_next'                   : 'Guardar e Continuar',
  'personal_card_active_badge'          : 'Ativo para este CV',
  'personal_sheet_title_add'            : 'Novo Perfil',
  'personal_sheet_title_edit'           : 'Editar Perfil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTA',
  'personal_sheet_brutalist_banner'     : 'O modelo Brutalista tem campos de contacto compactos. Valores mais curtos (ex. só cidade) ficam melhores.',
  'personal_section_photo'              : 'Foto de Perfil',
  'personal_section_basic'              : 'Dados Básicos',
  'personal_section_contact'            : 'Contacto',
  'personal_section_online'             : 'Presença Online',
  'personal_section_summary'            : 'Resumo Profissional',
  'personal_field_first_name'           : 'Primeiro Nome *',
  'personal_field_last_name'            : 'Apelido',
  'personal_field_job_title'            : 'Título Profissional *',
  'personal_field_email'                : 'Endereço de E-mail *',
  'personal_field_phone'                : 'Número de Telefone *',
  'personal_field_location'             : 'Localização',
  'personal_field_location_brut'        : 'Localização (apenas cidade)',
  'personal_field_website'              : 'Website / Portfólio',
  'personal_field_linkedin'             : 'URL do LinkedIn',
  'personal_hint_first_name'            : 'ex. Ana',
  'personal_hint_last_name'             : 'ex. Silva',
  'personal_hint_job_title'             : 'ex. Engenheiro Sénior',
  'personal_hint_email'                 : 'ex. ana@exemplo.com',
  'personal_hint_phone'                 : 'ex. +351 912 345 678',
  'personal_hint_location'              : 'ex. Lisboa, Portugal',
  'personal_hint_location_brut'         : 'ex. Lisboa, PT',
  'personal_hint_website'               : 'ex. github.com/anasilva',
  'personal_hint_website_brut'          : 'ex. github.com/ana',
  'personal_hint_linkedin'              : 'ex. linkedin.com/in/anasilva',
  'personal_hint_linkedin_brut'         : 'ex. linkedin.com/in/ana',
  'personal_summary_hint_label'         : 'Seja conciso — isto aparece no topo do seu CV.',
  'personal_hint_summary'               : 'Um breve resumo de 2 a 3 frases sobre o seu percurso e objetivos...',
  'personal_validator_email'            : 'Introduza um e-mail válido',
  'personal_field_char_limit_tooltip'   : 'Limite de caracteres atingido',
  'personal_sheet_btn_save'             : 'Guardar Perfil',
  'personal_sheet_btn_update'           : 'Guardar Alterações',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Escolher Foto',
  'photo_option_gallery'                : 'Escolher da Galeria',
  'photo_option_camera'                 : 'Tirar uma Foto',
  'photo_option_reposition'             : 'Reposicionar Foto',
  'photo_option_remove'                 : 'Remover Foto',
  'photo_status_added'                  : 'Foto adicionada ✓',
  'photo_status_empty'                  : 'Adicione uma foto profissional',
  'photo_chip_gallery'                  : 'Galeria',
  'photo_chip_camera'                   : 'Câmara',
  'photo_chip_reposition'               : 'Reposicionar',
  'photo_reposition_title'              : 'Reposicionar Foto',
  'photo_reposition_sub'                : 'Arraste a foto para ajustar a posição',
  'photo_reposition_reset'              : 'Repor ao centro',
  'photo_reposition_apply'              : 'Aplicar',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Competências',
  'skills_subtitle'                     : 'Destaque as suas principais capacidades',
  'skills_add_btn'                      : 'Adicionar Nova Competência',
  'skills_snack_max_icons'              : 'Máximo de 10 ícones selecionados.',
  'skills_snack_max_skills'             : 'Máximo de 15 competências atingido.',
  'skills_library_title'                : 'Competências Guardadas',
  'skills_library_hint'                 : 'As competências marcadas são incluídas neste CV. As suas seleções são guardadas automaticamente.',
  'skills_nav_next'                     : 'Continuar para Adicional',
  'skills_wina_header_icon_bar'         : 'Barra de Ícones do Cabeçalho',
  'skills_wina_on'                      : 'ATIVO',
  'skills_wina_off'                     : 'INATIVO',
  'skills_wina_bar_on_sub'              : 'Círculos de ícones coloridos mostrados no cabeçalho do CV.',
  'skills_wina_bar_off_sub'             : 'Linha de ícones oculta — mais espaço para informações de contacto.',
  'skills_wina_palette_hint'            : 'Os ícones aparecem como círculos coloridos na ordem da paleta.',
  'skills_wina_preview_label'           : 'Pré-visualização',
  'skills_wina_disabled_hint'           : 'Ative a barra de ícones acima para escolher quais os ícones que aparecem no cabeçalho do CV.',
  'skills_sheet_title_add'              : 'Adicionar Competência',
  'skills_sheet_title_edit'             : 'Editar Competência',
  'skills_sheet_field_name'             : 'Nome da Competência *',
  'skills_sheet_hint_short'             : 'ex. Flutter, Design',
  'skills_sheet_hint_long'              : 'ex. Flutter, Gestão de Projetos',
  'skills_sheet_validator_max'          : 'Máx. {n} caracteres',
  'skills_sheet_proficiency'            : 'Nível de Proficiência',
  'skills_sheet_beginner'               : 'Iniciante',
  'skills_sheet_expert'                 : 'Especialista',
  'skills_sheet_btn_save'               : 'Guardar Competência',
  'skills_sheet_btn_update'             : 'Atualizar Competência',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referências Pessoais',
  'refs_subtitle'                       : 'Pessoas que podem recomendar pessoalmente',
  'refs_add_btn'                        : 'Adicionar Nova Referência Pessoal',
  'refs_snack_max_selected'             : 'Máximo de 4 referências pode ser selecionado para um CV.',
  'refs_snack_max_saved'                : 'Máximo de 10 referências guardadas atingido.',
  'refs_library_title'                  : 'Referências Guardadas',
  'refs_library_hint'                   : 'As referências marcadas são incluídas neste CV. Máx. 4 por CV. As suas seleções são guardadas automaticamente.',
  'refs_nav_next'                       : 'Continuar para Personalizar',
  'refs_sheet_title_add'                : 'Adicionar Referência Pessoal',
  'refs_sheet_title_edit'               : 'Editar Referência Pessoal',
  'refs_sheet_sub_add'                  : 'Alguém que o possa recomendar pessoalmente aos empregadores.',
  'refs_sheet_sub_edit'                 : 'Atualize os dados desta referência abaixo.',
  'refs_sheet_field_name'               : 'Nome Completo *',
  'refs_sheet_field_title'              : 'Título Profissional *',
  'refs_sheet_field_company'            : 'Empresa (opcional)',
  'refs_sheet_field_email'              : 'Endereço de E-mail *',
  'refs_sheet_field_phone'              : 'Número de Telefone *',
  'refs_sheet_hint_name'                : 'ex. João Silva',
  'refs_sheet_hint_title'               : 'ex. Gestor de Engenharia',
  'refs_sheet_hint_company'             : 'ex. Acme Corp',
  'refs_sheet_hint_email'               : 'ex. joao@acme.com',
  'refs_sheet_hint_phone'               : 'ex. +351 912 345 678',
  'refs_sheet_validator_email'          : 'Introduza um endereço de e-mail válido',
  'refs_sheet_btn_save'                 : 'Guardar Referência Pessoal',
  'refs_sheet_btn_update'               : 'Atualizar Referência Pessoal',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Experiência Profissional',
  'exp_subtitle'                        : 'Adicione o seu historial profissional',
  'exp_banner_info'                     : 'Até {n} responsabilidades por função aparecerão no CV. 3–6 funções cabem tipicamente em 1–2 páginas.',
  'exp_add_btn'                         : 'Adicionar Nova Experiência',
  'exp_snack_max_selected'              : 'Máximo de 8 experiências pode ser selecionado para um CV.',
  'exp_snack_max_saved'                 : 'Máximo de 12 experiências guardadas atingido.',
  'exp_library_title'                   : 'Experiências Guardadas',
  'exp_library_hint'                    : 'As entradas marcadas são incluídas apenas neste CV. Os outros CVs mantêm as suas próprias seleções independentes.',
  'exp_nav_next'                        : 'Continuar para Educação',
  'exp_empty_message'                   : 'Ainda não há experiência adicionada',
  'exp_empty_sub'                       : 'Toque acima para adicionar a sua primeira função',
  'exp_card_resp_singular'              : 'responsabilidade',
  'exp_card_resp_plural'                : 'responsabilidades',
  'exp_card_resp_tooltip'               : 'Apenas as primeiras 8 responsabilidades aparecerão no CV',
  'exp_sheet_title_add'                 : 'Adicionar Experiência',
  'exp_sheet_title_edit'                : 'Editar Experiência',
  'exp_sheet_field_job_title'           : 'Título Profissional *',
  'exp_sheet_field_company'             : 'Empresa *',
  'exp_sheet_field_location'            : 'Localização',
  'exp_sheet_section_responsibilities'  : 'Responsabilidades Principais',
  'exp_sheet_resp_hint_info'            : 'Máx. 8 pontos · 200 caracteres cada',
  'exp_sheet_resp_label'                : 'Responsabilidade {n}',
  'exp_sheet_resp_hint'                 : 'ex. Liderou uma equipa de 5 engenheiros',
  'exp_sheet_resp_add_btn'              : 'Adicionar Responsabilidade',
  'exp_sheet_resp_max_info'             : 'Máximo de {n} responsabilidades atingido',
  'exp_sheet_resp_validator_max'        : 'Máx. 200 caracteres',
  'exp_sheet_hint_job_title'            : 'ex. Programador Sénior',
  'exp_sheet_hint_location'             : 'ex. Lisboa, Portugal',
  'exp_sheet_btn_save'                  : 'Guardar Experiência',
  'exp_sheet_btn_update'                : 'Guardar Alterações',
  'exp_date_present'                    : 'Atual / Função Atual',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Educação',
  'edu_subtitle'                        : 'Adicione o seu percurso académico',
  'edu_add_btn'                         : 'Adicionar Nova Educação',
  'edu_snack_max_selected'              : 'Máximo de 8 entradas de educação pode ser selecionado para um CV.',
  'edu_snack_max_saved'                 : 'Máximo de 12 entradas de educação guardadas atingido.',
  'edu_library_title'                   : 'Educação Guardada',
  'edu_library_hint'                    : 'As entradas marcadas são incluídas neste CV. As suas seleções são guardadas automaticamente.',
  'edu_nav_next'                        : 'Continuar para Competências',
  'edu_empty_message'                   : 'Ainda não há educação adicionada',
  'edu_empty_sub'                       : 'Toque acima para adicionar as suas qualificações',
  'edu_card_bullet_singular'            : 'ponto',
  'edu_card_bullet_plural'              : 'pontos',
  'edu_sheet_title_add'                 : 'Adicionar Educação',
  'edu_sheet_title_edit'                : 'Editar Educação',
  'edu_sheet_field_degree'              : 'Grau / Qualificação *',
  'edu_sheet_field_institution'         : 'Instituição *',
  'edu_sheet_section_key_points'        : 'Pontos Principais',
  'edu_sheet_key_points_hint_info'      : 'Opcional · 1 ponto · máx. 100 caracteres',
  'edu_sheet_point_label'               : 'Ponto {n}',
  'edu_sheet_point_add_btn'             : 'Adicionar Ponto',
  'edu_sheet_point_max_info'            : 'Máximo de {n} pontos atingido',
  'edu_sheet_point_validator_max'       : 'Máx. {n} caracteres',
  'edu_sheet_hint_degree'               : 'ex. Licenciatura em Ciências da Computação',
  'edu_sheet_hint_institution'          : 'ex. Universidade de Lisboa',
  'edu_sheet_hint_bullet'               : 'ex. Classificação com Distinção',
  'edu_sheet_btn_save'                  : 'Guardar Educação',
  'edu_sheet_btn_update'                : 'Guardar Alterações',
  'edu_date_present'                    : 'Atual / A Estudar',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Informação Adicional',
  'additional_subtitle'                 : 'Certificações, idiomas e mais',
  'additional_cert_section_title'       : 'Certificações',
  'additional_cert_counter'             : '{sel}/{total} selecionados · máx. {max}',
  'additional_cert_hide'                : 'Ocultar',
  'additional_cert_show'                : 'Mostrar',
  'additional_cert_add_btn'             : 'Adicionar',
  'additional_cert_snack_max'           : 'Máximo de {n} entradas de certificação atingido.',
  'additional_cert_hint'                : 'As entradas marcadas são incluídas neste CV. As suas seleções são guardadas automaticamente.',
  'additional_cert_empty'               : 'Ainda não há certificações adicionadas',
  'additional_lang_section_title'       : 'Idiomas',
  'additional_lang_add_hint'            : 'ex. Espanhol',
  'additional_lang_snack_max'           : 'Máximo de {n} entradas de idioma atingido.',
  'additional_lang_empty'               : 'Ainda não há idiomas adicionados',
  'additional_hobby_section_title'      : 'Hobbies e Interesses',
  'additional_hobby_add_hint'           : 'ex. Fotografia',
  'additional_hobby_snack_max'          : 'Máximo de {n} entradas de hobby atingido.',
  'additional_hobby_empty'              : 'Ainda não há hobbies adicionados',
  'additional_section_hint'             : 'As entradas marcadas são incluídas neste CV. As suas seleções são guardadas automaticamente.',
  'additional_nav_next'                 : 'Continuar para Árbitros',
  'cert_sheet_title_add'                : 'Adicionar Certificação',
  'cert_sheet_title_edit'               : 'Editar Certificação',
  'cert_sheet_sub'                      : 'Adicione uma qualificação, certificado ou credencial profissional.',
  'cert_sheet_field_name'               : 'Nome da Certificação *',
  'cert_sheet_field_issued_by'          : 'Emitido Por (opcional)',
  'cert_sheet_field_short_desc'         : 'Descrição Breve (opcional)',
  'cert_sheet_hint_name'                : 'ex. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'ex. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'ex. Obtido em 2024',
  'cert_sheet_btn_save'                 : 'Guardar Certificação',
  'cert_sheet_btn_update'               : 'Atualizar Certificação',
  'simple_sheet_title_add_language'     : 'Adicionar Idioma',
  'simple_sheet_title_edit_language'    : 'Editar Idioma',
  'simple_sheet_title_add_hobby'        : 'Adicionar Hobby',
  'simple_sheet_title_edit_hobby'       : 'Editar Hobby',
  'simple_sheet_btn_save'               : 'Guardar',
  'simple_sheet_btn_update'             : 'Atualizar',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contacto',
  'pdf_section_about_me'                : 'Sobre Mim',
  'pdf_section_summary'                 : 'Resumo',
  'pdf_section_summary_short'           : 'Resumo',
  'pdf_section_profile'                 : 'Perfil',
  'pdf_section_experience'              : 'Experiência',
  'pdf_section_experience_short'        : 'Experiência',
  'pdf_section_education'               : 'Educação',
  'pdf_section_skills'                  : 'Competências',
  'pdf_section_languages'               : 'Idiomas',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefone',
  'pdf_label_location'                  : 'Localização',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Limite de CVs atingido',
  'limit_dialog_body'                   : 'Atingiu o máximo de 30 CVs. Por favor, elimine um CV existente antes de criar um novo.',
  'limit_dialog_go_to_my_cvs'           : 'Ir para Os Meus CVs',
  'limit_dialog_cancel'                 : 'Cancelar',
  'refs_count_summary'                  : '{checked}/{maxChecked} selecionados · {saved}/{maxSaved} guardados',
  'refs_selected_badge'                 : '{n} selecionado(s)',
  'refs_empty_message'                  : 'Ainda não há referências guardadas',
  'refs_empty_sub'                      : 'Toque acima para adicionar uma referência pessoal',
};