// lib/language_keys/lang_fi_finnish.dart
//
// Finnish (Finland) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> fiFinnish = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Kieltä ei löydy',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Ohita',
  'onboarding_next'                     : 'Seuraava',
  'onboarding_get_started'              : 'Aloita',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Tervetuloa',
  'ob1_title'                           : 'Luo CV, joka\nAvaa Ovia',
  'ob1_body'                            : 'Erottu sadoista hakijoista. Rakenna viimeistelty, työn voittava CV minuuteissa — suunnittelutaitoja ei tarvita.',
  'ob1_pill_label'                      : 'Ammatillinen CV-rakentaja',
  'ob1_chip_templates'                  : '24+ mallia',
  'ob1_chip_pdf'                        : 'PDF-vienti',
  'ob1_chip_free'                       : 'Ilmainen',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Mallit',
  'ob2_title'                           : 'Joka toimiala.\nJoka tavoite.',
  'ob2_body'                            : 'Johtokuntatason asetteluista rohkeisiin luoviin suunnitteluihin — malli, joka kertoo tarinasi.',
  'ob2_tap_hint'                        : 'Napauta mitä tahansa mallia esikatsellaksesi',
  'ob2_tpl_executive'                   : 'Johtaja',
  'ob2_tpl_vibrant'                     : 'Eloisa',
  'ob2_tpl_nordic'                      : 'Pohjoismainen',
  'ob2_tpl_tech_dark'                   : 'Tech tumma',
  'ob2_tpl_luxury'                      : 'Luksus',
  'ob2_tag_corporate'                   : 'Yritysmalli',
  'ob2_tag_creative'                    : 'Luova',
  'ob2_tag_minimal'                     : 'Minimalistinen',
  'ob2_tag_modern'                      : 'Moderni',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Älykäs asettelu',
  'ob3_title'                           : 'CV:si.\nTäydellisesti järjestetty.',
  'ob3_body'                            : 'Älykäs asettelu järjestää osiot uudelleen maksimaalista vaikutusta varten — asettaen vahvimman sisältösi sinne, missä rekrytoijat katsovat ensin.',
  'ob3_badge_smart_layout'              : 'Älykäs asettelu',
  'ob3_badge_cv_ready'                  : 'CV valmis!',
  'ob3_step1_label'                     : 'Valitse malli',
  'ob3_step1_desc'                      : 'Valitse yli 24 upeasta suunnittelusta.',
  'ob3_step2_label'                     : 'Täytä tietosi',
  'ob3_step2_desc'                      : 'Opastetut kentät kaikille osioille.',
  'ob3_step3_label'                     : 'Älykäs asettelu',
  'ob3_step3_desc'                      : 'Yksi napautus järjestää CV:si täydellisesti.',
  'ob3_step4_label'                     : 'Vie PDF:nä',
  'ob3_step4_desc'                      : 'Pikselinperfekti PDF valmiina lähetettäväksi.',
  'ob3_section_work'                    : 'Työkokemus',
  'ob3_section_education'               : 'Koulutus',
  'ob3_section_skills'                  : 'Taidot',
  'ob3_section_references'              : 'Suosittelijat',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Valmis käytettäväksi',
  'ob4_title'                           : 'Miksi huippuhakijat\nvalitsevat CV Builderin',
  'ob4_visual_headline'                 : 'Kaikki on valmista!',
  'ob4_visual_subline'                  : 'Kaikki mitä tarvitset työn saamiseen.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Mallia',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Enintään CV:tä',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Vienti',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Yksityinen',
  'ob4_hl1_title'                       : 'Yksityinen ja turvallinen',
  'ob4_hl1_sub'                         : 'Tiedot pysyvät laitteellasi.',
  'ob4_hl2_title'                       : 'Automaattinen tallennus',
  'ob4_hl2_sub'                         : 'Jokainen näppäinpainallus tallennetaan välittömästi.',
  'ob4_hl3_title'                       : 'Jopa 30 CV:tä',
  'ob4_hl3_sub'                         : 'Ainutlaatuinen CV jokaiselle tehtävälle.',
  'ob4_hl4_title'                       : 'Yhden napautuksen jakaminen',
  'ob4_hl4_sub'                         : 'Lähetä PDF poistumatta sovelluksesta.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Erottu joukosta',
  'home_hero_title'                     : 'Luo ammatillinen\nCV:si',
  'home_hero_sub'                       : 'Rakenna upea ansioluettelo\nminuuteissa',
  'home_hero_cta'                       : 'Aloita rakentaminen',
  'home_premium_soon'                   : 'Päivitys Pro-versioon tulossa pian!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Uusimmat ensin',
  'history_sort_alphabetical'           : 'A–Ö',
  'history_sort_last_edited'            : 'Viimeksi muokattu',
  'history_sort_by_template'            : 'Mallin mukaan',
  'history_sort_sheet_title'            : 'Järjestä',
  'history_sort_alphabetical_full'      : 'Aakkosjärjestys (A–Ö)',
  'history_premium_soon'                : 'Päivitys Pro-versioon tulossa pian!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Asetukset',
  'settings_section_preferences'        : 'Asetukset',
  'settings_section_support'            : 'Tuki',
  'settings_section_legal'              : 'Oikeudelliset',
  'settings_section_about'              : 'Tietoja',
  'settings_language_tile_title'        : 'Kieli',
  'settings_dark_mode_title'            : 'Tumma tila',
  'settings_dark_mode_on'               : 'Tumma teema käytössä',
  'settings_dark_mode_off'              : 'Vaalea teema käytössä',
  'settings_help_faq_title'             : 'Ohje ja UKK',
  'settings_help_faq_sub'               : 'Yleisimmät kysymykset vastattu',
  'settings_contact_support_title'      : 'Ota yhteyttä tukeen',
  'settings_rate_app_title'             : 'Arvioi sovellus',
  'settings_rate_app_sub'               : 'Pidätkö sovelluksesta? Jätä arvostelu!',
  'settings_privacy_policy_title'       : 'Tietosuojakäytäntö',
  'settings_terms_title'                : 'Käyttöehdot',
  'settings_app_version_title'          : 'Sovelluksen versio',
  'settings_email_error'                : 'Sähköpostisovellusta ei voitu avata. Lähetä sähköpostia osoitteeseen cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CV:n esikatselu',
  'preview_header_sub'                  : 'Valmis vientiin',
  'preview_generating'                  : 'Luodaan CV:tä...',
  'preview_failed_title'                : 'Esikatselu epäonnistui',
  'preview_failed_error'                : 'Virhe: {error}',
  'preview_go_back'                     : 'Palaa takaisin',
  'preview_no_data'                     : 'Ei tietoja saatavilla',
  'preview_btn_print'                   : 'Tulosta',
  'preview_btn_download'                : 'Lataa ja jaa',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Ohje ja UKK',
  'faq_category_all'                    : 'Kaikki',
  'faq_empty'                           : 'Tuloksia ei löydy',
  'faq_contact_headline'                : 'Tarvitsetko vielä apua?',
  'faq_contact_sub'                     : 'Tiimimme on täällä sinua varten.',
  'faq_contact_btn'                     : 'Ota yhteyttä',
  'faq_email_error'                     : 'Sähköpostisovellusta ei voitu avata. Lähetä sähköpostia osoitteeseen cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Aloittaminen',
  'faq_cat_templates'                   : 'Mallit',
  'faq_cat_editing'                     : 'Muokkaus',
  'faq_cat_exporting'                   : 'Vienti',
  'faq_cat_data_privacy'                : 'Tiedot ja yksityisyys',
  'faq_cat_troubleshooting'             : 'Vianmääritys',
  'faq_q1'  : 'Miten luon ensimmäisen CV:ni?',
  'faq_a1'  : 'Napauta aloitusnäytön "+" -painiketta aloittaaksesi uuden CV:n. Valitse tyylillesi sopiva malli, täytä sitten henkilötietosi, työkokemuksesi, koulutuksesi ja taitosi vaihe vaiheelta. Edistymisesi tallennetaan automaattisesti.',
  'faq_q2'  : 'Voinko luoda useamman kuin yhden CV:n?',
  'faq_a2'  : 'Kyllä! Voit luoda useita CV:itä eri tehtäviä tai toimialoja varten. Jokainen CV tallennetaan erikseen, joten voit räätälöidä ne tiettyihin työnhakemuksiin.',
  'faq_q3'  : 'Miten vaihdan CV:ni mallin?',
  'faq_a3'  : 'Avaa CV:si, napauta näytön yläosassa olevaa mallikuvaketta ja selaa saatavilla olevia malleja. Napauta mitä tahansa mallia esikatsellaksesi sen nykyisellä sisälläsi. Vahvista ottaaksesi sen käyttöön.',
  'faq_q4'  : 'Onko ilmaisia ja premium-malleja?',
  'faq_a4'  : 'Kyllä. Valikoima ammatillisia malleja on saatavilla ilmaiseksi. Premium-mallit edistyneillä suunnitteluilla ja väripaletteilla ovat saatavilla kertaostoksella tai tilauksella.',
  'faq_q5'  : 'Miten lisään tai poistan osioita?',
  'faq_a5'  : 'CV-editorissa vieritä näytön alareunaan ja napauta "Lisää osio" lisätäksesi lisäosia kuten Kielet, Sertifioinnit tai Vapaaehtoistoiminta. Poistaaksesi osion napauta osion otsikkoa ja valitse "Poista."',
  'faq_q6'  : 'Miten järjestän osiot uudelleen?',
  'faq_a6'  : 'Paina pitkään vetokahvaa (≡) minkä tahansa osion otsikon vieressä ja vedä se haluamaasi paikkaan. Muutokset tallennetaan automaattisesti.',
  'faq_q7'  : 'Miten vien CV:ni PDF:nä?',
  'faq_a7'  : 'Avaa CV:si ja napauta vientipainiketta (jako-kuvake) oikeassa yläkulmassa. Valitse "Vie PDF:nä." Voit sitten tallentaa sen laitteellesi, jakaa sen sähköpostilla, WhatsAppilla tai ladata sen suoraan työnhakusivustoille.',
  'faq_q8'  : 'Mitä tiedostomuotoja tuetaan?',
  'faq_a8'  : 'Tällä hetkellä sovellus tukee CV:n viemistä korkealaatuisena PDF:nä. Lisämuotoja voidaan lisätä tulevissa päivityksissä.',
  'faq_q9'  : 'Missä CV:ni tiedot tallennetaan?',
  'faq_a9'  : 'Kaikki CV:si tiedot tallennetaan paikallisesti laitteellesi. Emme lataa henkilökohtaisia tietojasi palvelimillemme. Tämä tarkoittaa, että tietosi pysyvät yksityisinä ja ovat käytettävissä offline-tilassa.',
  'faq_q10' : 'Miten varmuuskopioin CV:ni?',
  'faq_a10' : 'CV:si sisältyvät laitteesi vakiovarmuuskopioon (Google Drive Androidilla, iCloud iOS:llä), jos varmuuskopio on käytössä laitteesi asetuksissa. Voit myös viedä yksittäiset CV:t PDF:nä säilyttääksesi kopion.',
  'faq_q11' : 'Sovellus toimii hitaasti. Mitä minun pitäisi tehdä?',
  'faq_a11' : 'Kokeile sulkea ja avata sovellus uudelleen. Jos ongelma jatkuu, käynnistä laite uudelleen. Varmista, että sinulla on uusin versio sovelluksesta asennettuna Play Storesta / App Storesta.',
  'faq_q12' : 'CV:ni ei vie oikein. Mitä minun pitäisi tehdä?',
  'faq_a12' : 'Varmista, että laitteellasi on tarpeeksi tallennustilaa. Kokeile pienentää suuria kuvia CV:ssäsi. Jos ongelma jatkuu, ota yhteyttä tukitiimiimme.',
  'faq_q13' : 'Unohdin tallentaa — onko työni menetetty?',
  'faq_a13' : 'Ei lainkaan! Sovellus tallentaa edistymisesi jatkuvasti muokkauksen aikana.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Urasi, täydelliseksi hiottuna',
  'header_tooltip_back'                 : 'Takaisin',
  'header_tooltip_my_cvs'               : 'CV:ni',
  'header_tooltip_settings'             : 'Asetukset',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV:ni',
  'saved_count_single'                  : '{n} asiakirja',
  'saved_count_plural'                  : '{n} asiakirjaa',
  'saved_limit_reached'                 : 'Raja saavutettu',
  'saved_footer_count'                  : '{n} / 30 CV:tä',
  'saved_filter_all'                    : 'Kaikki',
  'saved_filter_draft'                  : 'Luonnos',
  'saved_filter_complete'               : 'Valmis',
  'saved_status_complete'               : 'Valmis',
  'saved_status_saved'                  : 'Tallennettu',
  'saved_status_draft'                  : 'Luonnos',
  'saved_empty_title'                   : 'Ei vielä CV:itä',
  'saved_empty_sub'                     : 'Aloita ensimmäisen CV:si rakentaminen yllä',
  'saved_search_empty_title'            : 'Tuloksia ei löydy',
  'saved_search_empty_sub'              : 'Kokeile eri hakusanaa',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Väriteema',
  'custom_font_settings_title'          : 'Kirjasinmääritykset',
  'custom_font_family_label'            : 'Kirjasinperhe',
  'custom_font_size_label'              : 'Kirjasinkoko: ',
  'custom_current_template_title'       : 'Nykyinen malli',
  'custom_change_template_btn'          : 'Vaihda mallia',
  'custom_tpl_modern'                   : 'Moderni',
  'custom_tpl_classic'                  : 'Klassinen',
  'custom_tpl_professional'             : 'Ammatillinen',
  'custom_tpl_creative'                 : 'Luova',
  'custom_tpl_minimal'                  : 'Minimalistinen',
  'custom_tpl_modern_desc'              : 'Puhdas ja ajanmukainen suunnittelu',
  'custom_tpl_classic_desc'             : 'Perinteinen ammatillinen asettelu',
  'custom_tpl_professional_desc'        : 'Liiketoimintakeskeinen malli',
  'custom_tpl_creative_desc'            : 'Erottu ainutlaatuisella suunnittelulla',
  'custom_tpl_minimal_desc'             : 'Yksinkertainen ja tyylikäs tyyli',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Valitse malli',
  'swipe_photo_badge'                   : 'Kuva',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Johtaja',
  'tpl_nordic_name'                     : 'Pohjoismainen',
  'tpl_vibrant_name'                    : 'Eloisa',
  'tpl_tech_dark_name'                  : 'Tech tumma',
  'tpl_luxury_name'                     : 'Luksus',
  'tpl_executive_tag'                   : 'Suosituin',
  'tpl_nordic_tag'                      : 'Selkeä',
  'tpl_vibrant_tag'                     : 'Luova',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Rohkea ja arvovaltainen vanhemmille tehtäville',
  'tpl_nordic_desc'                     : 'Minimalistinen selkeys, johon johtavat yritykset luottavat',
  'tpl_vibrant_desc'                    : 'Erottu energialla ja väreillä',
  'tpl_tech_dark_desc'                  : 'Terminaaliestetiikka kehittäjille',
  'tpl_luxury_desc'                     : 'Kultakoristeltu arvokkuus mustalla pohjalla',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Malli',
  'detail_step_personal'                : 'Henkilökohtainen',
  'detail_step_experience'              : 'Kokemus',
  'detail_step_education'               : 'Koulutus',
  'detail_step_skills'                  : 'Taidot',
  'detail_step_additional'              : 'Lisätiedot',
  'detail_step_references'              : 'Suosittelijat',
  'detail_step_customize'               : 'Mukauta',
  'detail_banner_heading'               : 'Melkein valmista!',
  'detail_banner_btn'                   : 'Jatka',
  'detail_banner_completion_label'      : 'Valmistuminen',
  'detail_stat_created_label'           : 'Luotu',
  'detail_stat_steps_label'             : 'Vaiheita tehty',
  'detail_section_template_style'       : 'Mallin tyyli',
  'detail_section_steps'                : 'Vaiheet',
  'detail_steps_counter'                : '{done} / {total} valmis',
  'detail_step_sub'                     : 'Vaihe {n} / {total}',
  'detail_section_activity'             : 'Toiminta',
  'detail_activity_created'             : 'Luotu',
  'detail_activity_last_edited'         : 'Viimeksi muokattu',
  'detail_activity_template'            : 'Malli',
  'detail_btn_continue_editing'         : 'Jatka muokkaamista',
  'detail_btn_edit_cv'                  : 'Muokkaa CV:tä',
  'detail_option_rename'                : 'Nimeä CV uudelleen',
  'detail_option_delete'                : 'Poista CV',
  'detail_rename_title'                 : 'Nimeä CV uudelleen',
  'detail_rename_hint'                  : 'esim. Ohjelmistoinsinöörin CV',
  'detail_rename_error_empty'           : 'Nimi ei voi olla tyhjä',
  'detail_rename_btn_cancel'            : 'Peruuta',
  'detail_rename_btn_save'              : 'Tallenna',
  'detail_rename_snackbar'              : 'Nimetty uudelleen nimeksi "{name}"',
  'detail_delete_title'                 : 'Poistetaanko CV?',
  'detail_delete_body'                  : 'Tämä poistaa pysyvästi "{name}". Tätä toimintoa ei voi kumota.',
  'detail_delete_btn_cancel'            : 'Peruuta',
  'detail_delete_btn_confirm'           : 'Poista',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Valmis',
  'detail_check_tile_incomplete'        : 'Ei vielä täytetty',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Valitse mallisi',
  'chooser_subtitle'                    : 'Pyyhkäise selataksesi  ·  Napauta valitaksesi  ·  Pidä esikatsellaksesi',
  'chooser_card_hold_hint'              : 'Pidä esikatsellaksesi',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Valittu',
  'chooser_modal_heading'               : 'Nimeä CV:si',
  'chooser_modal_sub'                   : 'Anna sille nimi, jotta löydät sen helposti CV:istäni ja historiastani.',
  'chooser_modal_field_label'           : 'CV:n nimi',
  'chooser_modal_save_btn'              : 'Tallenna ja aloita rakentaminen',
  'chooser_modal_divider'               : 'tai jatka olemassa olevaa CV:tä',
  'chooser_nav_selected_sub'            : 'Valittu malli',
  'chooser_nav_cta'                     : 'Tallenna ja jatka',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Enimmäismäärä merkintöjä saavutettu',
  'editor_show_hide'                    : 'Näytä/Piilota',
  'editor_editing_badge'                : 'Muokataan',
  'editor_field_required'               : 'Pakollinen',
  'editor_tooltip_edit'                 : 'Muokkaa',
  'editor_tooltip_delete'               : 'Poista',
  'editor_date_start'                   : 'Alkamispäivä *',
  'editor_date_end'                     : 'Päättymispäivä *',
  'editor_date_tap_hint'                : 'Napauta valitaksesi',
  'editor_date_dialog_title'            : 'Valitse kuukausi ja vuosi',
  'editor_date_confirm'                 : 'Vahvista',
  'editor_panel_hide'                   : 'Piilota',
  'editor_panel_show'                   : 'Näytä',
  'editor_validator_max_chars'          : 'Enintään {n} merkkiä',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Rakenna CV:si',
  'editor_header_step_sub'              : 'Vaihe {current} / {total} · {label}',
  'editor_step_template'                : 'Malli',
  'editor_step_personal'                : 'Henkilökohtainen',
  'editor_step_experience'              : 'Kokemus',
  'editor_step_education'               : 'Koulutus',
  'editor_step_skills'                  : 'Taidot',
  'editor_step_additional'              : 'Lisätiedot',
  'editor_step_references'              : 'Suosittelijat',
  'editor_step_customize'               : 'Mukauta',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Mukauta',
  'customize_subtitle'                  : 'Tee CV:stäsi ainutlaatuisesti omasi',
  'customize_smart_layout_btn'          : 'Älykäs asettelu',
  'customize_back_to_top'               : 'Takaisin ylös',
  'customize_done_title'                : 'Kaikki on valmista!',
  'customize_done_sub'                  : 'Napauta Esikatsele CV alla nähdäksesi valmiin CV:si',
  'customize_preview_btn'               : 'Esikatsele CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Väriteema',
  'color_black'                         : 'Musta',
  'color_blue'                          : 'Sininen',
  'color_nordic_blue'                   : 'Pohjoismainen sininen',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Sinivihreä',
  'color_green'                         : 'Vihreä',
  'color_purple'                        : 'Violetti',
  'color_orange'                        : 'Oranssi',
  'color_red'                           : 'Punainen',
  'color_executive_gold'                : 'Johtajan kulta',
  'color_vibrant_coral'                 : 'Eloisa koralli',
  'color_white'                         : 'Valkoinen',
  'color_white_bg'                      : 'Valkoinen tausta',
  'color_maroon'                        : 'Kastanjanruskea',
  'color_brutalist_yellow'              : 'Brutalistinen keltainen',
  'color_neon_blue'                     : 'Neonsininen',
  'color_blueprint_navy'                : 'Blueprint laivastonsininen',
  'color_light_grey'                    : 'Vaalenharmaa',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Kirjasinperhe',
  'customize_font_picker_title'         : 'Valitse kirjasin',
  'customize_font_picker_sub'           : 'Jokainen kirjasin esikatsellaan omassa kirjasinlajissaan',
  'customize_font_preview_sample'       : 'Nopea ruskea kettu',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Kirjasinkoko',
  'customize_font_size_label'           : 'Tekstikoko',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Kuvan koko',
  'customize_image_size_label'          : 'Kuvan koko',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Reaaliaikainen esikatselu',
  'preview_page_count_singular'         : '1 sivu',
  'preview_page_count_plural'           : '{n} sivua',
  'preview_page_of'                     : 'Sivu {page} / {total}',
  'preview_live_hint'                   : 'Muutokset näkyvät välittömästi',
  'preview_template_unregistered'       : 'Ei vielä rekisteröity customize_preview.dart-tiedostossa',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Valmistellaan CV:täsi…',
  'preview_bar_print'                   : 'Tulosta',
  'preview_bar_save_pdf'                : 'Tallenna PDF:nä',
  'preview_bar_share'                   : 'Jaa',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CV:n esikatselu',
  'preview_screen_sub'                  : '{n} {unit} · täsmälleen kuten tulostettu',
  'preview_page_singular'               : 'sivu',
  'preview_page_plural'                 : 'sivua',
  'preview_pdf_filename'                : 'CV:ni',
  'preview_share_subject'               : 'CV:ni',
  'preview_snack_print_failed'          : 'Tulostus epäonnistui: {e}',
  'preview_snack_saved'                 : 'CV tallennettu Lataukset-kansioon ✓',
  'preview_snack_export_failed'         : 'Vienti epäonnistui: {e}',
  'preview_snack_share_failed'          : 'Jakaminen epäonnistui: {e}',
  'preview_template_not_registered'     : 'Mallia ei ole rekisteröity',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Sulje esikatselu',
  'preview_modal_hint_photo'            : 'Tukee profiilikuvaa  ·  Napauta korttia valitaksesi',
  'preview_modal_hint_no_photo'         : 'Napauta mallikorttia valitaksesi sen',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV:ni',
  'time_just_now'                       : 'Juuri nyt',
  'time_minutes_ago'                    : '{n} min sitten',
  'time_hours_ago'                      : '{n} t sitten',
  'time_yesterday'                      : 'Eilen',
  'time_days_ago'                       : '{n} päivää sitten',
  'time_one_week_ago'                   : '1 viikko sitten',
  'time_weeks_ago'                      : '{n} viikkoa sitten',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Tyylikäs',
  'tpl_tag_classic'                     : 'Klassinen',
  'tpl_tag_minimal'                     : 'Minimalistinen',
  'tpl_tag_creative'                    : 'Luova',
  'tpl_tag_bold'                        : 'Rohkea',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Liukuväri',
  'tpl_gradient_desc'                   : 'Sinivihreästä violettiin liukuvärijätetyt kortit',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Toimituksellinen',
  'tpl_editorial_desc'                  : 'Lehtityylinen punaisella ja kermavalkoisella',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pehmeä pastelli',
  'tpl_pastel_soft_desc'                : 'Laventeli sivupalkki, pehmeät kortit',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalistinen',
  'tpl_brutalist_desc'                  : 'Raaka ruudukko, rohkeat reunat ja keltainen',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragdi',
  'tpl_emerald_desc'                    : 'Metsänvihreä aikajanalla',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografiikka',
  'tpl_infographic_desc'                : 'Tumma kanvas rengaskaavioilla',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920-luvun geometrinen kultaluksus',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina tumma',
  'tpl_wina_dark_desc'                  : 'Tumma infografiikka renkailla',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio oranssi',
  'tpl_rio_orange_desc'                 : 'Tumma sivupalkki oranssilla korostuksella',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Kesä',
  'tpl_summer_desc'                     : 'Puhdas minimalistinen, pehmeät harmaat sävyt',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Lämmin beige tyylikäs sävy',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Pelkistetty mustavalkoinen klassikko',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klassinen ATS-yhteensopiva asettelu',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony tumma',
  'tpl_tony_dark_desc'                  : 'Tumma oranssi infografiikkatyyli',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Muoti',
  'tpl_fashion_desc'                    : 'Tekninen piirustus ruudukolla',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arkistonhoitaja',
  'tpl_archivist_desc'                  : 'Klassinen kaksisarakkeinen etikettijärjestely',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomaatti',
  'tpl_diplomat_desc'                   : 'Varjostetut otsikot timanttijohtajilla',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridiaani',
  'tpl_meridian_desc'                   : 'Keskitetyt otsikot, korostetut yritykset',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Vauhti',
  'tpl_momentum_desc'                   : 'Rohkea nimi, aikajanan pisteet ja saavutukset',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Henkilökohtaiset tiedot',
  'personal_subtitle'                   : 'Kerro työnantajille kuka olet',
  'personal_profile_counter'            : '{n}/{max} profiilia',
  'personal_info_banner'                : 'Tallenna jopa 5 profiilia ja valitse yksi per CV. Valintasi muistetaan jokaiselle CV:lle erikseen.',
  'personal_snack_max'                  : '{n} profiilin enimmäismäärä saavutettu.',
  'personal_add_btn'                    : 'Lisää uusi profiili',
  'personal_library_title'              : 'Tallennetut profiilit',
  'personal_selected_one'               : '1 valittu',
  'personal_selected_none'              : 'ei valittua',
  'personal_library_hint'               : 'Napauta korttia valitaksesi sen vain tälle CV:lle. Muut CV:t säilyttävät omat itsenäiset valintansa.',
  'personal_empty_message'              : 'Ei vielä tallennettuja profiileja',
  'personal_empty_sub'                  : 'Napauta yllä lisätäksesi henkilökohtaiset tietosi',
  'personal_nav_next'                   : 'Tallenna ja jatka',
  'personal_card_active_badge'          : 'Aktiivinen tälle CV:lle',
  'personal_sheet_title_add'            : 'Uusi profiili',
  'personal_sheet_title_edit'           : 'Muokkaa profiilia',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTINEN',
  'personal_sheet_brutalist_banner'     : 'Brutalistinen malli sisältää kompaktit yhteystietokentät. Lyhyemmät arvot (esim. vain kaupunki) näyttävät parhaimmilta.',
  'personal_section_photo'              : 'Profiilikuva',
  'personal_section_basic'              : 'Perustiedot',
  'personal_section_contact'            : 'Yhteystiedot',
  'personal_section_online'             : 'Verkkonäkyvyys',
  'personal_section_summary'            : 'Ammatillinen yhteenveto',
  'personal_field_first_name'           : 'Etunimi *',
  'personal_field_last_name'            : 'Sukunimi',
  'personal_field_job_title'            : 'Tehtävänimike *',
  'personal_field_email'                : 'Sähköpostiosoite *',
  'personal_field_phone'                : 'Puhelinnumero *',
  'personal_field_location'             : 'Sijainti',
  'personal_field_location_brut'        : 'Sijainti (vain kaupunki)',
  'personal_field_website'              : 'Verkkosivusto / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn-URL',
  'personal_hint_first_name'            : 'esim. Liisa',
  'personal_hint_last_name'             : 'esim. Mäkinen',
  'personal_hint_job_title'             : 'esim. Vanhempi insinööri',
  'personal_hint_email'                 : 'esim. liisa@esimerkki.fi',
  'personal_hint_phone'                 : 'esim. +358 40 123 4567',
  'personal_hint_location'              : 'esim. Helsinki, Suomi',
  'personal_hint_location_brut'         : 'esim. Helsinki',
  'personal_hint_website'               : 'esim. github.com/liisamakinen',
  'personal_hint_website_brut'          : 'esim. github.com/liisa',
  'personal_hint_linkedin'              : 'esim. linkedin.com/in/liisamakinen',
  'personal_hint_linkedin_brut'         : 'esim. linkedin.com/in/liisa',
  'personal_summary_hint_label'         : 'Pidä se tiiviinä — tämä näkyy CV:si yläosassa.',
  'personal_hint_summary'               : 'Lyhyt 2–3 lauseen yhteenveto taustastasi ja tavoitteistasi...',
  'personal_validator_email'            : 'Anna kelvollinen sähköpostiosoite',
  'personal_field_char_limit_tooltip'   : 'Merkkimääräraja saavutettu',
  'personal_sheet_btn_save'             : 'Tallenna profiili',
  'personal_sheet_btn_update'           : 'Tallenna muutokset',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Valitse kuva',
  'photo_option_gallery'                : 'Valitse galleriasta',
  'photo_option_camera'                 : 'Ota kuva',
  'photo_option_reposition'             : 'Muuta kuvan sijaintia',
  'photo_option_remove'                 : 'Poista kuva',
  'photo_status_added'                  : 'Kuva lisätty ✓',
  'photo_status_empty'                  : 'Lisää ammatillinen kasvokuva',
  'photo_chip_gallery'                  : 'Galleria',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Muuta sijaintia',
  'photo_reposition_title'              : 'Muuta kuvan sijaintia',
  'photo_reposition_sub'                : 'Vedä kuvaa säätääksesi sijaintia',
  'photo_reposition_reset'              : 'Palauta keskelle',
  'photo_reposition_apply'              : 'Käytä',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Taidot',
  'skills_subtitle'                     : 'Korosta tärkeimmät kykysi',
  'skills_add_btn'                      : 'Lisää uusi taito',
  'skills_snack_max_icons'              : 'Enintään 10 kuvaketta valittu.',
  'skills_snack_max_skills'             : '15 taidon enimmäismäärä saavutettu.',
  'skills_library_title'                : 'Tallennetut taidot',
  'skills_library_hint'                 : 'Valitut taidot sisältyvät tähän CV:hen. Valintasi tallennetaan automaattisesti.',
  'skills_nav_next'                     : 'Jatka lisätietoihin',
  'skills_wina_header_icon_bar'         : 'Otsikon kuvakepalkki',
  'skills_wina_on'                      : 'PÄÄLLÄ',
  'skills_wina_off'                     : 'POIS',
  'skills_wina_bar_on_sub'              : 'Väritetyt kuvakeympyrät näytetään CV:n otsikossa.',
  'skills_wina_bar_off_sub'             : 'Kuvakerivi piilotettu — enemmän tilaa yhteystiedoille.',
  'skills_wina_palette_hint'            : 'Kuvakkeet näkyvät väritettyinä ympyröinä paletin järjestyksessä.',
  'skills_wina_preview_label'           : 'Esikatselu',
  'skills_wina_disabled_hint'           : 'Ota kuvakepalkki käyttöön yllä valitaksesi, mitkä kuvakkeet näkyvät CV:n otsikossa.',
  'skills_sheet_title_add'              : 'Lisää taito',
  'skills_sheet_title_edit'             : 'Muokkaa taitoa',
  'skills_sheet_field_name'             : 'Taidon nimi *',
  'skills_sheet_hint_short'             : 'esim. Flutter, Suunnittelu',
  'skills_sheet_hint_long'              : 'esim. Flutter, Projektinhallinta',
  'skills_sheet_validator_max'          : 'Enintään {n} merkkiä',
  'skills_sheet_proficiency'            : 'Osaamistaso',
  'skills_sheet_beginner'               : 'Aloittelija',
  'skills_sheet_expert'                 : 'Asiantuntija',
  'skills_sheet_btn_save'               : 'Tallenna taito',
  'skills_sheet_btn_update'             : 'Päivitä taito',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Henkilökohtaiset suosittelijat',
  'refs_subtitle'                       : 'Henkilöt, jotka voivat suositella sinua henkilökohtaisesti',
  'refs_add_btn'                        : 'Lisää uusi henkilökohtainen suosittelija',
  'refs_snack_max_selected'             : 'CV:lle voidaan valita enintään 4 suosittelijaa.',
  'refs_snack_max_saved'                : '10 tallennetun suosittelijan enimmäismäärä saavutettu.',
  'refs_library_title'                  : 'Tallennetut suosittelijat',
  'refs_library_hint'                   : 'Valitut suosittelijat sisältyvät tähän CV:hen. Enintään 4 per CV. Valintasi tallennetaan automaattisesti.',
  'refs_nav_next'                       : 'Jatka mukauttamiseen',
  'refs_sheet_title_add'                : 'Lisää henkilökohtainen suosittelija',
  'refs_sheet_title_edit'               : 'Muokkaa henkilökohtaista suosittelijaa',
  'refs_sheet_sub_add'                  : 'Henkilö, joka voi suositella sinua henkilökohtaisesti työnantajille.',
  'refs_sheet_sub_edit'                 : 'Päivitä tämän suosittelijan tiedot alla.',
  'refs_sheet_field_name'               : 'Koko nimi *',
  'refs_sheet_field_title'              : 'Tehtävänimike *',
  'refs_sheet_field_company'            : 'Yritys (valinnainen)',
  'refs_sheet_field_email'              : 'Sähköpostiosoite *',
  'refs_sheet_field_phone'              : 'Puhelinnumero *',
  'refs_sheet_hint_name'                : 'esim. Mikko Virtanen',
  'refs_sheet_hint_title'               : 'esim. Insinööripäällikkö',
  'refs_sheet_hint_company'             : 'esim. Acme Oy',
  'refs_sheet_hint_email'               : 'esim. mikko@acme.fi',
  'refs_sheet_hint_phone'               : 'esim. +358 40 123 4567',
  'refs_sheet_validator_email'          : 'Anna kelvollinen sähköpostiosoite',
  'refs_sheet_btn_save'                 : 'Tallenna henkilökohtainen suosittelija',
  'refs_sheet_btn_update'               : 'Päivitä henkilökohtainen suosittelija',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Työkokemus',
  'exp_subtitle'                        : 'Lisää työhistoriasi',
  'exp_banner_info'                     : 'Enintään {n} vastuuta per tehtävä näkyy CV:ssä. 3–6 tehtävää mahtuu yleensä 1–2 sivulle.',
  'exp_add_btn'                         : 'Lisää uusi kokemus',
  'exp_snack_max_selected'              : 'CV:lle voidaan valita enintään 8 kokemusta.',
  'exp_snack_max_saved'                 : '12 tallennetun kokemuksen enimmäismäärä saavutettu.',
  'exp_library_title'                   : 'Tallennetut kokemukset',
  'exp_library_hint'                    : 'Valitut merkinnät sisältyvät vain tähän CV:hen. Muut CV:t säilyttävät omat itsenäiset valintansa.',
  'exp_nav_next'                        : 'Jatka koulutukseen',
  'exp_empty_message'                   : 'Ei vielä lisättyä kokemusta',
  'exp_empty_sub'                       : 'Napauta yllä lisätäksesi ensimmäisen tehtäväsi',
  'exp_card_resp_singular'              : 'vastuu',
  'exp_card_resp_plural'                : 'vastuuta',
  'exp_card_resp_tooltip'               : 'Vain ensimmäiset 8 vastuuta näkyvät CV:ssä',
  'exp_sheet_title_add'                 : 'Lisää kokemus',
  'exp_sheet_title_edit'                : 'Muokkaa kokemusta',
  'exp_sheet_field_job_title'           : 'Tehtävänimike *',
  'exp_sheet_field_company'             : 'Yritys *',
  'exp_sheet_field_location'            : 'Sijainti',
  'exp_sheet_section_responsibilities'  : 'Keskeiset vastuut',
  'exp_sheet_resp_hint_info'            : 'Enintään 8 luettelopistettä · 200 merkkiä kukin',
  'exp_sheet_resp_label'                : 'Vastuu {n}',
  'exp_sheet_resp_hint'                 : 'esim. Johdin 5 insinöörin tiimiä',
  'exp_sheet_resp_add_btn'              : 'Lisää vastuu',
  'exp_sheet_resp_max_info'             : '{n} vastuun enimmäismäärä saavutettu',
  'exp_sheet_resp_validator_max'        : 'Enintään 200 merkkiä',
  'exp_sheet_hint_job_title'            : 'esim. Vanhempi kehittäjä',
  'exp_sheet_hint_location'             : 'esim. Helsinki, Suomi',
  'exp_sheet_btn_save'                  : 'Tallenna kokemus',
  'exp_sheet_btn_update'                : 'Tallenna muutokset',
  'exp_date_present'                    : 'Nykyinen / Tämänhetkinen tehtävä',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Koulutus',
  'edu_subtitle'                        : 'Lisää akateeminen taustasi',
  'edu_add_btn'                         : 'Lisää uusi koulutus',
  'edu_snack_max_selected'              : 'CV:lle voidaan valita enintään 8 koulutusmerkintää.',
  'edu_snack_max_saved'                 : '12 tallennetun koulutusmerkinnän enimmäismäärä saavutettu.',
  'edu_library_title'                   : 'Tallennettu koulutus',
  'edu_library_hint'                    : 'Valitut merkinnät sisältyvät tähän CV:hen. Valintasi tallennetaan automaattisesti.',
  'edu_nav_next'                        : 'Jatka taitoihin',
  'edu_empty_message'                   : 'Ei vielä lisättyä koulutusta',
  'edu_empty_sub'                       : 'Napauta yllä lisätäksesi tutkintatietosi',
  'edu_card_bullet_singular'            : 'luettelopiste',
  'edu_card_bullet_plural'              : 'luettelopistettä',
  'edu_sheet_title_add'                 : 'Lisää koulutus',
  'edu_sheet_title_edit'                : 'Muokkaa koulutusta',
  'edu_sheet_field_degree'              : 'Tutkinto / Pätevyys *',
  'edu_sheet_field_institution'         : 'Oppilaitos *',
  'edu_sheet_section_key_points'        : 'Keskeiset kohdat',
  'edu_sheet_key_points_hint_info'      : 'Valinnainen · 1 luettelopiste · enintään 100 merkkiä',
  'edu_sheet_point_label'               : 'Kohta {n}',
  'edu_sheet_point_add_btn'             : 'Lisää luettelopiste',
  'edu_sheet_point_max_info'            : '{n} luettelopisteen enimmäismäärä saavutettu',
  'edu_sheet_point_validator_max'       : 'Enintään {n} merkkiä',
  'edu_sheet_hint_degree'               : 'esim. Tietojenkäsittelytieteen kandidaatti',
  'edu_sheet_hint_institution'          : 'esim. Aalto-yliopisto',
  'edu_sheet_hint_bullet'               : 'esim. Laudatur-arvosana',
  'edu_sheet_btn_save'                  : 'Tallenna koulutus',
  'edu_sheet_btn_update'                : 'Tallenna muutokset',
  'edu_date_present'                    : 'Nykyinen / Opiskelen tällä hetkellä',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Lisätiedot',
  'additional_subtitle'                 : 'Sertifioinnit, kielet ja muuta',
  'additional_cert_section_title'       : 'Sertifioinnit',
  'additional_cert_counter'             : '{sel}/{total} valittu · enintään {max}',
  'additional_cert_hide'                : 'Piilota',
  'additional_cert_show'                : 'Näytä',
  'additional_cert_add_btn'             : 'Lisää',
  'additional_cert_snack_max'           : '{n} sertifiointimerkinnän enimmäismäärä saavutettu.',
  'additional_cert_hint'                : 'Valitut merkinnät sisältyvät tähän CV:hen. Valintasi tallennetaan automaattisesti.',
  'additional_cert_empty'               : 'Ei vielä lisättyjä sertifiointeja',
  'additional_lang_section_title'       : 'Kielet',
  'additional_lang_add_hint'            : 'esim. Englanti',
  'additional_lang_snack_max'           : '{n} kielimerkinnän enimmäismäärä saavutettu.',
  'additional_lang_empty'               : 'Ei vielä lisättyjä kieliä',
  'additional_hobby_section_title'      : 'Harrastukset ja kiinnostuksen kohteet',
  'additional_hobby_add_hint'           : 'esim. Valokuvaus',
  'additional_hobby_snack_max'          : '{n} harrastusmerkinnän enimmäismäärä saavutettu.',
  'additional_hobby_empty'              : 'Ei vielä lisättyjä harrastuksia',
  'additional_section_hint'             : 'Valitut merkinnät sisältyvät tähän CV:hen. Valintasi tallennetaan automaattisesti.',
  'additional_nav_next'                 : 'Jatka suosittelijoihin',
  'cert_sheet_title_add'                : 'Lisää sertifiointi',
  'cert_sheet_title_edit'               : 'Muokkaa sertifiointia',
  'cert_sheet_sub'                      : 'Lisää pätevyys, todistus tai ammatillinen tunnustus.',
  'cert_sheet_field_name'               : 'Sertifioinnin nimi *',
  'cert_sheet_field_issued_by'          : 'Myöntäjä (valinnainen)',
  'cert_sheet_field_short_desc'         : 'Lyhyt kuvaus (valinnainen)',
  'cert_sheet_hint_name'                : 'esim. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'esim. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'esim. Saavutettu 2024',
  'cert_sheet_btn_save'                 : 'Tallenna sertifiointi',
  'cert_sheet_btn_update'               : 'Päivitä sertifiointi',
  'simple_sheet_title_add_language'     : 'Lisää kieli',
  'simple_sheet_title_edit_language'    : 'Muokkaa kieltä',
  'simple_sheet_title_add_hobby'        : 'Lisää harrastus',
  'simple_sheet_title_edit_hobby'       : 'Muokkaa harrastusta',
  'simple_sheet_btn_save'               : 'Tallenna',
  'simple_sheet_btn_update'             : 'Päivitä',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Yhteystiedot',
  'pdf_section_about_me'                : 'Minusta',
  'pdf_section_summary'                 : 'Yhteenveto',
  'pdf_section_summary_short'           : 'Yhteenveto',
  'pdf_section_profile'                 : 'Profiili',
  'pdf_section_experience'              : 'Kokemus',
  'pdf_section_experience_short'        : 'Kokemus',
  'pdf_section_education'               : 'Koulutus',
  'pdf_section_skills'                  : 'Taidot',
  'pdf_section_languages'               : 'Kielet',
  'pdf_label_email'                     : 'Sähköposti',
  'pdf_label_phone'                     : 'Puhelin',
  'pdf_label_location'                  : 'Sijainti',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV-raja saavutettu',
  'limit_dialog_body'                   : 'Olet saavuttanut enimmäismäärän 30 CV:tä. Poista olemassa oleva CV ennen uuden luomista.',
  'limit_dialog_go_to_my_cvs'           : 'Siirry CV:ihini',
  'limit_dialog_cancel'                 : 'Peruuta',
  'refs_count_summary'                  : '{checked}/{maxChecked} valittu · {saved}/{maxSaved} tallennettu',
  'refs_selected_badge'                 : '{n} valittu',
  'refs_empty_message'                  : 'Ei tallennettuja suosituksia vielä',
  'refs_empty_sub'                      : 'Napauta ylhäältä lisätäksesi henkilökohtaisen suosituksen',
};