// lib/language_keys/lang_el_greek.dart
//
// Greek (Ελληνικά) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> elGreek = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Δεν βρέθηκαν γλώσσες',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Παράλειψη',
  'onboarding_next'                     : 'Επόμενο',
  'onboarding_get_started'              : 'Ξεκινήστε',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Καλωσορίσατε',
  'ob1_title'                           : 'Δημιουργήστε ένα CV\nπου Ανοίγει Πόρτες',
  'ob1_body'                            : 'Ξεχωρίστε από εκατοντάδες υποψηφίους. Δημιουργήστε ένα επαγγελματικό, νικηφόρο CV σε λίγα λεπτά — δεν απαιτούνται δεξιότητες σχεδιασμού.',
  'ob1_pill_label'                      : 'Επαγγελματικός Δημιουργός CV',
  'ob1_chip_templates'                  : '24+ Πρότυπα',
  'ob1_chip_pdf'                        : 'Εξαγωγή PDF',
  'ob1_chip_free'                       : 'Δωρεάν Χρήση',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Πρότυπα',
  'ob2_title'                           : 'Κάθε Κλάδος.\nΚάθε Φιλοδοξία.',
  'ob2_body'                            : 'Από διατάξεις κατάλληλες για αίθουσα συνεδριάσεων έως τολμηρά δημιουργικά σχέδια — ένα πρότυπο που αφηγείται την ιστορία σας.',
  'ob2_tap_hint'                        : 'Πατήστε οποιοδήποτε πρότυπο για προεπισκόπηση',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Εταιρικό',
  'ob2_tag_creative'                    : 'Δημιουργικό',
  'ob2_tag_minimal'                     : 'Μινιμαλιστικό',
  'ob2_tag_modern'                      : 'Μοντέρνο',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Έξυπνη Διάταξη',
  'ob3_title'                           : 'Το CV σας.\nΤέλεια Οργανωμένο.',
  'ob3_body'                            : 'Η Έξυπνη Διάταξη αναδιατάσσει τις ενότητες σας για μέγιστο αντίκτυπο — τοποθετώντας το πιο δυνατό περιεχόμενο σας εκεί που κοιτούν πρώτα οι εργοδότες.',
  'ob3_badge_smart_layout'              : 'Έξυπνη Διάταξη',
  'ob3_badge_cv_ready'                  : 'CV Έτοιμο!',
  'ob3_step1_label'                     : 'Επιλέξτε Πρότυπο',
  'ob3_step1_desc'                      : 'Επιλέξτε από 24+ εντυπωσιακά σχέδια.',
  'ob3_step2_label'                     : 'Συμπληρώστε τα Στοιχεία σας',
  'ob3_step2_desc'                      : 'Καθοδηγούμενα πεδία για όλες τις ενότητες.',
  'ob3_step3_label'                     : 'Έξυπνη Διάταξη',
  'ob3_step3_desc'                      : 'Ένα άγγιγμα αναδιατάσσει τέλεια το CV σας.',
  'ob3_step4_label'                     : 'Εξαγωγή ως PDF',
  'ob3_step4_desc'                      : 'Τέλειο PDF έτοιμο για αποστολή.',
  'ob3_section_work'                    : 'Επαγγελματική Εμπειρία',
  'ob3_section_education'               : 'Εκπαίδευση',
  'ob3_section_skills'                  : 'Δεξιότητες',
  'ob3_section_references'              : 'Συστάσεις',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Έτοιμοι να Ξεκινήσετε',
  'ob4_title'                           : 'Γιατί οι Κορυφαίοι Υποψήφιοι\nΕπιλέγουν το CV Builder',
  'ob4_visual_headline'                 : 'Είστε Έτοιμοι!',
  'ob4_visual_subline'                  : 'Όλα όσα χρειάζεστε για να πάρετε τη δουλειά.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Πρότυπα',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Μέγ. CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Εξαγωγή',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Ιδιωτικό',
  'ob4_hl1_title'                       : 'Ιδιωτικό & Ασφαλές',
  'ob4_hl1_sub'                         : 'Τα δεδομένα παραμένουν στη συσκευή σας.',
  'ob4_hl2_title'                       : 'Αυτόματη Αποθήκευση',
  'ob4_hl2_sub'                         : 'Κάθε πληκτρολόγηση αποθηκεύεται αμέσως.',
  'ob4_hl3_title'                       : 'Έως 30 CV',
  'ob4_hl3_sub'                         : 'Μοναδικό CV για κάθε θέση.',
  'ob4_hl4_title'                       : 'Κοινοποίηση με Ένα Άγγιγμα',
  'ob4_hl4_sub'                         : 'Αποστολή PDF χωρίς να φύγετε από την εφαρμογή.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Ξεχωρίστε από το πλήθος',
  'home_hero_title'                     : 'Δημιουργήστε το\nΕπαγγελματικό σας CV',
  'home_hero_sub'                       : 'Δημιουργήστε ένα εντυπωσιακό βιογραφικό\nσε λίγα λεπτά',
  'home_hero_cta'                       : 'Ξεκινήστε τη Δημιουργία',
  'home_premium_soon'                   : 'Η αναβάθμιση σε Pro έρχεται σύντομα!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Πιο Πρόσφατο',
  'history_sort_alphabetical'           : 'Α–Ω',
  'history_sort_last_edited'            : 'Τελευταία Επεξεργασία',
  'history_sort_by_template'            : 'Ανά Πρότυπο',
  'history_sort_sheet_title'            : 'Ταξινόμηση Κατά',
  'history_sort_alphabetical_full'      : 'Αλφαβητικά (Α–Ω)',
  'history_premium_soon'                : 'Η αναβάθμιση σε Pro έρχεται σύντομα!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Ρυθμίσεις',
  'settings_section_preferences'        : 'Προτιμήσεις',
  'settings_section_support'            : 'Υποστήριξη',
  'settings_section_legal'              : 'Νομικά',
  'settings_section_about'              : 'Σχετικά',
  'settings_language_tile_title'        : 'Γλώσσα',
  'settings_dark_mode_title'            : 'Σκοτεινή Λειτουργία',
  'settings_dark_mode_on'               : 'Σκοτεινό θέμα ενεργοποιημένο',
  'settings_dark_mode_off'              : 'Φωτεινό θέμα ενεργοποιημένο',
  'settings_help_faq_title'             : 'Βοήθεια & Συχνές Ερωτήσεις',
  'settings_help_faq_sub'               : 'Απαντήσεις σε συνηθισμένες ερωτήσεις',
  'settings_contact_support_title'      : 'Επικοινωνία με Υποστήριξη',
  'settings_rate_app_title'             : 'Αξιολογήστε την Εφαρμογή',
  'settings_rate_app_sub'               : 'Σας αρέσει η εφαρμογή; Αφήστε μια κριτική!',
  'settings_privacy_policy_title'       : 'Πολιτική Απορρήτου',
  'settings_terms_title'                : 'Όροι Χρήσης',
  'settings_app_version_title'          : 'Έκδοση Εφαρμογής',
  'settings_email_error'                : 'Δεν ήταν δυνατό το άνοιγμα της εφαρμογής email. Στείλτε email στο cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Προεπισκόπηση CV',
  'preview_header_sub'                  : 'Έτοιμο για εξαγωγή',
  'preview_generating'                  : 'Δημιουργία του CV σας...',
  'preview_failed_title'                : 'Η Προεπισκόπηση Απέτυχε',
  'preview_failed_error'                : 'Σφάλμα: {error}',
  'preview_go_back'                     : 'Πίσω',
  'preview_no_data'                     : 'Δεν υπάρχουν διαθέσιμα δεδομένα',
  'preview_btn_print'                   : 'Εκτύπωση',
  'preview_btn_download'                : 'Λήψη & Κοινοποίηση',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Βοήθεια & Συχνές Ερωτήσεις',
  'faq_category_all'                    : 'Όλα',
  'faq_empty'                           : 'Δεν βρέθηκαν αποτελέσματα',
  'faq_contact_headline'                : 'Χρειάζεστε ακόμα βοήθεια;',
  'faq_contact_sub'                     : 'Η ομάδα μας είναι εδώ για εσάς.',
  'faq_contact_btn'                     : 'Επικοινωνία',
  'faq_email_error'                     : 'Δεν ήταν δυνατό το άνοιγμα της εφαρμογής email. Στείλτε email στο cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Ξεκινώντας',
  'faq_cat_templates'                   : 'Πρότυπα',
  'faq_cat_editing'                     : 'Επεξεργασία',
  'faq_cat_exporting'                   : 'Εξαγωγή',
  'faq_cat_data_privacy'                : 'Δεδομένα & Απόρρητο',
  'faq_cat_troubleshooting'             : 'Αντιμετώπιση Προβλημάτων',
  'faq_q1'  : 'Πώς δημιουργώ το πρώτο μου CV;',
  'faq_a1'  : 'Πατήστε το κουμπί "+" στην αρχική οθόνη για να ξεκινήσετε ένα νέο CV. Επιλέξτε ένα πρότυπο που ταιριάζει στο στιλ σας και συμπληρώστε τα προσωπικά σας στοιχεία, την εργασιακή εμπειρία, την εκπαίδευση και τις δεξιότητες βήμα προς βήμα. Η πρόοδός σας αποθηκεύεται αυτόματα.',
  'faq_q2'  : 'Μπορώ να δημιουργήσω περισσότερα από ένα CV;',
  'faq_a2'  : 'Ναι! Μπορείτε να δημιουργήσετε πολλά CV για διαφορετικούς ρόλους ή κλάδους. Κάθε CV αποθηκεύεται ξεχωριστά, ώστε να μπορείτε να τα προσαρμόζετε σε συγκεκριμένες αγγελίες εργασίας.',
  'faq_q3'  : 'Πώς αλλάζω το πρότυπο του CV μου;',
  'faq_a3'  : 'Ανοίξτε το CV σας, πατήστε το εικονίδιο προτύπου στο πάνω μέρος της οθόνης και περιηγηθείτε στα διαθέσιμα πρότυπα. Πατήστε οποιοδήποτε πρότυπο για να το προεπισκοπήσετε με το υπάρχον περιεχόμενό σας. Επιβεβαιώστε για εφαρμογή.',
  'faq_q4'  : 'Υπάρχουν δωρεάν και premium πρότυπα;',
  'faq_a4'  : 'Ναι. Μια επιλογή επαγγελματικών προτύπων είναι διαθέσιμη δωρεάν. Τα premium πρότυπα με προηγμένα σχέδια και παλέτες χρωμάτων είναι διαθέσιμα μέσω εφάπαξ αγοράς ή συνδρομής.',
  'faq_q5'  : 'Πώς προσθέτω ή αφαιρώ ενότητες;',
  'faq_a5'  : 'Στον επεξεργαστή CV, μετακινηθείτε στο κάτω μέρος της οθόνης και πατήστε "Προσθήκη Ενότητας" για να συμπεριλάβετε επιπλέον στοιχεία όπως Γλώσσες, Πιστοποιήσεις ή Εθελοντική Εργασία. Για να αφαιρέσετε μια ενότητα, πατήστε την κεφαλίδα της ενότητας και επιλέξτε "Αφαίρεση".',
  'faq_q6'  : 'Πώς αναδιατάσσω τις ενότητες;',
  'faq_a6'  : 'Πατήστε παρατεταμένα τη λαβή μεταφοράς (≡) δίπλα σε οποιαδήποτε κεφαλίδα ενότητας και σύρτε την στη θέση που προτιμάτε. Οι αλλαγές αποθηκεύονται αυτόματα.',
  'faq_q7'  : 'Πώς εξάγω το CV μου ως PDF;',
  'faq_a7'  : 'Ανοίξτε το CV σας και πατήστε το κουμπί εξαγωγής (εικονίδιο κοινοποίησης) στην επάνω δεξιά γωνία. Επιλέξτε "Εξαγωγή ως PDF". Στη συνέχεια μπορείτε να το αποθηκεύσετε στη συσκευή σας, να το κοινοποιήσετε μέσω email, WhatsApp ή να το ανεβάσετε απευθείας σε ιστοτόπους αγγελιών.',
  'faq_q8'  : 'Ποιες μορφές αρχείων υποστηρίζονται;',
  'faq_a8'  : 'Αυτή τη στιγμή η Εφαρμογή υποστηρίζει εξαγωγή του CV σας ως PDF υψηλής ποιότητας. Πρόσθετες μορφές ενδέχεται να προστεθούν σε μελλοντικές ενημερώσεις.',
  'faq_q9'  : 'Πού αποθηκεύονται τα δεδομένα του CV μου;',
  'faq_a9'  : 'Όλα τα δεδομένα του CV σας αποθηκεύονται τοπικά στη συσκευή σας. Δεν ανεβάζουμε τις προσωπικές σας πληροφορίες στους διακομιστές μας. Αυτό σημαίνει ότι τα δεδομένα σας παραμένουν ιδιωτικά και προσβάσιμα εκτός σύνδεσης.',
  'faq_q10' : 'Πώς δημιουργώ αντίγραφο ασφαλείας των CV μου;',
  'faq_a10' : 'Τα CV σας περιλαμβάνονται στο τυπικό αντίγραφο ασφαλείας της συσκευής σας (Google Drive backup σε Android, iCloud σε iOS) εάν έχετε ενεργοποιήσει το backup στις ρυθμίσεις της συσκευής σας. Μπορείτε επίσης να εξάγετε μεμονωμένα CV ως PDF για να έχετε ένα αντίγραφο.',
  'faq_q11' : 'Η εφαρμογή λειτουργεί αργά. Τι πρέπει να κάνω;',
  'faq_a11' : 'Δοκιμάστε να κλείσετε και να ανοίξετε ξανά την εφαρμογή. Εάν το πρόβλημα παραμένει, επανεκκινήστε τη συσκευή σας. Βεβαιωθείτε ότι έχετε εγκατεστημένη την πιο πρόσφατη έκδοση της εφαρμογής από το Play Store / App Store.',
  'faq_q12' : 'Το CV μου δεν εξάγεται σωστά. Τι πρέπει να κάνω;',
  'faq_a12' : 'Βεβαιωθείτε ότι έχετε αρκετό χώρο αποθήκευσης στη συσκευή σας. Δοκιμάστε να μειώσετε τις μεγάλες εικόνες στο CV σας. Εάν το πρόβλημα συνεχίζεται, επικοινωνήστε με την ομάδα υποστήριξης.',
  'faq_q13' : 'Ξέχασα να αποθηκεύσω — έχασα τη δουλειά μου;',
  'faq_a13' : 'Καθόλου! Η εφαρμογή αποθηκεύει συνεχώς την πρόοδό σας κατά την επεξεργασία.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Η καριέρα σας, τελειοποιημένη',
  'header_tooltip_back'                 : 'Πίσω',
  'header_tooltip_my_cvs'               : 'Τα CV μου',
  'header_tooltip_settings'             : 'Ρυθμίσεις',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Τα CV μου',
  'saved_count_single'                  : '{n} έγγραφο',
  'saved_count_plural'                  : '{n} έγγραφα',
  'saved_limit_reached'                 : 'Το όριο συμπληρώθηκε',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Όλα',
  'saved_filter_draft'                  : 'Πρόχειρο',
  'saved_filter_complete'               : 'Ολοκληρωμένο',
  'saved_status_complete'               : 'Ολοκληρωμένο',
  'saved_status_saved'                  : 'Αποθηκευμένο',
  'saved_status_draft'                  : 'Πρόχειρο',
  'saved_empty_title'                   : 'Δεν υπάρχουν CV εδώ ακόμα',
  'saved_empty_sub'                     : 'Ξεκινήστε να δημιουργείτε το πρώτο σας CV παραπάνω',
  'saved_search_empty_title'            : 'Δεν βρέθηκαν αποτελέσματα',
  'saved_search_empty_sub'              : 'Δοκιμάστε διαφορετικό όρο αναζήτησης',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Χρωματική Παλέτα',
  'custom_font_settings_title'          : 'Ρυθμίσεις Γραμματοσειράς',
  'custom_font_family_label'            : 'Οικογένεια Γραμματοσειράς',
  'custom_font_size_label'              : 'Μέγεθος Γραμματοσειράς: ',
  'custom_current_template_title'       : 'Τρέχον Πρότυπο',
  'custom_change_template_btn'          : 'Αλλαγή Προτύπου',
  'custom_tpl_modern'                   : 'Μοντέρνο',
  'custom_tpl_classic'                  : 'Κλασικό',
  'custom_tpl_professional'             : 'Επαγγελματικό',
  'custom_tpl_creative'                 : 'Δημιουργικό',
  'custom_tpl_minimal'                  : 'Μινιμαλιστικό',
  'custom_tpl_modern_desc'              : 'Καθαρό και σύγχρονο σχέδιο',
  'custom_tpl_classic_desc'             : 'Παραδοσιακή επαγγελματική διάταξη',
  'custom_tpl_professional_desc'        : 'Πρότυπο εστιασμένο στις επιχειρήσεις',
  'custom_tpl_creative_desc'            : 'Ξεχωρίστε με μοναδικό σχέδιο',
  'custom_tpl_minimal_desc'             : 'Απλό και κομψό στιλ',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Επιλογή Προτύπου',
  'swipe_photo_badge'                   : 'Φωτογραφία',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Πιο Δημοφιλές',
  'tpl_nordic_tag'                      : 'Καθαρό',
  'tpl_vibrant_tag'                     : 'Δημιουργικό',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Τολμηρό & αυθεντικό για ανώτερες θέσεις',
  'tpl_nordic_desc'                     : 'Μινιμαλιστική σαφήνεια που εμπιστεύονται κορυφαίες εταιρείες',
  'tpl_vibrant_desc'                    : 'Ξεχωρίστε με ενέργεια και χρώμα',
  'tpl_tech_dark_desc'                  : 'Terminal αισθητική για προγραμματιστές',
  'tpl_luxury_desc'                     : 'Χρυσές λεπτομέρειες πολυτέλειας σε μαύρο φόντο',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Πρότυπο',
  'detail_step_personal'                : 'Προσωπικά',
  'detail_step_experience'              : 'Εμπειρία',
  'detail_step_education'               : 'Εκπαίδευση',
  'detail_step_skills'                  : 'Δεξιότητες',
  'detail_step_additional'              : 'Επιπλέον',
  'detail_step_references'              : 'Συστάσεις',
  'detail_step_customize'               : 'Προσαρμογή',
  'detail_banner_heading'               : 'Σχεδόν έτοιμο!',
  'detail_banner_btn'                   : 'Συνέχεια',
  'detail_banner_completion_label'      : 'Ολοκλήρωση',
  'detail_stat_created_label'           : 'Δημιουργήθηκε',
  'detail_stat_steps_label'             : 'Βήματα ολοκλ.',
  'detail_section_template_style'       : 'Στιλ Προτύπου',
  'detail_section_steps'                : 'Βήματα',
  'detail_steps_counter'                : '{done} από {total} ολοκληρωμένα',
  'detail_step_sub'                     : 'Βήμα {n} από {total}',
  'detail_section_activity'             : 'Δραστηριότητα',
  'detail_activity_created'             : 'Δημιουργήθηκε',
  'detail_activity_last_edited'         : 'Τελευταία Επεξεργασία',
  'detail_activity_template'            : 'Πρότυπο',
  'detail_btn_continue_editing'         : 'Συνέχεια Επεξεργασίας',
  'detail_btn_edit_cv'                  : 'Επεξεργασία CV',
  'detail_option_rename'                : 'Μετονομασία CV',
  'detail_option_delete'                : 'Διαγραφή CV',
  'detail_rename_title'                 : 'Μετονομασία CV',
  'detail_rename_hint'                  : 'π.χ. CV Μηχανικού Λογισμικού',
  'detail_rename_error_empty'           : 'Το όνομα δεν μπορεί να είναι κενό',
  'detail_rename_btn_cancel'            : 'Ακύρωση',
  'detail_rename_btn_save'              : 'Αποθήκευση',
  'detail_rename_snackbar'              : 'Μετονομάστηκε σε "{name}"',
  'detail_delete_title'                 : 'Διαγραφή CV;',
  'detail_delete_body'                  : 'Αυτό θα διαγράψει οριστικά το "{name}". Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
  'detail_delete_btn_cancel'            : 'Ακύρωση',
  'detail_delete_btn_confirm'           : 'Διαγραφή',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Ολοκληρώθηκε',
  'detail_check_tile_incomplete'        : 'Δεν έχει συμπληρωθεί ακόμα',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Επιλέξτε το Πρότυπό σας',
  'chooser_subtitle'                    : 'Σύρετε για περιήγηση  ·  Πατήστε για επιλογή  ·  Κρατήστε για προεπισκόπηση',
  'chooser_card_hold_hint'              : 'Κρατήστε για προεπισκόπηση',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Επιλεγμένο',
  'chooser_modal_heading'               : 'Ονομάστε το CV σας',
  'chooser_modal_sub'                   : 'Δώστε του ένα όνομα ώστε να το βρίσκετε εύκολα στα CV μου και στο Ιστορικό.',
  'chooser_modal_field_label'           : 'Όνομα CV',
  'chooser_modal_save_btn'              : 'Αποθήκευση & Έναρξη Δημιουργίας',
  'chooser_modal_divider'               : 'ή συνεχίστε ένα υπάρχον CV',
  'chooser_nav_selected_sub'            : 'Επιλεγμένο πρότυπο',
  'chooser_nav_cta'                     : 'Αποθήκευση & Συνέχεια',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Επιτεύχθηκε το Μέγιστο Πλήθος Καταχωρήσεων',
  'editor_show_hide'                    : 'Εμφάνιση/Απόκρυψη',
  'editor_editing_badge'                : 'Επεξεργασία',
  'editor_field_required'               : 'Υποχρεωτικό',
  'editor_tooltip_edit'                 : 'Επεξεργασία',
  'editor_tooltip_delete'               : 'Διαγραφή',
  'editor_date_start'                   : 'Ημερομηνία Έναρξης *',
  'editor_date_end'                     : 'Ημερομηνία Λήξης *',
  'editor_date_tap_hint'                : 'Πατήστε για επιλογή',
  'editor_date_dialog_title'            : 'Επιλογή Μήνα & Έτους',
  'editor_date_confirm'                 : 'Επιβεβαίωση',
  'editor_panel_hide'                   : 'Απόκρυψη',
  'editor_panel_show'                   : 'Εμφάνιση',
  'editor_validator_max_chars'          : 'Μέγ. {n} χαρακτήρες',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Δημιουργία CV',
  'editor_header_step_sub'              : 'Βήμα {current} από {total} · {label}',
  'editor_step_template'                : 'Πρότυπο',
  'editor_step_personal'                : 'Προσωπικά',
  'editor_step_experience'              : 'Εμπειρία',
  'editor_step_education'               : 'Εκπαίδευση',
  'editor_step_skills'                  : 'Δεξιότητες',
  'editor_step_additional'              : 'Επιπλέον',
  'editor_step_references'              : 'Συστάσεις',
  'editor_step_customize'               : 'Προσαρμογή',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Προσαρμογή',
  'customize_subtitle'                  : 'Κάντε το CV σας μοναδικά δικό σας',
  'customize_smart_layout_btn'          : 'Έξυπνη Διάταξη',
  'customize_back_to_top'               : 'Πίσω στην Κορυφή',
  'customize_done_title'                : 'Είστε έτοιμοι!',
  'customize_done_sub'                  : 'Πατήστε Προεπισκόπηση CV παρακάτω για να δείτε το ολοκληρωμένο CV σας',
  'customize_preview_btn'               : 'Προεπισκόπηση CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Χρωματική Παλέτα',
  'color_black'                         : 'Μαύρο',
  'color_blue'                          : 'Μπλε',
  'color_nordic_blue'                   : 'Σκανδιναβικό Μπλε',
  'color_indigo'                        : 'Ινδικό Μπλε',
  'color_teal'                          : 'Τιρκουάζ',
  'color_green'                         : 'Πράσινο',
  'color_purple'                        : 'Μωβ',
  'color_orange'                        : 'Πορτοκαλί',
  'color_red'                           : 'Κόκκινο',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'Λευκό',
  'color_white_bg'                      : 'Λευκό Φόντο',
  'color_maroon'                        : 'Σκούρο Κόκκινο',
  'color_brutalist_yellow'              : 'Brutalist Yellow',
  'color_neon_blue'                     : 'Νέον Μπλε',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'Ανοιχτό Γκρι',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Οικογένεια Γραμματοσειράς',
  'customize_font_picker_title'         : 'Επιλογή Γραμματοσειράς',
  'customize_font_picker_sub'           : 'Κάθε γραμματοσειρά προεπισκοπείται στο δικό της τυπογραφικό στιλ',
  'customize_font_preview_sample'       : 'Η γρήγορη καφέ αλεπού',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Μέγεθος Γραμματοσειράς',
  'customize_font_size_label'           : 'Μέγεθος Κειμένου',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Μέγεθος Εικόνας',
  'customize_image_size_label'          : 'Μέγεθος Εικόνας',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Ζωντανή Προεπισκόπηση',
  'preview_page_count_singular'         : '1 σελίδα',
  'preview_page_count_plural'           : '{n} σελίδες',
  'preview_page_of'                     : 'Σελίδα {page} από {total}',
  'preview_live_hint'                   : 'Οι αλλαγές εφαρμόζονται αμέσως',
  'preview_template_unregistered'       : 'Δεν έχει εγγραφεί ακόμα στο customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Προετοιμασία του CV σας…',
  'preview_bar_print'                   : 'Εκτύπωση',
  'preview_bar_save_pdf'                : 'Αποθήκευση ως PDF',
  'preview_bar_share'                   : 'Κοινοποίηση',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Προεπισκόπηση CV',
  'preview_screen_sub'                  : '{n} {unit} · ακριβώς όπως εκτυπώνεται',
  'preview_page_singular'               : 'σελίδα',
  'preview_page_plural'                 : 'σελίδες',
  'preview_pdf_filename'                : 'CV_μου',
  'preview_share_subject'               : 'Το CV μου',
  'preview_snack_print_failed'          : 'Αποτυχία εκτύπωσης: {e}',
  'preview_snack_saved'                 : 'Το CV αποθηκεύτηκε στις Λήψεις ✓',
  'preview_snack_export_failed'         : 'Αποτυχία εξαγωγής: {e}',
  'preview_snack_share_failed'          : 'Αποτυχία κοινοποίησης: {e}',
  'preview_template_not_registered'     : 'Το πρότυπο δεν είναι εγγεγραμμένο',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Κλείσιμο προεπισκόπησης',
  'preview_modal_hint_photo'            : 'Υποστηρίζει φωτογραφία προφίλ  ·  Πατήστε κάρτα για επιλογή',
  'preview_modal_hint_no_photo'         : 'Πατήστε μια κάρτα προτύπου για να την επιλέξετε',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Το CV μου',
  'time_just_now'                       : 'Μόλις τώρα',
  'time_minutes_ago'                    : 'πριν {n} λεπτά',
  'time_hours_ago'                      : 'πριν {n} ώρες',
  'time_yesterday'                      : 'Χθες',
  'time_days_ago'                       : 'πριν {n} ημέρες',
  'time_one_week_ago'                   : 'πριν 1 εβδομάδα',
  'time_weeks_ago'                      : 'πριν {n} εβδομάδες',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Κομψό',
  'tpl_tag_classic'                     : 'Κλασικό',
  'tpl_tag_minimal'                     : 'Μινιμαλιστικό',
  'tpl_tag_creative'                    : 'Δημιουργικό',
  'tpl_tag_bold'                        : 'Τολμηρό',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Κάρτες με κλίση από τιρκουάζ σε βιολετί',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Στιλ περιοδικού, κόκκινο & κρεμ',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'Λεβάντα sidebar, απαλές κάρτες',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Ακατέργαστο πλέγμα, έντονα πλαίσια & κίτρινο',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Πράσινο δάσους με χρονολόγιο',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Σκοτεινό φόντο με κυκλικά γραφήματα',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Γεωμετρική χρυσή πολυτέλεια της δεκαετίας του 1920',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Σκοτεινό infographic με κυκλικά γραφήματα',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Σκοτεινό sidebar με πορτοκαλί τόνο',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Καθαρό μινιμαλιστικό, απαλές γκρι αποχρώσεις',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Ζεστοί μπεζ κομψοί τόνοι',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Έντονο μαύρο & άσπρο κλασικό',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Κλασική διάταξη φιλική προς ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Σκοτεινό πορτοκαλί infographic στιλ',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Τεχνικό σχέδιο σε πλέγμα',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Κλασική διάταξη δύο στηλών με ετικέτες',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Σκιασμένες κεφαλίδες με διαμαντένιους οδηγούς',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Κεντραρισμένες κεφαλίδες, έντονες εταιρείες',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Τολμηρό όνομα, κουκκίδες χρονολογίου & επιτεύγματα',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Προσωπικά Στοιχεία',
  'personal_subtitle'                   : 'Πείτε στους εργοδότες ποιοι είστε',
  'personal_profile_counter'            : '{n}/{max} προφίλ',
  'personal_info_banner'                : 'Αποθηκεύστε έως 5 προφίλ και επιλέξτε ένα ανά CV. Η επιλογή σας αποθηκεύεται χωριστά για κάθε CV.',
  'personal_snack_max'                  : 'Επιτεύχθηκε το μέγιστο των {n} προφίλ.',
  'personal_add_btn'                    : 'Προσθήκη Νέου Προφίλ',
  'personal_library_title'              : 'Αποθηκευμένα Προφίλ',
  'personal_selected_one'               : '1 επιλεγμένο',
  'personal_selected_none'              : 'κανένα επιλεγμένο',
  'personal_library_hint'               : 'Πατήστε μια κάρτα για να την επιλέξετε μόνο για αυτό το CV. Τα άλλα CV διατηρούν τις δικές τους ανεξάρτητες επιλογές.',
  'personal_empty_message'              : 'Δεν έχουν αποθηκευτεί προφίλ ακόμα',
  'personal_empty_sub'                  : 'Πατήστε παραπάνω για να προσθέσετε τα προσωπικά σας στοιχεία',
  'personal_nav_next'                   : 'Αποθήκευση & Συνέχεια',
  'personal_card_active_badge'          : 'Ενεργό για αυτό το CV',
  'personal_sheet_title_add'            : 'Νέο Προφίλ',
  'personal_sheet_title_edit'           : 'Επεξεργασία Προφίλ',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Το πρότυπο Brutalist έχει συμπαγή πεδία επαφής. Συντομότερες τιμές (π.χ. μόνο πόλη) εμφανίζονται καλύτερα.',
  'personal_section_photo'              : 'Φωτογραφία Προφίλ',
  'personal_section_basic'              : 'Βασικά Στοιχεία',
  'personal_section_contact'            : 'Επικοινωνία',
  'personal_section_online'             : 'Διαδικτυακή Παρουσία',
  'personal_section_summary'            : 'Επαγγελματική Περίληψη',
  'personal_field_first_name'           : 'Όνομα *',
  'personal_field_last_name'            : 'Επώνυμο',
  'personal_field_job_title'            : 'Επαγγελματικός Τίτλος *',
  'personal_field_email'                : 'Διεύθυνση Email *',
  'personal_field_phone'                : 'Αριθμός Τηλεφώνου *',
  'personal_field_location'             : 'Τοποθεσία',
  'personal_field_location_brut'        : 'Τοποθεσία (μόνο πόλη)',
  'personal_field_website'              : 'Ιστοσελίδα / Portfolio',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'π.χ. Μαρία',
  'personal_hint_last_name'             : 'π.χ. Παπαδοπούλου',
  'personal_hint_job_title'             : 'π.χ. Ανώτερος Μηχανικός',
  'personal_hint_email'                 : 'π.χ. maria@example.com',
  'personal_hint_phone'                 : 'π.χ. +30 210 123 4567',
  'personal_hint_location'              : 'π.χ. Αθήνα, Ελλάδα',
  'personal_hint_location_brut'         : 'π.χ. Αθήνα',
  'personal_hint_website'               : 'π.χ. github.com/mariapapadopoulou',
  'personal_hint_website_brut'          : 'π.χ. github.com/maria',
  'personal_hint_linkedin'              : 'π.χ. linkedin.com/in/mariapapadopoulou',
  'personal_hint_linkedin_brut'         : 'π.χ. linkedin.com/in/maria',
  'personal_summary_hint_label'         : 'Κρατήστε το συνοπτικό — εμφανίζεται στην κορυφή του CV σας.',
  'personal_hint_summary'               : 'Μια σύντομη περίληψη 2–3 προτάσεων για το υπόβαθρο και τους στόχους σας...',
  'personal_validator_email'            : 'Εισάγετε έγκυρο email',
  'personal_field_char_limit_tooltip'   : 'Επιτεύχθηκε το όριο χαρακτήρων',
  'personal_sheet_btn_save'             : 'Αποθήκευση Προφίλ',
  'personal_sheet_btn_update'           : 'Αποθήκευση Αλλαγών',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Επιλογή Φωτογραφίας',
  'photo_option_gallery'                : 'Επιλογή από Γκαλερί',
  'photo_option_camera'                 : 'Λήψη Φωτογραφίας',
  'photo_option_reposition'             : 'Αλλαγή Θέσης Φωτογραφίας',
  'photo_option_remove'                 : 'Αφαίρεση Φωτογραφίας',
  'photo_status_added'                  : 'Η φωτογραφία προστέθηκε ✓',
  'photo_status_empty'                  : 'Προσθέστε επαγγελματική φωτογραφία',
  'photo_chip_gallery'                  : 'Γκαλερί',
  'photo_chip_camera'                   : 'Κάμερα',
  'photo_chip_reposition'               : 'Αλλαγή θέσης',
  'photo_reposition_title'              : 'Αλλαγή Θέσης Φωτογραφίας',
  'photo_reposition_sub'                : 'Σύρετε τη φωτογραφία για να προσαρμόσετε τη θέση',
  'photo_reposition_reset'              : 'Επαναφορά στο κέντρο',
  'photo_reposition_apply'              : 'Εφαρμογή',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Δεξιότητες',
  'skills_subtitle'                     : 'Αναδείξτε τις βασικές σας ικανότητες',
  'skills_add_btn'                      : 'Προσθήκη Νέας Δεξιότητας',
  'skills_snack_max_icons'              : 'Επιτεύχθηκε το μέγιστο των 10 εικονιδίων.',
  'skills_snack_max_skills'             : 'Επιτεύχθηκε το μέγιστο των 15 δεξιοτήτων.',
  'skills_library_title'                : 'Αποθηκευμένες Δεξιότητες',
  'skills_library_hint'                 : 'Οι επιλεγμένες δεξιότητες συμπεριλαμβάνονται σε αυτό το CV. Οι επιλογές σας αποθηκεύονται αυτόματα.',
  'skills_nav_next'                     : 'Συνέχεια στα Επιπλέον',
  'skills_wina_header_icon_bar'         : 'Μπάρα Εικονιδίων Κεφαλίδας',
  'skills_wina_on'                      : 'ΕΝΕΡΓΟ',
  'skills_wina_off'                     : 'ΑΝΕΝΕΡΓΟ',
  'skills_wina_bar_on_sub'              : 'Έγχρωμοι κύκλοι εικονιδίων εμφανίζονται στην κεφαλίδα του CV.',
  'skills_wina_bar_off_sub'             : 'Η γραμμή εικονιδίων είναι κρυφή — περισσότερος χώρος για στοιχεία επαφής.',
  'skills_wina_palette_hint'            : 'Τα εικονίδια εμφανίζονται ως έγχρωμοι κύκλοι με τη σειρά της παλέτας.',
  'skills_wina_preview_label'           : 'Προεπισκόπηση',
  'skills_wina_disabled_hint'           : 'Ενεργοποιήστε τη μπάρα εικονιδίων παραπάνω για να επιλέξετε ποια εικονίδια εμφανίζονται στην κεφαλίδα του CV.',
  'skills_sheet_title_add'              : 'Προσθήκη Δεξιότητας',
  'skills_sheet_title_edit'             : 'Επεξεργασία Δεξιότητας',
  'skills_sheet_field_name'             : 'Όνομα Δεξιότητας *',
  'skills_sheet_hint_short'             : 'π.χ. Flutter, Σχεδιασμός',
  'skills_sheet_hint_long'              : 'π.χ. Flutter, Διαχείριση Έργου',
  'skills_sheet_validator_max'          : 'Μέγ. {n} χαρακτήρες',
  'skills_sheet_proficiency'            : 'Επίπεδο Επάρκειας',
  'skills_sheet_beginner'               : 'Αρχάριος',
  'skills_sheet_expert'                 : 'Ειδικός',
  'skills_sheet_btn_save'               : 'Αποθήκευση Δεξιότητας',
  'skills_sheet_btn_update'             : 'Ενημέρωση Δεξιότητας',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Προσωπικές Συστάσεις',
  'refs_subtitle'                       : 'Άτομα που μπορούν να σας συστήσουν προσωπικά',
  'refs_add_btn'                        : 'Προσθήκη Νέας Προσωπικής Σύστασης',
  'refs_snack_max_selected'             : 'Μπορείτε να επιλέξετε έως 4 συστάσεις για ένα CV.',
  'refs_snack_max_saved'                : 'Επιτεύχθηκε το μέγιστο των 10 αποθηκευμένων συστάσεων.',
  'refs_library_title'                  : 'Αποθηκευμένες Συστάσεις',
  'refs_library_hint'                   : 'Οι επιλεγμένες συστάσεις συμπεριλαμβάνονται σε αυτό το CV. Μέγ. 4 ανά CV. Οι επιλογές σας αποθηκεύονται αυτόματα.',
  'refs_nav_next'                       : 'Συνέχεια στην Προσαρμογή',
  'refs_sheet_title_add'                : 'Προσθήκη Προσωπικής Σύστασης',
  'refs_sheet_title_edit'               : 'Επεξεργασία Προσωπικής Σύστασης',
  'refs_sheet_sub_add'                  : 'Κάποιος που μπορεί να σας συστήσει προσωπικά σε εργοδότες.',
  'refs_sheet_sub_edit'                 : 'Ενημερώστε τα στοιχεία αυτής της σύστασης παρακάτω.',
  'refs_sheet_field_name'               : 'Πλήρες Όνομα *',
  'refs_sheet_field_title'              : 'Επαγγελματικός Τίτλος *',
  'refs_sheet_field_company'            : 'Εταιρεία (προαιρετικό)',
  'refs_sheet_field_email'              : 'Διεύθυνση Email *',
  'refs_sheet_field_phone'              : 'Αριθμός Τηλεφώνου *',
  'refs_sheet_hint_name'                : 'π.χ. Γιώργος Παπαδόπουλος',
  'refs_sheet_hint_title'               : 'π.χ. Διευθυντής Μηχανικής',
  'refs_sheet_hint_company'             : 'π.χ. Acme Corp',
  'refs_sheet_hint_email'               : 'π.χ. giorgos@acme.com',
  'refs_sheet_hint_phone'               : 'π.χ. +30 210 123 4567',
  'refs_sheet_validator_email'          : 'Εισάγετε έγκυρη διεύθυνση email',
  'refs_sheet_btn_save'                 : 'Αποθήκευση Προσωπικής Σύστασης',
  'refs_sheet_btn_update'               : 'Ενημέρωση Προσωπικής Σύστασης',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Επαγγελματική Εμπειρία',
  'exp_subtitle'                        : 'Προσθέστε το επαγγελματικό σας ιστορικό',
  'exp_banner_info'                     : 'Έως {n} αρμοδιότητες ανά ρόλο θα εμφανιστούν στο CV. 3–6 ρόλοι συνήθως χωρούν σε 1–2 σελίδες.',
  'exp_add_btn'                         : 'Προσθήκη Νέας Εμπειρίας',
  'exp_snack_max_selected'              : 'Μπορείτε να επιλέξετε έως 8 εμπειρίες για ένα CV.',
  'exp_snack_max_saved'                 : 'Επιτεύχθηκε το μέγιστο των 12 αποθηκευμένων εμπειριών.',
  'exp_library_title'                   : 'Αποθηκευμένες Εμπειρίες',
  'exp_library_hint'                    : 'Οι επιλεγμένες καταχωρήσεις συμπεριλαμβάνονται μόνο σε αυτό το CV. Τα άλλα CV διατηρούν τις δικές τους ανεξάρτητες επιλογές.',
  'exp_nav_next'                        : 'Συνέχεια στην Εκπαίδευση',
  'exp_empty_message'                   : 'Δεν έχει προστεθεί εμπειρία ακόμα',
  'exp_empty_sub'                       : 'Πατήστε παραπάνω για να προσθέσετε τον πρώτο σας ρόλο',
  'exp_card_resp_singular'              : 'αρμοδιότητα',
  'exp_card_resp_plural'                : 'αρμοδιότητες',
  'exp_card_resp_tooltip'               : 'Μόνο οι πρώτες 8 αρμοδιότητες θα εμφανιστούν στο CV',
  'exp_sheet_title_add'                 : 'Προσθήκη Εμπειρίας',
  'exp_sheet_title_edit'                : 'Επεξεργασία Εμπειρίας',
  'exp_sheet_field_job_title'           : 'Επαγγελματικός Τίτλος *',
  'exp_sheet_field_company'             : 'Εταιρεία *',
  'exp_sheet_field_location'            : 'Τοποθεσία',
  'exp_sheet_section_responsibilities'  : 'Βασικές Αρμοδιότητες',
  'exp_sheet_resp_hint_info'            : 'Μέγ. 8 bullet points · 200 χαρακτήρες κάθε',
  'exp_sheet_resp_label'                : 'Αρμοδιότητα {n}',
  'exp_sheet_resp_hint'                 : 'π.χ. Διηύθυνα ομάδα 5 μηχανικών',
  'exp_sheet_resp_add_btn'              : 'Προσθήκη Αρμοδιότητας',
  'exp_sheet_resp_max_info'             : 'Επιτεύχθηκε το μέγιστο {n} αρμοδιοτήτων',
  'exp_sheet_resp_validator_max'        : 'Μέγ. 200 χαρακτήρες',
  'exp_sheet_hint_job_title'            : 'π.χ. Ανώτερος Προγραμματιστής',
  'exp_sheet_hint_location'             : 'π.χ. Αθήνα, Ελλάδα',
  'exp_sheet_btn_save'                  : 'Αποθήκευση Εμπειρίας',
  'exp_sheet_btn_update'                : 'Αποθήκευση Αλλαγών',
  'exp_date_present'                    : 'Παρόν / Τρέχουσα Θέση',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Εκπαίδευση',
  'edu_subtitle'                        : 'Προσθέστε το ακαδημαϊκό σας υπόβαθρο',
  'edu_add_btn'                         : 'Προσθήκη Νέας Εκπαίδευσης',
  'edu_snack_max_selected'              : 'Μπορείτε να επιλέξετε έως 8 εκπαιδευτικές καταχωρήσεις για ένα CV.',
  'edu_snack_max_saved'                 : 'Επιτεύχθηκε το μέγιστο των 12 αποθηκευμένων εκπαιδευτικών καταχωρήσεων.',
  'edu_library_title'                   : 'Αποθηκευμένη Εκπαίδευση',
  'edu_library_hint'                    : 'Οι επιλεγμένες καταχωρήσεις συμπεριλαμβάνονται σε αυτό το CV. Οι επιλογές σας αποθηκεύονται αυτόματα.',
  'edu_nav_next'                        : 'Συνέχεια στις Δεξιότητες',
  'edu_empty_message'                   : 'Δεν έχει προστεθεί εκπαίδευση ακόμα',
  'edu_empty_sub'                       : 'Πατήστε παραπάνω για να προσθέσετε τα προσόντα σας',
  'edu_card_bullet_singular'            : 'bullet point',
  'edu_card_bullet_plural'              : 'bullet points',
  'edu_sheet_title_add'                 : 'Προσθήκη Εκπαίδευσης',
  'edu_sheet_title_edit'                : 'Επεξεργασία Εκπαίδευσης',
  'edu_sheet_field_degree'              : 'Τίτλος / Πτυχίο *',
  'edu_sheet_field_institution'         : 'Ίδρυμα *',
  'edu_sheet_section_key_points'        : 'Βασικά Σημεία',
  'edu_sheet_key_points_hint_info'      : 'Προαιρετικό · 1 bullet point · μέγ. 100 χαρακτήρες',
  'edu_sheet_point_label'               : 'Σημείο {n}',
  'edu_sheet_point_add_btn'             : 'Προσθήκη Bullet Point',
  'edu_sheet_point_max_info'            : 'Επιτεύχθηκε το μέγιστο {n} bullet points',
  'edu_sheet_point_validator_max'       : 'Μέγ. {n} χαρακτήρες',
  'edu_sheet_hint_degree'               : 'π.χ. Πτυχίο Πληροφορικής',
  'edu_sheet_hint_institution'          : 'π.χ. Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών',
  'edu_sheet_hint_bullet'               : 'π.χ. Άριστα',
  'edu_sheet_btn_save'                  : 'Αποθήκευση Εκπαίδευσης',
  'edu_sheet_btn_update'                : 'Αποθήκευση Αλλαγών',
  'edu_date_present'                    : 'Παρόν / Σπουδές σε Εξέλιξη',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Επιπλέον Πληροφορίες',
  'additional_subtitle'                 : 'Πιστοποιήσεις, γλώσσες & άλλα',
  'additional_cert_section_title'       : 'Πιστοποιήσεις',
  'additional_cert_counter'             : '{sel}/{total} επιλεγμένες · μέγ. {max}',
  'additional_cert_hide'                : 'Απόκρυψη',
  'additional_cert_show'                : 'Εμφάνιση',
  'additional_cert_add_btn'             : 'Προσθήκη',
  'additional_cert_snack_max'           : 'Επιτεύχθηκε το μέγιστο των {n} πιστοποιήσεων.',
  'additional_cert_hint'                : 'Οι επιλεγμένες καταχωρήσεις συμπεριλαμβάνονται σε αυτό το CV. Οι επιλογές σας αποθηκεύονται αυτόματα.',
  'additional_cert_empty'               : 'Δεν έχουν προστεθεί πιστοποιήσεις ακόμα',
  'additional_lang_section_title'       : 'Γλώσσες',
  'additional_lang_add_hint'            : 'π.χ. Ισπανικά',
  'additional_lang_snack_max'           : 'Επιτεύχθηκε το μέγιστο των {n} γλωσσών.',
  'additional_lang_empty'               : 'Δεν έχουν προστεθεί γλώσσες ακόμα',
  'additional_hobby_section_title'      : 'Χόμπι & Ενδιαφέροντα',
  'additional_hobby_add_hint'           : 'π.χ. Φωτογραφία',
  'additional_hobby_snack_max'          : 'Επιτεύχθηκε το μέγιστο των {n} χόμπι.',
  'additional_hobby_empty'              : 'Δεν έχουν προστεθεί χόμπι ακόμα',
  'additional_section_hint'             : 'Οι επιλεγμένες καταχωρήσεις συμπεριλαμβάνονται σε αυτό το CV. Οι επιλογές σας αποθηκεύονται αυτόματα.',
  'additional_nav_next'                 : 'Συνέχεια στις Συστάσεις',
  'cert_sheet_title_add'                : 'Προσθήκη Πιστοποίησης',
  'cert_sheet_title_edit'               : 'Επεξεργασία Πιστοποίησης',
  'cert_sheet_sub'                      : 'Προσθέστε ένα προσόν, πιστοποιητικό ή επαγγελματική πιστοποίηση.',
  'cert_sheet_field_name'               : 'Όνομα Πιστοποίησης *',
  'cert_sheet_field_issued_by'          : 'Εκδόθηκε Από (προαιρετικό)',
  'cert_sheet_field_short_desc'         : 'Σύντομη Περιγραφή (προαιρετικό)',
  'cert_sheet_hint_name'                : 'π.χ. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'π.χ. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'π.χ. Αποκτήθηκε 2024',
  'cert_sheet_btn_save'                 : 'Αποθήκευση Πιστοποίησης',
  'cert_sheet_btn_update'               : 'Ενημέρωση Πιστοποίησης',
  'simple_sheet_title_add_language'     : 'Προσθήκη Γλώσσας',
  'simple_sheet_title_edit_language'    : 'Επεξεργασία Γλώσσας',
  'simple_sheet_title_add_hobby'        : 'Προσθήκη Χόμπι',
  'simple_sheet_title_edit_hobby'       : 'Επεξεργασία Χόμπι',
  'simple_sheet_btn_save'               : 'Αποθήκευση',
  'simple_sheet_btn_update'             : 'Ενημέρωση',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Επικοινωνία',
  'pdf_section_about_me'                : 'Σχετικά με Εμένα',
  'pdf_section_summary'                 : 'Περίληψη',
  'pdf_section_summary_short'           : 'Περίληψη',
  'pdf_section_profile'                 : 'Προφίλ',
  'pdf_section_experience'              : 'Εμπειρία',
  'pdf_section_experience_short'        : 'Εμπειρία',
  'pdf_section_education'               : 'Εκπαίδευση',
  'pdf_section_skills'                  : 'Δεξιότητες',
  'pdf_section_languages'               : 'Γλώσσες',
  'pdf_label_email'                     : 'Email',
  'pdf_label_phone'                     : 'Τηλέφωνο',
  'pdf_label_location'                  : 'Τοποθεσία',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Επιτεύχθηκε το Όριο CV',
  'limit_dialog_body'                   : 'Έχετε φτάσει το μέγιστο των 30 CV. Διαγράψτε ένα υπάρχον CV πριν δημιουργήσετε ένα νέο.',
  'limit_dialog_go_to_my_cvs'           : 'Μετάβαση στα CV μου',
  'limit_dialog_cancel'                 : 'Ακύρωση',
  'refs_count_summary'                  : '{checked}/{maxChecked} επιλεγμένες · {saved}/{maxSaved} αποθηκευμένες',
  'refs_selected_badge'                 : '{n} επιλεγμένες',
  'refs_empty_message'                  : 'Δεν έχουν αποθηκευτεί συστάσεις ακόμα',
  'refs_empty_sub'                      : 'Πατήστε παραπάνω για να προσθέσετε μια προσωπική σύσταση',
};