// lib/language_keys/lang_fa_persian.dart
//
// Persian (Farsi) — translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> faPersian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'زبانی یافت نشد',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'رد کردن',
  'onboarding_next'                     : 'بعدی',
  'onboarding_get_started'              : 'شروع کنید',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  خوش آمدید',
  'ob1_title'                           : 'رزومه‌ای بسازید که\nدرها را باز کند',
  'ob1_body'                            : 'از میان صدها متقاضی متمایز شوید. در چند دقیقه یک رزومه حرفه‌ای و برنده بسازید — بدون نیاز به مهارت طراحی.',
  'ob1_pill_label'                      : 'سازنده رزومه حرفه‌ای',
  'ob1_chip_templates'                  : '۲۴+ قالب',
  'ob1_chip_pdf'                        : 'خروجی PDF',
  'ob1_chip_free'                       : 'رایگان',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  قالب‌ها',
  'ob2_title'                           : 'هر صنعت.\nهر هدف.',
  'ob2_body'                            : 'از طرح‌های آماده برای جلسات هیئت مدیره تا طراحی‌های خلاق و جسورانه — قالبی که داستان شما را روایت می‌کند.',
  'ob2_tap_hint'                        : 'روی هر قالب ضربه بزنید تا پیش‌نمایش ببینید',
  'ob2_tpl_executive'                   : 'مدیریتی',
  'ob2_tpl_vibrant'                     : 'پرانرژی',
  'ob2_tpl_nordic'                      : 'نوردیک',
  'ob2_tpl_tech_dark'                   : 'تک دارک',
  'ob2_tpl_luxury'                      : 'لوکس',
  'ob2_tag_corporate'                   : 'سازمانی',
  'ob2_tag_creative'                    : 'خلاق',
  'ob2_tag_minimal'                     : 'مینیمال',
  'ob2_tag_modern'                      : 'مدرن',
  'ob2_tag_premium'                     : 'ویژه',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  چیدمان هوشمند',
  'ob3_title'                           : 'رزومه شما.\nمرتب‌شده.',
  'ob3_body'                            : 'چیدمان هوشمند بخش‌های رزومه شما را برای بیشترین تأثیر مرتب می‌کند — قوی‌ترین محتوا را جایی قرار می‌دهد که کارفرماها اول نگاه می‌کنند.',
  'ob3_badge_smart_layout'              : 'چیدمان هوشمند',
  'ob3_badge_cv_ready'                  : 'رزومه آماده است!',
  'ob3_step1_label'                     : 'انتخاب قالب',
  'ob3_step1_desc'                      : 'از ۲۴+ طرح زیبا انتخاب کنید.',
  'ob3_step2_label'                     : 'تکمیل اطلاعات',
  'ob3_step2_desc'                      : 'فیلدهای راهنما برای تمام بخش‌ها.',
  'ob3_step3_label'                     : 'چیدمان هوشمند',
  'ob3_step3_desc'                      : 'با یک ضربه رزومه شما کامل می‌شود.',
  'ob3_step4_label'                     : 'خروجی PDF',
  'ob3_step4_desc'                      : 'PDF با کیفیت بالا آماده ارسال.',
  'ob3_section_work'                    : 'سابقه کاری',
  'ob3_section_education'               : 'تحصیلات',
  'ob3_section_skills'                  : 'مهارت‌ها',
  'ob3_section_references'              : 'معرف‌ها',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  آماده شروع',
  'ob4_title'                           : 'چرا داوطلبان برتر\nسازنده رزومه را انتخاب می‌کنند',
  'ob4_visual_headline'                 : 'همه چیز آماده است!',
  'ob4_visual_subline'                  : 'هر آنچه برای گرفتن شغل نیاز دارید.',
  'ob4_stat_templates_value'            : '۲۴+',
  'ob4_stat_templates_label'            : 'قالب',
  'ob4_stat_max_cvs_value'              : '۳۰',
  'ob4_stat_max_cvs_label'              : 'حداکثر رزومه',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'خروجی',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'خصوصی',
  'ob4_hl1_title'                       : 'خصوصی و ایمن',
  'ob4_hl1_sub'                         : 'داده‌ها روی دستگاه شما می‌مانند.',
  'ob4_hl2_title'                       : 'ذخیره خودکار',
  'ob4_hl2_sub'                         : 'هر چیزی که تایپ می‌کنید فوری ذخیره می‌شود.',
  'ob4_hl3_title'                       : 'تا ۳۰ رزومه',
  'ob4_hl3_sub'                         : 'رزومه منحصربه‌فرد برای هر موقعیت.',
  'ob4_hl4_title'                       : 'اشتراک‌گذاری با یک ضربه',
  'ob4_hl4_sub'                         : 'بدون خروج از برنامه PDF بفرستید.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ از جمعیت متمایز شوید',
  'home_hero_title'                     : 'رزومه حرفه‌ای\nخود را بسازید',
  'home_hero_sub'                       : 'در چند دقیقه یک رزومه\nچشمگیر بسازید',
  'home_hero_cta'                       : 'شروع ساخت',
  'home_premium_soon'                   : 'ارتقا به نسخه Pro به زودی!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'جدیدترین',
  'history_sort_alphabetical'           : 'الف–ی',
  'history_sort_last_edited'            : 'آخرین ویرایش',
  'history_sort_by_template'            : 'بر اساس قالب',
  'history_sort_sheet_title'            : 'مرتب‌سازی بر اساس',
  'history_sort_alphabetical_full'      : 'الفبایی (الف–ی)',
  'history_premium_soon'                : 'ارتقا به نسخه Pro به زودی!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'تنظیمات',
  'settings_section_preferences'        : 'ترجیحات',
  'settings_section_support'            : 'پشتیبانی',
  'settings_section_legal'              : 'قانونی',
  'settings_section_about'              : 'درباره',
  'settings_language_tile_title'        : 'زبان',
  'settings_dark_mode_title'            : 'حالت تاریک',
  'settings_dark_mode_on'               : 'تم تاریک فعال است',
  'settings_dark_mode_off'              : 'تم روشن فعال است',
  'settings_help_faq_title'             : 'راهنما و سؤالات متداول',
  'settings_help_faq_sub'               : 'پاسخ به سؤالات رایج',
  'settings_contact_support_title'      : 'تماس با پشتیبانی',
  'settings_rate_app_title'             : 'امتیاز دهید',
  'settings_rate_app_sub'               : 'از برنامه لذت می‌برید؟ نظر بدهید!',
  'settings_privacy_policy_title'       : 'سیاست حریم خصوصی',
  'settings_terms_title'                : 'شرایط خدمات',
  'settings_app_version_title'          : 'نسخه برنامه',
  'settings_email_error'                : 'نمی‌توان برنامه ایمیل را باز کرد. لطفاً به cyberinc101@gmail.com ایمیل بزنید',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'پیش‌نمایش رزومه',
  'preview_header_sub'                  : 'آماده برای خروجی',
  'preview_generating'                  : 'در حال ساخت رزومه...',
  'preview_failed_title'                : 'پیش‌نمایش ناموفق بود',
  'preview_failed_error'                : 'خطا: {error}',
  'preview_go_back'                     : 'بازگشت',
  'preview_no_data'                     : 'داده‌ای موجود نیست',
  'preview_btn_print'                   : 'چاپ',
  'preview_btn_download'                : 'دانلود و اشتراک‌گذاری',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'راهنما و سؤالات متداول',
  'faq_category_all'                    : 'همه',
  'faq_empty'                           : 'نتیجه‌ای یافت نشد',
  'faq_contact_headline'                : 'هنوز به کمک نیاز دارید؟',
  'faq_contact_sub'                     : 'تیم ما آماده کمک به شماست.',
  'faq_contact_btn'                     : 'تماس',
  'faq_email_error'                     : 'نمی‌توان برنامه ایمیل را باز کرد. لطفاً به cyberinc101@gmail.com ایمیل بزنید',
  'faq_cat_getting_started'             : 'شروع کار',
  'faq_cat_templates'                   : 'قالب‌ها',
  'faq_cat_editing'                     : 'ویرایش',
  'faq_cat_exporting'                   : 'خروجی گرفتن',
  'faq_cat_data_privacy'                : 'داده و حریم خصوصی',
  'faq_cat_troubleshooting'             : 'عیب‌یابی',
  'faq_q1'  : 'چطور اولین رزومه‌ام را بسازم؟',
  'faq_a1'  : 'دکمه «+» را در صفحه اصلی ضربه بزنید تا رزومه جدیدی شروع کنید. قالبی که با سبک شما مناسب است را انتخاب کنید، سپس اطلاعات شخصی، سابقه کاری، تحصیلات و مهارت‌ها را گام به گام وارد کنید. پیشرفت شما به صورت خودکار ذخیره می‌شود.',
  'faq_q2'  : 'آیا می‌توانم بیش از یک رزومه بسازم؟',
  'faq_a2'  : 'بله! می‌توانید رزومه‌های متعددی برای موقعیت‌ها یا صنایع مختلف بسازید. هر رزومه جداگانه ذخیره می‌شود تا بتوانید آن‌ها را برای درخواست‌های شغلی خاص تنظیم کنید.',
  'faq_q3'  : 'چطور قالب رزومه‌ام را تغییر دهم؟',
  'faq_a3'  : 'رزومه را باز کنید، روی آیکون قالب در بالای صفحه ضربه بزنید و قالب‌های موجود را مرور کنید. روی هر قالبی ضربه بزنید تا با محتوای موجودتان پیش‌نمایش ببینید. تأیید کنید تا اعمال شود.',
  'faq_q4'  : 'آیا قالب‌های رایگان و پریمیوم وجود دارد؟',
  'faq_a4'  : 'بله. مجموعه‌ای از قالب‌های حرفه‌ای به صورت رایگان در دسترس است. قالب‌های پریمیوم با طراحی‌های پیشرفته و پالت رنگی از طریق خرید یکبار یا اشتراک در دسترس هستند.',
  'faq_q5'  : 'چطور بخش‌ها را اضافه یا حذف کنم؟',
  'faq_a5'  : 'در ویرایشگر رزومه، به پایین صفحه بروید و «افزودن بخش» را ضربه بزنید تا مواردی مانند زبان‌ها، گواهینامه‌ها یا کار داوطلبانه اضافه شود. برای حذف یک بخش، عنوان آن را ضربه بزنید و «حذف» را انتخاب کنید.',
  'faq_q6'  : 'چطور ترتیب بخش‌ها را تغییر دهم؟',
  'faq_a6'  : 'دسته کشیدن (≡) کنار هر عنوان بخش را طولانی نگه دارید و به موقعیت دلخواه بکشید. تغییرات به صورت خودکار ذخیره می‌شوند.',
  'faq_q7'  : 'چطور رزومه‌ام را به صورت PDF خروجی بگیرم؟',
  'faq_a7'  : 'رزومه را باز کنید و دکمه خروجی (آیکون اشتراک‌گذاری) در گوشه بالا-راست را ضربه بزنید. «خروجی PDF» را انتخاب کنید. سپس می‌توانید آن را در دستگاهتان ذخیره کنید، از طریق ایمیل، واتساپ به اشتراک بگذارید یا مستقیماً در سایت‌های کاریابی آپلود کنید.',
  'faq_q8'  : 'چه فرمت‌های فایلی پشتیبانی می‌شوند؟',
  'faq_a8'  : 'در حال حاضر برنامه از خروجی رزومه شما به عنوان PDF با کیفیت بالا پشتیبانی می‌کند. فرمت‌های دیگر ممکن است در به‌روزرسانی‌های آینده اضافه شوند.',
  'faq_q9'  : 'داده‌های رزومه‌ام کجا ذخیره می‌شوند؟',
  'faq_a9'  : 'تمام داده‌های رزومه شما به صورت محلی روی دستگاهتان ذخیره می‌شوند. ما اطلاعات شخصی شما را به سرورهایمان آپلود نمی‌کنیم. این به معنای خصوصی ماندن داده‌هایتان و دسترسی آفلاین است.',
  'faq_q10' : 'چطور از رزومه‌هایم نسخه پشتیبان بگیرم؟',
  'faq_a10' : 'رزومه‌های شما در پشتیبان‌گیری استاندارد دستگاهتان (پشتیبان‌گیری Google Drive در اندروید، iCloud در iOS) در صورت فعال بودن پشتیبان‌گیری در تنظیمات دستگاه گنجانده می‌شوند. همچنین می‌توانید رزومه‌های جداگانه را به صورت PDF خروجی بگیرید.',
  'faq_q11' : 'برنامه کند اجرا می‌شود. چه کاری انجام دهم؟',
  'faq_a11' : 'سعی کنید برنامه را ببندید و دوباره باز کنید. اگر مشکل ادامه داشت، دستگاه خود را راه‌اندازی مجدد کنید. اطمینان حاصل کنید که آخرین نسخه برنامه را از فروشگاه Play / App Store نصب کرده‌اید.',
  'faq_q12' : 'رزومه‌ام درست خروجی نمی‌گیرد. چه کاری انجام دهم؟',
  'faq_a12' : 'مطمئن شوید که فضای ذخیره‌سازی کافی روی دستگاهتان دارید. سعی کنید تصاویر بزرگ در رزومه را کاهش دهید. اگر مشکل ادامه داشت، لطفاً با تیم پشتیبانی ما تماس بگیرید.',
  'faq_q13' : 'فراموش کردم ذخیره کنم — آیا کارم از دست رفته؟',
  'faq_a13' : 'اصلاً! برنامه پیشرفت شما را در حین ویرایش به صورت مداوم ذخیره می‌کند.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'مسیر شغلی شما، کامل‌شده',
  'header_tooltip_back'                 : 'بازگشت',
  'header_tooltip_my_cvs'               : 'رزومه‌های من',
  'header_tooltip_settings'             : 'تنظیمات',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'رزومه‌های من',
  'saved_count_single'                  : '{n} سند',
  'saved_count_plural'                  : '{n} سند',
  'saved_limit_reached'                 : 'به محدودیت رسید',
  'saved_footer_count'                  : '{n} / ۳۰ رزومه',
  'saved_filter_all'                    : 'همه',
  'saved_filter_draft'                  : 'پیش‌نویس',
  'saved_filter_complete'               : 'کامل',
  'saved_status_complete'               : 'کامل',
  'saved_status_saved'                  : 'ذخیره‌شده',
  'saved_status_draft'                  : 'پیش‌نویس',
  'saved_empty_title'                   : 'هنوز رزومه‌ای ندارید',
  'saved_empty_sub'                     : 'از بالا شروع به ساخت اولین رزومه‌تان کنید',
  'saved_search_empty_title'            : 'نتیجه‌ای یافت نشد',
  'saved_search_empty_sub'              : 'عبارت جستجوی دیگری امتحان کنید',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'طرح رنگی',
  'custom_font_settings_title'          : 'تنظیمات فونت',
  'custom_font_family_label'            : 'خانواده فونت',
  'custom_font_size_label'              : 'اندازه فونت: ',
  'custom_current_template_title'       : 'قالب فعلی',
  'custom_change_template_btn'          : 'تغییر قالب',
  'custom_tpl_modern'                   : 'مدرن',
  'custom_tpl_classic'                  : 'کلاسیک',
  'custom_tpl_professional'             : 'حرفه‌ای',
  'custom_tpl_creative'                 : 'خلاق',
  'custom_tpl_minimal'                  : 'مینیمال',
  'custom_tpl_modern_desc'              : 'طراحی تمیز و معاصر',
  'custom_tpl_classic_desc'             : 'چیدمان سنتی حرفه‌ای',
  'custom_tpl_professional_desc'        : 'قالب متمرکز بر کسب‌وکار',
  'custom_tpl_creative_desc'            : 'با طراحی منحصربه‌فرد متمایز شوید',
  'custom_tpl_minimal_desc'             : 'سبک ساده و ظریف',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'انتخاب قالب',
  'swipe_photo_badge'                   : 'عکس',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'مدیریتی',
  'tpl_nordic_name'                     : 'نوردیک',
  'tpl_vibrant_name'                    : 'پرانرژی',
  'tpl_tech_dark_name'                  : 'تک دارک',
  'tpl_luxury_name'                     : 'لوکس',
  'tpl_executive_tag'                   : 'محبوب‌ترین',
  'tpl_nordic_tag'                      : 'تمیز',
  'tpl_vibrant_tag'                     : 'خلاق',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'نخبه',
  'tpl_executive_desc'                  : 'جسور و معتبر برای نقش‌های ارشد',
  'tpl_nordic_desc'                     : 'وضوح مینیمال مورد اعتماد شرکت‌های برتر',
  'tpl_vibrant_desc'                    : 'با انرژی و رنگ متمایز شوید',
  'tpl_tech_dark_desc'                  : 'ظاهر ترمینالی برای توسعه‌دهندگان',
  'tpl_luxury_desc'                     : 'برجستگی طلایی روی زمینه مشکی',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'قالب',
  'detail_step_personal'                : 'شخصی',
  'detail_step_experience'              : 'تجربه',
  'detail_step_education'               : 'تحصیلات',
  'detail_step_skills'                  : 'مهارت‌ها',
  'detail_step_additional'              : 'اضافی',
  'detail_step_references'              : 'معرف‌ها',
  'detail_step_customize'               : 'سفارشی‌سازی',
  'detail_banner_heading'               : 'تقریباً تمام شد!',
  'detail_banner_btn'                   : 'ادامه',
  'detail_banner_completion_label'      : 'تکمیل',
  'detail_stat_created_label'           : 'ایجادشده',
  'detail_stat_steps_label'             : 'مراحل انجام‌شده',
  'detail_section_template_style'       : 'سبک قالب',
  'detail_section_steps'                : 'مراحل',
  'detail_steps_counter'                : '{done} از {total} کامل',
  'detail_step_sub'                     : 'مرحله {n} از {total}',
  'detail_section_activity'             : 'فعالیت',
  'detail_activity_created'             : 'ایجادشده',
  'detail_activity_last_edited'         : 'آخرین ویرایش',
  'detail_activity_template'            : 'قالب',
  'detail_btn_continue_editing'         : 'ادامه ویرایش',
  'detail_btn_edit_cv'                  : 'ویرایش رزومه',
  'detail_option_rename'                : 'تغییر نام رزومه',
  'detail_option_delete'                : 'حذف رزومه',
  'detail_rename_title'                 : 'تغییر نام رزومه',
  'detail_rename_hint'                  : 'مثلاً رزومه مهندس نرم‌افزار',
  'detail_rename_error_empty'           : 'نام نمی‌تواند خالی باشد',
  'detail_rename_btn_cancel'            : 'انصراف',
  'detail_rename_btn_save'              : 'ذخیره',
  'detail_rename_snackbar'              : 'نام به "{name}" تغییر یافت',
  'detail_delete_title'                 : 'رزومه حذف شود؟',
  'detail_delete_body'                  : 'این عمل "{name}" را برای همیشه حذف می‌کند. این عمل قابل برگشت نیست.',
  'detail_delete_btn_cancel'            : 'انصراف',
  'detail_delete_btn_confirm'           : 'حذف',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'تکمیل‌شده',
  'detail_check_tile_incomplete'        : 'هنوز پر نشده',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'قالب خود را انتخاب کنید',
  'chooser_subtitle'                    : 'بکشید تا مرور کنید  ·  ضربه بزنید تا انتخاب کنید  ·  نگه دارید تا پیش‌نمایش ببینید',
  'chooser_card_hold_hint'              : 'نگه دارید تا پیش‌نمایش ببینید',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'انتخاب‌شده',
  'chooser_modal_heading'               : 'نام رزومه را وارد کنید',
  'chooser_modal_sub'                   : 'نامی بدهید تا بتوانید آن را در رزومه‌های من و تاریخچه راحت پیدا کنید.',
  'chooser_modal_field_label'           : 'نام رزومه',
  'chooser_modal_save_btn'              : 'ذخیره و شروع ساخت',
  'chooser_modal_divider'               : 'یا ادامه رزومه موجود',
  'chooser_nav_selected_sub'            : 'قالب انتخاب‌شده',
  'chooser_nav_cta'                     : 'ذخیره و ادامه',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'حداکثر تعداد ورودی‌ها رسیده',
  'editor_show_hide'                    : 'نمایش/پنهان',
  'editor_editing_badge'                : 'در حال ویرایش',
  'editor_field_required'               : 'الزامی',
  'editor_tooltip_edit'                 : 'ویرایش',
  'editor_tooltip_delete'               : 'حذف',
  'editor_date_start'                   : 'تاریخ شروع *',
  'editor_date_end'                     : 'تاریخ پایان *',
  'editor_date_tap_hint'                : 'ضربه بزنید تا انتخاب کنید',
  'editor_date_dialog_title'            : 'ماه و سال را انتخاب کنید',
  'editor_date_confirm'                 : 'تأیید',
  'editor_panel_hide'                   : 'پنهان',
  'editor_panel_show'                   : 'نمایش',
  'editor_validator_max_chars'          : 'حداکثر {n} کاراکتر',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'رزومه خود را بسازید',
  'editor_header_step_sub'              : 'مرحله {current} از {total} · {label}',
  'editor_step_template'                : 'قالب',
  'editor_step_personal'                : 'شخصی',
  'editor_step_experience'              : 'تجربه',
  'editor_step_education'               : 'تحصیلات',
  'editor_step_skills'                  : 'مهارت‌ها',
  'editor_step_additional'              : 'اضافی',
  'editor_step_references'              : 'معرف‌ها',
  'editor_step_customize'               : 'سفارشی‌سازی',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'سفارشی‌سازی',
  'customize_subtitle'                  : 'رزومه خود را منحصربه‌فرد کنید',
  'customize_smart_layout_btn'          : 'چیدمان هوشمند',
  'customize_back_to_top'               : 'بازگشت به بالا',
  'customize_done_title'                : 'همه چیز آماده است!',
  'customize_done_sub'                  : 'روی پیش‌نمایش رزومه در زیر ضربه بزنید تا رزومه تمام‌شده‌تان را ببینید',
  'customize_preview_btn'               : 'پیش‌نمایش رزومه',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'طرح رنگی',
  'color_black'                         : 'مشکی',
  'color_blue'                          : 'آبی',
  'color_nordic_blue'                   : 'آبی نوردیک',
  'color_indigo'                        : 'نیلی',
  'color_teal'                          : 'فیروزه‌ای',
  'color_green'                         : 'سبز',
  'color_purple'                        : 'بنفش',
  'color_orange'                        : 'نارنجی',
  'color_red'                           : 'قرمز',
  'color_executive_gold'                : 'طلایی مدیریتی',
  'color_vibrant_coral'                 : 'مرجانی پرانرژی',
  'color_white'                         : 'سفید',
  'color_white_bg'                      : 'پس‌زمینه سفید',
  'color_maroon'                        : 'زرشکی',
  'color_brutalist_yellow'              : 'زرد برتالیست',
  'color_neon_blue'                     : 'آبی نئون',
  'color_blueprint_navy'                : 'سرمه‌ای نقشه',
  'color_light_grey'                    : 'خاکستری روشن',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'خانواده فونت',
  'customize_font_picker_title'         : 'انتخاب فونت',
  'customize_font_picker_sub'           : 'هر فونت در قالب خودش پیش‌نمایش می‌شود',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'اندازه فونت',
  'customize_font_size_label'           : 'اندازه متن',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '۱۰ pt',
  'customize_font_size_max'             : '۱۶ pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'اندازه تصویر',
  'customize_image_size_label'          : 'اندازه تصویر',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '۱۰ px',
  'customize_image_size_max'            : '۱۶ px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'پیش‌نمایش زنده',
  'preview_page_count_singular'         : '۱ صفحه',
  'preview_page_count_plural'           : '{n} صفحه',
  'preview_page_of'                     : 'صفحه {page} از {total}',
  'preview_live_hint'                   : 'تغییرات فوری اعمال می‌شوند',
  'preview_template_unregistered'       : 'هنوز در customize_preview.dart ثبت نشده',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'در حال آماده‌سازی رزومه…',
  'preview_bar_print'                   : 'چاپ',
  'preview_bar_save_pdf'                : 'ذخیره به عنوان PDF',
  'preview_bar_share'                   : 'اشتراک‌گذاری',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'پیش‌نمایش رزومه',
  'preview_screen_sub'                  : '{n} {unit} · دقیقاً همانطور که چاپ می‌شود',
  'preview_page_singular'               : 'صفحه',
  'preview_page_plural'                 : 'صفحه',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'رزومه من',
  'preview_snack_print_failed'          : 'چاپ ناموفق بود: {e}',
  'preview_snack_saved'                 : 'رزومه در دانلودها ذخیره شد ✓',
  'preview_snack_export_failed'         : 'خروجی‌گیری ناموفق بود: {e}',
  'preview_snack_share_failed'          : 'اشتراک‌گذاری ناموفق بود: {e}',
  'preview_template_not_registered'     : 'قالب ثبت نشده',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'بستن پیش‌نمایش',
  'preview_modal_hint_photo'            : 'از عکس پروفایل پشتیبانی می‌کند  ·  روی کارت ضربه بزنید تا انتخاب کنید',
  'preview_modal_hint_no_photo'         : 'روی کارت قالب ضربه بزنید تا انتخاب کنید',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'رزومه من',
  'time_just_now'                       : 'همین الان',
  'time_minutes_ago'                    : '{n} دقیقه پیش',
  'time_hours_ago'                      : '{n} ساعت پیش',
  'time_yesterday'                      : 'دیروز',
  'time_days_ago'                       : '{n} روز پیش',
  'time_one_week_ago'                   : '۱ هفته پیش',
  'time_weeks_ago'                      : '{n} هفته پیش',

  // ─── preview_registry.dart — shared tag labels ───────────────────────────
  'tpl_tag_elegant'                     : 'ظریف',
  'tpl_tag_classic'                     : 'کلاسیک',
  'tpl_tag_minimal'                     : 'مینیمال',
  'tpl_tag_creative'                    : 'خلاق',
  'tpl_tag_bold'                        : 'جسور',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'گرادیان',
  'tpl_gradient_desc'                   : 'کارت‌های گرادیان فیروزه‌ای تا بنفش',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'مجله‌ای',
  'tpl_editorial_desc'                  : 'سبک مجله با قرمز و کرم',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'پاستل ملایم',
  'tpl_pastel_soft_desc'                : 'نوار کنار لاوندری، کارت‌های ملایم',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'برتالیست',
  'tpl_brutalist_desc'                  : 'شبکه خام، حاشیه‌های پررنگ و زرد',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'زمرد',
  'tpl_emerald_desc'                    : 'سبز جنگلی با خط زمان',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'اینفوگرافیک',
  'tpl_infographic_desc'                : 'بوم تاریک با نمودارهای حلقوی',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'آرت دکو',
  'tpl_art_deco_desc'                   : 'لوکس هندسی طلایی دهه ۱۹۲۰',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'وینا دارک',
  'tpl_wina_dark_desc'                  : 'اینفوگرافیک تاریک با حلقه‌ها',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'ریو نارنجی',
  'tpl_rio_orange_desc'                 : 'نوار کنار تاریک با برجستگی نارنجی',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'تابستان',
  'tpl_summer_desc'                     : 'مینیمال تمیز با تن‌های خاکستری ملایم',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'هلن',
  'tpl_helene_desc'                     : 'تن‌های بژ گرم و ظریف',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'کنفیلد',
  'tpl_canfield_desc'                   : 'کلاسیک مشکی و سفید تند',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'کالینز',
  'tpl_collins_desc'                    : 'چیدمان کلاسیک سازگار با ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'تونی دارک',
  'tpl_tony_dark_desc'                  : 'سبک اینفوگرافیک نارنجی تاریک',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'فشن',
  'tpl_fashion_desc'                    : 'نقشه فنی روی شبکه',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'آرشیویست',
  'tpl_archivist_desc'                  : 'چیدمان کلاسیک دو ستونی با برچسب',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'دیپلمات',
  'tpl_diplomat_desc'                   : 'سرصفحه‌های سایه‌دار با جداکننده‌های الماسی',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'مریدیان',
  'tpl_meridian_desc'                   : 'سرصفحه‌های وسط‌چین با شرکت‌های برجسته',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'مومنتوم',
  'tpl_momentum_desc'                   : 'نام پررنگ، نقاط خط زمان و دستاوردها',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'اطلاعات شخصی',
  'personal_subtitle'                   : 'به کارفرمایان بگویید چه کسی هستید',
  'personal_profile_counter'            : '{n}/{max} پروفایل',
  'personal_info_banner'                : 'تا ۵ پروفایل ذخیره کنید و برای هر رزومه یکی انتخاب کنید. انتخاب شما برای هر رزومه جداگانه به خاطر سپرده می‌شود.',
  'personal_snack_max'                  : 'حداکثر {n} پروفایل رسیده.',
  'personal_add_btn'                    : 'افزودن پروفایل جدید',
  'personal_library_title'              : 'پروفایل‌های ذخیره‌شده',
  'personal_selected_one'               : '۱ انتخاب‌شده',
  'personal_selected_none'              : 'هیچکدام انتخاب نشده',
  'personal_library_hint'               : 'روی کارت ضربه بزنید تا فقط برای این رزومه انتخاب شود. رزومه‌های دیگر انتخاب‌های مستقل خود را حفظ می‌کنند.',
  'personal_empty_message'              : 'هنوز پروفایلی ذخیره نشده',
  'personal_empty_sub'                  : 'از بالا ضربه بزنید تا اطلاعات شخصی خود را اضافه کنید',
  'personal_nav_next'                   : 'ذخیره و ادامه',
  'personal_card_active_badge'          : 'فعال برای این رزومه',
  'personal_sheet_title_add'            : 'پروفایل جدید',
  'personal_sheet_title_edit'           : 'ویرایش پروفایل',
  'personal_sheet_brutalist_badge'      : 'برتالیست',
  'personal_sheet_brutalist_banner'     : 'قالب برتالیست فیلدهای تماس فشرده دارد. مقادیر کوتاه‌تر (مثلاً فقط شهر) بهتر نمایش داده می‌شوند.',
  'personal_section_photo'              : 'عکس پروفایل',
  'personal_section_basic'              : 'مشخصات اصلی',
  'personal_section_contact'            : 'تماس',
  'personal_section_online'             : 'حضور آنلاین',
  'personal_section_summary'            : 'خلاصه حرفه‌ای',
  'personal_field_first_name'           : 'نام *',
  'personal_field_last_name'            : 'نام خانوادگی',
  'personal_field_job_title'            : 'عنوان شغلی *',
  'personal_field_email'                : 'آدرس ایمیل *',
  'personal_field_phone'                : 'شماره تلفن *',
  'personal_field_location'             : 'محل سکونت',
  'personal_field_location_brut'        : 'محل سکونت (فقط شهر)',
  'personal_field_website'              : 'وب‌سایت / پورتفولیو',
  'personal_field_linkedin'             : 'لینکدین',
  'personal_hint_first_name'            : 'مثلاً سارا',
  'personal_hint_last_name'             : 'مثلاً احمدی',
  'personal_hint_job_title'             : 'مثلاً مهندس ارشد',
  'personal_hint_email'                 : 'مثلاً sara@example.com',
  'personal_hint_phone'                 : 'مثلاً ۰۹۱۲۱۲۳۴۵۶۷',
  'personal_hint_location'              : 'مثلاً تهران، ایران',
  'personal_hint_location_brut'         : 'مثلاً تهران',
  'personal_hint_website'               : 'مثلاً github.com/sara',
  'personal_hint_website_brut'          : 'مثلاً github.com/sara',
  'personal_hint_linkedin'              : 'مثلاً linkedin.com/in/sara',
  'personal_hint_linkedin_brut'         : 'مثلاً linkedin.com/in/sara',
  'personal_summary_hint_label'         : 'مختصر بنویسید — این در بالای رزومه شما ظاهر می‌شود.',
  'personal_hint_summary'               : 'خلاصه‌ای ۲–۳ جمله‌ای از سابقه و اهداف شما...',
  'personal_validator_email'            : 'یک ایمیل معتبر وارد کنید',
  'personal_field_char_limit_tooltip'   : 'محدودیت کاراکتر رسیده',
  'personal_sheet_btn_save'             : 'ذخیره پروفایل',
  'personal_sheet_btn_update'           : 'ذخیره تغییرات',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'انتخاب عکس',
  'photo_option_gallery'                : 'انتخاب از گالری',
  'photo_option_camera'                 : 'گرفتن عکس',
  'photo_option_reposition'             : 'تنظیم موقعیت عکس',
  'photo_option_remove'                 : 'حذف عکس',
  'photo_status_added'                  : 'عکس اضافه شد ✓',
  'photo_status_empty'                  : 'یک عکس حرفه‌ای اضافه کنید',
  'photo_chip_gallery'                  : 'گالری',
  'photo_chip_camera'                   : 'دوربین',
  'photo_chip_reposition'               : 'تنظیم موقعیت',
  'photo_reposition_title'              : 'تنظیم موقعیت عکس',
  'photo_reposition_sub'                : 'عکس را بکشید تا موقعیت را تنظیم کنید',
  'photo_reposition_reset'              : 'بازگشت به مرکز',
  'photo_reposition_apply'              : 'اعمال',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'مهارت‌ها',
  'skills_subtitle'                     : 'توانایی‌های کلیدی خود را برجسته کنید',
  'skills_add_btn'                      : 'افزودن مهارت جدید',
  'skills_snack_max_icons'              : 'حداکثر ۱۰ آیکون انتخاب شده.',
  'skills_snack_max_skills'             : 'حداکثر ۱۵ مهارت رسیده.',
  'skills_library_title'                : 'مهارت‌های ذخیره‌شده',
  'skills_library_hint'                 : 'مهارت‌های تیک‌خورده در این رزومه گنجانده می‌شوند. انتخاب‌های شما به صورت خودکار ذخیره می‌شوند.',
  'skills_nav_next'                     : 'ادامه به اطلاعات اضافی',
  'skills_wina_header_icon_bar'         : 'نوار آیکون سرصفحه',
  'skills_wina_on'                      : 'روشن',
  'skills_wina_off'                     : 'خاموش',
  'skills_wina_bar_on_sub'              : 'دایره‌های آیکون رنگی در سرصفحه رزومه نشان داده می‌شوند.',
  'skills_wina_bar_off_sub'             : 'ردیف آیکون پنهان است — فضای بیشتری برای اطلاعات تماس.',
  'skills_wina_palette_hint'            : 'آیکون‌ها به صورت دایره‌های رنگی به ترتیب پالت نمایش داده می‌شوند.',
  'skills_wina_preview_label'           : 'پیش‌نمایش',
  'skills_wina_disabled_hint'           : 'نوار آیکون بالا را فعال کنید تا انتخاب کنید کدام آیکون‌ها در سرصفحه رزومه ظاهر شوند.',
  'skills_sheet_title_add'              : 'افزودن مهارت',
  'skills_sheet_title_edit'             : 'ویرایش مهارت',
  'skills_sheet_field_name'             : 'نام مهارت *',
  'skills_sheet_hint_short'             : 'مثلاً Flutter، طراحی',
  'skills_sheet_hint_long'              : 'مثلاً Flutter، مدیریت پروژه',
  'skills_sheet_validator_max'          : 'حداکثر {n} کاراکتر',
  'skills_sheet_proficiency'            : 'سطح مهارت',
  'skills_sheet_beginner'               : 'مبتدی',
  'skills_sheet_expert'                 : 'خبره',
  'skills_sheet_btn_save'               : 'ذخیره مهارت',
  'skills_sheet_btn_update'             : 'به‌روزرسانی مهارت',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'معرف‌های شخصی',
  'refs_subtitle'                       : 'افرادی که می‌توانند شخصاً شما را تأیید کنند',
  'refs_add_btn'                        : 'افزودن معرف شخصی جدید',
  'refs_snack_max_selected'             : 'حداکثر ۴ معرف می‌توان برای یک رزومه انتخاب کرد.',
  'refs_snack_max_saved'                : 'حداکثر ۱۰ معرف ذخیره‌شده رسیده.',
  'refs_library_title'                  : 'معرف‌های ذخیره‌شده',
  'refs_library_hint'                   : 'معرف‌های تیک‌خورده در این رزومه گنجانده می‌شوند. حداکثر ۴ نفر در هر رزومه. انتخاب‌های شما به صورت خودکار ذخیره می‌شوند.',
  'refs_nav_next'                       : 'ادامه به سفارشی‌سازی',
  'refs_sheet_title_add'                : 'افزودن معرف شخصی',
  'refs_sheet_title_edit'               : 'ویرایش معرف شخصی',
  'refs_sheet_sub_add'                  : 'کسی که می‌تواند شما را شخصاً به کارفرمایان توصیه کند.',
  'refs_sheet_sub_edit'                 : 'اطلاعات این معرف را در زیر به‌روزرسانی کنید.',
  'refs_sheet_field_name'               : 'نام و نام خانوادگی *',
  'refs_sheet_field_title'              : 'عنوان شغلی *',
  'refs_sheet_field_company'            : 'شرکت (اختیاری)',
  'refs_sheet_field_email'              : 'آدرس ایمیل *',
  'refs_sheet_field_phone'              : 'شماره تلفن *',
  'refs_sheet_hint_name'                : 'مثلاً علی احمدی',
  'refs_sheet_hint_title'               : 'مثلاً مدیر مهندسی',
  'refs_sheet_hint_company'             : 'مثلاً شرکت آکمه',
  'refs_sheet_hint_email'               : 'مثلاً ali@acme.com',
  'refs_sheet_hint_phone'               : 'مثلاً ۰۹۱۲۱۲۳۴۵۶۷',
  'refs_sheet_validator_email'          : 'یک آدرس ایمیل معتبر وارد کنید',
  'refs_sheet_btn_save'                 : 'ذخیره معرف شخصی',
  'refs_sheet_btn_update'               : 'به‌روزرسانی معرف شخصی',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'سابقه کاری',
  'exp_subtitle'                        : 'تاریخچه کاری خود را اضافه کنید',
  'exp_banner_info'                     : 'تا {n} مسئولیت در هر نقش در رزومه ظاهر می‌شود. معمولاً ۳–۶ نقش در ۱–۲ صفحه جا می‌گیرد.',
  'exp_add_btn'                         : 'افزودن تجربه جدید',
  'exp_snack_max_selected'              : 'حداکثر ۸ تجربه می‌توان برای یک رزومه انتخاب کرد.',
  'exp_snack_max_saved'                 : 'حداکثر ۱۲ تجربه ذخیره‌شده رسیده.',
  'exp_library_title'                   : 'تجربه‌های ذخیره‌شده',
  'exp_library_hint'                    : 'موارد تیک‌خورده فقط در این رزومه گنجانده می‌شوند. رزومه‌های دیگر انتخاب‌های مستقل خود را حفظ می‌کنند.',
  'exp_nav_next'                        : 'ادامه به تحصیلات',
  'exp_empty_message'                   : 'هنوز تجربه‌ای اضافه نشده',
  'exp_empty_sub'                       : 'از بالا ضربه بزنید تا اولین نقش خود را اضافه کنید',
  'exp_card_resp_singular'              : 'مسئولیت',
  'exp_card_resp_plural'                : 'مسئولیت',
  'exp_card_resp_tooltip'               : 'فقط ۸ مسئولیت اول در رزومه ظاهر می‌شود',
  'exp_sheet_title_add'                 : 'افزودن تجربه',
  'exp_sheet_title_edit'                : 'ویرایش تجربه',
  'exp_sheet_field_job_title'           : 'عنوان شغلی *',
  'exp_sheet_field_company'             : 'شرکت *',
  'exp_sheet_field_location'            : 'محل',
  'exp_sheet_section_responsibilities'  : 'مسئولیت‌های کلیدی',
  'exp_sheet_resp_hint_info'            : 'حداکثر ۸ نقطه‌بولت · هر کدام ۲۰۰ کاراکتر',
  'exp_sheet_resp_label'                : 'مسئولیت {n}',
  'exp_sheet_resp_hint'                 : 'مثلاً تیمی از ۵ مهندس را رهبری کردم',
  'exp_sheet_resp_add_btn'              : 'افزودن مسئولیت',
  'exp_sheet_resp_max_info'             : 'حداکثر {n} مسئولیت رسیده',
  'exp_sheet_resp_validator_max'        : 'حداکثر ۲۰۰ کاراکتر',
  'exp_sheet_hint_job_title'            : 'مثلاً توسعه‌دهنده ارشد',
  'exp_sheet_hint_location'             : 'مثلاً تهران، ایران',
  'exp_sheet_btn_save'                  : 'ذخیره تجربه',
  'exp_sheet_btn_update'                : 'ذخیره تغییرات',
  'exp_date_present'                    : 'حال / نقش فعلی',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'تحصیلات',
  'edu_subtitle'                        : 'سابقه تحصیلی خود را اضافه کنید',
  'edu_add_btn'                         : 'افزودن تحصیلات جدید',
  'edu_snack_max_selected'              : 'حداکثر ۸ سابقه تحصیلی می‌توان برای یک رزومه انتخاب کرد.',
  'edu_snack_max_saved'                 : 'حداکثر ۱۲ سابقه تحصیلی ذخیره‌شده رسیده.',
  'edu_library_title'                   : 'تحصیلات ذخیره‌شده',
  'edu_library_hint'                    : 'موارد تیک‌خورده در این رزومه گنجانده می‌شوند. انتخاب‌های شما به صورت خودکار ذخیره می‌شوند.',
  'edu_nav_next'                        : 'ادامه به مهارت‌ها',
  'edu_empty_message'                   : 'هنوز تحصیلاتی اضافه نشده',
  'edu_empty_sub'                       : 'از بالا ضربه بزنید تا مدارک تحصیلی خود را اضافه کنید',
  'edu_card_bullet_singular'            : 'نقطه‌بولت',
  'edu_card_bullet_plural'              : 'نقطه‌بولت',
  'edu_sheet_title_add'                 : 'افزودن تحصیلات',
  'edu_sheet_title_edit'                : 'ویرایش تحصیلات',
  'edu_sheet_field_degree'              : 'مدرک / مؤهلیت *',
  'edu_sheet_field_institution'         : 'مؤسسه آموزشی *',
  'edu_sheet_section_key_points'        : 'نکات کلیدی',
  'edu_sheet_key_points_hint_info'      : 'اختیاری · ۱ نقطه‌بولت · حداکثر ۱۰۰ کاراکتر',
  'edu_sheet_point_label'               : 'نکته {n}',
  'edu_sheet_point_add_btn'             : 'افزودن نقطه‌بولت',
  'edu_sheet_point_max_info'            : 'حداکثر {n} نقطه‌بولت رسیده',
  'edu_sheet_point_validator_max'       : 'حداکثر {n} کاراکتر',
  'edu_sheet_hint_degree'               : 'مثلاً کارشناسی علوم کامپیوتر',
  'edu_sheet_hint_institution'          : 'مثلاً دانشگاه تهران',
  'edu_sheet_hint_bullet'               : 'مثلاً با رتبه عالی فارغ‌التحصیل شدم',
  'edu_sheet_btn_save'                  : 'ذخیره تحصیلات',
  'edu_sheet_btn_update'                : 'ذخیره تغییرات',
  'edu_date_present'                    : 'حال / در حال تحصیل',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'اطلاعات اضافی',
  'additional_subtitle'                 : 'گواهینامه‌ها، زبان‌ها و بیشتر',
  'additional_cert_section_title'       : 'گواهینامه‌ها',
  'additional_cert_counter'             : '{sel}/{total} انتخاب‌شده · حداکثر {max}',
  'additional_cert_hide'                : 'پنهان',
  'additional_cert_show'                : 'نمایش',
  'additional_cert_add_btn'             : 'افزودن',
  'additional_cert_snack_max'           : 'حداکثر {n} گواهینامه رسیده.',
  'additional_cert_hint'                : 'موارد تیک‌خورده در این رزومه گنجانده می‌شوند. انتخاب‌های شما به صورت خودکار ذخیره می‌شوند.',
  'additional_cert_empty'               : 'هنوز گواهینامه‌ای اضافه نشده',
  'additional_lang_section_title'       : 'زبان‌ها',
  'additional_lang_add_hint'            : 'مثلاً انگلیسی',
  'additional_lang_snack_max'           : 'حداکثر {n} زبان رسیده.',
  'additional_lang_empty'               : 'هنوز زبانی اضافه نشده',
  'additional_hobby_section_title'      : 'سرگرمی‌ها و علاقه‌مندی‌ها',
  'additional_hobby_add_hint'           : 'مثلاً عکاسی',
  'additional_hobby_snack_max'          : 'حداکثر {n} سرگرمی رسیده.',
  'additional_hobby_empty'              : 'هنوز سرگرمی‌ای اضافه نشده',
  'additional_section_hint'             : 'موارد تیک‌خورده در این رزومه گنجانده می‌شوند. انتخاب‌های شما به صورت خودکار ذخیره می‌شوند.',
  'additional_nav_next'                 : 'ادامه به معرف‌ها',
  'cert_sheet_title_add'                : 'افزودن گواهینامه',
  'cert_sheet_title_edit'               : 'ویرایش گواهینامه',
  'cert_sheet_sub'                      : 'یک مدرک، گواهینامه یا اعتبارنامه حرفه‌ای اضافه کنید.',
  'cert_sheet_field_name'               : 'نام گواهینامه *',
  'cert_sheet_field_issued_by'          : 'صادرشده توسط (اختیاری)',
  'cert_sheet_field_short_desc'         : 'توضیح کوتاه (اختیاری)',
  'cert_sheet_hint_name'                : 'مثلاً AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'مثلاً Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'مثلاً دریافت‌شده در ۱۴۰۳',
  'cert_sheet_btn_save'                 : 'ذخیره گواهینامه',
  'cert_sheet_btn_update'               : 'به‌روزرسانی گواهینامه',
  'simple_sheet_title_add_language'     : 'افزودن زبان',
  'simple_sheet_title_edit_language'    : 'ویرایش زبان',
  'simple_sheet_title_add_hobby'        : 'افزودن سرگرمی',
  'simple_sheet_title_edit_hobby'       : 'ویرایش سرگرمی',
  'simple_sheet_btn_save'               : 'ذخیره',
  'simple_sheet_btn_update'             : 'به‌روزرسانی',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'تماس',
  'pdf_section_about_me'                : 'درباره من',
  'pdf_section_summary'                 : 'خلاصه',
  'pdf_section_summary_short'           : 'خلاصه',
  'pdf_section_profile'                 : 'پروفایل',
  'pdf_section_experience'              : 'تجربه',
  'pdf_section_experience_short'        : 'تجربه',
  'pdf_section_education'               : 'تحصیلات',
  'pdf_section_skills'                  : 'مهارت‌ها',
  'pdf_section_languages'               : 'زبان‌ها',
  'pdf_label_email'                     : 'ایمیل',
  'pdf_label_phone'                     : 'تلفن',
  'pdf_label_location'                  : 'محل',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'محدودیت رزومه رسیده',
  'limit_dialog_body'                   : 'به حداکثر ۳۰ رزومه رسیده‌اید. لطفاً قبل از ساختن رزومه جدید یک رزومه موجود را حذف کنید.',
  'limit_dialog_go_to_my_cvs'           : 'رفتن به رزومه‌های من',
  'limit_dialog_cancel'                 : 'انصراف',
  'refs_count_summary'                  : '{checked}/{maxChecked} انتخاب‌شده · {saved}/{maxSaved} ذخیره‌شده',
  'refs_selected_badge'                 : '{n} انتخاب‌شده',
  'refs_empty_message'                  : 'هنوز معرفی ذخیره نشده',
  'refs_empty_sub'                      : 'از بالا ضربه بزنید تا یک معرف شخصی اضافه کنید',
};