// lib/language_keys/lang_bn_bengali.dart
//
// Bengali (Bangladesh) — translation map.
// All keys mirror lang_en_english.dart exactly.

const Map<String, String> bnBengali = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'কোনো ভাষা পাওয়া যায়নি',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'এড়িয়ে যান',
  'onboarding_next'                     : 'পরবর্তী',
  'onboarding_get_started'              : 'শুরু করুন',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  স্বাগতম',
  'ob1_title'                           : 'একটি সিভি তৈরি করুন যা\nদরজা খুলে দেয়',
  'ob1_body'                            : 'শত শত প্রার্থীর মধ্যে আলাদা হয়ে উঠুন। মিনিটের মধ্যে একটি পেশাদার, চাকরি জয়ের সিভি তৈরি করুন — ডিজাইন দক্ষতার প্রয়োজন নেই।',
  'ob1_pill_label'                      : 'প্রফেশনাল সিভি বিল্ডার',
  'ob1_chip_templates'                  : '২৪+ টেমপ্লেট',
  'ob1_chip_pdf'                        : 'পিডিএফ এক্সপোর্ট',
  'ob1_chip_free'                       : 'বিনামূল্যে ব্যবহার',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  টেমপ্লেট',
  'ob2_title'                           : 'প্রতিটি শিল্প।\nপ্রতিটি উচ্চাকাঙ্ক্ষা।',
  'ob2_body'                            : 'বোর্ডরুম-প্রস্তুত লেআউট থেকে সাহসী সৃজনশীল ডিজাইন পর্যন্ত — একটি টেমপ্লেট যা আপনার গল্প বলে।',
  'ob2_tap_hint'                        : 'প্রিভিউ করতে যেকোনো টেমপ্লেটে ট্যাপ করুন',
  'ob2_tpl_executive'                   : 'এক্সিকিউটিভ',
  'ob2_tpl_vibrant'                     : 'ভাইব্র্যান্ট',
  'ob2_tpl_nordic'                      : 'নর্ডিক',
  'ob2_tpl_tech_dark'                   : 'টেক ডার্ক',
  'ob2_tpl_luxury'                      : 'লাক্সারি',
  'ob2_tag_corporate'                   : 'কর্পোরেট',
  'ob2_tag_creative'                    : 'ক্রিয়েটিভ',
  'ob2_tag_minimal'                     : 'মিনিমাল',
  'ob2_tag_modern'                      : 'মডার্ন',
  'ob2_tag_premium'                     : 'প্রিমিয়াম',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  স্মার্ট লেআউট',
  'ob3_title'                           : 'আপনার সিভি।\nনিখুঁতভাবে সাজানো।',
  'ob3_body'                            : 'স্মার্ট লেআউট সর্বোচ্চ প্রভাবের জন্য আপনার বিভাগগুলি পুনর্বিন্যাস করে — নিয়োগকর্তারা যেখানে প্রথমে দেখেন সেখানে আপনার সবচেয়ে শক্তিশালী বিষয়বস্তু রাখে।',
  'ob3_badge_smart_layout'              : 'স্মার্ট লেআউট',
  'ob3_badge_cv_ready'                  : 'সিভি প্রস্তুত!',
  'ob3_step1_label'                     : 'একটি টেমপ্লেট বেছে নিন',
  'ob3_step1_desc'                      : '২৪+ অসাধারণ ডিজাইন থেকে বেছে নিন।',
  'ob3_step2_label'                     : 'আপনার বিবরণ পূরণ করুন',
  'ob3_step2_desc'                      : 'সমস্ত বিভাগের জন্য গাইডেড ফিল্ড।',
  'ob3_step3_label'                     : 'স্মার্ট লেআউট',
  'ob3_step3_desc'                      : 'এক ট্যাপে আপনার সিভি নিখুঁতভাবে সাজায়।',
  'ob3_step4_label'                     : 'পিডিএফ হিসেবে এক্সপোর্ট করুন',
  'ob3_step4_desc'                      : 'পিক্সেল-পারফেক্ট পিডিএফ পাঠানোর জন্য প্রস্তুত।',
  'ob3_section_work'                    : 'কাজের অভিজ্ঞতা',
  'ob3_section_education'               : 'শিক্ষা',
  'ob3_section_skills'                  : 'দক্ষতা',
  'ob3_section_references'              : 'রেফারেন্স',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  শুরু করতে প্রস্তুত',
  'ob4_title'                           : 'শীর্ষ প্রার্থীরা কেন\nসিভি বিল্ডার বেছে নেন',
  'ob4_visual_headline'                 : 'আপনি সম্পূর্ণ প্রস্তুত!',
  'ob4_visual_subline'                  : 'চাকরি পেতে যা দরকার সব কিছুই আছে।',
  'ob4_stat_templates_value'            : '২৪+',
  'ob4_stat_templates_label'            : 'টেমপ্লেট',
  'ob4_stat_max_cvs_value'              : '৩০',
  'ob4_stat_max_cvs_label'             : 'সর্বোচ্চ সিভি',
  'ob4_stat_export_value'               : 'পিডিএফ',
  'ob4_stat_export_label'               : 'এক্সপোর্ট',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'প্রাইভেট',
  'ob4_hl1_title'                       : 'ব্যক্তিগত ও নিরাপদ',
  'ob4_hl1_sub'                         : 'ডেটা আপনার ডিভাইসেই থাকে।',
  'ob4_hl2_title'                       : 'অটো-সেভ',
  'ob4_hl2_sub'                         : 'প্রতিটি কিস্ট্রোক তাৎক্ষণিকভাবে সেভ হয়।',
  'ob4_hl3_title'                       : '৩০টি পর্যন্ত সিভি',
  'ob4_hl3_sub'                         : 'প্রতিটি পদের জন্য অনন্য সিভি।',
  'ob4_hl4_title'                       : 'এক-ট্যাপ শেয়ার',
  'ob4_hl4_sub'                         : 'অ্যাপ না ছেড়েই পিডিএফ পাঠান।',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ ভিড় থেকে আলাদা হয়ে উঠুন',
  'home_hero_title'                     : 'আপনার প্রফেশনাল\nসিভি তৈরি করুন',
  'home_hero_sub'                       : 'মিনিটের মধ্যে একটি\nআকর্ষণীয় রেজুমে তৈরি করুন',
  'home_hero_cta'                       : 'তৈরি শুরু করুন',
  'home_premium_soon'                   : 'প্রো আপগ্রেড শীঘ্রই আসছে!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'সর্বশেষ',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'সর্বশেষ সম্পাদিত',
  'history_sort_by_template'            : 'টেমপ্লেট অনুযায়ী',
  'history_sort_sheet_title'            : 'সাজানোর ধরন',
  'history_sort_alphabetical_full'      : 'বর্ণানুক্রমিক (A–Z)',
  'history_premium_soon'                : 'প্রো আপগ্রেড শীঘ্রই আসছে!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'সেটিংস',
  'settings_section_preferences'        : 'পছন্দসমূহ',
  'settings_section_support'            : 'সাপোর্ট',
  'settings_section_legal'              : 'আইনি',
  'settings_section_about'              : 'সম্পর্কে',
  'settings_language_tile_title'        : 'ভাষা',
  'settings_dark_mode_title'            : 'ডার্ক মোড',
  'settings_dark_mode_on'               : 'ডার্ক থিম সক্রিয়',
  'settings_dark_mode_off'              : 'লাইট থিম সক্রিয়',
  'settings_help_faq_title'             : 'সাহায্য ও FAQ',
  'settings_help_faq_sub'               : 'সাধারণ প্রশ্নের উত্তর',
  'settings_contact_support_title'      : 'সাপোর্টে যোগাযোগ করুন',
  'settings_rate_app_title'             : 'অ্যাপটি রেট করুন',
  'settings_rate_app_sub'               : 'অ্যাপটি উপভোগ করছেন? একটি রিভিউ দিন!',
  'settings_privacy_policy_title'       : 'গোপনীয়তা নীতি',
  'settings_terms_title'                : 'সেবার শর্তাবলী',
  'settings_app_version_title'          : 'অ্যাপ সংস্করণ',
  'settings_email_error'                : 'ইমেইল অ্যাপ খুলতে পারেনি। অনুগ্রহ করে cyberinc101@gmail.com-এ ইমেইল করুন',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'সিভি প্রিভিউ',
  'preview_header_sub'                  : 'এক্সপোর্টের জন্য প্রস্তুত',
  'preview_generating'                  : 'আপনার সিভি তৈরি হচ্ছে...',
  'preview_failed_title'                : 'প্রিভিউ ব্যর্থ হয়েছে',
  'preview_failed_error'                : 'ত্রুটি: {error}',
  'preview_go_back'                     : 'ফিরে যান',
  'preview_no_data'                     : 'কোনো তথ্য পাওয়া যায়নি',
  'preview_btn_print'                   : 'প্রিন্ট',
  'preview_btn_download'                : 'ডাউনলোড ও শেয়ার',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'সাহায্য ও FAQ',
  'faq_category_all'                    : 'সব',
  'faq_empty'                           : 'কোনো ফলাফল পাওয়া যায়নি',
  'faq_contact_headline'                : 'এখনও সাহায্য দরকার?',
  'faq_contact_sub'                     : 'আমাদের টিম আপনার জন্য প্রস্তুত।',
  'faq_contact_btn'                     : 'যোগাযোগ করুন',
  'faq_email_error'                     : 'ইমেইল অ্যাপ খুলতে পারেনি। অনুগ্রহ করে cyberinc101@gmail.com-এ ইমেইল করুন',
  'faq_cat_getting_started'             : 'শুরু করা',
  'faq_cat_templates'                   : 'টেমপ্লেট',
  'faq_cat_editing'                     : 'সম্পাদনা',
  'faq_cat_exporting'                   : 'এক্সপোর্ট',
  'faq_cat_data_privacy'                : 'ডেটা ও গোপনীয়তা',
  'faq_cat_troubleshooting'             : 'সমস্যা সমাধান',
  'faq_q1'  : 'আমি কীভাবে আমার প্রথম সিভি তৈরি করব?',
  'faq_a1'  : 'একটি নতুন সিভি শুরু করতে হোম স্ক্রিনে "+" বাটনে ট্যাপ করুন। আপনার স্টাইলের সাথে মানানসই একটি টেমপ্লেট বেছে নিন, তারপর ধাপে ধাপে আপনার ব্যক্তিগত তথ্য, কাজের অভিজ্ঞতা, শিক্ষা এবং দক্ষতা পূরণ করুন। আপনার অগ্রগতি স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'faq_q2'  : 'আমি কি একাধিক সিভি তৈরি করতে পারি?',
  'faq_a2'  : 'হ্যাঁ! আপনি বিভিন্ন পদ বা শিল্পের জন্য একাধিক সিভি তৈরি করতে পারেন। প্রতিটি সিভি আলাদাভাবে সেভ হয়, তাই আপনি নির্দিষ্ট চাকরির আবেদনের জন্য সেগুলো কাস্টমাইজ করতে পারেন।',
  'faq_q3'  : 'আমি কীভাবে আমার সিভি টেমপ্লেট পরিবর্তন করব?',
  'faq_a3'  : 'আপনার সিভি খুলুন, স্ক্রিনের উপরে টেমপ্লেট আইকনে ট্যাপ করুন এবং উপলব্ধ টেমপ্লেটগুলো ব্রাউজ করুন। আপনার বিদ্যমান বিষয়বস্তু দিয়ে প্রিভিউ করতে যেকোনো টেমপ্লেটে ট্যাপ করুন। প্রয়োগ করতে নিশ্চিত করুন।',
  'faq_q4'  : 'কি বিনামূল্যে এবং প্রিমিয়াম টেমপ্লেট আছে?',
  'faq_a4'  : 'হ্যাঁ। কিছু পেশাদার টেমপ্লেট বিনামূল্যে পাওয়া যায়। উন্নত ডিজাইন এবং রঙের প্যালেট সহ প্রিমিয়াম টেমপ্লেট একবার ক্রয় বা সাবস্ক্রিপশনের মাধ্যমে পাওয়া যায়।',
  'faq_q5'  : 'আমি কীভাবে বিভাগ যোগ বা সরাব?',
  'faq_a5'  : 'সিভি এডিটরে, স্ক্রিনের নিচে স্ক্রোল করুন এবং ভাষা, সার্টিফিকেশন বা স্বেচ্ছাসেবী কাজের মতো অতিরিক্ত বিভাগ যোগ করতে "বিভাগ যোগ করুন" ট্যাপ করুন। একটি বিভাগ সরাতে, বিভাগ হেডারে ট্যাপ করুন এবং "সরান" নির্বাচন করুন।',
  'faq_q6'  : 'আমি কীভাবে বিভাগগুলো পুনর্বিন্যাস করব?',
  'faq_a6'  : 'যেকোনো বিভাগ হেডারের পাশে ড্র্যাগ হ্যান্ডেল (≡) দীর্ঘ-চাপ দিন এবং আপনার পছন্দের অবস্থানে টেনে নিয়ে যান। পরিবর্তনগুলো স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'faq_q7'  : 'আমি কীভাবে আমার সিভি পিডিএফ হিসেবে এক্সপোর্ট করব?',
  'faq_a7'  : 'আপনার সিভি খুলুন এবং উপরের ডান কোণে এক্সপোর্ট বাটনে (শেয়ার আইকন) ট্যাপ করুন। "পিডিএফ হিসেবে এক্সপোর্ট করুন" নির্বাচন করুন। তারপর আপনি এটি আপনার ডিভাইসে সেভ করতে, ইমেইল বা হোয়াটসঅ্যাপের মাধ্যমে শেয়ার করতে বা সরাসরি চাকরির বোর্ডে আপলোড করতে পারেন।',
  'faq_q8'  : 'কোন ফাইল ফরম্যাট সমর্থিত?',
  'faq_a8'  : 'বর্তমানে অ্যাপটি উচ্চ-মানের পিডিএফ হিসেবে আপনার সিভি এক্সপোর্ট করতে সমর্থন করে। ভবিষ্যতের আপডেটে অতিরিক্ত ফরম্যাট যোগ করা হতে পারে।',
  'faq_q9'  : 'আমার সিভি ডেটা কোথায় সংরক্ষিত হয়?',
  'faq_a9'  : 'আপনার সমস্ত সিভি ডেটা আপনার ডিভাইসে স্থানীয়ভাবে সংরক্ষিত হয়। আমরা আমাদের সার্ভারে আপনার ব্যক্তিগত তথ্য আপলোড করি না। এর মানে আপনার ডেটা ব্যক্তিগত থাকে এবং অফলাইনে অ্যাক্সেসযোগ্য।',
  'faq_q10' : 'আমি কীভাবে আমার সিভি ব্যাকআপ করব?',
  'faq_a10' : 'আপনার ডিভাইস সেটিংসে ব্যাকআপ সক্রিয় থাকলে আপনার সিভিগুলো আপনার ডিভাইসের স্ট্যান্ডার্ড ব্যাকআপে (অ্যান্ড্রয়েডে গুগল ড্রাইভ ব্যাকআপ, আইওএসে আইক্লাউড) অন্তর্ভুক্ত থাকে। আপনি একটি কপি রাখতে পিডিএফ হিসেবে পৃথক সিভিও এক্সপোর্ট করতে পারেন।',
  'faq_q11' : 'অ্যাপটি ধীরে চলছে। আমার কী করা উচিত?',
  'faq_a11' : 'অ্যাপটি বন্ধ করে পুনরায় খোলার চেষ্টা করুন। সমস্যা অব্যাহত থাকলে আপনার ডিভাইস পুনরায় চালু করুন। প্লে স্টোর / অ্যাপ স্টোর থেকে অ্যাপের সর্বশেষ সংস্করণ ইনস্টল আছে কিনা নিশ্চিত করুন।',
  'faq_q12' : 'আমার সিভি সঠিকভাবে এক্সপোর্ট হচ্ছে না। আমার কী করা উচিত?',
  'faq_a12' : 'আপনার ডিভাইসে পর্যাপ্ত স্টোরেজ স্পেস আছে কিনা নিশ্চিত করুন। আপনার সিভিতে বড় ছবি কমানোর চেষ্টা করুন। সমস্যা অব্যাহত থাকলে আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন।',
  'faq_q13' : 'আমি সেভ করতে ভুলে গেছি — আমার কাজ কি হারিয়ে গেছে?',
  'faq_a13' : 'মোটেও না! অ্যাপটি সম্পাদনার সময় ক্রমাগত আপনার অগ্রগতি সেভ করে।',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'আপনার ক্যারিয়ার, নিখুঁত',
  'header_tooltip_back'                 : 'ফিরে যান',
  'header_tooltip_my_cvs'               : 'আমার সিভি',
  'header_tooltip_settings'             : 'সেটিংস',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'আমার সিভি',
  'saved_count_single'                  : '{n}টি ডকুমেন্ট',
  'saved_count_plural'                  : '{n}টি ডকুমেন্ট',
  'saved_limit_reached'                 : 'সীমা পৌঁছে গেছে',
  'saved_footer_count'                  : '{n} / ৩০ সিভি',
  'saved_filter_all'                    : 'সব',
  'saved_filter_draft'                  : 'খসড়া',
  'saved_filter_complete'               : 'সম্পূর্ণ',
  'saved_status_complete'               : 'সম্পূর্ণ',
  'saved_status_saved'                  : 'সেভ হয়েছে',
  'saved_status_draft'                  : 'খসড়া',
  'saved_empty_title'                   : 'এখানে কোনো সিভি নেই',
  'saved_empty_sub'                     : 'উপরে আপনার প্রথম সিভি তৈরি শুরু করুন',
  'saved_search_empty_title'            : 'কোনো ফলাফল পাওয়া যায়নি',
  'saved_search_empty_sub'              : 'ভিন্ন সার্চ টার্ম চেষ্টা করুন',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'রঙের স্কিম',
  'custom_font_settings_title'          : 'ফন্ট সেটিংস',
  'custom_font_family_label'            : 'ফন্ট ফ্যামিলি',
  'custom_font_size_label'              : 'ফন্ট সাইজ: ',
  'custom_current_template_title'       : 'বর্তমান টেমপ্লেট',
  'custom_change_template_btn'          : 'টেমপ্লেট পরিবর্তন করুন',
  'custom_tpl_modern'                   : 'মডার্ন',
  'custom_tpl_classic'                  : 'ক্লাসিক',
  'custom_tpl_professional'             : 'প্রফেশনাল',
  'custom_tpl_creative'                 : 'ক্রিয়েটিভ',
  'custom_tpl_minimal'                  : 'মিনিমাল',
  'custom_tpl_modern_desc'              : 'পরিষ্কার ও আধুনিক ডিজাইন',
  'custom_tpl_classic_desc'             : 'ঐতিহ্যবাহী পেশাদার লেআউট',
  'custom_tpl_professional_desc'        : 'ব্যবসা-কেন্দ্রিক টেমপ্লেট',
  'custom_tpl_creative_desc'            : 'অনন্য ডিজাইনে আলাদা হয়ে উঠুন',
  'custom_tpl_minimal_desc'             : 'সরল ও মার্জিত স্টাইল',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'টেমপ্লেট বেছে নিন',
  'swipe_photo_badge'                   : 'ছবি',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'এক্সিকিউটিভ',
  'tpl_nordic_name'                     : 'নর্ডিক',
  'tpl_vibrant_name'                    : 'ভাইব্র্যান্ট',
  'tpl_tech_dark_name'                  : 'টেক ডার্ক',
  'tpl_luxury_name'                     : 'লাক্সারি',
  'tpl_executive_tag'                   : 'সবচেয়ে জনপ্রিয়',
  'tpl_nordic_tag'                      : 'পরিষ্কার',
  'tpl_vibrant_tag'                     : 'ক্রিয়েটিভ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'এলিট',
  'tpl_executive_desc'                  : 'সিনিয়র পদের জন্য সাহসী ও কর্তৃত্বশীল',
  'tpl_nordic_desc'                     : 'শীর্ষ কোম্পানিগুলোর বিশ্বস্ত নূন্যতম স্বচ্ছতা',
  'tpl_vibrant_desc'                    : 'শক্তি ও রঙে আলাদা হয়ে উঠুন',
  'tpl_tech_dark_desc'                  : 'ডেভেলপারদের জন্য টার্মিনাল নান্দনিকতা',
  'tpl_luxury_desc'                     : 'কালো পটভূমিতে স্বর্ণ-সজ্জিত মর্যাদা',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'টেমপ্লেট',
  'detail_step_personal'                : 'ব্যক্তিগত',
  'detail_step_experience'              : 'অভিজ্ঞতা',
  'detail_step_education'               : 'শিক্ষা',
  'detail_step_skills'                  : 'দক্ষতা',
  'detail_step_additional'              : 'অতিরিক্ত',
  'detail_step_references'              : 'রেফারেন্স',
  'detail_step_customize'               : 'কাস্টমাইজ',
  'detail_banner_heading'               : 'প্রায় হয়ে গেছে!',
  'detail_banner_btn'                   : 'চালিয়ে যান',
  'detail_banner_completion_label'      : 'সম্পূর্ণতা',
  'detail_stat_created_label'           : 'তৈরি হয়েছে',
  'detail_stat_steps_label'             : 'ধাপ সম্পন্ন',
  'detail_section_template_style'       : 'টেমপ্লেট স্টাইল',
  'detail_section_steps'                : 'ধাপসমূহ',
  'detail_steps_counter'                : '{total}টির মধ্যে {done}টি সম্পন্ন',
  'detail_step_sub'                     : '{total}টির মধ্যে ধাপ {n}',
  'detail_section_activity'             : 'কার্যক্রম',
  'detail_activity_created'             : 'তৈরি হয়েছে',
  'detail_activity_last_edited'         : 'সর্বশেষ সম্পাদিত',
  'detail_activity_template'            : 'টেমপ্লেট',
  'detail_btn_continue_editing'         : 'সম্পাদনা চালিয়ে যান',
  'detail_btn_edit_cv'                  : 'সিভি সম্পাদনা করুন',
  'detail_option_rename'                : 'সিভি নাম পরিবর্তন করুন',
  'detail_option_delete'                : 'সিভি মুছুন',
  'detail_rename_title'                 : 'সিভি নাম পরিবর্তন করুন',
  'detail_rename_hint'                  : 'যেমন: সফটওয়্যার ইঞ্জিনিয়ার সিভি',
  'detail_rename_error_empty'           : 'নাম খালি রাখা যাবে না',
  'detail_rename_btn_cancel'            : 'বাতিল',
  'detail_rename_btn_save'              : 'সেভ করুন',
  'detail_rename_snackbar'              : '"{name}" নামে পরিবর্তিত হয়েছে',
  'detail_delete_title'                 : 'সিভি মুছবেন?',
  'detail_delete_body'                  : 'এটি "{name}" স্থায়ীভাবে মুছে ফেলবে। এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
  'detail_delete_btn_cancel'            : 'বাতিল',
  'detail_delete_btn_confirm'           : 'মুছুন',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'সম্পন্ন',
  'detail_check_tile_incomplete'        : 'এখনও পূরণ করা হয়নি',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'আপনার টেমপ্লেট বেছে নিন',
  'chooser_subtitle'                    : 'ব্রাউজ করতে সোয়াইপ করুন  ·  নির্বাচন করতে ট্যাপ করুন  ·  প্রিভিউ করতে ধরে রাখুন',
  'chooser_card_hold_hint'              : 'প্রিভিউ করতে ধরে রাখুন',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'নির্বাচিত',
  'chooser_modal_heading'               : 'আপনার সিভির নাম দিন',
  'chooser_modal_sub'                   : 'এটিকে একটি নাম দিন যাতে আপনি সহজেই আমার সিভি এবং ইতিহাসে খুঁজে পান।',
  'chooser_modal_field_label'           : 'সিভির নাম',
  'chooser_modal_save_btn'              : 'সেভ করুন এবং তৈরি শুরু করুন',
  'chooser_modal_divider'               : 'অথবা একটি বিদ্যমান সিভি চালিয়ে যান',
  'chooser_nav_selected_sub'            : 'নির্বাচিত টেমপ্লেট',
  'chooser_nav_cta'                     : 'সেভ করুন এবং চালিয়ে যান',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'সর্বোচ্চ এন্ট্রি সংখ্যায় পৌঁছে গেছে',
  'editor_show_hide'                    : 'দেখান/লুকান',
  'editor_editing_badge'                : 'সম্পাদনা হচ্ছে',
  'editor_field_required'               : 'আবশ্যক',
  'editor_tooltip_edit'                 : 'সম্পাদনা করুন',
  'editor_tooltip_delete'               : 'মুছুন',
  'editor_date_start'                   : 'শুরুর তারিখ *',
  'editor_date_end'                     : 'শেষের তারিখ *',
  'editor_date_tap_hint'                : 'নির্বাচন করতে ট্যাপ করুন',
  'editor_date_dialog_title'            : 'মাস ও বছর নির্বাচন করুন',
  'editor_date_confirm'                 : 'নিশ্চিত করুন',
  'editor_panel_hide'                   : 'লুকান',
  'editor_panel_show'                   : 'দেখান',
  'editor_validator_max_chars'          : 'সর্বোচ্চ {n} অক্ষর',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'আপনার সিভি তৈরি করুন',
  'editor_header_step_sub'              : 'ধাপ {current} / {total} · {label}',
  'editor_step_template'                : 'টেমপ্লেট',
  'editor_step_personal'                : 'ব্যক্তিগত',
  'editor_step_experience'              : 'অভিজ্ঞতা',
  'editor_step_education'               : 'শিক্ষা',
  'editor_step_skills'                  : 'দক্ষতা',
  'editor_step_additional'              : 'অতিরিক্ত',
  'editor_step_references'              : 'রেফারেন্স',
  'editor_step_customize'               : 'কাস্টমাইজ',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'কাস্টমাইজ',
  'customize_subtitle'                  : 'আপনার সিভিকে অনন্য করে তুলুন',
  'customize_smart_layout_btn'          : 'স্মার্ট লেআউট',
  'customize_back_to_top'               : 'উপরে ফিরে যান',
  'customize_done_title'                : 'সব প্রস্তুত!',
  'customize_done_sub'                  : 'আপনার সম্পন্ন সিভি দেখতে নিচে Preview CV ট্যাপ করুন',
  'customize_preview_btn'               : 'সিভি প্রিভিউ',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'রঙের স্কিম',
  'color_black'                         : 'কালো',
  'color_blue'                          : 'নীল',
  'color_nordic_blue'                   : 'নর্ডিক নীল',
  'color_indigo'                        : 'ইন্ডিগো',
  'color_teal'                          : 'টিল',
  'color_green'                         : 'সবুজ',
  'color_purple'                        : 'বেগুনি',
  'color_orange'                        : 'কমলা',
  'color_red'                           : 'লাল',
  'color_executive_gold'                : 'এক্সিকিউটিভ গোল্ড',
  'color_vibrant_coral'                 : 'ভাইব্র্যান্ট কোরাল',
  'color_white'                         : 'সাদা',
  'color_white_bg'                      : 'সাদা ব্যাকগ্রাউন্ড',
  'color_maroon'                        : 'মেরুন',
  'color_brutalist_yellow'              : 'ব্রুটালিস্ট হলুদ',
  'color_neon_blue'                     : 'নিয়ন নীল',
  'color_blueprint_navy'                : 'ব্লুপ্রিন্ট নেভি',
  'color_light_grey'                    : 'হালকা ধূসর',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'ফন্ট ফ্যামিলি',
  'customize_font_picker_title'         : 'ফন্ট বেছে নিন',
  'customize_font_picker_sub'           : 'প্রতিটি ফন্ট নিজস্ব টাইপফেসে প্রিভিউ করা হয়',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'ফন্ট সাইজ',
  'customize_font_size_label'           : 'টেক্সট সাইজ',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '১০ pt',
  'customize_font_size_max'             : '১৬ pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'ছবির সাইজ',
  'customize_image_size_label'          : 'ছবির সাইজ',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '১০ px',
  'customize_image_size_max'            : '১৬ px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'লাইভ প্রিভিউ',
  'preview_page_count_singular'         : '১ পৃষ্ঠা',
  'preview_page_count_plural'           : '{n} পৃষ্ঠা',
  'preview_page_of'                     : '{total}টির মধ্যে পৃষ্ঠা {page}',
  'preview_live_hint'                   : 'পরিবর্তন তাৎক্ষণিকভাবে প্রয়োগ হয়',
  'preview_template_unregistered'       : 'customize_preview.dart-এ এখনও নিবন্ধিত নয়',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'আপনার সিভি প্রস্তুত হচ্ছে…',
  'preview_bar_print'                   : 'প্রিন্ট',
  'preview_bar_save_pdf'                : 'পিডিএফ হিসেবে সেভ করুন',
  'preview_bar_share'                   : 'শেয়ার করুন',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'সিভি প্রিভিউ',
  'preview_screen_sub'                  : '{n} {unit} · ঠিক মুদ্রণের মতো',
  'preview_page_singular'               : 'পৃষ্ঠা',
  'preview_page_plural'                 : 'পৃষ্ঠা',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'আমার সিভি',
  'preview_snack_print_failed'          : 'প্রিন্ট ব্যর্থ হয়েছে: {e}',
  'preview_snack_saved'                 : 'সিভি ডাউনলোডসে সেভ হয়েছে ✓',
  'preview_snack_export_failed'         : 'এক্সপোর্ট ব্যর্থ হয়েছে: {e}',
  'preview_snack_share_failed'          : 'শেয়ার ব্যর্থ হয়েছে: {e}',
  'preview_template_not_registered'     : 'টেমপ্লেট নিবন্ধিত নয়',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'প্রিভিউ বন্ধ করুন',
  'preview_modal_hint_photo'            : 'প্রোফাইল ছবি সমর্থন করে  ·  নির্বাচন করতে একটি কার্ডে ট্যাপ করুন',
  'preview_modal_hint_no_photo'         : 'নির্বাচন করতে একটি টেমপ্লেট কার্ডে ট্যাপ করুন',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'আমার সিভি',
  'time_just_now'                       : 'এইমাত্র',
  'time_minutes_ago'                    : '{n} মিনিট আগে',
  'time_hours_ago'                      : '{n} ঘণ্টা আগে',
  'time_yesterday'                      : 'গতকাল',
  'time_days_ago'                       : '{n} দিন আগে',
  'time_one_week_ago'                   : '১ সপ্তাহ আগে',
  'time_weeks_ago'                      : '{n} সপ্তাহ আগে',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'মার্জিত',
  'tpl_tag_classic'                     : 'ক্লাসিক',
  'tpl_tag_minimal'                     : 'মিনিমাল',
  'tpl_tag_creative'                    : 'ক্রিয়েটিভ',
  'tpl_tag_bold'                        : 'সাহসী',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'গ্র্যাডিয়েন্ট',
  'tpl_gradient_desc'                   : 'টিল থেকে ভায়োলেট গ্র্যাডিয়েন্ট কার্ড',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'এডিটোরিয়াল',
  'tpl_editorial_desc'                  : 'ম্যাগাজিন স্টাইল লাল ও ক্রিম',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'প্যাস্টেল সফট',
  'tpl_pastel_soft_desc'                : 'ল্যাভেন্ডার সাইডবার, নরম কার্ড',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'ব্রুটালিস্ট',
  'tpl_brutalist_desc'                  : 'কাঁচা গ্রিড, সাহসী বর্ডার ও হলুদ',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'এমারেল্ড',
  'tpl_emerald_desc'                    : 'টাইমলাইন সহ বনসবুজ',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'ইনফোগ্রাফিক',
  'tpl_infographic_desc'                : 'রিং চার্ট সহ ডার্ক ক্যানভাস',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'আর্ট ডেকো',
  'tpl_art_deco_desc'                   : '১৯২০-এর দশকের জ্যামিতিক সোনালী বিলাসিতা',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'উইনা ডার্ক',
  'tpl_wina_dark_desc'                  : 'রিং সহ ডার্ক ইনফোগ্রাফিক',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'রিও অরেঞ্জ',
  'tpl_rio_orange_desc'                 : 'কমলা পপ সহ ডার্ক সাইডবার',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'সামার',
  'tpl_summer_desc'                     : 'পরিষ্কার মিনিমাল, নরম ধূসর টোন',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'হেলেন',
  'tpl_helene_desc'                     : 'উষ্ণ বেইজ মার্জিত টোন',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'ক্যানফিল্ড',
  'tpl_canfield_desc'                   : 'কঠোর কালো ও সাদা ক্লাসিক',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'কলিন্স',
  'tpl_collins_desc'                    : 'ক্লাসিক ATS-বান্ধব লেআউট',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'টনি ডার্ক',
  'tpl_tony_dark_desc'                  : 'ডার্ক কমলা ইনফোগ্রাফিক স্টাইল',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'ফ্যাশন',
  'tpl_fashion_desc'                    : 'গ্রিডে টেকনিক্যাল ড্রয়িং',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'আর্কিভিস্ট',
  'tpl_archivist_desc'                  : 'ক্লাসিক দুই-কলাম লেবেল লেআউট',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'ডিপ্লোম্যাট',
  'tpl_diplomat_desc'                   : 'ডায়মন্ড লিডার সহ শেডেড হেডার',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'মেরিডিয়ান',
  'tpl_meridian_desc'                   : 'কেন্দ্রিক হেডার, অ্যাকসেন্ট কোম্পানি',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'মোমেন্টাম',
  'tpl_momentum_desc'                   : 'সাহসী নাম, টাইমলাইন ডট ও অর্জন',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'ব্যক্তিগত তথ্য',
  'personal_subtitle'                   : 'নিয়োগকর্তাদের জানান আপনি কে',
  'personal_profile_counter'            : '{n}/{max}টি প্রোফাইল',
  'personal_info_banner'                : '৫টি পর্যন্ত প্রোফাইল সেভ করুন এবং প্রতিটি সিভিতে একটি নির্বাচন করুন। আপনার নির্বাচন প্রতিটি সিভির জন্য আলাদাভাবে মনে রাখা হয়।',
  'personal_snack_max'                  : 'সর্বোচ্চ {n}টি প্রোফাইলে পৌঁছে গেছে।',
  'personal_add_btn'                    : 'নতুন প্রোফাইল যোগ করুন',
  'personal_library_title'              : 'সেভ করা প্রোফাইল',
  'personal_selected_one'               : '১টি নির্বাচিত',
  'personal_selected_none'              : 'কোনোটি নির্বাচিত নয়',
  'personal_library_hint'               : 'শুধুমাত্র এই সিভির জন্য নির্বাচন করতে একটি কার্ডে ট্যাপ করুন। অন্য সিভিগুলো তাদের নিজস্ব স্বাধীন নির্বাচন রাখে।',
  'personal_empty_message'              : 'এখনও কোনো প্রোফাইল সেভ করা হয়নি',
  'personal_empty_sub'                  : 'আপনার ব্যক্তিগত তথ্য যোগ করতে উপরে ট্যাপ করুন',
  'personal_nav_next'                   : 'সেভ করুন এবং চালিয়ে যান',
  'personal_card_active_badge'          : 'এই সিভির জন্য সক্রিয়',
  'personal_sheet_title_add'            : 'নতুন প্রোফাইল',
  'personal_sheet_title_edit'           : 'প্রোফাইল সম্পাদনা করুন',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'ব্রুটালিস্ট টেমপ্লেটে কম্প্যাক্ট কন্টাক্ট ফিল্ড রয়েছে। ছোট মান (যেমন শুধু শহর) সবচেয়ে ভালো দেখায়।',
  'personal_section_photo'              : 'প্রোফাইল ছবি',
  'personal_section_basic'              : 'মূল বিবরণ',
  'personal_section_contact'            : 'যোগাযোগ',
  'personal_section_online'             : 'অনলাইন উপস্থিতি',
  'personal_section_summary'            : 'পেশাদার সারসংক্ষেপ',
  'personal_field_first_name'           : 'প্রথম নাম *',
  'personal_field_last_name'            : 'শেষ নাম',
  'personal_field_job_title'            : 'পদের নাম *',
  'personal_field_email'                : 'ইমেইল ঠিকানা *',
  'personal_field_phone'                : 'ফোন নম্বর *',
  'personal_field_location'             : 'অবস্থান',
  'personal_field_location_brut'        : 'অবস্থান (শুধু শহর)',
  'personal_field_website'              : 'ওয়েবসাইট / পোর্টফোলিও',
  'personal_field_linkedin'             : 'লিংকডইন URL',
  'personal_hint_first_name'            : 'যেমন: করিম',
  'personal_hint_last_name'             : 'যেমন: হোসেন',
  'personal_hint_job_title'             : 'যেমন: সিনিয়র ইঞ্জিনিয়ার',
  'personal_hint_email'                 : 'যেমন: karim@example.com',
  'personal_hint_phone'                 : 'যেমন: +880 1711 123456',
  'personal_hint_location'              : 'যেমন: ঢাকা, বাংলাদেশ',
  'personal_hint_location_brut'         : 'যেমন: ঢাকা, BD',
  'personal_hint_website'               : 'যেমন: github.com/karimhossain',
  'personal_hint_website_brut'          : 'যেমন: github.com/karim',
  'personal_hint_linkedin'              : 'যেমন: linkedin.com/in/karimhossain',
  'personal_hint_linkedin_brut'         : 'যেমন: linkedin.com/in/karim',
  'personal_summary_hint_label'         : 'সংক্ষিপ্ত রাখুন — এটি আপনার সিভির উপরে দেখা যায়।',
  'personal_hint_summary'               : 'আপনার পটভূমি ও লক্ষ্যের একটি সংক্ষিপ্ত ২–৩ বাক্যের সারসংক্ষেপ...',
  'personal_validator_email'            : 'একটি বৈধ ইমেইল প্রবেশ করুন',
  'personal_field_char_limit_tooltip'   : 'অক্ষর সীমায় পৌঁছে গেছে',
  'personal_sheet_btn_save'             : 'প্রোফাইল সেভ করুন',
  'personal_sheet_btn_update'           : 'পরিবর্তন সেভ করুন',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'ছবি বেছে নিন',
  'photo_option_gallery'                : 'গ্যালারি থেকে বেছে নিন',
  'photo_option_camera'                 : 'ছবি তুলুন',
  'photo_option_reposition'             : 'ছবি পুনর্বিন্যাস করুন',
  'photo_option_remove'                 : 'ছবি সরান',
  'photo_status_added'                  : 'ছবি যোগ হয়েছে ✓',
  'photo_status_empty'                  : 'একটি পেশাদার হেডশট যোগ করুন',
  'photo_chip_gallery'                  : 'গ্যালারি',
  'photo_chip_camera'                   : 'ক্যামেরা',
  'photo_chip_reposition'               : 'পুনর্বিন্যাস',
  'photo_reposition_title'              : 'ছবি পুনর্বিন্যাস করুন',
  'photo_reposition_sub'                : 'অবস্থান সামঞ্জস্য করতে ছবি টেনে নিন',
  'photo_reposition_reset'              : 'কেন্দ্রে রিসেট করুন',
  'photo_reposition_apply'              : 'প্রয়োগ করুন',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'দক্ষতা',
  'skills_subtitle'                     : 'আপনার মূল দক্ষতাগুলো তুলে ধরুন',
  'skills_add_btn'                      : 'নতুন দক্ষতা যোগ করুন',
  'skills_snack_max_icons'              : 'সর্বোচ্চ ১০টি আইকন নির্বাচিত।',
  'skills_snack_max_skills'             : 'সর্বোচ্চ ১৫টি দক্ষতায় পৌঁছে গেছে।',
  'skills_library_title'                : 'সেভ করা দক্ষতা',
  'skills_library_hint'                 : 'চেক করা দক্ষতাগুলো এই সিভিতে অন্তর্ভুক্ত। আপনার নির্বাচন স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'skills_nav_next'                     : 'অতিরিক্তে চালিয়ে যান',
  'skills_wina_header_icon_bar'         : 'হেডার আইকন বার',
  'skills_wina_on'                      : 'চালু',
  'skills_wina_off'                     : 'বন্ধ',
  'skills_wina_bar_on_sub'              : 'সিভি হেডারে রঙিন আইকন বৃত্ত দেখানো হয়।',
  'skills_wina_bar_off_sub'             : 'আইকন সারি লুকানো — যোগাযোগ তথ্যের জন্য বেশি জায়গা।',
  'skills_wina_palette_hint'            : 'আইকনগুলো প্যালেট ক্রমে রঙিন বৃত্ত হিসেবে দেখা যায়।',
  'skills_wina_preview_label'           : 'প্রিভিউ',
  'skills_wina_disabled_hint'           : 'সিভি হেডারে কোন আইকন দেখাবে তা বেছে নিতে উপরের আইকন বার সক্রিয় করুন।',
  'skills_sheet_title_add'              : 'দক্ষতা যোগ করুন',
  'skills_sheet_title_edit'             : 'দক্ষতা সম্পাদনা করুন',
  'skills_sheet_field_name'             : 'দক্ষতার নাম *',
  'skills_sheet_hint_short'             : 'যেমন: Flutter, ডিজাইন',
  'skills_sheet_hint_long'              : 'যেমন: Flutter, প্রজেক্ট ম্যানেজমেন্ট',
  'skills_sheet_validator_max'          : 'সর্বোচ্চ {n} অক্ষর',
  'skills_sheet_proficiency'            : 'দক্ষতার স্তর',
  'skills_sheet_beginner'               : 'শিক্ষানবিশ',
  'skills_sheet_expert'                 : 'বিশেষজ্ঞ',
  'skills_sheet_btn_save'               : 'দক্ষতা সেভ করুন',
  'skills_sheet_btn_update'             : 'দক্ষতা আপডেট করুন',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'ব্যক্তিগত রেফারেন্স',
  'refs_subtitle'                       : 'যারা ব্যক্তিগতভাবে আপনার জন্য সুপারিশ করতে পারেন',
  'refs_add_btn'                        : 'নতুন ব্যক্তিগত রেফারেন্স যোগ করুন',
  'refs_snack_max_selected'             : 'একটি সিভিতে সর্বোচ্চ ৪টি রেফারেন্স নির্বাচন করা যাবে।',
  'refs_snack_max_saved'                : 'সর্বোচ্চ ১০টি সেভ করা রেফারেন্সে পৌঁছে গেছে।',
  'refs_library_title'                  : 'সেভ করা রেফারেন্স',
  'refs_library_hint'                   : 'চেক করা রেফারেন্সগুলো এই সিভিতে অন্তর্ভুক্ত। প্রতি সিভিতে সর্বোচ্চ ৪টি। আপনার নির্বাচন স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'refs_nav_next'                       : 'কাস্টমাইজে চালিয়ে যান',
  'refs_sheet_title_add'                : 'ব্যক্তিগত রেফারেন্স যোগ করুন',
  'refs_sheet_title_edit'               : 'ব্যক্তিগত রেফারেন্স সম্পাদনা করুন',
  'refs_sheet_sub_add'                  : 'যিনি নিয়োগকর্তাদের কাছে ব্যক্তিগতভাবে আপনাকে সুপারিশ করতে পারেন।',
  'refs_sheet_sub_edit'                 : 'নিচে এই রেফারেন্সের বিবরণ আপডেট করুন।',
  'refs_sheet_field_name'               : 'পুরো নাম *',
  'refs_sheet_field_title'              : 'পদের নাম *',
  'refs_sheet_field_company'            : 'কোম্পানি (ঐচ্ছিক)',
  'refs_sheet_field_email'              : 'ইমেইল ঠিকানা *',
  'refs_sheet_field_phone'              : 'ফোন নম্বর *',
  'refs_sheet_hint_name'                : 'যেমন: রাহেলা বেগম',
  'refs_sheet_hint_title'               : 'যেমন: ইঞ্জিনিয়ারিং ম্যানেজার',
  'refs_sheet_hint_company'             : 'যেমন: Acme Corp',
  'refs_sheet_hint_email'               : 'যেমন: rahela@acme.com',
  'refs_sheet_hint_phone'               : 'যেমন: +880 1711 123456',
  'refs_sheet_validator_email'          : 'একটি বৈধ ইমেইল ঠিকানা প্রবেশ করুন',
  'refs_sheet_btn_save'                 : 'ব্যক্তিগত রেফারেন্স সেভ করুন',
  'refs_sheet_btn_update'               : 'ব্যক্তিগত রেফারেন্স আপডেট করুন',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'কাজের অভিজ্ঞতা',
  'exp_subtitle'                        : 'আপনার কাজের ইতিহাস যোগ করুন',
  'exp_banner_info'                     : 'প্রতিটি পদের জন্য {n}টি পর্যন্ত দায়িত্ব সিভিতে দেখা যাবে। ৩–৬টি পদ সাধারণত ১–২ পৃষ্ঠায় ফিট হয়।',
  'exp_add_btn'                         : 'নতুন অভিজ্ঞতা যোগ করুন',
  'exp_snack_max_selected'              : 'একটি সিভিতে সর্বোচ্চ ৮টি অভিজ্ঞতা নির্বাচন করা যাবে।',
  'exp_snack_max_saved'                 : 'সর্বোচ্চ ১২টি সেভ করা অভিজ্ঞতায় পৌঁছে গেছে।',
  'exp_library_title'                   : 'সেভ করা অভিজ্ঞতা',
  'exp_library_hint'                    : 'চেক করা এন্ট্রিগুলো শুধুমাত্র এই সিভিতে অন্তর্ভুক্ত। অন্য সিভিগুলো তাদের নিজস্ব স্বাধীন নির্বাচন রাখে।',
  'exp_nav_next'                        : 'শিক্ষায় চালিয়ে যান',
  'exp_empty_message'                   : 'এখনও কোনো অভিজ্ঞতা যোগ করা হয়নি',
  'exp_empty_sub'                       : 'আপনার প্রথম পদ যোগ করতে উপরে ট্যাপ করুন',
  'exp_card_resp_singular'              : 'দায়িত্ব',
  'exp_card_resp_plural'                : 'দায়িত্ব',
  'exp_card_resp_tooltip'               : 'শুধুমাত্র প্রথম ৮টি দায়িত্ব সিভিতে দেখা যাবে',
  'exp_sheet_title_add'                 : 'অভিজ্ঞতা যোগ করুন',
  'exp_sheet_title_edit'                : 'অভিজ্ঞতা সম্পাদনা করুন',
  'exp_sheet_field_job_title'           : 'পদের নাম *',
  'exp_sheet_field_company'             : 'কোম্পানি *',
  'exp_sheet_field_location'            : 'অবস্থান',
  'exp_sheet_section_responsibilities'  : 'মূল দায়িত্বসমূহ',
  'exp_sheet_resp_hint_info'            : 'সর্বোচ্চ ৮টি বুলেট পয়েন্ট · প্রতিটি ২০০ অক্ষর',
  'exp_sheet_resp_label'                : 'দায়িত্ব {n}',
  'exp_sheet_resp_hint'                 : 'যেমন: ৫ জন ইঞ্জিনিয়ারের টিম নেতৃত্ব দিয়েছি',
  'exp_sheet_resp_add_btn'              : 'দায়িত্ব যোগ করুন',
  'exp_sheet_resp_max_info'             : 'সর্বোচ্চ {n}টি দায়িত্বে পৌঁছে গেছে',
  'exp_sheet_resp_validator_max'        : 'সর্বোচ্চ ২০০ অক্ষর',
  'exp_sheet_hint_job_title'            : 'যেমন: সিনিয়র ডেভেলপার',
  'exp_sheet_hint_location'             : 'যেমন: ঢাকা, বাংলাদেশ',
  'exp_sheet_btn_save'                  : 'অভিজ্ঞতা সেভ করুন',
  'exp_sheet_btn_update'                : 'পরিবর্তন সেভ করুন',
  'exp_date_present'                    : 'বর্তমান / চলমান পদ',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'শিক্ষা',
  'edu_subtitle'                        : 'আপনার শিক্ষাগত পটভূমি যোগ করুন',
  'edu_add_btn'                         : 'নতুন শিক্ষা যোগ করুন',
  'edu_snack_max_selected'              : 'একটি সিভিতে সর্বোচ্চ ৮টি শিক্ষাগত এন্ট্রি নির্বাচন করা যাবে।',
  'edu_snack_max_saved'                 : 'সর্বোচ্চ ১২টি সেভ করা শিক্ষাগত এন্ট্রিতে পৌঁছে গেছে।',
  'edu_library_title'                   : 'সেভ করা শিক্ষা',
  'edu_library_hint'                    : 'চেক করা এন্ট্রিগুলো এই সিভিতে অন্তর্ভুক্ত। আপনার নির্বাচন স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'edu_nav_next'                        : 'দক্ষতায় চালিয়ে যান',
  'edu_empty_message'                   : 'এখনও কোনো শিক্ষা যোগ করা হয়নি',
  'edu_empty_sub'                       : 'আপনার যোগ্যতা যোগ করতে উপরে ট্যাপ করুন',
  'edu_card_bullet_singular'            : 'বুলেট পয়েন্ট',
  'edu_card_bullet_plural'              : 'বুলেট পয়েন্ট',
  'edu_sheet_title_add'                 : 'শিক্ষা যোগ করুন',
  'edu_sheet_title_edit'                : 'শিক্ষা সম্পাদনা করুন',
  'edu_sheet_field_degree'              : 'ডিগ্রি / যোগ্যতা *',
  'edu_sheet_field_institution'         : 'প্রতিষ্ঠান *',
  'edu_sheet_section_key_points'        : 'মূল বিষয়সমূহ',
  'edu_sheet_key_points_hint_info'      : 'ঐচ্ছিক · ১টি বুলেট পয়েন্ট · সর্বোচ্চ ১০০ অক্ষর',
  'edu_sheet_point_label'               : 'বিষয় {n}',
  'edu_sheet_point_add_btn'             : 'বুলেট পয়েন্ট যোগ করুন',
  'edu_sheet_point_max_info'            : 'সর্বোচ্চ {n}টি বুলেট পয়েন্টে পৌঁছে গেছে',
  'edu_sheet_point_validator_max'       : 'সর্বোচ্চ {n} অক্ষর',
  'edu_sheet_hint_degree'               : 'যেমন: BSc কম্পিউটার সায়েন্স',
  'edu_sheet_hint_institution'          : 'যেমন: ঢাকা বিশ্ববিদ্যালয়',
  'edu_sheet_hint_bullet'               : 'যেমন: প্রথম শ্রেণী সম্মান',
  'edu_sheet_btn_save'                  : 'শিক্ষা সেভ করুন',
  'edu_sheet_btn_update'                : 'পরিবর্তন সেভ করুন',
  'edu_date_present'                    : 'বর্তমান / চলমান পড়াশোনা',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'অতিরিক্ত তথ্য',
  'additional_subtitle'                 : 'সার্টিফিকেশন, ভাষা ও আরও',
  'additional_cert_section_title'       : 'সার্টিফিকেশন',
  'additional_cert_counter'             : '{sel}/{total}টি নির্বাচিত · সর্বোচ্চ {max}',
  'additional_cert_hide'                : 'লুকান',
  'additional_cert_show'                : 'দেখান',
  'additional_cert_add_btn'             : 'যোগ করুন',
  'additional_cert_snack_max'           : 'সর্বোচ্চ {n}টি সার্টিফিকেশন এন্ট্রিতে পৌঁছে গেছে।',
  'additional_cert_hint'                : 'চেক করা এন্ট্রিগুলো এই সিভিতে অন্তর্ভুক্ত। আপনার নির্বাচন স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'additional_cert_empty'               : 'এখনও কোনো সার্টিফিকেশন যোগ করা হয়নি',
  'additional_lang_section_title'       : 'ভাষা',
  'additional_lang_add_hint'            : 'যেমন: স্প্যানিশ',
  'additional_lang_snack_max'           : 'সর্বোচ্চ {n}টি ভাষা এন্ট্রিতে পৌঁছে গেছে।',
  'additional_lang_empty'               : 'এখনও কোনো ভাষা যোগ করা হয়নি',
  'additional_hobby_section_title'      : 'শখ ও আগ্রহ',
  'additional_hobby_add_hint'           : 'যেমন: ফটোগ্রাফি',
  'additional_hobby_snack_max'          : 'সর্বোচ্চ {n}টি শখ এন্ট্রিতে পৌঁছে গেছে।',
  'additional_hobby_empty'              : 'এখনও কোনো শখ যোগ করা হয়নি',
  'additional_section_hint'             : 'চেক করা এন্ট্রিগুলো এই সিভিতে অন্তর্ভুক্ত। আপনার নির্বাচন স্বয়ংক্রিয়ভাবে সেভ হয়।',
  'additional_nav_next'                 : 'রেফারিতে চালিয়ে যান',
  'cert_sheet_title_add'                : 'সার্টিফিকেশন যোগ করুন',
  'cert_sheet_title_edit'               : 'সার্টিফিকেশন সম্পাদনা করুন',
  'cert_sheet_sub'                      : 'একটি যোগ্যতা, সার্টিফিকেট বা পেশাদার স্বীকৃতি যোগ করুন।',
  'cert_sheet_field_name'               : 'সার্টিফিকেশনের নাম *',
  'cert_sheet_field_issued_by'          : 'ইস্যুকারী (ঐচ্ছিক)',
  'cert_sheet_field_short_desc'         : 'সংক্ষিপ্ত বিবরণ (ঐচ্ছিক)',
  'cert_sheet_hint_name'                : 'যেমন: AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'যেমন: Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'যেমন: ২০২৪ সালে অর্জিত',
  'cert_sheet_btn_save'                 : 'সার্টিফিকেশন সেভ করুন',
  'cert_sheet_btn_update'               : 'সার্টিফিকেশন আপডেট করুন',
  'simple_sheet_title_add_language'     : 'ভাষা যোগ করুন',
  'simple_sheet_title_edit_language'    : 'ভাষা সম্পাদনা করুন',
  'simple_sheet_title_add_hobby'        : 'শখ যোগ করুন',
  'simple_sheet_title_edit_hobby'       : 'শখ সম্পাদনা করুন',
  'simple_sheet_btn_save'               : 'সেভ করুন',
  'simple_sheet_btn_update'             : 'আপডেট করুন',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'যোগাযোগ',
  'pdf_section_about_me'                : 'আমার সম্পর্কে',
  'pdf_section_summary'                 : 'সারসংক্ষেপ',
  'pdf_section_summary_short'           : 'সারসংক্ষেপ',
  'pdf_section_profile'                 : 'প্রোফাইল',
  'pdf_section_experience'              : 'অভিজ্ঞতা',
  'pdf_section_experience_short'        : 'অভিজ্ঞতা',
  'pdf_section_education'               : 'শিক্ষা',
  'pdf_section_skills'                  : 'দক্ষতা',
  'pdf_section_languages'               : 'ভাষা',
  'pdf_label_email'                     : 'ইমেইল',
  'pdf_label_phone'                     : 'ফোন',
  'pdf_label_location'                  : 'অবস্থান',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV সীমা পূর্ণ হয়েছে',
  'limit_dialog_body'                   : 'আপনি সর্বোচ্চ ৩০টি CV-তে পৌঁছেছেন। নতুন তৈরি করার আগে একটি বিদ্যমান CV মুছুন।',
  'limit_dialog_go_to_my_cvs'           : 'আমার CVs-এ যান',
  'limit_dialog_cancel'                 : 'বাতিল',
  'refs_count_summary'                  : '{checked}/{maxChecked} নির্বাচিত · {saved}/{maxSaved} সংরক্ষিত',
  'refs_selected_badge'                 : '{n} নির্বাচিত',
  'refs_empty_message'                  : 'এখনও কোনো রেফারেন্স সংরক্ষিত নেই',
  'refs_empty_sub'                      : 'একটি ব্যক্তিগত রেফারেন্স যোগ করতে উপরে ট্যাপ করুন',
};