// lib/language_keys/lang_he_hebrew.dart
//
// Hebrew (Israel) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> heHebrew = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'לא נמצאו שפות',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'דלג',
  'onboarding_next'                     : 'הבא',
  'onboarding_get_started'              : 'בואו נתחיל',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  ברוך הבא',
  'ob1_title'                           : 'צור קורות חיים\nשפותחים דלתות',
  'ob1_body'                            : 'תבלוט מבין מאות מועמדים. בנה קורות חיים מקצועיים ומנצחים תוך דקות — ללא צורך בכישורי עיצוב.',
  'ob1_pill_label'                      : 'בונה קורות חיים מקצועי',
  'ob1_chip_templates'                  : '24+ תבניות',
  'ob1_chip_pdf'                        : 'ייצוא PDF',
  'ob1_chip_free'                       : 'חינם לשימוש',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  תבניות',
  'ob2_title'                           : 'כל תעשייה.\nכל שאיפה.',
  'ob2_body'                            : 'מפריסות מוכנות לחדר הישיבות ועד עיצובים יצירתיים נועזים — תבנית שמספרת את הסיפור שלך.',
  'ob2_tap_hint'                        : 'הקש על כל תבנית לתצוגה מקדימה',
  'ob2_tpl_executive'                   : 'מנהלים',
  'ob2_tpl_vibrant'                     : 'תוסס',
  'ob2_tpl_nordic'                      : 'נורדי',
  'ob2_tpl_tech_dark'                   : 'טכנולוגי כהה',
  'ob2_tpl_luxury'                      : 'יוקרה',
  'ob2_tag_corporate'                   : 'עסקי',
  'ob2_tag_creative'                    : 'יצירתי',
  'ob2_tag_minimal'                     : 'מינימלי',
  'ob2_tag_modern'                      : 'מודרני',
  'ob2_tag_premium'                     : 'פרמיום',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  פריסה חכמה',
  'ob3_title'                           : 'קורות החיים שלך.\nמסודרים בצורה מושלמת.',
  'ob3_body'                            : 'פריסה חכמה מסדרת מחדש את הסעיפים שלך להשפעה מרבית — ומציבה את התוכן החזק ביותר שלך במקום שהמגייסים מסתכלים בו ראשית.',
  'ob3_badge_smart_layout'              : 'פריסה חכמה',
  'ob3_badge_cv_ready'                  : 'קורות חיים מוכנים!',
  'ob3_step1_label'                     : 'בחר תבנית',
  'ob3_step1_desc'                      : 'בחר מתוך 24+ עיצובים מרהיבים.',
  'ob3_step2_label'                     : 'מלא את הפרטים',
  'ob3_step2_desc'                      : 'שדות מודרכים לכל הסעיפים.',
  'ob3_step3_label'                     : 'פריסה חכמה',
  'ob3_step3_desc'                      : 'הקשה אחת מסדרת את קורות החיים בצורה מושלמת.',
  'ob3_step4_label'                     : 'ייצא כ-PDF',
  'ob3_step4_desc'                      : 'PDF מושלם פיקסל מוכן לשליחה.',
  'ob3_section_work'                    : 'ניסיון עבודה',
  'ob3_section_education'               : 'השכלה',
  'ob3_section_skills'                  : 'כישורים',
  'ob3_section_references'              : 'ממליצים',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  מוכן להתחיל',
  'ob4_title'                           : 'מדוע מועמדים מובילים\nבוחרים ב-CV Builder',
  'ob4_visual_headline'                 : 'הכל מוכן!',
  'ob4_visual_subline'                  : 'כל מה שצריך כדי לקבל את העבודה.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'תבניות',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'מקסימום קורות חיים',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'ייצוא',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'פרטי',
  'ob4_hl1_title'                       : 'פרטי ומאובטח',
  'ob4_hl1_sub'                         : 'הנתונים נשמרים במכשיר שלך.',
  'ob4_hl2_title'                       : 'שמירה אוטומטית',
  'ob4_hl2_sub'                         : 'כל הקשה נשמרת מיד.',
  'ob4_hl3_title'                       : 'עד 30 קורות חיים',
  'ob4_hl3_sub'                         : 'קורות חיים ייחודיים לכל תפקיד.',
  'ob4_hl4_title'                       : 'שיתוף בהקשה אחת',
  'ob4_hl4_sub'                         : 'שלח PDF מבלי לצאת מהאפליקציה.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ תבלוט מהקהל',
  'home_hero_title'                     : 'צור את קורות\nהחיים המקצועיים שלך',
  'home_hero_sub'                       : 'בנה קורות חיים מרשימים\nתוך דקות',
  'home_hero_cta'                       : 'התחל לבנות',
  'home_premium_soon'                   : 'שדרוג לגרסת Pro בקרוב!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'האחרון ביותר',
  'history_sort_alphabetical'           : 'א–ת',
  'history_sort_last_edited'            : 'עריכה אחרונה',
  'history_sort_by_template'            : 'לפי תבנית',
  'history_sort_sheet_title'            : 'מיין לפי',
  'history_sort_alphabetical_full'      : 'אלפביתי (א–ת)',
  'history_premium_soon'                : 'שדרוג לגרסת Pro בקרוב!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'הגדרות',
  'settings_section_preferences'        : 'העדפות',
  'settings_section_support'            : 'תמיכה',
  'settings_section_legal'              : 'משפטי',
  'settings_section_about'              : 'אודות',
  'settings_language_tile_title'        : 'שפה',
  'settings_dark_mode_title'            : 'מצב כהה',
  'settings_dark_mode_on'               : 'ערכת נושא כהה מופעלת',
  'settings_dark_mode_off'              : 'ערכת נושא בהירה מופעלת',
  'settings_help_faq_title'             : 'עזרה ושאלות נפוצות',
  'settings_help_faq_sub'               : 'תשובות לשאלות נפוצות',
  'settings_contact_support_title'      : 'פנה לתמיכה',
  'settings_rate_app_title'             : 'דרג את האפליקציה',
  'settings_rate_app_sub'               : 'נהנה מהאפליקציה? השאר ביקורת!',
  'settings_privacy_policy_title'       : 'מדיניות פרטיות',
  'settings_terms_title'                : 'תנאי שירות',
  'settings_app_version_title'          : 'גרסת אפליקציה',
  'settings_email_error'                : 'לא ניתן לפתוח את אפליקציית האימייל. אנא שלח אימייל ל-cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'תצוגה מקדימה של קורות חיים',
  'preview_header_sub'                  : 'מוכן לייצוא',
  'preview_generating'                  : 'מייצר את קורות החיים שלך...',
  'preview_failed_title'                : 'התצוגה המקדימה נכשלה',
  'preview_failed_error'                : 'שגיאה: {error}',
  'preview_go_back'                     : 'חזור אחורה',
  'preview_no_data'                     : 'אין נתונים זמינים',
  'preview_btn_print'                   : 'הדפס',
  'preview_btn_download'                : 'הורד ושתף',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'עזרה ושאלות נפוצות',
  'faq_category_all'                    : 'הכל',
  'faq_empty'                           : 'לא נמצאו תוצאות',
  'faq_contact_headline'                : 'עדיין זקוק לעזרה?',
  'faq_contact_sub'                     : 'הצוות שלנו כאן בשבילך.',
  'faq_contact_btn'                     : 'צור קשר',
  'faq_email_error'                     : 'לא ניתן לפתוח את אפליקציית האימייל. אנא שלח אימייל ל-cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'תחילת עבודה',
  'faq_cat_templates'                   : 'תבניות',
  'faq_cat_editing'                     : 'עריכה',
  'faq_cat_exporting'                   : 'ייצוא',
  'faq_cat_data_privacy'                : 'נתונים ופרטיות',
  'faq_cat_troubleshooting'             : 'פתרון בעיות',
  'faq_q1'  : 'כיצד אני יוצר את קורות החיים הראשונים שלי?',
  'faq_a1'  : 'הקש על כפתור "+" במסך הבית כדי להתחיל קורות חיים חדשים. בחר תבנית המתאימה לסגנון שלך, ולאחר מכן מלא את הפרטים האישיים, ניסיון העבודה, ההשכלה והכישורים שלך שלב אחר שלב. ההתקדמות שלך נשמרת אוטומטית.',
  'faq_q2'  : 'האם ניתן ליצור יותר מקורות חיים אחד?',
  'faq_a2'  : 'כן! ניתן ליצור מספר קורות חיים לתפקידים או תעשיות שונות. כל קורות חיים נשמרים בנפרד, כך שניתן להתאים אותם לבקשות עבודה ספציפיות.',
  'faq_q3'  : 'כיצד אני משנה את תבנית קורות החיים שלי?',
  'faq_a3'  : 'פתח את קורות החיים שלך, הקש על סמל התבנית בראש המסך, ועיין בתבניות הזמינות. הקש על כל תבנית לתצוגה מקדימה עם התוכן הקיים שלך. אשר להחיל אותה.',
  'faq_q4'  : 'האם יש תבניות חינמיות ופרמיום?',
  'faq_a4'  : 'כן. מבחר תבניות מקצועיות זמין בחינם. תבניות פרמיום עם עיצובים מתקדמים וצבעים זמינות דרך רכישה חד-פעמית או מנוי.',
  'faq_q5'  : 'כיצד אני מוסיף או מסיר סעיפים?',
  'faq_a5'  : 'בעורך קורות החיים, גלול לתחתית המסך והקש על "הוסף סעיף" כדי לכלול תוספות כמו שפות, הסמכות או עבודה התנדבותית. כדי להסיר סעיף, הקש על כותרת הסעיף ובחר "הסר".',
  'faq_q6'  : 'כיצד אני מסדר מחדש את הסעיפים?',
  'faq_a6'  : 'לחץ לחיצה ארוכה על ידית הגרירה (≡) ליד כל כותרת סעיף וגרור אותה למיקום הרצוי. השינויים נשמרים אוטומטית.',
  'faq_q7'  : 'כיצד אני מייצא את קורות החיים שלי כ-PDF?',
  'faq_a7'  : 'פתח את קורות החיים שלך והקש על כפתור הייצוא (סמל שיתוף) בפינה הימנית העליונה. בחר "ייצא כ-PDF". לאחר מכן תוכל לשמור אותו במכשירך, לשתפו באמצעות אימייל, WhatsApp, או להעלותו ישירות ללוחות דרושים.',
  'faq_q8'  : 'אילו פורמטי קבצים נתמכים?',
  'faq_a8'  : 'כרגע האפליקציה תומכת בייצוא קורות החיים שלך כ-PDF באיכות גבוהה. פורמטים נוספים עשויים להתווסף בעדכונים עתידיים.',
  'faq_q9'  : 'היכן מאוחסנים נתוני קורות החיים שלי?',
  'faq_a9'  : 'כל נתוני קורות החיים שלך מאוחסנים באופן מקומי במכשיר שלך. אנחנו לא מעלים את המידע האישי שלך לשרתים שלנו. המשמעות היא שהנתונים שלך נשארים פרטיים ונגישים גם במצב לא מקוון.',
  'faq_q10' : 'כיצד אני מגבה את קורות החיים שלי?',
  'faq_a10' : 'קורות החיים שלך כלולים בגיבוי הסטנדרטי של המכשיר שלך (גיבוי Google Drive ב-Android, iCloud ב-iOS) אם הגיבוי מופעל בהגדרות המכשיר. ניתן גם לייצא קורות חיים בודדים כ-PDF לשמירת עותק.',
  'faq_q11' : 'האפליקציה פועלת לאט. מה עלי לעשות?',
  'faq_a11' : 'נסה לסגור ולפתוח מחדש את האפליקציה. אם הבעיה נמשכת, הפעל מחדש את המכשיר שלך. ודא שיש לך את הגרסה העדכנית של האפליקציה מ-Play Store / App Store.',
  'faq_q12' : 'קורות החיים שלי לא מייצאים כראוי. מה עלי לעשות?',
  'faq_a12' : 'ודא שיש מספיק שטח אחסון במכשיר שלך. נסה להקטין תמונות גדולות בקורות החיים שלך. אם הבעיה נמשכת, אנא פנה לצוות התמיכה שלנו.',
  'faq_q13' : 'שכחתי לשמור — האם העבודה שלי אבדה?',
  'faq_a13' : 'בכלל לא! האפליקציה שומרת את ההתקדמות שלך באופן רציף בזמן שאתה עורך.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'הקריירה שלך, בצורה מושלמת',
  'header_tooltip_back'                 : 'חזור',
  'header_tooltip_my_cvs'               : 'קורות החיים שלי',
  'header_tooltip_settings'             : 'הגדרות',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'קורות החיים שלי',
  'saved_count_single'                  : 'מסמך {n}',
  'saved_count_plural'                  : '{n} מסמכים',
  'saved_limit_reached'                 : 'הגעת למגבלה',
  'saved_footer_count'                  : '{n} / 30 קורות חיים',
  'saved_filter_all'                    : 'הכל',
  'saved_filter_draft'                  : 'טיוטה',
  'saved_filter_complete'               : 'הושלם',
  'saved_status_complete'               : 'הושלם',
  'saved_status_saved'                  : 'נשמר',
  'saved_status_draft'                  : 'טיוטה',
  'saved_empty_title'                   : 'אין קורות חיים עדיין',
  'saved_empty_sub'                     : 'התחל לבנות את קורות החיים הראשונים שלך למעלה',
  'saved_search_empty_title'            : 'לא נמצאו תוצאות',
  'saved_search_empty_sub'              : 'נסה מונח חיפוש אחר',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'ערכת צבעים',
  'custom_font_settings_title'          : 'הגדרות גופן',
  'custom_font_family_label'            : 'משפחת גופן',
  'custom_font_size_label'              : 'גודל גופן: ',
  'custom_current_template_title'       : 'תבנית נוכחית',
  'custom_change_template_btn'          : 'שנה תבנית',
  'custom_tpl_modern'                   : 'מודרני',
  'custom_tpl_classic'                  : 'קלאסי',
  'custom_tpl_professional'             : 'מקצועי',
  'custom_tpl_creative'                 : 'יצירתי',
  'custom_tpl_minimal'                  : 'מינימלי',
  'custom_tpl_modern_desc'              : 'עיצוב נקי ועכשווי',
  'custom_tpl_classic_desc'             : 'פריסה מקצועית מסורתית',
  'custom_tpl_professional_desc'        : 'תבנית ממוקדת עסקים',
  'custom_tpl_creative_desc'            : 'תבלוט עם עיצוב ייחודי',
  'custom_tpl_minimal_desc'             : 'סגנון פשוט ואלגנטי',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'בחר תבנית',
  'swipe_photo_badge'                   : 'תמונה',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'מנהלים',
  'tpl_nordic_name'                     : 'נורדי',
  'tpl_vibrant_name'                    : 'תוסס',
  'tpl_tech_dark_name'                  : 'טכנולוגי כהה',
  'tpl_luxury_name'                     : 'יוקרה',
  'tpl_executive_tag'                   : 'הפופולרי ביותר',
  'tpl_nordic_tag'                      : 'נקי',
  'tpl_vibrant_tag'                     : 'יצירתי',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'עילית',
  'tpl_executive_desc'                  : 'נועז וסמכותי לתפקידים בכירים',
  'tpl_nordic_desc'                     : 'בהירות מינימלית אמינה בחברות מובילות',
  'tpl_vibrant_desc'                    : 'תבלוט עם אנרגיה וצבע',
  'tpl_tech_dark_desc'                  : 'אסתטיקת טרמינל למפתחים',
  'tpl_luxury_desc'                     : 'יוקרה בהדגשות זהב על רקע שחור',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'תבנית',
  'detail_step_personal'                : 'אישי',
  'detail_step_experience'              : 'ניסיון',
  'detail_step_education'               : 'השכלה',
  'detail_step_skills'                  : 'כישורים',
  'detail_step_additional'              : 'נוסף',
  'detail_step_references'              : 'ממליצים',
  'detail_step_customize'               : 'התאמה אישית',
  'detail_banner_heading'               : 'כמעט שם!',
  'detail_banner_btn'                   : 'המשך',
  'detail_banner_completion_label'      : 'השלמה',
  'detail_stat_created_label'           : 'נוצר',
  'detail_stat_steps_label'             : 'שלבים הושלמו',
  'detail_section_template_style'       : 'סגנון תבנית',
  'detail_section_steps'                : 'שלבים',
  'detail_steps_counter'                : '{done} מתוך {total} הושלמו',
  'detail_step_sub'                     : 'שלב {n} מתוך {total}',
  'detail_section_activity'             : 'פעילות',
  'detail_activity_created'             : 'נוצר',
  'detail_activity_last_edited'         : 'עריכה אחרונה',
  'detail_activity_template'            : 'תבנית',
  'detail_btn_continue_editing'         : 'המשך עריכה',
  'detail_btn_edit_cv'                  : 'ערוך קורות חיים',
  'detail_option_rename'                : 'שנה שם לקורות חיים',
  'detail_option_delete'                : 'מחק קורות חיים',
  'detail_rename_title'                 : 'שנה שם לקורות חיים',
  'detail_rename_hint'                  : 'לדוגמה: קורות חיים מהנדס תוכנה',
  'detail_rename_error_empty'           : 'השם לא יכול להיות ריק',
  'detail_rename_btn_cancel'            : 'בטל',
  'detail_rename_btn_save'              : 'שמור',
  'detail_rename_snackbar'              : 'שונה שם ל-"{name}"',
  'detail_delete_title'                 : 'למחוק את קורות החיים?',
  'detail_delete_body'                  : 'פעולה זו תמחק לצמיתות את "{name}". לא ניתן לבטל פעולה זו.',
  'detail_delete_btn_cancel'            : 'בטל',
  'detail_delete_btn_confirm'           : 'מחק',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'הושלם',
  'detail_check_tile_incomplete'        : 'טרם מולא',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'בחר את התבנית שלך',
  'chooser_subtitle'                    : 'החלק לעיון  ·  הקש לבחירה  ·  לחץ לתצוגה מקדימה',
  'chooser_card_hold_hint'              : 'לחץ לתצוגה מקדימה',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'נבחר',
  'chooser_modal_heading'               : 'תן שם לקורות החיים שלך',
  'chooser_modal_sub'                   : 'תן לו שם כדי שתוכל למצוא אותו בקלות בקורות החיים שלי ובהיסטוריה.',
  'chooser_modal_field_label'           : 'שם קורות החיים',
  'chooser_modal_save_btn'              : 'שמור והתחל לבנות',
  'chooser_modal_divider'               : 'או המשך עם קורות חיים קיימים',
  'chooser_nav_selected_sub'            : 'תבנית נבחרת',
  'chooser_nav_cta'                     : 'שמור והמשך',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'הגעת למספר המרבי של ערכים',
  'editor_show_hide'                    : 'הצג/הסתר',
  'editor_editing_badge'                : 'עריכה',
  'editor_field_required'               : 'חובה',
  'editor_tooltip_edit'                 : 'ערוך',
  'editor_tooltip_delete'               : 'מחק',
  'editor_date_start'                   : 'תאריך התחלה *',
  'editor_date_end'                     : 'תאריך סיום *',
  'editor_date_tap_hint'                : 'הקש לבחירה',
  'editor_date_dialog_title'            : 'בחר חודש ושנה',
  'editor_date_confirm'                 : 'אשר',
  'editor_panel_hide'                   : 'הסתר',
  'editor_panel_show'                   : 'הצג',
  'editor_validator_max_chars'          : 'מקסימום {n} תווים',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'בנה את קורות החיים שלך',
  'editor_header_step_sub'              : 'שלב {current} מתוך {total} · {label}',
  'editor_step_template'                : 'תבנית',
  'editor_step_personal'                : 'אישי',
  'editor_step_experience'              : 'ניסיון',
  'editor_step_education'               : 'השכלה',
  'editor_step_skills'                  : 'כישורים',
  'editor_step_additional'              : 'נוסף',
  'editor_step_references'              : 'ממליצים',
  'editor_step_customize'               : 'התאמה אישית',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'התאמה אישית',
  'customize_subtitle'                  : 'הפוך את קורות החיים שלך לייחודיים',
  'customize_smart_layout_btn'          : 'פריסה חכמה',
  'customize_back_to_top'               : 'חזור למעלה',
  'customize_done_title'                : 'הכל מוכן!',
  'customize_done_sub'                  : 'הקש על "תצוגה מקדימה של קורות חיים" למטה כדי לראות את קורות החיים המוגמרים שלך',
  'customize_preview_btn'               : 'תצוגה מקדימה של קורות חיים',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'ערכת צבעים',
  'color_black'                         : 'שחור',
  'color_blue'                          : 'כחול',
  'color_nordic_blue'                   : 'כחול נורדי',
  'color_indigo'                        : 'אינדיגו',
  'color_teal'                          : 'טיל',
  'color_green'                         : 'ירוק',
  'color_purple'                        : 'סגול',
  'color_orange'                        : 'כתום',
  'color_red'                           : 'אדום',
  'color_executive_gold'                : 'זהב מנהלים',
  'color_vibrant_coral'                 : 'אלמוג תוסס',
  'color_white'                         : 'לבן',
  'color_white_bg'                      : 'רקע לבן',
  'color_maroon'                        : 'בורדו',
  'color_brutalist_yellow'              : 'צהוב ברוטליסטי',
  'color_neon_blue'                     : 'כחול ניאון',
  'color_blueprint_navy'                : 'כחול כהה טכני',
  'color_light_grey'                    : 'אפור בהיר',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'משפחת גופן',
  'customize_font_picker_title'         : 'בחר גופן',
  'customize_font_picker_sub'           : 'כל גופן מוצג בסגנון שלו',
  'customize_font_preview_sample'       : 'הגופן המהיר החום',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'גודל גופן',
  'customize_font_size_label'           : 'גודל טקסט',
  'customize_font_size_value'           : '{n} נק\'',
  'customize_font_size_min'             : '10 נק\'',
  'customize_font_size_max'             : '16 נק\'',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'גודל תמונה',
  'customize_image_size_label'          : 'גודל תמונה',
  'customize_image_size_value'          : '{n} פיקסל',
  'customize_image_size_min'            : '10 פיקסל',
  'customize_image_size_max'            : '16 פיקסל',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'תצוגה מקדימה חיה',
  'preview_page_count_singular'         : 'עמוד 1',
  'preview_page_count_plural'           : '{n} עמודים',
  'preview_page_of'                     : 'עמוד {page} מתוך {total}',
  'preview_live_hint'                   : 'שינויים מוחלים מיד',
  'preview_template_unregistered'       : 'טרם רשום ב-customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'מכין את קורות החיים שלך…',
  'preview_bar_print'                   : 'הדפס',
  'preview_bar_save_pdf'                : 'שמור כ-PDF',
  'preview_bar_share'                   : 'שתף',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'תצוגה מקדימה של קורות חיים',
  'preview_screen_sub'                  : '{n} {unit} · בדיוק כפי שיודפס',
  'preview_page_singular'               : 'עמוד',
  'preview_page_plural'                 : 'עמודים',
  'preview_pdf_filename'                : 'קורות_חיים_שלי',
  'preview_share_subject'               : 'קורות החיים שלי',
  'preview_snack_print_failed'          : 'ההדפסה נכשלה: {e}',
  'preview_snack_saved'                 : 'קורות החיים נשמרו בהורדות ✓',
  'preview_snack_export_failed'         : 'הייצוא נכשל: {e}',
  'preview_snack_share_failed'          : 'השיתוף נכשל: {e}',
  'preview_template_not_registered'     : 'התבנית אינה רשומה',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'סגור תצוגה מקדימה',
  'preview_modal_hint_photo'             : 'תומך בתמונת פרופיל  ·  הקש על כרטיס לבחירה',
  'preview_modal_hint_no_photo'          : 'הקש על כרטיס תבנית לבחירה',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'קורות החיים שלי',
  'time_just_now'                       : 'הרגע',
  'time_minutes_ago'                    : 'לפני {n} דקות',
  'time_hours_ago'                      : 'לפני {n} שעות',
  'time_yesterday'                      : 'אתמול',
  'time_days_ago'                       : 'לפני {n} ימים',
  'time_one_week_ago'                   : 'לפני שבוע',
  'time_weeks_ago'                      : 'לפני {n} שבועות',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'אלגנטי',
  'tpl_tag_classic'                     : 'קלאסי',
  'tpl_tag_minimal'                     : 'מינימלי',
  'tpl_tag_creative'                    : 'יצירתי',
  'tpl_tag_bold'                        : 'נועז',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'גרדיאנט',
  'tpl_gradient_desc'                   : 'כרטיסי גרדיאנט מטיל לסגול',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'עיתונאי',
  'tpl_editorial_desc'                  : 'סגנון מגזין אדום וקרם',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'פסטל רך',
  'tpl_pastel_soft_desc'                : 'סרגל צד לבנדר, כרטיסים רכים',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'ברוטליסטי',
  'tpl_brutalist_desc'                  : 'רשת גולמית, גבולות נועזים וצהוב',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'אמרלד',
  'tpl_emerald_desc'                    : 'ירוק יער עם ציר זמן',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'אינפוגרפיקה',
  'tpl_infographic_desc'                : 'בד כהה עם תרשימי טבעת',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'ארט דקו',
  'tpl_art_deco_desc'                   : 'יוקרת זהב גיאומטרית משנות ה-20',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'וינה כהה',
  'tpl_wina_dark_desc'                  : 'אינפוגרפיקה כהה עם טבעות',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'ריו כתום',
  'tpl_rio_orange_desc'                 : 'סרגל צד כהה עם נגיעת כתום',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'קיץ',
  'tpl_summer_desc'                     : 'נקי ומינימלי, גוני אפור רך',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'הלן',
  'tpl_helene_desc'                     : 'גוני בז\' אלגנטיים וחמים',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'קנפילד',
  'tpl_canfield_desc'                   : 'קלאסי שחור ולבן בולט',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'קולינס',
  'tpl_collins_desc'                    : 'פריסה קלאסית ידידותית ל-ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'טוני כהה',
  'tpl_tony_dark_desc'                  : 'סגנון אינפוגרפיקה כתום כהה',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'אופנה',
  'tpl_fashion_desc'                    : 'ציור טכני על רשת',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'ארכיוניסט',
  'tpl_archivist_desc'                  : 'פריסת תוויות קלאסית בשתי עמודות',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'דיפלומט',
  'tpl_diplomat_desc'                   : 'כותרות מוצללות עם מובילי יהלום',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'מרידיאן',
  'tpl_meridian_desc'                   : 'כותרות מרכוזיות, חברות מודגשות',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'מומנטום',
  'tpl_momentum_desc'                   : 'שם נועז, נקודות ציר זמן והישגים',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'פרטים אישיים',
  'personal_subtitle'                   : 'ספר למעסיקים מי אתה',
  'personal_profile_counter'            : '{n}/{max} פרופילים',
  'personal_info_banner'                : 'שמור עד 5 פרופילים ובחר אחד לכל קורות חיים. הבחירה שלך נשמרת בנפרד עבור כל קורות חיים.',
  'personal_snack_max'                  : 'הגעת למקסימום של {n} פרופילים.',
  'personal_add_btn'                    : 'הוסף פרופיל חדש',
  'personal_library_title'              : 'פרופילים שמורים',
  'personal_selected_one'               : '1 נבחר',
  'personal_selected_none'              : 'לא נבחר',
  'personal_library_hint'               : 'הקש על כרטיס לבחירה עבור קורות חיים אלה בלבד. קורות חיים אחרים שומרים על הבחירות העצמאיות שלהם.',
  'personal_empty_message'              : 'אין פרופילים שמורים עדיין',
  'personal_empty_sub'                  : 'הקש למעלה להוספת הפרטים האישיים שלך',
  'personal_nav_next'                   : 'שמור והמשך',
  'personal_card_active_badge'          : 'פעיל עבור קורות חיים אלה',
  'personal_sheet_title_add'            : 'פרופיל חדש',
  'personal_sheet_title_edit'           : 'ערוך פרופיל',
  'personal_sheet_brutalist_badge'      : 'ברוטליסטי',
  'personal_sheet_brutalist_banner'     : 'תבנית ברוטליסטית מכילה שדות יצירת קשר קומפקטיים. ערכים קצרים יותר (לדוגמה: עיר בלבד) מוצגים בצורה הטובה ביותר.',
  'personal_section_photo'              : 'תמונת פרופיל',
  'personal_section_basic'              : 'פרטים בסיסיים',
  'personal_section_contact'            : 'יצירת קשר',
  'personal_section_online'             : 'נוכחות מקוונת',
  'personal_section_summary'            : 'סיכום מקצועי',
  'personal_field_first_name'           : 'שם פרטי *',
  'personal_field_last_name'            : 'שם משפחה',
  'personal_field_job_title'            : 'כותרת תפקיד *',
  'personal_field_email'                : 'כתובת אימייל *',
  'personal_field_phone'                : 'מספר טלפון *',
  'personal_field_location'             : 'מיקום',
  'personal_field_location_brut'        : 'מיקום (עיר בלבד)',
  'personal_field_website'              : 'אתר אינטרנט / תיק עבודות',
  'personal_field_linkedin'             : 'קישור LinkedIn',
  'personal_hint_first_name'            : 'לדוגמה: דנה',
  'personal_hint_last_name'             : 'לדוגמה: כהן',
  'personal_hint_job_title'             : 'לדוגמה: מהנדס בכיר',
  'personal_hint_email'                 : 'לדוגמה: dana@example.com',
  'personal_hint_phone'                 : 'לדוגמה: +972 50 123 4567',
  'personal_hint_location'              : 'לדוגמה: תל אביב, ישראל',
  'personal_hint_location_brut'         : 'לדוגמה: תל אביב',
  'personal_hint_website'               : 'לדוגמה: github.com/danacohen',
  'personal_hint_website_brut'          : 'לדוגמה: github.com/dana',
  'personal_hint_linkedin'              : 'לדוגמה: linkedin.com/in/danacohen',
  'personal_hint_linkedin_brut'         : 'לדוגמה: linkedin.com/in/dana',
  'personal_summary_hint_label'         : 'שמור על תמציתיות — הסיכום מופיע בראש קורות החיים שלך.',
  'personal_hint_summary'               : 'סיכום קצר של 2–3 משפטים על הרקע שלך ומטרותיך...',
  'personal_validator_email'            : 'הזן כתובת אימייל תקינה',
  'personal_field_char_limit_tooltip'   : 'הגעת למגבלת התווים',
  'personal_sheet_btn_save'             : 'שמור פרופיל',
  'personal_sheet_btn_update'           : 'שמור שינויים',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'בחר תמונה',
  'photo_option_gallery'                : 'בחר מהגלריה',
  'photo_option_camera'                 : 'צלם תמונה',
  'photo_option_reposition'             : 'שנה מיקום תמונה',
  'photo_option_remove'                 : 'הסר תמונה',
  'photo_status_added'                  : 'תמונה נוספה ✓',
  'photo_status_empty'                  : 'הוסף תמונת ראש מקצועית',
  'photo_chip_gallery'                  : 'גלריה',
  'photo_chip_camera'                   : 'מצלמה',
  'photo_chip_reposition'               : 'שנה מיקום',
  'photo_reposition_title'              : 'שנה מיקום תמונה',
  'photo_reposition_sub'                : 'גרור את התמונה לכוונון המיקום',
  'photo_reposition_reset'              : 'איפוס למרכז',
  'photo_reposition_apply'              : 'החל',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'כישורים',
  'skills_subtitle'                     : 'הדגש את היכולות המרכזיות שלך',
  'skills_add_btn'                      : 'הוסף כישור חדש',
  'skills_snack_max_icons'              : 'נבחרו מקסימום 10 סמלים.',
  'skills_snack_max_skills'             : 'הגעת למקסימום של 15 כישורים.',
  'skills_library_title'                : 'כישורים שמורים',
  'skills_library_hint'                 : 'כישורים מסומנים כלולים בקורות חיים אלה. הבחירות שלך נשמרות אוטומטית.',
  'skills_nav_next'                     : 'המשך למידע נוסף',
  'skills_wina_header_icon_bar'         : 'סרגל סמלי כותרת',
  'skills_wina_on'                      : 'מופעל',
  'skills_wina_off'                     : 'כבוי',
  'skills_wina_bar_on_sub'              : 'עיגולי סמלים צבעוניים מוצגים בכותרת קורות החיים.',
  'skills_wina_bar_off_sub'             : 'שורת הסמלים מוסתרת — יותר מקום לפרטי יצירת קשר.',
  'skills_wina_palette_hint'            : 'סמלים מופיעים כעיגולים צבעוניים בסדר הפלטה.',
  'skills_wina_preview_label'           : 'תצוגה מקדימה',
  'skills_wina_disabled_hint'           : 'הפעל את סרגל הסמלים למעלה כדי לבחור אילו סמלים יופיעו בכותרת קורות החיים.',
  'skills_sheet_title_add'              : 'הוסף כישור',
  'skills_sheet_title_edit'             : 'ערוך כישור',
  'skills_sheet_field_name'             : 'שם הכישור *',
  'skills_sheet_hint_short'             : 'לדוגמה: Flutter, עיצוב',
  'skills_sheet_hint_long'              : 'לדוגמה: Flutter, ניהול פרויקטים',
  'skills_sheet_validator_max'          : 'מקסימום {n} תווים',
  'skills_sheet_proficiency'            : 'רמת מיומנות',
  'skills_sheet_beginner'               : 'מתחיל',
  'skills_sheet_expert'                 : 'מומחה',
  'skills_sheet_btn_save'               : 'שמור כישור',
  'skills_sheet_btn_update'             : 'עדכן כישור',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'ממליצים אישיים',
  'refs_subtitle'                       : 'אנשים שיכולים להמליץ עליך אישית',
  'refs_add_btn'                        : 'הוסף ממליץ אישי חדש',
  'refs_snack_max_selected'             : 'ניתן לבחור מקסימום 4 ממליצים עבור קורות חיים.',
  'refs_snack_max_saved'                : 'הגעת למקסימום של 10 ממליצים שמורים.',
  'refs_library_title'                  : 'ממליצים שמורים',
  'refs_library_hint'                   : 'ממליצים מסומנים כלולים בקורות חיים אלה. מקסימום 4 לכל קורות חיים. הבחירות שלך נשמרות אוטומטית.',
  'refs_nav_next'                       : 'המשך להתאמה אישית',
  'refs_sheet_title_add'                : 'הוסף ממליץ אישי',
  'refs_sheet_title_edit'               : 'ערוך ממליץ אישי',
  'refs_sheet_sub_add'                  : 'מישהו שיכול להמליץ עליך אישית למעסיקים.',
  'refs_sheet_sub_edit'                 : 'עדכן את פרטי הממליץ למטה.',
  'refs_sheet_field_name'               : 'שם מלא *',
  'refs_sheet_field_title'              : 'כותרת תפקיד *',
  'refs_sheet_field_company'            : 'חברה (אופציונלי)',
  'refs_sheet_field_email'              : 'כתובת אימייל *',
  'refs_sheet_field_phone'              : 'מספר טלפון *',
  'refs_sheet_hint_name'                : 'לדוגמה: יעקב לוי',
  'refs_sheet_hint_title'               : 'לדוגמה: מנהל הנדסה',
  'refs_sheet_hint_company'             : 'לדוגמה: חברת Acme',
  'refs_sheet_hint_email'               : 'לדוגמה: yaakov@acme.com',
  'refs_sheet_hint_phone'               : 'לדוגמה: +972 50 123 4567',
  'refs_sheet_validator_email'          : 'הזן כתובת אימייל תקינה',
  'refs_sheet_btn_save'                 : 'שמור ממליץ אישי',
  'refs_sheet_btn_update'               : 'עדכן ממליץ אישי',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'ניסיון עבודה',
  'exp_subtitle'                        : 'הוסף את היסטוריית העבודה שלך',
  'exp_banner_info'                     : 'עד {n} תחומי אחריות לכל תפקיד יופיעו בקורות החיים. 3–6 תפקידים בדרך כלל מתאימים ל-1–2 עמודים.',
  'exp_add_btn'                         : 'הוסף ניסיון חדש',
  'exp_snack_max_selected'              : 'ניתן לבחור מקסימום 8 ניסיונות עבודה עבור קורות חיים.',
  'exp_snack_max_saved'                 : 'הגעת למקסימום של 12 ניסיונות עבודה שמורים.',
  'exp_library_title'                   : 'ניסיונות עבודה שמורים',
  'exp_library_hint'                    : 'ערכים מסומנים כלולים בקורות חיים אלה בלבד. קורות חיים אחרים שומרים על הבחירות העצמאיות שלהם.',
  'exp_nav_next'                        : 'המשך להשכלה',
  'exp_empty_message'                   : 'טרם נוסף ניסיון עבודה',
  'exp_empty_sub'                       : 'הקש למעלה להוספת התפקיד הראשון שלך',
  'exp_card_resp_singular'              : 'תחום אחריות',
  'exp_card_resp_plural'                : 'תחומי אחריות',
  'exp_card_resp_tooltip'               : 'רק 8 תחומי האחריות הראשונים יופיעו בקורות החיים',
  'exp_sheet_title_add'                 : 'הוסף ניסיון',
  'exp_sheet_title_edit'                : 'ערוך ניסיון',
  'exp_sheet_field_job_title'           : 'כותרת תפקיד *',
  'exp_sheet_field_company'             : 'חברה *',
  'exp_sheet_field_location'            : 'מיקום',
  'exp_sheet_section_responsibilities'  : 'תחומי אחריות מרכזיים',
  'exp_sheet_resp_hint_info'            : 'מקסימום 8 נקודות · 200 תווים לכל אחת',
  'exp_sheet_resp_label'                : 'אחריות {n}',
  'exp_sheet_resp_hint'                 : 'לדוגמה: הובלתי צוות של 5 מהנדסים',
  'exp_sheet_resp_add_btn'              : 'הוסף אחריות',
  'exp_sheet_resp_max_info'             : 'הגעת למקסימום של {n} תחומי אחריות',
  'exp_sheet_resp_validator_max'        : 'מקסימום 200 תווים',
  'exp_sheet_hint_job_title'            : 'לדוגמה: מפתח בכיר',
  'exp_sheet_hint_location'             : 'לדוגמה: תל אביב, ישראל',
  'exp_sheet_btn_save'                  : 'שמור ניסיון',
  'exp_sheet_btn_update'                : 'שמור שינויים',
  'exp_date_present'                    : 'הווה / תפקיד נוכחי',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'השכלה',
  'edu_subtitle'                        : 'הוסף את הרקע האקדמי שלך',
  'edu_add_btn'                         : 'הוסף השכלה חדשה',
  'edu_snack_max_selected'              : 'ניתן לבחור מקסימום 8 רשומות השכלה עבור קורות חיים.',
  'edu_snack_max_saved'                 : 'הגעת למקסימום של 12 רשומות השכלה שמורות.',
  'edu_library_title'                   : 'השכלה שמורה',
  'edu_library_hint'                    : 'ערכים מסומנים כלולים בקורות חיים אלה. הבחירות שלך נשמרות אוטומטית.',
  'edu_nav_next'                        : 'המשך לכישורים',
  'edu_empty_message'                   : 'טרם נוספה השכלה',
  'edu_empty_sub'                       : 'הקש למעלה להוספת הכישורים האקדמיים שלך',
  'edu_card_bullet_singular'            : 'נקודת תבליט',
  'edu_card_bullet_plural'              : 'נקודות תבליט',
  'edu_sheet_title_add'                 : 'הוסף השכלה',
  'edu_sheet_title_edit'                : 'ערוך השכלה',
  'edu_sheet_field_degree'              : 'תואר / כישור *',
  'edu_sheet_field_institution'         : 'מוסד *',
  'edu_sheet_section_key_points'        : 'נקודות מרכזיות',
  'edu_sheet_key_points_hint_info'      : 'אופציונלי · נקודת תבליט 1 · מקסימום 100 תווים',
  'edu_sheet_point_label'               : 'נקודה {n}',
  'edu_sheet_point_add_btn'             : 'הוסף נקודת תבליט',
  'edu_sheet_point_max_info'            : 'הגעת למקסימום של {n} נקודות תבליט',
  'edu_sheet_point_validator_max'       : 'מקסימום {n} תווים',
  'edu_sheet_hint_degree'               : 'לדוגמה: תואר ראשון במדעי המחשב',
  'edu_sheet_hint_institution'          : 'לדוגמה: אוניברסיטת תל אביב',
  'edu_sheet_hint_bullet'               : 'לדוגמה: הצטיינות',
  'edu_sheet_btn_save'                  : 'שמור השכלה',
  'edu_sheet_btn_update'                : 'שמור שינויים',
  'edu_date_present'                    : 'הווה / לימודים נוכחיים',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'מידע נוסף',
  'additional_subtitle'                 : 'הסמכות, שפות ועוד',
  'additional_cert_section_title'       : 'הסמכות',
  'additional_cert_counter'             : '{sel}/{total} נבחרו · מקסימום {max}',
  'additional_cert_hide'                : 'הסתר',
  'additional_cert_show'                : 'הצג',
  'additional_cert_add_btn'             : 'הוסף',
  'additional_cert_snack_max'           : 'הגעת למקסימום של {n} הסמכות.',
  'additional_cert_hint'                : 'ערכים מסומנים כלולים בקורות חיים אלה. הבחירות שלך נשמרות אוטומטית.',
  'additional_cert_empty'               : 'טרם נוספו הסמכות',
  'additional_lang_section_title'       : 'שפות',
  'additional_lang_add_hint'            : 'לדוגמה: ספרדית',
  'additional_lang_snack_max'           : 'הגעת למקסימום של {n} שפות.',
  'additional_lang_empty'               : 'טרם נוספו שפות',
  'additional_hobby_section_title'      : 'תחביבים ותחומי עניין',
  'additional_hobby_add_hint'           : 'לדוגמה: צילום',
  'additional_hobby_snack_max'          : 'הגעת למקסימום של {n} תחביבים.',
  'additional_hobby_empty'              : 'טרם נוספו תחביבים',
  'additional_section_hint'             : 'ערכים מסומנים כלולים בקורות חיים אלה. הבחירות שלך נשמרות אוטומטית.',
  'additional_nav_next'                 : 'המשך לממליצים',
  'cert_sheet_title_add'                : 'הוסף הסמכה',
  'cert_sheet_title_edit'               : 'ערוך הסמכה',
  'cert_sheet_sub'                      : 'הוסף כישור, תעודה או אישור מקצועי.',
  'cert_sheet_field_name'               : 'שם ההסמכה *',
  'cert_sheet_field_issued_by'          : 'הונפק על ידי (אופציונלי)',
  'cert_sheet_field_short_desc'         : 'תיאור קצר (אופציונלי)',
  'cert_sheet_hint_name'                : 'לדוגמה: AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'לדוגמה: Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'לדוגמה: הושג ב-2024',
  'cert_sheet_btn_save'                 : 'שמור הסמכה',
  'cert_sheet_btn_update'               : 'עדכן הסמכה',
  'simple_sheet_title_add_language'     : 'הוסף שפה',
  'simple_sheet_title_edit_language'    : 'ערוך שפה',
  'simple_sheet_title_add_hobby'        : 'הוסף תחביב',
  'simple_sheet_title_edit_hobby'       : 'ערוך תחביב',
  'simple_sheet_btn_save'               : 'שמור',
  'simple_sheet_btn_update'             : 'עדכן',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'יצירת קשר',
  'pdf_section_about_me'                : 'אודותיי',
  'pdf_section_summary'                 : 'סיכום',
  'pdf_section_summary_short'           : 'סיכום',
  'pdf_section_profile'                 : 'פרופיל',
  'pdf_section_experience'              : 'ניסיון',
  'pdf_section_experience_short'        : 'ניסיון',
  'pdf_section_education'               : 'השכלה',
  'pdf_section_skills'                  : 'כישורים',
  'pdf_section_languages'               : 'שפות',
  'pdf_label_email'                     : 'אימייל',
  'pdf_label_phone'                     : 'טלפון',
  'pdf_label_location'                  : 'מיקום',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'הגעת למגבלת קורות חיים',
  'limit_dialog_body'                   : 'הגעת למקסימום של 30 קורות חיים. אנא מחק קורות חיים קיימים לפני יצירת חדשים.',
  'limit_dialog_go_to_my_cvs'           : 'עבור לקורות החיים שלי',
  'limit_dialog_cancel'                 : 'בטל',
  'refs_count_summary'                  : '{checked}/{maxChecked} נבחרו · {saved}/{maxSaved} שמורים',
  'refs_selected_badge'                 : '{n} נבחרו',
  'refs_empty_message'                  : 'אין ממליצים שמורים עדיין',
  'refs_empty_sub'                      : 'הקש למעלה להוספת ממליץ אישי',
};