// lib/language_keys/lang_uk_ukrainian.dart
//
// Ukrainian translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> ukUkrainian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Мови не знайдено',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Пропустити',
  'onboarding_next'                     : 'Далі',
  'onboarding_get_started'              : 'Розпочати',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Ласкаво просимо',
  'ob1_title'                           : 'Створіть резюме,\nяке відкриває двері',
  'ob1_body'                            : 'Виділяйтеся серед сотень кандидатів. Створіть бездоганне, переможне резюме за лічені хвилини — без навичок дизайну.',
  'ob1_pill_label'                      : 'Професійний конструктор резюме',
  'ob1_chip_templates'                  : '24+ шаблони',
  'ob1_chip_pdf'                        : 'Експорт PDF',
  'ob1_chip_free'                       : 'Безкоштовно',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Шаблони',
  'ob2_title'                           : 'Будь-яка галузь.\nБудь-які амбіції.',
  'ob2_body'                            : 'Від ділових макетів до сміливих креативних дизайнів — шаблон, який розповідає вашу історію.',
  'ob2_tap_hint'                        : 'Торкніться шаблону для перегляду',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Корпоративний',
  'ob2_tag_creative'                    : 'Креативний',
  'ob2_tag_minimal'                     : 'Мінімалістичний',
  'ob2_tag_modern'                      : 'Сучасний',
  'ob2_tag_premium'                     : 'Преміум',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Розумне компонування',
  'ob3_title'                           : 'Ваше резюме.\nІдеально впорядковане.',
  'ob3_body'                            : 'Розумне компонування перевпорядковує розділи для максимального впливу — розміщуючи найсильніший контент там, де рекрутери дивляться насамперед.',
  'ob3_badge_smart_layout'              : 'Розумне компонування',
  'ob3_badge_cv_ready'                  : 'Резюме готове!',
  'ob3_step1_label'                     : 'Оберіть шаблон',
  'ob3_step1_desc'                      : 'Виберіть з 24+ чудових дизайнів.',
  'ob3_step2_label'                     : 'Заповніть дані',
  'ob3_step2_desc'                      : 'Зручні поля для всіх розділів.',
  'ob3_step3_label'                     : 'Розумне компонування',
  'ob3_step3_desc'                      : 'Одним дотиком ідеально впорядкуйте резюме.',
  'ob3_step4_label'                     : 'Експортувати у PDF',
  'ob3_step4_desc'                      : 'Ідеальний PDF готовий до відправки.',
  'ob3_section_work'                    : 'Досвід роботи',
  'ob3_section_education'               : 'Освіта',
  'ob3_section_skills'                  : 'Навички',
  'ob3_section_references'              : 'Рекомендації',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Готово до роботи',
  'ob4_title'                           : 'Чому кращі кандидати\nобирають CV Builder',
  'ob4_visual_headline'                 : 'Ви готові!',
  'ob4_visual_subline'                  : 'Все необхідне, щоб отримати роботу.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Шаблони',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Макс. резюме',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Експорт',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Приватно',
  'ob4_hl1_title'                       : 'Приватність і безпека',
  'ob4_hl1_sub'                         : 'Дані зберігаються на вашому пристрої.',
  'ob4_hl2_title'                       : 'Автозбереження',
  'ob4_hl2_sub'                         : 'Кожне натискання клавіші зберігається миттєво.',
  'ob4_hl3_title'                       : 'До 30 резюме',
  'ob4_hl3_sub'                         : 'Унікальне резюме для кожної вакансії.',
  'ob4_hl4_title'                       : 'Поділитися одним дотиком',
  'ob4_hl4_sub'                         : 'Надішліть PDF, не виходячи з програми.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Виділяйтесь серед інших',
  'home_hero_title'                     : 'Створіть своє\nпрофесійне резюме',
  'home_hero_sub'                       : 'Створіть чудове резюме\nза лічені хвилини',
  'home_hero_cta'                       : 'Почати створення',
  'home_premium_soon'                   : 'Оновлення до Pro незабаром!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Найновіші',
  'history_sort_alphabetical'           : 'А–Я',
  'history_sort_last_edited'            : 'Останнє редагування',
  'history_sort_by_template'            : 'За шаблоном',
  'history_sort_sheet_title'            : 'Сортувати за',
  'history_sort_alphabetical_full'      : 'За алфавітом (А–Я)',
  'history_premium_soon'                : 'Оновлення до Pro незабаром!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Налаштування',
  'settings_section_preferences'        : 'Параметри',
  'settings_section_support'            : 'Підтримка',
  'settings_section_legal'              : 'Правова інформація',
  'settings_section_about'              : 'Про програму',
  'settings_language_tile_title'        : 'Мова',
  'settings_dark_mode_title'            : 'Темна тема',
  'settings_dark_mode_on'               : 'Темну тему увімкнено',
  'settings_dark_mode_off'              : 'Світлу тему увімкнено',
  'settings_help_faq_title'             : 'Допомога та FAQ',
  'settings_help_faq_sub'               : 'Відповіді на поширені запитання',
  'settings_contact_support_title'      : 'Зв\'язатися з підтримкою',
  'settings_rate_app_title'             : 'Оцінити програму',
  'settings_rate_app_sub'               : 'Подобається програма? Залиште відгук!',
  'settings_privacy_policy_title'       : 'Політика конфіденційності',
  'settings_terms_title'                : 'Умови використання',
  'settings_app_version_title'          : 'Версія програми',
  'settings_email_error'                : 'Не вдалося відкрити поштову програму. Напишіть на cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Перегляд резюме',
  'preview_header_sub'                  : 'Готово до експорту',
  'preview_generating'                  : 'Генерується ваше резюме...',
  'preview_failed_title'                : 'Помилка перегляду',
  'preview_failed_error'                : 'Помилка: {error}',
  'preview_go_back'                     : 'Назад',
  'preview_no_data'                     : 'Дані недоступні',
  'preview_btn_print'                   : 'Друкувати',
  'preview_btn_download'                : 'Завантажити та поділитися',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Допомога та FAQ',
  'faq_category_all'                    : 'Всі',
  'faq_empty'                           : 'Результатів не знайдено',
  'faq_contact_headline'                : 'Ще потрібна допомога?',
  'faq_contact_sub'                     : 'Наша команда завжди готова допомогти.',
  'faq_contact_btn'                     : 'Написати',
  'faq_email_error'                     : 'Не вдалося відкрити поштову програму. Напишіть на cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Початок роботи',
  'faq_cat_templates'                   : 'Шаблони',
  'faq_cat_editing'                     : 'Редагування',
  'faq_cat_exporting'                   : 'Експорт',
  'faq_cat_data_privacy'                : 'Дані та конфіденційність',
  'faq_cat_troubleshooting'             : 'Усунення несправностей',
  'faq_q1'  : 'Як створити перше резюме?',
  'faq_a1'  : 'Натисніть кнопку «+» на головному екрані, щоб розпочати нове резюме. Оберіть шаблон, що відповідає вашому стилю, а потім крок за кроком заповніть особисті дані, досвід роботи, освіту та навички. Ваш прогрес зберігається автоматично.',
  'faq_q2'  : 'Чи можна створити більше одного резюме?',
  'faq_a2'  : 'Так! Ви можете створити кілька резюме для різних посад або галузей. Кожне резюме зберігається окремо, щоб ви могли адаптувати їх до конкретних вакансій.',
  'faq_q3'  : 'Як змінити шаблон резюме?',
  'faq_a3'  : 'Відкрийте резюме, торкніться іконки шаблону у верхній частині екрана та перегляньте доступні шаблони. Торкніться будь-якого шаблону, щоб переглянути його з вашим вмістом. Підтвердіть, щоб застосувати.',
  'faq_q4'  : 'Є безкоштовні та преміум шаблони?',
  'faq_a4'  : 'Так. Вибір професійних шаблонів доступний безкоштовно. Преміум шаблони з розширеними дизайнами та кольоровими палітрами доступні за одноразову покупку або підписку.',
  'faq_q5'  : 'Як додати або видалити розділи?',
  'faq_a5'  : 'У редакторі резюме прокрутіть до нижньої частини екрана та натисніть «Додати розділ», щоб включити додаткові розділи, як-от мови, сертифікати або волонтерська робота. Щоб видалити розділ, торкніться заголовка розділу та виберіть «Видалити».',
  'faq_q6'  : 'Як змінити порядок розділів?',
  'faq_a6'  : 'Утримуйте маркер перетягування (≡) поряд із заголовком будь-якого розділу та перетягніть його на потрібну позицію. Зміни зберігаються автоматично.',
  'faq_q7'  : 'Як експортувати резюме у форматі PDF?',
  'faq_a7'  : 'Відкрийте резюме та натисніть кнопку експорту (іконка поширення) у верхньому правому куті. Виберіть «Експортувати як PDF». Потім ви можете зберегти його на пристрої, поділитися електронною поштою, WhatsApp або завантажити безпосередньо на сайти пошуку роботи.',
  'faq_q8'  : 'Які формати файлів підтримуються?',
  'faq_a8'  : 'Наразі програма підтримує експорт резюме у вигляді високоякісного PDF. Додаткові формати можуть бути додані в майбутніх оновленнях.',
  'faq_q9'  : 'Де зберігаються дані мого резюме?',
  'faq_a9'  : 'Всі дані вашого резюме зберігаються локально на вашому пристрої. Ми не завантажуємо вашу особисту інформацію на наші сервери. Це означає, що ваші дані залишаються приватними та доступними офлайн.',
  'faq_q10' : 'Як зробити резервну копію резюме?',
  'faq_a10' : 'Ваші резюме включені до стандартної резервної копії вашого пристрою (резервне копіювання Google Drive на Android, iCloud на iOS), якщо у вас увімкнено резервне копіювання в налаштуваннях пристрою. Ви також можете експортувати окремі резюме у форматі PDF для збереження копії.',
  'faq_q11' : 'Програма працює повільно. Що робити?',
  'faq_a11' : 'Спробуйте закрити та перезапустити програму. Якщо проблема не зникає, перезавантажте пристрій. Переконайтеся, що у вас встановлена остання версія програми з Play Store / App Store.',
  'faq_q12' : 'Моє резюме не експортується правильно. Що робити?',
  'faq_a12' : 'Переконайтеся, що на вашому пристрої достатньо місця для зберігання. Спробуйте зменшити великі зображення в резюме. Якщо проблема не зникає, зверніться до нашої служби підтримки.',
  'faq_q13' : 'Я забув зберегти — чи втрачена моя робота?',
  'faq_a13' : 'Ні! Програма безперервно зберігає ваш прогрес під час редагування.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Ваша кар\'єра, вдосконалена',
  'header_tooltip_back'                 : 'Назад',
  'header_tooltip_my_cvs'               : 'Мої резюме',
  'header_tooltip_settings'             : 'Налаштування',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Мої резюме',
  'saved_count_single'                  : '{n} документ',
  'saved_count_plural'                  : '{n} документів',
  'saved_limit_reached'                 : 'Досягнуто ліміту',
  'saved_footer_count'                  : '{n} / 30 резюме',
  'saved_filter_all'                    : 'Всі',
  'saved_filter_draft'                  : 'Чернетка',
  'saved_filter_complete'               : 'Завершено',
  'saved_status_complete'               : 'Завершено',
  'saved_status_saved'                  : 'Збережено',
  'saved_status_draft'                  : 'Чернетка',
  'saved_empty_title'                   : 'Тут ще немає резюме',
  'saved_empty_sub'                     : 'Почніть створювати перше резюме вище',
  'saved_search_empty_title'            : 'Результатів не знайдено',
  'saved_search_empty_sub'              : 'Спробуйте інший пошуковий запит',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Колірна схема',
  'custom_font_settings_title'          : 'Налаштування шрифту',
  'custom_font_family_label'            : 'Сімейство шрифтів',
  'custom_font_size_label'              : 'Розмір шрифту: ',
  'custom_current_template_title'       : 'Поточний шаблон',
  'custom_change_template_btn'          : 'Змінити шаблон',
  'custom_tpl_modern'                   : 'Сучасний',
  'custom_tpl_classic'                  : 'Класичний',
  'custom_tpl_professional'             : 'Професійний',
  'custom_tpl_creative'                 : 'Креативний',
  'custom_tpl_minimal'                  : 'Мінімалістичний',
  'custom_tpl_modern_desc'              : 'Чистий та сучасний дизайн',
  'custom_tpl_classic_desc'             : 'Традиційне професійне розташування',
  'custom_tpl_professional_desc'        : 'Бізнес-орієнтований шаблон',
  'custom_tpl_creative_desc'            : 'Виділяйтесь унікальним дизайном',
  'custom_tpl_minimal_desc'             : 'Простий та елегантний стиль',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Оберіть шаблон',
  'swipe_photo_badge'                   : 'Фото',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Найпопулярніший',
  'tpl_nordic_tag'                      : 'Чистий',
  'tpl_vibrant_tag'                     : 'Креативний',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Еліт',
  'tpl_executive_desc'                  : 'Сміливий та авторитетний для керівних посад',
  'tpl_nordic_desc'                     : 'Мінімальна чіткість, якій довіряють провідні компанії',
  'tpl_vibrant_desc'                    : 'Виділяйтесь енергією та кольором',
  'tpl_tech_dark_desc'                  : 'Термінальна естетика для розробників',
  'tpl_luxury_desc'                     : 'Золоті акценти на чорному тлі',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Шаблон',
  'detail_step_personal'                : 'Особисте',
  'detail_step_experience'              : 'Досвід',
  'detail_step_education'               : 'Освіта',
  'detail_step_skills'                  : 'Навички',
  'detail_step_additional'              : 'Додатково',
  'detail_step_references'              : 'Рекомендації',
  'detail_step_customize'               : 'Налаштування',
  'detail_banner_heading'               : 'Майже готово!',
  'detail_banner_btn'                   : 'Продовжити',
  'detail_banner_completion_label'      : 'Завершеність',
  'detail_stat_created_label'           : 'Створено',
  'detail_stat_steps_label'             : 'Кроків виконано',
  'detail_section_template_style'       : 'Стиль шаблону',
  'detail_section_steps'                : 'Кроки',
  'detail_steps_counter'                : '{done} з {total} виконано',
  'detail_step_sub'                     : 'Крок {n} з {total}',
  'detail_section_activity'             : 'Активність',
  'detail_activity_created'             : 'Створено',
  'detail_activity_last_edited'         : 'Останнє редагування',
  'detail_activity_template'            : 'Шаблон',
  'detail_btn_continue_editing'         : 'Продовжити редагування',
  'detail_btn_edit_cv'                  : 'Редагувати резюме',
  'detail_option_rename'                : 'Перейменувати резюме',
  'detail_option_delete'                : 'Видалити резюме',
  'detail_rename_title'                 : 'Перейменувати резюме',
  'detail_rename_hint'                  : 'напр. Резюме програміста',
  'detail_rename_error_empty'           : 'Назва не може бути порожньою',
  'detail_rename_btn_cancel'            : 'Скасувати',
  'detail_rename_btn_save'              : 'Зберегти',
  'detail_rename_snackbar'              : 'Перейменовано на "{name}"',
  'detail_delete_title'                 : 'Видалити резюме?',
  'detail_delete_body'                  : 'Це назавжди видалить "{name}". Цю дію неможливо скасувати.',
  'detail_delete_btn_cancel'            : 'Скасувати',
  'detail_delete_btn_confirm'           : 'Видалити',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Заповнено',
  'detail_check_tile_incomplete'        : 'Ще не заповнено',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Оберіть шаблон',
  'chooser_subtitle'                    : 'Гортайте для перегляду  ·  Торкніться для вибору  ·  Утримуйте для попереднього перегляду',
  'chooser_card_hold_hint'              : 'Утримуйте для перегляду',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Вибрано',
  'chooser_modal_heading'               : 'Назвіть своє резюме',
  'chooser_modal_sub'                   : 'Дайте назву, щоб легко знайти в Моїх резюме та Історії.',
  'chooser_modal_field_label'           : 'Назва резюме',
  'chooser_modal_save_btn'              : 'Зберегти та почати',
  'chooser_modal_divider'               : 'або продовжити наявне резюме',
  'chooser_nav_selected_sub'            : 'Вибраний шаблон',
  'chooser_nav_cta'                     : 'Зберегти та продовжити',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Досягнуто максимальну кількість записів',
  'editor_show_hide'                    : 'Показати/Приховати',
  'editor_editing_badge'                : 'Редагування',
  'editor_field_required'               : 'Обов\'язкове поле',
  'editor_tooltip_edit'                 : 'Редагувати',
  'editor_tooltip_delete'               : 'Видалити',
  'editor_date_start'                   : 'Дата початку *',
  'editor_date_end'                     : 'Дата закінчення *',
  'editor_date_tap_hint'                : 'Торкніться для вибору',
  'editor_date_dialog_title'            : 'Виберіть місяць та рік',
  'editor_date_confirm'                 : 'Підтвердити',
  'editor_panel_hide'                   : 'Приховати',
  'editor_panel_show'                   : 'Показати',
  'editor_validator_max_chars'          : 'Макс. {n} символів',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Створення резюме',
  'editor_header_step_sub'              : 'Крок {current} з {total} · {label}',
  'editor_step_template'                : 'Шаблон',
  'editor_step_personal'                : 'Особисте',
  'editor_step_experience'              : 'Досвід',
  'editor_step_education'               : 'Освіта',
  'editor_step_skills'                  : 'Навички',
  'editor_step_additional'              : 'Додатково',
  'editor_step_references'              : 'Рекомендації',
  'editor_step_customize'               : 'Налаштування',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Налаштування',
  'customize_subtitle'                  : 'Зробіть резюме унікально вашим',
  'customize_smart_layout_btn'          : 'Розумне компонування',
  'customize_back_to_top'               : 'На початок',
  'customize_done_title'                : 'Все готово!',
  'customize_done_sub'                  : 'Натисніть «Переглянути резюме» нижче, щоб побачити готове резюме',
  'customize_preview_btn'               : 'Переглянути резюме',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Колірна схема',
  'color_black'                         : 'Чорний',
  'color_blue'                          : 'Синій',
  'color_nordic_blue'                   : 'Скандинавський синій',
  'color_indigo'                        : 'Індиго',
  'color_teal'                          : 'Смарагдово-зелений',
  'color_green'                         : 'Зелений',
  'color_purple'                        : 'Фіолетовий',
  'color_orange'                        : 'Помаранчевий',
  'color_red'                           : 'Червоний',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'Білий',
  'color_white_bg'                      : 'Білий фон',
  'color_maroon'                        : 'Бордовий',
  'color_brutalist_yellow'              : 'Брутальний жовтий',
  'color_neon_blue'                     : 'Неоновий синій',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'Світло-сірий',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Сімейство шрифтів',
  'customize_font_picker_title'         : 'Вибрати шрифт',
  'customize_font_picker_sub'           : 'Кожен шрифт відображається у своїй гарнітурі',
  'customize_font_preview_sample'       : 'Швидка коричнева лисиця',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Розмір шрифту',
  'customize_font_size_label'           : 'Розмір тексту',
  'customize_font_size_value'           : '{n} пт',
  'customize_font_size_min'             : '10 пт',
  'customize_font_size_max'             : '16 пт',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Розмір зображення',
  'customize_image_size_label'          : 'Розмір зображення',
  'customize_image_size_value'          : '{n} пкс',
  'customize_image_size_min'            : '10 пкс',
  'customize_image_size_max'            : '16 пкс',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Перегляд в реальному часі',
  'preview_page_count_singular'         : '1 сторінка',
  'preview_page_count_plural'           : '{n} сторінок',
  'preview_page_of'                     : 'Сторінка {page} з {total}',
  'preview_live_hint'                   : 'Зміни застосовуються миттєво',
  'preview_template_unregistered'       : 'Ще не зареєстровано в customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Підготовка вашого резюме…',
  'preview_bar_print'                   : 'Друкувати',
  'preview_bar_save_pdf'                : 'Зберегти як PDF',
  'preview_bar_share'                   : 'Поділитися',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Перегляд резюме',
  'preview_screen_sub'                  : '{n} {unit} · як надруковано',
  'preview_page_singular'               : 'сторінка',
  'preview_page_plural'                 : 'сторінок',
  'preview_pdf_filename'                : 'Моє_резюме',
  'preview_share_subject'               : 'Моє резюме',
  'preview_snack_print_failed'          : 'Помилка друку: {e}',
  'preview_snack_saved'                 : 'Резюме збережено в Завантаження ✓',
  'preview_snack_export_failed'         : 'Помилка експорту: {e}',
  'preview_snack_share_failed'          : 'Помилка поширення: {e}',
  'preview_template_not_registered'     : 'Шаблон не зареєстровано',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Закрити перегляд',
  'preview_modal_hint_photo'            : 'Підтримує фото профілю  ·  Торкніться картки для вибору',
  'preview_modal_hint_no_photo'         : 'Торкніться картки шаблону для вибору',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Моє резюме',
  'time_just_now'                       : 'Щойно',
  'time_minutes_ago'                    : '{n} хв тому',
  'time_hours_ago'                      : '{n} год тому',
  'time_yesterday'                      : 'Вчора',
  'time_days_ago'                       : '{n} дн тому',
  'time_one_week_ago'                   : '1 тиждень тому',
  'time_weeks_ago'                      : '{n} тижнів тому',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Елегантний',
  'tpl_tag_classic'                     : 'Класичний',
  'tpl_tag_minimal'                     : 'Мінімалістичний',
  'tpl_tag_creative'                    : 'Креативний',
  'tpl_tag_bold'                        : 'Сміливий',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Картки з градієнтом від смарагдового до фіолетового',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Журнальний стиль: червоний та кремовий',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'Лавандова бічна панель, м\'які картки',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Груба сітка, жирні рамки та жовтий',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Темно-зелений з хронологією',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Темне полотно з кільцевими діаграмами',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Геометрична розкіш 1920-х у золоті',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Темна інфографіка з кільцями',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Темна бічна панель з помаранчевим акцентом',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Чистий мінімалізм, м\'які сірі тони',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Теплі бежеві елегантні тони',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Різкий чорно-білий класичний стиль',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Класичне компонування для ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Темний помаранчевий інфографічний стиль',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Технічне креслення на сітці',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Класичне двоколонкове розташування з мітками',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Затіновані заголовки з ромбовими маркерами',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Центровані заголовки, акцентовані компанії',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Жирне ім\'я, крапки хронології та досягнення',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Особиста інформація',
  'personal_subtitle'                   : 'Розкажіть роботодавцям, хто ви',
  'personal_profile_counter'            : '{n}/{max} профілів',
  'personal_info_banner'                : 'Зберігайте до 5 профілів та вибирайте один для кожного резюме. Ваш вибір запам\'ятовується окремо для кожного резюме.',
  'personal_snack_max'                  : 'Досягнуто максимум {n} профілів.',
  'personal_add_btn'                    : 'Додати новий профіль',
  'personal_library_title'              : 'Збережені профілі',
  'personal_selected_one'               : '1 вибрано',
  'personal_selected_none'              : 'нічого не вибрано',
  'personal_library_hint'               : 'Торкніться картки, щоб вибрати її лише для цього резюме. Інші резюме зберігають власні незалежні вибори.',
  'personal_empty_message'              : 'Профілів ще немає',
  'personal_empty_sub'                  : 'Натисніть вище, щоб додати особисту інформацію',
  'personal_nav_next'                   : 'Зберегти та продовжити',
  'personal_card_active_badge'          : 'Активно для цього резюме',
  'personal_sheet_title_add'            : 'Новий профіль',
  'personal_sheet_title_edit'           : 'Редагувати профіль',
  'personal_sheet_brutalist_badge'      : 'БРУТАЛЬНИЙ',
  'personal_sheet_brutalist_banner'     : 'Шаблон Brutalist має компактні контактні поля. Коротші значення (напр., лише місто) відображаються найкраще.',
  'personal_section_photo'              : 'Фото профілю',
  'personal_section_basic'              : 'Основні дані',
  'personal_section_contact'            : 'Контакти',
  'personal_section_online'             : 'Онлайн-присутність',
  'personal_section_summary'            : 'Професійне резюме',
  'personal_field_first_name'           : 'Ім\'я *',
  'personal_field_last_name'            : 'Прізвище',
  'personal_field_job_title'            : 'Посада *',
  'personal_field_email'                : 'Електронна адреса *',
  'personal_field_phone'                : 'Номер телефону *',
  'personal_field_location'             : 'Місцезнаходження',
  'personal_field_location_brut'        : 'Місцезнаходження (лише місто)',
  'personal_field_website'              : 'Сайт / Портфоліо',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'напр. Іванна',
  'personal_hint_last_name'             : 'напр. Коваль',
  'personal_hint_job_title'             : 'напр. Старший інженер',
  'personal_hint_email'                 : 'напр. ivanna@example.com',
  'personal_hint_phone'                 : 'напр. +38 050 123 4567',
  'personal_hint_location'              : 'напр. Київ, Україна',
  'personal_hint_location_brut'         : 'напр. Київ, UA',
  'personal_hint_website'               : 'напр. github.com/ivannasmith',
  'personal_hint_website_brut'          : 'напр. github.com/ivanna',
  'personal_hint_linkedin'              : 'напр. linkedin.com/in/ivannasmith',
  'personal_hint_linkedin_brut'         : 'напр. linkedin.com/in/ivanna',
  'personal_summary_hint_label'         : 'Будьте лаконічні — це з\'являється у верхній частині резюме.',
  'personal_hint_summary'               : 'Короткий підсумок з 2–3 речень про ваш досвід та цілі...',
  'personal_validator_email'            : 'Введіть дійсну електронну адресу',
  'personal_field_char_limit_tooltip'   : 'Досягнуто ліміту символів',
  'personal_sheet_btn_save'             : 'Зберегти профіль',
  'personal_sheet_btn_update'           : 'Зберегти зміни',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Вибрати фото',
  'photo_option_gallery'                : 'Вибрати з галереї',
  'photo_option_camera'                 : 'Зробити фото',
  'photo_option_reposition'             : 'Змінити положення фото',
  'photo_option_remove'                 : 'Видалити фото',
  'photo_status_added'                  : 'Фото додано ✓',
  'photo_status_empty'                  : 'Додайте професійне фото',
  'photo_chip_gallery'                  : 'Галерея',
  'photo_chip_camera'                   : 'Камера',
  'photo_chip_reposition'               : 'Змінити положення',
  'photo_reposition_title'              : 'Змінити положення фото',
  'photo_reposition_sub'                : 'Перетягніть фото, щоб налаштувати положення',
  'photo_reposition_reset'              : 'Скинути до центру',
  'photo_reposition_apply'              : 'Застосувати',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Навички',
  'skills_subtitle'                     : 'Підкресліть свої ключові здібності',
  'skills_add_btn'                      : 'Додати нову навичку',
  'skills_snack_max_icons'              : 'Вибрано максимум 10 іконок.',
  'skills_snack_max_skills'             : 'Досягнуто максимум 15 навичок.',
  'skills_library_title'                : 'Збережені навички',
  'skills_library_hint'                 : 'Позначені навички включені до цього резюме. Ваші вибори зберігаються автоматично.',
  'skills_nav_next'                     : 'Перейти до додаткових даних',
  'skills_wina_header_icon_bar'         : 'Панель іконок заголовка',
  'skills_wina_on'                      : 'УВ.',
  'skills_wina_off'                     : 'ВИКЛ.',
  'skills_wina_bar_on_sub'              : 'Кольорові кола іконок відображаються в заголовку резюме.',
  'skills_wina_bar_off_sub'             : 'Рядок іконок приховано — більше місця для контактних даних.',
  'skills_wina_palette_hint'            : 'Іконки відображаються у вигляді кольорових кіл у порядку палітри.',
  'skills_wina_preview_label'           : 'Перегляд',
  'skills_wina_disabled_hint'           : 'Увімкніть панель іконок вище, щоб вибрати, які іконки відображатимуться в заголовку резюме.',
  'skills_sheet_title_add'              : 'Додати навичку',
  'skills_sheet_title_edit'             : 'Редагувати навичку',
  'skills_sheet_field_name'             : 'Назва навички *',
  'skills_sheet_hint_short'             : 'напр. Flutter, Дизайн',
  'skills_sheet_hint_long'              : 'напр. Flutter, Управління проєктами',
  'skills_sheet_validator_max'          : 'Макс. {n} символів',
  'skills_sheet_proficiency'            : 'Рівень володіння',
  'skills_sheet_beginner'               : 'Початківець',
  'skills_sheet_expert'                 : 'Експерт',
  'skills_sheet_btn_save'               : 'Зберегти навичку',
  'skills_sheet_btn_update'             : 'Оновити навичку',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Особисті рекомендації',
  'refs_subtitle'                       : 'Люди, які можуть особисто за вас поручитися',
  'refs_add_btn'                        : 'Додати нову особисту рекомендацію',
  'refs_snack_max_selected'             : 'Для одного резюме можна вибрати не більше 4 рекомендацій.',
  'refs_snack_max_saved'                : 'Досягнуто максимум 10 збережених рекомендацій.',
  'refs_library_title'                  : 'Збережені рекомендації',
  'refs_library_hint'                   : 'Позначені рекомендації включені до цього резюме. Макс. 4 на резюме. Ваші вибори зберігаються автоматично.',
  'refs_nav_next'                       : 'Перейти до налаштувань',
  'refs_sheet_title_add'                : 'Додати особисту рекомендацію',
  'refs_sheet_title_edit'               : 'Редагувати особисту рекомендацію',
  'refs_sheet_sub_add'                  : 'Людина, яка може особисто рекомендувати вас роботодавцям.',
  'refs_sheet_sub_edit'                 : 'Оновіть дані цієї рекомендації нижче.',
  'refs_sheet_field_name'               : 'Повне ім\'я *',
  'refs_sheet_field_title'              : 'Посада *',
  'refs_sheet_field_company'            : 'Компанія (необов\'язково)',
  'refs_sheet_field_email'              : 'Електронна адреса *',
  'refs_sheet_field_phone'              : 'Номер телефону *',
  'refs_sheet_hint_name'                : 'напр. Іван Коваль',
  'refs_sheet_hint_title'               : 'напр. Керівник інженерного відділу',
  'refs_sheet_hint_company'             : 'напр. Acme Corp',
  'refs_sheet_hint_email'               : 'напр. ivan@acme.com',
  'refs_sheet_hint_phone'               : 'напр. +38 050 123 4567',
  'refs_sheet_validator_email'          : 'Введіть дійсну електронну адресу',
  'refs_sheet_btn_save'                 : 'Зберегти особисту рекомендацію',
  'refs_sheet_btn_update'               : 'Оновити особисту рекомендацію',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Досвід роботи',
  'exp_subtitle'                        : 'Додайте свою трудову біографію',
  'exp_banner_info'                     : 'У резюме відображатиметься до {n} обов\'язків для кожної посади. Зазвичай 3–6 місць роботи вміщуються на 1–2 сторінках.',
  'exp_add_btn'                         : 'Додати новий досвід',
  'exp_snack_max_selected'              : 'Для одного резюме можна вибрати не більше 8 місць роботи.',
  'exp_snack_max_saved'                 : 'Досягнуто максимум 12 збережених місць роботи.',
  'exp_library_title'                   : 'Збережений досвід',
  'exp_library_hint'                    : 'Позначені записи включені лише до цього резюме. Інші резюме зберігають власні незалежні вибори.',
  'exp_nav_next'                        : 'Перейти до освіти',
  'exp_empty_message'                   : 'Досвід ще не додано',
  'exp_empty_sub'                       : 'Натисніть вище, щоб додати першу посаду',
  'exp_card_resp_singular'              : 'обов\'язок',
  'exp_card_resp_plural'                : 'обов\'язків',
  'exp_card_resp_tooltip'               : 'У резюме відображатимуться лише перші 8 обов\'язків',
  'exp_sheet_title_add'                 : 'Додати досвід',
  'exp_sheet_title_edit'                : 'Редагувати досвід',
  'exp_sheet_field_job_title'           : 'Посада *',
  'exp_sheet_field_company'             : 'Компанія *',
  'exp_sheet_field_location'            : 'Місцезнаходження',
  'exp_sheet_section_responsibilities'  : 'Ключові обов\'язки',
  'exp_sheet_resp_hint_info'            : 'Макс. 8 пунктів · 200 символів кожен',
  'exp_sheet_resp_label'                : 'Обов\'язок {n}',
  'exp_sheet_resp_hint'                 : 'напр. Керував командою з 5 інженерів',
  'exp_sheet_resp_add_btn'              : 'Додати обов\'язок',
  'exp_sheet_resp_max_info'             : 'Досягнуто максимум {n} обов\'язків',
  'exp_sheet_resp_validator_max'        : 'Макс. 200 символів',
  'exp_sheet_hint_job_title'            : 'напр. Старший розробник',
  'exp_sheet_hint_location'             : 'напр. Київ, Україна',
  'exp_sheet_btn_save'                  : 'Зберегти досвід',
  'exp_sheet_btn_update'                : 'Зберегти зміни',
  'exp_date_present'                    : 'По теперішній час / Поточна посада',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Освіта',
  'edu_subtitle'                        : 'Додайте свій академічний досвід',
  'edu_add_btn'                         : 'Додати нову освіту',
  'edu_snack_max_selected'              : 'Для одного резюме можна вибрати не більше 8 записів про освіту.',
  'edu_snack_max_saved'                 : 'Досягнуто максимум 12 збережених записів про освіту.',
  'edu_library_title'                   : 'Збережена освіта',
  'edu_library_hint'                    : 'Позначені записи включені до цього резюме. Ваші вибори зберігаються автоматично.',
  'edu_nav_next'                        : 'Перейти до навичок',
  'edu_empty_message'                   : 'Освіту ще не додано',
  'edu_empty_sub'                       : 'Натисніть вище, щоб додати свої кваліфікації',
  'edu_card_bullet_singular'            : 'пункт',
  'edu_card_bullet_plural'              : 'пунктів',
  'edu_sheet_title_add'                 : 'Додати освіту',
  'edu_sheet_title_edit'                : 'Редагувати освіту',
  'edu_sheet_field_degree'              : 'Ступінь / Кваліфікація *',
  'edu_sheet_field_institution'         : 'Навчальний заклад *',
  'edu_sheet_section_key_points'        : 'Ключові моменти',
  'edu_sheet_key_points_hint_info'      : 'Необов\'язково · 1 пункт · макс. 100 символів',
  'edu_sheet_point_label'               : 'Пункт {n}',
  'edu_sheet_point_add_btn'             : 'Додати пункт',
  'edu_sheet_point_max_info'            : 'Досягнуто максимум {n} пунктів',
  'edu_sheet_point_validator_max'       : 'Макс. {n} символів',
  'edu_sheet_hint_degree'               : 'напр. Бакалавр комп\'ютерних наук',
  'edu_sheet_hint_institution'          : 'напр. Київський національний університет',
  'edu_sheet_hint_bullet'               : 'напр. Диплом з відзнакою',
  'edu_sheet_btn_save'                  : 'Зберегти освіту',
  'edu_sheet_btn_update'                : 'Зберегти зміни',
  'edu_date_present'                    : 'По теперішній час / Навчаюся зараз',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Додаткова інформація',
  'additional_subtitle'                 : 'Сертифікати, мови та інше',
  'additional_cert_section_title'       : 'Сертифікати',
  'additional_cert_counter'             : '{sel}/{total} вибрано · макс. {max}',
  'additional_cert_hide'                : 'Приховати',
  'additional_cert_show'                : 'Показати',
  'additional_cert_add_btn'             : 'Додати',
  'additional_cert_snack_max'           : 'Досягнуто максимум {n} записів сертифікатів.',
  'additional_cert_hint'                : 'Позначені записи включені до цього резюме. Ваші вибори зберігаються автоматично.',
  'additional_cert_empty'               : 'Сертифікатів ще не додано',
  'additional_lang_section_title'       : 'Мови',
  'additional_lang_add_hint'            : 'напр. Іспанська',
  'additional_lang_snack_max'           : 'Досягнуто максимум {n} записів мов.',
  'additional_lang_empty'               : 'Мов ще не додано',
  'additional_hobby_section_title'      : 'Хобі та інтереси',
  'additional_hobby_add_hint'           : 'напр. Фотографія',
  'additional_hobby_snack_max'          : 'Досягнуто максимум {n} записів хобі.',
  'additional_hobby_empty'              : 'Хобі ще не додано',
  'additional_section_hint'             : 'Позначені записи включені до цього резюме. Ваші вибори зберігаються автоматично.',
  'additional_nav_next'                 : 'Перейти до рекомендацій',
  'cert_sheet_title_add'                : 'Додати сертифікат',
  'cert_sheet_title_edit'               : 'Редагувати сертифікат',
  'cert_sheet_sub'                      : 'Додайте кваліфікацію, сертифікат або професійне посвідчення.',
  'cert_sheet_field_name'               : 'Назва сертифіката *',
  'cert_sheet_field_issued_by'          : 'Видано (необов\'язково)',
  'cert_sheet_field_short_desc'         : 'Короткий опис (необов\'язково)',
  'cert_sheet_hint_name'                : 'напр. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'напр. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'напр. Отримано у 2024',
  'cert_sheet_btn_save'                 : 'Зберегти сертифікат',
  'cert_sheet_btn_update'               : 'Оновити сертифікат',
  'simple_sheet_title_add_language'     : 'Додати мову',
  'simple_sheet_title_edit_language'    : 'Редагувати мову',
  'simple_sheet_title_add_hobby'        : 'Додати хобі',
  'simple_sheet_title_edit_hobby'       : 'Редагувати хобі',
  'simple_sheet_btn_save'               : 'Зберегти',
  'simple_sheet_btn_update'             : 'Оновити',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Контакти',
  'pdf_section_about_me'                : 'Про мене',
  'pdf_section_summary'                 : 'Резюме',
  'pdf_section_summary_short'           : 'Резюме',
  'pdf_section_profile'                 : 'Профіль',
  'pdf_section_experience'              : 'Досвід',
  'pdf_section_experience_short'        : 'Досвід',
  'pdf_section_education'               : 'Освіта',
  'pdf_section_skills'                  : 'Навички',
  'pdf_section_languages'               : 'Мови',
  'pdf_label_email'                     : 'Ел. пошта',
  'pdf_label_phone'                     : 'Телефон',
  'pdf_label_location'                  : 'Місцезнаходження',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Досягнуто ліміту резюме',
  'limit_dialog_body'                   : 'Ви досягли максимуму в 30 резюме. Будь ласка, видаліть наявне резюме перед створенням нового.',
  'limit_dialog_go_to_my_cvs'           : 'Перейти до Моїх резюме',
  'limit_dialog_cancel'                 : 'Скасувати',
  'refs_count_summary'                  : '{checked}/{maxChecked} вибрано · {saved}/{maxSaved} збережено',
  'refs_selected_badge'                 : '{n} вибрано',
  'refs_empty_message'                  : 'Рекомендацій ще не збережено',
  'refs_empty_sub'                      : 'Натисніть вище, щоб додати особисту рекомендацію',
};