// lib/language_keys/lang_cs_czech.dart
//
// Czech (Česká republika) — translation map.
// All keys mirror lang_en_english.dart exactly.

const Map<String, String> csCzech = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Žádné jazyky nenalezeny',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Přeskočit',
  'onboarding_next'                     : 'Další',
  'onboarding_get_started'              : 'Začít',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Vítejte',
  'ob1_title'                           : 'Vytvořte CV, které\notevře dveře',
  'ob1_body'                            : 'Vynikněte mezi stovkami uchazečů. Sestavte profesionální, úspěšné CV během několika minut — bez potřeby designérských dovedností.',
  'ob1_pill_label'                      : 'Profesionální tvorba CV',
  'ob1_chip_templates'                  : '24+ šablon',
  'ob1_chip_pdf'                        : 'Export do PDF',
  'ob1_chip_free'                       : 'Zdarma',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Šablony',
  'ob2_title'                           : 'Každé odvětví.\nKaždá ambice.',
  'ob2_body'                            : 'Od rozvržení pro nejvyšší vedení až po odvážné kreativní návrhy — šablona, která vypráví váš příběh.',
  'ob2_tap_hint'                        : 'Klepnutím zobrazíte náhled šablony',
  'ob2_tpl_executive'                   : 'Vedoucí',
  'ob2_tpl_vibrant'                     : 'Živý',
  'ob2_tpl_nordic'                      : 'Nordický',
  'ob2_tpl_tech_dark'                   : 'Tech Tmavý',
  'ob2_tpl_luxury'                      : 'Luxusní',
  'ob2_tag_corporate'                   : 'Firemní',
  'ob2_tag_creative'                    : 'Kreativní',
  'ob2_tag_minimal'                     : 'Minimální',
  'ob2_tag_modern'                      : 'Moderní',
  'ob2_tag_premium'                     : 'Prémiový',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Chytré rozvržení',
  'ob3_title'                           : 'Vaše CV.\nDokonale uspořádané.',
  'ob3_body'                            : 'Chytré rozvržení přeorganizuje vaše sekce pro maximální dopad — nejsilnější obsah umístí tam, kde ho náboráři hledají nejprve.',
  'ob3_badge_smart_layout'              : 'Chytré rozvržení',
  'ob3_badge_cv_ready'                  : 'CV připraveno!',
  'ob3_step1_label'                     : 'Vyberte šablonu',
  'ob3_step1_desc'                      : 'Vybírejte z 24+ úžasných návrhů.',
  'ob3_step2_label'                     : 'Vyplňte údaje',
  'ob3_step2_desc'                      : 'Průvodce poli pro všechny sekce.',
  'ob3_step3_label'                     : 'Chytré rozvržení',
  'ob3_step3_desc'                      : 'Jedním klepnutím přeformátujete CV dokonale.',
  'ob3_step4_label'                     : 'Export do PDF',
  'ob3_step4_desc'                      : 'Pixel-dokonalé PDF připravené k odeslání.',
  'ob3_section_work'                    : 'Pracovní zkušenosti',
  'ob3_section_education'               : 'Vzdělání',
  'ob3_section_skills'                  : 'Dovednosti',
  'ob3_section_references'              : 'Reference',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Připraveno',
  'ob4_title'                           : 'Proč nejlepší uchazeči\nvolí CV Builder',
  'ob4_visual_headline'                 : 'Vše je připraveno!',
  'ob4_visual_subline'                  : 'Vše, co potřebujete k získání práce.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'šablon',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Max CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Soukromé',
  'ob4_hl1_title'                       : 'Soukromé a bezpečné',
  'ob4_hl1_sub'                         : 'Data zůstávají ve vašem zařízení.',
  'ob4_hl2_title'                       : 'Automatické ukládání',
  'ob4_hl2_sub'                         : 'Každý stisk klávesy uložen okamžitě.',
  'ob4_hl3_title'                       : 'Až 30 CV',
  'ob4_hl3_sub'                         : 'Jedinečné CV pro každou pozici.',
  'ob4_hl4_title'                       : 'Sdílení jedním klepnutím',
  'ob4_hl4_sub'                         : 'Odešlete PDF bez opuštění aplikace.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Vynikněte z davu',
  'home_hero_title'                     : 'Vytvořte své\nprofesionální CV',
  'home_hero_sub'                       : 'Sestavte působivý životopis\nza pár minut',
  'home_hero_cta'                       : 'Začít tvořit',
  'home_premium_soon'                   : 'Upgrade na Pro již brzy!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Nejnovější',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Naposledy upravené',
  'history_sort_by_template'            : 'Podle šablony',
  'history_sort_sheet_title'            : 'Seřadit podle',
  'history_sort_alphabetical_full'      : 'Abecedně (A–Z)',
  'history_premium_soon'                : 'Upgrade na Pro již brzy!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Nastavení',
  'settings_section_preferences'        : 'Předvolby',
  'settings_section_support'            : 'Podpora',
  'settings_section_legal'              : 'Právní informace',
  'settings_section_about'              : 'O aplikaci',
  'settings_language_tile_title'        : 'Jazyk',
  'settings_dark_mode_title'            : 'Tmavý režim',
  'settings_dark_mode_on'               : 'Tmavý motiv zapnut',
  'settings_dark_mode_off'              : 'Světlý motiv zapnut',
  'settings_help_faq_title'             : 'Nápověda a FAQ',
  'settings_help_faq_sub'               : 'Odpovědi na časté otázky',
  'settings_contact_support_title'      : 'Kontaktovat podporu',
  'settings_rate_app_title'             : 'Ohodnotit aplikaci',
  'settings_rate_app_sub'               : 'Baví vás aplikace? Napište recenzi!',
  'settings_privacy_policy_title'       : 'Zásady ochrany soukromí',
  'settings_terms_title'                : 'Podmínky použití',
  'settings_app_version_title'          : 'Verze aplikace',
  'settings_email_error'                : 'Nelze otevřít e-mailovou aplikaci. Napište na cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Náhled CV',
  'preview_header_sub'                  : 'Připraveno k exportu',
  'preview_generating'                  : 'Generování vašeho CV...',
  'preview_failed_title'                : 'Náhled se nezdařil',
  'preview_failed_error'                : 'Chyba: {error}',
  'preview_go_back'                     : 'Zpět',
  'preview_no_data'                     : 'Žádná data nejsou k dispozici',
  'preview_btn_print'                   : 'Tisknout',
  'preview_btn_download'                : 'Stáhnout a sdílet',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Nápověda a FAQ',
  'faq_category_all'                    : 'Vše',
  'faq_empty'                           : 'Žádné výsledky nenalezeny',
  'faq_contact_headline'                : 'Stále potřebujete pomoc?',
  'faq_contact_sub'                     : 'Náš tým je tu pro vás.',
  'faq_contact_btn'                     : 'Kontakt',
  'faq_email_error'                     : 'Nelze otevřít e-mailovou aplikaci. Napište na cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Začínáme',
  'faq_cat_templates'                   : 'Šablony',
  'faq_cat_editing'                     : 'Úpravy',
  'faq_cat_exporting'                   : 'Export',
  'faq_cat_data_privacy'                : 'Data a soukromí',
  'faq_cat_troubleshooting'             : 'Řešení problémů',
  'faq_q1'  : 'Jak vytvořím své první CV?',
  'faq_a1'  : 'Klepněte na tlačítko „+" na hlavní obrazovce a zahajte nové CV. Vyberte šablonu odpovídající vašemu stylu, poté krok za krokem vyplňte osobní údaje, pracovní zkušenosti, vzdělání a dovednosti. Váš postup se ukládá automaticky.',
  'faq_q2'  : 'Mohu vytvořit více než jedno CV?',
  'faq_a2'  : 'Ano! Můžete vytvořit více CV pro různé pozice nebo odvětví. Každé CV se ukládá samostatně, takže je můžete přizpůsobit konkrétním pracovním žádostem.',
  'faq_q3'  : 'Jak změním šablonu CV?',
  'faq_a3'  : 'Otevřete CV, klepněte na ikonu šablony v horní části obrazovky a procházejte dostupné šablony. Klepnutím na libovolnou šablonu zobrazíte její náhled s vaším stávajícím obsahem. Potvrďte pro použití.',
  'faq_q4'  : 'Jsou k dispozici bezplatné i prémiové šablony?',
  'faq_a4'  : 'Ano. Výběr profesionálních šablon je dostupný zdarma. Prémiové šablony s pokročilými návrhy a barevnými paletami jsou dostupné prostřednictvím jednorázového nákupu nebo předplatného.',
  'faq_q5'  : 'Jak přidám nebo odstraním sekce?',
  'faq_a5'  : 'V editoru CV přejděte dolů na konec obrazovky a klepněte na „Přidat sekci" pro přidání doplňků jako Jazyky, Certifikace nebo Dobrovolnická práce. Pro odstranění sekce klepněte na záhlaví sekce a vyberte „Odstranit".',
  'faq_q6'  : 'Jak změním pořadí sekcí?',
  'faq_a6'  : 'Dlouze stiskněte úchyt pro přetahování (≡) vedle záhlaví sekce a přetáhněte ji na požadovanou pozici. Změny se ukládají automaticky.',
  'faq_q7'  : 'Jak exportuji CV jako PDF?',
  'faq_a7'  : 'Otevřete CV a klepněte na tlačítko exportu (ikona sdílení) v pravém horním rohu. Vyberte „Exportovat jako PDF". Poté jej můžete uložit do zařízení, sdílet e-mailem, přes WhatsApp nebo nahrát přímo na pracovní portály.',
  'faq_q8'  : 'Jaké formáty souborů jsou podporovány?',
  'faq_a8'  : 'Aplikace aktuálně podporuje export CV jako vysoce kvalitní PDF. Další formáty mohou být přidány v budoucích aktualizacích.',
  'faq_q9'  : 'Kde jsou uložena data mého CV?',
  'faq_a9'  : 'Všechna data CV jsou uložena lokálně ve vašem zařízení. Vaše osobní informace nenahrávame na naše servery. To znamená, že vaše data zůstávají soukromá a přístupná offline.',
  'faq_q10' : 'Jak zálohuji svá CV?',
  'faq_a10' : 'Vaše CV jsou součástí standardní zálohy vašeho zařízení (záloha Google Drive na Androidu, iCloud na iOS), pokud máte zálohu v nastavení zařízení povolenou. Jednotlivá CV můžete také exportovat jako PDF a uchovat kopii.',
  'faq_q11' : 'Aplikace běží pomalu. Co mám dělat?',
  'faq_a11' : 'Zkuste aplikaci zavřít a znovu otevřít. Pokud problém přetrvává, restartujte zařízení. Ujistěte se, že máte nainstalovanou nejnovější verzi aplikace z obchodu Play Store / App Store.',
  'faq_q12' : 'CV se neexportuje správně. Co mám dělat?',
  'faq_a12' : 'Zkontrolujte, zda máte v zařízení dostatek místa. Zkuste zmenšit velké obrázky v CV. Pokud problém přetrvává, kontaktujte náš tým podpory.',
  'faq_q13' : 'Zapomněl jsem uložit — je moje práce ztracena?',
  'faq_a13' : 'Vůbec ne! Aplikace průběžně ukládá váš postup při úpravách.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Vaše kariéra, dokonalá',
  'header_tooltip_back'                 : 'Zpět',
  'header_tooltip_my_cvs'               : 'Moje CV',
  'header_tooltip_settings'             : 'Nastavení',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Moje CV',
  'saved_count_single'                  : '{n} dokument',
  'saved_count_plural'                  : '{n} dokumentů',
  'saved_limit_reached'                 : 'Limit dosažen',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Vše',
  'saved_filter_draft'                  : 'Koncept',
  'saved_filter_complete'               : 'Dokončené',
  'saved_status_complete'               : 'Dokončené',
  'saved_status_saved'                  : 'Uložené',
  'saved_status_draft'                  : 'Koncept',
  'saved_empty_title'                   : 'Zatím žádné CV',
  'saved_empty_sub'                     : 'Začněte tvořit své první CV výše',
  'saved_search_empty_title'            : 'Žádné výsledky nenalezeny',
  'saved_search_empty_sub'              : 'Zkuste jiný vyhledávací výraz',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Barevné schéma',
  'custom_font_settings_title'          : 'Nastavení písma',
  'custom_font_family_label'            : 'Rodina písem',
  'custom_font_size_label'              : 'Velikost písma: ',
  'custom_current_template_title'       : 'Aktuální šablona',
  'custom_change_template_btn'          : 'Změnit šablonu',
  'custom_tpl_modern'                   : 'Moderní',
  'custom_tpl_classic'                  : 'Klasický',
  'custom_tpl_professional'             : 'Profesionální',
  'custom_tpl_creative'                 : 'Kreativní',
  'custom_tpl_minimal'                  : 'Minimální',
  'custom_tpl_modern_desc'              : 'Čistý a moderní design',
  'custom_tpl_classic_desc'             : 'Tradiční profesionální rozvržení',
  'custom_tpl_professional_desc'        : 'Šablona zaměřená na podnikání',
  'custom_tpl_creative_desc'            : 'Vynikněte jedinečným designem',
  'custom_tpl_minimal_desc'             : 'Jednoduchý a elegantní styl',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Vyberte šablonu',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Vedoucí',
  'tpl_nordic_name'                     : 'Nordický',
  'tpl_vibrant_name'                    : 'Živý',
  'tpl_tech_dark_name'                  : 'Tech Tmavý',
  'tpl_luxury_name'                     : 'Luxusní',
  'tpl_executive_tag'                   : 'Nejoblíbenější',
  'tpl_nordic_tag'                      : 'Čistý',
  'tpl_vibrant_tag'                     : 'Kreativní',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elitní',
  'tpl_executive_desc'                  : 'Odvážný a autoritativní pro vedoucí pozice',
  'tpl_nordic_desc'                     : 'Minimální přehlednost důvěryhodná u předních firem',
  'tpl_vibrant_desc'                    : 'Vynikněte energií a barvami',
  'tpl_tech_dark_desc'                  : 'Terminálová estetika pro vývojáře',
  'tpl_luxury_desc'                     : 'Zlatem zdobená prestiž na černém pozadí',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Šablona',
  'detail_step_personal'                : 'Osobní',
  'detail_step_experience'              : 'Zkušenosti',
  'detail_step_education'               : 'Vzdělání',
  'detail_step_skills'                  : 'Dovednosti',
  'detail_step_additional'              : 'Doplňkové',
  'detail_step_references'              : 'Reference',
  'detail_step_customize'               : 'Přizpůsobit',
  'detail_banner_heading'               : 'Téměř hotovo!',
  'detail_banner_btn'                   : 'Pokračovat',
  'detail_banner_completion_label'      : 'Dokončení',
  'detail_stat_created_label'           : 'Vytvořeno',
  'detail_stat_steps_label'             : 'Kroky splněny',
  'detail_section_template_style'       : 'Styl šablony',
  'detail_section_steps'                : 'Kroky',
  'detail_steps_counter'                : '{done} z {total} dokončeno',
  'detail_step_sub'                     : 'Krok {n} z {total}',
  'detail_section_activity'             : 'Aktivita',
  'detail_activity_created'             : 'Vytvořeno',
  'detail_activity_last_edited'         : 'Naposledy upraveno',
  'detail_activity_template'            : 'Šablona',
  'detail_btn_continue_editing'         : 'Pokračovat v úpravách',
  'detail_btn_edit_cv'                  : 'Upravit CV',
  'detail_option_rename'                : 'Přejmenovat CV',
  'detail_option_delete'                : 'Smazat CV',
  'detail_rename_title'                 : 'Přejmenovat CV',
  'detail_rename_hint'                  : 'např. CV softwarového inženýra',
  'detail_rename_error_empty'           : 'Název nesmí být prázdný',
  'detail_rename_btn_cancel'            : 'Zrušit',
  'detail_rename_btn_save'              : 'Uložit',
  'detail_rename_snackbar'              : 'Přejmenováno na „{name}"',
  'detail_delete_title'                 : 'Smazat CV?',
  'detail_delete_body'                  : 'Tím trvale smažete „{name}". Tuto akci nelze vrátit zpět.',
  'detail_delete_btn_cancel'            : 'Zrušit',
  'detail_delete_btn_confirm'           : 'Smazat',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Dokončeno',
  'detail_check_tile_incomplete'        : 'Zatím nevyplněno',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Vyberte šablonu',
  'chooser_subtitle'                    : 'Přejeďte prstem k procházení  ·  Klepněte pro výběr  ·  Podržte pro náhled',
  'chooser_card_hold_hint'              : 'Podržte pro náhled',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Vybráno',
  'chooser_modal_heading'               : 'Pojmenujte své CV',
  'chooser_modal_sub'                   : 'Dejte mu název, abyste ho snadno našli v Moje CV a Historii.',
  'chooser_modal_field_label'           : 'Název CV',
  'chooser_modal_save_btn'              : 'Uložit a začít tvořit',
  'chooser_modal_divider'               : 'nebo pokračovat v existujícím CV',
  'chooser_nav_selected_sub'            : 'Vybraná šablona',
  'chooser_nav_cta'                     : 'Uložit a pokračovat',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maximální počet záznamů dosažen',
  'editor_show_hide'                    : 'Zobrazit/Skrýt',
  'editor_editing_badge'                : 'Upravování',
  'editor_field_required'               : 'Povinné',
  'editor_tooltip_edit'                 : 'Upravit',
  'editor_tooltip_delete'               : 'Smazat',
  'editor_date_start'                   : 'Datum zahájení *',
  'editor_date_end'                     : 'Datum ukončení *',
  'editor_date_tap_hint'                : 'Klepnutím vyberte',
  'editor_date_dialog_title'            : 'Vyberte měsíc a rok',
  'editor_date_confirm'                 : 'Potvrdit',
  'editor_panel_hide'                   : 'Skrýt',
  'editor_panel_show'                   : 'Zobrazit',
  'editor_validator_max_chars'          : 'Max {n} znaků',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Sestavte své CV',
  'editor_header_step_sub'              : 'Krok {current} z {total} · {label}',
  'editor_step_template'                : 'Šablona',
  'editor_step_personal'                : 'Osobní',
  'editor_step_experience'              : 'Zkušenosti',
  'editor_step_education'               : 'Vzdělání',
  'editor_step_skills'                  : 'Dovednosti',
  'editor_step_additional'              : 'Doplňkové',
  'editor_step_references'              : 'Reference',
  'editor_step_customize'               : 'Přizpůsobit',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Přizpůsobit',
  'customize_subtitle'                  : 'Udělejte CV jedinečně vaším',
  'customize_smart_layout_btn'          : 'Chytré rozvržení',
  'customize_back_to_top'               : 'Zpět nahoru',
  'customize_done_title'                : 'Vše je připraveno!',
  'customize_done_sub'                  : 'Klepněte na Náhled CV níže pro zobrazení hotového CV',
  'customize_preview_btn'               : 'Náhled CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Barevné schéma',
  'color_black'                         : 'Černá',
  'color_blue'                          : 'Modrá',
  'color_nordic_blue'                   : 'Nordická modrá',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Šedozelená',
  'color_green'                         : 'Zelená',
  'color_purple'                        : 'Fialová',
  'color_orange'                        : 'Oranžová',
  'color_red'                           : 'Červená',
  'color_executive_gold'                : 'Zlatá vedoucího',
  'color_vibrant_coral'                 : 'Živá korálová',
  'color_white'                         : 'Bílá',
  'color_white_bg'                      : 'Bílé pozadí',
  'color_maroon'                        : 'Kaštanová',
  'color_brutalist_yellow'              : 'Brutalistická žlutá',
  'color_neon_blue'                     : 'Neonová modrá',
  'color_blueprint_navy'                : 'Námořnická modrá',
  'color_light_grey'                    : 'Světle šedá',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Rodina písem',
  'customize_font_picker_title'         : 'Vyberte písmo',
  'customize_font_picker_sub'           : 'Každé písmo je zobrazeno ve vlastním fontu',
  'customize_font_preview_sample'       : 'Příklad textu písma',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Velikost písma',
  'customize_font_size_label'           : 'Velikost textu',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Velikost obrázku',
  'customize_image_size_label'          : 'Velikost obrázku',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Živý náhled',
  'preview_page_count_singular'         : '1 strana',
  'preview_page_count_plural'           : '{n} stran',
  'preview_page_of'                     : 'Strana {page} z {total}',
  'preview_live_hint'                   : 'Změny se projeví okamžitě',
  'preview_template_unregistered'       : 'Zatím nezaregistrováno v customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Příprava vašeho CV…',
  'preview_bar_print'                   : 'Tisknout',
  'preview_bar_save_pdf'                : 'Uložit jako PDF',
  'preview_bar_share'                   : 'Sdílet',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Náhled CV',
  'preview_screen_sub'                  : '{n} {unit} · přesně jak bude vytištěno',
  'preview_page_singular'               : 'strana',
  'preview_page_plural'                 : 'stran',
  'preview_pdf_filename'                : 'Moje_CV',
  'preview_share_subject'               : 'Moje CV',
  'preview_snack_print_failed'          : 'Tisk se nezdařil: {e}',
  'preview_snack_saved'                 : 'CV uloženo do Stažených souborů ✓',
  'preview_snack_export_failed'         : 'Export se nezdařil: {e}',
  'preview_snack_share_failed'          : 'Sdílení se nezdařilo: {e}',
  'preview_template_not_registered'     : 'Šablona není zaregistrována',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Zavřít náhled',
  'preview_modal_hint_photo'            : 'Podporuje profilovou fotografii  ·  Klepnutím na kartu vyberte',
  'preview_modal_hint_no_photo'         : 'Klepnutím na kartu šablony ji vyberte',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Moje CV',
  'time_just_now'                       : 'Právě teď',
  'time_minutes_ago'                    : 'před {n} min',
  'time_hours_ago'                      : 'před {n} h',
  'time_yesterday'                      : 'Včera',
  'time_days_ago'                       : 'před {n} dny',
  'time_one_week_ago'                   : 'před 1 týdnem',
  'time_weeks_ago'                      : 'před {n} týdny',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegantní',
  'tpl_tag_classic'                     : 'Klasický',
  'tpl_tag_minimal'                     : 'Minimální',
  'tpl_tag_creative'                    : 'Kreativní',
  'tpl_tag_bold'                        : 'Odvážný',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Přechod',
  'tpl_gradient_desc'                   : 'Karty s přechodem od tyrkysové k fialové',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Redakční',
  'tpl_editorial_desc'                  : 'Styl magazínu v červené a krémové',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Jemný pastel',
  'tpl_pastel_soft_desc'                : 'Levandulový postranní panel, jemné karty',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalistický',
  'tpl_brutalist_desc'                  : 'Hrubá mřížka, tučné ohraničení a žlutá',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragdový',
  'tpl_emerald_desc'                    : 'Lesní zelená s časovou osou',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografika',
  'tpl_infographic_desc'                : 'Tmavé plátno s kruhovými grafy',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Geometický zlatý luxus 20. let',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Tmavý',
  'tpl_wina_dark_desc'                  : 'Tmavá infografika s kruhy',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Oranžový',
  'tpl_rio_orange_desc'                 : 'Tmavý postranní panel s oranžovým akcentem',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Letní',
  'tpl_summer_desc'                     : 'Čistý minimální, jemné šedé tóny',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Teplé béžové elegantní tóny',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Strohá černo-bílá klasika',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klasické rozvržení vhodné pro ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Tmavý',
  'tpl_tony_dark_desc'                  : 'Tmavý oranžový infografický styl',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Technický výkres na mřížce',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivář',
  'tpl_archivist_desc'                  : 'Klasické dvousloupcové rozvržení s popisky',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Stínovaná záhlaví s kosočtvercovými zarážkami',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridián',
  'tpl_meridian_desc'                   : 'Centrovaná záhlaví, zvýrazněné společnosti',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Tučné jméno, tečky časové osy a úspěchy',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Osobní informace',
  'personal_subtitle'                   : 'Představte se zaměstnavatelům',
  'personal_profile_counter'            : '{n}/{max} profilů',
  'personal_info_banner'                : 'Uložte až 5 profilů a vyberte jeden pro každé CV. Váš výběr se pro každé CV ukládá samostatně.',
  'personal_snack_max'                  : 'Byl dosažen maximální počet {n} profilů.',
  'personal_add_btn'                    : 'Přidat nový profil',
  'personal_library_title'              : 'Uložené profily',
  'personal_selected_one'               : '1 vybráno',
  'personal_selected_none'              : 'nic nevybráno',
  'personal_library_hint'               : 'Klepnutím na kartu ji vyberete pouze pro toto CV. Ostatní CV si uchovají vlastní nezávislé výběry.',
  'personal_empty_message'              : 'Zatím nejsou uloženy žádné profily',
  'personal_empty_sub'                  : 'Klepnutím výše přidejte osobní informace',
  'personal_nav_next'                   : 'Uložit a pokračovat',
  'personal_card_active_badge'          : 'Aktivní pro toto CV',
  'personal_sheet_title_add'            : 'Nový profil',
  'personal_sheet_title_edit'           : 'Upravit profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTICKÝ',
  'personal_sheet_brutalist_banner'     : 'Brutalistická šablona má kompaktní kontaktní pole. Nejlépe se zobrazují kratší hodnoty (např. pouze město).',
  'personal_section_photo'              : 'Profilová fotografie',
  'personal_section_basic'              : 'Základní údaje',
  'personal_section_contact'            : 'Kontakt',
  'personal_section_online'             : 'Online přítomnost',
  'personal_section_summary'            : 'Profesionální shrnutí',
  'personal_field_first_name'           : 'Jméno *',
  'personal_field_last_name'            : 'Příjmení',
  'personal_field_job_title'            : 'Pracovní pozice *',
  'personal_field_email'                : 'E-mailová adresa *',
  'personal_field_phone'                : 'Telefonní číslo *',
  'personal_field_location'             : 'Město',
  'personal_field_location_brut'        : 'Město (pouze město)',
  'personal_field_website'              : 'Webové stránky / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'např. Jan',
  'personal_hint_last_name'             : 'např. Novák',
  'personal_hint_job_title'             : 'např. Senior inženýr',
  'personal_hint_email'                 : 'např. jan@example.com',
  'personal_hint_phone'                 : 'např. +420 123 456 789',
  'personal_hint_location'              : 'např. Praha, Česká republika',
  'personal_hint_location_brut'         : 'např. Praha, CZ',
  'personal_hint_website'               : 'např. github.com/jannovak',
  'personal_hint_website_brut'          : 'např. github.com/jan',
  'personal_hint_linkedin'              : 'např. linkedin.com/in/jannovak',
  'personal_hint_linkedin_brut'         : 'např. linkedin.com/in/jan',
  'personal_summary_hint_label'         : 'Buďte stručný — toto se zobrazí v horní části vašeho CV.',
  'personal_hint_summary'               : 'Stručné shrnutí vašeho zázemí a cílů v 2–3 větách...',
  'personal_validator_email'            : 'Zadejte platný e-mail',
  'personal_field_char_limit_tooltip'   : 'Byl dosažen limit znaků',
  'personal_sheet_btn_save'             : 'Uložit profil',
  'personal_sheet_btn_update'           : 'Uložit změny',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Vybrat fotografii',
  'photo_option_gallery'                : 'Vybrat z galerie',
  'photo_option_camera'                 : 'Vyfotit',
  'photo_option_reposition'             : 'Přemístit fotografii',
  'photo_option_remove'                 : 'Odebrat fotografii',
  'photo_status_added'                  : 'Fotografie přidána ✓',
  'photo_status_empty'                  : 'Přidejte profesionální fotografii',
  'photo_chip_gallery'                  : 'Galerie',
  'photo_chip_camera'                   : 'Fotoaparát',
  'photo_chip_reposition'               : 'Přemístit',
  'photo_reposition_title'              : 'Přemístit fotografii',
  'photo_reposition_sub'                : 'Přetáhněte fotografii pro úpravu polohy',
  'photo_reposition_reset'              : 'Resetovat na střed',
  'photo_reposition_apply'              : 'Použít',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Dovednosti',
  'skills_subtitle'                     : 'Zdůrazněte své klíčové schopnosti',
  'skills_add_btn'                      : 'Přidat novou dovednost',
  'skills_snack_max_icons'              : 'Byl dosažen maximální počet 10 ikon.',
  'skills_snack_max_skills'             : 'Byl dosažen maximální počet 15 dovedností.',
  'skills_library_title'                : 'Uložené dovednosti',
  'skills_library_hint'                 : 'Zaškrtnuté dovednosti jsou zahrnuty v tomto CV. Vaše výběry se ukládají automaticky.',
  'skills_nav_next'                     : 'Pokračovat na Doplňkové',
  'skills_wina_header_icon_bar'         : 'Lišta ikon v záhlaví',
  'skills_wina_on'                      : 'ZAP',
  'skills_wina_off'                     : 'VYP',
  'skills_wina_bar_on_sub'              : 'Barevné kruhy ikon zobrazeny v záhlaví CV.',
  'skills_wina_bar_off_sub'             : 'Řada ikon skryta — více místa pro kontaktní informace.',
  'skills_wina_palette_hint'            : 'Ikony se zobrazují jako barevné kruhy v pořadí palety.',
  'skills_wina_preview_label'           : 'Náhled',
  'skills_wina_disabled_hint'           : 'Povolte lištu ikon výše a vyberte, které ikony se zobrazí v záhlaví CV.',
  'skills_sheet_title_add'              : 'Přidat dovednost',
  'skills_sheet_title_edit'             : 'Upravit dovednost',
  'skills_sheet_field_name'             : 'Název dovednosti *',
  'skills_sheet_hint_short'             : 'např. Flutter, Design',
  'skills_sheet_hint_long'              : 'např. Flutter, Projektový management',
  'skills_sheet_validator_max'          : 'Max {n} znaků',
  'skills_sheet_proficiency'            : 'Úroveň znalostí',
  'skills_sheet_beginner'               : 'Začátečník',
  'skills_sheet_expert'                 : 'Expert',
  'skills_sheet_btn_save'               : 'Uložit dovednost',
  'skills_sheet_btn_update'             : 'Aktualizovat dovednost',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Osobní reference',
  'refs_subtitle'                       : 'Lidé, kteří za vás mohou osobně ručit',
  'refs_add_btn'                        : 'Přidat novou osobní referenci',
  'refs_snack_max_selected'             : 'Pro CV lze vybrat maximálně 4 reference.',
  'refs_snack_max_saved'                : 'Byl dosažen maximální počet 10 uložených referencí.',
  'refs_library_title'                  : 'Uložené reference',
  'refs_library_hint'                   : 'Zaškrtnuté reference jsou zahrnuty v tomto CV. Max 4 na CV. Vaše výběry se ukládají automaticky.',
  'refs_nav_next'                       : 'Pokračovat na Přizpůsobit',
  'refs_sheet_title_add'                : 'Přidat osobní referenci',
  'refs_sheet_title_edit'               : 'Upravit osobní referenci',
  'refs_sheet_sub_add'                  : 'Někdo, kdo vás může osobně doporučit zaměstnavatelům.',
  'refs_sheet_sub_edit'                 : 'Aktualizujte údaje této reference níže.',
  'refs_sheet_field_name'               : 'Celé jméno *',
  'refs_sheet_field_title'              : 'Pracovní pozice *',
  'refs_sheet_field_company'            : 'Společnost (nepovinné)',
  'refs_sheet_field_email'              : 'E-mailová adresa *',
  'refs_sheet_field_phone'              : 'Telefonní číslo *',
  'refs_sheet_hint_name'                : 'např. Jakub Novák',
  'refs_sheet_hint_title'               : 'např. Vedoucí inženýringu',
  'refs_sheet_hint_company'             : 'např. Acme Corp',
  'refs_sheet_hint_email'               : 'např. jakub@acme.com',
  'refs_sheet_hint_phone'               : 'např. +420 123 456 789',
  'refs_sheet_validator_email'          : 'Zadejte platnou e-mailovou adresu',
  'refs_sheet_btn_save'                 : 'Uložit osobní referenci',
  'refs_sheet_btn_update'               : 'Aktualizovat osobní referenci',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Pracovní zkušenosti',
  'exp_subtitle'                        : 'Přidejte svou pracovní historii',
  'exp_banner_info'                     : 'Na CV se zobrazí až {n} povinností na pozici. 3–6 pozic se obvykle vejde na 1–2 strány.',
  'exp_add_btn'                         : 'Přidat novou zkušenost',
  'exp_snack_max_selected'              : 'Pro CV lze vybrat maximálně 8 zkušeností.',
  'exp_snack_max_saved'                 : 'Byl dosažen maximální počet 12 uložených zkušeností.',
  'exp_library_title'                   : 'Uložené zkušenosti',
  'exp_library_hint'                    : 'Zaškrtnuté záznamy jsou zahrnuty pouze v tomto CV. Ostatní CV si uchovají vlastní nezávislé výběry.',
  'exp_nav_next'                        : 'Pokračovat na Vzdělání',
  'exp_empty_message'                   : 'Zatím nejsou přidány žádné zkušenosti',
  'exp_empty_sub'                       : 'Klepnutím výše přidejte svou první pozici',
  'exp_card_resp_singular'              : 'povinnost',
  'exp_card_resp_plural'                : 'povinností',
  'exp_card_resp_tooltip'               : 'Na CV se zobrazí pouze prvních 8 povinností',
  'exp_sheet_title_add'                 : 'Přidat zkušenost',
  'exp_sheet_title_edit'                : 'Upravit zkušenost',
  'exp_sheet_field_job_title'           : 'Pracovní pozice *',
  'exp_sheet_field_company'             : 'Společnost *',
  'exp_sheet_field_location'            : 'Město',
  'exp_sheet_section_responsibilities'  : 'Klíčové povinnosti',
  'exp_sheet_resp_hint_info'            : 'Max 8 odrážek · 200 znaků každá',
  'exp_sheet_resp_label'                : 'Povinnost {n}',
  'exp_sheet_resp_hint'                 : 'např. Vedl tým 5 inženýrů',
  'exp_sheet_resp_add_btn'              : 'Přidat povinnost',
  'exp_sheet_resp_max_info'             : 'Byl dosažen maximální počet {n} povinností',
  'exp_sheet_resp_validator_max'        : 'Max 200 znaků',
  'exp_sheet_hint_job_title'            : 'např. Senior vývojář',
  'exp_sheet_hint_location'             : 'např. Praha, ČR',
  'exp_sheet_btn_save'                  : 'Uložit zkušenost',
  'exp_sheet_btn_update'                : 'Uložit změny',
  'exp_date_present'                    : 'Současnost / Aktuální pozice',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Vzdělání',
  'edu_subtitle'                        : 'Přidejte své akademické vzdělání',
  'edu_add_btn'                         : 'Přidat nové vzdělání',
  'edu_snack_max_selected'              : 'Pro CV lze vybrat maximálně 8 vzdělávacích záznamů.',
  'edu_snack_max_saved'                 : 'Byl dosažen maximální počet 12 uložených vzdělávacích záznamů.',
  'edu_library_title'                   : 'Uložené vzdělání',
  'edu_library_hint'                    : 'Zaškrtnuté záznamy jsou zahrnuty v tomto CV. Vaše výběry se ukládají automaticky.',
  'edu_nav_next'                        : 'Pokračovat na Dovednosti',
  'edu_empty_message'                   : 'Zatím není přidáno žádné vzdělání',
  'edu_empty_sub'                       : 'Klepnutím výše přidejte své kvalifikace',
  'edu_card_bullet_singular'            : 'odrážka',
  'edu_card_bullet_plural'              : 'odrážek',
  'edu_sheet_title_add'                 : 'Přidat vzdělání',
  'edu_sheet_title_edit'                : 'Upravit vzdělání',
  'edu_sheet_field_degree'              : 'Titul / Kvalifikace *',
  'edu_sheet_field_institution'         : 'Instituce *',
  'edu_sheet_section_key_points'        : 'Klíčové body',
  'edu_sheet_key_points_hint_info'      : 'Nepovinné · 1 odrážka · max 100 znaků',
  'edu_sheet_point_label'               : 'Bod {n}',
  'edu_sheet_point_add_btn'             : 'Přidat odrážku',
  'edu_sheet_point_max_info'            : 'Byl dosažen maximální počet {n} odrážek',
  'edu_sheet_point_validator_max'       : 'Max {n} znaků',
  'edu_sheet_hint_degree'               : 'např. Bc. Informatika',
  'edu_sheet_hint_institution'          : 'např. Karlova univerzita',
  'edu_sheet_hint_bullet'               : 'např. Absolvováno s vyznamenáním',
  'edu_sheet_btn_save'                  : 'Uložit vzdělání',
  'edu_sheet_btn_update'                : 'Uložit změny',
  'edu_date_present'                    : 'Současnost / Probíhající studium',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Doplňkové informace',
  'additional_subtitle'                 : 'Certifikace, jazyky a další',
  'additional_cert_section_title'       : 'Certifikace',
  'additional_cert_counter'             : '{sel}/{total} vybráno · max {max}',
  'additional_cert_hide'                : 'Skrýt',
  'additional_cert_show'                : 'Zobrazit',
  'additional_cert_add_btn'             : 'Přidat',
  'additional_cert_snack_max'           : 'Byl dosažen maximální počet {n} certifikačních záznamů.',
  'additional_cert_hint'                : 'Zaškrtnuté záznamy jsou zahrnuty v tomto CV. Vaše výběry se ukládají automaticky.',
  'additional_cert_empty'               : 'Zatím nejsou přidány žádné certifikace',
  'additional_lang_section_title'       : 'Jazyky',
  'additional_lang_add_hint'            : 'např. Španělština',
  'additional_lang_snack_max'           : 'Byl dosažen maximální počet {n} jazykových záznamů.',
  'additional_lang_empty'               : 'Zatím nejsou přidány žádné jazyky',
  'additional_hobby_section_title'      : 'Koníčky a zájmy',
  'additional_hobby_add_hint'           : 'např. Fotografování',
  'additional_hobby_snack_max'          : 'Byl dosažen maximální počet {n} koníčků.',
  'additional_hobby_empty'              : 'Zatím nejsou přidány žádné koníčky',
  'additional_section_hint'             : 'Zaškrtnuté záznamy jsou zahrnuty v tomto CV. Vaše výběry se ukládají automaticky.',
  'additional_nav_next'                 : 'Pokračovat na Reference',
  'cert_sheet_title_add'                : 'Přidat certifikaci',
  'cert_sheet_title_edit'               : 'Upravit certifikaci',
  'cert_sheet_sub'                      : 'Přidejte kvalifikaci, certifikát nebo profesionální pověření.',
  'cert_sheet_field_name'               : 'Název certifikace *',
  'cert_sheet_field_issued_by'          : 'Vydáno kým (nepovinné)',
  'cert_sheet_field_short_desc'         : 'Krátký popis (nepovinné)',
  'cert_sheet_hint_name'                : 'např. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'např. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'např. Získáno 2024',
  'cert_sheet_btn_save'                 : 'Uložit certifikaci',
  'cert_sheet_btn_update'               : 'Aktualizovat certifikaci',
  'simple_sheet_title_add_language'     : 'Přidat jazyk',
  'simple_sheet_title_edit_language'    : 'Upravit jazyk',
  'simple_sheet_title_add_hobby'        : 'Přidat koníček',
  'simple_sheet_title_edit_hobby'       : 'Upravit koníček',
  'simple_sheet_btn_save'               : 'Uložit',
  'simple_sheet_btn_update'             : 'Aktualizovat',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontakt',
  'pdf_section_about_me'                : 'O mně',
  'pdf_section_summary'                 : 'Shrnutí',
  'pdf_section_summary_short'           : 'Shrnutí',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Zkušenosti',
  'pdf_section_experience_short'        : 'Zkušenosti',
  'pdf_section_education'               : 'Vzdělání',
  'pdf_section_skills'                  : 'Dovednosti',
  'pdf_section_languages'               : 'Jazyky',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Lokalita',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Dosažen limit životopisů',
  'limit_dialog_body'                   : 'Dosáhli jste maximálního počtu 30 životopisů. Před vytvořením nového prosím smažte stávající.',
  'limit_dialog_go_to_my_cvs'           : 'Přejít na Moje životopisy',
  'limit_dialog_cancel'                 : 'Zrušit',
  'refs_count_summary'                  : '{checked}/{maxChecked} vybráno · {saved}/{maxSaved} uloženo',
  'refs_selected_badge'                 : '{n} vybráno',
  'refs_empty_message'                  : 'Zatím žádné uložené reference',
  'refs_empty_sub'                      : 'Klepnutím výše přidejte osobní referenci',
};