// lib/language_keys/lang_ur_urdu.dart
//
// Urdu (اردو) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> urUrdu = {

  // ─── language_ui_select.dart ────────────────────────────────────────────────
  'lang_select_no_results'              : 'کوئی زبان نہیں ملی',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'چھوڑیں',
  'onboarding_next'                     : 'آگے',
  'onboarding_get_started'              : 'شروع کریں',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────────
  'ob1_tag'                             : '✦  خوش آمدید',
  'ob1_title'                           : 'پیشہ ورانہ CV بنائیں\nجو دروازے کھولے',
  'ob1_body'                            : 'سینکڑوں درخواست گزاروں سے آگے نکلیں — منٹوں میں پیشہ ورانہ CV بنائیں، کوئی ڈیزائن مہارت درکار نہیں',
  'ob1_pill_label'                      : 'پیشہ ورانہ CV بنانے کا آلہ',
  'ob1_chip_templates'                  : '24+ ٹیمپلیٹس',
  'ob1_chip_pdf'                        : 'PDF برآمد',
  'ob1_chip_free'                       : 'مفت استعمال',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────────
  'ob2_tag'                             : '✦  ٹیمپلیٹس',
  'ob2_title'                           : 'ہر صنعت\nہر خواہش',
  'ob2_body'                            : 'میٹنگ روم لے آؤٹ سے لے کر تخلیقی ڈیزائن تک — ایسے ٹیمپلیٹس جو آپ کی کہانی بیان کریں',
  'ob2_tap_hint'                        : 'ٹیمپلیٹ دیکھنے کے لیے تھپتھپائیں',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'کارپوریٹ',
  'ob2_tag_creative'                    : 'تخلیقی',
  'ob2_tag_minimal'                     : 'سادہ',
  'ob2_tag_modern'                      : 'جدید',
  'ob2_tag_premium'                     : 'پریمیم',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart Layout',
  'ob3_title'                           : 'آپ کا CV\nخودکار طریقے سے ترتیب پائے',
  'ob3_body'                            : 'Smart Layout آپ کے حصوں کو بہترین اثر کے لیے ترتیب دیتا ہے — اپنی مضبوط ترین خوبیاں وہاں رکھیں جہاں بھرتی کار پہلے دیکھتے ہیں',
  'ob3_badge_smart_layout'              : 'Smart Layout',
  'ob3_badge_cv_ready'                  : 'CV تیار ہے!',
  'ob3_step1_label'                     : 'ٹیمپلیٹ چنیں',
  'ob3_step1_desc'                      : '24+ خوبصورت ڈیزائنوں میں سے انتخاب کریں',
  'ob3_step2_label'                     : 'اپنی معلومات بھریں',
  'ob3_step2_desc'                      : 'ہر حصے کے لیے مددگار اشارے کے ساتھ آسان فارم',
  'ob3_step3_label'                     : 'Smart Layout',
  'ob3_step3_desc'                      : 'ایک ٹیپ میں CV کو کامل طریقے سے ترتیب دیں',
  'ob3_step4_label'                     : 'PDF برآمد کریں',
  'ob3_step4_desc'                      : 'اعلی معیار کا PDF بھیجنے کے لیے تیار',
  'ob3_section_work'                    : 'کام کا تجربہ',
  'ob3_section_education'               : 'تعلیم',
  'ob3_section_skills'                  : 'مہارتیں',
  'ob3_section_references'              : 'حوالہ جات',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────────
  'ob4_tag'                             : '✦  تیار ہیں',
  'ob4_title'                           : 'اعلی درجے کے درخواست گزار\nCV Builder کیوں چنتے ہیں',
  'ob4_visual_headline'                 : 'آپ تیار ہیں!',
  'ob4_visual_subline'                  : 'کام کرنے کے لیے وہ سب کچھ جو آپ کو چاہیے',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'ٹیمپلیٹس',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'زیادہ سے زیادہ CVs',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'برآمد',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'نجی',
  'ob4_hl1_title'                       : 'نجی اور محفوظ',
  'ob4_hl1_sub'                         : 'ڈیٹا آپ کے آلے پر محفوظ',
  'ob4_hl2_title'                       : 'خودکار محفوظ',
  'ob4_hl2_sub'                         : 'ہر تبدیلی فوری محفوظ',
  'ob4_hl3_title'                       : '30 CVs تک',
  'ob4_hl3_sub'                         : 'ہر عہدے کے لیے الگ CV',
  'ob4_hl4_title'                       : 'ایک ٹیپ میں شیئر',
  'ob4_hl4_sub'                         : 'ایپ سے باہر نکلے بغیر PDF بھیجیں',

  // ─── home_screen.dart ───────────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ دوسروں سے آگے نکلیں',
  'home_hero_title'                     : 'اپنا پیشہ ورانہ\nCV بنائیں',
  'home_hero_sub'                       : 'منٹوں میں خوبصورت\nریزیومے بنائیں',
  'home_hero_cta'                       : 'بنانا شروع کریں',
  'home_premium_soon'                   : 'جلد Pro پر اپ گریڈ کریں!',

  // ─── history_screen.dart ────────────────────────────────────────────────────
  'history_sort_most_recent'            : 'تازہ ترین',
  'history_sort_alphabetical'           : 'الف–ی',
  'history_sort_last_edited'            : 'آخری ترمیم',
  'history_sort_by_template'            : 'ٹیمپلیٹ کے مطابق',
  'history_sort_sheet_title'            : 'ترتیب دیں بلحاظ',
  'history_sort_alphabetical_full'      : 'حروف تہجی کے مطابق (الف–ی)',
  'history_premium_soon'                : 'جلد Pro پر اپ گریڈ کریں!',

  // ─── settings_screen.dart ───────────────────────────────────────────────────
  'settings_title'                      : 'ترتیبات',
  'settings_section_preferences'        : 'ترجیحات',
  'settings_section_support'            : 'سپورٹ',
  'settings_section_legal'              : 'قانونی',
  'settings_section_about'              : 'کے بارے میں',
  'settings_language_tile_title'        : 'زبان',
  'settings_dark_mode_title'            : 'ڈارک موڈ',
  'settings_dark_mode_on'               : 'گہرا تھیم فعال',
  'settings_dark_mode_off'              : 'ہلکا تھیم فعال',
  'settings_help_faq_title'             : 'مدد اور FAQ',
  'settings_help_faq_sub'               : 'عام سوالات کے جوابات',
  'settings_contact_support_title'      : 'سپورٹ سے رابطہ کریں',
  'settings_rate_app_title'             : 'ایپ کو ریٹ کریں',
  'settings_rate_app_sub'               : 'ایپ پسند ہے؟ ریویو دیں!',
  'settings_privacy_policy_title'       : 'رازداری کی پالیسی',
  'settings_terms_title'                : 'سروس کی شرائط',
  'settings_app_version_title'          : 'ایپ ورژن',
  'settings_email_error'                : 'ای میل ایپ نہیں کھل سکی۔ براہ کرم cyberinc101@gmail.com پر ای میل بھیجیں',

  // ─── preview_screen.dart ────────────────────────────────────────────────────
  'preview_header_title'                : 'CV پیش نظارہ',
  'preview_header_sub'                  : 'بھیجنے کے لیے تیار',
  'preview_generating'                  : 'آپ کا CV تیار ہو رہا ہے...',
  'preview_failed_title'                : 'پیش نظارہ ناکام',
  'preview_failed_error'                : 'خرابی: {error}',
  'preview_go_back'                     : 'واپس جائیں',
  'preview_no_data'                     : 'کوئی ڈیٹا نہیں',
  'preview_btn_print'                   : 'پرنٹ',
  'preview_btn_download'                : 'ڈاؤنلوڈ اور شیئر',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────────
  'faq_title'                           : 'مدد اور FAQ',
  'faq_category_all'                    : 'سب',
  'faq_empty'                           : 'کوئی نتیجہ نہیں',
  'faq_contact_headline'                : 'ابھی بھی مدد چاہیے؟',
  'faq_contact_sub'                     : 'ہماری ٹیم آپ کی مدد کے لیے تیار ہے',
  'faq_contact_btn'                     : 'رابطہ کریں',
  'faq_email_error'                     : 'ای میل ایپ نہیں کھل سکی۔ براہ کرم cyberinc101@gmail.com پر ای میل بھیجیں',
  'faq_cat_getting_started'             : 'شروعات',
  'faq_cat_templates'                   : 'ٹیمپلیٹس',
  'faq_cat_editing'                     : 'ترمیم',
  'faq_cat_exporting'                   : 'برآمد',
  'faq_cat_data_privacy'                : 'ڈیٹا اور رازداری',
  'faq_cat_troubleshooting'             : 'مسئلہ حل کرنا',
  'faq_q1'  : 'میں اپنا پہلا CV کیسے بناؤں؟',
  'faq_a1'  : 'نیا CV شروع کرنے کے لیے ہوم اسکرین پر "+" بٹن تھپتھپائیں۔ اپنے انداز کے مطابق ٹیمپلیٹ چنیں، پھر ذاتی معلومات، کام کا تجربہ، تعلیم اور مہارتیں قدم بہ قدم بھریں۔ آپ کی پیشرفت خودکار محفوظ ہوتی رہے گی',
  'faq_q2'  : 'کیا میں ایک سے زیادہ CVs بنا سکتا ہوں؟',
  'faq_a2'  : 'بالکل! آپ مختلف ملازمتوں یا صنعتوں کے لیے متعدد CVs بنا سکتے ہیں۔ ہر CV الگ محفوظ ہوتا ہے، اس لیے آپ ہر درخواست کے لیے الگ CV تیار کر سکتے ہیں',
  'faq_q3'  : 'میں اپنے CV کا ٹیمپلیٹ کیسے بدلوں؟',
  'faq_a3'  : 'اپنا CV کھولیں اور اسکرین کے اوپر ٹیمپلیٹ آئیکن تھپتھپائیں۔ دستیاب ٹیمپلیٹس دیکھیں اور کوئی بھی موجودہ مواد کے ساتھ پیش نظارہ کے لیے چنیں، پھر تصدیق کریں',
  'faq_q4'  : 'کیا مفت اور پریمیم ٹیمپلیٹس ہیں؟',
  'faq_a4'  : 'ہاں، کچھ پیشہ ورانہ ٹیمپلیٹس مفت ہیں۔ اعلی ڈیزائن اور رنگوں والے پریمیم ٹیمپلیٹس ایک بار خریدے جا سکتے ہیں یا سبسکرپشن سے حاصل کیے جا سکتے ہیں',
  'faq_q5'  : 'میں حصے کیسے شامل یا ہٹاؤں؟',
  'faq_a5'  : 'CV ایڈیٹر میں نیچے سکرول کریں اور "حصہ شامل کریں" تھپتھپائیں تاکہ زبانیں، سرٹیفکیٹ یا رضاکارانہ کام شامل کریں۔ حصہ ہٹانے کے لیے اس کا عنوان تھپتھپائیں اور "حذف" چنیں',
  'faq_q6'  : 'میں حصوں کو دوبارہ ترتیب کیسے دوں؟',
  'faq_a6'  : 'کسی بھی حصے کے عنوان کے پاس ہینڈل (≡) دبائیں اور اسے مطلوبہ جگہ پر گھسیٹیں۔ ترتیب خودکار محفوظ ہو جاتی ہے',
  'faq_q7'  : 'میں اپنا CV بطور PDF کیسے برآمد کروں؟',
  'faq_a7'  : 'اپنا CV کھولیں اور اوپر دائیں جانب شیئر آئیکن تھپتھپائیں۔ "PDF برآمد کریں" چنیں، پھر آلے میں محفوظ کریں، ای میل یا WhatsApp سے شیئر کریں یا براہ راست جاب بورڈ پر اپ لوڈ کریں',
  'faq_q8'  : 'کون سے فائل فارمیٹس سپورٹ ہیں؟',
  'faq_a8'  : 'فی الحال ایپ آپ کا CV اعلی معیار کے PDF کے طور پر برآمد کرتی ہے۔ مستقبل کی اپڈیٹس میں اضافی فارمیٹس شامل ہو سکتے ہیں',
  'faq_q9'  : 'میرا CV ڈیٹا کہاں محفوظ ہوتا ہے؟',
  'faq_a9'  : 'آپ کا تمام CV ڈیٹا آپ کے آلے پر محفوظ ہوتا ہے۔ ہم آپ کی ذاتی معلومات اپنے سرورز پر اپ لوڈ نہیں کرتے، یعنی آپ کا ڈیٹا نجی رہتا ہے اور آف لائن قابل رسائی ہے',
  'faq_q10' : 'میں اپنا CV ڈیٹا بیک اپ کیسے کروں؟',
  'faq_a10' : 'آپ کے CVs آلے کے معیاری بیک اپ (Android پر Google Drive، iOS پر iCloud) میں شامل ہوتے ہیں۔ آلے کی ترتیبات میں بیک اپ فعال کرنے پر آپ ہر CV کو PDF کے طور پر بھی برآمد کر سکتے ہیں',
  'faq_q11' : 'ایپ سست چل رہی ہے، کیا کروں؟',
  'faq_a11' : 'ایپ بند کر کے دوبارہ کھولیں۔ اگر مسئلہ برقرار رہے تو اپنا آلہ ری اسٹارٹ کریں۔ یقینی بنائیں کہ Play Store / App Store سے تازہ ترین ورژن انسٹال ہے',
  'faq_q12' : 'میرا CV درست برآمد نہیں ہو رہا، کیا کروں؟',
  'faq_a12' : 'یقینی بنائیں کہ آلے میں کافی اسٹوریج موجود ہے۔ CV میں بڑی تصویریں چھوٹی کرنے کی کوشش کریں۔ اگر مسئلہ برقرار رہے تو ہماری سپورٹ ٹیم سے رابطہ کریں',
  'faq_q13' : 'میں محفوظ نہیں کیا — کیا میرا کام ضائع ہو گیا؟',
  'faq_a13' : 'نہیں! ایپ ترمیم کے دوران آپ کی پیشرفت مسلسل محفوظ کرتی رہتی ہے',

  // ─── very_top_header.dart ───────────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'آپ کا پیشہ ورانہ CV، کامل انداز میں',
  'header_tooltip_back'                 : 'واپس',
  'header_tooltip_my_cvs'               : 'میرے CVs',
  'header_tooltip_settings'             : 'ترتیبات',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────────
  'saved_section_title'                 : 'میرے CVs',
  'saved_count_single'                  : '{n} دستاویز',
  'saved_count_plural'                  : '{n} دستاویزات',
  'saved_limit_reached'                 : 'حد پوری ہو گئی',
  'saved_footer_count'                  : '{n} / 30 CVs',
  'saved_filter_all'                    : 'سب',
  'saved_filter_draft'                  : 'مسودہ',
  'saved_filter_complete'               : 'مکمل',
  'saved_status_complete'               : 'مکمل',
  'saved_status_saved'                  : 'محفوظ',
  'saved_status_draft'                  : 'مسودہ',
  'saved_empty_title'                   : 'ابھی کوئی CV نہیں',
  'saved_empty_sub'                     : 'اوپر اپنا پہلا CV بنانا شروع کریں',
  'saved_search_empty_title'            : 'کوئی نتیجہ نہیں',
  'saved_search_empty_sub'              : 'دوسرے الفاظ سے تلاش کریں',

  // ─── customization_panel.dart ───────────────────────────────────────────────
  'custom_color_scheme_title'           : 'رنگ اسکیم',
  'custom_font_settings_title'          : 'فونٹ ترتیبات',
  'custom_font_family_label'            : 'فونٹ',
  'custom_font_size_label'              : 'فونٹ سائز: ',
  'custom_current_template_title'       : 'موجودہ ٹیمپلیٹ',
  'custom_change_template_btn'          : 'ٹیمپلیٹ بدلیں',
  'custom_tpl_modern'                   : 'جدید',
  'custom_tpl_classic'                  : 'کلاسک',
  'custom_tpl_professional'             : 'پیشہ ورانہ',
  'custom_tpl_creative'                 : 'تخلیقی',
  'custom_tpl_minimal'                  : 'سادہ',
  'custom_tpl_modern_desc'              : 'صاف اور عصری ڈیزائن',
  'custom_tpl_classic_desc'             : 'روایتی پیشہ ورانہ لے آؤٹ',
  'custom_tpl_professional_desc'        : 'کاروبار پر مرکوز ٹیمپلیٹ',
  'custom_tpl_creative_desc'            : 'منفرد ڈیزائن سے نمایاں ہوں',
  'custom_tpl_minimal_desc'             : 'سادہ اور خوبصورت انداز',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────────
  'swipe_section_title'                 : 'ٹیمپلیٹ چنیں',
  'swipe_photo_badge'                   : 'تصویر',

  // ─── template_data.dart ─────────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'سب سے مقبول',
  'tpl_nordic_tag'                      : 'صاف',
  'tpl_vibrant_tag'                     : 'تخلیقی',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'اعلی عہدوں کے لیے نمایاں اور با اختیار',
  'tpl_nordic_desc'                     : 'صاف اور سادہ وضاحت جو اداروں کو پسند ہے',
  'tpl_vibrant_desc'                    : 'توانائی اور رنگ سے نمایاں ہوں',
  'tpl_tech_dark_desc'                  : 'ڈویلپرز کے لیے ٹرمینل انداز',
  'tpl_luxury_desc'                     : 'سیاہ پس منظر پر سنہری شان',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────────
  'detail_step_template'                : 'ٹیمپلیٹ',
  'detail_step_personal'                : 'ذاتی',
  'detail_step_experience'              : 'تجربہ',
  'detail_step_education'               : 'تعلیم',
  'detail_step_skills'                  : 'مہارتیں',
  'detail_step_additional'              : 'اضافی',
  'detail_step_references'              : 'حوالہ جات',
  'detail_step_customize'               : 'حسب ضرورت',
  'detail_banner_heading'               : 'تقریباً مکمل!',
  'detail_banner_btn'                   : 'جاری رکھیں',
  'detail_banner_completion_label'      : 'تکمیل',
  'detail_stat_created_label'           : 'بنایا',
  'detail_stat_steps_label'             : 'مراحل مکمل',
  'detail_section_template_style'       : 'ٹیمپلیٹ انداز',
  'detail_section_steps'                : 'مراحل',
  'detail_steps_counter'                : '{done} / {total} مکمل',
  'detail_step_sub'                     : 'مرحلہ {n} از {total}',
  'detail_section_activity'             : 'سرگرمی',
  'detail_activity_created'             : 'بنایا',
  'detail_activity_last_edited'         : 'آخری ترمیم',
  'detail_activity_template'            : 'ٹیمپلیٹ',
  'detail_btn_continue_editing'         : 'ترمیم جاری رکھیں',
  'detail_btn_edit_cv'                  : 'CV ترمیم کریں',
  'detail_option_rename'                : 'CV کا نام بدلیں',
  'detail_option_delete'                : 'CV حذف کریں',
  'detail_rename_title'                 : 'CV کا نام بدلیں',
  'detail_rename_hint'                  : 'مثلاً سافٹ ویئر انجینئر CV',
  'detail_rename_error_empty'           : 'نام خالی نہیں ہو سکتا',
  'detail_rename_btn_cancel'            : 'منسوخ',
  'detail_rename_btn_save'              : 'محفوظ کریں',
  'detail_rename_snackbar'              : 'نام بدل کر "{name}" کر دیا گیا',
  'detail_delete_title'                 : 'CV حذف کریں؟',
  'detail_delete_body'                  : 'یہ عمل "{name}" کو مستقل حذف کر دے گا۔ اسے واپس نہیں لایا جا سکتا',
  'detail_delete_btn_cancel'            : 'منسوخ',
  'detail_delete_btn_confirm'           : 'حذف کریں',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────────
  'detail_check_tile_complete'          : 'مکمل',
  'detail_check_tile_incomplete'        : 'ابھی نہیں بھرا',

  // ─── step_template_chooser.dart ─────────────────────────────────────────────
  'chooser_title'                       : 'اپنا ٹیمپلیٹ چنیں',
  'chooser_subtitle'                    : 'دیکھنے کے لیے سوائپ کریں  ·  چننے کے لیے تھپتھپائیں  ·  پیش نظارے کے لیے دبائیں',
  'chooser_card_hold_hint'              : 'پیش نظارے کے لیے دبائیں',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'منتخب',
  'chooser_modal_heading'               : 'اپنے CV کا نام رکھیں',
  'chooser_modal_sub'                   : 'نام رکھیں تاکہ میرے CVs اور تاریخ میں آسانی سے ملے',
  'chooser_modal_field_label'           : 'CV کا نام',
  'chooser_modal_save_btn'              : 'محفوظ کریں اور بنانا شروع کریں',
  'chooser_modal_divider'               : 'یا موجودہ CV جاری رکھیں',
  'chooser_nav_selected_sub'            : 'منتخب ٹیمپلیٹ',
  'chooser_nav_cta'                     : 'محفوظ کریں اور جاری رکھیں',

  // ─── Shared editor strings ───────────────────────────────────────────────────
  'editor_max_entries_reached'          : 'زیادہ سے زیادہ اندراجات پوری ہوئیں',
  'editor_show_hide'                    : 'دکھائیں/چھپائیں',
  'editor_editing_badge'                : 'ترمیم جاری',
  'editor_field_required'               : 'ضروری',
  'editor_tooltip_edit'                 : 'ترمیم',
  'editor_tooltip_delete'               : 'حذف',
  'editor_date_start'                   : 'شروع کی تاریخ *',
  'editor_date_end'                     : 'ختم کی تاریخ *',
  'editor_date_tap_hint'                : 'چننے کے لیے تھپتھپائیں',
  'editor_date_dialog_title'            : 'مہینہ اور سال چنیں',
  'editor_date_confirm'                 : 'تصدیق کریں',
  'editor_panel_hide'                   : 'چھپائیں',
  'editor_panel_show'                   : 'دکھائیں',
  'editor_validator_max_chars'          : 'زیادہ سے زیادہ {n} حروف',

  // ─── editor_screen.dart ─────────────────────────────────────────────────────
  'editor_header_title'                 : 'اپنا CV بنائیں',
  'editor_header_step_sub'              : 'مرحلہ {current} از {total} · {label}',
  'editor_step_template'                : 'ٹیمپلیٹ',
  'editor_step_personal'                : 'ذاتی',
  'editor_step_experience'              : 'تجربہ',
  'editor_step_education'               : 'تعلیم',
  'editor_step_skills'                  : 'مہارتیں',
  'editor_step_additional'              : 'اضافی',
  'editor_step_references'              : 'حوالہ جات',
  'editor_step_customize'               : 'حسب ضرورت',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────────
  'customize_title'                     : 'حسب ضرورت بنائیں',
  'customize_subtitle'                  : 'اپنا CV منفرد بنائیں',
  'customize_smart_layout_btn'          : 'Smart Layout',
  'customize_back_to_top'               : 'اوپر واپس جائیں',
  'customize_done_title'                : 'آپ تیار ہیں!',
  'customize_done_sub'                  : 'نیچے CV پیش نظارہ تھپتھپائیں تاکہ اپنا مکمل CV دیکھیں',
  'customize_preview_btn'               : 'CV پیش نظارہ',

  // ─── customize_color_section.dart ───────────────────────────────────────────
  'customize_color_section_title'       : 'رنگ اسکیم',
  'color_black'                         : 'سیاہ',
  'color_blue'                          : 'نیلا',
  'color_nordic_blue'                   : 'Nordic Blue',
  'color_indigo'                        : 'جامنی نیلا',
  'color_teal'                          : 'فیروزی',
  'color_green'                         : 'سبز',
  'color_purple'                        : 'جامنی',
  'color_orange'                        : 'نارنجی',
  'color_red'                           : 'سرخ',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'سفید',
  'color_white_bg'                      : 'سفید پس منظر',
  'color_maroon'                        : 'گہرا سرخ',
  'color_brutalist_yellow'              : 'Brutalist Yellow',
  'color_neon_blue'                     : 'Neon Blue',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'ہلکا سرمئی',

  // ─── customize_font_section.dart ────────────────────────────────────────────
  'customize_font_family_title'         : 'فونٹ',
  'customize_font_picker_title'         : 'فونٹ چنیں',
  'customize_font_picker_sub'           : 'ہر فونٹ اپنے حروف میں نمونہ دکھاتا ہے',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────────
  'customize_font_size_title'           : 'فونٹ سائز',
  'customize_font_size_label'           : 'حرف سائز',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────────
  'customize_image_size_title'          : 'تصویر سائز',
  'customize_image_size_label'          : 'تصویر سائز',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────────
  'preview_live_label'                  : 'لائیو پیش نظارہ',
  'preview_page_count_singular'         : '1 صفحہ',
  'preview_page_count_plural'           : '{n} صفحات',
  'preview_page_of'                     : 'صفحہ {page} از {total}',
  'preview_live_hint'                   : 'تبدیلیاں فوری نظر آئیں گی',
  'preview_template_unregistered'       : 'customize_preview.dart میں رجسٹرڈ نہیں',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────────
  'preview_bar_preparing'               : 'آپ کا CV تیار ہو رہا ہے…',
  'preview_bar_print'                   : 'پرنٹ',
  'preview_bar_save_pdf'                : 'PDF محفوظ کریں',
  'preview_bar_share'                   : 'شیئر',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────────
  'preview_screen_title'                : 'CV پیش نظارہ',
  'preview_screen_sub'                  : '{n} {unit} · جیسے واقعی چھاپا جائے گا',
  'preview_page_singular'               : 'صفحہ',
  'preview_page_plural'                 : 'صفحات',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'میرا CV',
  'preview_snack_print_failed'          : 'پرنٹ ناکام: {e}',
  'preview_snack_saved'                 : 'CV ڈاؤنلوڈز میں محفوظ ✓',
  'preview_snack_export_failed'         : 'برآمد ناکام: {e}',
  'preview_snack_share_failed'          : 'شیئر ناکام: {e}',
  'preview_template_not_registered'     : 'ٹیمپلیٹ رجسٹرڈ نہیں',

  // ─── template_full_preview_modal.dart ───────────────────────────────────────
  'preview_modal_barrier_label'         : 'پیش نظارہ بند کریں',
  'preview_modal_hint_photo'            : 'پروفائل تصویر کا تعاون کرتا ہے  ·  چننے کے لیے تھپتھپائیں',
  'preview_modal_hint_no_photo'         : 'چننے کے لیے ٹیمپلیٹ تھپتھپائیں',

  // ─── cv_provider.dart ───────────────────────────────────────────────────────
  'cv_default_title'                    : 'میرا CV',
  'time_just_now'                       : 'ابھی',
  'time_minutes_ago'                    : '{n} منٹ پہلے',
  'time_hours_ago'                      : '{n} گھنٹے پہلے',
  'time_yesterday'                      : 'کل',
  'time_days_ago'                       : '{n} دن پہلے',
  'time_one_week_ago'                   : '1 ہفتہ پہلے',
  'time_weeks_ago'                      : '{n} ہفتے پہلے',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────────
  'tpl_tag_elegant'                     : 'خوبصورت',
  'tpl_tag_classic'                     : 'کلاسک',
  'tpl_tag_minimal'                     : 'سادہ',
  'tpl_tag_creative'                    : 'تخلیقی',
  'tpl_tag_bold'                        : 'جرات مند',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────────
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'جامنی سے مرجانی رنگ کا دلکش کارڈ',

  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'سرخ اور کریمی رسالہ انداز',

  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'لیوینڈر سائیڈ بار، نازک کارڈ',

  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'گرڈ، موٹی سرحدیں اور پیلا رنگ',

  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'جنگلی سبز ٹائم لائن کے ساتھ',

  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'گہرا پس منظر اور گول چارٹ',

  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920 کی دہائی کی ہندسی خوبصورتی',

  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'رنگین حلقوں والا تاریک انفوگرافک',

  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'تازہ نارنجی کے ساتھ تاریک سائیڈ بار',

  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'صاف اور سادہ، ہلکے رنگوں میں',

  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'گرم بیج کا خوبصورت انداز',

  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'سیاہ اور سفید کلاسک، واضح تقسیم',

  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'ATS دوستانہ کلاسک لے آؤٹ',

  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'تاریک نارنجی انفوگرافک انداز',

  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'گرڈ پر تکنیکی خاکے',

  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'کلاسک دو کالمی لے آؤٹ',

  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'ہیرے کے نشان والے شاندار عنوانات',

  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'درمیانی عنوان، رنگدار کمپنی کا نام',

  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'بڑا نام، ٹائم لائن اور کامیابیاں',

  // ─── step_personal_info.dart ────────────────────────────────────────────────
  'personal_title'                      : 'ذاتی معلومات',
  'personal_subtitle'                   : 'ملازم دہندہ کو اپنا تعارف کروائیں',
  'personal_profile_counter'            : '{n}/{max} پروفائلز',
  'personal_info_banner'                : 'زیادہ سے زیادہ 5 پروفائلز محفوظ کریں اور ہر CV کے لیے ایک چنیں۔ آپ کا انتخاب ہر CV کے لیے الگ یاد رہے گا',
  'personal_snack_max'                  : 'زیادہ سے زیادہ {n} پروفائلز پوری ہو گئیں',
  'personal_add_btn'                    : 'نئی پروفائل شامل کریں',
  'personal_library_title'              : 'محفوظ پروفائلز',
  'personal_selected_one'               : '1 منتخب',
  'personal_selected_none'              : 'کوئی منتخب نہیں',
  'personal_library_hint'               : 'صرف اس CV کے لیے چنیں۔ دوسرے CVs اپنا انتخاب یاد رکھیں گے',
  'personal_empty_message'              : 'ابھی کوئی پروفائل نہیں',
  'personal_empty_sub'                  : 'اپنی ذاتی معلومات شامل کرنے کے لیے اوپر تھپتھپائیں',
  'personal_nav_next'                   : 'محفوظ کریں اور جاری رکھیں',
  'personal_card_active_badge'          : 'اس CV کے لیے فعال',
  'personal_sheet_title_add'            : 'نئی پروفائل',
  'personal_sheet_title_edit'           : 'پروفائل ترمیم کریں',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Brutalist ٹیمپلیٹ میں چھوٹی اقدار بہترین نظر آتی ہیں (مثلاً صرف شہر کا نام)',
  'personal_section_photo'              : 'پروفائل تصویر',
  'personal_section_basic'              : 'بنیادی معلومات',
  'personal_section_contact'            : 'رابطہ معلومات',
  'personal_section_online'             : 'آن لائن شناخت',
  'personal_section_summary'            : 'پیشہ ورانہ خلاصہ',
  'personal_field_first_name'           : 'نام *',
  'personal_field_last_name'            : 'خاندانی نام',
  'personal_field_job_title'            : 'عہدہ *',
  'personal_field_email'                : 'ای میل *',
  'personal_field_phone'                : 'فون نمبر *',
  'personal_field_location'             : 'مقام',
  'personal_field_location_brut'        : 'مقام (صرف شہر)',
  'personal_field_website'              : 'ویب سائٹ / پورٹ فولیو',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'مثلاً احمد',
  'personal_hint_last_name'             : 'مثلاً خان',
  'personal_hint_job_title'             : 'مثلاً سافٹ ویئر انجینئر',
  'personal_hint_email'                 : 'مثلاً ahmed@example.com',
  'personal_hint_phone'                 : 'مثلاً +92 300 1234567',
  'personal_hint_location'              : 'مثلاً کراچی، پاکستان',
  'personal_hint_location_brut'         : 'مثلاً کراچی',
  'personal_hint_website'               : 'مثلاً github.com/ahmed',
  'personal_hint_website_brut'          : 'مثلاً github.com/ahmed',
  'personal_hint_linkedin'              : 'مثلاً linkedin.com/in/ahmed',
  'personal_hint_linkedin_brut'         : 'مثلاً linkedin.com/in/ahmed',
  'personal_summary_hint_label'         : 'نوٹ — یہ آپ کے CV کے اوپر ظاہر ہوگا',
  'personal_hint_summary'               : 'اپنا پس منظر اور اہداف 2–3 جملوں میں بتائیں...',
  'personal_validator_email'            : 'براہ کرم درست ای میل درج کریں',
  'personal_field_char_limit_tooltip'   : 'حرف کی حد پوری ہو گئی',
  'personal_sheet_btn_save'             : 'پروفائل محفوظ کریں',
  'personal_sheet_btn_update'           : 'تبدیلیاں محفوظ کریں',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────────
  'photo_sheet_title'                   : 'تصویر چنیں',
  'photo_option_gallery'                : 'گیلری سے چنیں',
  'photo_option_camera'                 : 'تصویر لیں',
  'photo_option_reposition'             : 'تصویر دوبارہ رکھیں',
  'photo_option_remove'                 : 'تصویر ہٹائیں',
  'photo_status_added'                  : 'تصویر شامل ✓',
  'photo_status_empty'                  : 'پیشہ ورانہ تصویر شامل کریں',
  'photo_chip_gallery'                  : 'گیلری',
  'photo_chip_camera'                   : 'کیمرہ',
  'photo_chip_reposition'               : 'دوبارہ رکھیں',
  'photo_reposition_title'              : 'تصویر دوبارہ رکھیں',
  'photo_reposition_sub'                : 'پوزیشن درست کرنے کے لیے تصویر گھسیٹیں',
  'photo_reposition_reset'              : 'درمیان میں ری سیٹ کریں',
  'photo_reposition_apply'              : 'لاگو کریں',

  // ─── step_skills.dart ───────────────────────────────────────────────────────
  'skills_title'                        : 'مہارتیں',
  'skills_subtitle'                     : 'اپنی اہم مہارتیں اجاگر کریں',
  'skills_add_btn'                      : 'نئی مہارت شامل کریں',
  'skills_snack_max_icons'              : 'زیادہ سے زیادہ 10 آئیکونز چن سکتے ہیں',
  'skills_snack_max_skills'             : 'زیادہ سے زیادہ 15 مہارتیں پوری ہوئیں',
  'skills_library_title'                : 'محفوظ مہارتیں',
  'skills_library_hint'                 : 'منتخب مہارتیں اس CV میں شامل ہوں گی۔ آپ کا انتخاب خودکار محفوظ ہوگا',
  'skills_nav_next'                     : 'اضافی معلومات پر جائیں',
  'skills_wina_header_icon_bar'         : 'عنوان آئیکون بار',
  'skills_wina_on'                      : 'فعال',
  'skills_wina_off'                     : 'غیر فعال',
  'skills_wina_bar_on_sub'              : 'CV ہیڈر میں رنگین آئیکون دکھائیں',
  'skills_wina_bar_off_sub'             : 'آئیکون چھپائیں — رابطہ معلومات کے لیے زیادہ جگہ',
  'skills_wina_palette_hint'            : 'آئیکون رنگ ترتیب کے مطابق دکھائے جائیں گے',
  'skills_wina_preview_label'           : 'نمونہ',
  'skills_wina_disabled_hint'           : 'CV ہیڈر میں آئیکون چننے کے لیے اوپر فعال کریں',
  'skills_sheet_title_add'              : 'مہارت شامل کریں',
  'skills_sheet_title_edit'             : 'مہارت ترمیم کریں',
  'skills_sheet_field_name'             : 'مہارت کا نام *',
  'skills_sheet_hint_short'             : 'مثلاً Flutter، ڈیزائن',
  'skills_sheet_hint_long'              : 'مثلاً Flutter، پروجیکٹ مینجمنٹ',
  'skills_sheet_validator_max'          : 'زیادہ سے زیادہ {n} حروف',
  'skills_sheet_proficiency'            : 'مہارت کی سطح',
  'skills_sheet_beginner'               : 'ابتدائی',
  'skills_sheet_expert'                 : 'ماہر',
  'skills_sheet_btn_save'               : 'مہارت محفوظ کریں',
  'skills_sheet_btn_update'             : 'مہارت اپڈیٹ کریں',

  // ─── step_personal_reference.dart ───────────────────────────────────────────
  'refs_title'                          : 'ذاتی حوالہ جات',
  'refs_subtitle'                       : 'وہ لوگ جو آپ کی سفارش کر سکتے ہیں',
  'refs_add_btn'                        : 'نیا حوالہ شامل کریں',
  'refs_snack_max_selected'             : 'فی CV زیادہ سے زیادہ 4 حوالہ جات چن سکتے ہیں',
  'refs_snack_max_saved'                : 'زیادہ سے زیادہ 10 محفوظ حوالہ جات پوری ہو گئیں',
  'refs_library_title'                  : 'محفوظ حوالہ جات',
  'refs_library_hint'                   : 'منتخب حوالہ جات اس CV میں شامل ہوں گے، زیادہ سے زیادہ 4 فی CV۔ آپ کا انتخاب خودکار محفوظ ہوگا',
  'refs_nav_next'                       : 'حسب ضرورت پر جائیں',
  'refs_sheet_title_add'                : 'حوالہ شامل کریں',
  'refs_sheet_title_edit'               : 'حوالہ ترمیم کریں',
  'refs_sheet_sub_add'                  : 'وہ شخص جو ملازم دہندہ کو آپ کی سفارش کر سکے',
  'refs_sheet_sub_edit'                 : 'نیچے اس حوالے کی تفصیل اپڈیٹ کریں',
  'refs_sheet_field_name'               : 'پورا نام *',
  'refs_sheet_field_title'              : 'عہدہ *',
  'refs_sheet_field_company'            : 'کمپنی (اختیاری)',
  'refs_sheet_field_email'              : 'ای میل *',
  'refs_sheet_field_phone'              : 'فون نمبر *',
  'refs_sheet_hint_name'                : 'مثلاً احمد خان',
  'refs_sheet_hint_title'               : 'مثلاً انجینئرنگ مینیجر',
  'refs_sheet_hint_company'             : 'مثلاً Acme کمپنی',
  'refs_sheet_hint_email'               : 'مثلاً ahmed@acme.com',
  'refs_sheet_hint_phone'               : 'مثلاً +92 300 1234567',
  'refs_sheet_validator_email'          : 'براہ کرم درست ای میل درج کریں',
  'refs_sheet_btn_save'                 : 'حوالہ محفوظ کریں',
  'refs_sheet_btn_update'               : 'حوالہ اپڈیٹ کریں',

  // ─── step_experience.dart ───────────────────────────────────────────────────
  'exp_title'                           : 'کام کا تجربہ',
  'exp_subtitle'                        : 'اپنی پیشہ ورانہ تاریخ بتائیں',
  'exp_banner_info'                     : 'فی عہدے زیادہ سے زیادہ {n} ذمہ داریاں CV میں ظاہر ہوں گی۔ عموماً 1–2 صفحات کے لیے 3–6 عہدے کافی ہیں',
  'exp_add_btn'                         : 'نیا تجربہ شامل کریں',
  'exp_snack_max_selected'              : 'فی CV زیادہ سے زیادہ 8 تجربات چن سکتے ہیں',
  'exp_snack_max_saved'                 : 'زیادہ سے زیادہ 12 محفوظ تجربات پوری ہو گئیں',
  'exp_library_title'                   : 'محفوظ تجربات',
  'exp_library_hint'                    : 'منتخب اندراجات صرف اس CV میں شامل ہوں گے۔ دوسرے CVs اپنا انتخاب یاد رکھیں گے',
  'exp_nav_next'                        : 'تعلیم پر جائیں',
  'exp_empty_message'                   : 'ابھی کوئی تجربہ نہیں',
  'exp_empty_sub'                       : 'اپنی پہلی پوزیشن شامل کرنے کے لیے اوپر تھپتھپائیں',
  'exp_card_resp_singular'              : 'ذمہ داری',
  'exp_card_resp_plural'                : 'ذمہ داریاں',
  'exp_card_resp_tooltip'               : 'CV میں پہلی 8 ذمہ داریاں دکھائی جائیں گی',
  'exp_sheet_title_add'                 : 'تجربہ شامل کریں',
  'exp_sheet_title_edit'                : 'تجربہ ترمیم کریں',
  'exp_sheet_field_job_title'           : 'عہدہ *',
  'exp_sheet_field_company'             : 'کمپنی *',
  'exp_sheet_field_location'            : 'مقام',
  'exp_sheet_section_responsibilities'  : 'اہم ذمہ داریاں',
  'exp_sheet_resp_hint_info'            : 'زیادہ سے زیادہ 8 بلٹ پوائنٹس · 200 حروف فی پوائنٹ',
  'exp_sheet_resp_label'                : 'ذمہ داری {n}',
  'exp_sheet_resp_hint'                 : 'مثلاً 5 انجینئرز کی ٹیم کی قیادت کی',
  'exp_sheet_resp_add_btn'              : 'ذمہ داری شامل کریں',
  'exp_sheet_resp_max_info'             : 'زیادہ سے زیادہ {n} ذمہ داریاں پوری ہوئیں',
  'exp_sheet_resp_validator_max'        : 'زیادہ سے زیادہ 200 حروف',
  'exp_sheet_hint_job_title'            : 'مثلاً سافٹ ویئر ڈویلپر',
  'exp_sheet_hint_location'             : 'مثلاً کراچی، پاکستان',
  'exp_sheet_btn_save'                  : 'تجربہ محفوظ کریں',
  'exp_sheet_btn_update'                : 'تبدیلیاں محفوظ کریں',
  'exp_date_present'                    : 'موجودہ / ابھی بھی کام کر رہا ہوں',

  // ─── step_education.dart ────────────────────────────────────────────────────
  'edu_title'                           : 'تعلیم',
  'edu_subtitle'                        : 'اپنی علمی بنیاد بتائیں',
  'edu_add_btn'                         : 'نئی تعلیم شامل کریں',
  'edu_snack_max_selected'              : 'فی CV زیادہ سے زیادہ 8 تعلیمی اندراجات چن سکتے ہیں',
  'edu_snack_max_saved'                 : 'زیادہ سے زیادہ 12 محفوظ تعلیمی اندراجات پوری ہو گئیں',
  'edu_library_title'                   : 'محفوظ تعلیم',
  'edu_library_hint'                    : 'منتخب اندراجات اس CV میں شامل ہوں گے۔ آپ کا انتخاب خودکار محفوظ ہوگا',
  'edu_nav_next'                        : 'مہارتوں پر جائیں',
  'edu_empty_message'                   : 'ابھی کوئی تعلیم نہیں',
  'edu_empty_sub'                       : 'اپنی تعلیمی قابلیت شامل کرنے کے لیے اوپر تھپتھپائیں',
  'edu_card_bullet_singular'            : 'بلٹ پوائنٹ',
  'edu_card_bullet_plural'              : 'بلٹ پوائنٹس',
  'edu_sheet_title_add'                 : 'تعلیم شامل کریں',
  'edu_sheet_title_edit'                : 'تعلیم ترمیم کریں',
  'edu_sheet_field_degree'              : 'ڈگری / قابلیت *',
  'edu_sheet_field_institution'         : 'ادارہ *',
  'edu_sheet_section_key_points'        : 'اہم نکات',
  'edu_sheet_key_points_hint_info'      : 'اختیاری · 1 بلٹ پوائنٹ · زیادہ سے زیادہ 100 حروف',
  'edu_sheet_point_label'               : 'نکتہ {n}',
  'edu_sheet_point_add_btn'             : 'بلٹ پوائنٹ شامل کریں',
  'edu_sheet_point_max_info'            : 'زیادہ سے زیادہ {n} بلٹ پوائنٹس پوری ہوئیں',
  'edu_sheet_point_validator_max'       : 'زیادہ سے زیادہ {n} حروف',
  'edu_sheet_hint_degree'               : 'مثلاً بیچلر آف سائنس، کمپیوٹر سائنس',
  'edu_sheet_hint_institution'          : 'مثلاً جامعہ کراچی',
  'edu_sheet_hint_bullet'               : 'مثلاً پہلی پوزیشن',
  'edu_sheet_btn_save'                  : 'تعلیم محفوظ کریں',
  'edu_sheet_btn_update'                : 'تبدیلیاں محفوظ کریں',
  'edu_date_present'                    : 'موجودہ / ابھی زیر تعلیم ہوں',

  // ─── step_additional.dart ───────────────────────────────────────────────────
  'additional_title'                    : 'اضافی معلومات',
  'additional_subtitle'                 : 'سرٹیفکیٹس، زبانیں اور مزید',
  'additional_cert_section_title'       : 'سرٹیفکیٹس',
  'additional_cert_counter'             : '{sel}/{total} منتخب · زیادہ سے زیادہ {max}',
  'additional_cert_hide'                : 'چھپائیں',
  'additional_cert_show'                : 'دکھائیں',
  'additional_cert_add_btn'             : 'شامل کریں',
  'additional_cert_snack_max'           : 'زیادہ سے زیادہ {n} سرٹیفکیٹس پوری ہوئیں',
  'additional_cert_hint'                : 'منتخب اندراجات اس CV میں شامل ہوں گے۔ آپ کا انتخاب خودکار محفوظ ہوگا',
  'additional_cert_empty'               : 'ابھی کوئی سرٹیفکیٹ نہیں',
  'additional_lang_section_title'       : 'زبانیں',
  'additional_lang_add_hint'            : 'مثلاً ہسپانوی',
  'additional_lang_snack_max'           : 'زیادہ سے زیادہ {n} زبانیں پوری ہوئیں',
  'additional_lang_empty'               : 'ابھی کوئی زبان نہیں',
  'additional_hobby_section_title'      : 'مشاغل اور دلچسپیاں',
  'additional_hobby_add_hint'           : 'مثلاً فوٹوگرافی',
  'additional_hobby_snack_max'          : 'زیادہ سے زیادہ {n} مشاغل پوری ہوئیں',
  'additional_hobby_empty'              : 'ابھی کوئی مشغلہ نہیں',
  'additional_section_hint'             : 'منتخب اندراجات اس CV میں شامل ہوں گے۔ آپ کا انتخاب خودکار محفوظ ہوگا',
  'additional_nav_next'                 : 'حوالہ جات پر جائیں',
  'cert_sheet_title_add'                : 'سرٹیفکیٹ شامل کریں',
  'cert_sheet_title_edit'               : 'سرٹیفکیٹ ترمیم کریں',
  'cert_sheet_sub'                      : 'قابلیت، سرٹیفکیٹ یا پیشہ ورانہ اعزاز شامل کریں',
  'cert_sheet_field_name'               : 'سرٹیفکیٹ کا نام *',
  'cert_sheet_field_issued_by'          : 'جاری کرنے والا (اختیاری)',
  'cert_sheet_field_short_desc'         : 'مختصر تفصیل (اختیاری)',
  'cert_sheet_hint_name'                : 'مثلاً AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'مثلاً Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'مثلاً 2023 میں حاصل کیا',
  'cert_sheet_btn_save'                 : 'سرٹیفکیٹ محفوظ کریں',
  'cert_sheet_btn_update'               : 'سرٹیفکیٹ اپڈیٹ کریں',
  'simple_sheet_title_add_language'     : 'زبان شامل کریں',
  'simple_sheet_title_edit_language'    : 'زبان ترمیم کریں',
  'simple_sheet_title_add_hobby'        : 'مشغلہ شامل کریں',
  'simple_sheet_title_edit_hobby'       : 'مشغلہ ترمیم کریں',
  'simple_sheet_btn_save'               : 'محفوظ کریں',
  'simple_sheet_btn_update'             : 'اپڈیٹ کریں',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────────
  'pdf_section_contact'                 : 'رابطہ معلومات',
  'pdf_section_about_me'                : 'میرے بارے میں',
  'pdf_section_summary'                 : 'خلاصہ',
  'pdf_section_summary_short'           : 'خلاصہ',
  'pdf_section_profile'                 : 'پروفائل',
  'pdf_section_experience'              : 'تجربہ',
  'pdf_section_experience_short'        : 'تجربہ',
  'pdf_section_education'               : 'تعلیم',
  'pdf_section_skills'                  : 'مہارتیں',
  'pdf_section_languages'               : 'زبانیں',
  'pdf_label_email'                     : 'ای میل',
  'pdf_label_phone'                     : 'فون',
  'pdf_label_location'                  : 'Localisation',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV کی حد پوری ہو گئی',
  'limit_dialog_body'                   : 'آپ کے پاس زیادہ سے زیادہ 30 CVs ہیں۔ نیا بنانے سے پہلے کوئی پرانا CV حذف کریں',
  'limit_dialog_go_to_my_cvs'           : 'میرے CVs پر جائیں',
  'limit_dialog_cancel'                 : 'منسوخ',
  'refs_count_summary'                  : '{checked}/{maxChecked} منتخب · {saved}/{maxSaved} محفوظ',
  'refs_selected_badge'                 : '{n} منتخب',
  'refs_empty_message'                  : 'ابھی کوئی حوالہ نہیں',
  'refs_empty_sub'                      : 'حوالہ جات شامل کرنے کے لیے اوپر تھپتھپائیں',
};