// lib/language_keys/lang_ms_malay.dart
//
// Malay (Malaysia) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> msMalay = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Tiada bahasa ditemui',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Langkau',
  'onboarding_next'                     : 'Seterusnya',
  'onboarding_get_started'              : 'Mulakan',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Selamat Datang',
  'ob1_title'                           : 'Cipta CV Yang\nMembuka Peluang',
  'ob1_body'                            : 'Tonjolkan diri anda daripada ratusan pemohon. Bina CV profesional yang memenangi pekerjaan dalam beberapa minit — tiada kemahiran reka bentuk diperlukan.',
  'ob1_pill_label'                      : 'Pembina CV Profesional',
  'ob1_chip_templates'                  : '24+ Templat',
  'ob1_chip_pdf'                        : 'Eksport PDF',
  'ob1_chip_free'                       : 'Percuma',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Templat',
  'ob2_title'                           : 'Setiap Industri.\nSetiap Cita-cita.',
  'ob2_body'                            : 'Dari reka letak profesional hingga reka bentuk kreatif yang berani — templat yang menceritakan kisah anda.',
  'ob2_tap_hint'                        : 'Ketuk mana-mana templat untuk pratonton',
  'ob2_tpl_executive'                   : 'Eksekutif',
  'ob2_tpl_vibrant'                     : 'Bersemangat',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Teknologi Gelap',
  'ob2_tpl_luxury'                      : 'Mewah',
  'ob2_tag_corporate'                   : 'Korporat',
  'ob2_tag_creative'                    : 'Kreatif',
  'ob2_tag_minimal'                     : 'Minima',
  'ob2_tag_modern'                      : 'Moden',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Susun Atur Pintar',
  'ob3_title'                           : 'CV Anda.\nDisusun dengan Sempurna.',
  'ob3_body'                            : 'Susun Atur Pintar menyusun semula bahagian anda untuk impak maksimum — meletakkan kandungan terkuat anda di tempat perekrut melihat terlebih dahulu.',
  'ob3_badge_smart_layout'              : 'Susun Atur Pintar',
  'ob3_badge_cv_ready'                  : 'CV Sedia!',
  'ob3_step1_label'                     : 'Pilih Templat',
  'ob3_step1_desc'                      : 'Pilih daripada 24+ reka bentuk menakjubkan.',
  'ob3_step2_label'                     : 'Isi Butiran Anda',
  'ob3_step2_desc'                      : 'Medan berpanduan untuk semua bahagian.',
  'ob3_step3_label'                     : 'Susun Atur Pintar',
  'ob3_step3_desc'                      : 'Satu ketukan menyusun semula CV anda dengan sempurna.',
  'ob3_step4_label'                     : 'Eksport sebagai PDF',
  'ob3_step4_desc'                      : 'PDF berkualiti tinggi siap dihantar.',
  'ob3_section_work'                    : 'Pengalaman Kerja',
  'ob3_section_education'               : 'Pendidikan',
  'ob3_section_skills'                  : 'Kemahiran',
  'ob3_section_references'              : 'Rujukan',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Sedia untuk Bermula',
  'ob4_title'                           : 'Mengapa Calon Terbaik\nMemilih CV Builder',
  'ob4_visual_headline'                 : 'Anda Sudah Bersedia!',
  'ob4_visual_subline'                  : 'Semua yang anda perlukan untuk mendapat pekerjaan.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Templat',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'CV Maksimum',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Eksport',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Peribadi',
  'ob4_hl1_title'                       : 'Peribadi & Selamat',
  'ob4_hl1_sub'                         : 'Data tersimpan di peranti anda.',
  'ob4_hl2_title'                       : 'Simpan Automatik',
  'ob4_hl2_sub'                         : 'Setiap ketukan kekunci disimpan serta-merta.',
  'ob4_hl3_title'                       : 'Sehingga 30 CV',
  'ob4_hl3_sub'                         : 'CV unik untuk setiap peranan.',
  'ob4_hl4_title'                       : 'Kongsi Satu Ketukan',
  'ob4_hl4_sub'                         : 'Hantar PDF tanpa meninggalkan apl.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Tonjolkan diri anda',
  'home_hero_title'                     : 'Cipta CV\nProfesional Anda',
  'home_hero_sub'                       : 'Bina resume yang menakjubkan\ndalam beberapa minit',
  'home_hero_cta'                       : 'Mula Membina',
  'home_premium_soon'                   : 'Naik taraf ke Pro akan datang!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Terbaru',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Terakhir Diedit',
  'history_sort_by_template'            : 'Mengikut Templat',
  'history_sort_sheet_title'            : 'Susun Mengikut',
  'history_sort_alphabetical_full'      : 'Abjad (A–Z)',
  'history_premium_soon'                : 'Naik taraf ke Pro akan datang!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Tetapan',
  'settings_section_preferences'        : 'Keutamaan',
  'settings_section_support'            : 'Sokongan',
  'settings_section_legal'              : 'Undang-undang',
  'settings_section_about'              : 'Mengenai',
  'settings_language_tile_title'        : 'Bahasa',
  'settings_dark_mode_title'            : 'Mod Gelap',
  'settings_dark_mode_on'               : 'Tema gelap diaktifkan',
  'settings_dark_mode_off'              : 'Tema cerah diaktifkan',
  'settings_help_faq_title'             : 'Bantuan & Soalan Lazim',
  'settings_help_faq_sub'               : 'Soalan lazim dijawab',
  'settings_contact_support_title'      : 'Hubungi Sokongan',
  'settings_rate_app_title'             : 'Beri Penilaian Apl',
  'settings_rate_app_sub'               : 'Suka apl ini? Tinggalkan ulasan!',
  'settings_privacy_policy_title'       : 'Dasar Privasi',
  'settings_terms_title'                : 'Terma Perkhidmatan',
  'settings_app_version_title'          : 'Versi Apl',
  'settings_email_error'                : 'Tidak dapat membuka apl e-mel. Sila e-mel cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Pratonton CV',
  'preview_header_sub'                  : 'Sedia untuk dieksport',
  'preview_generating'                  : 'Menjana CV anda...',
  'preview_failed_title'                : 'Pratonton Gagal',
  'preview_failed_error'                : 'Ralat: {error}',
  'preview_go_back'                     : 'Kembali',
  'preview_no_data'                     : 'Tiada data tersedia',
  'preview_btn_print'                   : 'Cetak',
  'preview_btn_download'                : 'Muat Turun & Kongsi',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Bantuan & Soalan Lazim',
  'faq_category_all'                    : 'Semua',
  'faq_empty'                           : 'Tiada keputusan ditemui',
  'faq_contact_headline'                : 'Masih perlukan bantuan?',
  'faq_contact_sub'                     : 'Pasukan kami sedia membantu anda.',
  'faq_contact_btn'                     : 'Hubungi',
  'faq_email_error'                     : 'Tidak dapat membuka apl e-mel. Sila e-mel cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Memulakan',
  'faq_cat_templates'                   : 'Templat',
  'faq_cat_editing'                     : 'Penyuntingan',
  'faq_cat_exporting'                   : 'Pengeksportan',
  'faq_cat_data_privacy'                : 'Data & Privasi',
  'faq_cat_troubleshooting'             : 'Penyelesaian Masalah',
  'faq_q1'  : 'Bagaimana saya membuat CV pertama saya?',
  'faq_a1'  : 'Ketuk butang "+" pada skrin utama untuk memulakan CV baru. Pilih templat yang sesuai dengan gaya anda, kemudian isi maklumat peribadi, pengalaman kerja, pendidikan, dan kemahiran langkah demi langkah. Kemajuan anda disimpan secara automatik.',
  'faq_q2'  : 'Bolehkah saya membuat lebih daripada satu CV?',
  'faq_a2'  : 'Ya! Anda boleh membuat beberapa CV untuk peranan atau industri yang berbeza. Setiap CV disimpan secara berasingan, jadi anda boleh menyesuaikannya untuk permohonan kerja tertentu.',
  'faq_q3'  : 'Bagaimana saya menukar templat CV saya?',
  'faq_a3'  : 'Buka CV anda, ketuk ikon templat di bahagian atas skrin, dan layari templat yang tersedia. Ketuk mana-mana templat untuk mempratonton dengan kandungan sedia ada anda. Sahkan untuk menggunakannya.',
  'faq_q4'  : 'Adakah terdapat templat percuma dan premium?',
  'faq_a4'  : 'Ya. Pilihan templat profesional tersedia secara percuma. Templat premium dengan reka bentuk dan palet warna lanjutan tersedia melalui pembelian sekali atau langganan.',
  'faq_q5'  : 'Bagaimana saya menambah atau mengalih keluar bahagian?',
  'faq_a5'  : 'Dalam editor CV, tatal ke bahagian bawah skrin dan ketuk "Tambah Bahagian" untuk menyertakan tambahan seperti Bahasa, Pensijilan, atau Kerja Sukarela. Untuk mengalih keluar bahagian, ketuk pengepala bahagian dan pilih "Alih Keluar."',
  'faq_q6'  : 'Bagaimana saya menyusun semula bahagian?',
  'faq_a6'  : 'Tekan lama pemegang seret (≡) di sebelah mana-mana pengepala bahagian dan seret ke kedudukan pilihan anda. Perubahan disimpan secara automatik.',
  'faq_q7'  : 'Bagaimana saya mengeksport CV saya sebagai PDF?',
  'faq_a7'  : 'Buka CV anda dan ketuk butang eksport (ikon kongsi) di penjuru kanan atas. Pilih "Eksport sebagai PDF." Anda kemudian boleh menyimpannya ke peranti anda, berkongsi melalui e-mel, WhatsApp, atau memuat naiknya terus ke papan kerja.',
  'faq_q8'  : 'Format fail apa yang disokong?',
  'faq_a8'  : 'Pada masa ini Apl menyokong pengeksportan CV anda sebagai PDF berkualiti tinggi. Format tambahan mungkin ditambah dalam kemas kini akan datang.',
  'faq_q9'  : 'Di mana data CV saya disimpan?',
  'faq_a9'  : 'Semua data CV anda disimpan secara setempat di peranti anda. Kami tidak memuat naik maklumat peribadi anda ke pelayan kami. Ini bermakna data anda kekal peribadi dan boleh diakses secara luar talian.',
  'faq_q10' : 'Bagaimana saya membuat sandaran CV saya?',
  'faq_a10' : 'CV anda disertakan dalam sandaran standard peranti anda (sandaran Google Drive di Android, iCloud di iOS) jika anda mengaktifkan sandaran dalam tetapan peranti anda. Anda juga boleh mengeksport CV individu sebagai PDF untuk menyimpan salinan.',
  'faq_q11' : 'Apl berjalan perlahan. Apa yang perlu saya lakukan?',
  'faq_a11' : 'Cuba tutup dan buka semula apl. Jika masalah berterusan, mulakan semula peranti anda. Pastikan anda mempunyai versi terkini apl yang dipasang dari Play Store / App Store.',
  'faq_q12' : 'CV saya tidak dieksport dengan betul. Apa yang perlu saya lakukan?',
  'faq_a12' : 'Pastikan anda mempunyai ruang storan yang mencukupi di peranti anda. Cuba kurangkan imej besar dalam CV anda. Jika masalah berterusan, sila hubungi pasukan sokongan kami.',
  'faq_q13' : 'Saya terlupa menyimpan — adakah kerja saya hilang?',
  'faq_a13' : 'Tidak sama sekali! Apl menyimpan kemajuan anda secara berterusan semasa anda mengedit.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Kerjaya anda, disempurnakan',
  'header_tooltip_back'                 : 'Kembali',
  'header_tooltip_my_cvs'               : 'CV Saya',
  'header_tooltip_settings'             : 'Tetapan',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV Saya',
  'saved_count_single'                  : '{n} dokumen',
  'saved_count_plural'                  : '{n} dokumen',
  'saved_limit_reached'                 : 'Had dicapai',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Semua',
  'saved_filter_draft'                  : 'Draf',
  'saved_filter_complete'               : 'Lengkap',
  'saved_status_complete'               : 'Lengkap',
  'saved_status_saved'                  : 'Disimpan',
  'saved_status_draft'                  : 'Draf',
  'saved_empty_title'                   : 'Tiada CV di sini lagi',
  'saved_empty_sub'                     : 'Mula membina CV pertama anda di atas',
  'saved_search_empty_title'            : 'Tiada keputusan ditemui',
  'saved_search_empty_sub'              : 'Cuba istilah carian yang berbeza',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Skema Warna',
  'custom_font_settings_title'          : 'Tetapan Fon',
  'custom_font_family_label'            : 'Keluarga Fon',
  'custom_font_size_label'              : 'Saiz Fon: ',
  'custom_current_template_title'       : 'Templat Semasa',
  'custom_change_template_btn'          : 'Tukar Templat',
  'custom_tpl_modern'                   : 'Moden',
  'custom_tpl_classic'                  : 'Klasik',
  'custom_tpl_professional'             : 'Profesional',
  'custom_tpl_creative'                 : 'Kreatif',
  'custom_tpl_minimal'                  : 'Minima',
  'custom_tpl_modern_desc'              : 'Reka bentuk bersih dan kontemporari',
  'custom_tpl_classic_desc'             : 'Reka letak profesional tradisional',
  'custom_tpl_professional_desc'        : 'Templat berorientasikan perniagaan',
  'custom_tpl_creative_desc'            : 'Tonjolkan diri dengan reka bentuk unik',
  'custom_tpl_minimal_desc'             : 'Gaya ringkas dan elegan',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Pilih Templat',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Eksekutif',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Bersemangat',
  'tpl_tech_dark_name'                  : 'Teknologi Gelap',
  'tpl_luxury_name'                     : 'Mewah',
  'tpl_executive_tag'                   : 'Paling Popular',
  'tpl_nordic_tag'                      : 'Bersih',
  'tpl_vibrant_tag'                     : 'Kreatif',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elit',
  'tpl_executive_desc'                  : 'Berani & berwibawa untuk peranan kanan',
  'tpl_nordic_desc'                     : 'Kejelasan minima yang dipercayai firma teratas',
  'tpl_vibrant_desc'                    : 'Tonjolkan diri dengan tenaga dan warna',
  'tpl_tech_dark_desc'                  : 'Estetika terminal untuk pembangun',
  'tpl_luxury_desc'                     : 'Prestij beraksen emas pada latar hitam',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Templat',
  'detail_step_personal'                : 'Peribadi',
  'detail_step_experience'              : 'Pengalaman',
  'detail_step_education'               : 'Pendidikan',
  'detail_step_skills'                  : 'Kemahiran',
  'detail_step_additional'              : 'Tambahan',
  'detail_step_references'              : 'Rujukan',
  'detail_step_customize'               : 'Sesuaikan',
  'detail_banner_heading'               : 'Hampir selesai!',
  'detail_banner_btn'                   : 'Teruskan',
  'detail_banner_completion_label'      : 'Penyelesaian',
  'detail_stat_created_label'           : 'Dicipta',
  'detail_stat_steps_label'             : 'Langkah selesai',
  'detail_section_template_style'       : 'Gaya Templat',
  'detail_section_steps'                : 'Langkah',
  'detail_steps_counter'                : '{done} daripada {total} selesai',
  'detail_step_sub'                     : 'Langkah {n} daripada {total}',
  'detail_section_activity'             : 'Aktiviti',
  'detail_activity_created'             : 'Dicipta',
  'detail_activity_last_edited'         : 'Terakhir Diedit',
  'detail_activity_template'            : 'Templat',
  'detail_btn_continue_editing'         : 'Teruskan Penyuntingan',
  'detail_btn_edit_cv'                  : 'Edit CV',
  'detail_option_rename'                : 'Namakan Semula CV',
  'detail_option_delete'                : 'Padam CV',
  'detail_rename_title'                 : 'Namakan Semula CV',
  'detail_rename_hint'                  : 'cth. CV Jurutera Perisian',
  'detail_rename_error_empty'           : 'Nama tidak boleh kosong',
  'detail_rename_btn_cancel'            : 'Batal',
  'detail_rename_btn_save'              : 'Simpan',
  'detail_rename_snackbar'              : 'Dinamakan semula kepada "{name}"',
  'detail_delete_title'                 : 'Padam CV?',
  'detail_delete_body'                  : 'Ini akan memadam "{name}" secara kekal. Tindakan ini tidak boleh dibatalkan.',
  'detail_delete_btn_cancel'            : 'Batal',
  'detail_delete_btn_confirm'           : 'Padam',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Selesai',
  'detail_check_tile_incomplete'        : 'Belum diisi',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Pilih Templat Anda',
  'chooser_subtitle'                    : 'Leret untuk layar  ·  Ketuk untuk pilih  ·  Tahan untuk pratonton',
  'chooser_card_hold_hint'              : 'Tahan untuk pratonton',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Dipilih',
  'chooser_modal_heading'               : 'Namakan CV Anda',
  'chooser_modal_sub'                   : 'Beri nama supaya anda mudah mencarinya dalam CV Saya dan Sejarah.',
  'chooser_modal_field_label'           : 'Nama CV',
  'chooser_modal_save_btn'              : 'Simpan & Mula Membina',
  'chooser_modal_divider'               : 'atau teruskan CV sedia ada',
  'chooser_nav_selected_sub'            : 'Templat dipilih',
  'chooser_nav_cta'                     : 'Simpan & Teruskan',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Had Maksimum Entri Dicapai',
  'editor_show_hide'                    : 'Tunjuk/Sembunyi',
  'editor_editing_badge'                : 'Mengedit',
  'editor_field_required'               : 'Diperlukan',
  'editor_tooltip_edit'                 : 'Edit',
  'editor_tooltip_delete'               : 'Padam',
  'editor_date_start'                   : 'Tarikh Mula *',
  'editor_date_end'                     : 'Tarikh Tamat *',
  'editor_date_tap_hint'                : 'Ketuk untuk pilih',
  'editor_date_dialog_title'            : 'Pilih Bulan & Tahun',
  'editor_date_confirm'                 : 'Sahkan',
  'editor_panel_hide'                   : 'Sembunyi',
  'editor_panel_show'                   : 'Tunjuk',
  'editor_validator_max_chars'          : 'Maks {n} aksara',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Bina CV Anda',
  'editor_header_step_sub'              : 'Langkah {current} daripada {total} · {label}',
  'editor_step_template'                : 'Templat',
  'editor_step_personal'                : 'Peribadi',
  'editor_step_experience'              : 'Pengalaman',
  'editor_step_education'               : 'Pendidikan',
  'editor_step_skills'                  : 'Kemahiran',
  'editor_step_additional'              : 'Tambahan',
  'editor_step_references'              : 'Rujukan',
  'editor_step_customize'               : 'Sesuaikan',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Sesuaikan',
  'customize_subtitle'                  : 'Jadikan CV anda unik milik anda',
  'customize_smart_layout_btn'          : 'Susun Atur Pintar',
  'customize_back_to_top'               : 'Kembali ke Atas',
  'customize_done_title'                : 'Anda sudah bersedia!',
  'customize_done_sub'                  : 'Ketuk Pratonton CV di bawah untuk melihat CV anda yang siap',
  'customize_preview_btn'               : 'Pratonton CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Skema Warna',
  'color_black'                         : 'Hitam',
  'color_blue'                          : 'Biru',
  'color_nordic_blue'                   : 'Biru Nordic',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Teal',
  'color_green'                         : 'Hijau',
  'color_purple'                        : 'Ungu',
  'color_orange'                        : 'Oren',
  'color_red'                           : 'Merah',
  'color_executive_gold'                : 'Emas Eksekutif',
  'color_vibrant_coral'                 : 'Koral Bersemangat',
  'color_white'                         : 'Putih',
  'color_white_bg'                      : 'Latar Putih',
  'color_maroon'                        : 'Merun',
  'color_brutalist_yellow'              : 'Kuning Brutalis',
  'color_neon_blue'                     : 'Biru Neon',
  'color_blueprint_navy'                : 'Biru Cetak Biru',
  'color_light_grey'                    : 'Kelabu Cerah',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Keluarga Fon',
  'customize_font_picker_title'         : 'Pilih Fon',
  'customize_font_picker_sub'           : 'Setiap fon dipratonton dalam huruf sendiri',
  'customize_font_preview_sample'       : 'Rubah perang yang pantas',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Saiz Fon',
  'customize_font_size_label'           : 'Saiz Teks',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Saiz Imej',
  'customize_image_size_label'          : 'Saiz Imej',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Pratonton Langsung',
  'preview_page_count_singular'         : '1 halaman',
  'preview_page_count_plural'           : '{n} halaman',
  'preview_page_of'                     : 'Halaman {page} daripada {total}',
  'preview_live_hint'                   : 'Perubahan digunakan serta-merta',
  'preview_template_unregistered'       : 'Belum didaftarkan dalam customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Menyediakan CV anda…',
  'preview_bar_print'                   : 'Cetak',
  'preview_bar_save_pdf'                : 'Simpan sebagai PDF',
  'preview_bar_share'                   : 'Kongsi',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Pratonton CV',
  'preview_screen_sub'                  : '{n} {unit} · tepat seperti dicetak',
  'preview_page_singular'               : 'halaman',
  'preview_page_plural'                 : 'halaman',
  'preview_pdf_filename'                : 'CV_Saya',
  'preview_share_subject'               : 'CV Saya',
  'preview_snack_print_failed'          : 'Cetakan gagal: {e}',
  'preview_snack_saved'                 : 'CV disimpan ke Muat Turun ✓',
  'preview_snack_export_failed'         : 'Eksport gagal: {e}',
  'preview_snack_share_failed'          : 'Perkongsian gagal: {e}',
  'preview_template_not_registered'     : 'Templat tidak didaftarkan',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Tutup pratonton',
  'preview_modal_hint_photo'            : 'Menyokong foto profil  ·  Ketuk kad untuk pilih',
  'preview_modal_hint_no_photo'         : 'Ketuk kad templat untuk memilihnya',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV Saya',
  'time_just_now'                       : 'Baru sahaja',
  'time_minutes_ago'                    : '{n} minit lalu',
  'time_hours_ago'                      : '{n} jam lalu',
  'time_yesterday'                      : 'Semalam',
  'time_days_ago'                       : '{n} hari lalu',
  'time_one_week_ago'                   : '1 minggu lalu',
  'time_weeks_ago'                      : '{n} minggu lalu',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegan',
  'tpl_tag_classic'                     : 'Klasik',
  'tpl_tag_minimal'                     : 'Minima',
  'tpl_tag_creative'                    : 'Kreatif',
  'tpl_tag_bold'                        : 'Berani',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Kecerunan',
  'tpl_gradient_desc'                   : 'Kad kecerunan teal ke ungu',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Gaya majalah merah & krim',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Lembut',
  'tpl_pastel_soft_desc'                : 'Bar sisi lavender, kad lembut',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalis',
  'tpl_brutalist_desc'                  : 'Grid mentah, sempadan berani & kuning',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Zamrud',
  'tpl_emerald_desc'                    : 'Hijau hutan dengan garis masa',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografik',
  'tpl_infographic_desc'                : 'Kanvas gelap dengan carta cincin',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Kemewahan emas geometri 1920-an',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Gelap',
  'tpl_wina_dark_desc'                  : 'Infografik gelap dengan cincin',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Oren',
  'tpl_rio_orange_desc'                 : 'Bar sisi gelap dengan sentuhan oren',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Musim Panas',
  'tpl_summer_desc'                     : 'Minima bersih, nada kelabu lembut',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Nada beige yang hangat dan elegan',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Klasik hitam & putih yang tegas',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Reka letak klasik mesra ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Gelap',
  'tpl_tony_dark_desc'                  : 'Gaya infografik oren gelap',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fesyen',
  'tpl_fashion_desc'                    : 'Lukisan teknikal pada grid',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arkivis',
  'tpl_archivist_desc'                  : 'Reka letak label dua lajur klasik',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Pengepala berlorek dengan pemimpin berlian',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Pengepala berpusat, syarikat beraksen',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nama berani, titik garis masa & pencapaian',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Maklumat Peribadi',
  'personal_subtitle'                   : 'Beritahu majikan siapa anda',
  'personal_profile_counter'            : '{n}/{max} profil',
  'personal_info_banner'                : 'Simpan sehingga 5 profil dan pilih satu setiap CV. Pilihan anda diingati untuk setiap CV secara berasingan.',
  'personal_snack_max'                  : 'Maksimum {n} profil telah dicapai.',
  'personal_add_btn'                    : 'Tambah Profil Baru',
  'personal_library_title'              : 'Profil Disimpan',
  'personal_selected_one'               : '1 dipilih',
  'personal_selected_none'              : 'tiada dipilih',
  'personal_library_hint'               : 'Ketuk kad untuk memilihnya untuk CV ini sahaja. CV lain mengekalkan pilihan bebas mereka sendiri.',
  'personal_empty_message'              : 'Tiada profil disimpan lagi',
  'personal_empty_sub'                  : 'Ketuk di atas untuk menambah maklumat peribadi anda',
  'personal_nav_next'                   : 'Simpan & Teruskan',
  'personal_card_active_badge'          : 'Aktif untuk CV ini',
  'personal_sheet_title_add'            : 'Profil Baru',
  'personal_sheet_title_edit'           : 'Edit Profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALIS',
  'personal_sheet_brutalist_banner'     : 'Templat Brutalis mempunyai medan kenalan padat. Nilai yang lebih pendek (cth. bandar sahaja) dipaparkan dengan terbaik.',
  'personal_section_photo'              : 'Foto Profil',
  'personal_section_basic'              : 'Butiran Asas',
  'personal_section_contact'            : 'Hubungi',
  'personal_section_online'             : 'Kehadiran Dalam Talian',
  'personal_section_summary'            : 'Ringkasan Profesional',
  'personal_field_first_name'           : 'Nama Pertama *',
  'personal_field_last_name'            : 'Nama Akhir',
  'personal_field_job_title'            : 'Jawatan *',
  'personal_field_email'                : 'Alamat E-mel *',
  'personal_field_phone'                : 'Nombor Telefon *',
  'personal_field_location'             : 'Lokasi',
  'personal_field_location_brut'        : 'Lokasi (bandar sahaja)',
  'personal_field_website'              : 'Laman Web / Portfolio',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'cth. Siti',
  'personal_hint_last_name'             : 'cth. Rahman',
  'personal_hint_job_title'             : 'cth. Jurutera Kanan',
  'personal_hint_email'                 : 'cth. siti@contoh.com',
  'personal_hint_phone'                 : 'cth. +60 12 345 6789',
  'personal_hint_location'              : 'cth. Kuala Lumpur, Malaysia',
  'personal_hint_location_brut'         : 'cth. Kuala Lumpur, MY',
  'personal_hint_website'               : 'cth. github.com/sitirahman',
  'personal_hint_website_brut'          : 'cth. github.com/siti',
  'personal_hint_linkedin'              : 'cth. linkedin.com/in/sitirahman',
  'personal_hint_linkedin_brut'         : 'cth. linkedin.com/in/siti',
  'personal_summary_hint_label'         : 'Ringkaskan — ini muncul di bahagian atas CV anda.',
  'personal_hint_summary'               : 'Ringkasan pendek 2–3 ayat tentang latar belakang dan matlamat anda...',
  'personal_validator_email'            : 'Masukkan e-mel yang sah',
  'personal_field_char_limit_tooltip'   : 'Had aksara dicapai',
  'personal_sheet_btn_save'             : 'Simpan Profil',
  'personal_sheet_btn_update'           : 'Simpan Perubahan',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Pilih Foto',
  'photo_option_gallery'                : 'Pilih dari Galeri',
  'photo_option_camera'                 : 'Ambil Foto',
  'photo_option_reposition'             : 'Ubah Kedudukan Foto',
  'photo_option_remove'                 : 'Alih Keluar Foto',
  'photo_status_added'                  : 'Foto ditambah ✓',
  'photo_status_empty'                  : 'Tambah gambar kepala profesional',
  'photo_chip_gallery'                  : 'Galeri',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Ubah Kedudukan',
  'photo_reposition_title'              : 'Ubah Kedudukan Foto',
  'photo_reposition_sub'                : 'Seret foto untuk melaraskan kedudukan',
  'photo_reposition_reset'              : 'Tetapkan semula ke tengah',
  'photo_reposition_apply'              : 'Guna',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Kemahiran',
  'skills_subtitle'                     : 'Tonjolkan kebolehan utama anda',
  'skills_add_btn'                      : 'Tambah Kemahiran Baru',
  'skills_snack_max_icons'              : 'Maksimum 10 ikon dipilih.',
  'skills_snack_max_skills'             : 'Maksimum 15 kemahiran dicapai.',
  'skills_library_title'                : 'Kemahiran Disimpan',
  'skills_library_hint'                 : 'Kemahiran yang ditanda disertakan dalam CV ini. Pilihan anda disimpan secara automatik.',
  'skills_nav_next'                     : 'Teruskan ke Tambahan',
  'skills_wina_header_icon_bar'         : 'Bar Ikon Pengepala',
  'skills_wina_on'                      : 'HIDUP',
  'skills_wina_off'                     : 'MATI',
  'skills_wina_bar_on_sub'              : 'Bulatan ikon berwarna ditunjukkan dalam pengepala CV.',
  'skills_wina_bar_off_sub'             : 'Baris ikon disembunyikan — lebih ruang untuk maklumat hubungan.',
  'skills_wina_palette_hint'            : 'Ikon muncul sebagai bulatan berwarna dalam susunan palet.',
  'skills_wina_preview_label'           : 'Pratonton',
  'skills_wina_disabled_hint'           : 'Aktifkan bar ikon di atas untuk memilih ikon yang muncul dalam pengepala CV.',
  'skills_sheet_title_add'              : 'Tambah Kemahiran',
  'skills_sheet_title_edit'             : 'Edit Kemahiran',
  'skills_sheet_field_name'             : 'Nama Kemahiran *',
  'skills_sheet_hint_short'             : 'cth. Flutter, Reka Bentuk',
  'skills_sheet_hint_long'              : 'cth. Flutter, Pengurusan Projek',
  'skills_sheet_validator_max'          : 'Maks {n} aksara',
  'skills_sheet_proficiency'            : 'Tahap Kemahiran',
  'skills_sheet_beginner'               : 'Pemula',
  'skills_sheet_expert'                 : 'Pakar',
  'skills_sheet_btn_save'               : 'Simpan Kemahiran',
  'skills_sheet_btn_update'             : 'Kemas Kini Kemahiran',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Rujukan Peribadi',
  'refs_subtitle'                       : 'Orang yang boleh mengesahkan anda secara peribadi',
  'refs_add_btn'                        : 'Tambah Rujukan Peribadi Baru',
  'refs_snack_max_selected'             : 'Maksimum 4 rujukan boleh dipilih untuk CV.',
  'refs_snack_max_saved'                : 'Maksimum 10 rujukan tersimpan dicapai.',
  'refs_library_title'                  : 'Rujukan Disimpan',
  'refs_library_hint'                   : 'Rujukan yang ditanda disertakan dalam CV ini. Maks 4 setiap CV. Pilihan anda disimpan secara automatik.',
  'refs_nav_next'                       : 'Teruskan ke Sesuaikan',
  'refs_sheet_title_add'                : 'Tambah Rujukan Peribadi',
  'refs_sheet_title_edit'               : 'Edit Rujukan Peribadi',
  'refs_sheet_sub_add'                  : 'Seseorang yang boleh mengesyorkan anda kepada majikan.',
  'refs_sheet_sub_edit'                 : 'Kemas kini butiran rujukan ini di bawah.',
  'refs_sheet_field_name'               : 'Nama Penuh *',
  'refs_sheet_field_title'              : 'Jawatan *',
  'refs_sheet_field_company'            : 'Syarikat (pilihan)',
  'refs_sheet_field_email'              : 'Alamat E-mel *',
  'refs_sheet_field_phone'              : 'Nombor Telefon *',
  'refs_sheet_hint_name'                : 'cth. Ahmad bin Ali',
  'refs_sheet_hint_title'               : 'cth. Pengurus Kejuruteraan',
  'refs_sheet_hint_company'             : 'cth. Syarikat Acme',
  'refs_sheet_hint_email'               : 'cth. ahmad@acme.com',
  'refs_sheet_hint_phone'               : 'cth. +60 12 345 6789',
  'refs_sheet_validator_email'          : 'Masukkan alamat e-mel yang sah',
  'refs_sheet_btn_save'                 : 'Simpan Rujukan Peribadi',
  'refs_sheet_btn_update'               : 'Kemas Kini Rujukan Peribadi',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Pengalaman Kerja',
  'exp_subtitle'                        : 'Tambah sejarah kerja anda',
  'exp_banner_info'                     : 'Sehingga {n} tanggungjawab setiap peranan akan muncul dalam CV. 3–6 peranan biasanya muat dalam 1–2 halaman.',
  'exp_add_btn'                         : 'Tambah Pengalaman Baru',
  'exp_snack_max_selected'              : 'Maksimum 8 pengalaman boleh dipilih untuk CV.',
  'exp_snack_max_saved'                 : 'Maksimum 12 pengalaman tersimpan dicapai.',
  'exp_library_title'                   : 'Pengalaman Disimpan',
  'exp_library_hint'                    : 'Entri yang ditanda disertakan dalam CV ini sahaja. CV lain mengekalkan pilihan bebas mereka sendiri.',
  'exp_nav_next'                        : 'Teruskan ke Pendidikan',
  'exp_empty_message'                   : 'Tiada pengalaman ditambah lagi',
  'exp_empty_sub'                       : 'Ketuk di atas untuk menambah peranan pertama anda',
  'exp_card_resp_singular'              : 'tanggungjawab',
  'exp_card_resp_plural'                : 'tanggungjawab',
  'exp_card_resp_tooltip'               : 'Hanya 8 tanggungjawab pertama akan muncul dalam CV',
  'exp_sheet_title_add'                 : 'Tambah Pengalaman',
  'exp_sheet_title_edit'                : 'Edit Pengalaman',
  'exp_sheet_field_job_title'           : 'Jawatan *',
  'exp_sheet_field_company'             : 'Syarikat *',
  'exp_sheet_field_location'            : 'Lokasi',
  'exp_sheet_section_responsibilities'  : 'Tanggungjawab Utama',
  'exp_sheet_resp_hint_info'            : 'Maks 8 poin · 200 aksara setiap satu',
  'exp_sheet_resp_label'                : 'Tanggungjawab {n}',
  'exp_sheet_resp_hint'                 : 'cth. Mengetuai pasukan 5 jurutera',
  'exp_sheet_resp_add_btn'              : 'Tambah Tanggungjawab',
  'exp_sheet_resp_max_info'             : 'Maksimum {n} tanggungjawab dicapai',
  'exp_sheet_resp_validator_max'        : 'Maks 200 aksara',
  'exp_sheet_hint_job_title'            : 'cth. Pembangun Kanan',
  'exp_sheet_hint_location'             : 'cth. Kuala Lumpur, Malaysia',
  'exp_sheet_btn_save'                  : 'Simpan Pengalaman',
  'exp_sheet_btn_update'                : 'Simpan Perubahan',
  'exp_date_present'                    : 'Sekarang / Peranan Semasa',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Pendidikan',
  'edu_subtitle'                        : 'Tambah latar belakang akademik anda',
  'edu_add_btn'                         : 'Tambah Pendidikan Baru',
  'edu_snack_max_selected'              : 'Maksimum 8 entri pendidikan boleh dipilih untuk CV.',
  'edu_snack_max_saved'                 : 'Maksimum 12 entri pendidikan tersimpan dicapai.',
  'edu_library_title'                   : 'Pendidikan Disimpan',
  'edu_library_hint'                    : 'Entri yang ditanda disertakan dalam CV ini. Pilihan anda disimpan secara automatik.',
  'edu_nav_next'                        : 'Teruskan ke Kemahiran',
  'edu_empty_message'                   : 'Tiada pendidikan ditambah lagi',
  'edu_empty_sub'                       : 'Ketuk di atas untuk menambah kelayakan anda',
  'edu_card_bullet_singular'            : 'poin',
  'edu_card_bullet_plural'              : 'poin',
  'edu_sheet_title_add'                 : 'Tambah Pendidikan',
  'edu_sheet_title_edit'                : 'Edit Pendidikan',
  'edu_sheet_field_degree'              : 'Ijazah / Kelayakan *',
  'edu_sheet_field_institution'         : 'Institusi *',
  'edu_sheet_section_key_points'        : 'Poin Utama',
  'edu_sheet_key_points_hint_info'      : 'Pilihan · 1 poin · maks 100 aksara',
  'edu_sheet_point_label'               : 'Poin {n}',
  'edu_sheet_point_add_btn'             : 'Tambah Poin',
  'edu_sheet_point_max_info'            : 'Maksimum {n} poin dicapai',
  'edu_sheet_point_validator_max'       : 'Maks {n} aksara',
  'edu_sheet_hint_degree'               : 'cth. Sarjana Muda Sains Komputer',
  'edu_sheet_hint_institution'          : 'cth. Universiti Malaya',
  'edu_sheet_hint_bullet'               : 'cth. Kepujian Kelas Pertama',
  'edu_sheet_btn_save'                  : 'Simpan Pendidikan',
  'edu_sheet_btn_update'                : 'Simpan Perubahan',
  'edu_date_present'                    : 'Sekarang / Pengajian Semasa',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Maklumat Tambahan',
  'additional_subtitle'                 : 'Pensijilan, bahasa & lain-lain',
  'additional_cert_section_title'       : 'Pensijilan',
  'additional_cert_counter'             : '{sel}/{total} dipilih · maks {max}',
  'additional_cert_hide'                : 'Sembunyi',
  'additional_cert_show'                : 'Tunjuk',
  'additional_cert_add_btn'             : 'Tambah',
  'additional_cert_snack_max'           : 'Maksimum {n} entri pensijilan dicapai.',
  'additional_cert_hint'                : 'Entri yang ditanda disertakan dalam CV ini. Pilihan anda disimpan secara automatik.',
  'additional_cert_empty'               : 'Tiada pensijilan ditambah lagi',
  'additional_lang_section_title'       : 'Bahasa',
  'additional_lang_add_hint'            : 'cth. Mandarin',
  'additional_lang_snack_max'           : 'Maksimum {n} entri bahasa dicapai.',
  'additional_lang_empty'               : 'Tiada bahasa ditambah lagi',
  'additional_hobby_section_title'      : 'Hobi & Minat',
  'additional_hobby_add_hint'           : 'cth. Fotografi',
  'additional_hobby_snack_max'          : 'Maksimum {n} entri hobi dicapai.',
  'additional_hobby_empty'              : 'Tiada hobi ditambah lagi',
  'additional_section_hint'             : 'Entri yang ditanda disertakan dalam CV ini. Pilihan anda disimpan secara automatik.',
  'additional_nav_next'                 : 'Teruskan ke Perakuan',
  'cert_sheet_title_add'                : 'Tambah Pensijilan',
  'cert_sheet_title_edit'               : 'Edit Pensijilan',
  'cert_sheet_sub'                      : 'Tambah kelayakan, sijil atau kelayakan profesional.',
  'cert_sheet_field_name'               : 'Nama Pensijilan *',
  'cert_sheet_field_issued_by'          : 'Dikeluarkan Oleh (pilihan)',
  'cert_sheet_field_short_desc'         : 'Penerangan Ringkas (pilihan)',
  'cert_sheet_hint_name'                : 'cth. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'cth. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'cth. Dicapai 2024',
  'cert_sheet_btn_save'                 : 'Simpan Pensijilan',
  'cert_sheet_btn_update'               : 'Kemas Kini Pensijilan',
  'simple_sheet_title_add_language'     : 'Tambah Bahasa',
  'simple_sheet_title_edit_language'    : 'Edit Bahasa',
  'simple_sheet_title_add_hobby'        : 'Tambah Hobi',
  'simple_sheet_title_edit_hobby'       : 'Edit Hobi',
  'simple_sheet_btn_save'               : 'Simpan',
  'simple_sheet_btn_update'             : 'Kemas Kini',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Hubungi',
  'pdf_section_about_me'                : 'Tentang Saya',
  'pdf_section_summary'                 : 'Ringkasan',
  'pdf_section_summary_short'           : 'Ringkasan',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Pengalaman',
  'pdf_section_experience_short'        : 'Pengalaman',
  'pdf_section_education'               : 'Pendidikan',
  'pdf_section_skills'                  : 'Kemahiran',
  'pdf_section_languages'               : 'Bahasa',
  'pdf_label_email'                     : 'E-mel',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Lokasi',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Had CV Dicapai',
  'limit_dialog_body'                   : 'Anda telah mencapai maksimum 30 CV. Sila padam CV sedia ada sebelum mencipta yang baharu.',
  'limit_dialog_go_to_my_cvs'           : 'Pergi ke CV Saya',
  'limit_dialog_cancel'                 : 'Batal',
  'refs_count_summary'                  : '{checked}/{maxChecked} dipilih · {saved}/{maxSaved} disimpan',
  'refs_selected_badge'                 : '{n} dipilih',
  'refs_empty_message'                  : 'Tiada rujukan disimpan lagi',
  'refs_empty_sub'                      : 'Ketik di atas untuk menambah rujukan peribadi',
};