// lib/language_keys/lang_vi_vietnamese.dart
//
// Vietnamese (Tiếng Việt) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> viVietnamese = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Không tìm thấy ngôn ngữ',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Bỏ qua',
  'onboarding_next'                     : 'Tiếp theo',
  'onboarding_get_started'              : 'Bắt đầu',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Chào mừng',
  'ob1_title'                           : 'Tạo CV Mở Ra\nCơ Hội Mới',
  'ob1_body'                            : 'Nổi bật giữa hàng trăm ứng viên. Tạo CV chuyên nghiệp giúp bạn có được việc làm trong vài phút — không cần kỹ năng thiết kế.',
  'ob1_pill_label'                      : 'Công Cụ Tạo CV Chuyên Nghiệp',
  'ob1_chip_templates'                  : '24+ Mẫu',
  'ob1_chip_pdf'                        : 'Xuất PDF',
  'ob1_chip_free'                       : 'Miễn Phí',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Mẫu CV',
  'ob2_title'                           : 'Mọi Ngành Nghề.\nMọi Khát Vọng.',
  'ob2_body'                            : 'Từ bố cục chuyên nghiệp đến thiết kế sáng tạo ấn tượng — một mẫu CV kể câu chuyện của bạn.',
  'ob2_tap_hint'                        : 'Nhấn vào mẫu bất kỳ để xem trước',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Doanh nghiệp',
  'ob2_tag_creative'                    : 'Sáng tạo',
  'ob2_tag_minimal'                     : 'Tối giản',
  'ob2_tag_modern'                      : 'Hiện đại',
  'ob2_tag_premium'                     : 'Cao cấp',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Bố Cục Thông Minh',
  'ob3_title'                           : 'CV Của Bạn.\nĐược Sắp Xếp Hoàn Hảo.',
  'ob3_body'                            : 'Smart Layout sắp xếp lại các mục để tạo ấn tượng tối đa — đặt nội dung mạnh nhất của bạn vào nơi nhà tuyển dụng nhìn đầu tiên.',
  'ob3_badge_smart_layout'              : 'Smart Layout',
  'ob3_badge_cv_ready'                  : 'CV Sẵn Sàng!',
  'ob3_step1_label'                     : 'Chọn Mẫu',
  'ob3_step1_desc'                      : 'Chọn từ 24+ thiết kế ấn tượng.',
  'ob3_step2_label'                     : 'Điền Thông Tin',
  'ob3_step2_desc'                      : 'Các trường có hướng dẫn cho tất cả các mục.',
  'ob3_step3_label'                     : 'Bố Cục Thông Minh',
  'ob3_step3_desc'                      : 'Một chạm sắp xếp CV hoàn hảo.',
  'ob3_step4_label'                     : 'Xuất PDF',
  'ob3_step4_desc'                      : 'PDF sắc nét sẵn sàng gửi đi.',
  'ob3_section_work'                    : 'Kinh Nghiệm Làm Việc',
  'ob3_section_education'               : 'Học Vấn',
  'ob3_section_skills'                  : 'Kỹ Năng',
  'ob3_section_references'              : 'Người Tham Chiếu',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Sẵn Sàng',
  'ob4_title'                           : 'Tại Sao Ứng Viên Hàng Đầu\nChọn CV Builder',
  'ob4_visual_headline'                 : 'Bạn Đã Sẵn Sàng!',
  'ob4_visual_subline'                  : 'Mọi thứ bạn cần để có được việc làm.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Mẫu CV',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'CV Tối Đa',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Xuất File',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Riêng Tư',
  'ob4_hl1_title'                       : 'Riêng Tư & Bảo Mật',
  'ob4_hl1_sub'                         : 'Dữ liệu lưu trữ trên thiết bị của bạn.',
  'ob4_hl2_title'                       : 'Tự Động Lưu',
  'ob4_hl2_sub'                         : 'Mỗi lần gõ được lưu ngay lập tức.',
  'ob4_hl3_title'                       : 'Tối Đa 30 CV',
  'ob4_hl3_sub'                         : 'CV riêng biệt cho từng vị trí.',
  'ob4_hl4_title'                       : 'Chia Sẻ Một Chạm',
  'ob4_hl4_sub'                         : 'Gửi PDF mà không cần rời ứng dụng.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Nổi bật giữa đám đông',
  'home_hero_title'                     : 'Tạo CV\nChuyên Nghiệp Của Bạn',
  'home_hero_sub'                       : 'Xây dựng hồ sơ ấn tượng\nchỉ trong vài phút',
  'home_hero_cta'                       : 'Bắt Đầu Tạo CV',
  'home_premium_soon'                   : 'Nâng cấp Pro sắp ra mắt!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Mới Nhất',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Chỉnh Sửa Gần Đây',
  'history_sort_by_template'            : 'Theo Mẫu',
  'history_sort_sheet_title'            : 'Sắp Xếp Theo',
  'history_sort_alphabetical_full'      : 'Theo Bảng Chữ Cái (A–Z)',
  'history_premium_soon'                : 'Nâng cấp Pro sắp ra mắt!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Cài Đặt',
  'settings_section_preferences'        : 'Tuỳ Chọn',
  'settings_section_support'            : 'Hỗ Trợ',
  'settings_section_legal'              : 'Pháp Lý',
  'settings_section_about'              : 'Giới Thiệu',
  'settings_language_tile_title'        : 'Ngôn Ngữ',
  'settings_dark_mode_title'            : 'Chế Độ Tối',
  'settings_dark_mode_on'               : 'Đang dùng giao diện tối',
  'settings_dark_mode_off'              : 'Đang dùng giao diện sáng',
  'settings_help_faq_title'             : 'Trợ Giúp & FAQ',
  'settings_help_faq_sub'               : 'Giải đáp các câu hỏi thường gặp',
  'settings_contact_support_title'      : 'Liên Hệ Hỗ Trợ',
  'settings_rate_app_title'             : 'Đánh Giá Ứng Dụng',
  'settings_rate_app_sub'               : 'Thích ứng dụng? Để lại đánh giá nhé!',
  'settings_privacy_policy_title'       : 'Chính Sách Bảo Mật',
  'settings_terms_title'                : 'Điều Khoản Dịch Vụ',
  'settings_app_version_title'          : 'Phiên Bản Ứng Dụng',
  'settings_email_error'                : 'Không thể mở ứng dụng email. Vui lòng gửi email đến cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Xem Trước CV',
  'preview_header_sub'                  : 'Sẵn sàng xuất file',
  'preview_generating'                  : 'Đang tạo CV của bạn...',
  'preview_failed_title'                : 'Xem Trước Thất Bại',
  'preview_failed_error'                : 'Lỗi: {error}',
  'preview_go_back'                     : 'Quay Lại',
  'preview_no_data'                     : 'Không có dữ liệu',
  'preview_btn_print'                   : 'In',
  'preview_btn_download'                : 'Tải Xuống & Chia Sẻ',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Trợ Giúp & FAQ',
  'faq_category_all'                    : 'Tất Cả',
  'faq_empty'                           : 'Không tìm thấy kết quả',
  'faq_contact_headline'                : 'Vẫn cần trợ giúp?',
  'faq_contact_sub'                     : 'Đội ngũ của chúng tôi luôn sẵn sàng hỗ trợ bạn.',
  'faq_contact_btn'                     : 'Liên Hệ',
  'faq_email_error'                     : 'Không thể mở ứng dụng email. Vui lòng gửi email đến cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Bắt Đầu',
  'faq_cat_templates'                   : 'Mẫu CV',
  'faq_cat_editing'                     : 'Chỉnh Sửa',
  'faq_cat_exporting'                   : 'Xuất File',
  'faq_cat_data_privacy'                : 'Dữ Liệu & Bảo Mật',
  'faq_cat_troubleshooting'             : 'Khắc Phục Sự Cố',
  'faq_q1'  : 'Làm thế nào để tạo CV đầu tiên?',
  'faq_a1'  : 'Nhấn nút "+" trên màn hình chính để bắt đầu CV mới. Chọn mẫu phù hợp với phong cách của bạn, sau đó điền thông tin cá nhân, kinh nghiệm làm việc, học vấn và kỹ năng từng bước. Tiến trình của bạn được lưu tự động.',
  'faq_q2'  : 'Tôi có thể tạo nhiều hơn một CV không?',
  'faq_a2'  : 'Có! Bạn có thể tạo nhiều CV cho các vị trí hoặc ngành nghề khác nhau. Mỗi CV được lưu riêng biệt để bạn có thể tùy chỉnh cho từng đơn xin việc.',
  'faq_q3'  : 'Làm thế nào để thay đổi mẫu CV?',
  'faq_a3'  : 'Mở CV của bạn, nhấn vào biểu tượng mẫu ở đầu màn hình và duyệt qua các mẫu có sẵn. Nhấn vào mẫu bất kỳ để xem trước với nội dung hiện tại. Xác nhận để áp dụng.',
  'faq_q4'  : 'Có mẫu miễn phí và cao cấp không?',
  'faq_a4'  : 'Có. Một số mẫu chuyên nghiệp có sẵn miễn phí. Các mẫu cao cấp với thiết kế nâng cao và bảng màu đặc biệt có thể dùng qua mua một lần hoặc đăng ký.',
  'faq_q5'  : 'Làm thế nào để thêm hoặc xóa các mục?',
  'faq_a5'  : 'Trong trình chỉnh sửa CV, cuộn xuống cuối màn hình và nhấn "Thêm Mục" để bổ sung các phần như Ngôn ngữ, Chứng chỉ hoặc Tình nguyện. Để xóa một mục, nhấn vào tiêu đề mục và chọn "Xóa".',
  'faq_q6'  : 'Làm thế nào để sắp xếp lại các mục?',
  'faq_a6'  : 'Nhấn giữ vào tay cầm kéo (≡) bên cạnh tiêu đề mục và kéo đến vị trí mong muốn. Thay đổi được lưu tự động.',
  'faq_q7'  : 'Làm thế nào để xuất CV dưới dạng PDF?',
  'faq_a7'  : 'Mở CV và nhấn nút xuất (biểu tượng chia sẻ) ở góc trên bên phải. Chọn "Xuất dưới dạng PDF". Bạn có thể lưu vào thiết bị, chia sẻ qua email, WhatsApp hoặc tải trực tiếp lên các trang tuyển dụng.',
  'faq_q8'  : 'Những định dạng file nào được hỗ trợ?',
  'faq_a8'  : 'Hiện tại ứng dụng hỗ trợ xuất CV dưới dạng PDF chất lượng cao. Các định dạng khác có thể được bổ sung trong các bản cập nhật sau.',
  'faq_q9'  : 'Dữ liệu CV của tôi được lưu ở đâu?',
  'faq_a9'  : 'Tất cả dữ liệu CV của bạn được lưu trữ cục bộ trên thiết bị. Chúng tôi không tải thông tin cá nhân của bạn lên máy chủ. Điều này có nghĩa là dữ liệu của bạn luôn riêng tư và có thể truy cập ngoài tuyến.',
  'faq_q10' : 'Làm thế nào để sao lưu CV?',
  'faq_a10' : 'CV của bạn được đưa vào bản sao lưu tiêu chuẩn của thiết bị (Google Drive trên Android, iCloud trên iOS) nếu bạn đã bật sao lưu trong cài đặt thiết bị. Bạn cũng có thể xuất từng CV dưới dạng PDF để lưu bản sao.',
  'faq_q11' : 'Ứng dụng chạy chậm. Tôi phải làm gì?',
  'faq_a11' : 'Thử đóng và mở lại ứng dụng. Nếu sự cố vẫn tiếp diễn, hãy khởi động lại thiết bị. Đảm bảo bạn đã cài đặt phiên bản mới nhất từ Play Store / App Store.',
  'faq_q12' : 'CV của tôi không xuất được. Tôi phải làm gì?',
  'faq_a12' : 'Đảm bảo thiết bị có đủ dung lượng lưu trữ. Thử giảm kích thước ảnh lớn trong CV. Nếu sự cố vẫn tiếp tục, vui lòng liên hệ đội hỗ trợ của chúng tôi.',
  'faq_q13' : 'Tôi quên lưu — công việc của tôi có bị mất không?',
  'faq_a13' : 'Hoàn toàn không! Ứng dụng liên tục lưu tiến trình của bạn trong quá trình chỉnh sửa.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Sự nghiệp của bạn, hoàn hảo hơn',
  'header_tooltip_back'                 : 'Quay Lại',
  'header_tooltip_my_cvs'               : 'CV Của Tôi',
  'header_tooltip_settings'             : 'Cài Đặt',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV Của Tôi',
  'saved_count_single'                  : '{n} tài liệu',
  'saved_count_plural'                  : '{n} tài liệu',
  'saved_limit_reached'                 : 'Đã đạt giới hạn',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Tất Cả',
  'saved_filter_draft'                  : 'Bản Nháp',
  'saved_filter_complete'               : 'Hoàn Chỉnh',
  'saved_status_complete'               : 'Hoàn Chỉnh',
  'saved_status_saved'                  : 'Đã Lưu',
  'saved_status_draft'                  : 'Bản Nháp',
  'saved_empty_title'                   : 'Chưa có CV nào',
  'saved_empty_sub'                     : 'Bắt đầu tạo CV đầu tiên của bạn ở trên',
  'saved_search_empty_title'            : 'Không tìm thấy kết quả',
  'saved_search_empty_sub'              : 'Thử từ khoá tìm kiếm khác',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Bảng Màu',
  'custom_font_settings_title'          : 'Cài Đặt Phông Chữ',
  'custom_font_family_label'            : 'Họ Phông Chữ',
  'custom_font_size_label'              : 'Cỡ Chữ: ',
  'custom_current_template_title'       : 'Mẫu Hiện Tại',
  'custom_change_template_btn'          : 'Đổi Mẫu',
  'custom_tpl_modern'                   : 'Hiện Đại',
  'custom_tpl_classic'                  : 'Cổ Điển',
  'custom_tpl_professional'             : 'Chuyên Nghiệp',
  'custom_tpl_creative'                 : 'Sáng Tạo',
  'custom_tpl_minimal'                  : 'Tối Giản',
  'custom_tpl_modern_desc'              : 'Thiết kế sạch sẽ và hiện đại',
  'custom_tpl_classic_desc'             : 'Bố cục chuyên nghiệp truyền thống',
  'custom_tpl_professional_desc'        : 'Mẫu tập trung vào kinh doanh',
  'custom_tpl_creative_desc'            : 'Nổi bật với thiết kế độc đáo sáng tạo',
  'custom_tpl_minimal_desc'             : 'Phong cách đơn giản và thanh lịch',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Chọn Mẫu CV',
  'swipe_photo_badge'                   : 'Ảnh',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Phổ Biến Nhất',
  'tpl_nordic_tag'                      : 'Sạch Sẽ',
  'tpl_vibrant_tag'                     : 'Sáng Tạo',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Mạnh mẽ và uy quyền cho vị trí cấp cao',
  'tpl_nordic_desc'                     : 'Rõ ràng tối giản được các công ty hàng đầu tin dùng',
  'tpl_vibrant_desc'                    : 'Nổi bật với năng lượng và màu sắc',
  'tpl_tech_dark_desc'                  : 'Phong cách terminal dành cho lập trình viên',
  'tpl_luxury_desc'                     : 'Đồng cấp viền vàng trên nền đen',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Mẫu CV',
  'detail_step_personal'                : 'Cá Nhân',
  'detail_step_experience'              : 'Kinh Nghiệm',
  'detail_step_education'               : 'Học Vấn',
  'detail_step_skills'                  : 'Kỹ Năng',
  'detail_step_additional'              : 'Bổ Sung',
  'detail_step_references'              : 'Người Tham Chiếu',
  'detail_step_customize'               : 'Tuỳ Chỉnh',
  'detail_banner_heading'               : 'Gần xong rồi!',
  'detail_banner_btn'                   : 'Tiếp Tục',
  'detail_banner_completion_label'      : 'Hoàn Thành',
  'detail_stat_created_label'           : 'Ngày Tạo',
  'detail_stat_steps_label'             : 'Bước đã làm',
  'detail_section_template_style'       : 'Phong Cách Mẫu',
  'detail_section_steps'                : 'Các Bước',
  'detail_steps_counter'                : '{done} trong {total} hoàn thành',
  'detail_step_sub'                     : 'Bước {n} trong {total}',
  'detail_section_activity'             : 'Hoạt Động',
  'detail_activity_created'             : 'Ngày Tạo',
  'detail_activity_last_edited'         : 'Chỉnh Sửa Gần Đây',
  'detail_activity_template'            : 'Mẫu CV',
  'detail_btn_continue_editing'         : 'Tiếp Tục Chỉnh Sửa',
  'detail_btn_edit_cv'                  : 'Chỉnh Sửa CV',
  'detail_option_rename'                : 'Đổi Tên CV',
  'detail_option_delete'                : 'Xóa CV',
  'detail_rename_title'                 : 'Đổi Tên CV',
  'detail_rename_hint'                  : 'VD: CV Kỹ Sư Phần Mềm',
  'detail_rename_error_empty'           : 'Tên không được để trống',
  'detail_rename_btn_cancel'            : 'Hủy',
  'detail_rename_btn_save'              : 'Lưu',
  'detail_rename_snackbar'              : 'Đã đổi tên thành "{name}"',
  'detail_delete_title'                 : 'Xóa CV?',
  'detail_delete_body'                  : 'Thao tác này sẽ xóa vĩnh viễn "{name}". Không thể hoàn tác.',
  'detail_delete_btn_cancel'            : 'Hủy',
  'detail_delete_btn_confirm'           : 'Xóa',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Đã hoàn thành',
  'detail_check_tile_incomplete'        : 'Chưa điền',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Chọn Mẫu CV Của Bạn',
  'chooser_subtitle'                    : 'Vuốt để duyệt  ·  Nhấn để chọn  ·  Giữ để xem trước',
  'chooser_card_hold_hint'              : 'Giữ để xem trước',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Đã Chọn',
  'chooser_modal_heading'               : 'Đặt Tên CV',
  'chooser_modal_sub'                   : 'Đặt tên để dễ tìm trong CV Của Tôi và Lịch Sử.',
  'chooser_modal_field_label'           : 'Tên CV',
  'chooser_modal_save_btn'              : 'Lưu & Bắt Đầu Tạo',
  'chooser_modal_divider'               : 'hoặc tiếp tục CV hiện có',
  'chooser_nav_selected_sub'            : 'Mẫu đã chọn',
  'chooser_nav_cta'                     : 'Lưu & Tiếp Tục',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Đã Đạt Số Lượng Tối Đa',
  'editor_show_hide'                    : 'Hiện/Ẩn',
  'editor_editing_badge'                : 'Đang Chỉnh Sửa',
  'editor_field_required'               : 'Bắt buộc',
  'editor_tooltip_edit'                 : 'Chỉnh Sửa',
  'editor_tooltip_delete'               : 'Xóa',
  'editor_date_start'                   : 'Ngày Bắt Đầu *',
  'editor_date_end'                     : 'Ngày Kết Thúc *',
  'editor_date_tap_hint'                : 'Nhấn để chọn',
  'editor_date_dialog_title'            : 'Chọn Tháng & Năm',
  'editor_date_confirm'                 : 'Xác Nhận',
  'editor_panel_hide'                   : 'Ẩn',
  'editor_panel_show'                   : 'Hiện',
  'editor_validator_max_chars'          : 'Tối đa {n} ký tự',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Tạo CV Của Bạn',
  'editor_header_step_sub'              : 'Bước {current} trong {total} · {label}',
  'editor_step_template'                : 'Mẫu CV',
  'editor_step_personal'                : 'Cá Nhân',
  'editor_step_experience'              : 'Kinh Nghiệm',
  'editor_step_education'               : 'Học Vấn',
  'editor_step_skills'                  : 'Kỹ Năng',
  'editor_step_additional'              : 'Bổ Sung',
  'editor_step_references'              : 'Người Tham Chiếu',
  'editor_step_customize'               : 'Tuỳ Chỉnh',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Tuỳ Chỉnh',
  'customize_subtitle'                  : 'Làm cho CV của bạn thật độc đáo',
  'customize_smart_layout_btn'          : 'Bố Cục Thông Minh',
  'customize_back_to_top'               : 'Lên Đầu Trang',
  'customize_done_title'                : 'Bạn đã sẵn sàng!',
  'customize_done_sub'                  : 'Nhấn Xem Trước CV bên dưới để xem CV hoàn chỉnh',
  'customize_preview_btn'               : 'Xem Trước CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Bảng Màu',
  'color_black'                         : 'Đen',
  'color_blue'                          : 'Xanh Dương',
  'color_nordic_blue'                   : 'Nordic Blue',
  'color_indigo'                        : 'Chàm',
  'color_teal'                          : 'Xanh Ngọc',
  'color_green'                         : 'Xanh Lá',
  'color_purple'                        : 'Tím',
  'color_orange'                        : 'Cam',
  'color_red'                           : 'Đỏ',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'Trắng',
  'color_white_bg'                      : 'Nền Trắng',
  'color_maroon'                        : 'Đỏ Sẫm',
  'color_brutalist_yellow'              : 'Brutalist Yellow',
  'color_neon_blue'                     : 'Neon Blue',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'Xám Nhạt',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Họ Phông Chữ',
  'customize_font_picker_title'         : 'Chọn Phông Chữ',
  'customize_font_picker_sub'           : 'Mỗi phông chữ hiển thị theo kiểu riêng',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Cỡ Chữ',
  'customize_font_size_label'           : 'Kích Thước Chữ',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Kích Thước Ảnh',
  'customize_image_size_label'          : 'Kích Thước Ảnh',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Xem Trước Trực Tiếp',
  'preview_page_count_singular'         : '1 trang',
  'preview_page_count_plural'           : '{n} trang',
  'preview_page_of'                     : 'Trang {page} trong {total}',
  'preview_live_hint'                   : 'Thay đổi áp dụng ngay lập tức',
  'preview_template_unregistered'       : 'Chưa đăng ký trong customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Đang chuẩn bị CV của bạn…',
  'preview_bar_print'                   : 'In',
  'preview_bar_save_pdf'                : 'Lưu dưới dạng PDF',
  'preview_bar_share'                   : 'Chia Sẻ',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Xem Trước CV',
  'preview_screen_sub'                  : '{n} {unit} · đúng như khi in',
  'preview_page_singular'               : 'trang',
  'preview_page_plural'                 : 'trang',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'CV Của Tôi',
  'preview_snack_print_failed'          : 'In thất bại: {e}',
  'preview_snack_saved'                 : 'CV đã lưu vào Tải Xuống ✓',
  'preview_snack_export_failed'         : 'Xuất file thất bại: {e}',
  'preview_snack_share_failed'          : 'Chia sẻ thất bại: {e}',
  'preview_template_not_registered'     : 'Mẫu chưa được đăng ký',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Đóng xem trước',
  'preview_modal_hint_photo'            : 'Hỗ trợ ảnh hồ sơ  ·  Nhấn thẻ để chọn',
  'preview_modal_hint_no_photo'         : 'Nhấn thẻ mẫu để chọn',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV Của Tôi',
  'time_just_now'                       : 'Vừa xong',
  'time_minutes_ago'                    : '{n} phút trước',
  'time_hours_ago'                      : '{n} giờ trước',
  'time_yesterday'                      : 'Hôm qua',
  'time_days_ago'                       : '{n} ngày trước',
  'time_one_week_ago'                   : '1 tuần trước',
  'time_weeks_ago'                      : '{n} tuần trước',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Thanh Lịch',
  'tpl_tag_classic'                     : 'Cổ Điển',
  'tpl_tag_minimal'                     : 'Tối Giản',
  'tpl_tag_creative'                    : 'Sáng Tạo',
  'tpl_tag_bold'                        : 'Nổi Bật',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Thẻ chuyển màu từ xanh ngọc sang tím',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Phong cách tạp chí đỏ & kem',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'Thanh bên màu oải hương, thẻ mềm mại',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Lưới thô, viền đậm & màu vàng',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Xanh rừng với đường thời gian',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Nền tối với biểu đồ vòng tròn',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Sang trọng vàng hình học thập niên 1920',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Infographic tối với vòng tròn',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Thanh bên tối với điểm nhấn cam',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Tối giản sạch sẽ, tông xám nhẹ',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Tông be ấm áp thanh lịch',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Cổ điển đen trắng tương phản mạnh',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Bố cục cổ điển thân thiện với ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Phong cách infographic cam tối',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Bản vẽ kỹ thuật trên lưới',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Bố cục hai cột nhãn kiểu cổ điển',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Tiêu đề tô bóng với dấu kim cương',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Tiêu đề căn giữa, công ty nổi bật',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Tên đậm, chấm thời gian & thành tích',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Thông Tin Cá Nhân',
  'personal_subtitle'                   : 'Giới thiệu bạn với nhà tuyển dụng',
  'personal_profile_counter'            : '{n}/{max} hồ sơ',
  'personal_info_banner'                : 'Lưu tối đa 5 hồ sơ và chọn một hồ sơ cho mỗi CV. Lựa chọn của bạn được ghi nhớ riêng cho từng CV.',
  'personal_snack_max'                  : 'Đã đạt tối đa {n} hồ sơ.',
  'personal_add_btn'                    : 'Thêm Hồ Sơ Mới',
  'personal_library_title'              : 'Hồ Sơ Đã Lưu',
  'personal_selected_one'               : 'Đã chọn 1',
  'personal_selected_none'              : 'Chưa chọn',
  'personal_library_hint'               : 'Nhấn thẻ để chọn cho CV này. Các CV khác giữ lựa chọn riêng của chúng.',
  'personal_empty_message'              : 'Chưa có hồ sơ nào được lưu',
  'personal_empty_sub'                  : 'Nhấn phía trên để thêm thông tin cá nhân',
  'personal_nav_next'                   : 'Lưu & Tiếp Tục',
  'personal_card_active_badge'          : 'Đang dùng cho CV này',
  'personal_sheet_title_add'            : 'Hồ Sơ Mới',
  'personal_sheet_title_edit'           : 'Chỉnh Sửa Hồ Sơ',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Mẫu Brutalist có các trường liên hệ gọn hơn. Giá trị ngắn hơn (VD: chỉ thành phố) hiển thị tốt nhất.',
  'personal_section_photo'              : 'Ảnh Hồ Sơ',
  'personal_section_basic'              : 'Thông Tin Cơ Bản',
  'personal_section_contact'            : 'Liên Hệ',
  'personal_section_online'             : 'Hiện Diện Trực Tuyến',
  'personal_section_summary'            : 'Tóm Tắt Chuyên Nghiệp',
  'personal_field_first_name'           : 'Tên *',
  'personal_field_last_name'            : 'Họ',
  'personal_field_job_title'            : 'Chức Danh *',
  'personal_field_email'                : 'Địa Chỉ Email *',
  'personal_field_phone'                : 'Số Điện Thoại *',
  'personal_field_location'             : 'Địa Chỉ',
  'personal_field_location_brut'        : 'Địa Chỉ (chỉ thành phố)',
  'personal_field_website'              : 'Website / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'VD: Văn An',
  'personal_hint_last_name'             : 'VD: Nguyễn',
  'personal_hint_job_title'             : 'VD: Kỹ Sư Cấp Cao',
  'personal_hint_email'                 : 'VD: vanan@example.com',
  'personal_hint_phone'                 : 'VD: +84 90 123 4567',
  'personal_hint_location'              : 'VD: Hà Nội, Việt Nam',
  'personal_hint_location_brut'         : 'VD: Hà Nội',
  'personal_hint_website'               : 'VD: github.com/vanan',
  'personal_hint_website_brut'          : 'VD: github.com/van',
  'personal_hint_linkedin'              : 'VD: linkedin.com/in/vanan',
  'personal_hint_linkedin_brut'         : 'VD: linkedin.com/in/van',
  'personal_summary_hint_label'         : 'Giữ ngắn gọn — phần này xuất hiện ở đầu CV của bạn.',
  'personal_hint_summary'               : 'Tóm tắt 2–3 câu về kinh nghiệm và mục tiêu của bạn...',
  'personal_validator_email'            : 'Nhập email hợp lệ',
  'personal_field_char_limit_tooltip'   : 'Đã đạt giới hạn ký tự',
  'personal_sheet_btn_save'             : 'Lưu Hồ Sơ',
  'personal_sheet_btn_update'           : 'Lưu Thay Đổi',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Chọn Ảnh',
  'photo_option_gallery'                : 'Chọn Từ Thư Viện',
  'photo_option_camera'                 : 'Chụp Ảnh',
  'photo_option_reposition'             : 'Đặt Lại Vị Trí Ảnh',
  'photo_option_remove'                 : 'Xóa Ảnh',
  'photo_status_added'                  : 'Đã thêm ảnh ✓',
  'photo_status_empty'                  : 'Thêm ảnh chân dung chuyên nghiệp',
  'photo_chip_gallery'                  : 'Thư Viện',
  'photo_chip_camera'                   : 'Máy Ảnh',
  'photo_chip_reposition'               : 'Đặt Lại',
  'photo_reposition_title'              : 'Đặt Lại Vị Trí Ảnh',
  'photo_reposition_sub'                : 'Kéo ảnh để điều chỉnh vị trí',
  'photo_reposition_reset'              : 'Đặt lại về giữa',
  'photo_reposition_apply'              : 'Áp Dụng',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Kỹ Năng',
  'skills_subtitle'                     : 'Làm nổi bật các năng lực chính của bạn',
  'skills_add_btn'                      : 'Thêm Kỹ Năng Mới',
  'skills_snack_max_icons'              : 'Đã chọn tối đa 10 biểu tượng.',
  'skills_snack_max_skills'             : 'Đã đạt tối đa 15 kỹ năng.',
  'skills_library_title'                : 'Kỹ Năng Đã Lưu',
  'skills_library_hint'                 : 'Kỹ năng được tích sẽ có trong CV này. Lựa chọn được lưu tự động.',
  'skills_nav_next'                     : 'Tiếp Tục đến Bổ Sung',
  'skills_wina_header_icon_bar'         : 'Thanh Biểu Tượng Tiêu Đề',
  'skills_wina_on'                      : 'BẬT',
  'skills_wina_off'                     : 'TẮT',
  'skills_wina_bar_on_sub'              : 'Vòng tròn biểu tượng màu hiển thị trong tiêu đề CV.',
  'skills_wina_bar_off_sub'             : 'Ẩn hàng biểu tượng — thêm chỗ cho thông tin liên hệ.',
  'skills_wina_palette_hint'            : 'Biểu tượng xuất hiện dưới dạng vòng tròn màu theo thứ tự bảng màu.',
  'skills_wina_preview_label'           : 'Xem Trước',
  'skills_wina_disabled_hint'           : 'Bật thanh biểu tượng ở trên để chọn biểu tượng xuất hiện trong tiêu đề CV.',
  'skills_sheet_title_add'              : 'Thêm Kỹ Năng',
  'skills_sheet_title_edit'             : 'Chỉnh Sửa Kỹ Năng',
  'skills_sheet_field_name'             : 'Tên Kỹ Năng *',
  'skills_sheet_hint_short'             : 'VD: Flutter, Thiết Kế',
  'skills_sheet_hint_long'              : 'VD: Flutter, Quản Lý Dự Án',
  'skills_sheet_validator_max'          : 'Tối đa {n} ký tự',
  'skills_sheet_proficiency'            : 'Mức Độ Thành Thạo',
  'skills_sheet_beginner'               : 'Mới Bắt Đầu',
  'skills_sheet_expert'                 : 'Chuyên Gia',
  'skills_sheet_btn_save'               : 'Lưu Kỹ Năng',
  'skills_sheet_btn_update'             : 'Cập Nhật Kỹ Năng',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Người Tham Chiếu Cá Nhân',
  'refs_subtitle'                       : 'Những người có thể đảm bảo cho bạn',
  'refs_add_btn'                        : 'Thêm Người Tham Chiếu Mới',
  'refs_snack_max_selected'             : 'Chỉ chọn tối đa 4 người tham chiếu cho một CV.',
  'refs_snack_max_saved'                : 'Đã đạt tối đa 10 người tham chiếu được lưu.',
  'refs_library_title'                  : 'Người Tham Chiếu Đã Lưu',
  'refs_library_hint'                   : 'Người được tích sẽ có trong CV này. Tối đa 4 người/CV. Lựa chọn được lưu tự động.',
  'refs_nav_next'                       : 'Tiếp Tục đến Tuỳ Chỉnh',
  'refs_sheet_title_add'                : 'Thêm Người Tham Chiếu',
  'refs_sheet_title_edit'               : 'Chỉnh Sửa Người Tham Chiếu',
  'refs_sheet_sub_add'                  : 'Người có thể giới thiệu bạn với nhà tuyển dụng.',
  'refs_sheet_sub_edit'                 : 'Cập nhật thông tin người tham chiếu bên dưới.',
  'refs_sheet_field_name'               : 'Họ Tên *',
  'refs_sheet_field_title'              : 'Chức Danh *',
  'refs_sheet_field_company'            : 'Công Ty (không bắt buộc)',
  'refs_sheet_field_email'              : 'Địa Chỉ Email *',
  'refs_sheet_field_phone'              : 'Số Điện Thoại *',
  'refs_sheet_hint_name'                : 'VD: Trần Văn Bình',
  'refs_sheet_hint_title'               : 'VD: Trưởng Phòng Kỹ Thuật',
  'refs_sheet_hint_company'             : 'VD: Công ty Acme',
  'refs_sheet_hint_email'               : 'VD: binh@acme.com',
  'refs_sheet_hint_phone'               : 'VD: +84 90 123 4567',
  'refs_sheet_validator_email'          : 'Nhập địa chỉ email hợp lệ',
  'refs_sheet_btn_save'                 : 'Lưu Người Tham Chiếu',
  'refs_sheet_btn_update'               : 'Cập Nhật Người Tham Chiếu',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Kinh Nghiệm Làm Việc',
  'exp_subtitle'                        : 'Thêm lịch sử công việc của bạn',
  'exp_banner_info'                     : 'Tối đa {n} trách nhiệm mỗi vị trí sẽ xuất hiện trên CV. 3–6 vị trí thường vừa với 1–2 trang.',
  'exp_add_btn'                         : 'Thêm Kinh Nghiệm Mới',
  'exp_snack_max_selected'              : 'Chỉ chọn tối đa 8 kinh nghiệm cho một CV.',
  'exp_snack_max_saved'                 : 'Đã đạt tối đa 12 kinh nghiệm được lưu.',
  'exp_library_title'                   : 'Kinh Nghiệm Đã Lưu',
  'exp_library_hint'                    : 'Mục được tích sẽ có trong CV này. Các CV khác giữ lựa chọn riêng.',
  'exp_nav_next'                        : 'Tiếp Tục đến Học Vấn',
  'exp_empty_message'                   : 'Chưa có kinh nghiệm nào',
  'exp_empty_sub'                       : 'Nhấn phía trên để thêm vị trí đầu tiên',
  'exp_card_resp_singular'              : 'trách nhiệm',
  'exp_card_resp_plural'                : 'trách nhiệm',
  'exp_card_resp_tooltip'               : 'Chỉ 8 trách nhiệm đầu tiên sẽ xuất hiện trên CV',
  'exp_sheet_title_add'                 : 'Thêm Kinh Nghiệm',
  'exp_sheet_title_edit'                : 'Chỉnh Sửa Kinh Nghiệm',
  'exp_sheet_field_job_title'           : 'Chức Danh *',
  'exp_sheet_field_company'             : 'Công Ty *',
  'exp_sheet_field_location'            : 'Địa Điểm',
  'exp_sheet_section_responsibilities'  : 'Trách Nhiệm Chính',
  'exp_sheet_resp_hint_info'            : 'Tối đa 8 gạch đầu dòng · 200 ký tự mỗi dòng',
  'exp_sheet_resp_label'                : 'Trách Nhiệm {n}',
  'exp_sheet_resp_hint'                 : 'VD: Dẫn dắt nhóm 5 kỹ sư',
  'exp_sheet_resp_add_btn'              : 'Thêm Trách Nhiệm',
  'exp_sheet_resp_max_info'             : 'Đã đạt tối đa {n} trách nhiệm',
  'exp_sheet_resp_validator_max'        : 'Tối đa 200 ký tự',
  'exp_sheet_hint_job_title'            : 'VD: Lập Trình Viên Cấp Cao',
  'exp_sheet_hint_location'             : 'VD: Hà Nội, Việt Nam',
  'exp_sheet_btn_save'                  : 'Lưu Kinh Nghiệm',
  'exp_sheet_btn_update'                : 'Lưu Thay Đổi',
  'exp_date_present'                    : 'Hiện Tại / Vị Trí Hiện Tại',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Học Vấn',
  'edu_subtitle'                        : 'Thêm quá trình học tập của bạn',
  'edu_add_btn'                         : 'Thêm Học Vấn Mới',
  'edu_snack_max_selected'              : 'Chỉ chọn tối đa 8 mục học vấn cho một CV.',
  'edu_snack_max_saved'                 : 'Đã đạt tối đa 12 mục học vấn được lưu.',
  'edu_library_title'                   : 'Học Vấn Đã Lưu',
  'edu_library_hint'                    : 'Mục được tích sẽ có trong CV này. Lựa chọn được lưu tự động.',
  'edu_nav_next'                        : 'Tiếp Tục đến Kỹ Năng',
  'edu_empty_message'                   : 'Chưa có học vấn nào',
  'edu_empty_sub'                       : 'Nhấn phía trên để thêm bằng cấp của bạn',
  'edu_card_bullet_singular'            : 'gạch đầu dòng',
  'edu_card_bullet_plural'              : 'gạch đầu dòng',
  'edu_sheet_title_add'                 : 'Thêm Học Vấn',
  'edu_sheet_title_edit'                : 'Chỉnh Sửa Học Vấn',
  'edu_sheet_field_degree'              : 'Bằng Cấp / Chứng Chỉ *',
  'edu_sheet_field_institution'         : 'Trường / Cơ Sở *',
  'edu_sheet_section_key_points'        : 'Điểm Nổi Bật',
  'edu_sheet_key_points_hint_info'      : 'Không bắt buộc · 1 gạch đầu dòng · Tối đa 100 ký tự',
  'edu_sheet_point_label'               : 'Điểm {n}',
  'edu_sheet_point_add_btn'             : 'Thêm Gạch Đầu Dòng',
  'edu_sheet_point_max_info'            : 'Đã đạt tối đa {n} gạch đầu dòng',
  'edu_sheet_point_validator_max'       : 'Tối đa {n} ký tự',
  'edu_sheet_hint_degree'               : 'VD: Cử nhân Khoa học Máy tính',
  'edu_sheet_hint_institution'          : 'VD: Đại học Bách Khoa Hà Nội',
  'edu_sheet_hint_bullet'               : 'VD: Tốt nghiệp Xuất sắc',
  'edu_sheet_btn_save'                  : 'Lưu Học Vấn',
  'edu_sheet_btn_update'                : 'Lưu Thay Đổi',
  'edu_date_present'                    : 'Hiện Tại / Đang Học',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Thông Tin Bổ Sung',
  'additional_subtitle'                 : 'Chứng chỉ, ngôn ngữ & thêm nữa',
  'additional_cert_section_title'       : 'Chứng Chỉ',
  'additional_cert_counter'             : '{sel}/{total} đã chọn · tối đa {max}',
  'additional_cert_hide'                : 'Ẩn',
  'additional_cert_show'                : 'Hiện',
  'additional_cert_add_btn'             : 'Thêm',
  'additional_cert_snack_max'           : 'Đã đạt tối đa {n} mục chứng chỉ.',
  'additional_cert_hint'                : 'Mục được tích sẽ có trong CV này. Lựa chọn được lưu tự động.',
  'additional_cert_empty'               : 'Chưa có chứng chỉ nào',
  'additional_lang_section_title'       : 'Ngôn Ngữ',
  'additional_lang_add_hint'            : 'VD: Tiếng Anh',
  'additional_lang_snack_max'           : 'Đã đạt tối đa {n} mục ngôn ngữ.',
  'additional_lang_empty'               : 'Chưa có ngôn ngữ nào',
  'additional_hobby_section_title'      : 'Sở Thích & Hoạt Động',
  'additional_hobby_add_hint'           : 'VD: Nhiếp Ảnh',
  'additional_hobby_snack_max'          : 'Đã đạt tối đa {n} mục sở thích.',
  'additional_hobby_empty'              : 'Chưa có sở thích nào',
  'additional_section_hint'             : 'Mục được tích sẽ có trong CV này. Lựa chọn được lưu tự động.',
  'additional_nav_next'                 : 'Tiếp Tục đến Người Tham Chiếu',
  'cert_sheet_title_add'                : 'Thêm Chứng Chỉ',
  'cert_sheet_title_edit'               : 'Chỉnh Sửa Chứng Chỉ',
  'cert_sheet_sub'                      : 'Thêm bằng cấp, chứng chỉ hoặc chứng nhận nghề nghiệp.',
  'cert_sheet_field_name'               : 'Tên Chứng Chỉ *',
  'cert_sheet_field_issued_by'          : 'Cấp Bởi (không bắt buộc)',
  'cert_sheet_field_short_desc'         : 'Mô Tả Ngắn (không bắt buộc)',
  'cert_sheet_hint_name'                : 'VD: AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'VD: Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'VD: Đạt được năm 2024',
  'cert_sheet_btn_save'                 : 'Lưu Chứng Chỉ',
  'cert_sheet_btn_update'               : 'Cập Nhật Chứng Chỉ',
  'simple_sheet_title_add_language'     : 'Thêm Ngôn Ngữ',
  'simple_sheet_title_edit_language'    : 'Chỉnh Sửa Ngôn Ngữ',
  'simple_sheet_title_add_hobby'        : 'Thêm Sở Thích',
  'simple_sheet_title_edit_hobby'       : 'Chỉnh Sửa Sở Thích',
  'simple_sheet_btn_save'               : 'Lưu',
  'simple_sheet_btn_update'             : 'Cập Nhật',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Liên Hệ',
  'pdf_section_about_me'                : 'Về Tôi',
  'pdf_section_summary'                 : 'Tóm Tắt',
  'pdf_section_summary_short'           : 'Tóm Tắt',
  'pdf_section_profile'                 : 'Hồ Sơ',
  'pdf_section_experience'              : 'Kinh Nghiệm',
  'pdf_section_experience_short'        : 'Kinh Nghiệm',
  'pdf_section_education'               : 'Học Vấn',
  'pdf_section_skills'                  : 'Kỹ Năng',
  'pdf_section_languages'               : 'Ngôn Ngữ',
  'pdf_label_email'                     : 'Email',
  'pdf_label_phone'                     : 'Điện Thoại',
  'pdf_label_location'                  : 'Địa Chỉ',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Đã Đạt Giới Hạn CV',
  'limit_dialog_body'                   : 'Bạn đã đạt tối đa 30 CV. Vui lòng xóa một CV hiện có trước khi tạo mới.',
  'limit_dialog_go_to_my_cvs'           : 'Đến CV của tôi',
  'limit_dialog_cancel'                 : 'Hủy',
  'refs_count_summary'                  : '{checked}/{maxChecked} đã chọn · {saved}/{maxSaved} đã lưu',
  'refs_selected_badge'                 : '{n} đã chọn',
  'refs_empty_message'                  : 'Chưa có người giới thiệu nào được lưu',
  'refs_empty_sub'                      : 'Nhấn phía trên để thêm người giới thiệu cá nhân',
};