// lib/language_keys/lang_es_spanish.dart
//
// Spanish (Español) — translation map.
// All keys mirror lang_en_english.dart exactly.

const Map<String, String> esSpanish = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'No se encontraron idiomas',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Omitir',
  'onboarding_next'                     : 'Siguiente',
  'onboarding_get_started'              : 'Comenzar',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Bienvenido',
  'ob1_title'                           : 'Crea un CV que\nAbra Puertas',
  'ob1_body'                            : 'Destácate entre cientos de candidatos. Crea un CV profesional y ganador en minutos — sin necesidad de diseño.',
  'ob1_pill_label'                      : 'Creador de CV Profesional',
  'ob1_chip_templates'                  : '24+ Plantillas',
  'ob1_chip_pdf'                        : 'Exportar PDF',
  'ob1_chip_free'                       : 'Gratis',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Plantillas',
  'ob2_title'                           : 'Cada Sector.\nCada Ambición.',
  'ob2_body'                            : 'Desde diseños ejecutivos hasta creativos — una plantilla que cuenta tu historia.',
  'ob2_tap_hint'                        : 'Toca cualquier plantilla para previsualizar',
  'ob2_tpl_executive'                   : 'Ejecutivo',
  'ob2_tpl_vibrant'                     : 'Vibrante',
  'ob2_tpl_nordic'                      : 'Nórdico',
  'ob2_tpl_tech_dark'                   : 'Tech Oscuro',
  'ob2_tpl_luxury'                      : 'Lujo',
  'ob2_tag_corporate'                   : 'Corporativo',
  'ob2_tag_creative'                    : 'Creativo',
  'ob2_tag_minimal'                     : 'Minimalista',
  'ob2_tag_modern'                      : 'Moderno',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Diseño Inteligente',
  'ob3_title'                           : 'Tu CV.\nPerfectamente Organizado.',
  'ob3_body'                            : 'El Diseño Inteligente reordena tus secciones para el máximo impacto — poniendo tu contenido más fuerte donde los reclutadores miran primero.',
  'ob3_badge_smart_layout'              : 'Diseño Inteligente',
  'ob3_badge_cv_ready'                  : '¡CV Listo!',
  'ob3_step1_label'                     : 'Elige una Plantilla',
  'ob3_step1_desc'                      : 'Escoge entre más de 24 diseños.',
  'ob3_step2_label'                     : 'Completa tus Datos',
  'ob3_step2_desc'                      : 'Campos guiados para todas las secciones.',
  'ob3_step3_label'                     : 'Diseño Inteligente',
  'ob3_step3_desc'                      : 'Un toque reorganiza tu CV perfectamente.',
  'ob3_step4_label'                     : 'Exportar como PDF',
  'ob3_step4_desc'                      : 'PDF perfecto listo para enviar.',
  'ob3_section_work'                    : 'Experiencia Laboral',
  'ob3_section_education'               : 'Educación',
  'ob3_section_skills'                  : 'Habilidades',
  'ob3_section_references'              : 'Referencias',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Listo para Empezar',
  'ob4_title'                           : 'Por qué los Mejores Candidatos\nEligen CV Builder',
  'ob4_visual_headline'                 : '¡Todo Listo!',
  'ob4_visual_subline'                  : 'Todo lo que necesitas para conseguir el trabajo.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Plantillas',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'CVs Máx.',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Exportar',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privado',
  'ob4_hl1_title'                       : 'Privado y Seguro',
  'ob4_hl1_sub'                         : 'Los datos permanecen en tu dispositivo.',
  'ob4_hl2_title'                       : 'Guardado Automático',
  'ob4_hl2_sub'                         : 'Cada tecla guardada al instante.',
  'ob4_hl3_title'                       : 'Hasta 30 CVs',
  'ob4_hl3_sub'                         : 'CV único para cada puesto.',
  'ob4_hl4_title'                       : 'Compartir con Un Toque',
  'ob4_hl4_sub'                         : 'Envía PDF sin salir de la app.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Destácate entre la multitud',
  'home_hero_title'                     : 'Crea tu CV\nProfesional',
  'home_hero_sub'                       : 'Crea un currículum impresionante\nen minutos',
  'home_hero_cta'                       : 'Empezar a Crear',
  'home_premium_soon'                   : '¡Mejora a Pro próximamente!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Más Reciente',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Última Edición',
  'history_sort_by_template'            : 'Por Plantilla',
  'history_sort_sheet_title'            : 'Ordenar Por',
  'history_sort_alphabetical_full'      : 'Alfabético (A–Z)',
  'history_premium_soon'                : '¡Mejora a Pro próximamente!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Configuración',
  'settings_section_preferences'        : 'Preferencias',
  'settings_section_support'            : 'Soporte',
  'settings_section_legal'              : 'Legal',
  'settings_section_about'              : 'Acerca de',
  'settings_language_tile_title'        : 'Idioma',
  'settings_dark_mode_title'            : 'Modo Oscuro',
  'settings_dark_mode_on'               : 'Tema oscuro activado',
  'settings_dark_mode_off'              : 'Tema claro activado',
  'settings_help_faq_title'             : 'Ayuda y Preguntas Frecuentes',
  'settings_help_faq_sub'               : 'Preguntas comunes respondidas',
  'settings_contact_support_title'      : 'Contactar Soporte',
  'settings_rate_app_title'             : 'Calificar la App',
  'settings_rate_app_sub'               : '¿Disfrutas la app? ¡Deja una reseña!',
  'settings_privacy_policy_title'       : 'Política de Privacidad',
  'settings_terms_title'                : 'Términos de Servicio',
  'settings_app_version_title'          : 'Versión de la App',
  'settings_email_error'                : 'No se pudo abrir la app de correo. Por favor envía un email a cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Vista Previa del CV',
  'preview_header_sub'                  : 'Listo para exportar',
  'preview_generating'                  : 'Generando tu CV...',
  'preview_failed_title'                : 'Vista Previa Fallida',
  'preview_failed_error'                : 'Error: {error}',
  'preview_go_back'                     : 'Volver',
  'preview_no_data'                     : 'No hay datos disponibles',
  'preview_btn_print'                   : 'Imprimir',
  'preview_btn_download'                : 'Descargar y Compartir',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Ayuda y Preguntas Frecuentes',
  'faq_category_all'                    : 'Todo',
  'faq_empty'                           : 'No se encontraron resultados',
  'faq_contact_headline'                : '¿Necesitas más ayuda?',
  'faq_contact_sub'                     : 'Nuestro equipo está aquí para ti.',
  'faq_contact_btn'                     : 'Contactar',
  'faq_email_error'                     : 'No se pudo abrir la app de correo. Por favor envía un email a cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Primeros Pasos',
  'faq_cat_templates'                   : 'Plantillas',
  'faq_cat_editing'                     : 'Edición',
  'faq_cat_exporting'                   : 'Exportación',
  'faq_cat_data_privacy'                : 'Datos y Privacidad',
  'faq_cat_troubleshooting'             : 'Solución de Problemas',
  'faq_q1'  : '¿Cómo creo mi primer CV?',
  'faq_a1'  : 'Toca el botón "+" en la pantalla de inicio para comenzar un nuevo CV. Elige una plantilla que se adapte a tu estilo, luego completa tus datos personales, experiencia laboral, educación y habilidades paso a paso. Tu progreso se guarda automáticamente.',
  'faq_q2'  : '¿Puedo crear más de un CV?',
  'faq_a2'  : '¡Sí! Puedes crear múltiples CVs para diferentes puestos o sectores. Cada CV se guarda por separado, para que puedas adaptarlos a solicitudes de empleo específicas.',
  'faq_q3'  : '¿Cómo cambio la plantilla de mi CV?',
  'faq_a3'  : 'Abre tu CV, toca el ícono de plantilla en la parte superior de la pantalla y navega por las plantillas disponibles. Toca cualquier plantilla para previsualizarla con tu contenido existente. Confirma para aplicarla.',
  'faq_q4'  : '¿Hay plantillas gratuitas y premium?',
  'faq_a4'  : 'Sí. Una selección de plantillas profesionales está disponible de forma gratuita. Las plantillas premium con diseños avanzados y paletas de colores están disponibles mediante una compra única o suscripción.',
  'faq_q5'  : '¿Cómo agrego o elimino secciones?',
  'faq_a5'  : 'En el editor de CV, desplázate hasta el final de la pantalla y toca "Agregar Sección" para incluir extras como Idiomas, Certificaciones o Voluntariado. Para eliminar una sección, toca el encabezado de la sección y selecciona "Eliminar".',
  'faq_q6'  : '¿Cómo reordeno las secciones?',
  'faq_a6'  : 'Mantén presionado el control de arrastre (≡) junto al encabezado de cualquier sección y arrástralo a tu posición preferida. Los cambios se guardan automáticamente.',
  'faq_q7'  : '¿Cómo exporto mi CV como PDF?',
  'faq_a7'  : 'Abre tu CV y toca el botón de exportar (ícono de compartir) en la esquina superior derecha. Selecciona "Exportar como PDF". Luego puedes guardarlo en tu dispositivo, compartirlo por correo, WhatsApp o subirlo directamente a portales de empleo.',
  'faq_q8'  : '¿Qué formatos de archivo son compatibles?',
  'faq_a8'  : 'Actualmente la App admite exportar tu CV como PDF de alta calidad. Es posible que se agreguen formatos adicionales en futuras actualizaciones.',
  'faq_q9'  : '¿Dónde se almacenan los datos de mi CV?',
  'faq_a9'  : 'Todos los datos de tu CV se almacenan localmente en tu dispositivo. No subimos tu información personal a nuestros servidores. Esto significa que tus datos permanecen privados y accesibles sin conexión.',
  'faq_q10' : '¿Cómo hago una copia de seguridad de mis CVs?',
  'faq_a10' : 'Tus CVs están incluidos en la copia de seguridad estándar de tu dispositivo (Google Drive en Android, iCloud en iOS) si tienes la copia de seguridad activada en la configuración del dispositivo. También puedes exportar CVs individuales como PDFs para guardar una copia.',
  'faq_q11' : 'La app funciona lentamente. ¿Qué debo hacer?',
  'faq_a11' : 'Intenta cerrar y volver a abrir la app. Si el problema persiste, reinicia tu dispositivo. Asegúrate de tener la última versión de la app instalada desde Play Store / App Store.',
  'faq_q12' : 'Mi CV no se exporta correctamente. ¿Qué debo hacer?',
  'faq_a12' : 'Asegúrate de tener suficiente espacio de almacenamiento en tu dispositivo. Intenta reducir imágenes grandes en tu CV. Si el problema continúa, comunícate con nuestro equipo de soporte.',
  'faq_q13' : 'Olvidé guardar — ¿perdí mi trabajo?',
  'faq_a13' : '¡Para nada! La app guarda tu progreso continuamente mientras editas.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Tu carrera, perfeccionada',
  'header_tooltip_back'                 : 'Atrás',
  'header_tooltip_my_cvs'               : 'Mis CVs',
  'header_tooltip_settings'             : 'Configuración',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Mis CVs',
  'saved_count_single'                  : '{n} documento',
  'saved_count_plural'                  : '{n} documentos',
  'saved_limit_reached'                 : 'Límite alcanzado',
  'saved_footer_count'                  : '{n} / 30 CVs',
  'saved_filter_all'                    : 'Todo',
  'saved_filter_draft'                  : 'Borrador',
  'saved_filter_complete'               : 'Completo',
  'saved_status_complete'               : 'Completo',
  'saved_status_saved'                  : 'Guardado',
  'saved_status_draft'                  : 'Borrador',
  'saved_empty_title'                   : 'Aún no hay CVs aquí',
  'saved_empty_sub'                     : 'Empieza a crear tu primer CV arriba',
  'saved_search_empty_title'            : 'No se encontraron resultados',
  'saved_search_empty_sub'              : 'Prueba con un término de búsqueda diferente',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Esquema de Colores',
  'custom_font_settings_title'          : 'Configuración de Fuente',
  'custom_font_family_label'            : 'Familia de Fuente',
  'custom_font_size_label'              : 'Tamaño de Fuente: ',
  'custom_current_template_title'       : 'Plantilla Actual',
  'custom_change_template_btn'          : 'Cambiar Plantilla',
  'custom_tpl_modern'                   : 'Moderno',
  'custom_tpl_classic'                  : 'Clásico',
  'custom_tpl_professional'             : 'Profesional',
  'custom_tpl_creative'                 : 'Creativo',
  'custom_tpl_minimal'                  : 'Minimalista',
  'custom_tpl_modern_desc'              : 'Diseño limpio y contemporáneo',
  'custom_tpl_classic_desc'             : 'Diseño profesional tradicional',
  'custom_tpl_professional_desc'        : 'Plantilla enfocada en negocios',
  'custom_tpl_creative_desc'            : 'Destácate con un diseño único',
  'custom_tpl_minimal_desc'             : 'Estilo simple y elegante',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Elegir Plantilla',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Ejecutivo',
  'tpl_nordic_name'                     : 'Nórdico',
  'tpl_vibrant_name'                    : 'Vibrante',
  'tpl_tech_dark_name'                  : 'Tech Oscuro',
  'tpl_luxury_name'                     : 'Lujo',
  'tpl_executive_tag'                   : 'Más Popular',
  'tpl_nordic_tag'                      : 'Limpio',
  'tpl_vibrant_tag'                     : 'Creativo',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Audaz y autoritario para puestos senior',
  'tpl_nordic_desc'                     : 'Claridad minimalista de confianza en las mejores empresas',
  'tpl_vibrant_desc'                    : 'Destácate con energía y color',
  'tpl_tech_dark_desc'                  : 'Estética terminal para desarrolladores',
  'tpl_luxury_desc'                     : 'Prestigio con detalles dorados sobre negro',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Plantilla',
  'detail_step_personal'                : 'Personal',
  'detail_step_experience'              : 'Experiencia',
  'detail_step_education'               : 'Educación',
  'detail_step_skills'                  : 'Habilidades',
  'detail_step_additional'              : 'Adicional',
  'detail_step_references'              : 'Referencias',
  'detail_step_customize'               : 'Personalizar',
  'detail_banner_heading'               : '¡Casi listo!',
  'detail_banner_btn'                   : 'Continuar',
  'detail_banner_completion_label'      : 'Completado',
  'detail_stat_created_label'           : 'Creado',
  'detail_stat_steps_label'             : 'Pasos completados',
  'detail_section_template_style'       : 'Estilo de Plantilla',
  'detail_section_steps'                : 'Pasos',
  'detail_steps_counter'                : '{done} de {total} completados',
  'detail_step_sub'                     : 'Paso {n} de {total}',
  'detail_section_activity'             : 'Actividad',
  'detail_activity_created'             : 'Creado',
  'detail_activity_last_edited'         : 'Última Edición',
  'detail_activity_template'            : 'Plantilla',
  'detail_btn_continue_editing'         : 'Continuar Editando',
  'detail_btn_edit_cv'                  : 'Editar CV',
  'detail_option_rename'                : 'Renombrar CV',
  'detail_option_delete'                : 'Eliminar CV',
  'detail_rename_title'                 : 'Renombrar CV',
  'detail_rename_hint'                  : 'ej. CV de Ingeniero de Software',
  'detail_rename_error_empty'           : 'El nombre no puede estar vacío',
  'detail_rename_btn_cancel'            : 'Cancelar',
  'detail_rename_btn_save'              : 'Guardar',
  'detail_rename_snackbar'              : 'Renombrado a "{name}"',
  'detail_delete_title'                 : '¿Eliminar CV?',
  'detail_delete_body'                  : 'Esto eliminará permanentemente "{name}". Esta acción no se puede deshacer.',
  'detail_delete_btn_cancel'            : 'Cancelar',
  'detail_delete_btn_confirm'           : 'Eliminar',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Completado',
  'detail_check_tile_incomplete'        : 'Aún no completado',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Elige tu Plantilla',
  'chooser_subtitle'                    : 'Desliza para explorar  ·  Toca para seleccionar  ·  Mantén para previsualizar',
  'chooser_card_hold_hint'              : 'Mantén para previsualizar',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Seleccionada',
  'chooser_modal_heading'               : 'Nombra tu CV',
  'chooser_modal_sub'                   : 'Dale un nombre para encontrarlo fácilmente en Mis CVs e Historial.',
  'chooser_modal_field_label'           : 'Nombre del CV',
  'chooser_modal_save_btn'              : 'Guardar y Empezar',
  'chooser_modal_divider'               : 'o continúa con un CV existente',
  'chooser_nav_selected_sub'            : 'Plantilla seleccionada',
  'chooser_nav_cta'                     : 'Guardar y Continuar',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Máximo de Entradas Alcanzado',
  'editor_show_hide'                    : 'Mostrar/Ocultar',
  'editor_editing_badge'                : 'Editando',
  'editor_field_required'               : 'Requerido',
  'editor_tooltip_edit'                 : 'Editar',
  'editor_tooltip_delete'               : 'Eliminar',
  'editor_date_start'                   : 'Fecha de Inicio *',
  'editor_date_end'                     : 'Fecha de Fin *',
  'editor_date_tap_hint'                : 'Toca para seleccionar',
  'editor_date_dialog_title'            : 'Selecciona Mes y Año',
  'editor_date_confirm'                 : 'Confirmar',
  'editor_panel_hide'                   : 'Ocultar',
  'editor_panel_show'                   : 'Mostrar',
  'editor_validator_max_chars'          : 'Máx. {n} caracteres',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Crea tu CV',
  'editor_header_step_sub'              : 'Paso {current} de {total} · {label}',
  'editor_step_template'                : 'Plantilla',
  'editor_step_personal'                : 'Personal',
  'editor_step_experience'              : 'Experiencia',
  'editor_step_education'               : 'Educación',
  'editor_step_skills'                  : 'Habilidades',
  'editor_step_additional'              : 'Adicional',
  'editor_step_references'              : 'Referencias',
  'editor_step_customize'               : 'Personalizar',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personalizar',
  'customize_subtitle'                  : 'Haz tu CV único',
  'customize_smart_layout_btn'          : 'Diseño Inteligente',
  'customize_back_to_top'               : 'Volver Arriba',
  'customize_done_title'                : '¡Todo listo!',
  'customize_done_sub'                  : 'Toca Vista Previa del CV abajo para ver tu CV terminado',
  'customize_preview_btn'               : 'Vista Previa del CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Esquema de Colores',
  'color_black'                         : 'Negro',
  'color_blue'                          : 'Azul',
  'color_nordic_blue'                   : 'Azul Nórdico',
  'color_indigo'                        : 'Índigo',
  'color_teal'                          : 'Verde Azulado',
  'color_green'                         : 'Verde',
  'color_purple'                        : 'Morado',
  'color_orange'                        : 'Naranja',
  'color_red'                           : 'Rojo',
  'color_executive_gold'                : 'Dorado Ejecutivo',
  'color_vibrant_coral'                 : 'Coral Vibrante',
  'color_white'                         : 'Blanco',
  'color_white_bg'                      : 'Fondo Blanco',
  'color_maroon'                        : 'Granate',
  'color_brutalist_yellow'              : 'Amarillo Brutalista',
  'color_neon_blue'                     : 'Azul Neón',
  'color_blueprint_navy'                : 'Azul Marino Blueprint',
  'color_light_grey'                    : 'Gris Claro',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Familia de Fuente',
  'customize_font_picker_title'         : 'Elegir Fuente',
  'customize_font_picker_sub'           : 'Cada fuente se previsualiza en su propia tipografía',
  'customize_font_preview_sample'       : 'El rápido zorro marrón',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Tamaño de Fuente',
  'customize_font_size_label'           : 'Tamaño de Texto',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Tamaño de Imagen',
  'customize_image_size_label'          : 'Tamaño de Imagen',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Vista Previa en Vivo',
  'preview_page_count_singular'         : '1 página',
  'preview_page_count_plural'           : '{n} páginas',
  'preview_page_of'                     : 'Página {page} de {total}',
  'preview_live_hint'                   : 'Los cambios se aplican al instante',
  'preview_template_unregistered'       : 'Aún no registrado en customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Preparando tu CV…',
  'preview_bar_print'                   : 'Imprimir',
  'preview_bar_save_pdf'                : 'Guardar como PDF',
  'preview_bar_share'                   : 'Compartir',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Vista Previa del CV',
  'preview_screen_sub'                  : '{n} {unit} · tal como se imprime',
  'preview_page_singular'               : 'página',
  'preview_page_plural'                 : 'páginas',
  'preview_pdf_filename'                : 'Mi_CV',
  'preview_share_subject'               : 'Mi CV',
  'preview_snack_print_failed'          : 'Error al imprimir: {e}',
  'preview_snack_saved'                 : 'CV guardado en Descargas ✓',
  'preview_snack_export_failed'         : 'Error al exportar: {e}',
  'preview_snack_share_failed'          : 'Error al compartir: {e}',
  'preview_template_not_registered'     : 'Plantilla no registrada',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Cerrar vista previa',
  'preview_modal_hint_photo'            : 'Admite foto de perfil  ·  Toca una tarjeta para seleccionar',
  'preview_modal_hint_no_photo'         : 'Toca una tarjeta de plantilla para seleccionarla',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Mi CV',
  'time_just_now'                       : 'Ahora mismo',
  'time_minutes_ago'                    : 'hace {n} min',
  'time_hours_ago'                      : 'hace {n} h',
  'time_yesterday'                      : 'Ayer',
  'time_days_ago'                       : 'hace {n} días',
  'time_one_week_ago'                   : 'hace 1 semana',
  'time_weeks_ago'                      : 'hace {n} semanas',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegante',
  'tpl_tag_classic'                     : 'Clásico',
  'tpl_tag_minimal'                     : 'Minimalista',
  'tpl_tag_creative'                    : 'Creativo',
  'tpl_tag_bold'                        : 'Audaz',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Degradado',
  'tpl_gradient_desc'                   : 'Tarjetas con degradado de verde azulado a violeta',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Estilo revista en rojo y crema',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Suave',
  'tpl_pastel_soft_desc'                : 'Barra lateral lavanda, tarjetas suaves',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalista',
  'tpl_brutalist_desc'                  : 'Cuadrícula cruda, bordes audaces y amarillo',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Esmeralda',
  'tpl_emerald_desc'                    : 'Verde bosque con línea de tiempo',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infográfico',
  'tpl_infographic_desc'                : 'Fondo oscuro con gráficos circulares',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Decó',
  'tpl_art_deco_desc'                   : 'Lujo geométrico dorado de los años 20',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Oscuro',
  'tpl_wina_dark_desc'                  : 'Infográfico oscuro con anillos',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Río Naranja',
  'tpl_rio_orange_desc'                 : 'Barra lateral oscura con acento naranja',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Verano',
  'tpl_summer_desc'                     : 'Minimalista limpio en tonos gris suave',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Tonos elegantes en beige cálido',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Clásico en blanco y negro austero',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Diseño clásico compatible con ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Oscuro',
  'tpl_tony_dark_desc'                  : 'Estilo infográfico oscuro naranja',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Dibujo técnico sobre cuadrícula',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivista',
  'tpl_archivist_desc'                  : 'Diseño clásico de dos columnas con etiquetas',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomático',
  'tpl_diplomat_desc'                   : 'Encabezados sombreados con guías de diamante',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Encabezados centrados con empresas en acento',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nombre audaz, puntos de línea de tiempo y logros',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Información Personal',
  'personal_subtitle'                   : 'Cuéntale a los empleadores quién eres',
  'personal_profile_counter'            : '{n}/{max} perfiles',
  'personal_info_banner'                : 'Guarda hasta 5 perfiles y selecciona uno por CV. Tu selección se recuerda para cada CV por separado.',
  'personal_snack_max'                  : 'Máximo de {n} perfiles alcanzado.',
  'personal_add_btn'                    : 'Agregar Nuevo Perfil',
  'personal_library_title'              : 'Perfiles Guardados',
  'personal_selected_one'               : '1 seleccionado',
  'personal_selected_none'              : 'ninguno seleccionado',
  'personal_library_hint'               : 'Toca una tarjeta para seleccionarla solo para este CV. Los demás CVs mantienen sus propias selecciones independientes.',
  'personal_empty_message'              : 'Aún no hay perfiles guardados',
  'personal_empty_sub'                  : 'Toca arriba para agregar tu información personal',
  'personal_nav_next'                   : 'Guardar y Continuar',
  'personal_card_active_badge'          : 'Activo para este CV',
  'personal_sheet_title_add'            : 'Nuevo Perfil',
  'personal_sheet_title_edit'           : 'Editar Perfil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTA',
  'personal_sheet_brutalist_banner'     : 'La plantilla Brutalista tiene campos de contacto compactos. Los valores más cortos (ej. solo ciudad) se muestran mejor.',
  'personal_section_photo'              : 'Foto de Perfil',
  'personal_section_basic'              : 'Datos Básicos',
  'personal_section_contact'            : 'Contacto',
  'personal_section_online'             : 'Presencia en Línea',
  'personal_section_summary'            : 'Resumen Profesional',
  'personal_field_first_name'           : 'Nombre *',
  'personal_field_last_name'            : 'Apellido',
  'personal_field_job_title'            : 'Cargo *',
  'personal_field_email'                : 'Correo Electrónico *',
  'personal_field_phone'                : 'Número de Teléfono *',
  'personal_field_location'             : 'Ubicación',
  'personal_field_location_brut'        : 'Ubicación (solo ciudad)',
  'personal_field_website'              : 'Sitio Web / Portafolio',
  'personal_field_linkedin'             : 'URL de LinkedIn',
  'personal_hint_first_name'            : 'ej. Ana',
  'personal_hint_last_name'             : 'ej. García',
  'personal_hint_job_title'             : 'ej. Ingeniera Senior',
  'personal_hint_email'                 : 'ej. ana@ejemplo.com',
  'personal_hint_phone'                 : 'ej. +34 612 345 678',
  'personal_hint_location'              : 'ej. Madrid, España',
  'personal_hint_location_brut'         : 'ej. Madrid, ES',
  'personal_hint_website'               : 'ej. github.com/anagarcia',
  'personal_hint_website_brut'          : 'ej. github.com/ana',
  'personal_hint_linkedin'              : 'ej. linkedin.com/in/anagarcia',
  'personal_hint_linkedin_brut'         : 'ej. linkedin.com/in/ana',
  'personal_summary_hint_label'         : 'Sé conciso — esto aparece en la parte superior de tu CV.',
  'personal_hint_summary'               : 'Un breve resumen de 2 a 3 frases sobre tu experiencia y objetivos...',
  'personal_validator_email'            : 'Introduce un correo electrónico válido',
  'personal_field_char_limit_tooltip'   : 'Límite de caracteres alcanzado',
  'personal_sheet_btn_save'             : 'Guardar Perfil',
  'personal_sheet_btn_update'           : 'Guardar Cambios',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Elegir Foto',
  'photo_option_gallery'                : 'Elegir de la Galería',
  'photo_option_camera'                 : 'Tomar una Foto',
  'photo_option_reposition'             : 'Reposicionar Foto',
  'photo_option_remove'                 : 'Eliminar Foto',
  'photo_status_added'                  : 'Foto agregada ✓',
  'photo_status_empty'                  : 'Agrega una foto profesional',
  'photo_chip_gallery'                  : 'Galería',
  'photo_chip_camera'                   : 'Cámara',
  'photo_chip_reposition'               : 'Reposicionar',
  'photo_reposition_title'              : 'Reposicionar Foto',
  'photo_reposition_sub'                : 'Arrastra la foto para ajustar la posición',
  'photo_reposition_reset'              : 'Restablecer al centro',
  'photo_reposition_apply'              : 'Aplicar',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Habilidades',
  'skills_subtitle'                     : 'Destaca tus capacidades clave',
  'skills_add_btn'                      : 'Agregar Nueva Habilidad',
  'skills_snack_max_icons'              : 'Máximo de 10 íconos seleccionados.',
  'skills_snack_max_skills'             : 'Máximo de 15 habilidades alcanzado.',
  'skills_library_title'                : 'Habilidades Guardadas',
  'skills_library_hint'                 : 'Las habilidades marcadas se incluyen en este CV. Tus selecciones se guardan automáticamente.',
  'skills_nav_next'                     : 'Continuar a Adicional',
  'skills_wina_header_icon_bar'         : 'Barra de Íconos del Encabezado',
  'skills_wina_on'                      : 'ACTIVADO',
  'skills_wina_off'                     : 'DESACTIVADO',
  'skills_wina_bar_on_sub'              : 'Círculos de íconos de colores mostrados en el encabezado del CV.',
  'skills_wina_bar_off_sub'             : 'Fila de íconos oculta — más espacio para información de contacto.',
  'skills_wina_palette_hint'            : 'Los íconos aparecen como círculos de colores en el orden de la paleta.',
  'skills_wina_preview_label'           : 'Vista Previa',
  'skills_wina_disabled_hint'           : 'Activa la barra de íconos arriba para elegir qué íconos aparecen en el encabezado del CV.',
  'skills_sheet_title_add'              : 'Agregar Habilidad',
  'skills_sheet_title_edit'             : 'Editar Habilidad',
  'skills_sheet_field_name'             : 'Nombre de la Habilidad *',
  'skills_sheet_hint_short'             : 'ej. Flutter, Diseño',
  'skills_sheet_hint_long'              : 'ej. Flutter, Gestión de Proyectos',
  'skills_sheet_validator_max'          : 'Máx. {n} caracteres',
  'skills_sheet_proficiency'            : 'Nivel de Competencia',
  'skills_sheet_beginner'               : 'Principiante',
  'skills_sheet_expert'                 : 'Experto',
  'skills_sheet_btn_save'               : 'Guardar Habilidad',
  'skills_sheet_btn_update'             : 'Actualizar Habilidad',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referencias Personales',
  'refs_subtitle'                       : 'Personas que pueden responder por ti personalmente',
  'refs_add_btn'                        : 'Agregar Nueva Referencia Personal',
  'refs_snack_max_selected'             : 'Se pueden seleccionar máximo 4 referencias para un CV.',
  'refs_snack_max_saved'                : 'Máximo de 10 referencias guardadas alcanzado.',
  'refs_library_title'                  : 'Referencias Guardadas',
  'refs_library_hint'                   : 'Las referencias marcadas se incluyen en este CV. Máx. 4 por CV. Tus selecciones se guardan automáticamente.',
  'refs_nav_next'                       : 'Continuar a Personalizar',
  'refs_sheet_title_add'                : 'Agregar Referencia Personal',
  'refs_sheet_title_edit'               : 'Editar Referencia Personal',
  'refs_sheet_sub_add'                  : 'Alguien que pueda recomendarte personalmente a los empleadores.',
  'refs_sheet_sub_edit'                 : 'Actualiza los datos de esta referencia a continuación.',
  'refs_sheet_field_name'               : 'Nombre Completo *',
  'refs_sheet_field_title'              : 'Cargo *',
  'refs_sheet_field_company'            : 'Empresa (opcional)',
  'refs_sheet_field_email'              : 'Correo Electrónico *',
  'refs_sheet_field_phone'              : 'Número de Teléfono *',
  'refs_sheet_hint_name'                : 'ej. Carlos López',
  'refs_sheet_hint_title'               : 'ej. Gerente de Ingeniería',
  'refs_sheet_hint_company'             : 'ej. Acme Corp',
  'refs_sheet_hint_email'               : 'ej. carlos@acme.com',
  'refs_sheet_hint_phone'               : 'ej. +34 612 345 678',
  'refs_sheet_validator_email'          : 'Introduce una dirección de correo válida',
  'refs_sheet_btn_save'                 : 'Guardar Referencia Personal',
  'refs_sheet_btn_update'               : 'Actualizar Referencia Personal',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Experiencia Laboral',
  'exp_subtitle'                        : 'Agrega tu historial laboral',
  'exp_banner_info'                     : 'Hasta {n} responsabilidades por puesto aparecerán en el CV. De 3 a 6 puestos suele caber en 1 o 2 páginas.',
  'exp_add_btn'                         : 'Agregar Nueva Experiencia',
  'exp_snack_max_selected'              : 'Se pueden seleccionar máximo 8 experiencias para un CV.',
  'exp_snack_max_saved'                 : 'Máximo de 12 experiencias guardadas alcanzado.',
  'exp_library_title'                   : 'Experiencias Guardadas',
  'exp_library_hint'                    : 'Las entradas marcadas se incluyen solo en este CV. Los demás CVs mantienen sus propias selecciones independientes.',
  'exp_nav_next'                        : 'Continuar a Educación',
  'exp_empty_message'                   : 'Aún no se ha agregado experiencia',
  'exp_empty_sub'                       : 'Toca arriba para agregar tu primer puesto',
  'exp_card_resp_singular'              : 'responsabilidad',
  'exp_card_resp_plural'                : 'responsabilidades',
  'exp_card_resp_tooltip'               : 'Solo las primeras 8 responsabilidades aparecerán en el CV',
  'exp_sheet_title_add'                 : 'Agregar Experiencia',
  'exp_sheet_title_edit'                : 'Editar Experiencia',
  'exp_sheet_field_job_title'           : 'Cargo *',
  'exp_sheet_field_company'             : 'Empresa *',
  'exp_sheet_field_location'            : 'Ubicación',
  'exp_sheet_section_responsibilities'  : 'Responsabilidades Clave',
  'exp_sheet_resp_hint_info'            : 'Máx. 8 puntos · 200 caracteres cada uno',
  'exp_sheet_resp_label'                : 'Responsabilidad {n}',
  'exp_sheet_resp_hint'                 : 'ej. Lideró un equipo de 5 ingenieros',
  'exp_sheet_resp_add_btn'              : 'Agregar Responsabilidad',
  'exp_sheet_resp_max_info'             : 'Máximo {n} responsabilidades alcanzado',
  'exp_sheet_resp_validator_max'        : 'Máx. 200 caracteres',
  'exp_sheet_hint_job_title'            : 'ej. Desarrollador Senior',
  'exp_sheet_hint_location'             : 'ej. Madrid, España',
  'exp_sheet_btn_save'                  : 'Guardar Experiencia',
  'exp_sheet_btn_update'                : 'Guardar Cambios',
  'exp_date_present'                    : 'Presente / Puesto Actual',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Educación',
  'edu_subtitle'                        : 'Agrega tu formación académica',
  'edu_add_btn'                         : 'Agregar Nueva Educación',
  'edu_snack_max_selected'              : 'Se pueden seleccionar máximo 8 entradas de educación para un CV.',
  'edu_snack_max_saved'                 : 'Máximo de 12 entradas de educación guardadas alcanzado.',
  'edu_library_title'                   : 'Educación Guardada',
  'edu_library_hint'                    : 'Las entradas marcadas se incluyen en este CV. Tus selecciones se guardan automáticamente.',
  'edu_nav_next'                        : 'Continuar a Habilidades',
  'edu_empty_message'                   : 'Aún no se ha agregado educación',
  'edu_empty_sub'                       : 'Toca arriba para agregar tus calificaciones',
  'edu_card_bullet_singular'            : 'punto',
  'edu_card_bullet_plural'              : 'puntos',
  'edu_sheet_title_add'                 : 'Agregar Educación',
  'edu_sheet_title_edit'                : 'Editar Educación',
  'edu_sheet_field_degree'              : 'Título / Calificación *',
  'edu_sheet_field_institution'         : 'Institución *',
  'edu_sheet_section_key_points'        : 'Puntos Clave',
  'edu_sheet_key_points_hint_info'      : 'Opcional · 1 punto · máx. 100 caracteres',
  'edu_sheet_point_label'               : 'Punto {n}',
  'edu_sheet_point_add_btn'             : 'Agregar Punto',
  'edu_sheet_point_max_info'            : 'Máximo {n} puntos alcanzado',
  'edu_sheet_point_validator_max'       : 'Máx. {n} caracteres',
  'edu_sheet_hint_degree'               : 'ej. Grado en Ingeniería Informática',
  'edu_sheet_hint_institution'          : 'ej. Universidad Complutense de Madrid',
  'edu_sheet_hint_bullet'               : 'ej. Matrícula de Honor',
  'edu_sheet_btn_save'                  : 'Guardar Educación',
  'edu_sheet_btn_update'                : 'Guardar Cambios',
  'edu_date_present'                    : 'Presente / Estudio Actual',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Información Adicional',
  'additional_subtitle'                 : 'Certificaciones, idiomas y más',
  'additional_cert_section_title'       : 'Certificaciones',
  'additional_cert_counter'             : '{sel}/{total} seleccionadas · máx. {max}',
  'additional_cert_hide'                : 'Ocultar',
  'additional_cert_show'                : 'Mostrar',
  'additional_cert_add_btn'             : 'Agregar',
  'additional_cert_snack_max'           : 'Máximo de {n} entradas de certificación alcanzado.',
  'additional_cert_hint'                : 'Las entradas marcadas se incluyen en este CV. Tus selecciones se guardan automáticamente.',
  'additional_cert_empty'               : 'Aún no se han agregado certificaciones',
  'additional_lang_section_title'       : 'Idiomas',
  'additional_lang_add_hint'            : 'ej. Español',
  'additional_lang_snack_max'           : 'Máximo de {n} entradas de idioma alcanzado.',
  'additional_lang_empty'               : 'Aún no se han agregado idiomas',
  'additional_hobby_section_title'      : 'Hobbies e Intereses',
  'additional_hobby_add_hint'           : 'ej. Fotografía',
  'additional_hobby_snack_max'          : 'Máximo de {n} entradas de hobby alcanzado.',
  'additional_hobby_empty'              : 'Aún no se han agregado hobbies',
  'additional_section_hint'             : 'Las entradas marcadas se incluyen en este CV. Tus selecciones se guardan automáticamente.',
  'additional_nav_next'                 : 'Continuar a Referencias',
  'cert_sheet_title_add'                : 'Agregar Certificación',
  'cert_sheet_title_edit'               : 'Editar Certificación',
  'cert_sheet_sub'                      : 'Agrega una calificación, certificado o credencial profesional.',
  'cert_sheet_field_name'               : 'Nombre de la Certificación *',
  'cert_sheet_field_issued_by'          : 'Emitida Por (opcional)',
  'cert_sheet_field_short_desc'         : 'Descripción Breve (opcional)',
  'cert_sheet_hint_name'                : 'ej. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'ej. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'ej. Obtenida en 2024',
  'cert_sheet_btn_save'                 : 'Guardar Certificación',
  'cert_sheet_btn_update'               : 'Actualizar Certificación',
  'simple_sheet_title_add_language'     : 'Agregar Idioma',
  'simple_sheet_title_edit_language'    : 'Editar Idioma',
  'simple_sheet_title_add_hobby'        : 'Agregar Hobby',
  'simple_sheet_title_edit_hobby'       : 'Editar Hobby',
  'simple_sheet_btn_save'               : 'Guardar',
  'simple_sheet_btn_update'             : 'Actualizar',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contacto',
  'pdf_section_about_me'                : 'Sobre Mí',
  'pdf_section_summary'                 : 'Resumen',
  'pdf_section_summary_short'           : 'Resumen',
  'pdf_section_profile'                 : 'Perfil',
  'pdf_section_experience'              : 'Experiencia',
  'pdf_section_experience_short'        : 'Experiencia',
  'pdf_section_education'               : 'Educación',
  'pdf_section_skills'                  : 'Habilidades',
  'pdf_section_languages'               : 'Idiomas',
  'pdf_label_email'                     : 'Correo',
  'pdf_label_phone'                     : 'Teléfono',
  'pdf_label_location'                  : 'Localización',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Límite de CV alcanzado',
  'limit_dialog_body'                   : 'Has alcanzado el máximo de 30 CVs. Por favor, elimina un CV existente antes de crear uno nuevo.',
  'limit_dialog_go_to_my_cvs'           : 'Ir a Mis CVs',
  'limit_dialog_cancel'                 : 'Cancelar',
  'refs_count_summary'                  : '{checked}/{maxChecked} seleccionados · {saved}/{maxSaved} guardados',
  'refs_selected_badge'                 : '{n} seleccionado(s)',
  'refs_empty_message'                  : 'No hay referencias guardadas aún',
  'refs_empty_sub'                      : 'Toca arriba para agregar una referencia personal',
};