// lib/language_keys/lang_fr_french.dart
//
// French (France) translation map.

const Map<String, String> frFrench = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Aucune langue trouvée',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Ignorer',
  'onboarding_next'                     : 'Suivant',
  'onboarding_get_started'              : 'Commencer',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Bienvenue',
  'ob1_title'                           : 'Créez un CV qui\nOuvre des Portes',
  'ob1_body'                            : 'Démarquez-vous parmi des centaines de candidats. Créez un CV soigné et gagnant en quelques minutes — aucune compétence en design requise.',
  'ob1_pill_label'                      : 'Créateur de CV Professionnel',
  'ob1_chip_templates'                  : '24+ Modèles',
  'ob1_chip_pdf'                        : 'Export PDF',
  'ob1_chip_free'                       : 'Gratuit',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Modèles',
  'ob2_title'                           : 'Chaque Secteur.\nChaque Ambition.',
  'ob2_body'                            : 'Des mises en page pour salles de conseil aux designs créatifs audacieux — un modèle qui raconte votre histoire.',
  'ob2_tap_hint'                        : 'Appuyez sur un modèle pour l\'apercevoir',
  'ob2_tpl_executive'                   : 'Cadre',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordique',
  'ob2_tpl_tech_dark'                   : 'Tech Sombre',
  'ob2_tpl_luxury'                      : 'Luxe',
  'ob2_tag_corporate'                   : 'Corporate',
  'ob2_tag_creative'                    : 'Créatif',
  'ob2_tag_minimal'                     : 'Minimaliste',
  'ob2_tag_modern'                      : 'Moderne',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Mise en Page Intelligente',
  'ob3_title'                           : 'Votre CV.\nParfaitement Organisé.',
  'ob3_body'                            : 'La Mise en Page Intelligente réorganise vos sections pour un impact maximal — plaçant votre contenu le plus fort là où les recruteurs regardent en premier.',
  'ob3_badge_smart_layout'              : 'Mise en Page Intelligente',
  'ob3_badge_cv_ready'                  : 'CV Prêt !',
  'ob3_step1_label'                     : 'Choisir un Modèle',
  'ob3_step1_desc'                      : 'Choisissez parmi plus de 24 designs époustouflants.',
  'ob3_step2_label'                     : 'Remplir vos Informations',
  'ob3_step2_desc'                      : 'Champs guidés pour toutes les sections.',
  'ob3_step3_label'                     : 'Mise en Page Intelligente',
  'ob3_step3_desc'                      : 'Un seul appui réorganise votre CV parfaitement.',
  'ob3_step4_label'                     : 'Exporter en PDF',
  'ob3_step4_desc'                      : 'PDF pixel-perfect prêt à envoyer.',
  'ob3_section_work'                    : 'Expérience Professionnelle',
  'ob3_section_education'               : 'Formation',
  'ob3_section_skills'                  : 'Compétences',
  'ob3_section_references'              : 'Références',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Prêt à Démarrer',
  'ob4_title'                           : 'Pourquoi les Meilleurs Candidats\nChoisissent CV Builder',
  'ob4_visual_headline'                 : 'Tout est Prêt !',
  'ob4_visual_subline'                  : 'Tout ce dont vous avez besoin pour décrocher le poste.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Modèles',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'CV Max.',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privé',
  'ob4_hl1_title'                       : 'Privé et Sécurisé',
  'ob4_hl1_sub'                         : 'Les données restent sur votre appareil.',
  'ob4_hl2_title'                       : 'Sauvegarde Auto',
  'ob4_hl2_sub'                         : 'Chaque frappe sauvegardée instantanément.',
  'ob4_hl3_title'                       : 'Jusqu\'à 30 CV',
  'ob4_hl3_sub'                         : 'Un CV unique pour chaque poste.',
  'ob4_hl4_title'                       : 'Partage en Un Geste',
  'ob4_hl4_sub'                         : 'Envoyez le PDF sans quitter l\'application.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Démarquez-vous de la foule',
  'home_hero_title'                     : 'Créez votre\nCV Professionnel',
  'home_hero_sub'                       : 'Créez un CV impressionnant\nen quelques minutes',
  'home_hero_cta'                       : 'Commencer',
  'home_premium_soon'                   : 'Mise à niveau Pro bientôt disponible !',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Plus Récent',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Dernière Modification',
  'history_sort_by_template'            : 'Par Modèle',
  'history_sort_sheet_title'            : 'Trier Par',
  'history_sort_alphabetical_full'      : 'Alphabétique (A–Z)',
  'history_premium_soon'                : 'Mise à niveau Pro bientôt disponible !',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Paramètres',
  'settings_section_preferences'        : 'Préférences',
  'settings_section_support'            : 'Assistance',
  'settings_section_legal'              : 'Mentions Légales',
  'settings_section_about'              : 'À Propos',
  'settings_language_tile_title'        : 'Langue',
  'settings_dark_mode_title'            : 'Mode Sombre',
  'settings_dark_mode_on'               : 'Thème sombre activé',
  'settings_dark_mode_off'              : 'Thème clair activé',
  'settings_help_faq_title'             : 'Aide et FAQ',
  'settings_help_faq_sub'               : 'Questions fréquentes répondues',
  'settings_contact_support_title'      : 'Contacter l\'Assistance',
  'settings_rate_app_title'             : 'Évaluer l\'Application',
  'settings_rate_app_sub'               : 'Vous aimez l\'application ? Laissez un avis !',
  'settings_privacy_policy_title'       : 'Politique de Confidentialité',
  'settings_terms_title'                : 'Conditions d\'Utilisation',
  'settings_app_version_title'          : 'Version de l\'Application',
  'settings_email_error'                : 'Impossible d\'ouvrir l\'application de messagerie. Veuillez envoyer un e-mail à cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Aperçu du CV',
  'preview_header_sub'                  : 'Prêt à exporter',
  'preview_generating'                  : 'Génération de votre CV...',
  'preview_failed_title'                : 'Échec de l\'Aperçu',
  'preview_failed_error'                : 'Erreur : {error}',
  'preview_go_back'                     : 'Retour',
  'preview_no_data'                     : 'Aucune donnée disponible',
  'preview_btn_print'                   : 'Imprimer',
  'preview_btn_download'                : 'Télécharger et Partager',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Aide et FAQ',
  'faq_category_all'                    : 'Tout',
  'faq_empty'                           : 'Aucun résultat trouvé',
  'faq_contact_headline'                : 'Besoin d\'aide ?',
  'faq_contact_sub'                     : 'Notre équipe est là pour vous.',
  'faq_contact_btn'                     : 'Contacter',
  'faq_email_error'                     : 'Impossible d\'ouvrir l\'application de messagerie. Veuillez envoyer un e-mail à cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Premiers Pas',
  'faq_cat_templates'                   : 'Modèles',
  'faq_cat_editing'                     : 'Édition',
  'faq_cat_exporting'                   : 'Exportation',
  'faq_cat_data_privacy'                : 'Données et Confidentialité',
  'faq_cat_troubleshooting'             : 'Dépannage',
  'faq_q1'  : 'Comment créer mon premier CV ?',
  'faq_a1'  : 'Appuyez sur le bouton "+" sur l\'écran d\'accueil pour commencer un nouveau CV. Choisissez un modèle qui correspond à votre style, puis remplissez vos informations personnelles, votre expérience professionnelle, votre formation et vos compétences étape par étape. Votre progression est sauvegardée automatiquement.',
  'faq_q2'  : 'Puis-je créer plus d\'un CV ?',
  'faq_a2'  : 'Oui ! Vous pouvez créer plusieurs CV pour différents postes ou secteurs. Chaque CV est sauvegardé séparément, vous permettant de les adapter à des candidatures spécifiques.',
  'faq_q3'  : 'Comment changer le modèle de mon CV ?',
  'faq_a3'  : 'Ouvrez votre CV, appuyez sur l\'icône de modèle en haut de l\'écran et parcourez les modèles disponibles. Appuyez sur n\'importe quel modèle pour le prévisualiser avec votre contenu existant. Confirmez pour l\'appliquer.',
  'faq_q4'  : 'Y a-t-il des modèles gratuits et premium ?',
  'faq_a4'  : 'Oui. Une sélection de modèles professionnels est disponible gratuitement. Les modèles premium avec des designs avancés et des palettes de couleurs sont disponibles via un achat unique ou un abonnement.',
  'faq_q5'  : 'Comment ajouter ou supprimer des sections ?',
  'faq_a5'  : 'Dans l\'éditeur de CV, faites défiler jusqu\'en bas de l\'écran et appuyez sur "Ajouter une section" pour inclure des extras comme Langues, Certifications ou Bénévolat. Pour supprimer une section, appuyez sur l\'en-tête de section et sélectionnez "Supprimer."',
  'faq_q6'  : 'Comment réorganiser les sections ?',
  'faq_a6'  : 'Appuyez longuement sur la poignée de glissement (≡) à côté de n\'importe quel en-tête de section et faites-la glisser vers la position souhaitée. Les modifications sont sauvegardées automatiquement.',
  'faq_q7'  : 'Comment exporter mon CV en PDF ?',
  'faq_a7'  : 'Ouvrez votre CV et appuyez sur le bouton d\'exportation (icône de partage) dans le coin supérieur droit. Sélectionnez "Exporter en PDF." Vous pouvez ensuite le sauvegarder sur votre appareil, le partager par e-mail, WhatsApp ou le télécharger directement sur des sites d\'emploi.',
  'faq_q8'  : 'Quels formats de fichiers sont pris en charge ?',
  'faq_a8'  : 'Actuellement, l\'application prend en charge l\'exportation de votre CV en PDF haute qualité. Des formats supplémentaires pourront être ajoutés dans les mises à jour futures.',
  'faq_q9'  : 'Où sont stockées les données de mon CV ?',
  'faq_a9'  : 'Toutes les données de votre CV sont stockées localement sur votre appareil. Nous ne téléchargeons pas vos informations personnelles sur nos serveurs. Vos données restent ainsi privées et accessibles hors ligne.',
  'faq_q10' : 'Comment sauvegarder mes CV ?',
  'faq_a10' : 'Vos CV sont inclus dans la sauvegarde standard de votre appareil (sauvegarde Google Drive sur Android, iCloud sur iOS) si vous avez activé la sauvegarde dans les paramètres de votre appareil. Vous pouvez également exporter des CV individuels en PDF pour en conserver une copie.',
  'faq_q11' : 'L\'application est lente. Que faire ?',
  'faq_a11' : 'Essayez de fermer et de rouvrir l\'application. Si le problème persiste, redémarrez votre appareil. Assurez-vous d\'avoir la dernière version de l\'application installée depuis le Play Store / App Store.',
  'faq_q12' : 'Mon CV ne s\'exporte pas correctement. Que faire ?',
  'faq_a12' : 'Assurez-vous d\'avoir suffisamment d\'espace de stockage sur votre appareil. Essayez de réduire les grandes images dans votre CV. Si le problème persiste, veuillez contacter notre équipe d\'assistance.',
  'faq_q13' : 'J\'ai oublié de sauvegarder — mon travail est-il perdu ?',
  'faq_a13' : 'Pas du tout ! L\'application sauvegarde votre progression en continu pendant que vous éditez.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Votre carrière, perfectionnée',
  'header_tooltip_back'                 : 'Retour',
  'header_tooltip_my_cvs'               : 'Mes CV',
  'header_tooltip_settings'             : 'Paramètres',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Mes CV',
  'saved_count_single'                  : '{n} document',
  'saved_count_plural'                  : '{n} documents',
  'saved_limit_reached'                 : 'Limite atteinte',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Tous',
  'saved_filter_draft'                  : 'Brouillon',
  'saved_filter_complete'               : 'Complet',
  'saved_status_complete'               : 'Complet',
  'saved_status_saved'                  : 'Sauvegardé',
  'saved_status_draft'                  : 'Brouillon',
  'saved_empty_title'                   : 'Aucun CV pour l\'instant',
  'saved_empty_sub'                     : 'Commencez à créer votre premier CV ci-dessus',
  'saved_search_empty_title'            : 'Aucun résultat trouvé',
  'saved_search_empty_sub'              : 'Essayez un autre terme de recherche',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Palette de Couleurs',
  'custom_font_settings_title'          : 'Paramètres de Police',
  'custom_font_family_label'            : 'Famille de Police',
  'custom_font_size_label'              : 'Taille de Police : ',
  'custom_current_template_title'       : 'Modèle Actuel',
  'custom_change_template_btn'          : 'Changer de Modèle',
  'custom_tpl_modern'                   : 'Moderne',
  'custom_tpl_classic'                  : 'Classique',
  'custom_tpl_professional'             : 'Professionnel',
  'custom_tpl_creative'                 : 'Créatif',
  'custom_tpl_minimal'                  : 'Minimaliste',
  'custom_tpl_modern_desc'              : 'Design épuré et contemporain',
  'custom_tpl_classic_desc'             : 'Mise en page professionnelle traditionnelle',
  'custom_tpl_professional_desc'        : 'Modèle axé sur les affaires',
  'custom_tpl_creative_desc'            : 'Démarquez-vous avec un design unique',
  'custom_tpl_minimal_desc'             : 'Style simple et élégant',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Choisir un Modèle',
  'swipe_photo_badge'                   : 'Photo',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Cadre',
  'tpl_nordic_name'                     : 'Nordique',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Sombre',
  'tpl_luxury_name'                     : 'Luxe',
  'tpl_executive_tag'                   : 'Le Plus Populaire',
  'tpl_nordic_tag'                      : 'Épuré',
  'tpl_vibrant_tag'                     : 'Créatif',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Élite',
  'tpl_executive_desc'                  : 'Audacieux et autoritaire pour les postes seniors',
  'tpl_nordic_desc'                     : 'Clarté minimaliste adoptée par les meilleures entreprises',
  'tpl_vibrant_desc'                    : 'Démarquez-vous avec énergie et couleur',
  'tpl_tech_dark_desc'                  : 'Esthétique terminal pour les développeurs',
  'tpl_luxury_desc'                     : 'Prestige doré sur fond noir',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Modèle',
  'detail_step_personal'                : 'Personnel',
  'detail_step_experience'              : 'Expérience',
  'detail_step_education'               : 'Formation',
  'detail_step_skills'                  : 'Compétences',
  'detail_step_additional'              : 'Complémentaire',
  'detail_step_references'              : 'Références',
  'detail_step_customize'               : 'Personnaliser',
  'detail_banner_heading'               : 'Presque terminé !',
  'detail_banner_btn'                   : 'Continuer',
  'detail_banner_completion_label'      : 'Avancement',
  'detail_stat_created_label'           : 'Créé',
  'detail_stat_steps_label'             : 'Étapes effectuées',
  'detail_section_template_style'       : 'Style du Modèle',
  'detail_section_steps'                : 'Étapes',
  'detail_steps_counter'                : '{done} sur {total} terminées',
  'detail_step_sub'                     : 'Étape {n} sur {total}',
  'detail_section_activity'             : 'Activité',
  'detail_activity_created'             : 'Créé',
  'detail_activity_last_edited'         : 'Dernière Modification',
  'detail_activity_template'            : 'Modèle',
  'detail_btn_continue_editing'         : 'Continuer l\'Édition',
  'detail_btn_edit_cv'                  : 'Modifier le CV',
  'detail_option_rename'                : 'Renommer le CV',
  'detail_option_delete'                : 'Supprimer le CV',
  'detail_rename_title'                 : 'Renommer le CV',
  'detail_rename_hint'                  : 'ex. CV Ingénieur Logiciel',
  'detail_rename_error_empty'           : 'Le nom ne peut pas être vide',
  'detail_rename_btn_cancel'            : 'Annuler',
  'detail_rename_btn_save'              : 'Enregistrer',
  'detail_rename_snackbar'              : 'Renommé en "{name}"',
  'detail_delete_title'                 : 'Supprimer le CV ?',
  'detail_delete_body'                  : 'Ceci supprimera définitivement "{name}". Cette action est irréversible.',
  'detail_delete_btn_cancel'            : 'Annuler',
  'detail_delete_btn_confirm'           : 'Supprimer',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Terminé',
  'detail_check_tile_incomplete'        : 'Pas encore rempli',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Choisissez votre Modèle',
  'chooser_subtitle'                    : 'Glisser pour parcourir  ·  Appuyer pour sélectionner  ·  Maintenir pour apercevoir',
  'chooser_card_hold_hint'              : 'Maintenir pour apercevoir',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Sélectionné',
  'chooser_modal_heading'               : 'Nommez votre CV',
  'chooser_modal_sub'                   : 'Donnez-lui un nom pour le retrouver facilement dans Mes CV et l\'Historique.',
  'chooser_modal_field_label'           : 'Nom du CV',
  'chooser_modal_save_btn'              : 'Enregistrer et Commencer',
  'chooser_modal_divider'               : 'ou continuer un CV existant',
  'chooser_nav_selected_sub'            : 'Modèle sélectionné',
  'chooser_nav_cta'                     : 'Enregistrer et Continuer',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Nombre Maximum d\'Entrées Atteint',
  'editor_show_hide'                    : 'Afficher/Masquer',
  'editor_editing_badge'                : 'En cours d\'Édition',
  'editor_field_required'               : 'Obligatoire',
  'editor_tooltip_edit'                 : 'Modifier',
  'editor_tooltip_delete'               : 'Supprimer',
  'editor_date_start'                   : 'Date de Début *',
  'editor_date_end'                     : 'Date de Fin *',
  'editor_date_tap_hint'                : 'Appuyez pour sélectionner',
  'editor_date_dialog_title'            : 'Sélectionner Mois et Année',
  'editor_date_confirm'                 : 'Confirmer',
  'editor_panel_hide'                   : 'Masquer',
  'editor_panel_show'                   : 'Afficher',
  'editor_validator_max_chars'          : 'Max. {n} caractères',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Créez votre CV',
  'editor_header_step_sub'              : 'Étape {current} sur {total} · {label}',
  'editor_step_template'                : 'Modèle',
  'editor_step_personal'                : 'Personnel',
  'editor_step_experience'              : 'Expérience',
  'editor_step_education'               : 'Formation',
  'editor_step_skills'                  : 'Compétences',
  'editor_step_additional'              : 'Complémentaire',
  'editor_step_references'              : 'Références',
  'editor_step_customize'               : 'Personnaliser',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personnaliser',
  'customize_subtitle'                  : 'Rendez votre CV unique',
  'customize_smart_layout_btn'          : 'Mise en Page Intelligente',
  'customize_back_to_top'               : 'Retour en Haut',
  'customize_done_title'                : 'Tout est prêt !',
  'customize_done_sub'                  : 'Appuyez sur Aperçu du CV ci-dessous pour voir votre CV terminé',
  'customize_preview_btn'               : 'Aperçu du CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Palette de Couleurs',
  'color_black'                         : 'Noir',
  'color_blue'                          : 'Bleu',
  'color_nordic_blue'                   : 'Bleu Nordique',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Sarcelle',
  'color_green'                         : 'Vert',
  'color_purple'                        : 'Violet',
  'color_orange'                        : 'Orange',
  'color_red'                           : 'Rouge',
  'color_executive_gold'                : 'Or Exécutif',
  'color_vibrant_coral'                 : 'Corail Vibrant',
  'color_white'                         : 'Blanc',
  'color_white_bg'                      : 'Fond Blanc',
  'color_maroon'                        : 'Bordeaux',
  'color_brutalist_yellow'              : 'Jaune Brutaliste',
  'color_neon_blue'                     : 'Bleu Néon',
  'color_blueprint_navy'                : 'Bleu Marine Blueprint',
  'color_light_grey'                    : 'Gris Clair',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Famille de Police',
  'customize_font_picker_title'         : 'Choisir une Police',
  'customize_font_picker_sub'           : 'Chaque police est prévisualisée dans sa propre typographie',
  'customize_font_preview_sample'       : 'Le renard brun rapide',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Taille de Police',
  'customize_font_size_label'           : 'Taille du Texte',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Taille de l\'Image',
  'customize_image_size_label'          : 'Taille de l\'Image',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Aperçu en Direct',
  'preview_page_count_singular'         : '1 page',
  'preview_page_count_plural'           : '{n} pages',
  'preview_page_of'                     : 'Page {page} sur {total}',
  'preview_live_hint'                   : 'Les modifications s\'appliquent instantanément',
  'preview_template_unregistered'       : 'Pas encore enregistré dans customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Préparation de votre CV…',
  'preview_bar_print'                   : 'Imprimer',
  'preview_bar_save_pdf'                : 'Enregistrer en PDF',
  'preview_bar_share'                   : 'Partager',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Aperçu du CV',
  'preview_screen_sub'                  : '{n} {unit} · exactement tel qu\'imprimé',
  'preview_page_singular'               : 'page',
  'preview_page_plural'                 : 'pages',
  'preview_pdf_filename'                : 'Mon_CV',
  'preview_share_subject'               : 'Mon CV',
  'preview_snack_print_failed'          : 'Échec de l\'impression : {e}',
  'preview_snack_saved'                 : 'CV enregistré dans les Téléchargements ✓',
  'preview_snack_export_failed'         : 'Échec de l\'exportation : {e}',
  'preview_snack_share_failed'          : 'Échec du partage : {e}',
  'preview_template_not_registered'     : 'Modèle non enregistré',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Fermer l\'aperçu',
  'preview_modal_hint_photo'            : 'Prend en charge la photo de profil  ·  Appuyez sur une carte pour sélectionner',
  'preview_modal_hint_no_photo'         : 'Appuyez sur une carte de modèle pour la sélectionner',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Mon CV',
  'time_just_now'                       : 'À l\'instant',
  'time_minutes_ago'                    : 'il y a {n} min',
  'time_hours_ago'                      : 'il y a {n} h',
  'time_yesterday'                      : 'Hier',
  'time_days_ago'                       : 'il y a {n} jours',
  'time_one_week_ago'                   : 'il y a 1 semaine',
  'time_weeks_ago'                      : 'il y a {n} semaines',

  // ─── preview_registry.dart — tag labels ─────────────────────────────────
  'tpl_tag_elegant'                     : 'Élégant',
  'tpl_tag_classic'                     : 'Classique',
  'tpl_tag_minimal'                     : 'Minimaliste',
  'tpl_tag_creative'                    : 'Créatif',
  'tpl_tag_bold'                        : 'Audacieux',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────
  'tpl_gradient_name'                   : 'Dégradé',
  'tpl_gradient_desc'                   : 'Cartes en dégradé du sarcelle au violet',
  'tpl_editorial_name'                  : 'Éditorial',
  'tpl_editorial_desc'                  : 'Style magazine en rouge et crème',
  'tpl_pastel_soft_name'                : 'Pastel Doux',
  'tpl_pastel_soft_desc'                : 'Barre latérale lavande, cartes douces',
  'tpl_brutalist_name'                  : 'Brutaliste',
  'tpl_brutalist_desc'                  : 'Grille brute, bordures audacieuses et jaune',
  'tpl_emerald_name'                    : 'Émeraude',
  'tpl_emerald_desc'                    : 'Vert forêt avec chronologie',
  'tpl_infographic_name'                : 'Infographique',
  'tpl_infographic_desc'                : 'Toile sombre avec graphiques en anneau',
  'tpl_art_deco_name'                   : 'Art Déco',
  'tpl_art_deco_desc'                   : 'Luxe géométrique doré des années 1920',
  'tpl_wina_dark_name'                  : 'Wina Sombre',
  'tpl_wina_dark_desc'                  : 'Infographique sombre avec anneaux',
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Barre latérale sombre avec touche d\'orange',
  'tpl_summer_name'                     : 'Été',
  'tpl_summer_desc'                     : 'Minimaliste épuré, tons gris doux',
  'tpl_helene_name'                     : 'Hélène',
  'tpl_helene_desc'                     : 'Tons beige chauds et élégants',
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Classique noir et blanc épuré',
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Mise en page classique compatible ATS',
  'tpl_tony_dark_name'                  : 'Tony Sombre',
  'tpl_tony_dark_desc'                  : 'Style infographique orange sombre',
  'tpl_fashion_name'                    : 'Mode',
  'tpl_fashion_desc'                    : 'Dessin technique sur quadrillage',
  'tpl_archivist_name'                  : 'Archiviste',
  'tpl_archivist_desc'                  : 'Mise en page classique à deux colonnes',
  'tpl_diplomat_name'                   : 'Diplomate',
  'tpl_diplomat_desc'                   : 'En-têtes ombrés avec points diamant',
  'tpl_meridian_name'                   : 'Méridien',
  'tpl_meridian_desc'                   : 'En-têtes centrés, entreprises en relief',
  'tpl_momentum_name'                   : 'Élan',
  'tpl_momentum_desc'                   : 'Nom en gras, points chronologiques et réalisations',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informations Personnelles',
  'personal_subtitle'                   : 'Présentez-vous aux employeurs',
  'personal_profile_counter'            : '{n}/{max} profils',
  'personal_info_banner'                : 'Enregistrez jusqu\'à 5 profils et sélectionnez-en un par CV. Votre sélection est mémorisée pour chaque CV séparément.',
  'personal_snack_max'                  : 'Nombre maximum de {n} profils atteint.',
  'personal_add_btn'                    : 'Ajouter un Nouveau Profil',
  'personal_library_title'              : 'Profils Enregistrés',
  'personal_selected_one'               : '1 sélectionné',
  'personal_selected_none'              : 'aucun sélectionné',
  'personal_library_hint'               : 'Appuyez sur une carte pour la sélectionner pour ce CV uniquement. Les autres CV conservent leurs propres sélections indépendantes.',
  'personal_empty_message'              : 'Aucun profil enregistré',
  'personal_empty_sub'                  : 'Appuyez ci-dessus pour ajouter vos informations personnelles',
  'personal_nav_next'                   : 'Enregistrer et Continuer',
  'personal_card_active_badge'          : 'Actif pour ce CV',
  'personal_sheet_title_add'            : 'Nouveau Profil',
  'personal_sheet_title_edit'           : 'Modifier le Profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTE',
  'personal_sheet_brutalist_banner'     : 'Le modèle Brutaliste a des champs de contact compacts. Des valeurs plus courtes (ex. ville uniquement) s\'affichent mieux.',
  'personal_section_photo'              : 'Photo de Profil',
  'personal_section_basic'              : 'Informations de Base',
  'personal_section_contact'            : 'Contact',
  'personal_section_online'             : 'Présence en Ligne',
  'personal_section_summary'            : 'Résumé Professionnel',
  'personal_field_first_name'           : 'Prénom *',
  'personal_field_last_name'            : 'Nom de Famille',
  'personal_field_job_title'            : 'Intitulé du Poste *',
  'personal_field_email'                : 'Adresse E-mail *',
  'personal_field_phone'                : 'Numéro de Téléphone *',
  'personal_field_location'             : 'Localisation',
  'personal_field_location_brut'        : 'Localisation (ville uniquement)',
  'personal_field_website'              : 'Site Web / Portfolio',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'ex. Marie',
  'personal_hint_last_name'             : 'ex. Dupont',
  'personal_hint_job_title'             : 'ex. Ingénieure Senior',
  'personal_hint_email'                 : 'ex. marie@exemple.com',
  'personal_hint_phone'                 : 'ex. +33 6 12 34 56 78',
  'personal_hint_location'              : 'ex. Paris, France',
  'personal_hint_location_brut'         : 'ex. Paris',
  'personal_hint_website'               : 'ex. github.com/mariedupont',
  'personal_hint_website_brut'          : 'ex. github.com/marie',
  'personal_hint_linkedin'              : 'ex. linkedin.com/in/mariedupont',
  'personal_hint_linkedin_brut'         : 'ex. linkedin.com/in/marie',
  'personal_summary_hint_label'         : 'Soyez concis — ceci apparaît en haut de votre CV.',
  'personal_hint_summary'               : 'Un bref résumé de 2 à 3 phrases sur votre parcours et vos objectifs...',
  'personal_validator_email'            : 'Saisissez une adresse e-mail valide',
  'personal_field_char_limit_tooltip'   : 'Limite de caractères atteinte',
  'personal_sheet_btn_save'             : 'Enregistrer le Profil',
  'personal_sheet_btn_update'           : 'Enregistrer les Modifications',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Choisir une Photo',
  'photo_option_gallery'                : 'Choisir depuis la Galerie',
  'photo_option_camera'                 : 'Prendre une Photo',
  'photo_option_reposition'             : 'Repositionner la Photo',
  'photo_option_remove'                 : 'Supprimer la Photo',
  'photo_status_added'                  : 'Photo ajoutée ✓',
  'photo_status_empty'                  : 'Ajoutez une photo professionnelle',
  'photo_chip_gallery'                  : 'Galerie',
  'photo_chip_camera'                   : 'Appareil Photo',
  'photo_chip_reposition'               : 'Repositionner',
  'photo_reposition_title'              : 'Repositionner la Photo',
  'photo_reposition_sub'                : 'Faites glisser la photo pour ajuster la position',
  'photo_reposition_reset'              : 'Réinitialiser au centre',
  'photo_reposition_apply'              : 'Appliquer',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Compétences',
  'skills_subtitle'                     : 'Mettez en valeur vos aptitudes clés',
  'skills_add_btn'                      : 'Ajouter une Nouvelle Compétence',
  'skills_snack_max_icons'              : 'Maximum de 10 icônes sélectionnées.',
  'skills_snack_max_skills'             : 'Maximum de 15 compétences atteint.',
  'skills_library_title'                : 'Compétences Enregistrées',
  'skills_library_hint'                 : 'Les compétences cochées sont incluses dans ce CV. Vos sélections sont enregistrées automatiquement.',
  'skills_nav_next'                     : 'Continuer vers Complémentaire',
  'skills_wina_header_icon_bar'         : 'Barre d\'Icônes d\'En-tête',
  'skills_wina_on'                      : 'ACT.',
  'skills_wina_off'                     : 'DÉS.',
  'skills_wina_bar_on_sub'              : 'Cercles d\'icônes colorés affichés dans l\'en-tête du CV.',
  'skills_wina_bar_off_sub'             : 'Rangée d\'icônes masquée — plus d\'espace pour les coordonnées.',
  'skills_wina_palette_hint'            : 'Les icônes apparaissent sous forme de cercles colorés dans l\'ordre de la palette.',
  'skills_wina_preview_label'           : 'Aperçu',
  'skills_wina_disabled_hint'           : 'Activez la barre d\'icônes ci-dessus pour choisir les icônes qui apparaissent dans l\'en-tête du CV.',
  'skills_sheet_title_add'              : 'Ajouter une Compétence',
  'skills_sheet_title_edit'             : 'Modifier la Compétence',
  'skills_sheet_field_name'             : 'Nom de la Compétence *',
  'skills_sheet_hint_short'             : 'ex. Flutter, Design',
  'skills_sheet_hint_long'              : 'ex. Flutter, Gestion de Projet',
  'skills_sheet_validator_max'          : 'Max. {n} caractères',
  'skills_sheet_proficiency'            : 'Niveau de Maîtrise',
  'skills_sheet_beginner'               : 'Débutant',
  'skills_sheet_expert'                 : 'Expert',
  'skills_sheet_btn_save'               : 'Enregistrer la Compétence',
  'skills_sheet_btn_update'             : 'Mettre à Jour la Compétence',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Références Personnelles',
  'refs_subtitle'                       : 'Personnes pouvant vous recommander personnellement',
  'refs_add_btn'                        : 'Ajouter une Nouvelle Référence Personnelle',
  'refs_snack_max_selected'             : 'Maximum de 4 références pouvant être sélectionnées pour un CV.',
  'refs_snack_max_saved'                : 'Maximum de 10 références enregistrées atteint.',
  'refs_library_title'                  : 'Références Enregistrées',
  'refs_library_hint'                   : 'Les références cochées sont incluses dans ce CV. Max. 4 par CV. Vos sélections sont enregistrées automatiquement.',
  'refs_nav_next'                       : 'Continuer vers Personnaliser',
  'refs_sheet_title_add'                : 'Ajouter une Référence Personnelle',
  'refs_sheet_title_edit'               : 'Modifier la Référence Personnelle',
  'refs_sheet_sub_add'                  : 'Quelqu\'un pouvant vous recommander personnellement auprès des employeurs.',
  'refs_sheet_sub_edit'                 : 'Mettez à jour les informations de cette référence ci-dessous.',
  'refs_sheet_field_name'               : 'Nom Complet *',
  'refs_sheet_field_title'              : 'Intitulé du Poste *',
  'refs_sheet_field_company'            : 'Entreprise (facultatif)',
  'refs_sheet_field_email'              : 'Adresse E-mail *',
  'refs_sheet_field_phone'              : 'Numéro de Téléphone *',
  'refs_sheet_hint_name'                : 'ex. Jean Martin',
  'refs_sheet_hint_title'               : 'ex. Responsable Ingénierie',
  'refs_sheet_hint_company'             : 'ex. Acme SA',
  'refs_sheet_hint_email'               : 'ex. jean@acme.fr',
  'refs_sheet_hint_phone'               : 'ex. +33 6 12 34 56 78',
  'refs_sheet_validator_email'          : 'Saisissez une adresse e-mail valide',
  'refs_sheet_btn_save'                 : 'Enregistrer la Référence Personnelle',
  'refs_sheet_btn_update'               : 'Mettre à Jour la Référence Personnelle',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Expérience Professionnelle',
  'exp_subtitle'                        : 'Ajoutez votre parcours professionnel',
  'exp_banner_info'                     : 'Jusqu\'à {n} responsabilités par poste apparaîtront sur le CV. 3 à 6 postes tiennent généralement sur 1 à 2 pages.',
  'exp_add_btn'                         : 'Ajouter une Nouvelle Expérience',
  'exp_snack_max_selected'              : 'Maximum de 8 expériences pouvant être sélectionnées pour un CV.',
  'exp_snack_max_saved'                 : 'Maximum de 12 expériences enregistrées atteint.',
  'exp_library_title'                   : 'Expériences Enregistrées',
  'exp_library_hint'                    : 'Les entrées cochées sont incluses dans ce CV uniquement. Les autres CV conservent leurs propres sélections indépendantes.',
  'exp_nav_next'                        : 'Continuer vers Formation',
  'exp_empty_message'                   : 'Aucune expérience ajoutée',
  'exp_empty_sub'                       : 'Appuyez ci-dessus pour ajouter votre premier poste',
  'exp_card_resp_singular'              : 'responsabilité',
  'exp_card_resp_plural'                : 'responsabilités',
  'exp_card_resp_tooltip'               : 'Seules les 8 premières responsabilités apparaîtront sur le CV',
  'exp_sheet_title_add'                 : 'Ajouter une Expérience',
  'exp_sheet_title_edit'                : 'Modifier l\'Expérience',
  'exp_sheet_field_job_title'           : 'Intitulé du Poste *',
  'exp_sheet_field_company'             : 'Entreprise *',
  'exp_sheet_field_location'            : 'Localisation',
  'exp_sheet_section_responsibilities'  : 'Responsabilités Clés',
  'exp_sheet_resp_hint_info'            : 'Max. 8 points · 200 caractères chacun',
  'exp_sheet_resp_label'                : 'Responsabilité {n}',
  'exp_sheet_resp_hint'                 : 'ex. Dirigé une équipe de 5 ingénieurs',
  'exp_sheet_resp_add_btn'              : 'Ajouter une Responsabilité',
  'exp_sheet_resp_max_info'             : 'Maximum de {n} responsabilités atteint',
  'exp_sheet_resp_validator_max'        : 'Max. 200 caractères',
  'exp_sheet_hint_job_title'            : 'ex. Développeur Senior',
  'exp_sheet_hint_location'             : 'ex. Paris, France',
  'exp_sheet_btn_save'                  : 'Enregistrer l\'Expérience',
  'exp_sheet_btn_update'                : 'Enregistrer les Modifications',
  'exp_date_present'                    : 'Présent / Poste Actuel',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Formation',
  'edu_subtitle'                        : 'Ajoutez votre parcours académique',
  'edu_add_btn'                         : 'Ajouter une Nouvelle Formation',
  'edu_snack_max_selected'              : 'Maximum de 8 formations pouvant être sélectionnées pour un CV.',
  'edu_snack_max_saved'                 : 'Maximum de 12 formations enregistrées atteint.',
  'edu_library_title'                   : 'Formations Enregistrées',
  'edu_library_hint'                    : 'Les entrées cochées sont incluses dans ce CV. Vos sélections sont enregistrées automatiquement.',
  'edu_nav_next'                        : 'Continuer vers Compétences',
  'edu_empty_message'                   : 'Aucune formation ajoutée',
  'edu_empty_sub'                       : 'Appuyez ci-dessus pour ajouter vos diplômes',
  'edu_card_bullet_singular'            : 'point clé',
  'edu_card_bullet_plural'              : 'points clés',
  'edu_sheet_title_add'                 : 'Ajouter une Formation',
  'edu_sheet_title_edit'                : 'Modifier la Formation',
  'edu_sheet_field_degree'              : 'Diplôme / Qualification *',
  'edu_sheet_field_institution'         : 'Établissement *',
  'edu_sheet_section_key_points'        : 'Points Clés',
  'edu_sheet_key_points_hint_info'      : 'Facultatif · 1 point · 100 caractères max.',
  'edu_sheet_point_label'               : 'Point {n}',
  'edu_sheet_point_add_btn'             : 'Ajouter un Point Clé',
  'edu_sheet_point_max_info'            : 'Maximum de {n} points atteint',
  'edu_sheet_point_validator_max'       : 'Max. {n} caractères',
  'edu_sheet_hint_degree'               : 'ex. Licence en Informatique',
  'edu_sheet_hint_institution'          : 'ex. Université Paris-Saclay',
  'edu_sheet_hint_bullet'               : 'ex. Major de Promotion',
  'edu_sheet_btn_save'                  : 'Enregistrer la Formation',
  'edu_sheet_btn_update'                : 'Enregistrer les Modifications',
  'edu_date_present'                    : 'Présent / Études en Cours',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Informations Complémentaires',
  'additional_subtitle'                 : 'Certifications, langues et plus',
  'additional_cert_section_title'       : 'Certifications',
  'additional_cert_counter'             : '{sel}/{total} sélectionnées · max. {max}',
  'additional_cert_hide'                : 'Masquer',
  'additional_cert_show'                : 'Afficher',
  'additional_cert_add_btn'             : 'Ajouter',
  'additional_cert_snack_max'           : 'Maximum de {n} certifications atteint.',
  'additional_cert_hint'                : 'Les entrées cochées sont incluses dans ce CV. Vos sélections sont enregistrées automatiquement.',
  'additional_cert_empty'               : 'Aucune certification ajoutée',
  'additional_lang_section_title'       : 'Langues',
  'additional_lang_add_hint'            : 'ex. Espagnol',
  'additional_lang_snack_max'           : 'Maximum de {n} langues atteint.',
  'additional_lang_empty'               : 'Aucune langue ajoutée',
  'additional_hobby_section_title'      : 'Loisirs et Centres d\'Intérêt',
  'additional_hobby_add_hint'           : 'ex. Photographie',
  'additional_hobby_snack_max'          : 'Maximum de {n} loisirs atteint.',
  'additional_hobby_empty'              : 'Aucun loisir ajouté',
  'additional_section_hint'             : 'Les entrées cochées sont incluses dans ce CV. Vos sélections sont enregistrées automatiquement.',
  'additional_nav_next'                 : 'Continuer vers les Références',
  'cert_sheet_title_add'                : 'Ajouter une Certification',
  'cert_sheet_title_edit'               : 'Modifier la Certification',
  'cert_sheet_sub'                      : 'Ajoutez une qualification, un certificat ou une accréditation professionnelle.',
  'cert_sheet_field_name'               : 'Nom de la Certification *',
  'cert_sheet_field_issued_by'          : 'Délivré Par (facultatif)',
  'cert_sheet_field_short_desc'         : 'Courte Description (facultatif)',
  'cert_sheet_hint_name'                : 'ex. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'ex. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'ex. Obtenu en 2024',
  'cert_sheet_btn_save'                 : 'Enregistrer la Certification',
  'cert_sheet_btn_update'               : 'Mettre à Jour la Certification',
  'simple_sheet_title_add_language'     : 'Ajouter une Langue',
  'simple_sheet_title_edit_language'    : 'Modifier la Langue',
  'simple_sheet_title_add_hobby'        : 'Ajouter un Loisir',
  'simple_sheet_title_edit_hobby'       : 'Modifier le Loisir',
  'simple_sheet_btn_save'               : 'Enregistrer',
  'simple_sheet_btn_update'             : 'Mettre à Jour',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contact',
  'pdf_section_about_me'                : 'À Propos de Moi',
  'pdf_section_summary'                 : 'Résumé',
  'pdf_section_summary_short'           : 'Résumé',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Expérience',
  'pdf_section_experience_short'        : 'Expérience',
  'pdf_section_education'               : 'Formation',
  'pdf_section_skills'                  : 'Compétences',
  'pdf_section_languages'               : 'Langues',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Téléphone',
  'pdf_label_location'                  : 'Localisation',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Limite de CV Atteinte',
  'limit_dialog_body'                   : 'Vous avez atteint le maximum de 30 CV. Veuillez supprimer un CV existant avant d\'en créer un nouveau.',
  'limit_dialog_go_to_my_cvs'           : 'Accéder à Mes CV',
  'limit_dialog_cancel'                 : 'Annuler',
  'refs_count_summary'                  : '{checked}/{maxChecked} sélectionnées · {saved}/{maxSaved} enregistrées',
  'refs_selected_badge'                 : '{n} sélectionnée(s)',
  'refs_empty_message'                  : 'Aucune référence enregistrée pour l\'instant',
  'refs_empty_sub'                      : 'Appuyez ci-dessus pour ajouter une référence personnelle',
};