// lib/language_keys/lang_pt_br_brazilian.dart
//
// Portuguese (Brazil) — translation map.

const Map<String, String> ptBrBrazilian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nenhum idioma encontrado',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Pular',
  'onboarding_next'                     : 'Próximo',
  'onboarding_get_started'              : 'Começar',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Bem-vindo',
  'ob1_title'                           : 'Crie um Currículo Que\nAbre Portas',
  'ob1_body'                            : 'Destaque-se entre centenas de candidatos. Crie um currículo polido e vencedor em minutos — sem precisar de habilidades em design.',
  'ob1_pill_label'                      : 'Criador de Currículo Profissional',
  'ob1_chip_templates'                  : '24+ Modelos',
  'ob1_chip_pdf'                        : 'Exportar PDF',
  'ob1_chip_free'                       : 'Gratuito',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Modelos',
  'ob2_title'                           : 'Todo Setor.\nToda Ambição.',
  'ob2_body'                            : 'De layouts corporativos a designs criativos marcantes — um modelo que conta a sua história.',
  'ob2_tap_hint'                        : 'Toque em qualquer modelo para visualizar',
  'ob2_tpl_executive'                   : 'Executivo',
  'ob2_tpl_vibrant'                     : 'Vibrante',
  'ob2_tpl_nordic'                      : 'Nórdico',
  'ob2_tpl_tech_dark'                   : 'Tech Escuro',
  'ob2_tpl_luxury'                      : 'Luxo',
  'ob2_tag_corporate'                   : 'Corporativo',
  'ob2_tag_creative'                    : 'Criativo',
  'ob2_tag_minimal'                     : 'Minimalista',
  'ob2_tag_modern'                      : 'Moderno',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Layout Inteligente',
  'ob3_title'                           : 'Seu Currículo.\nPerfeitamente Organizado.',
  'ob3_body'                            : 'O Layout Inteligente reorganiza suas seções para máximo impacto — colocando seu melhor conteúdo onde os recrutadores olham primeiro.',
  'ob3_badge_smart_layout'              : 'Layout Inteligente',
  'ob3_badge_cv_ready'                  : 'Currículo Pronto!',
  'ob3_step1_label'                     : 'Escolha um Modelo',
  'ob3_step1_desc'                      : 'Escolha entre 24+ designs incríveis.',
  'ob3_step2_label'                     : 'Preencha seus Dados',
  'ob3_step2_desc'                      : 'Campos guiados para todas as seções.',
  'ob3_step3_label'                     : 'Layout Inteligente',
  'ob3_step3_desc'                      : 'Um toque reorganiza seu currículo perfeitamente.',
  'ob3_step4_label'                     : 'Exportar como PDF',
  'ob3_step4_desc'                      : 'PDF perfeito pronto para enviar.',
  'ob3_section_work'                    : 'Experiência Profissional',
  'ob3_section_education'               : 'Educação',
  'ob3_section_skills'                  : 'Habilidades',
  'ob3_section_references'              : 'Referências',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Pronto para Começar',
  'ob4_title'                           : 'Por Que os Melhores Candidatos\nEscolhem o CV Builder',
  'ob4_visual_headline'                 : 'Tudo Pronto!',
  'ob4_visual_subline'                  : 'Tudo que você precisa para conseguir o emprego.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Modelos',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Máx. Currículos',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Exportação',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privado',
  'ob4_hl1_title'                       : 'Privado e Seguro',
  'ob4_hl1_sub'                         : 'Dados ficam no seu dispositivo.',
  'ob4_hl2_title'                       : 'Salvamento Automático',
  'ob4_hl2_sub'                         : 'Cada tecla salva instantaneamente.',
  'ob4_hl3_title'                       : 'Até 30 Currículos',
  'ob4_hl3_sub'                         : 'Currículo único para cada vaga.',
  'ob4_hl4_title'                       : 'Compartilhar com Um Toque',
  'ob4_hl4_sub'                         : 'Envie o PDF sem sair do app.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Destaque-se na multidão',
  'home_hero_title'                     : 'Crie Seu\nCurrículo Profissional',
  'home_hero_sub'                       : 'Monte um currículo impressionante\nem minutos',
  'home_hero_cta'                       : 'Começar a Criar',
  'home_premium_soon'                   : 'Upgrade para Pro em breve!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Mais Recentes',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Última Edição',
  'history_sort_by_template'            : 'Por Modelo',
  'history_sort_sheet_title'            : 'Ordenar Por',
  'history_sort_alphabetical_full'      : 'Alfabético (A–Z)',
  'history_premium_soon'                : 'Upgrade para Pro em breve!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Configurações',
  'settings_section_preferences'        : 'Preferências',
  'settings_section_support'            : 'Suporte',
  'settings_section_legal'              : 'Legal',
  'settings_section_about'              : 'Sobre',
  'settings_language_tile_title'        : 'Idioma',
  'settings_dark_mode_title'            : 'Modo Escuro',
  'settings_dark_mode_on'               : 'Tema escuro ativado',
  'settings_dark_mode_off'              : 'Tema claro ativado',
  'settings_help_faq_title'             : 'Ajuda e Perguntas Frequentes',
  'settings_help_faq_sub'               : 'Perguntas comuns respondidas',
  'settings_contact_support_title'      : 'Contatar Suporte',
  'settings_rate_app_title'             : 'Avaliar o App',
  'settings_rate_app_sub'               : 'Está gostando do app? Deixe uma avaliação!',
  'settings_privacy_policy_title'       : 'Política de Privacidade',
  'settings_terms_title'                : 'Termos de Serviço',
  'settings_app_version_title'          : 'Versão do App',
  'settings_email_error'                : 'Não foi possível abrir o e-mail. Por favor, envie um e-mail para cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Visualização do Currículo',
  'preview_header_sub'                  : 'Pronto para exportar',
  'preview_generating'                  : 'Gerando seu currículo...',
  'preview_failed_title'                : 'Falha na Visualização',
  'preview_failed_error'                : 'Erro: {error}',
  'preview_go_back'                     : 'Voltar',
  'preview_no_data'                     : 'Nenhum dado disponível',
  'preview_btn_print'                   : 'Imprimir',
  'preview_btn_download'                : 'Baixar e Compartilhar',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Ajuda e Perguntas Frequentes',
  'faq_category_all'                    : 'Todos',
  'faq_empty'                           : 'Nenhum resultado encontrado',
  'faq_contact_headline'                : 'Ainda precisa de ajuda?',
  'faq_contact_sub'                     : 'Nossa equipe está aqui para você.',
  'faq_contact_btn'                     : 'Contato',
  'faq_email_error'                     : 'Não foi possível abrir o e-mail. Por favor, envie um e-mail para cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Primeiros Passos',
  'faq_cat_templates'                   : 'Modelos',
  'faq_cat_editing'                     : 'Edição',
  'faq_cat_exporting'                   : 'Exportação',
  'faq_cat_data_privacy'                : 'Dados e Privacidade',
  'faq_cat_troubleshooting'             : 'Solução de Problemas',
  'faq_q1'  : 'Como crio meu primeiro currículo?',
  'faq_a1'  : 'Toque no botão "+" na tela inicial para começar um novo currículo. Escolha um modelo que combine com seu estilo, depois preencha seus dados pessoais, experiência profissional, educação e habilidades passo a passo. Seu progresso é salvo automaticamente.',
  'faq_q2'  : 'Posso criar mais de um currículo?',
  'faq_a2'  : 'Sim! Você pode criar vários currículos para diferentes cargos ou setores. Cada currículo é salvo separadamente, para que você possa personalizá-los para candidaturas específicas.',
  'faq_q3'  : 'Como mudo o modelo do meu currículo?',
  'faq_a3'  : 'Abra seu currículo, toque no ícone de modelo no topo da tela e navegue pelos modelos disponíveis. Toque em qualquer modelo para visualizá-lo com seu conteúdo atual. Confirme para aplicar.',
  'faq_q4'  : 'Há modelos gratuitos e premium?',
  'faq_a4'  : 'Sim. Uma seleção de modelos profissionais está disponível gratuitamente. Modelos premium com designs avançados e paletas de cores estão disponíveis mediante compra única ou assinatura.',
  'faq_q5'  : 'Como adiciono ou removo seções?',
  'faq_a5'  : 'No editor de currículo, role até o final da tela e toque em "Adicionar Seção" para incluir extras como Idiomas, Certificações ou Trabalho Voluntário. Para remover uma seção, toque no cabeçalho da seção e selecione "Remover".',
  'faq_q6'  : 'Como reordeno as seções?',
  'faq_a6'  : 'Pressione e segure a alça de arrastar (≡) ao lado de qualquer cabeçalho de seção e arraste para a posição desejada. As alterações são salvas automaticamente.',
  'faq_q7'  : 'Como exporto meu currículo como PDF?',
  'faq_a7'  : 'Abra seu currículo e toque no botão de exportar (ícone de compartilhar) no canto superior direito. Selecione "Exportar como PDF". Você pode salvar no dispositivo, compartilhar por e-mail, WhatsApp ou enviar diretamente para vagas de emprego.',
  'faq_q8'  : 'Quais formatos de arquivo são suportados?',
  'faq_a8'  : 'Atualmente o app suporta exportação do seu currículo em PDF de alta qualidade. Formatos adicionais podem ser adicionados em atualizações futuras.',
  'faq_q9'  : 'Onde estão armazenados os dados do meu currículo?',
  'faq_a9'  : 'Todos os dados do seu currículo são armazenados localmente no seu dispositivo. Não enviamos suas informações pessoais para nossos servidores. Isso significa que seus dados permanecem privados e acessíveis offline.',
  'faq_q10' : 'Como faço backup dos meus currículos?',
  'faq_a10' : 'Seus currículos estão incluídos no backup padrão do seu dispositivo (backup do Google Drive no Android, iCloud no iOS) se você tiver o backup ativado nas configurações do dispositivo. Você também pode exportar currículos individuais como PDF para manter uma cópia.',
  'faq_q11' : 'O app está lento. O que devo fazer?',
  'faq_a11' : 'Tente fechar e reabrir o app. Se o problema persistir, reinicie seu dispositivo. Certifique-se de ter a versão mais recente do app instalada da Play Store / App Store.',
  'faq_q12' : 'Meu currículo não está exportando corretamente. O que devo fazer?',
  'faq_a12' : 'Certifique-se de ter espaço de armazenamento suficiente no dispositivo. Tente reduzir imagens grandes no seu currículo. Se o problema continuar, entre em contato com nossa equipe de suporte.',
  'faq_q13' : 'Esqueci de salvar — perdi meu trabalho?',
  'faq_a13' : 'De jeito nenhum! O app salva seu progresso continuamente enquanto você edita.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Sua carreira, aperfeiçoada',
  'header_tooltip_back'                 : 'Voltar',
  'header_tooltip_my_cvs'               : 'Meus Currículos',
  'header_tooltip_settings'             : 'Configurações',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Meus Currículos',
  'saved_count_single'                  : '{n} documento',
  'saved_count_plural'                  : '{n} documentos',
  'saved_limit_reached'                 : 'Limite atingido',
  'saved_footer_count'                  : '{n} / 30 Currículos',
  'saved_filter_all'                    : 'Todos',
  'saved_filter_draft'                  : 'Rascunho',
  'saved_filter_complete'               : 'Completo',
  'saved_status_complete'               : 'Completo',
  'saved_status_saved'                  : 'Salvo',
  'saved_status_draft'                  : 'Rascunho',
  'saved_empty_title'                   : 'Nenhum currículo aqui ainda',
  'saved_empty_sub'                     : 'Comece a criar seu primeiro currículo acima',
  'saved_search_empty_title'            : 'Nenhum resultado encontrado',
  'saved_search_empty_sub'              : 'Tente um termo de busca diferente',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Esquema de Cores',
  'custom_font_settings_title'          : 'Configurações de Fonte',
  'custom_font_family_label'            : 'Família de Fonte',
  'custom_font_size_label'              : 'Tamanho da Fonte: ',
  'custom_current_template_title'       : 'Modelo Atual',
  'custom_change_template_btn'          : 'Trocar Modelo',
  'custom_tpl_modern'                   : 'Moderno',
  'custom_tpl_classic'                  : 'Clássico',
  'custom_tpl_professional'             : 'Profissional',
  'custom_tpl_creative'                 : 'Criativo',
  'custom_tpl_minimal'                  : 'Minimalista',
  'custom_tpl_modern_desc'              : 'Design limpo e contemporâneo',
  'custom_tpl_classic_desc'             : 'Layout profissional tradicional',
  'custom_tpl_professional_desc'        : 'Modelo focado em negócios',
  'custom_tpl_creative_desc'            : 'Destaque-se com design único',
  'custom_tpl_minimal_desc'             : 'Estilo simples e elegante',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Escolher Modelo',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executivo',
  'tpl_nordic_name'                     : 'Nórdico',
  'tpl_vibrant_name'                    : 'Vibrante',
  'tpl_tech_dark_name'                  : 'Tech Escuro',
  'tpl_luxury_name'                     : 'Luxo',
  'tpl_executive_tag'                   : 'Mais Popular',
  'tpl_nordic_tag'                      : 'Limpo',
  'tpl_vibrant_tag'                     : 'Criativo',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Marcante e autoritário para cargos sênior',
  'tpl_nordic_desc'                     : 'Clareza minimalista confiada pelas melhores empresas',
  'tpl_vibrant_desc'                    : 'Destaque-se com energia e cor',
  'tpl_tech_dark_desc'                  : 'Estética de terminal para desenvolvedores',
  'tpl_luxury_desc'                     : 'Prestígio com acentos dourados em preto',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Modelo',
  'detail_step_personal'                : 'Pessoal',
  'detail_step_experience'              : 'Experiência',
  'detail_step_education'               : 'Educação',
  'detail_step_skills'                  : 'Habilidades',
  'detail_step_additional'              : 'Adicional',
  'detail_step_references'              : 'Referências',
  'detail_step_customize'               : 'Personalizar',
  'detail_banner_heading'               : 'Quase lá!',
  'detail_banner_btn'                   : 'Continuar',
  'detail_banner_completion_label'      : 'Conclusão',
  'detail_stat_created_label'           : 'Criado',
  'detail_stat_steps_label'             : 'Etapas concluídas',
  'detail_section_template_style'       : 'Estilo do Modelo',
  'detail_section_steps'                : 'Etapas',
  'detail_steps_counter'                : '{done} de {total} concluídas',
  'detail_step_sub'                     : 'Etapa {n} de {total}',
  'detail_section_activity'             : 'Atividade',
  'detail_activity_created'             : 'Criado',
  'detail_activity_last_edited'         : 'Última Edição',
  'detail_activity_template'            : 'Modelo',
  'detail_btn_continue_editing'         : 'Continuar Editando',
  'detail_btn_edit_cv'                  : 'Editar Currículo',
  'detail_option_rename'                : 'Renomear Currículo',
  'detail_option_delete'                : 'Excluir Currículo',
  'detail_rename_title'                 : 'Renomear Currículo',
  'detail_rename_hint'                  : 'ex. Currículo Engenheiro de Software',
  'detail_rename_error_empty'           : 'O nome não pode estar vazio',
  'detail_rename_btn_cancel'            : 'Cancelar',
  'detail_rename_btn_save'              : 'Salvar',
  'detail_rename_snackbar'              : 'Renomeado para "{name}"',
  'detail_delete_title'                 : 'Excluir Currículo?',
  'detail_delete_body'                  : 'Isso excluirá permanentemente "{name}". Esta ação não pode ser desfeita.',
  'detail_delete_btn_cancel'            : 'Cancelar',
  'detail_delete_btn_confirm'           : 'Excluir',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Concluído',
  'detail_check_tile_incomplete'        : 'Ainda não preenchido',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Escolha seu Modelo',
  'chooser_subtitle'                    : 'Deslize para navegar  ·  Toque para selecionar  ·  Segure para visualizar',
  'chooser_card_hold_hint'              : 'Segure para visualizar',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Selecionado',
  'chooser_modal_heading'               : 'Nomeie seu Currículo',
  'chooser_modal_sub'                   : 'Dê um nome para encontrá-lo facilmente em Meus Currículos e Histórico.',
  'chooser_modal_field_label'           : 'Nome do Currículo',
  'chooser_modal_save_btn'              : 'Salvar e Começar a Criar',
  'chooser_modal_divider'               : 'ou continuar um currículo existente',
  'chooser_nav_selected_sub'            : 'Modelo selecionado',
  'chooser_nav_cta'                     : 'Salvar e Continuar',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Limite Máximo de Entradas Atingido',
  'editor_show_hide'                    : 'Mostrar/Ocultar',
  'editor_editing_badge'                : 'Editando',
  'editor_field_required'               : 'Obrigatório',
  'editor_tooltip_edit'                 : 'Editar',
  'editor_tooltip_delete'               : 'Excluir',
  'editor_date_start'                   : 'Data de Início *',
  'editor_date_end'                     : 'Data de Término *',
  'editor_date_tap_hint'                : 'Toque para selecionar',
  'editor_date_dialog_title'            : 'Selecione Mês e Ano',
  'editor_date_confirm'                 : 'Confirmar',
  'editor_panel_hide'                   : 'Ocultar',
  'editor_panel_show'                   : 'Mostrar',
  'editor_validator_max_chars'          : 'Máximo de {n} caracteres',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Criar seu Currículo',
  'editor_header_step_sub'              : 'Etapa {current} de {total} · {label}',
  'editor_step_template'                : 'Modelo',
  'editor_step_personal'                : 'Pessoal',
  'editor_step_experience'              : 'Experiência',
  'editor_step_education'               : 'Educação',
  'editor_step_skills'                  : 'Habilidades',
  'editor_step_additional'              : 'Adicional',
  'editor_step_references'              : 'Referências',
  'editor_step_customize'               : 'Personalizar',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personalizar',
  'customize_subtitle'                  : 'Torne seu currículo único',
  'customize_smart_layout_btn'          : 'Layout Inteligente',
  'customize_back_to_top'               : 'Voltar ao Topo',
  'customize_done_title'                : 'Tudo pronto!',
  'customize_done_sub'                  : 'Toque em Visualizar Currículo abaixo para ver seu currículo finalizado',
  'customize_preview_btn'               : 'Visualizar Currículo',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Esquema de Cores',
  'color_black'                         : 'Preto',
  'color_blue'                          : 'Azul',
  'color_nordic_blue'                   : 'Azul Nórdico',
  'color_indigo'                        : 'Índigo',
  'color_teal'                          : 'Verde-azulado',
  'color_green'                         : 'Verde',
  'color_purple'                        : 'Roxo',
  'color_orange'                        : 'Laranja',
  'color_red'                           : 'Vermelho',
  'color_executive_gold'                : 'Dourado Executivo',
  'color_vibrant_coral'                 : 'Coral Vibrante',
  'color_white'                         : 'Branco',
  'color_white_bg'                      : 'Fundo Branco',
  'color_maroon'                        : 'Bordô',
  'color_brutalist_yellow'              : 'Amarelo Brutalista',
  'color_neon_blue'                     : 'Azul Neon',
  'color_blueprint_navy'                : 'Azul-marinho Blueprint',
  'color_light_grey'                    : 'Cinza Claro',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Família de Fonte',
  'customize_font_picker_title'         : 'Escolher Fonte',
  'customize_font_picker_sub'           : 'Cada fonte é visualizada em seu próprio tipo',
  'customize_font_preview_sample'       : 'A raposa marrom saltou',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Tamanho da Fonte',
  'customize_font_size_label'           : 'Tamanho do Texto',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Tamanho da Imagem',
  'customize_image_size_label'          : 'Tamanho da Imagem',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Visualização ao Vivo',
  'preview_page_count_singular'         : '1 página',
  'preview_page_count_plural'           : '{n} páginas',
  'preview_page_of'                     : 'Página {page} de {total}',
  'preview_live_hint'                   : 'Alterações aplicadas instantaneamente',
  'preview_template_unregistered'       : 'Ainda não registrado em customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Preparando seu currículo…',
  'preview_bar_print'                   : 'Imprimir',
  'preview_bar_save_pdf'                : 'Salvar como PDF',
  'preview_bar_share'                   : 'Compartilhar',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Visualização do Currículo',
  'preview_screen_sub'                  : '{n} {unit} · exatamente como impresso',
  'preview_page_singular'               : 'página',
  'preview_page_plural'                 : 'páginas',
  'preview_pdf_filename'                : 'Meu_Curriculo',
  'preview_share_subject'               : 'Meu Currículo',
  'preview_snack_print_failed'          : 'Impressão falhou: {e}',
  'preview_snack_saved'                 : 'Currículo salvo em Downloads ✓',
  'preview_snack_export_failed'         : 'Exportação falhou: {e}',
  'preview_snack_share_failed'          : 'Compartilhamento falhou: {e}',
  'preview_template_not_registered'     : 'Modelo não registrado',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Fechar visualização',
  'preview_modal_hint_photo'            : 'Suporta foto de perfil  ·  Toque em um cartão para selecionar',
  'preview_modal_hint_no_photo'         : 'Toque em um cartão de modelo para selecioná-lo',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Meu Currículo',
  'time_just_now'                       : 'Agora mesmo',
  'time_minutes_ago'                    : 'Há {n}min',
  'time_hours_ago'                      : 'Há {n}h',
  'time_yesterday'                      : 'Ontem',
  'time_days_ago'                       : 'Há {n} dias',
  'time_one_week_ago'                   : 'Há 1 semana',
  'time_weeks_ago'                      : 'Há {n} semanas',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegante',
  'tpl_tag_classic'                     : 'Clássico',
  'tpl_tag_minimal'                     : 'Minimalista',
  'tpl_tag_creative'                    : 'Criativo',
  'tpl_tag_bold'                        : 'Ousado',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradiente',
  'tpl_gradient_desc'                   : 'Cartões em gradiente de verde-azulado a violeta',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Estilo revista em vermelho e creme',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Suave',
  'tpl_pastel_soft_desc'                : 'Barra lateral lavanda, cartões suaves',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalista',
  'tpl_brutalist_desc'                  : 'Grade bruta, bordas marcantes e amarelo',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Esmeralda',
  'tpl_emerald_desc'                    : 'Verde floresta com linha do tempo',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infográfico',
  'tpl_infographic_desc'                : 'Tela escura com gráficos circulares',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Déco',
  'tpl_art_deco_desc'                   : 'Luxo geométrico dourado dos anos 1920',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Escuro',
  'tpl_wina_dark_desc'                  : 'Infográfico escuro com anéis',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Laranja',
  'tpl_rio_orange_desc'                 : 'Barra lateral escura com destaque em laranja',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Verão',
  'tpl_summer_desc'                     : 'Minimalista limpo, tons de cinza suave',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Tons elegantes em bege quente',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Clássico marcante em preto e branco',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Layout clássico compatível com ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Escuro',
  'tpl_tony_dark_desc'                  : 'Estilo infográfico laranja escuro',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Moda',
  'tpl_fashion_desc'                    : 'Desenho técnico em grade',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arquivista',
  'tpl_archivist_desc'                  : 'Layout clássico em duas colunas com etiquetas',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomata',
  'tpl_diplomat_desc'                   : 'Cabeçalhos sombreados com marcadores em losango',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridiano',
  'tpl_meridian_desc'                   : 'Cabeçalhos centralizados, empresas em destaque',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Impulso',
  'tpl_momentum_desc'                   : 'Nome em destaque, pontos de linha do tempo e conquistas',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informações Pessoais',
  'personal_subtitle'                   : 'Apresente-se aos empregadores',
  'personal_profile_counter'            : '{n}/{max} perfis',
  'personal_info_banner'                : 'Salve até 5 perfis e selecione um por currículo. Sua seleção é lembrada para cada currículo separadamente.',
  'personal_snack_max'                  : 'Máximo de {n} perfis atingido.',
  'personal_add_btn'                    : 'Adicionar Novo Perfil',
  'personal_library_title'              : 'Perfis Salvos',
  'personal_selected_one'               : '1 selecionado',
  'personal_selected_none'              : 'nenhum selecionado',
  'personal_library_hint'               : 'Toque em um cartão para selecioná-lo somente para este currículo. Outros currículos mantêm suas próprias seleções independentes.',
  'personal_empty_message'              : 'Nenhum perfil salvo ainda',
  'personal_empty_sub'                  : 'Toque acima para adicionar suas informações pessoais',
  'personal_nav_next'                   : 'Salvar e Continuar',
  'personal_card_active_badge'          : 'Ativo para este currículo',
  'personal_sheet_title_add'            : 'Novo Perfil',
  'personal_sheet_title_edit'           : 'Editar Perfil',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTA',
  'personal_sheet_brutalist_banner'     : 'O modelo brutalista tem campos de contato compactos. Valores mais curtos (ex. somente cidade) ficam melhor.',
  'personal_section_photo'              : 'Foto de Perfil',
  'personal_section_basic'              : 'Dados Básicos',
  'personal_section_contact'            : 'Contato',
  'personal_section_online'             : 'Presença Online',
  'personal_section_summary'            : 'Resumo Profissional',
  'personal_field_first_name'           : 'Nome *',
  'personal_field_last_name'            : 'Sobrenome',
  'personal_field_job_title'            : 'Cargo *',
  'personal_field_email'                : 'Endereço de E-mail *',
  'personal_field_phone'                : 'Número de Telefone *',
  'personal_field_location'             : 'Localização',
  'personal_field_location_brut'        : 'Localização (somente cidade)',
  'personal_field_website'              : 'Site / Portfólio',
  'personal_field_linkedin'             : 'URL do LinkedIn',
  'personal_hint_first_name'            : 'ex. Ana',
  'personal_hint_last_name'             : 'ex. Silva',
  'personal_hint_job_title'             : 'ex. Engenheiro Sênior',
  'personal_hint_email'                 : 'ex. ana@exemplo.com',
  'personal_hint_phone'                 : 'ex. +55 11 91234-5678',
  'personal_hint_location'              : 'ex. São Paulo, Brasil',
  'personal_hint_location_brut'         : 'ex. São Paulo, SP',
  'personal_hint_website'               : 'ex. github.com/anasilva',
  'personal_hint_website_brut'          : 'ex. github.com/ana',
  'personal_hint_linkedin'              : 'ex. linkedin.com/in/anasilva',
  'personal_hint_linkedin_brut'         : 'ex. linkedin.com/in/ana',
  'personal_summary_hint_label'         : 'Seja conciso — isso aparece no topo do seu currículo.',
  'personal_hint_summary'               : 'Um breve resumo de 2–3 frases sobre seu histórico e objetivos...',
  'personal_validator_email'            : 'Insira um e-mail válido',
  'personal_field_char_limit_tooltip'   : 'Limite de caracteres atingido',
  'personal_sheet_btn_save'             : 'Salvar Perfil',
  'personal_sheet_btn_update'           : 'Salvar Alterações',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Escolher Foto',
  'photo_option_gallery'                : 'Escolher da Galeria',
  'photo_option_camera'                 : 'Tirar uma Foto',
  'photo_option_reposition'             : 'Reposicionar Foto',
  'photo_option_remove'                 : 'Remover Foto',
  'photo_status_added'                  : 'Foto adicionada ✓',
  'photo_status_empty'                  : 'Adicione uma foto profissional',
  'photo_chip_gallery'                  : 'Galeria',
  'photo_chip_camera'                   : 'Câmera',
  'photo_chip_reposition'               : 'Reposicionar',
  'photo_reposition_title'              : 'Reposicionar Foto',
  'photo_reposition_sub'                : 'Arraste a foto para ajustar a posição',
  'photo_reposition_reset'              : 'Centralizar',
  'photo_reposition_apply'              : 'Aplicar',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Habilidades',
  'skills_subtitle'                     : 'Destaque suas principais competências',
  'skills_add_btn'                      : 'Adicionar Nova Habilidade',
  'skills_snack_max_icons'              : 'Máximo de 10 ícones selecionados.',
  'skills_snack_max_skills'             : 'Máximo de 15 habilidades atingido.',
  'skills_library_title'                : 'Habilidades Salvas',
  'skills_library_hint'                 : 'Habilidades marcadas estão incluídas neste currículo. Suas seleções são salvas automaticamente.',
  'skills_nav_next'                     : 'Continuar para Adicional',
  'skills_wina_header_icon_bar'         : 'Barra de Ícones do Cabeçalho',
  'skills_wina_on'                      : 'LIGADO',
  'skills_wina_off'                     : 'DESLIGADO',
  'skills_wina_bar_on_sub'              : 'Círculos de ícones coloridos mostrados no cabeçalho do currículo.',
  'skills_wina_bar_off_sub'             : 'Linha de ícones oculta — mais espaço para informações de contato.',
  'skills_wina_palette_hint'            : 'Ícones aparecem como círculos coloridos na ordem da paleta.',
  'skills_wina_preview_label'           : 'Visualização',
  'skills_wina_disabled_hint'           : 'Ative a barra de ícones acima para escolher quais ícones aparecem no cabeçalho do currículo.',
  'skills_sheet_title_add'              : 'Adicionar Habilidade',
  'skills_sheet_title_edit'             : 'Editar Habilidade',
  'skills_sheet_field_name'             : 'Nome da Habilidade *',
  'skills_sheet_hint_short'             : 'ex. Flutter, Design',
  'skills_sheet_hint_long'              : 'ex. Flutter, Gestão de Projetos',
  'skills_sheet_validator_max'          : 'Máximo de {n} caracteres',
  'skills_sheet_proficiency'            : 'Nível de Proficiência',
  'skills_sheet_beginner'               : 'Iniciante',
  'skills_sheet_expert'                 : 'Especialista',
  'skills_sheet_btn_save'               : 'Salvar Habilidade',
  'skills_sheet_btn_update'             : 'Atualizar Habilidade',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referências Pessoais',
  'refs_subtitle'                       : 'Pessoas que podem recomendar você pessoalmente',
  'refs_add_btn'                        : 'Adicionar Nova Referência Pessoal',
  'refs_snack_max_selected'             : 'Máximo de 4 referências podem ser selecionadas para um currículo.',
  'refs_snack_max_saved'                : 'Máximo de 10 referências salvas atingido.',
  'refs_library_title'                  : 'Referências Salvas',
  'refs_library_hint'                   : 'Referências marcadas estão incluídas neste currículo. Máx. 4 por currículo. Suas seleções são salvas automaticamente.',
  'refs_nav_next'                       : 'Continuar para Personalizar',
  'refs_sheet_title_add'                : 'Adicionar Referência Pessoal',
  'refs_sheet_title_edit'               : 'Editar Referência Pessoal',
  'refs_sheet_sub_add'                  : 'Alguém que pode recomendá-lo pessoalmente aos empregadores.',
  'refs_sheet_sub_edit'                 : 'Atualize os dados desta referência abaixo.',
  'refs_sheet_field_name'               : 'Nome Completo *',
  'refs_sheet_field_title'              : 'Cargo *',
  'refs_sheet_field_company'            : 'Empresa (opcional)',
  'refs_sheet_field_email'              : 'Endereço de E-mail *',
  'refs_sheet_field_phone'              : 'Número de Telefone *',
  'refs_sheet_hint_name'                : 'ex. João Silva',
  'refs_sheet_hint_title'               : 'ex. Gerente de Engenharia',
  'refs_sheet_hint_company'             : 'ex. Empresa ABC',
  'refs_sheet_hint_email'               : 'ex. joao@empresa.com',
  'refs_sheet_hint_phone'               : 'ex. +55 11 91234-5678',
  'refs_sheet_validator_email'          : 'Insira um endereço de e-mail válido',
  'refs_sheet_btn_save'                 : 'Salvar Referência Pessoal',
  'refs_sheet_btn_update'               : 'Atualizar Referência Pessoal',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Experiência Profissional',
  'exp_subtitle'                        : 'Adicione seu histórico de trabalho',
  'exp_banner_info'                     : 'Até {n} responsabilidades por cargo aparecerão no currículo. 3–6 cargos geralmente cabem em 1–2 páginas.',
  'exp_add_btn'                         : 'Adicionar Nova Experiência',
  'exp_snack_max_selected'              : 'Máximo de 8 experiências podem ser selecionadas para um currículo.',
  'exp_snack_max_saved'                 : 'Máximo de 12 experiências salvas atingido.',
  'exp_library_title'                   : 'Experiências Salvas',
  'exp_library_hint'                    : 'Entradas marcadas estão incluídas somente neste currículo. Outros currículos mantêm suas próprias seleções independentes.',
  'exp_nav_next'                        : 'Continuar para Educação',
  'exp_empty_message'                   : 'Nenhuma experiência adicionada ainda',
  'exp_empty_sub'                       : 'Toque acima para adicionar seu primeiro cargo',
  'exp_card_resp_singular'              : 'responsabilidade',
  'exp_card_resp_plural'                : 'responsabilidades',
  'exp_card_resp_tooltip'               : 'Apenas as primeiras 8 responsabilidades aparecerão no currículo',
  'exp_sheet_title_add'                 : 'Adicionar Experiência',
  'exp_sheet_title_edit'                : 'Editar Experiência',
  'exp_sheet_field_job_title'           : 'Cargo *',
  'exp_sheet_field_company'             : 'Empresa *',
  'exp_sheet_field_location'            : 'Localização',
  'exp_sheet_section_responsibilities'  : 'Principais Responsabilidades',
  'exp_sheet_resp_hint_info'            : 'Máx. 8 tópicos · 200 caracteres cada',
  'exp_sheet_resp_label'                : 'Responsabilidade {n}',
  'exp_sheet_resp_hint'                 : 'ex. Liderou uma equipe de 5 engenheiros',
  'exp_sheet_resp_add_btn'              : 'Adicionar Responsabilidade',
  'exp_sheet_resp_max_info'             : 'Máximo de {n} responsabilidades atingido',
  'exp_sheet_resp_validator_max'        : 'Máximo de 200 caracteres',
  'exp_sheet_hint_job_title'            : 'ex. Desenvolvedor Sênior',
  'exp_sheet_hint_location'             : 'ex. São Paulo, SP',
  'exp_sheet_btn_save'                  : 'Salvar Experiência',
  'exp_sheet_btn_update'                : 'Salvar Alterações',
  'exp_date_present'                    : 'Presente / Cargo Atual',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Educação',
  'edu_subtitle'                        : 'Adicione sua formação acadêmica',
  'edu_add_btn'                         : 'Adicionar Nova Formação',
  'edu_snack_max_selected'              : 'Máximo de 8 formações podem ser selecionadas para um currículo.',
  'edu_snack_max_saved'                 : 'Máximo de 12 formações salvas atingido.',
  'edu_library_title'                   : 'Formações Salvas',
  'edu_library_hint'                    : 'Entradas marcadas estão incluídas neste currículo. Suas seleções são salvas automaticamente.',
  'edu_nav_next'                        : 'Continuar para Habilidades',
  'edu_empty_message'                   : 'Nenhuma formação adicionada ainda',
  'edu_empty_sub'                       : 'Toque acima para adicionar suas qualificações',
  'edu_card_bullet_singular'            : 'tópico',
  'edu_card_bullet_plural'              : 'tópicos',
  'edu_sheet_title_add'                 : 'Adicionar Formação',
  'edu_sheet_title_edit'                : 'Editar Formação',
  'edu_sheet_field_degree'              : 'Grau / Qualificação *',
  'edu_sheet_field_institution'         : 'Instituição *',
  'edu_sheet_section_key_points'        : 'Pontos Principais',
  'edu_sheet_key_points_hint_info'      : 'Opcional · 1 tópico · máx. 100 caracteres',
  'edu_sheet_point_label'               : 'Ponto {n}',
  'edu_sheet_point_add_btn'             : 'Adicionar Tópico',
  'edu_sheet_point_max_info'            : 'Máximo de {n} tópicos atingido',
  'edu_sheet_point_validator_max'       : 'Máx. {n} caracteres',
  'edu_sheet_hint_degree'               : 'ex. Bacharelado em Ciência da Computação',
  'edu_sheet_hint_institution'          : 'ex. Universidade de São Paulo',
  'edu_sheet_hint_bullet'               : 'ex. Distinção com Louvor',
  'edu_sheet_btn_save'                  : 'Salvar Formação',
  'edu_sheet_btn_update'                : 'Salvar Alterações',
  'edu_date_present'                    : 'Presente / Curso Atual',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Informações Adicionais',
  'additional_subtitle'                 : 'Certificações, idiomas e mais',
  'additional_cert_section_title'       : 'Certificações',
  'additional_cert_counter'             : '{sel}/{total} selecionadas · máx. {max}',
  'additional_cert_hide'                : 'Ocultar',
  'additional_cert_show'                : 'Mostrar',
  'additional_cert_add_btn'             : 'Adicionar',
  'additional_cert_snack_max'           : 'Máximo de {n} certificações atingido.',
  'additional_cert_hint'                : 'Entradas marcadas estão incluídas neste currículo. Suas seleções são salvas automaticamente.',
  'additional_cert_empty'               : 'Nenhuma certificação adicionada ainda',
  'additional_lang_section_title'       : 'Idiomas',
  'additional_lang_add_hint'            : 'ex. Espanhol',
  'additional_lang_snack_max'           : 'Máximo de {n} idiomas atingido.',
  'additional_lang_empty'               : 'Nenhum idioma adicionado ainda',
  'additional_hobby_section_title'      : 'Hobbies e Interesses',
  'additional_hobby_add_hint'           : 'ex. Fotografia',
  'additional_hobby_snack_max'          : 'Máximo de {n} hobbies atingido.',
  'additional_hobby_empty'              : 'Nenhum hobby adicionado ainda',
  'additional_section_hint'             : 'Entradas marcadas estão incluídas neste currículo. Suas seleções são salvas automaticamente.',
  'additional_nav_next'                 : 'Continuar para Referências',
  'cert_sheet_title_add'                : 'Adicionar Certificação',
  'cert_sheet_title_edit'               : 'Editar Certificação',
  'cert_sheet_sub'                      : 'Adicione uma qualificação, certificado ou credencial profissional.',
  'cert_sheet_field_name'               : 'Nome da Certificação *',
  'cert_sheet_field_issued_by'          : 'Emitido Por (opcional)',
  'cert_sheet_field_short_desc'         : 'Descrição Curta (opcional)',
  'cert_sheet_hint_name'                : 'ex. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'ex. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'ex. Obtido em 2024',
  'cert_sheet_btn_save'                 : 'Salvar Certificação',
  'cert_sheet_btn_update'               : 'Atualizar Certificação',
  'simple_sheet_title_add_language'     : 'Adicionar Idioma',
  'simple_sheet_title_edit_language'    : 'Editar Idioma',
  'simple_sheet_title_add_hobby'        : 'Adicionar Hobby',
  'simple_sheet_title_edit_hobby'       : 'Editar Hobby',
  'simple_sheet_btn_save'               : 'Salvar',
  'simple_sheet_btn_update'             : 'Atualizar',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contato',
  'pdf_section_about_me'                : 'Sobre Mim',
  'pdf_section_summary'                 : 'Resumo',
  'pdf_section_summary_short'           : 'Resumo',
  'pdf_section_profile'                 : 'Perfil',
  'pdf_section_experience'              : 'Experiência',
  'pdf_section_experience_short'        : 'Experiência',
  'pdf_section_education'               : 'Educação',
  'pdf_section_skills'                  : 'Habilidades',
  'pdf_section_languages'               : 'Idiomas',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefone',
  'pdf_label_location'                  : 'Localização',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Limite de CVs atingido',
  'limit_dialog_body'                   : 'Você atingiu o máximo de 30 CVs. Exclua um CV existente antes de criar um novo.',
  'limit_dialog_go_to_my_cvs'           : 'Ir para Meus CVs',
  'limit_dialog_cancel'                 : 'Cancelar',
  'refs_count_summary'                  : '{checked}/{maxChecked} selecionados · {saved}/{maxSaved} salvos',
  'refs_selected_badge'                 : '{n} selecionado(s)',
  'refs_empty_message'                  : 'Nenhuma referência salva ainda',
  'refs_empty_sub'                      : 'Toque acima para adicionar uma referência pessoal',
};