// lib/language_keys/lang_nl_dutch.dart
//
// Dutch (Netherlands) — translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> nlDutch = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Geen talen gevonden',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Overslaan',
  'onboarding_next'                     : 'Volgende',
  'onboarding_get_started'              : 'Aan de slag',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Welkom',
  'ob1_title'                           : 'Maak een CV dat\nDeuren Opent',
  'ob1_body'                            : 'Val op tussen honderden sollicitanten. Maak in minuten een verzorgd, winnend CV — geen ontwerpervaring nodig.',
  'ob1_pill_label'                      : 'Professionele CV-bouwer',
  'ob1_chip_templates'                  : '24+ Sjablonen',
  'ob1_chip_pdf'                        : 'PDF-export',
  'ob1_chip_free'                       : 'Gratis te gebruiken',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Sjablonen',
  'ob2_title'                           : 'Elke Branche.\nElke Ambitie.',
  'ob2_body'                            : 'Van zakelijke lay-outs tot gedurfde creatieve ontwerpen — een sjabloon dat jouw verhaal vertelt.',
  'ob2_tap_hint'                        : 'Tik op een sjabloon voor een voorbeeld',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Levendig',
  'ob2_tpl_nordic'                      : 'Scandinavisch',
  'ob2_tpl_tech_dark'                   : 'Tech Donker',
  'ob2_tpl_luxury'                      : 'Luxe',
  'ob2_tag_corporate'                   : 'Zakelijk',
  'ob2_tag_creative'                    : 'Creatief',
  'ob2_tag_minimal'                     : 'Minimaal',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Slimme indeling',
  'ob3_title'                           : 'Jouw CV.\nPerfect Gerangschikt.',
  'ob3_body'                            : 'Slimme indeling herordent je secties voor maximale impact — zodat de sterkste inhoud als eerste opvalt bij recruiters.',
  'ob3_badge_smart_layout'              : 'Slimme indeling',
  'ob3_badge_cv_ready'                  : 'CV klaar!',
  'ob3_step1_label'                     : 'Kies een sjabloon',
  'ob3_step1_desc'                      : 'Kies uit 24+ prachtige ontwerpen.',
  'ob3_step2_label'                     : 'Vul je gegevens in',
  'ob3_step2_desc'                      : 'Begeleide velden voor alle secties.',
  'ob3_step3_label'                     : 'Slimme indeling',
  'ob3_step3_desc'                      : 'Één tik en je CV is perfect ingedeeld.',
  'ob3_step4_label'                     : 'Exporteer als PDF',
  'ob3_step4_desc'                      : 'Pixel-perfect PDF klaar om te versturen.',
  'ob3_section_work'                    : 'Werkervaring',
  'ob3_section_education'               : 'Opleiding',
  'ob3_section_skills'                  : 'Vaardigheden',
  'ob3_section_references'              : 'Referenties',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Klaar om te gaan',
  'ob4_title'                           : 'Waarom Topkandidaten\nKiezen voor CV Builder',
  'ob4_visual_headline'                 : 'Je bent er klaar voor!',
  'ob4_visual_subline'                  : 'Alles wat je nodig hebt om de baan te krijgen.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Sjablonen',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : "Max CV's",
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privé',
  'ob4_hl1_title'                       : 'Privé & Veilig',
  'ob4_hl1_sub'                         : 'Gegevens blijven op je apparaat.',
  'ob4_hl2_title'                       : 'Automatisch opslaan',
  'ob4_hl2_sub'                         : 'Elke toetsaanslag direct opgeslagen.',
  'ob4_hl3_title'                       : "Tot 30 CV's",
  'ob4_hl3_sub'                         : 'Uniek CV voor elke functie.',
  'ob4_hl4_title'                       : 'Één tik om te delen',
  'ob4_hl4_sub'                         : 'Verstuur PDF zonder de app te verlaten.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Val op in de massa',
  'home_hero_title'                     : 'Maak je\nProfessionele CV',
  'home_hero_sub'                       : 'Bouw een indrukwekkend cv\nin minuten',
  'home_hero_cta'                       : 'Begin met bouwen',
  'home_premium_soon'                   : 'Upgrade naar Pro komt binnenkort!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Meest recent',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Laatst bewerkt',
  'history_sort_by_template'            : 'Op sjabloon',
  'history_sort_sheet_title'            : 'Sorteren op',
  'history_sort_alphabetical_full'      : 'Alfabetisch (A–Z)',
  'history_premium_soon'                : 'Upgrade naar Pro komt binnenkort!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Instellingen',
  'settings_section_preferences'        : 'Voorkeuren',
  'settings_section_support'            : 'Ondersteuning',
  'settings_section_legal'              : 'Juridisch',
  'settings_section_about'              : 'Over',
  'settings_language_tile_title'        : 'Taal',
  'settings_dark_mode_title'            : 'Donkere modus',
  'settings_dark_mode_on'               : 'Donker thema ingeschakeld',
  'settings_dark_mode_off'              : 'Licht thema ingeschakeld',
  'settings_help_faq_title'             : 'Help & FAQ',
  'settings_help_faq_sub'               : 'Veelgestelde vragen beantwoord',
  'settings_contact_support_title'      : 'Contact opnemen',
  'settings_rate_app_title'             : 'Beoordeel de app',
  'settings_rate_app_sub'               : 'Geniet je van de app? Laat een recensie achter!',
  'settings_privacy_policy_title'       : 'Privacybeleid',
  'settings_terms_title'                : 'Gebruiksvoorwaarden',
  'settings_app_version_title'          : 'App-versie',
  'settings_email_error'                : 'Kan de e-mailapp niet openen. Stuur een e-mail naar cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CV-voorbeeld',
  'preview_header_sub'                  : 'Klaar om te exporteren',
  'preview_generating'                  : 'Je CV wordt gegenereerd...',
  'preview_failed_title'                : 'Voorbeeld mislukt',
  'preview_failed_error'                : 'Fout: {error}',
  'preview_go_back'                     : 'Terug',
  'preview_no_data'                     : 'Geen gegevens beschikbaar',
  'preview_btn_print'                   : 'Afdrukken',
  'preview_btn_download'                : 'Downloaden & delen',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Help & FAQ',
  'faq_category_all'                    : 'Alle',
  'faq_empty'                           : 'Geen resultaten gevonden',
  'faq_contact_headline'                : 'Nog hulp nodig?',
  'faq_contact_sub'                     : 'Ons team staat voor je klaar.',
  'faq_contact_btn'                     : 'Contact',
  'faq_email_error'                     : 'Kan de e-mailapp niet openen. Stuur een e-mail naar cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Aan de slag',
  'faq_cat_templates'                   : 'Sjablonen',
  'faq_cat_editing'                     : 'Bewerken',
  'faq_cat_exporting'                   : 'Exporteren',
  'faq_cat_data_privacy'                : 'Gegevens & Privacy',
  'faq_cat_troubleshooting'             : 'Problemen oplossen',
  'faq_q1'  : 'Hoe maak ik mijn eerste CV?',
  'faq_a1'  : 'Tik op de "+"-knop op het beginscherm om een nieuw CV te starten. Kies een sjabloon dat bij je stijl past en vul stap voor stap je persoonlijke gegevens, werkervaring, opleiding en vaardigheden in. Je voortgang wordt automatisch opgeslagen.',
  'faq_q2'  : 'Kan ik meer dan één CV aanmaken?',
  'faq_a2'  : "Ja! Je kunt meerdere CV's aanmaken voor verschillende functies of sectoren. Elk CV wordt apart opgeslagen, zodat je ze kunt afstemmen op specifieke sollicitaties.",
  'faq_q3'  : 'Hoe verander ik mijn CV-sjabloon?',
  'faq_a3'  : 'Open je CV, tik op het sjabloonpictogram bovenaan het scherm en blader door de beschikbare sjablonen. Tik op een sjabloon om een voorbeeld te zien met je bestaande inhoud. Bevestig om het toe te passen.',
  'faq_q4'  : 'Zijn er gratis en betaalde sjablonen?',
  'faq_a4'  : 'Ja. Een selectie professionele sjablonen is gratis beschikbaar. Premium sjablonen met geavanceerde ontwerpen en kleurpaletten zijn beschikbaar via een eenmalige aankoop of abonnement.',
  'faq_q5'  : 'Hoe voeg ik secties toe of verwijder ik ze?',
  'faq_a5'  : 'Scroll in de CV-editor naar de onderkant van het scherm en tik op "Sectie toevoegen" om extra\'s toe te voegen zoals Talen, Certificaten of Vrijwilligerswerk. Om een sectie te verwijderen, tik je op de sectiekop en kies je "Verwijderen".',
  'faq_q6'  : 'Hoe herorden ik secties?',
  'faq_a6'  : 'Houd het sleephandvat (≡) naast een sectiekop ingedrukt en sleep het naar de gewenste positie. Wijzigingen worden automatisch opgeslagen.',
  'faq_q7'  : 'Hoe exporteer ik mijn CV als PDF?',
  'faq_a7'  : 'Open je CV en tik op de exportknop (deelpictogram) rechtsboven. Selecteer "Exporteer als PDF". Je kunt het dan opslaan op je apparaat, delen via e-mail, WhatsApp, of het direct uploaden naar vacaturesites.',
  'faq_q8'  : 'Welke bestandsindelingen worden ondersteund?',
  'faq_a8'  : 'De app ondersteunt momenteel het exporteren van je CV als hoogwaardige PDF. Aanvullende indelingen kunnen in toekomstige updates worden toegevoegd.',
  'faq_q9'  : 'Waar worden mijn CV-gegevens opgeslagen?',
  'faq_a9'  : 'Al je CV-gegevens worden lokaal op je apparaat opgeslagen. We uploaden je persoonlijke informatie niet naar onze servers. Dit betekent dat je gegevens privé blijven en offline toegankelijk zijn.',
  'faq_q10' : "Hoe maak ik een back-up van mijn CV's?",
  'faq_a10' : "Je CV's zijn opgenomen in de standaard back-up van je apparaat (Google Drive op Android, iCloud op iOS) als je back-up hebt ingeschakeld in de apparaatinstellingen. Je kunt ook afzonderlijke CV's exporteren als PDF om een kopie te bewaren.",
  'faq_q11' : 'De app werkt traag. Wat moet ik doen?',
  'faq_a11' : 'Probeer de app te sluiten en opnieuw te openen. Als het probleem aanhoudt, start je apparaat opnieuw op. Zorg ervoor dat je de nieuwste versie van de app hebt geïnstalleerd vanuit de Play Store / App Store.',
  'faq_q12' : 'Mijn CV wordt niet correct geëxporteerd. Wat moet ik doen?',
  'faq_a12' : 'Zorg ervoor dat je voldoende opslagruimte hebt op je apparaat. Probeer grote afbeeldingen in je CV te verkleinen. Als het probleem aanhoudt, neem dan contact op met ons ondersteuningsteam.',
  'faq_q13' : 'Ik ben vergeten op te slaan — is mijn werk verloren?',
  'faq_a13' : 'Helemaal niet! De app slaat je voortgang continu op terwijl je bewerkt.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Jouw carrière, geperfectioneerd',
  'header_tooltip_back'                 : 'Terug',
  'header_tooltip_my_cvs'               : "Mijn CV's",
  'header_tooltip_settings'             : 'Instellingen',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : "Mijn CV's",
  'saved_count_single'                  : '{n} document',
  'saved_count_plural'                  : '{n} documenten',
  'saved_limit_reached'                 : 'Limiet bereikt',
  'saved_footer_count'                  : "{n} / 30 CV's",
  'saved_filter_all'                    : 'Alle',
  'saved_filter_draft'                  : 'Concept',
  'saved_filter_complete'               : 'Voltooid',
  'saved_status_complete'               : 'Voltooid',
  'saved_status_saved'                  : 'Opgeslagen',
  'saved_status_draft'                  : 'Concept',
  'saved_empty_title'                   : "Nog geen CV's hier",
  'saved_empty_sub'                     : 'Begin hierboven met je eerste CV',
  'saved_search_empty_title'            : 'Geen resultaten gevonden',
  'saved_search_empty_sub'              : 'Probeer een andere zoekterm',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Kleurenschema',
  'custom_font_settings_title'          : 'Lettertype-instellingen',
  'custom_font_family_label'            : 'Lettertype',
  'custom_font_size_label'              : 'Lettergrootte: ',
  'custom_current_template_title'       : 'Huidig sjabloon',
  'custom_change_template_btn'          : 'Sjabloon wijzigen',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klassiek',
  'custom_tpl_professional'             : 'Professioneel',
  'custom_tpl_creative'                 : 'Creatief',
  'custom_tpl_minimal'                  : 'Minimaal',
  'custom_tpl_modern_desc'              : 'Strak en eigentijds ontwerp',
  'custom_tpl_classic_desc'             : 'Traditionele professionele lay-out',
  'custom_tpl_professional_desc'        : 'Zakelijk gericht sjabloon',
  'custom_tpl_creative_desc'            : 'Val op met een uniek ontwerp',
  'custom_tpl_minimal_desc'             : 'Eenvoudige en elegante stijl',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Kies sjabloon',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Scandinavisch',
  'tpl_vibrant_name'                    : 'Levendig',
  'tpl_tech_dark_name'                  : 'Tech Donker',
  'tpl_luxury_name'                     : 'Luxe',
  'tpl_executive_tag'                   : 'Meest populair',
  'tpl_nordic_tag'                      : 'Strak',
  'tpl_vibrant_tag'                     : 'Creatief',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Gedurfd & gezaghebbend voor seniorposities',
  'tpl_nordic_desc'                     : 'Minimalistische duidelijkheid, vertrouwd door topbedrijven',
  'tpl_vibrant_desc'                    : 'Val op met energie en kleur',
  'tpl_tech_dark_desc'                  : 'Terminalstijl voor ontwikkelaars',
  'tpl_luxury_desc'                     : 'Goudaccenten en prestige op zwart',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Sjabloon',
  'detail_step_personal'                : 'Persoonlijk',
  'detail_step_experience'              : 'Ervaring',
  'detail_step_education'               : 'Opleiding',
  'detail_step_skills'                  : 'Vaardigheden',
  'detail_step_additional'              : 'Aanvullend',
  'detail_step_references'              : 'Referenties',
  'detail_step_customize'               : 'Aanpassen',
  'detail_banner_heading'               : 'Bijna klaar!',
  'detail_banner_btn'                   : 'Doorgaan',
  'detail_banner_completion_label'      : 'Voltooiing',
  'detail_stat_created_label'           : 'Aangemaakt',
  'detail_stat_steps_label'             : 'Stappen gedaan',
  'detail_section_template_style'       : 'Sjabloonstijl',
  'detail_section_steps'                : 'Stappen',
  'detail_steps_counter'                : '{done} van {total} voltooid',
  'detail_step_sub'                     : 'Stap {n} van {total}',
  'detail_section_activity'             : 'Activiteit',
  'detail_activity_created'             : 'Aangemaakt',
  'detail_activity_last_edited'         : 'Laatst bewerkt',
  'detail_activity_template'            : 'Sjabloon',
  'detail_btn_continue_editing'         : 'Doorgaan met bewerken',
  'detail_btn_edit_cv'                  : 'CV bewerken',
  'detail_option_rename'                : 'CV hernoemen',
  'detail_option_delete'                : 'CV verwijderen',
  'detail_rename_title'                 : 'CV hernoemen',
  'detail_rename_hint'                  : 'bijv. Software Engineer CV',
  'detail_rename_error_empty'           : 'Naam mag niet leeg zijn',
  'detail_rename_btn_cancel'            : 'Annuleren',
  'detail_rename_btn_save'              : 'Opslaan',
  'detail_rename_snackbar'              : 'Hernoemd naar "{name}"',
  'detail_delete_title'                 : 'CV verwijderen?',
  'detail_delete_body'                  : 'Dit verwijdert "{name}" permanent. Deze actie kan niet ongedaan worden gemaakt.',
  'detail_delete_btn_cancel'            : 'Annuleren',
  'detail_delete_btn_confirm'           : 'Verwijderen',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Voltooid',
  'detail_check_tile_incomplete'        : 'Nog niet ingevuld',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Kies je sjabloon',
  'chooser_subtitle'                    : 'Veeg om te bladeren  ·  Tik om te selecteren  ·  Houd vast voor voorbeeld',
  'chooser_card_hold_hint'              : 'Houd vast voor voorbeeld',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Geselecteerd',
  'chooser_modal_heading'               : 'Geef je CV een naam',
  'chooser_modal_sub'                   : "Geef het een naam zodat je het gemakkelijk kunt vinden in Mijn CV's en Geschiedenis.",
  'chooser_modal_field_label'           : 'CV-naam',
  'chooser_modal_save_btn'              : 'Opslaan & beginnen',
  'chooser_modal_divider'               : 'of ga verder met een bestaand CV',
  'chooser_nav_selected_sub'            : 'Geselecteerd sjabloon',
  'chooser_nav_cta'                     : 'Opslaan & doorgaan',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Maximum aantal vermeldingen bereikt',
  'editor_show_hide'                    : 'Tonen/Verbergen',
  'editor_editing_badge'                : 'Bewerken',
  'editor_field_required'               : 'Verplicht',
  'editor_tooltip_edit'                 : 'Bewerken',
  'editor_tooltip_delete'               : 'Verwijderen',
  'editor_date_start'                   : 'Startdatum *',
  'editor_date_end'                     : 'Einddatum *',
  'editor_date_tap_hint'                : 'Tik om te selecteren',
  'editor_date_dialog_title'            : 'Selecteer maand & jaar',
  'editor_date_confirm'                 : 'Bevestigen',
  'editor_panel_hide'                   : 'Verbergen',
  'editor_panel_show'                   : 'Tonen',
  'editor_validator_max_chars'          : 'Max {n} tekens',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Bouw je CV',
  'editor_header_step_sub'              : 'Stap {current} van {total} · {label}',
  'editor_step_template'                : 'Sjabloon',
  'editor_step_personal'                : 'Persoonlijk',
  'editor_step_experience'              : 'Ervaring',
  'editor_step_education'               : 'Opleiding',
  'editor_step_skills'                  : 'Vaardigheden',
  'editor_step_additional'              : 'Aanvullend',
  'editor_step_references'              : 'Referenties',
  'editor_step_customize'               : 'Aanpassen',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Aanpassen',
  'customize_subtitle'                  : 'Maak je CV uniek van jou',
  'customize_smart_layout_btn'          : 'Slimme indeling',
  'customize_back_to_top'               : 'Terug naar boven',
  'customize_done_title'                : 'Je bent er klaar voor!',
  'customize_done_sub'                  : 'Tik hieronder op CV bekijken om je voltooide CV te zien',
  'customize_preview_btn'               : 'CV bekijken',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Kleurenschema',
  'color_black'                         : 'Zwart',
  'color_blue'                          : 'Blauw',
  'color_nordic_blue'                   : 'Scandinavisch blauw',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Groenblauw',
  'color_green'                         : 'Groen',
  'color_purple'                        : 'Paars',
  'color_orange'                        : 'Oranje',
  'color_red'                           : 'Rood',
  'color_executive_gold'                : 'Executive goud',
  'color_vibrant_coral'                 : 'Levendig koraal',
  'color_white'                         : 'Wit',
  'color_white_bg'                      : 'Witte achtergrond',
  'color_maroon'                        : 'Kastanjebruin',
  'color_brutalist_yellow'              : 'Brutalistisch geel',
  'color_neon_blue'                     : 'Neonblauw',
  'color_blueprint_navy'                : 'Blauwdruk marineblauw',
  'color_light_grey'                    : 'Lichtgrijs',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Lettertype',
  'customize_font_picker_title'         : 'Kies lettertype',
  'customize_font_picker_sub'           : 'Elk lettertype wordt weergegeven in zijn eigen stijl',
  'customize_font_preview_sample'       : 'De snelle bruine vos',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Lettergrootte',
  'customize_font_size_label'           : 'Tekstgrootte',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Afbeeldingsgrootte',
  'customize_image_size_label'          : 'Afbeeldingsgrootte',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Live voorbeeld',
  'preview_page_count_singular'         : '1 pagina',
  'preview_page_count_plural'           : "{n} pagina's",
  'preview_page_of'                     : 'Pagina {page} van {total}',
  'preview_live_hint'                   : 'Wijzigingen worden direct toegepast',
  'preview_template_unregistered'       : 'Nog niet geregistreerd in customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Je CV wordt voorbereid…',
  'preview_bar_print'                   : 'Afdrukken',
  'preview_bar_save_pdf'                : 'Opslaan als PDF',
  'preview_bar_share'                   : 'Delen',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CV-voorbeeld',
  'preview_screen_sub'                  : '{n} {unit} · precies zoals afgedrukt',
  'preview_page_singular'               : 'pagina',
  'preview_page_plural'                 : "pagina's",
  'preview_pdf_filename'                : 'Mijn_CV',
  'preview_share_subject'               : 'Mijn CV',
  'preview_snack_print_failed'          : 'Afdrukken mislukt: {e}',
  'preview_snack_saved'                 : 'CV opgeslagen in Downloads ✓',
  'preview_snack_export_failed'         : 'Exporteren mislukt: {e}',
  'preview_snack_share_failed'          : 'Delen mislukt: {e}',
  'preview_template_not_registered'     : 'Sjabloon niet geregistreerd',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Voorbeeld sluiten',
  'preview_modal_hint_photo'            : 'Ondersteunt profielfoto  ·  Tik op een kaart om te selecteren',
  'preview_modal_hint_no_photo'         : 'Tik op een sjabloonkaart om het te selecteren',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Mijn CV',
  'time_just_now'                       : 'Zojuist',
  'time_minutes_ago'                    : '{n} min geleden',
  'time_hours_ago'                      : '{n} uur geleden',
  'time_yesterday'                      : 'Gisteren',
  'time_days_ago'                       : '{n} dagen geleden',
  'time_one_week_ago'                   : '1 week geleden',
  'time_weeks_ago'                      : '{n} weken geleden',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegant',
  'tpl_tag_classic'                     : 'Klassiek',
  'tpl_tag_minimal'                     : 'Minimaal',
  'tpl_tag_creative'                    : 'Creatief',
  'tpl_tag_bold'                        : 'Gedurfd',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Verloop',
  'tpl_gradient_desc'                   : 'Groenblauw naar violet verloopkaarten',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Redactioneel',
  'tpl_editorial_desc'                  : 'Tijdschriftstijl in rood & crème',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Zacht',
  'tpl_pastel_soft_desc'                : 'Lavendel zijbalk, zachte kaarten',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalistisch',
  'tpl_brutalist_desc'                  : 'Ruw raster, dikke randen & geel',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragd',
  'tpl_emerald_desc'                    : 'Bosgroen met tijdlijn',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografiek',
  'tpl_infographic_desc'                : 'Donker canvas met ringgrafieken',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : "Jaren '20 geometrisch gouden luxe",

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Donker',
  'tpl_wina_dark_desc'                  : 'Donkere infografiek met ringen',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Oranje',
  'tpl_rio_orange_desc'                 : 'Donkere zijbalk met oranje accent',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Zomer',
  'tpl_summer_desc'                     : 'Strak minimaal, zachte grijstinten',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Warme beige elegante tinten',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Strak zwart & wit klassiek',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klassieke ATS-vriendelijke lay-out',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Donker',
  'tpl_tony_dark_desc'                  : 'Donkere oranje infografiekstijl',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Mode',
  'tpl_fashion_desc'                    : 'Technische tekening op raster',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivaris',
  'tpl_archivist_desc'                  : 'Klassieke twee-kolom labellay-out',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomaat',
  'tpl_diplomat_desc'                   : 'Gearceerde kopteksten met diamantpunten',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridiaan',
  'tpl_meridian_desc'                   : 'Gecentreerde kopteksten, geaccentueerde bedrijfsnamen',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Vette naam, tijdlijnpunten & prestaties',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Persoonlijke gegevens',
  'personal_subtitle'                   : 'Vertel werkgevers wie je bent',
  'personal_profile_counter'            : '{n}/{max} profielen',
  'personal_info_banner'                : 'Sla tot 5 profielen op en selecteer er één per CV. Je selectie wordt voor elk CV afzonderlijk onthouden.',
  'personal_snack_max'                  : 'Maximum van {n} profielen bereikt.',
  'personal_add_btn'                    : 'Nieuw profiel toevoegen',
  'personal_library_title'              : 'Opgeslagen profielen',
  'personal_selected_one'               : '1 geselecteerd',
  'personal_selected_none'              : 'geen geselecteerd',
  'personal_library_hint'               : "Tik op een kaart om het voor dit CV te selecteren. Andere CV's behouden hun eigen onafhankelijke selecties.",
  'personal_empty_message'              : 'Nog geen profielen opgeslagen',
  'personal_empty_sub'                  : 'Tik hierboven om je persoonlijke gegevens toe te voegen',
  'personal_nav_next'                   : 'Opslaan & doorgaan',
  'personal_card_active_badge'          : 'Actief voor dit CV',
  'personal_sheet_title_add'            : 'Nieuw profiel',
  'personal_sheet_title_edit'           : 'Profiel bewerken',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTISCH',
  'personal_sheet_brutalist_banner'     : 'Het brutalistisch sjabloon heeft compacte contactvelden. Kortere waarden (bijv. alleen stad) worden het best weergegeven.',
  'personal_section_photo'              : 'Profielfoto',
  'personal_section_basic'              : 'Basisgegevens',
  'personal_section_contact'            : 'Contact',
  'personal_section_online'             : 'Online aanwezigheid',
  'personal_section_summary'            : 'Professionele samenvatting',
  'personal_field_first_name'           : 'Voornaam *',
  'personal_field_last_name'            : 'Achternaam',
  'personal_field_job_title'            : 'Functietitel *',
  'personal_field_email'                : 'E-mailadres *',
  'personal_field_phone'                : 'Telefoonnummer *',
  'personal_field_location'             : 'Locatie',
  'personal_field_location_brut'        : 'Locatie (alleen stad)',
  'personal_field_website'              : 'Website / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn-URL',
  'personal_hint_first_name'            : 'bijv. Jan',
  'personal_hint_last_name'             : 'bijv. de Vries',
  'personal_hint_job_title'             : 'bijv. Senior Engineer',
  'personal_hint_email'                 : 'bijv. jan@voorbeeld.nl',
  'personal_hint_phone'                 : 'bijv. +31 6 12 34 56 78',
  'personal_hint_location'              : 'bijv. Amsterdam, Nederland',
  'personal_hint_location_brut'         : 'bijv. Amsterdam, NL',
  'personal_hint_website'               : 'bijv. github.com/jandevries',
  'personal_hint_website_brut'          : 'bijv. github.com/jan',
  'personal_hint_linkedin'              : 'bijv. linkedin.com/in/jandevries',
  'personal_hint_linkedin_brut'         : 'bijv. linkedin.com/in/jan',
  'personal_summary_hint_label'         : 'Houd het beknopt — dit verschijnt bovenaan je CV.',
  'personal_hint_summary'               : 'Een korte samenvatting van 2–3 zinnen over je achtergrond en doelen...',
  'personal_validator_email'            : 'Voer een geldig e-mailadres in',
  'personal_field_char_limit_tooltip'   : 'Tekenlimiet bereikt',
  'personal_sheet_btn_save'             : 'Profiel opslaan',
  'personal_sheet_btn_update'           : 'Wijzigingen opslaan',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Foto kiezen',
  'photo_option_gallery'                : 'Kiezen uit galerij',
  'photo_option_camera'                 : 'Foto maken',
  'photo_option_reposition'             : 'Foto herpositioneren',
  'photo_option_remove'                 : 'Foto verwijderen',
  'photo_status_added'                  : 'Foto toegevoegd ✓',
  'photo_status_empty'                  : 'Voeg een professionele pasfoto toe',
  'photo_chip_gallery'                  : 'Galerij',
  'photo_chip_camera'                   : 'Camera',
  'photo_chip_reposition'               : 'Herpositioneren',
  'photo_reposition_title'              : 'Foto herpositioneren',
  'photo_reposition_sub'                : 'Sleep de foto om de positie aan te passen',
  'photo_reposition_reset'              : 'Terugzetten naar midden',
  'photo_reposition_apply'              : 'Toepassen',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Vaardigheden',
  'skills_subtitle'                     : 'Benadruk je belangrijkste capaciteiten',
  'skills_add_btn'                      : 'Nieuwe vaardigheid toevoegen',
  'skills_snack_max_icons'              : 'Maximum van 10 pictogrammen geselecteerd.',
  'skills_snack_max_skills'             : 'Maximum van 15 vaardigheden bereikt.',
  'skills_library_title'                : 'Opgeslagen vaardigheden',
  'skills_library_hint'                 : 'Aangevinkte vaardigheden zijn opgenomen in dit CV. Je selecties worden automatisch opgeslagen.',
  'skills_nav_next'                     : 'Doorgaan naar aanvullend',
  'skills_wina_header_icon_bar'         : 'Pictogrambalk in koptekst',
  'skills_wina_on'                      : 'AAN',
  'skills_wina_off'                     : 'UIT',
  'skills_wina_bar_on_sub'              : 'Gekleurde pictogramcirkels worden weergegeven in de CV-koptekst.',
  'skills_wina_bar_off_sub'             : 'Pictogramrij verborgen — meer ruimte voor contactgegevens.',
  'skills_wina_palette_hint'            : 'Pictogrammen verschijnen als gekleurde cirkels in de paletsvolgorde.',
  'skills_wina_preview_label'           : 'Voorbeeld',
  'skills_wina_disabled_hint'           : 'Schakel de pictogrambalk hierboven in om te kiezen welke pictogrammen in de CV-koptekst verschijnen.',
  'skills_sheet_title_add'              : 'Vaardigheid toevoegen',
  'skills_sheet_title_edit'             : 'Vaardigheid bewerken',
  'skills_sheet_field_name'             : 'Naam van de vaardigheid *',
  'skills_sheet_hint_short'             : 'bijv. Flutter, Ontwerp',
  'skills_sheet_hint_long'              : 'bijv. Flutter, Projectbeheer',
  'skills_sheet_validator_max'          : 'Max {n} tekens',
  'skills_sheet_proficiency'            : 'Vaardigheidsniveau',
  'skills_sheet_beginner'               : 'Beginner',
  'skills_sheet_expert'                 : 'Expert',
  'skills_sheet_btn_save'               : 'Vaardigheid opslaan',
  'skills_sheet_btn_update'             : 'Vaardigheid bijwerken',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Persoonlijke referenties',
  'refs_subtitle'                       : 'Mensen die persoonlijk voor je kunnen instaan',
  'refs_add_btn'                        : 'Nieuwe persoonlijke referentie toevoegen',
  'refs_snack_max_selected'             : 'Maximum van 4 referenties kunnen worden geselecteerd voor een CV.',
  'refs_snack_max_saved'                : 'Maximum van 10 opgeslagen referenties bereikt.',
  'refs_library_title'                  : 'Opgeslagen referenties',
  'refs_library_hint'                   : 'Aangevinkte referenties zijn opgenomen in dit CV. Max 4 per CV. Je selecties worden automatisch opgeslagen.',
  'refs_nav_next'                       : 'Doorgaan naar aanpassen',
  'refs_sheet_title_add'                : 'Persoonlijke referentie toevoegen',
  'refs_sheet_title_edit'               : 'Persoonlijke referentie bewerken',
  'refs_sheet_sub_add'                  : 'Iemand die je persoonlijk kan aanbevelen bij werkgevers.',
  'refs_sheet_sub_edit'                 : 'Werk de gegevens van deze referentie hieronder bij.',
  'refs_sheet_field_name'               : 'Volledige naam *',
  'refs_sheet_field_title'              : 'Functietitel *',
  'refs_sheet_field_company'            : 'Bedrijf (optioneel)',
  'refs_sheet_field_email'              : 'E-mailadres *',
  'refs_sheet_field_phone'              : 'Telefoonnummer *',
  'refs_sheet_hint_name'                : 'bijv. Jan de Vries',
  'refs_sheet_hint_title'               : 'bijv. Engineering Manager',
  'refs_sheet_hint_company'             : 'bijv. Acme B.V.',
  'refs_sheet_hint_email'               : 'bijv. jan@acme.nl',
  'refs_sheet_hint_phone'               : 'bijv. +31 6 12 34 56 78',
  'refs_sheet_validator_email'          : 'Voer een geldig e-mailadres in',
  'refs_sheet_btn_save'                 : 'Persoonlijke referentie opslaan',
  'refs_sheet_btn_update'               : 'Persoonlijke referentie bijwerken',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Werkervaring',
  'exp_subtitle'                        : 'Voeg je werkgeschiedenis toe',
  'exp_banner_info'                     : "Tot {n} verantwoordelijkheden per functie verschijnen op het CV. 3–6 functies passen doorgaans op 1–2 pagina's.",
  'exp_add_btn'                         : 'Nieuwe ervaring toevoegen',
  'exp_snack_max_selected'              : 'Maximum van 8 ervaringen kunnen worden geselecteerd voor een CV.',
  'exp_snack_max_saved'                 : 'Maximum van 12 opgeslagen ervaringen bereikt.',
  'exp_library_title'                   : 'Opgeslagen ervaringen',
  'exp_library_hint'                    : "Aangevinkte vermeldingen zijn alleen opgenomen in dit CV. Andere CV's behouden hun eigen onafhankelijke selecties.",
  'exp_nav_next'                        : 'Doorgaan naar opleiding',
  'exp_empty_message'                   : 'Nog geen ervaring toegevoegd',
  'exp_empty_sub'                       : 'Tik hierboven om je eerste functie toe te voegen',
  'exp_card_resp_singular'              : 'verantwoordelijkheid',
  'exp_card_resp_plural'                : 'verantwoordelijkheden',
  'exp_card_resp_tooltip'               : 'Alleen de eerste 8 verantwoordelijkheden verschijnen op het CV',
  'exp_sheet_title_add'                 : 'Ervaring toevoegen',
  'exp_sheet_title_edit'                : 'Ervaring bewerken',
  'exp_sheet_field_job_title'           : 'Functietitel *',
  'exp_sheet_field_company'             : 'Bedrijf *',
  'exp_sheet_field_location'            : 'Locatie',
  'exp_sheet_section_responsibilities'  : 'Belangrijkste verantwoordelijkheden',
  'exp_sheet_resp_hint_info'            : 'Max 8 opsommingspunten · 200 tekens elk',
  'exp_sheet_resp_label'                : 'Verantwoordelijkheid {n}',
  'exp_sheet_resp_hint'                 : 'bijv. Leidde een team van 5 engineers',
  'exp_sheet_resp_add_btn'              : 'Verantwoordelijkheid toevoegen',
  'exp_sheet_resp_max_info'             : 'Maximum {n} verantwoordelijkheden bereikt',
  'exp_sheet_resp_validator_max'        : 'Max 200 tekens',
  'exp_sheet_hint_job_title'            : 'bijv. Senior Ontwikkelaar',
  'exp_sheet_hint_location'             : 'bijv. Amsterdam, Nederland',
  'exp_sheet_btn_save'                  : 'Ervaring opslaan',
  'exp_sheet_btn_update'                : 'Wijzigingen opslaan',
  'exp_date_present'                    : 'Heden / Huidige functie',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Opleiding',
  'edu_subtitle'                        : 'Voeg je academische achtergrond toe',
  'edu_add_btn'                         : 'Nieuwe opleiding toevoegen',
  'edu_snack_max_selected'              : 'Maximum van 8 opleidingsvermeldingen kunnen worden geselecteerd voor een CV.',
  'edu_snack_max_saved'                 : 'Maximum van 12 opgeslagen opleidingsvermeldingen bereikt.',
  'edu_library_title'                   : 'Opgeslagen opleidingen',
  'edu_library_hint'                    : 'Aangevinkte vermeldingen zijn opgenomen in dit CV. Je selecties worden automatisch opgeslagen.',
  'edu_nav_next'                        : 'Doorgaan naar vaardigheden',
  'edu_empty_message'                   : 'Nog geen opleiding toegevoegd',
  'edu_empty_sub'                       : 'Tik hierboven om je kwalificaties toe te voegen',
  'edu_card_bullet_singular'            : 'opsommingspunt',
  'edu_card_bullet_plural'              : 'opsommingspunten',
  'edu_sheet_title_add'                 : 'Opleiding toevoegen',
  'edu_sheet_title_edit'                : 'Opleiding bewerken',
  'edu_sheet_field_degree'              : 'Diploma / Kwalificatie *',
  'edu_sheet_field_institution'         : 'Instelling *',
  'edu_sheet_section_key_points'        : 'Kernpunten',
  'edu_sheet_key_points_hint_info'      : 'Optioneel · 1 opsommingspunt · max 100 tekens',
  'edu_sheet_point_label'               : 'Punt {n}',
  'edu_sheet_point_add_btn'             : 'Opsommingspunt toevoegen',
  'edu_sheet_point_max_info'            : 'Maximum {n} opsommingspunten bereikt',
  'edu_sheet_point_validator_max'       : 'Max {n} tekens',
  'edu_sheet_hint_degree'               : 'bijv. BSc Informatica',
  'edu_sheet_hint_institution'          : 'bijv. Universiteit van Amsterdam',
  'edu_sheet_hint_bullet'               : 'bijv. Cum laude afgestudeerd',
  'edu_sheet_btn_save'                  : 'Opleiding opslaan',
  'edu_sheet_btn_update'                : 'Wijzigingen opslaan',
  'edu_date_present'                    : 'Heden / Huidige studie',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Aanvullende informatie',
  'additional_subtitle'                 : 'Certificaten, talen & meer',
  'additional_cert_section_title'       : 'Certificaten',
  'additional_cert_counter'             : '{sel}/{total} geselecteerd · max {max}',
  'additional_cert_hide'                : 'Verbergen',
  'additional_cert_show'                : 'Tonen',
  'additional_cert_add_btn'             : 'Toevoegen',
  'additional_cert_snack_max'           : 'Maximum van {n} certificaatvermeldingen bereikt.',
  'additional_cert_hint'                : 'Aangevinkte vermeldingen zijn opgenomen in dit CV. Je selecties worden automatisch opgeslagen.',
  'additional_cert_empty'               : 'Nog geen certificaten toegevoegd',
  'additional_lang_section_title'       : 'Talen',
  'additional_lang_add_hint'            : 'bijv. Spaans',
  'additional_lang_snack_max'           : 'Maximum van {n} taalvermeldingen bereikt.',
  'additional_lang_empty'               : 'Nog geen talen toegevoegd',
  'additional_hobby_section_title'      : "Hobby's & Interesses",
  'additional_hobby_add_hint'           : 'bijv. Fotografie',
  'additional_hobby_snack_max'          : "Maximum van {n} hobby-vermeldingen bereikt.",
  'additional_hobby_empty'              : "Nog geen hobby's toegevoegd",
  'additional_section_hint'             : 'Aangevinkte vermeldingen zijn opgenomen in dit CV. Je selecties worden automatisch opgeslagen.',
  'additional_nav_next'                 : 'Doorgaan naar referenties',
  'cert_sheet_title_add'                : 'Certificaat toevoegen',
  'cert_sheet_title_edit'               : 'Certificaat bewerken',
  'cert_sheet_sub'                      : 'Voeg een kwalificatie, certificaat of professioneel credential toe.',
  'cert_sheet_field_name'               : 'Naam van het certificaat *',
  'cert_sheet_field_issued_by'          : 'Uitgegeven door (optioneel)',
  'cert_sheet_field_short_desc'         : 'Korte beschrijving (optioneel)',
  'cert_sheet_hint_name'                : 'bijv. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'bijv. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'bijv. Behaald in 2024',
  'cert_sheet_btn_save'                 : 'Certificaat opslaan',
  'cert_sheet_btn_update'               : 'Certificaat bijwerken',
  'simple_sheet_title_add_language'     : 'Taal toevoegen',
  'simple_sheet_title_edit_language'    : 'Taal bewerken',
  'simple_sheet_title_add_hobby'        : 'Hobby toevoegen',
  'simple_sheet_title_edit_hobby'       : 'Hobby bewerken',
  'simple_sheet_btn_save'               : 'Opslaan',
  'simple_sheet_btn_update'             : 'Bijwerken',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contact',
  'pdf_section_about_me'                : 'Over mij',
  'pdf_section_summary'                 : 'Samenvatting',
  'pdf_section_summary_short'           : 'Samenvatting',
  'pdf_section_profile'                 : 'Profiel',
  'pdf_section_experience'              : 'Ervaring',
  'pdf_section_experience_short'        : 'Ervaring',
  'pdf_section_education'               : 'Opleiding',
  'pdf_section_skills'                  : 'Vaardigheden',
  'pdf_section_languages'               : 'Talen',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefoon',
  'pdf_label_location'                  : 'Locatie',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV-limiet bereikt',
  'limit_dialog_body'                   : "U heeft het maximum van 30 CV's bereikt. Verwijder een bestaand CV voordat u een nieuw aanmaakt.",
  'limit_dialog_go_to_my_cvs'           : "Naar Mijn CV's",
  'limit_dialog_cancel'                 : 'Annuleren',
  'refs_count_summary'                  : '{checked}/{maxChecked} geselecteerd · {saved}/{maxSaved} opgeslagen',
  'refs_selected_badge'                 : '{n} geselecteerd',
  'refs_empty_message'                  : 'Nog geen referenties opgeslagen',
  'refs_empty_sub'                      : 'Tik hierboven om een persoonlijke referentie toe te voegen',
};