// lib/language_keys/lang_id_indonesian.dart
//
// Indonesian (Bahasa Indonesia) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> idIndonesian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Tidak ada bahasa ditemukan',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Lewati',
  'onboarding_next'                     : 'Berikutnya',
  'onboarding_get_started'              : 'Mulai Sekarang',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Selamat Datang',
  'ob1_title'                           : 'Buat CV yang\nMembuka Peluang',
  'ob1_body'                            : 'Tampil menonjol di antara ratusan pelamar. Buat CV yang rapi dan memenangkan pekerjaan dalam hitungan menit — tanpa keahlian desain.',
  'ob1_pill_label'                      : 'Pembuat CV Profesional',
  'ob1_chip_templates'                  : '24+ Templat',
  'ob1_chip_pdf'                        : 'Ekspor PDF',
  'ob1_chip_free'                       : 'Gratis',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Templat',
  'ob2_title'                           : 'Setiap Industri.\nSetiap Ambisi.',
  'ob2_body'                            : 'Dari tata letak siap rapat direksi hingga desain kreatif yang berani — templat yang menceritakan kisah Anda.',
  'ob2_tap_hint'                        : 'Ketuk templat mana saja untuk pratinjau',
  'ob2_tpl_executive'                   : 'Eksekutif',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Mewah',
  'ob2_tag_corporate'                   : 'Korporat',
  'ob2_tag_creative'                    : 'Kreatif',
  'ob2_tag_minimal'                     : 'Minimalis',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Tata Letak Cerdas',
  'ob3_title'                           : 'CV Anda.\nTertata Sempurna.',
  'ob3_body'                            : 'Tata Letak Cerdas menyusun ulang bagian-bagian CV Anda untuk dampak maksimal — menempatkan konten terkuat di tempat yang pertama dilihat perekrut.',
  'ob3_badge_smart_layout'              : 'Tata Letak Cerdas',
  'ob3_badge_cv_ready'                  : 'CV Siap!',
  'ob3_step1_label'                     : 'Pilih Templat',
  'ob3_step1_desc'                      : 'Pilih dari 24+ desain memukau.',
  'ob3_step2_label'                     : 'Isi Detail Anda',
  'ob3_step2_desc'                      : 'Kolom terpandu untuk semua bagian.',
  'ob3_step3_label'                     : 'Tata Letak Cerdas',
  'ob3_step3_desc'                      : 'Satu ketukan menyempurnakan CV Anda.',
  'ob3_step4_label'                     : 'Ekspor sebagai PDF',
  'ob3_step4_desc'                      : 'PDF sempurna piksel siap dikirim.',
  'ob3_section_work'                    : 'Pengalaman Kerja',
  'ob3_section_education'               : 'Pendidikan',
  'ob3_section_skills'                  : 'Keahlian',
  'ob3_section_references'              : 'Referensi',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Siap Digunakan',
  'ob4_title'                           : 'Mengapa Kandidat Terbaik\nMemilih CV Builder',
  'ob4_visual_headline'                 : 'Semuanya Siap!',
  'ob4_visual_subline'                  : 'Semua yang Anda butuhkan untuk mendapatkan pekerjaan.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Templat',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Maks CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Ekspor',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Pribadi',
  'ob4_hl1_title'                       : 'Pribadi & Aman',
  'ob4_hl1_sub'                         : 'Data tersimpan di perangkat Anda.',
  'ob4_hl2_title'                       : 'Simpan Otomatis',
  'ob4_hl2_sub'                         : 'Setiap ketikan tersimpan seketika.',
  'ob4_hl3_title'                       : 'Hingga 30 CV',
  'ob4_hl3_sub'                         : 'CV unik untuk setiap peran.',
  'ob4_hl4_title'                       : 'Bagikan Satu Ketukan',
  'ob4_hl4_sub'                         : 'Kirim PDF tanpa meninggalkan aplikasi.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Tampil menonjol dari yang lain',
  'home_hero_title'                     : 'Buat CV\nProfesional Anda',
  'home_hero_sub'                       : 'Buat resume memukau\ndalam hitungan menit',
  'home_hero_cta'                       : 'Mulai Membuat',
  'home_premium_soon'                   : 'Upgrade ke Pro segera hadir!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Terbaru',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Terakhir Diedit',
  'history_sort_by_template'            : 'Berdasarkan Templat',
  'history_sort_sheet_title'            : 'Urutkan Berdasarkan',
  'history_sort_alphabetical_full'      : 'Alfabet (A–Z)',
  'history_premium_soon'                : 'Upgrade ke Pro segera hadir!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Pengaturan',
  'settings_section_preferences'        : 'Preferensi',
  'settings_section_support'            : 'Dukungan',
  'settings_section_legal'              : 'Hukum',
  'settings_section_about'              : 'Tentang',
  'settings_language_tile_title'        : 'Bahasa',
  'settings_dark_mode_title'            : 'Mode Gelap',
  'settings_dark_mode_on'               : 'Tema gelap aktif',
  'settings_dark_mode_off'              : 'Tema terang aktif',
  'settings_help_faq_title'             : 'Bantuan & FAQ',
  'settings_help_faq_sub'               : 'Jawaban atas pertanyaan umum',
  'settings_contact_support_title'      : 'Hubungi Dukungan',
  'settings_rate_app_title'             : 'Beri Nilai Aplikasi',
  'settings_rate_app_sub'               : 'Menyukai aplikasinya? Tinggalkan ulasan!',
  'settings_privacy_policy_title'       : 'Kebijakan Privasi',
  'settings_terms_title'                : 'Syarat Layanan',
  'settings_app_version_title'          : 'Versi Aplikasi',
  'settings_email_error'                : 'Tidak dapat membuka aplikasi email. Silakan kirim email ke cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Pratinjau CV',
  'preview_header_sub'                  : 'Siap diekspor',
  'preview_generating'                  : 'Membuat CV Anda...',
  'preview_failed_title'                : 'Pratinjau Gagal',
  'preview_failed_error'                : 'Kesalahan: {error}',
  'preview_go_back'                     : 'Kembali',
  'preview_no_data'                     : 'Tidak ada data tersedia',
  'preview_btn_print'                   : 'Cetak',
  'preview_btn_download'                : 'Unduh & Bagikan',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Bantuan & FAQ',
  'faq_category_all'                    : 'Semua',
  'faq_empty'                           : 'Tidak ada hasil ditemukan',
  'faq_contact_headline'                : 'Masih butuh bantuan?',
  'faq_contact_sub'                     : 'Tim kami siap membantu Anda.',
  'faq_contact_btn'                     : 'Hubungi',
  'faq_email_error'                     : 'Tidak dapat membuka aplikasi email. Silakan kirim email ke cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Memulai',
  'faq_cat_templates'                   : 'Templat',
  'faq_cat_editing'                     : 'Pengeditan',
  'faq_cat_exporting'                   : 'Mengekspor',
  'faq_cat_data_privacy'                : 'Data & Privasi',
  'faq_cat_troubleshooting'             : 'Pemecahan Masalah',
  'faq_q1'  : 'Bagaimana cara membuat CV pertama saya?',
  'faq_a1'  : 'Ketuk tombol "+" di layar beranda untuk memulai CV baru. Pilih templat yang sesuai dengan gaya Anda, lalu isi detail pribadi, pengalaman kerja, pendidikan, dan keahlian Anda langkah demi langkah. Kemajuan Anda tersimpan secara otomatis.',
  'faq_q2'  : 'Bisakah saya membuat lebih dari satu CV?',
  'faq_a2'  : 'Ya! Anda dapat membuat beberapa CV untuk peran atau industri yang berbeda. Setiap CV disimpan secara terpisah, sehingga Anda dapat menyesuaikannya untuk lamaran pekerjaan tertentu.',
  'faq_q3'  : 'Bagaimana cara mengubah templat CV saya?',
  'faq_a3'  : 'Buka CV Anda, ketuk ikon templat di bagian atas layar, dan telusuri templat yang tersedia. Ketuk templat mana saja untuk melihat pratinjau dengan konten Anda yang sudah ada. Konfirmasi untuk menerapkannya.',
  'faq_q4'  : 'Apakah ada templat gratis dan premium?',
  'faq_a4'  : 'Ya. Pilihan templat profesional tersedia secara gratis. Templat premium dengan desain canggih dan palet warna tersedia melalui pembelian sekali atau langganan.',
  'faq_q5'  : 'Bagaimana cara menambah atau menghapus bagian?',
  'faq_a5'  : 'Di editor CV, gulir ke bagian bawah layar dan ketuk "Tambah Bagian" untuk menyertakan tambahan seperti Bahasa, Sertifikasi, atau Pekerjaan Sukarela. Untuk menghapus bagian, ketuk header bagian dan pilih "Hapus".',
  'faq_q6'  : 'Bagaimana cara mengatur ulang bagian?',
  'faq_a6'  : 'Tekan lama gagang seret (≡) di samping header bagian mana saja dan seret ke posisi yang Anda inginkan. Perubahan disimpan secara otomatis.',
  'faq_q7'  : 'Bagaimana cara mengekspor CV saya sebagai PDF?',
  'faq_a7'  : 'Buka CV Anda dan ketuk tombol ekspor (ikon bagikan) di sudut kanan atas. Pilih "Ekspor sebagai PDF." Anda kemudian dapat menyimpannya ke perangkat Anda, membagikannya melalui email, WhatsApp, atau mengunggahnya langsung ke papan lowongan kerja.',
  'faq_q8'  : 'Format file apa yang didukung?',
  'faq_a8'  : 'Saat ini Aplikasi mendukung ekspor CV Anda sebagai PDF berkualitas tinggi. Format tambahan dapat ditambahkan di pembaruan mendatang.',
  'faq_q9'  : 'Di mana data CV saya disimpan?',
  'faq_a9'  : 'Semua data CV Anda disimpan secara lokal di perangkat Anda. Kami tidak mengunggah informasi pribadi Anda ke server kami. Ini berarti data Anda tetap pribadi dan dapat diakses secara offline.',
  'faq_q10' : 'Bagaimana cara mencadangkan CV saya?',
  'faq_a10' : 'CV Anda disertakan dalam cadangan standar perangkat Anda (cadangan Google Drive di Android, iCloud di iOS) jika Anda mengaktifkan pencadangan di pengaturan perangkat. Anda juga dapat mengekspor CV individual sebagai PDF untuk menyimpan salinannya.',
  'faq_q11' : 'Aplikasi berjalan lambat. Apa yang harus saya lakukan?',
  'faq_a11' : 'Coba tutup dan buka kembali aplikasi. Jika masalah berlanjut, mulai ulang perangkat Anda. Pastikan Anda memiliki versi terbaru aplikasi yang terinstal dari Play Store / App Store.',
  'faq_q12' : 'CV saya tidak diekspor dengan benar. Apa yang harus saya lakukan?',
  'faq_a12' : 'Pastikan Anda memiliki cukup ruang penyimpanan di perangkat Anda. Coba kurangi gambar besar dalam CV Anda. Jika masalah berlanjut, silakan hubungi tim dukungan kami.',
  'faq_q13' : 'Saya lupa menyimpan — apakah pekerjaan saya hilang?',
  'faq_a13' : 'Sama sekali tidak! Aplikasi menyimpan kemajuan Anda secara terus-menerus saat Anda mengedit.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Karier Anda, disempurnakan',
  'header_tooltip_back'                 : 'Kembali',
  'header_tooltip_my_cvs'               : 'CV Saya',
  'header_tooltip_settings'             : 'Pengaturan',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV Saya',
  'saved_count_single'                  : '{n} dokumen',
  'saved_count_plural'                  : '{n} dokumen',
  'saved_limit_reached'                 : 'Batas tercapai',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Semua',
  'saved_filter_draft'                  : 'Draf',
  'saved_filter_complete'               : 'Lengkap',
  'saved_status_complete'               : 'Lengkap',
  'saved_status_saved'                  : 'Tersimpan',
  'saved_status_draft'                  : 'Draf',
  'saved_empty_title'                   : 'Belum ada CV di sini',
  'saved_empty_sub'                     : 'Mulai buat CV pertama Anda di atas',
  'saved_search_empty_title'            : 'Tidak ada hasil ditemukan',
  'saved_search_empty_sub'              : 'Coba kata kunci pencarian lain',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Skema Warna',
  'custom_font_settings_title'          : 'Pengaturan Font',
  'custom_font_family_label'            : 'Keluarga Font',
  'custom_font_size_label'              : 'Ukuran Font: ',
  'custom_current_template_title'       : 'Templat Saat Ini',
  'custom_change_template_btn'          : 'Ganti Templat',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klasik',
  'custom_tpl_professional'             : 'Profesional',
  'custom_tpl_creative'                 : 'Kreatif',
  'custom_tpl_minimal'                  : 'Minimalis',
  'custom_tpl_modern_desc'              : 'Desain bersih dan kontemporer',
  'custom_tpl_classic_desc'             : 'Tata letak profesional tradisional',
  'custom_tpl_professional_desc'        : 'Templat berorientasi bisnis',
  'custom_tpl_creative_desc'            : 'Tampil menonjol dengan desain unik',
  'custom_tpl_minimal_desc'             : 'Gaya sederhana dan elegan',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Pilih Templat',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Eksekutif',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Mewah',
  'tpl_executive_tag'                   : 'Paling Populer',
  'tpl_nordic_tag'                      : 'Bersih',
  'tpl_vibrant_tag'                     : 'Kreatif',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Tegas & berwibawa untuk peran senior',
  'tpl_nordic_desc'                     : 'Kejelasan minimalis yang dipercaya perusahaan terkemuka',
  'tpl_vibrant_desc'                    : 'Tampil menonjol dengan energi dan warna',
  'tpl_tech_dark_desc'                  : 'Estetika terminal untuk pengembang',
  'tpl_luxury_desc'                     : 'Prestise aksen emas di latar hitam',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Templat',
  'detail_step_personal'                : 'Pribadi',
  'detail_step_experience'              : 'Pengalaman',
  'detail_step_education'               : 'Pendidikan',
  'detail_step_skills'                  : 'Keahlian',
  'detail_step_additional'              : 'Tambahan',
  'detail_step_references'              : 'Referensi',
  'detail_step_customize'               : 'Kustomisasi',
  'detail_banner_heading'               : 'Hampir selesai!',
  'detail_banner_btn'                   : 'Lanjutkan',
  'detail_banner_completion_label'      : 'Penyelesaian',
  'detail_stat_created_label'           : 'Dibuat',
  'detail_stat_steps_label'             : 'Langkah selesai',
  'detail_section_template_style'       : 'Gaya Templat',
  'detail_section_steps'                : 'Langkah',
  'detail_steps_counter'                : '{done} dari {total} selesai',
  'detail_step_sub'                     : 'Langkah {n} dari {total}',
  'detail_section_activity'             : 'Aktivitas',
  'detail_activity_created'             : 'Dibuat',
  'detail_activity_last_edited'         : 'Terakhir Diedit',
  'detail_activity_template'            : 'Templat',
  'detail_btn_continue_editing'         : 'Lanjutkan Pengeditan',
  'detail_btn_edit_cv'                  : 'Edit CV',
  'detail_option_rename'                : 'Ganti Nama CV',
  'detail_option_delete'                : 'Hapus CV',
  'detail_rename_title'                 : 'Ganti Nama CV',
  'detail_rename_hint'                  : 'mis. CV Software Engineer',
  'detail_rename_error_empty'           : 'Nama tidak boleh kosong',
  'detail_rename_btn_cancel'            : 'Batal',
  'detail_rename_btn_save'              : 'Simpan',
  'detail_rename_snackbar'              : 'Diubah menjadi "{name}"',
  'detail_delete_title'                 : 'Hapus CV?',
  'detail_delete_body'                  : 'Ini akan menghapus "{name}" secara permanen. Tindakan ini tidak dapat dibatalkan.',
  'detail_delete_btn_cancel'            : 'Batal',
  'detail_delete_btn_confirm'           : 'Hapus',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Selesai',
  'detail_check_tile_incomplete'        : 'Belum diisi',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Pilih Templat Anda',
  'chooser_subtitle'                    : 'Geser untuk menelusuri  ·  Ketuk untuk memilih  ·  Tahan untuk pratinjau',
  'chooser_card_hold_hint'              : 'Tahan untuk pratinjau',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Dipilih',
  'chooser_modal_heading'               : 'Beri Nama CV Anda',
  'chooser_modal_sub'                   : 'Beri nama agar mudah ditemukan di CV Saya dan Riwayat.',
  'chooser_modal_field_label'           : 'Nama CV',
  'chooser_modal_save_btn'              : 'Simpan & Mulai Membuat',
  'chooser_modal_divider'               : 'atau lanjutkan CV yang sudah ada',
  'chooser_nav_selected_sub'            : 'Templat dipilih',
  'chooser_nav_cta'                     : 'Simpan & Lanjutkan',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Jumlah Entri Maksimum Tercapai',
  'editor_show_hide'                    : 'Tampilkan/Sembunyikan',
  'editor_editing_badge'                : 'Mengedit',
  'editor_field_required'               : 'Wajib diisi',
  'editor_tooltip_edit'                 : 'Edit',
  'editor_tooltip_delete'               : 'Hapus',
  'editor_date_start'                   : 'Tanggal Mulai *',
  'editor_date_end'                     : 'Tanggal Selesai *',
  'editor_date_tap_hint'                : 'Ketuk untuk memilih',
  'editor_date_dialog_title'            : 'Pilih Bulan & Tahun',
  'editor_date_confirm'                 : 'Konfirmasi',
  'editor_panel_hide'                   : 'Sembunyikan',
  'editor_panel_show'                   : 'Tampilkan',
  'editor_validator_max_chars'          : 'Maks {n} karakter',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Buat CV Anda',
  'editor_header_step_sub'              : 'Langkah {current} dari {total} · {label}',
  'editor_step_template'                : 'Templat',
  'editor_step_personal'                : 'Pribadi',
  'editor_step_experience'              : 'Pengalaman',
  'editor_step_education'               : 'Pendidikan',
  'editor_step_skills'                  : 'Keahlian',
  'editor_step_additional'              : 'Tambahan',
  'editor_step_references'              : 'Referensi',
  'editor_step_customize'               : 'Kustomisasi',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Kustomisasi',
  'customize_subtitle'                  : 'Jadikan CV Anda unik',
  'customize_smart_layout_btn'          : 'Tata Letak Cerdas',
  'customize_back_to_top'               : 'Kembali ke Atas',
  'customize_done_title'                : 'Semuanya siap!',
  'customize_done_sub'                  : 'Ketuk Pratinjau CV di bawah untuk melihat CV Anda yang sudah selesai',
  'customize_preview_btn'               : 'Pratinjau CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Skema Warna',
  'color_black'                         : 'Hitam',
  'color_blue'                          : 'Biru',
  'color_nordic_blue'                   : 'Biru Nordic',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Teal',
  'color_green'                         : 'Hijau',
  'color_purple'                        : 'Ungu',
  'color_orange'                        : 'Oranye',
  'color_red'                           : 'Merah',
  'color_executive_gold'                : 'Emas Eksekutif',
  'color_vibrant_coral'                 : 'Koral Vibrant',
  'color_white'                         : 'Putih',
  'color_white_bg'                      : 'Latar Putih',
  'color_maroon'                        : 'Merah Tua',
  'color_brutalist_yellow'              : 'Kuning Brutalis',
  'color_neon_blue'                     : 'Biru Neon',
  'color_blueprint_navy'                : 'Biru Tua Blueprint',
  'color_light_grey'                    : 'Abu-abu Muda',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Keluarga Font',
  'customize_font_picker_title'         : 'Pilih Font',
  'customize_font_picker_sub'           : 'Setiap font ditampilkan dalam jenis hurufnya sendiri',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Ukuran Font',
  'customize_font_size_label'           : 'Ukuran Teks',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Ukuran Gambar',
  'customize_image_size_label'          : 'Ukuran Gambar',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Pratinjau Langsung',
  'preview_page_count_singular'         : '1 halaman',
  'preview_page_count_plural'           : '{n} halaman',
  'preview_page_of'                     : 'Halaman {page} dari {total}',
  'preview_live_hint'                   : 'Perubahan diterapkan seketika',
  'preview_template_unregistered'       : 'Belum terdaftar di customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Mempersiapkan CV Anda…',
  'preview_bar_print'                   : 'Cetak',
  'preview_bar_save_pdf'                : 'Simpan sebagai PDF',
  'preview_bar_share'                   : 'Bagikan',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Pratinjau CV',
  'preview_screen_sub'                  : '{n} {unit} · persis seperti dicetak',
  'preview_page_singular'               : 'halaman',
  'preview_page_plural'                 : 'halaman',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'CV Saya',
  'preview_snack_print_failed'          : 'Pencetakan gagal: {e}',
  'preview_snack_saved'                 : 'CV tersimpan ke Unduhan ✓',
  'preview_snack_export_failed'         : 'Ekspor gagal: {e}',
  'preview_snack_share_failed'          : 'Berbagi gagal: {e}',
  'preview_template_not_registered'     : 'Templat tidak terdaftar',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Tutup pratinjau',
  'preview_modal_hint_photo'            : 'Mendukung foto profil  ·  Ketuk kartu untuk memilih',
  'preview_modal_hint_no_photo'         : 'Ketuk kartu templat untuk memilihnya',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV Saya',
  'time_just_now'                       : 'Baru saja',
  'time_minutes_ago'                    : '{n} mnt lalu',
  'time_hours_ago'                      : '{n} jam lalu',
  'time_yesterday'                      : 'Kemarin',
  'time_days_ago'                       : '{n} hari lalu',
  'time_one_week_ago'                   : '1 minggu lalu',
  'time_weeks_ago'                      : '{n} minggu lalu',

  // ─── preview_registry.dart — shared tag labels ───────────────────────────
  'tpl_tag_elegant'                     : 'Elegan',
  'tpl_tag_classic'                     : 'Klasik',
  'tpl_tag_minimal'                     : 'Minimalis',
  'tpl_tag_creative'                    : 'Kreatif',
  'tpl_tag_bold'                        : 'Tegas',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradien',
  'tpl_gradient_desc'                   : 'Kartu gradien dari teal ke violet',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Gaya majalah merah & krim',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Lembut',
  'tpl_pastel_soft_desc'                : 'Bilah samping lavender, kartu lembut',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalis',
  'tpl_brutalist_desc'                  : 'Grid mentah, batas tebal & kuning',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Zamrud',
  'tpl_emerald_desc'                    : 'Hijau hutan dengan garis waktu',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografis',
  'tpl_infographic_desc'                : 'Kanvas gelap dengan grafik cincin',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Kemewahan geometris emas tahun 1920-an',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Gelap',
  'tpl_wina_dark_desc'                  : 'Infografis gelap dengan cincin',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Oranye',
  'tpl_rio_orange_desc'                 : 'Bilah samping gelap dengan sentuhan oranye',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Musim Panas',
  'tpl_summer_desc'                     : 'Minimalis bersih, nada abu-abu lembut',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Nada beige hangat yang elegan',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Klasik hitam putih yang mencolok',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Tata letak klasik ramah ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Gelap',
  'tpl_tony_dark_desc'                  : 'Gaya infografis oranye gelap',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Gambar teknis di atas grid',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arsivis',
  'tpl_archivist_desc'                  : 'Tata letak label dua kolom klasik',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Header berteduh dengan penanda berlian',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Header terpusat, perusahaan aksen',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nama tebal, titik garis waktu & pencapaian',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informasi Pribadi',
  'personal_subtitle'                   : 'Ceritakan kepada pemberi kerja siapa Anda',
  'personal_profile_counter'            : '{n}/{max} profil',
  'personal_info_banner'                : 'Simpan hingga 5 profil dan pilih satu per CV. Pilihan Anda diingat untuk setiap CV secara terpisah.',
  'personal_snack_max'                  : 'Maksimum {n} profil tercapai.',
  'personal_add_btn'                    : 'Tambah Profil Baru',
  'personal_library_title'              : 'Profil Tersimpan',
  'personal_selected_one'               : '1 dipilih',
  'personal_selected_none'              : 'tidak ada yang dipilih',
  'personal_library_hint'               : 'Ketuk kartu untuk memilihnya hanya untuk CV ini. CV lain menyimpan pilihan independen mereka sendiri.',
  'personal_empty_message'              : 'Belum ada profil tersimpan',
  'personal_empty_sub'                  : 'Ketuk di atas untuk menambahkan informasi pribadi Anda',
  'personal_nav_next'                   : 'Simpan & Lanjutkan',
  'personal_card_active_badge'          : 'Aktif untuk CV ini',
  'personal_sheet_title_add'            : 'Profil Baru',
  'personal_sheet_title_edit'           : 'Edit Profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALIS',
  'personal_sheet_brutalist_banner'     : 'Templat Brutalis memiliki kolom kontak yang ringkas. Nilai yang lebih pendek (mis. hanya kota) tampil paling baik.',
  'personal_section_photo'              : 'Foto Profil',
  'personal_section_basic'              : 'Detail Dasar',
  'personal_section_contact'            : 'Kontak',
  'personal_section_online'             : 'Kehadiran Online',
  'personal_section_summary'            : 'Ringkasan Profesional',
  'personal_field_first_name'           : 'Nama Depan *',
  'personal_field_last_name'            : 'Nama Belakang',
  'personal_field_job_title'            : 'Jabatan *',
  'personal_field_email'                : 'Alamat Email *',
  'personal_field_phone'                : 'Nomor Telepon *',
  'personal_field_location'             : 'Lokasi',
  'personal_field_location_brut'        : 'Lokasi (hanya kota)',
  'personal_field_website'              : 'Situs Web / Portofolio',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'mis. Budi',
  'personal_hint_last_name'             : 'mis. Santoso',
  'personal_hint_job_title'             : 'mis. Senior Engineer',
  'personal_hint_email'                 : 'mis. budi@example.com',
  'personal_hint_phone'                 : 'mis. +62 812 3456 7890',
  'personal_hint_location'              : 'mis. Jakarta, Indonesia',
  'personal_hint_location_brut'         : 'mis. Jakarta',
  'personal_hint_website'               : 'mis. github.com/budisantoso',
  'personal_hint_website_brut'          : 'mis. github.com/budi',
  'personal_hint_linkedin'              : 'mis. linkedin.com/in/budisantoso',
  'personal_hint_linkedin_brut'         : 'mis. linkedin.com/in/budi',
  'personal_summary_hint_label'         : 'Tetap singkat — ini muncul di bagian atas CV Anda.',
  'personal_hint_summary'               : 'Ringkasan singkat 2–3 kalimat tentang latar belakang dan tujuan Anda...',
  'personal_validator_email'            : 'Masukkan email yang valid',
  'personal_field_char_limit_tooltip'   : 'Batas karakter tercapai',
  'personal_sheet_btn_save'             : 'Simpan Profil',
  'personal_sheet_btn_update'           : 'Simpan Perubahan',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Pilih Foto',
  'photo_option_gallery'                : 'Pilih dari Galeri',
  'photo_option_camera'                 : 'Ambil Foto',
  'photo_option_reposition'             : 'Atur Ulang Posisi Foto',
  'photo_option_remove'                 : 'Hapus Foto',
  'photo_status_added'                  : 'Foto ditambahkan ✓',
  'photo_status_empty'                  : 'Tambahkan foto profesional',
  'photo_chip_gallery'                  : 'Galeri',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Atur Posisi',
  'photo_reposition_title'              : 'Atur Ulang Posisi Foto',
  'photo_reposition_sub'                : 'Seret foto untuk menyesuaikan posisinya',
  'photo_reposition_reset'              : 'Atur ulang ke tengah',
  'photo_reposition_apply'              : 'Terapkan',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Keahlian',
  'skills_subtitle'                     : 'Tonjolkan kemampuan utama Anda',
  'skills_add_btn'                      : 'Tambah Keahlian Baru',
  'skills_snack_max_icons'              : 'Maksimum 10 ikon dipilih.',
  'skills_snack_max_skills'             : 'Batas 15 keahlian tercapai.',
  'skills_library_title'                : 'Keahlian Tersimpan',
  'skills_library_hint'                 : 'Keahlian yang dicentang disertakan dalam CV ini. Pilihan Anda disimpan secara otomatis.',
  'skills_nav_next'                     : 'Lanjut ke Tambahan',
  'skills_wina_header_icon_bar'         : 'Bilah Ikon Header',
  'skills_wina_on'                      : 'AKTIF',
  'skills_wina_off'                     : 'NONAKTIF',
  'skills_wina_bar_on_sub'              : 'Lingkaran ikon berwarna ditampilkan di header CV.',
  'skills_wina_bar_off_sub'             : 'Baris ikon disembunyikan — lebih banyak ruang untuk info kontak.',
  'skills_wina_palette_hint'            : 'Ikon muncul sebagai lingkaran berwarna sesuai urutan palet.',
  'skills_wina_preview_label'           : 'Pratinjau',
  'skills_wina_disabled_hint'           : 'Aktifkan bilah ikon di atas untuk memilih ikon mana yang muncul di header CV.',
  'skills_sheet_title_add'              : 'Tambah Keahlian',
  'skills_sheet_title_edit'             : 'Edit Keahlian',
  'skills_sheet_field_name'             : 'Nama Keahlian *',
  'skills_sheet_hint_short'             : 'mis. Flutter, Desain',
  'skills_sheet_hint_long'              : 'mis. Flutter, Manajemen Proyek',
  'skills_sheet_validator_max'          : 'Maks {n} karakter',
  'skills_sheet_proficiency'            : 'Tingkat Kemahiran',
  'skills_sheet_beginner'               : 'Pemula',
  'skills_sheet_expert'                 : 'Ahli',
  'skills_sheet_btn_save'               : 'Simpan Keahlian',
  'skills_sheet_btn_update'             : 'Perbarui Keahlian',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referensi Pribadi',
  'refs_subtitle'                       : 'Orang-orang yang dapat menjamin Anda secara pribadi',
  'refs_add_btn'                        : 'Tambah Referensi Pribadi Baru',
  'refs_snack_max_selected'             : 'Maksimum 4 referensi dapat dipilih untuk satu CV.',
  'refs_snack_max_saved'                : 'Batas 10 referensi tersimpan tercapai.',
  'refs_library_title'                  : 'Referensi Tersimpan',
  'refs_library_hint'                   : 'Referensi yang dicentang disertakan dalam CV ini. Maks 4 per CV. Pilihan Anda disimpan secara otomatis.',
  'refs_nav_next'                       : 'Lanjut ke Kustomisasi',
  'refs_sheet_title_add'                : 'Tambah Referensi Pribadi',
  'refs_sheet_title_edit'               : 'Edit Referensi Pribadi',
  'refs_sheet_sub_add'                  : 'Seseorang yang dapat merekomendasikan Anda secara pribadi kepada pemberi kerja.',
  'refs_sheet_sub_edit'                 : 'Perbarui detail referensi ini di bawah.',
  'refs_sheet_field_name'               : 'Nama Lengkap *',
  'refs_sheet_field_title'              : 'Jabatan *',
  'refs_sheet_field_company'            : 'Perusahaan (opsional)',
  'refs_sheet_field_email'              : 'Alamat Email *',
  'refs_sheet_field_phone'              : 'Nomor Telepon *',
  'refs_sheet_hint_name'                : 'mis. Andi Wijaya',
  'refs_sheet_hint_title'               : 'mis. Manajer Teknik',
  'refs_sheet_hint_company'             : 'mis. PT Maju Bersama',
  'refs_sheet_hint_email'               : 'mis. andi@majubersama.com',
  'refs_sheet_hint_phone'               : 'mis. +62 812 3456 7890',
  'refs_sheet_validator_email'          : 'Masukkan alamat email yang valid',
  'refs_sheet_btn_save'                 : 'Simpan Referensi Pribadi',
  'refs_sheet_btn_update'               : 'Perbarui Referensi Pribadi',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Pengalaman Kerja',
  'exp_subtitle'                        : 'Tambahkan riwayat kerja Anda',
  'exp_banner_info'                     : 'Hingga {n} tanggung jawab per peran akan muncul di CV. 3–6 peran biasanya muat dalam 1–2 halaman.',
  'exp_add_btn'                         : 'Tambah Pengalaman Baru',
  'exp_snack_max_selected'              : 'Maksimum 8 pengalaman dapat dipilih untuk satu CV.',
  'exp_snack_max_saved'                 : 'Batas 12 pengalaman tersimpan tercapai.',
  'exp_library_title'                   : 'Pengalaman Tersimpan',
  'exp_library_hint'                    : 'Entri yang dicentang hanya disertakan dalam CV ini. CV lain menyimpan pilihan independen mereka sendiri.',
  'exp_nav_next'                        : 'Lanjut ke Pendidikan',
  'exp_empty_message'                   : 'Belum ada pengalaman ditambahkan',
  'exp_empty_sub'                       : 'Ketuk di atas untuk menambahkan peran pertama Anda',
  'exp_card_resp_singular'              : 'tanggung jawab',
  'exp_card_resp_plural'                : 'tanggung jawab',
  'exp_card_resp_tooltip'               : 'Hanya 8 tanggung jawab pertama yang akan muncul di CV',
  'exp_sheet_title_add'                 : 'Tambah Pengalaman',
  'exp_sheet_title_edit'                : 'Edit Pengalaman',
  'exp_sheet_field_job_title'           : 'Jabatan *',
  'exp_sheet_field_company'             : 'Perusahaan *',
  'exp_sheet_field_location'            : 'Lokasi',
  'exp_sheet_section_responsibilities'  : 'Tanggung Jawab Utama',
  'exp_sheet_resp_hint_info'            : 'Maks 8 poin · masing-masing 200 karakter',
  'exp_sheet_resp_label'                : 'Tanggung Jawab {n}',
  'exp_sheet_resp_hint'                 : 'mis. Memimpin tim 5 insinyur',
  'exp_sheet_resp_add_btn'              : 'Tambah Tanggung Jawab',
  'exp_sheet_resp_max_info'             : 'Batas {n} tanggung jawab tercapai',
  'exp_sheet_resp_validator_max'        : 'Maks 200 karakter',
  'exp_sheet_hint_job_title'            : 'mis. Senior Developer',
  'exp_sheet_hint_location'             : 'mis. Jakarta, Indonesia',
  'exp_sheet_btn_save'                  : 'Simpan Pengalaman',
  'exp_sheet_btn_update'                : 'Simpan Perubahan',
  'exp_date_present'                    : 'Sekarang / Peran Saat Ini',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Pendidikan',
  'edu_subtitle'                        : 'Tambahkan latar belakang akademis Anda',
  'edu_add_btn'                         : 'Tambah Pendidikan Baru',
  'edu_snack_max_selected'              : 'Maksimum 8 entri pendidikan dapat dipilih untuk satu CV.',
  'edu_snack_max_saved'                 : 'Batas 12 entri pendidikan tersimpan tercapai.',
  'edu_library_title'                   : 'Pendidikan Tersimpan',
  'edu_library_hint'                    : 'Entri yang dicentang disertakan dalam CV ini. Pilihan Anda disimpan secara otomatis.',
  'edu_nav_next'                        : 'Lanjut ke Keahlian',
  'edu_empty_message'                   : 'Belum ada pendidikan ditambahkan',
  'edu_empty_sub'                       : 'Ketuk di atas untuk menambahkan kualifikasi Anda',
  'edu_card_bullet_singular'            : 'poin',
  'edu_card_bullet_plural'              : 'poin',
  'edu_sheet_title_add'                 : 'Tambah Pendidikan',
  'edu_sheet_title_edit'                : 'Edit Pendidikan',
  'edu_sheet_field_degree'              : 'Gelar / Kualifikasi *',
  'edu_sheet_field_institution'         : 'Institusi *',
  'edu_sheet_section_key_points'        : 'Poin Utama',
  'edu_sheet_key_points_hint_info'      : 'Opsional · 1 poin · maks 100 karakter',
  'edu_sheet_point_label'               : 'Poin {n}',
  'edu_sheet_point_add_btn'             : 'Tambah Poin',
  'edu_sheet_point_max_info'            : 'Batas {n} poin tercapai',
  'edu_sheet_point_validator_max'       : 'Maks {n} karakter',
  'edu_sheet_hint_degree'               : 'mis. S1 Ilmu Komputer',
  'edu_sheet_hint_institution'          : 'mis. Universitas Indonesia',
  'edu_sheet_hint_bullet'               : 'mis. Lulus dengan Pujian',
  'edu_sheet_btn_save'                  : 'Simpan Pendidikan',
  'edu_sheet_btn_update'                : 'Simpan Perubahan',
  'edu_date_present'                    : 'Sekarang / Studi Saat Ini',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Info Tambahan',
  'additional_subtitle'                 : 'Sertifikasi, bahasa & lainnya',
  'additional_cert_section_title'       : 'Sertifikasi',
  'additional_cert_counter'             : '{sel}/{total} dipilih · maks {max}',
  'additional_cert_hide'                : 'Sembunyikan',
  'additional_cert_show'                : 'Tampilkan',
  'additional_cert_add_btn'             : 'Tambah',
  'additional_cert_snack_max'           : 'Batas {n} entri sertifikasi tercapai.',
  'additional_cert_hint'                : 'Entri yang dicentang disertakan dalam CV ini. Pilihan Anda disimpan secara otomatis.',
  'additional_cert_empty'               : 'Belum ada sertifikasi ditambahkan',
  'additional_lang_section_title'       : 'Bahasa',
  'additional_lang_add_hint'            : 'mis. Spanyol',
  'additional_lang_snack_max'           : 'Batas {n} entri bahasa tercapai.',
  'additional_lang_empty'               : 'Belum ada bahasa ditambahkan',
  'additional_hobby_section_title'      : 'Hobi & Minat',
  'additional_hobby_add_hint'           : 'mis. Fotografi',
  'additional_hobby_snack_max'          : 'Batas {n} entri hobi tercapai.',
  'additional_hobby_empty'              : 'Belum ada hobi ditambahkan',
  'additional_section_hint'             : 'Entri yang dicentang disertakan dalam CV ini. Pilihan Anda disimpan secara otomatis.',
  'additional_nav_next'                 : 'Lanjut ke Referensi',
  'cert_sheet_title_add'                : 'Tambah Sertifikasi',
  'cert_sheet_title_edit'               : 'Edit Sertifikasi',
  'cert_sheet_sub'                      : 'Tambahkan kualifikasi, sertifikat, atau kredensial profesional.',
  'cert_sheet_field_name'               : 'Nama Sertifikasi *',
  'cert_sheet_field_issued_by'          : 'Diterbitkan Oleh (opsional)',
  'cert_sheet_field_short_desc'         : 'Deskripsi Singkat (opsional)',
  'cert_sheet_hint_name'                : 'mis. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'mis. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'mis. Diraih 2024',
  'cert_sheet_btn_save'                 : 'Simpan Sertifikasi',
  'cert_sheet_btn_update'               : 'Perbarui Sertifikasi',
  'simple_sheet_title_add_language'     : 'Tambah Bahasa',
  'simple_sheet_title_edit_language'    : 'Edit Bahasa',
  'simple_sheet_title_add_hobby'        : 'Tambah Hobi',
  'simple_sheet_title_edit_hobby'       : 'Edit Hobi',
  'simple_sheet_btn_save'               : 'Simpan',
  'simple_sheet_btn_update'             : 'Perbarui',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontak',
  'pdf_section_about_me'                : 'Tentang Saya',
  'pdf_section_summary'                 : 'Ringkasan',
  'pdf_section_summary_short'           : 'Ringkasan',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Pengalaman',
  'pdf_section_experience_short'        : 'Pengalaman',
  'pdf_section_education'               : 'Pendidikan',
  'pdf_section_skills'                  : 'Keahlian',
  'pdf_section_languages'               : 'Bahasa',
  'pdf_label_email'                     : 'Email',
  'pdf_label_phone'                     : 'Telepon',
  'pdf_label_location'                  : 'Lokasi',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Batas CV Tercapai',
  'limit_dialog_body'                   : 'Anda telah mencapai maksimum 30 CV. Hapus CV yang ada sebelum membuat yang baru.',
  'limit_dialog_go_to_my_cvs'           : 'Ke CV Saya',
  'limit_dialog_cancel'                 : 'Batal',
  'refs_count_summary'                  : '{checked}/{maxChecked} dipilih · {saved}/{maxSaved} disimpan',
  'refs_selected_badge'                 : '{n} dipilih',
  'refs_empty_message'                  : 'Belum ada referensi yang disimpan',
  'refs_empty_sub'                      : 'Ketuk di atas untuk menambahkan referensi pribadi',
};