// lib/language_keys/lang_hi_hindi.dart
//
// Hindi — translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> hiHindi = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'कोई भाषा नहीं मिली',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'छोड़ें',
  'onboarding_next'                     : 'अगला',
  'onboarding_get_started'              : 'शुरू करें',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  स्वागत है',
  'ob1_title'                           : 'एक ऐसा रिज्यूमे बनाएं जो\nदरवाज़े खोले',
  'ob1_body'                            : 'सैकड़ों आवेदकों में अलग दिखें। कुछ ही मिनटों में एक पेशेवर और प्रभावशाली रिज्यूमे बनाएं — बिना किसी डिज़ाइन कौशल के।',
  'ob1_pill_label'                      : 'प्रोफेशनल CV बिल्डर',
  'ob1_chip_templates'                  : '24+ टेम्पलेट',
  'ob1_chip_pdf'                        : 'PDF निर्यात',
  'ob1_chip_free'                       : 'मुफ़्त',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  टेम्पलेट',
  'ob2_title'                           : 'हर उद्योग।\nहर लक्ष्य।',
  'ob2_body'                            : 'बोर्डरूम-रेडी डिज़ाइन से लेकर साहसी क्रिएटिव लेआउट तक — वह टेम्पलेट जो आपकी कहानी बयान करे।',
  'ob2_tap_hint'                        : 'पूर्वावलोकन के लिए किसी भी टेम्पलेट पर टैप करें',
  'ob2_tpl_executive'                   : 'एग्ज़ेक्यूटिव',
  'ob2_tpl_vibrant'                     : 'वाइब्रेंट',
  'ob2_tpl_nordic'                      : 'नॉर्डिक',
  'ob2_tpl_tech_dark'                   : 'टेक डार्क',
  'ob2_tpl_luxury'                      : 'लक्ज़री',
  'ob2_tag_corporate'                   : 'कॉर्पोरेट',
  'ob2_tag_creative'                    : 'क्रिएटिव',
  'ob2_tag_minimal'                     : 'मिनिमल',
  'ob2_tag_modern'                      : 'मॉडर्न',
  'ob2_tag_premium'                     : 'प्रीमियम',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  स्मार्ट लेआउट',
  'ob3_title'                           : 'आपका रिज्यूमे।\nव्यवस्थित।',
  'ob3_body'                            : 'स्मार्ट लेआउट आपके रिज्यूमे के अनुभागों को अधिकतम प्रभाव के लिए व्यवस्थित करता है — सबसे मजबूत सामग्री वहाँ रखता है जहाँ नियोक्ता पहले देखते हैं।',
  'ob3_badge_smart_layout'              : 'स्मार्ट लेआउट',
  'ob3_badge_cv_ready'                  : 'CV तैयार है!',
  'ob3_step1_label'                     : 'टेम्पलेट चुनें',
  'ob3_step1_desc'                      : '24+ सुंदर डिज़ाइनों में से चुनें।',
  'ob3_step2_label'                     : 'जानकारी भरें',
  'ob3_step2_desc'                      : 'हर अनुभाग के लिए गाइडेड फ़ील्ड।',
  'ob3_step3_label'                     : 'स्मार्ट लेआउट',
  'ob3_step3_desc'                      : 'एक टैप में रिज्यूमे पूरा हो जाता है।',
  'ob3_step4_label'                     : 'PDF निर्यात',
  'ob3_step4_desc'                      : 'उच्च गुणवत्ता वाला PDF भेजने के लिए तैयार।',
  'ob3_section_work'                    : 'कार्य अनुभव',
  'ob3_section_education'               : 'शिक्षा',
  'ob3_section_skills'                  : 'कौशल',
  'ob3_section_references'              : 'संदर्भ',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  शुरू करने के लिए तैयार',
  'ob4_title'                           : 'शीर्ष उम्मीदवार CV Builder\nक्यों चुनते हैं',
  'ob4_visual_headline'                 : 'सब कुछ तैयार है!',
  'ob4_visual_subline'                  : 'नौकरी पाने के लिए जो कुछ भी चाहिए।',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'टेम्पलेट',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'अधिकतम CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'निर्यात',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'निजी',
  'ob4_hl1_title'                       : 'निजी और सुरक्षित',
  'ob4_hl1_sub'                         : 'डेटा आपके डिवाइस पर रहता है।',
  'ob4_hl2_title'                       : 'ऑटो-सेव',
  'ob4_hl2_sub'                         : 'जो भी टाइप करें, तुरंत सेव हो जाता है।',
  'ob4_hl3_title'                       : '30 CV तक',
  'ob4_hl3_sub'                         : 'हर पद के लिए अनूठा रिज्यूमे।',
  'ob4_hl4_title'                       : 'एक टैप में शेयर करें',
  'ob4_hl4_sub'                         : 'ऐप छोड़े बिना PDF भेजें।',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ भीड़ से अलग दिखें',
  'home_hero_title'                     : 'अपना पेशेवर\nरिज्यूमे बनाएं',
  'home_hero_sub'                       : 'कुछ ही मिनटों में एक\nप्रभावशाली रिज्यूमे बनाएं',
  'home_hero_cta'                       : 'बनाना शुरू करें',
  'home_premium_soon'                   : 'Pro में अपग्रेड करें — जल्द आ रहा है!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'सबसे नया',
  'history_sort_alphabetical'           : 'अ–ज़',
  'history_sort_last_edited'            : 'अंतिम संपादित',
  'history_sort_by_template'            : 'टेम्पलेट अनुसार',
  'history_sort_sheet_title'            : 'इस आधार पर क्रमबद्ध करें',
  'history_sort_alphabetical_full'      : 'वर्णमाला (अ–ज़)',
  'history_premium_soon'                : 'Pro में अपग्रेड करें — जल्द आ रहा है!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'सेटिंग्स',
  'settings_section_preferences'        : 'प्राथमिकताएं',
  'settings_section_support'            : 'सहायता',
  'settings_section_legal'              : 'कानूनी',
  'settings_section_about'              : 'के बारे में',
  'settings_language_tile_title'        : 'भाषा',
  'settings_dark_mode_title'            : 'डार्क मोड',
  'settings_dark_mode_on'               : 'डार्क थीम सक्रिय है',
  'settings_dark_mode_off'              : 'लाइट थीम सक्रिय है',
  'settings_help_faq_title'             : 'सहायता और FAQ',
  'settings_help_faq_sub'               : 'सामान्य प्रश्नों के उत्तर',
  'settings_contact_support_title'      : 'सहायता से संपर्क करें',
  'settings_rate_app_title'             : 'ऐप को रेट करें',
  'settings_rate_app_sub'               : 'ऐप पसंद आ रहा है? समीक्षा दें!',
  'settings_privacy_policy_title'       : 'गोपनीयता नीति',
  'settings_terms_title'                : 'सेवा की शर्तें',
  'settings_app_version_title'          : 'ऐप संस्करण',
  'settings_email_error'                : 'ईमेल ऐप नहीं खुल सका। कृपया cyberinc101@gmail.com पर ईमेल करें',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'रिज्यूमे पूर्वावलोकन',
  'preview_header_sub'                  : 'निर्यात के लिए तैयार',
  'preview_generating'                  : 'रिज्यूमे बन रहा है...',
  'preview_failed_title'                : 'पूर्वावलोकन विफल रहा',
  'preview_failed_error'                : 'त्रुटि: {error}',
  'preview_go_back'                     : 'वापस जाएं',
  'preview_no_data'                     : 'कोई डेटा उपलब्ध नहीं',
  'preview_btn_print'                   : 'प्रिंट करें',
  'preview_btn_download'                : 'डाउनलोड और शेयर करें',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'सहायता और FAQ',
  'faq_category_all'                    : 'सभी',
  'faq_empty'                           : 'कोई परिणाम नहीं मिला',
  'faq_contact_headline'                : 'अभी भी सहायता चाहिए?',
  'faq_contact_sub'                     : 'हमारी टीम आपकी मदद के लिए तैयार है।',
  'faq_contact_btn'                     : 'संपर्क करें',
  'faq_email_error'                     : 'ईमेल ऐप नहीं खुल सका। कृपया cyberinc101@gmail.com पर ईमेल करें',
  'faq_cat_getting_started'             : 'शुरुआत करना',
  'faq_cat_templates'                   : 'टेम्पलेट',
  'faq_cat_editing'                     : 'संपादन',
  'faq_cat_exporting'                   : 'निर्यात',
  'faq_cat_data_privacy'                : 'डेटा और गोपनीयता',
  'faq_cat_troubleshooting'             : 'समस्या निवारण',
  'faq_q1'  : 'मैं अपना पहला रिज्यूमे कैसे बनाऊं?',
  'faq_a1'  : 'होम स्क्रीन पर "+" बटन टैप करें और एक नया रिज्यूमे शुरू करें। अपनी शैली के अनुसार टेम्पलेट चुनें, फिर व्यक्तिगत जानकारी, कार्य अनुभव, शिक्षा और कौशल चरण-दर-चरण दर्ज करें। आपकी प्रगति अपने आप सेव होती रहती है।',
  'faq_q2'  : 'क्या मैं एक से ज़्यादा रिज्यूमे बना सकता/सकती हूं?',
  'faq_a2'  : 'हाँ! आप अलग-अलग पदों या उद्योगों के लिए कई रिज्यूमे बना सकते हैं। हर रिज्यूमे अलग से सेव होता है ताकि आप उन्हें विशेष नौकरी आवेदनों के लिए कस्टमाइज़ कर सकें।',
  'faq_q3'  : 'मैं अपने रिज्यूमे का टेम्पलेट कैसे बदलूं?',
  'faq_a3'  : 'रिज्यूमे खोलें, स्क्रीन के ऊपर टेम्पलेट आइकन टैप करें और उपलब्ध टेम्पलेट ब्राउज़ करें। किसी भी टेम्पलेट पर टैप करके अपने मौजूदा कंटेंट के साथ पूर्वावलोकन देखें। लागू करने के लिए पुष्टि करें।',
  'faq_q4'  : 'क्या मुफ़्त और प्रीमियम टेम्पलेट हैं?',
  'faq_a4'  : 'हाँ। पेशेवर टेम्पलेट का एक सेट मुफ़्त में उपलब्ध है। उन्नत डिज़ाइन और रंग पैलेट वाले प्रीमियम टेम्पलेट एकमुश्त खरीद या सदस्यता के ज़रिए उपलब्ध हैं।',
  'faq_q5'  : 'मैं अनुभाग कैसे जोड़ूं या हटाऊं?',
  'faq_a5'  : 'रिज्यूमे एडिटर में नीचे स्क्रॉल करें और "अनुभाग जोड़ें" टैप करें — जैसे भाषाएं, सर्टिफिकेशन या स्वयंसेवा। किसी अनुभाग को हटाने के लिए उसका शीर्षक टैप करें और "हटाएं" चुनें।',
  'faq_q6'  : 'मैं अनुभागों का क्रम कैसे बदलूं?',
  'faq_a6'  : 'हर अनुभाग शीर्षक के पास ड्रैग हैंडल (≡) को देर तक दबाएं और अपनी मनचाही जगह खींचें। परिवर्तन अपने आप सेव हो जाते हैं।',
  'faq_q7'  : 'मैं अपना रिज्यूमे PDF के रूप में कैसे निर्यात करूं?',
  'faq_a7'  : 'रिज्यूमे खोलें और ऊपरी दाएं कोने में निर्यात बटन (शेयर आइकन) टैप करें। "PDF निर्यात करें" चुनें। फिर आप इसे डिवाइस पर सेव कर सकते हैं, ईमेल या WhatsApp से शेयर कर सकते हैं, या सीधे जॉब साइट पर अपलोड कर सकते हैं।',
  'faq_q8'  : 'कौन से फ़ाइल फॉर्मेट समर्थित हैं?',
  'faq_a8'  : 'वर्तमान में ऐप आपके रिज्यूमे को उच्च गुणवत्ता वाले PDF के रूप में निर्यात करने का समर्थन करता है। अन्य फॉर्मेट भविष्य के अपडेट में जोड़े जा सकते हैं।',
  'faq_q9'  : 'मेरा रिज्यूमे डेटा कहाँ सेव होता है?',
  'faq_a9'  : 'आपका सारा रिज्यूमे डेटा आपके डिवाइस पर स्थानीय रूप से सेव होता है। हम आपकी व्यक्तिगत जानकारी हमारे सर्वर पर अपलोड नहीं करते। इसका मतलब है आपका डेटा निजी रहता है और ऑफलाइन उपलब्ध है।',
  'faq_q10' : 'मैं अपने रिज्यूमे का बैकअप कैसे लूं?',
  'faq_a10' : 'आपके रिज्यूमे आपके डिवाइस के मानक बैकअप में शामिल होते हैं — Android पर Google Drive बैकअप, iOS पर iCloud — अगर डिवाइस सेटिंग में बैकअप सक्षम है। आप अलग-अलग रिज्यूमे PDF के रूप में भी निर्यात कर सकते हैं।',
  'faq_q11' : 'ऐप धीमा चल रहा है। मैं क्या करूं?',
  'faq_a11' : 'ऐप बंद करके फिर से खोलें। अगर समस्या बनी रहे तो डिवाइस को पुनः आरंभ करें। सुनिश्चित करें कि Play Store / App Store से ऐप का नवीनतम संस्करण इंस्टॉल है।',
  'faq_q12' : 'मेरा रिज्यूमे सही से निर्यात नहीं हो रहा। मैं क्या करूं?',
  'faq_a12' : 'सुनिश्चित करें कि आपके डिवाइस पर पर्याप्त स्टोरेज खाली है। रिज्यूमे में बड़ी छवियां कम करने की कोशिश करें। अगर समस्या जारी रहे, तो कृपया हमारी सपोर्ट टीम से संपर्क करें।',
  'faq_q13' : 'मैं सेव करना भूल गया/गई — क्या मेरा काम खो गया?',
  'faq_a13' : 'बिल्कुल नहीं! ऐप संपादन के दौरान आपकी प्रगति लगातार सेव करता रहता है।',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'आपका करियर, संपूर्ण',
  'header_tooltip_back'                 : 'वापस',
  'header_tooltip_my_cvs'               : 'मेरे CV',
  'header_tooltip_settings'             : 'सेटिंग्स',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'मेरे रिज्यूमे',
  'saved_count_single'                  : '{n} दस्तावेज़',
  'saved_count_plural'                  : '{n} दस्तावेज़',
  'saved_limit_reached'                 : 'सीमा पहुंच गई',
  'saved_footer_count'                  : '{n} / 30 रिज्यूमे',
  'saved_filter_all'                    : 'सभी',
  'saved_filter_draft'                  : 'ड्राफ्ट',
  'saved_filter_complete'               : 'पूर्ण',
  'saved_status_complete'               : 'पूर्ण',
  'saved_status_saved'                  : 'सेव किया',
  'saved_status_draft'                  : 'ड्राफ्ट',
  'saved_empty_title'                   : 'अभी कोई रिज्यूमे नहीं',
  'saved_empty_sub'                     : 'ऊपर से अपना पहला रिज्यूमे बनाना शुरू करें',
  'saved_search_empty_title'            : 'कोई परिणाम नहीं मिला',
  'saved_search_empty_sub'              : 'कोई दूसरा खोज शब्द आज़माएं',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'रंग योजना',
  'custom_font_settings_title'          : 'फ़ॉन्ट सेटिंग्स',
  'custom_font_family_label'            : 'फ़ॉन्ट परिवार',
  'custom_font_size_label'              : 'फ़ॉन्ट आकार: ',
  'custom_current_template_title'       : 'वर्तमान टेम्पलेट',
  'custom_change_template_btn'          : 'टेम्पलेट बदलें',
  'custom_tpl_modern'                   : 'मॉडर्न',
  'custom_tpl_classic'                  : 'क्लासिक',
  'custom_tpl_professional'             : 'प्रोफेशनल',
  'custom_tpl_creative'                 : 'क्रिएटिव',
  'custom_tpl_minimal'                  : 'मिनिमल',
  'custom_tpl_modern_desc'              : 'साफ और समकालीन डिज़ाइन',
  'custom_tpl_classic_desc'             : 'पारंपरिक पेशेवर लेआउट',
  'custom_tpl_professional_desc'        : 'व्यवसाय-केंद्रित टेम्पलेट',
  'custom_tpl_creative_desc'            : 'अनोखे डिज़ाइन के साथ अलग दिखें',
  'custom_tpl_minimal_desc'             : 'सरल और परिष्कृत शैली',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'टेम्पलेट चुनें',
  'swipe_photo_badge'                   : 'फ़ोटो',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'एग्ज़ेक्यूटिव',
  'tpl_nordic_name'                     : 'नॉर्डिक',
  'tpl_vibrant_name'                    : 'वाइब्रेंट',
  'tpl_tech_dark_name'                  : 'टेक डार्क',
  'tpl_luxury_name'                     : 'लक्ज़री',
  'tpl_executive_tag'                   : 'सबसे लोकप्रिय',
  'tpl_nordic_tag'                      : 'साफ-सुथरा',
  'tpl_vibrant_tag'                     : 'क्रिएटिव',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'एलीट',
  'tpl_executive_desc'                  : 'वरिष्ठ भूमिकाओं के लिए साहसी और प्रतिष्ठित',
  'tpl_nordic_desc'                     : 'शीर्ष कंपनियों द्वारा पसंद की जाने वाली न्यूनतम स्पष्टता',
  'tpl_vibrant_desc'                    : 'ऊर्जा और रंग के साथ अलग दिखें',
  'tpl_tech_dark_desc'                  : 'डेवलपर्स के लिए टर्मिनल-स्टाइल लुक',
  'tpl_luxury_desc'                     : 'काले पृष्ठभूमि पर सुनहरी भव्यता',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'टेम्पलेट',
  'detail_step_personal'                : 'व्यक्तिगत',
  'detail_step_experience'              : 'अनुभव',
  'detail_step_education'               : 'शिक्षा',
  'detail_step_skills'                  : 'कौशल',
  'detail_step_additional'              : 'अतिरिक्त',
  'detail_step_references'              : 'संदर्भ',
  'detail_step_customize'               : 'कस्टमाइज़',
  'detail_banner_heading'               : 'लगभग हो गया!',
  'detail_banner_btn'                   : 'जारी रखें',
  'detail_banner_completion_label'      : 'पूर्णता',
  'detail_stat_created_label'           : 'बनाया गया',
  'detail_stat_steps_label'             : 'चरण पूर्ण',
  'detail_section_template_style'       : 'टेम्पलेट शैली',
  'detail_section_steps'                : 'चरण',
  'detail_steps_counter'                : '{done} / {total} पूर्ण',
  'detail_step_sub'                     : 'चरण {n} / {total}',
  'detail_section_activity'             : 'गतिविधि',
  'detail_activity_created'             : 'बनाया गया',
  'detail_activity_last_edited'         : 'अंतिम संपादित',
  'detail_activity_template'            : 'टेम्पलेट',
  'detail_btn_continue_editing'         : 'संपादन जारी रखें',
  'detail_btn_edit_cv'                  : 'CV संपादित करें',
  'detail_option_rename'                : 'CV का नाम बदलें',
  'detail_option_delete'                : 'CV हटाएं',
  'detail_rename_title'                 : 'CV का नाम बदलें',
  'detail_rename_hint'                  : 'जैसे सॉफ्टवेयर इंजीनियर रिज्यूमे',
  'detail_rename_error_empty'           : 'नाम खाली नहीं हो सकता',
  'detail_rename_btn_cancel'            : 'रद्द करें',
  'detail_rename_btn_save'              : 'सेव करें',
  'detail_rename_snackbar'              : 'नाम बदलकर "{name}" किया गया',
  'detail_delete_title'                 : 'CV हटाएं?',
  'detail_delete_body'                  : 'यह क्रिया "{name}" को हमेशा के लिए हटा देगी। इसे पूर्ववत नहीं किया जा सकता।',
  'detail_delete_btn_cancel'            : 'रद्द करें',
  'detail_delete_btn_confirm'           : 'हटाएं',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'पूर्ण',
  'detail_check_tile_incomplete'        : 'अभी भरा नहीं',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'अपना टेम्पलेट चुनें',
  'chooser_subtitle'                    : 'देखने के लिए स्वाइप करें  ·  चुनने के लिए टैप करें  ·  पूर्वावलोकन के लिए दबाकर रखें',
  'chooser_card_hold_hint'              : 'पूर्वावलोकन के लिए दबाकर रखें',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'चुना गया',
  'chooser_modal_heading'               : 'रिज्यूमे का नाम दर्ज करें',
  'chooser_modal_sub'                   : 'एक नाम दें ताकि आप इसे मेरे CV और इतिहास में आसानी से पहचान सकें।',
  'chooser_modal_field_label'           : 'रिज्यूमे का नाम',
  'chooser_modal_save_btn'              : 'सेव करें और बनाना शुरू करें',
  'chooser_modal_divider'               : 'या मौजूदा रिज्यूमे जारी रखें',
  'chooser_nav_selected_sub'            : 'चुना गया टेम्पलेट',
  'chooser_nav_cta'                     : 'सेव करें और जारी रखें',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'अधिकतम प्रविष्टियां पहुंच गईं',
  'editor_show_hide'                    : 'दिखाएं/छुपाएं',
  'editor_editing_badge'                : 'संपादन हो रहा है',
  'editor_field_required'               : 'आवश्यक',
  'editor_tooltip_edit'                 : 'संपादित करें',
  'editor_tooltip_delete'               : 'हटाएं',
  'editor_date_start'                   : 'शुरू की तारीख *',
  'editor_date_end'                     : 'समाप्ति तारीख *',
  'editor_date_tap_hint'                : 'चुनने के लिए टैप करें',
  'editor_date_dialog_title'            : 'महीना और वर्ष चुनें',
  'editor_date_confirm'                 : 'पुष्टि करें',
  'editor_panel_hide'                   : 'छुपाएं',
  'editor_panel_show'                   : 'दिखाएं',
  'editor_validator_max_chars'          : 'अधिकतम {n} अक्षर',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'अपना रिज्यूमे बनाएं',
  'editor_header_step_sub'              : 'चरण {current} / {total} · {label}',
  'editor_step_template'                : 'टेम्पलेट',
  'editor_step_personal'                : 'व्यक्तिगत',
  'editor_step_experience'              : 'अनुभव',
  'editor_step_education'               : 'शिक्षा',
  'editor_step_skills'                  : 'कौशल',
  'editor_step_additional'              : 'अतिरिक्त',
  'editor_step_references'              : 'संदर्भ',
  'editor_step_customize'               : 'कस्टमाइज़',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'कस्टमाइज़ करें',
  'customize_subtitle'                  : 'अपने रिज्यूमे को अनूठा बनाएं',
  'customize_smart_layout_btn'          : 'स्मार्ट लेआउट',
  'customize_back_to_top'               : 'ऊपर वापस जाएं',
  'customize_done_title'                : 'सब कुछ तैयार है!',
  'customize_done_sub'                  : 'नीचे रिज्यूमे पूर्वावलोकन पर टैप करें और अपना पूरा रिज्यूमे देखें',
  'customize_preview_btn'               : 'रिज्यूमे पूर्वावलोकन',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'रंग योजना',
  'color_black'                         : 'काला',
  'color_blue'                          : 'नीला',
  'color_nordic_blue'                   : 'नॉर्डिक नीला',
  'color_indigo'                        : 'इंडिगो',
  'color_teal'                          : 'टील',
  'color_green'                         : 'हरा',
  'color_purple'                        : 'बैंगनी',
  'color_orange'                        : 'नारंगी',
  'color_red'                           : 'लाल',
  'color_executive_gold'                : 'एग्ज़ेक्यूटिव गोल्ड',
  'color_vibrant_coral'                 : 'वाइब्रेंट कोरल',
  'color_white'                         : 'सफेद',
  'color_white_bg'                      : 'सफेद पृष्ठभूमि',
  'color_maroon'                        : 'मैरून',
  'color_brutalist_yellow'              : 'ब्रूटलिस्ट येलो',
  'color_neon_blue'                     : 'नियॉन ब्लू',
  'color_blueprint_navy'                : 'ब्लूप्रिंट नेवी',
  'color_light_grey'                    : 'हल्का स्लेटी',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'फ़ॉन्ट परिवार',
  'customize_font_picker_title'         : 'फ़ॉन्ट चुनें',
  'customize_font_picker_sub'           : 'हर फ़ॉन्ट अपने टेम्पलेट में पूर्वावलोकित होता है',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'फ़ॉन्ट आकार',
  'customize_font_size_label'           : 'टेक्स्ट आकार',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'छवि आकार',
  'customize_image_size_label'          : 'छवि आकार',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'लाइव पूर्वावलोकन',
  'preview_page_count_singular'         : '1 पृष्ठ',
  'preview_page_count_plural'           : '{n} पृष्ठ',
  'preview_page_of'                     : 'पृष्ठ {page} / {total}',
  'preview_live_hint'                   : 'परिवर्तन तुरंत लागू होते हैं',
  'preview_template_unregistered'       : 'customize_preview.dart में अभी पंजीकृत नहीं',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'रिज्यूमे तैयार हो रहा है…',
  'preview_bar_print'                   : 'प्रिंट',
  'preview_bar_save_pdf'                : 'PDF के रूप में सेव करें',
  'preview_bar_share'                   : 'शेयर करें',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'रिज्यूमे पूर्वावलोकन',
  'preview_screen_sub'                  : '{n} {unit} · जैसे प्रिंट होगा ठीक वैसे',
  'preview_page_singular'               : 'पृष्ठ',
  'preview_page_plural'                 : 'पृष्ठ',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'मेरा रिज्यूमे',
  'preview_snack_print_failed'          : 'प्रिंट विफल: {e}',
  'preview_snack_saved'                 : 'रिज्यूमे डाउनलोड में सेव हुआ ✓',
  'preview_snack_export_failed'         : 'निर्यात विफल: {e}',
  'preview_snack_share_failed'          : 'शेयर विफल: {e}',
  'preview_template_not_registered'     : 'टेम्पलेट पंजीकृत नहीं',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'पूर्वावलोकन बंद करें',
  'preview_modal_hint_photo'            : 'प्रोफ़ाइल फ़ोटो का समर्थन करता है  ·  चुनने के लिए कार्ड टैप करें',
  'preview_modal_hint_no_photo'         : 'चुनने के लिए टेम्पलेट कार्ड टैप करें',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'मेरा रिज्यूमे',
  'time_just_now'                       : 'अभी-अभी',
  'time_minutes_ago'                    : '{n} मिनट पहले',
  'time_hours_ago'                      : '{n} घंटे पहले',
  'time_yesterday'                      : 'कल',
  'time_days_ago'                       : '{n} दिन पहले',
  'time_one_week_ago'                   : '1 सप्ताह पहले',
  'time_weeks_ago'                      : '{n} सप्ताह पहले',

  // ─── preview_registry.dart — shared tag labels ───────────────────────────
  'tpl_tag_elegant'                     : 'एलिगेंट',
  'tpl_tag_classic'                     : 'क्लासिक',
  'tpl_tag_minimal'                     : 'मिनिमल',
  'tpl_tag_creative'                    : 'क्रिएटिव',
  'tpl_tag_bold'                        : 'बोल्ड',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'ग्रेडिएंट',
  'tpl_gradient_desc'                   : 'टील से बैंगनी ग्रेडिएंट कार्ड',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'एडिटोरियल',
  'tpl_editorial_desc'                  : 'लाल और क्रीम के साथ मैगज़ीन शैली',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'पेस्टल सॉफ्ट',
  'tpl_pastel_soft_desc'                : 'लैवेंडर साइडबार, मुलायम कार्ड',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'ब्रूटलिस्ट',
  'tpl_brutalist_desc'                  : 'कच्ची ग्रिड, मोटी सीमाएं और पीला',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'एमरल्ड',
  'tpl_emerald_desc'                    : 'टाइमलाइन के साथ वन हरा',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'इन्फोग्राफिक',
  'tpl_infographic_desc'                : 'रिंग चार्ट के साथ डार्क कैनवास',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'आर्ट डेको',
  'tpl_art_deco_desc'                   : '1920 के दशक की सुनहरी ज्यामितीय भव्यता',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'विना डार्क',
  'tpl_wina_dark_desc'                  : 'रिंग के साथ डार्क इन्फोग्राफिक',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'रियो ऑरेंज',
  'tpl_rio_orange_desc'                 : 'नारंगी एक्सेंट के साथ डार्क साइडबार',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'समर',
  'tpl_summer_desc'                     : 'हल्के स्लेटी टोन के साथ साफ मिनिमल',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'हेलेन',
  'tpl_helene_desc'                     : 'गर्म बेज और परिष्कृत टोन',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'कैनफील्ड',
  'tpl_canfield_desc'                   : 'तीखा क्लासिक काला और सफेद',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'कॉलिन्स',
  'tpl_collins_desc'                    : 'ATS-अनुकूल क्लासिक लेआउट',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'टोनी डार्क',
  'tpl_tony_dark_desc'                  : 'डार्क-ऑरेंज इन्फोग्राफिक शैली',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'फैशन',
  'tpl_fashion_desc'                    : 'ग्रिड पर टेक्निकल ब्लूप्रिंट',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'आर्किविस्ट',
  'tpl_archivist_desc'                  : 'लेबल के साथ क्लासिक दो-कॉलम लेआउट',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'डिप्लोमैट',
  'tpl_diplomat_desc'                   : 'हीरे विभाजकों के साथ छायांकित शीर्षलेख',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'मेरिडियन',
  'tpl_meridian_desc'                   : 'प्रमुख कंपनियों के साथ केंद्रित शीर्षलेख',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'मोमेंटम',
  'tpl_momentum_desc'                   : 'बोल्ड नाम, टाइमलाइन डॉट्स और उपलब्धियां',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'व्यक्तिगत जानकारी',
  'personal_subtitle'                   : 'नियोक्ताओं को बताएं आप कौन हैं',
  'personal_profile_counter'            : '{n}/{max} प्रोफ़ाइल',
  'personal_info_banner'                : '5 प्रोफ़ाइल तक सेव करें और हर रिज्यूमे के लिए एक चुनें। आपकी पसंद हर रिज्यूमे के लिए अलग से याद रखी जाती है।',
  'personal_snack_max'                  : 'अधिकतम {n} प्रोफ़ाइल पहुंच गई।',
  'personal_add_btn'                    : 'नई प्रोफ़ाइल जोड़ें',
  'personal_library_title'              : 'सेव की गई प्रोफ़ाइलें',
  'personal_selected_one'               : '1 चुनी गई',
  'personal_selected_none'              : 'कोई नहीं चुनी',
  'personal_library_hint'               : 'केवल इस रिज्यूमे के लिए चुनने हेतु कार्ड टैप करें। अन्य रिज्यूमे अपनी स्वतंत्र पसंद बनाए रखते हैं।',
  'personal_empty_message'              : 'अभी कोई प्रोफ़ाइल सेव नहीं',
  'personal_empty_sub'                  : 'अपनी व्यक्तिगत जानकारी जोड़ने के लिए ऊपर टैप करें',
  'personal_nav_next'                   : 'सेव करें और जारी रखें',
  'personal_card_active_badge'          : 'इस रिज्यूमे के लिए सक्रिय',
  'personal_sheet_title_add'            : 'नई प्रोफ़ाइल',
  'personal_sheet_title_edit'           : 'प्रोफ़ाइल संपादित करें',
  'personal_sheet_brutalist_badge'      : 'ब्रूटलिस्ट',
  'personal_sheet_brutalist_banner'     : 'ब्रूटलिस्ट टेम्पलेट में कॉम्पैक्ट संपर्क फ़ील्ड हैं। छोटे मान (जैसे केवल शहर) बेहतर दिखते हैं।',
  'personal_section_photo'              : 'प्रोफ़ाइल फ़ोटो',
  'personal_section_basic'              : 'मूल जानकारी',
  'personal_section_contact'            : 'संपर्क',
  'personal_section_online'             : 'ऑनलाइन उपस्थिति',
  'personal_section_summary'            : 'पेशेवर सारांश',
  'personal_field_first_name'           : 'पहला नाम *',
  'personal_field_last_name'            : 'उपनाम',
  'personal_field_job_title'            : 'पद का शीर्षक *',
  'personal_field_email'                : 'ईमेल पता *',
  'personal_field_phone'                : 'फ़ोन नंबर *',
  'personal_field_location'             : 'स्थान',
  'personal_field_location_brut'        : 'स्थान (केवल शहर)',
  'personal_field_website'              : 'वेबसाइट / पोर्टफोलियो',
  'personal_field_linkedin'             : 'LinkedIn',
  'personal_hint_first_name'            : 'जैसे राहुल',
  'personal_hint_last_name'             : 'जैसे शर्मा',
  'personal_hint_job_title'             : 'जैसे वरिष्ठ इंजीनियर',
  'personal_hint_email'                 : 'जैसे rahul@example.com',
  'personal_hint_phone'                 : 'जैसे +91 98765 43210',
  'personal_hint_location'              : 'जैसे मुंबई, भारत',
  'personal_hint_location_brut'         : 'जैसे मुंबई',
  'personal_hint_website'               : 'जैसे github.com/sara',
  'personal_hint_website_brut'          : 'जैसे github.com/sara',
  'personal_hint_linkedin'              : 'जैसे linkedin.com/in/sara',
  'personal_hint_linkedin_brut'         : 'जैसे linkedin.com/in/sara',
  'personal_summary_hint_label'         : 'संक्षिप्त लिखें — यह आपके रिज्यूमे के ऊपर दिखेगा।',
  'personal_hint_summary'               : 'आपके अनुभव और लक्ष्यों का 2–3 वाक्यों में सारांश...',
  'personal_validator_email'            : 'एक वैध ईमेल दर्ज करें',
  'personal_field_char_limit_tooltip'   : 'अक्षर सीमा पहुंच गई',
  'personal_sheet_btn_save'             : 'प्रोफ़ाइल सेव करें',
  'personal_sheet_btn_update'           : 'बदलाव सेव करें',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'फ़ोटो चुनें',
  'photo_option_gallery'                : 'गैलरी से चुनें',
  'photo_option_camera'                 : 'फ़ोटो लें',
  'photo_option_reposition'             : 'फ़ोटो की स्थिति बदलें',
  'photo_option_remove'                 : 'फ़ोटो हटाएं',
  'photo_status_added'                  : 'फ़ोटो जोड़ी गई ✓',
  'photo_status_empty'                  : 'एक पेशेवर फ़ोटो जोड़ें',
  'photo_chip_gallery'                  : 'गैलरी',
  'photo_chip_camera'                   : 'कैमरा',
  'photo_chip_reposition'               : 'स्थिति बदलें',
  'photo_reposition_title'              : 'फ़ोटो की स्थिति बदलें',
  'photo_reposition_sub'                : 'स्थिति समायोजित करने के लिए फ़ोटो खींचें',
  'photo_reposition_reset'              : 'केंद्र पर वापस जाएं',
  'photo_reposition_apply'              : 'लागू करें',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'कौशल',
  'skills_subtitle'                     : 'अपनी मुख्य क्षमताओं को उजागर करें',
  'skills_add_btn'                      : 'नया कौशल जोड़ें',
  'skills_snack_max_icons'              : 'अधिकतम 10 आइकन चुने गए।',
  'skills_snack_max_skills'             : 'अधिकतम 15 कौशल पहुंच गए।',
  'skills_library_title'                : 'सेव किए गए कौशल',
  'skills_library_hint'                 : 'चेक किए गए कौशल इस रिज्यूमे में शामिल होंगे। आपकी पसंद अपने आप सेव होती है।',
  'skills_nav_next'                     : 'अतिरिक्त जानकारी पर जाएं',
  'skills_wina_header_icon_bar'         : 'हेडर आइकन बार',
  'skills_wina_on'                      : 'चालू',
  'skills_wina_off'                     : 'बंद',
  'skills_wina_bar_on_sub'              : 'रंगीन आइकन सर्कल रिज्यूमे हेडर में दिखाए जाते हैं।',
  'skills_wina_bar_off_sub'             : 'आइकन पंक्ति छुपी है — संपर्क जानकारी के लिए अधिक जगह।',
  'skills_wina_palette_hint'            : 'आइकन पैलेट क्रम में रंगीन सर्कल के रूप में दिखाए जाते हैं।',
  'skills_wina_preview_label'           : 'पूर्वावलोकन',
  'skills_wina_disabled_hint'           : 'ऊपर आइकन बार सक्षम करें ताकि चुन सकें कौन से आइकन रिज्यूमे हेडर में दिखें।',
  'skills_sheet_title_add'              : 'कौशल जोड़ें',
  'skills_sheet_title_edit'             : 'कौशल संपादित करें',
  'skills_sheet_field_name'             : 'कौशल का नाम *',
  'skills_sheet_hint_short'             : 'जैसे Flutter, डिज़ाइन',
  'skills_sheet_hint_long'              : 'जैसे Flutter, प्रोजेक्ट प्रबंधन',
  'skills_sheet_validator_max'          : 'अधिकतम {n} अक्षर',
  'skills_sheet_proficiency'            : 'दक्षता स्तर',
  'skills_sheet_beginner'               : 'शुरुआती',
  'skills_sheet_expert'                 : 'विशेषज्ञ',
  'skills_sheet_btn_save'               : 'कौशल सेव करें',
  'skills_sheet_btn_update'             : 'कौशल अपडेट करें',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'व्यक्तिगत संदर्भ',
  'refs_subtitle'                       : 'वे लोग जो आपकी व्यक्तिगत रूप से अनुशंसा कर सकते हैं',
  'refs_add_btn'                        : 'नया व्यक्तिगत संदर्भ जोड़ें',
  'refs_snack_max_selected'             : 'एक रिज्यूमे में अधिकतम 4 संदर्भ चुने जा सकते हैं।',
  'refs_snack_max_saved'                : 'अधिकतम 10 सेव किए गए संदर्भ पहुंच गए।',
  'refs_library_title'                  : 'सेव किए गए संदर्भ',
  'refs_library_hint'                   : 'चेक किए गए संदर्भ इस रिज्यूमे में शामिल होंगे। प्रति रिज्यूमे अधिकतम 4। आपकी पसंद अपने आप सेव होती है।',
  'refs_nav_next'                       : 'कस्टमाइज़ पर जाएं',
  'refs_sheet_title_add'                : 'व्यक्तिगत संदर्भ जोड़ें',
  'refs_sheet_title_edit'               : 'व्यक्तिगत संदर्भ संपादित करें',
  'refs_sheet_sub_add'                  : 'कोई ऐसा व्यक्ति जो नियोक्ताओं को आपकी व्यक्तिगत रूप से अनुशंसा कर सके।',
  'refs_sheet_sub_edit'                 : 'नीचे इस संदर्भ की जानकारी अपडेट करें।',
  'refs_sheet_field_name'               : 'पूरा नाम *',
  'refs_sheet_field_title'              : 'पद का शीर्षक *',
  'refs_sheet_field_company'            : 'कंपनी (वैकल्पिक)',
  'refs_sheet_field_email'              : 'ईमेल पता *',
  'refs_sheet_field_phone'              : 'फ़ोन नंबर *',
  'refs_sheet_hint_name'                : 'जैसे अमित कुमार',
  'refs_sheet_hint_title'               : 'जैसे इंजीनियरिंग प्रबंधक',
  'refs_sheet_hint_company'             : 'जैसे Acme Corp',
  'refs_sheet_hint_email'               : 'जैसे amit@acme.com',
  'refs_sheet_hint_phone'               : 'जैसे +91 98765 43210',
  'refs_sheet_validator_email'          : 'एक वैध ईमेल पता दर्ज करें',
  'refs_sheet_btn_save'                 : 'व्यक्तिगत संदर्भ सेव करें',
  'refs_sheet_btn_update'               : 'व्यक्तिगत संदर्भ अपडेट करें',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'कार्य अनुभव',
  'exp_subtitle'                        : 'अपना कार्य इतिहास जोड़ें',
  'exp_banner_info'                     : 'प्रति भूमिका {n} ज़िम्मेदारियां रिज्यूमे में दिखेंगी। आमतौर पर 3–6 भूमिकाएं 1–2 पृष्ठों में फिट होती हैं।',
  'exp_add_btn'                         : 'नया अनुभव जोड़ें',
  'exp_snack_max_selected'              : 'एक रिज्यूमे में अधिकतम 8 अनुभव चुने जा सकते हैं।',
  'exp_snack_max_saved'                 : 'अधिकतम 12 सेव किए गए अनुभव पहुंच गए।',
  'exp_library_title'                   : 'सेव किए गए अनुभव',
  'exp_library_hint'                    : 'चेक किए गए आइटम केवल इस रिज्यूमे में शामिल होंगे। अन्य रिज्यूमे अपनी स्वतंत्र पसंद बनाए रखते हैं।',
  'exp_nav_next'                        : 'शिक्षा पर जाएं',
  'exp_empty_message'                   : 'अभी कोई अनुभव नहीं जोड़ा',
  'exp_empty_sub'                       : 'अपनी पहली भूमिका जोड़ने के लिए ऊपर टैप करें',
  'exp_card_resp_singular'              : 'ज़िम्मेदारी',
  'exp_card_resp_plural'                : 'ज़िम्मेदारियां',
  'exp_card_resp_tooltip'               : 'केवल पहली 8 ज़िम्मेदारियां रिज्यूमे में दिखेंगी',
  'exp_sheet_title_add'                 : 'अनुभव जोड़ें',
  'exp_sheet_title_edit'                : 'अनुभव संपादित करें',
  'exp_sheet_field_job_title'           : 'पद का शीर्षक *',
  'exp_sheet_field_company'             : 'कंपनी *',
  'exp_sheet_field_location'            : 'स्थान',
  'exp_sheet_section_responsibilities'  : 'मुख्य ज़िम्मेदारियां',
  'exp_sheet_resp_hint_info'            : 'अधिकतम 8 बुलेट · प्रत्येक 200 अक्षर',
  'exp_sheet_resp_label'                : 'ज़िम्मेदारी {n}',
  'exp_sheet_resp_hint'                 : 'जैसे 5 इंजीनियरों की टीम का नेतृत्व किया',
  'exp_sheet_resp_add_btn'              : 'ज़िम्मेदारी जोड़ें',
  'exp_sheet_resp_max_info'             : 'अधिकतम {n} ज़िम्मेदारियां पहुंच गईं',
  'exp_sheet_resp_validator_max'        : 'अधिकतम 200 अक्षर',
  'exp_sheet_hint_job_title'            : 'जैसे वरिष्ठ डेवलपर',
  'exp_sheet_hint_location'             : 'जैसे मुंबई, भारत',
  'exp_sheet_btn_save'                  : 'अनुभव सेव करें',
  'exp_sheet_btn_update'                : 'बदलाव सेव करें',
  'exp_date_present'                    : 'वर्तमान / अभी की भूमिका',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'शिक्षा',
  'edu_subtitle'                        : 'अपनी शैक्षिक पृष्ठभूमि जोड़ें',
  'edu_add_btn'                         : 'नई शिक्षा जोड़ें',
  'edu_snack_max_selected'              : 'एक रिज्यूमे में अधिकतम 8 शिक्षा रिकॉर्ड चुने जा सकते हैं।',
  'edu_snack_max_saved'                 : 'अधिकतम 12 सेव किए गए शिक्षा रिकॉर्ड पहुंच गए।',
  'edu_library_title'                   : 'सेव की गई शिक्षा',
  'edu_library_hint'                    : 'चेक किए गए आइटम इस रिज्यूमे में शामिल होंगे। आपकी पसंद अपने आप सेव होती है।',
  'edu_nav_next'                        : 'कौशल पर जाएं',
  'edu_empty_message'                   : 'अभी कोई शिक्षा नहीं जोड़ी',
  'edu_empty_sub'                       : 'अपनी शैक्षणिक योग्यताएं जोड़ने के लिए ऊपर टैप करें',
  'edu_card_bullet_singular'            : 'बुलेट',
  'edu_card_bullet_plural'              : 'बुलेट',
  'edu_sheet_title_add'                 : 'शिक्षा जोड़ें',
  'edu_sheet_title_edit'                : 'शिक्षा संपादित करें',
  'edu_sheet_field_degree'              : 'डिग्री / योग्यता *',
  'edu_sheet_field_institution'         : 'संस्थान *',
  'edu_sheet_section_key_points'        : 'मुख्य बातें',
  'edu_sheet_key_points_hint_info'      : 'वैकल्पिक · 1 बुलेट · अधिकतम 100 अक्षर',
  'edu_sheet_point_label'               : 'बात {n}',
  'edu_sheet_point_add_btn'             : 'बुलेट जोड़ें',
  'edu_sheet_point_max_info'            : 'अधिकतम {n} बुलेट पहुंच गए',
  'edu_sheet_point_validator_max'       : 'अधिकतम {n} अक्षर',
  'edu_sheet_hint_degree'               : 'जैसे B.Sc. कंप्यूटर विज्ञान',
  'edu_sheet_hint_institution'          : 'जैसे दिल्ली विश्वविद्यालय',
  'edu_sheet_hint_bullet'               : 'जैसे सम्मान के साथ उत्तीर्ण',
  'edu_sheet_btn_save'                  : 'शिक्षा सेव करें',
  'edu_sheet_btn_update'                : 'बदलाव सेव करें',
  'edu_date_present'                    : 'वर्तमान / अध्ययनरत',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'अतिरिक्त जानकारी',
  'additional_subtitle'                 : 'सर्टिफिकेशन, भाषाएं और अधिक',
  'additional_cert_section_title'       : 'सर्टिफिकेशन',
  'additional_cert_counter'             : '{sel}/{total} चुने · अधिकतम {max}',
  'additional_cert_hide'                : 'छुपाएं',
  'additional_cert_show'                : 'दिखाएं',
  'additional_cert_add_btn'             : 'जोड़ें',
  'additional_cert_snack_max'           : 'अधिकतम {n} सर्टिफिकेशन पहुंच गए।',
  'additional_cert_hint'                : 'चेक किए गए आइटम इस रिज्यूमे में शामिल होंगे। आपकी पसंद अपने आप सेव होती है।',
  'additional_cert_empty'               : 'अभी कोई सर्टिफिकेशन नहीं जोड़ा',
  'additional_lang_section_title'       : 'भाषाएं',
  'additional_lang_add_hint'            : 'जैसे अंग्रेज़ी',
  'additional_lang_snack_max'           : 'अधिकतम {n} भाषाएं पहुंच गईं।',
  'additional_lang_empty'               : 'अभी कोई भाषा नहीं जोड़ी',
  'additional_hobby_section_title'      : 'शौक और रुचियां',
  'additional_hobby_add_hint'           : 'जैसे फ़ोटोग्राफी',
  'additional_hobby_snack_max'          : 'अधिकतम {n} शौक पहुंच गए।',
  'additional_hobby_empty'              : 'अभी कोई शौक नहीं जोड़ा',
  'additional_section_hint'             : 'चेक किए गए आइटम इस रिज्यूमे में शामिल होंगे। आपकी पसंद अपने आप सेव होती है।',
  'additional_nav_next'                 : 'संदर्भों पर जाएं',
  'cert_sheet_title_add'                : 'सर्टिफिकेशन जोड़ें',
  'cert_sheet_title_edit'               : 'सर्टिफिकेशन संपादित करें',
  'cert_sheet_sub'                      : 'एक डिग्री, सर्टिफिकेट या पेशेवर क्रेडेंशियल जोड़ें।',
  'cert_sheet_field_name'               : 'सर्टिफिकेशन का नाम *',
  'cert_sheet_field_issued_by'          : 'जारीकर्ता (वैकल्पिक)',
  'cert_sheet_field_short_desc'         : 'संक्षिप्त विवरण (वैकल्पिक)',
  'cert_sheet_hint_name'                : 'जैसे AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'जैसे Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'जैसे 2024 में प्राप्त',
  'cert_sheet_btn_save'                 : 'सर्टिफिकेशन सेव करें',
  'cert_sheet_btn_update'               : 'सर्टिफिकेशन अपडेट करें',
  'simple_sheet_title_add_language'     : 'भाषा जोड़ें',
  'simple_sheet_title_edit_language'    : 'भाषा संपादित करें',
  'simple_sheet_title_add_hobby'        : 'शौक जोड़ें',
  'simple_sheet_title_edit_hobby'       : 'शौक संपादित करें',
  'simple_sheet_btn_save'               : 'सेव करें',
  'simple_sheet_btn_update'             : 'अपडेट करें',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'संपर्क',
  'pdf_section_about_me'                : 'मेरे बारे में',
  'pdf_section_summary'                 : 'सारांश',
  'pdf_section_summary_short'           : 'सारांश',
  'pdf_section_profile'                 : 'प्रोफ़ाइल',
  'pdf_section_experience'              : 'अनुभव',
  'pdf_section_experience_short'        : 'अनुभव',
  'pdf_section_education'               : 'शिक्षा',
  'pdf_section_skills'                  : 'कौशल',
  'pdf_section_languages'               : 'भाषाएं',
  'pdf_label_email'                     : 'ईमेल',
  'pdf_label_phone'                     : 'फ़ोन',
  'pdf_label_location'                  : 'स्थान',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV सीमा पहुंच गई',
  'limit_dialog_body'                   : 'आप अधिकतम 30 CV तक पहुंच गए हैं। नया बनाने से पहले कृपया एक मौजूदा CV हटाएं।',
  'limit_dialog_go_to_my_cvs'           : 'मेरे CV पर जाएं',
  'limit_dialog_cancel'                 : 'रद्द करें',
  'refs_count_summary'                  : '{checked}/{maxChecked} चुने · {saved}/{maxSaved} सेव किए',
  'refs_selected_badge'                 : '{n} चुने गए',
  'refs_empty_message'                  : 'अभी कोई संदर्भ सेव नहीं',
  'refs_empty_sub'                      : 'एक व्यक्तिगत संदर्भ जोड़ने के लिए ऊपर टैप करें',
};