// lib/language_keys/lang_it_italian.dart
//
// Italian (Italy) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> itItalian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nessuna lingua trovata',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Salta',
  'onboarding_next'                     : 'Avanti',
  'onboarding_get_started'              : 'Inizia',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Benvenuto',
  'ob1_title'                           : 'Crea un CV Che\nApre le Porte',
  'ob1_body'                            : 'Distinguiti da centinaia di candidati. Crea un CV professionale e vincente in pochi minuti — senza competenze di design.',
  'ob1_pill_label'                      : 'Creatore di CV Professionale',
  'ob1_chip_templates'                  : '24+ Modelli',
  'ob1_chip_pdf'                        : 'Esporta PDF',
  'ob1_chip_free'                       : 'Gratuito',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Modelli',
  'ob2_title'                           : 'Ogni Settore.\nOgni Ambizione.',
  'ob2_body'                            : 'Da layout adatti alle sale riunioni a design creativi e vivaci — un modello che racconta la tua storia.',
  'ob2_tap_hint'                        : 'Tocca un modello per visualizzarlo',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vivace',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Lusso',
  'ob2_tag_corporate'                   : 'Aziendale',
  'ob2_tag_creative'                    : 'Creativo',
  'ob2_tag_minimal'                     : 'Minimalista',
  'ob2_tag_modern'                      : 'Moderno',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Layout Intelligente',
  'ob3_title'                           : 'Il Tuo CV.\nPerfettamente Organizzato.',
  'ob3_body'                            : 'Il Layout Intelligente riordina le sezioni per il massimo impatto — mettendo i contenuti più forti dove i recruiter guardano per primi.',
  'ob3_badge_smart_layout'              : 'Layout Intelligente',
  'ob3_badge_cv_ready'                  : 'CV Pronto!',
  'ob3_step1_label'                     : 'Scegli un Modello',
  'ob3_step1_desc'                      : 'Scegli tra 24+ design straordinari.',
  'ob3_step2_label'                     : 'Inserisci i Tuoi Dati',
  'ob3_step2_desc'                      : 'Campi guidati per tutte le sezioni.',
  'ob3_step3_label'                     : 'Layout Intelligente',
  'ob3_step3_desc'                      : 'Un tocco e il tuo CV è perfetto.',
  'ob3_step4_label'                     : 'Esporta come PDF',
  'ob3_step4_desc'                      : 'PDF perfetto pronto per l\'invio.',
  'ob3_section_work'                    : 'Esperienza Lavorativa',
  'ob3_section_education'               : 'Istruzione',
  'ob3_section_skills'                  : 'Competenze',
  'ob3_section_references'              : 'Referenze',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Pronti a Partire',
  'ob4_title'                           : 'Perché i Migliori Candidati\nScelgono CV Builder',
  'ob4_visual_headline'                 : 'Sei Pronto!',
  'ob4_visual_subline'                  : 'Tutto ciò che ti serve per ottenere il lavoro.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Modelli',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'CV Max',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Esporta',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privato',
  'ob4_hl1_title'                       : 'Privato e Sicuro',
  'ob4_hl1_sub'                         : 'I dati rimangono sul tuo dispositivo.',
  'ob4_hl2_title'                       : 'Salvataggio Automatico',
  'ob4_hl2_sub'                         : 'Ogni tasto salvato immediatamente.',
  'ob4_hl3_title'                       : 'Fino a 30 CV',
  'ob4_hl3_sub'                         : 'Un CV unico per ogni ruolo.',
  'ob4_hl4_title'                       : 'Condivisione Rapida',
  'ob4_hl4_sub'                         : 'Invia il PDF senza uscire dall\'app.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Distinguiti dalla massa',
  'home_hero_title'                     : 'Crea il Tuo\nCV Professionale',
  'home_hero_sub'                       : 'Crea un curriculum straordinario\nin pochi minuti',
  'home_hero_cta'                       : 'Inizia a Creare',
  'home_premium_soon'                   : 'Passa a Pro — presto disponibile!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Più Recenti',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Ultima Modifica',
  'history_sort_by_template'            : 'Per Modello',
  'history_sort_sheet_title'            : 'Ordina Per',
  'history_sort_alphabetical_full'      : 'Alfabetico (A–Z)',
  'history_premium_soon'                : 'Passa a Pro — presto disponibile!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Impostazioni',
  'settings_section_preferences'        : 'Preferenze',
  'settings_section_support'            : 'Supporto',
  'settings_section_legal'              : 'Note Legali',
  'settings_section_about'              : 'Informazioni',
  'settings_language_tile_title'        : 'Lingua',
  'settings_dark_mode_title'            : 'Modalità Scura',
  'settings_dark_mode_on'               : 'Tema scuro attivato',
  'settings_dark_mode_off'              : 'Tema chiaro attivato',
  'settings_help_faq_title'             : 'Aiuto e FAQ',
  'settings_help_faq_sub'               : 'Risposte alle domande frequenti',
  'settings_contact_support_title'      : 'Contatta il Supporto',
  'settings_rate_app_title'             : 'Valuta l\'App',
  'settings_rate_app_sub'               : 'Ti piace l\'app? Lascia una recensione!',
  'settings_privacy_policy_title'       : 'Informativa sulla Privacy',
  'settings_terms_title'                : 'Termini di Servizio',
  'settings_app_version_title'          : 'Versione App',
  'settings_email_error'                : 'Impossibile aprire l\'app e-mail. Contattaci a cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Anteprima CV',
  'preview_header_sub'                  : 'Pronto per l\'esportazione',
  'preview_generating'                  : 'Generazione del tuo CV in corso...',
  'preview_failed_title'                : 'Anteprima non riuscita',
  'preview_failed_error'                : 'Errore: {error}',
  'preview_go_back'                     : 'Torna Indietro',
  'preview_no_data'                     : 'Nessun dato disponibile',
  'preview_btn_print'                   : 'Stampa',
  'preview_btn_download'                : 'Scarica e Condividi',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Aiuto e FAQ',
  'faq_category_all'                    : 'Tutto',
  'faq_empty'                           : 'Nessun risultato trovato',
  'faq_contact_headline'                : 'Hai ancora bisogno di aiuto?',
  'faq_contact_sub'                     : 'Il nostro team è a tua disposizione.',
  'faq_contact_btn'                     : 'Contatta',
  'faq_email_error'                     : 'Impossibile aprire l\'app e-mail. Contattaci a cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Per Iniziare',
  'faq_cat_templates'                   : 'Modelli',
  'faq_cat_editing'                     : 'Modifica',
  'faq_cat_exporting'                   : 'Esportazione',
  'faq_cat_data_privacy'                : 'Dati e Privacy',
  'faq_cat_troubleshooting'             : 'Risoluzione Problemi',
  'faq_q1'  : 'Come creo il mio primo CV?',
  'faq_a1'  : 'Tocca il pulsante "+" nella schermata principale per iniziare un nuovo CV. Scegli un modello adatto al tuo stile, poi inserisci i tuoi dati personali, l\'esperienza lavorativa, l\'istruzione e le competenze passo dopo passo. I progressi vengono salvati automaticamente.',
  'faq_q2'  : 'Posso creare più di un CV?',
  'faq_a2'  : 'Sì! Puoi creare più CV per ruoli o settori diversi. Ogni CV viene salvato separatamente, così puoi personalizzarli per specifiche candidature.',
  'faq_q3'  : 'Come cambio il modello del mio CV?',
  'faq_a3'  : 'Apri il tuo CV, tocca l\'icona del modello in cima alla schermata e sfoglia i modelli disponibili. Tocca un modello per visualizzare l\'anteprima con i tuoi contenuti esistenti. Conferma per applicarlo.',
  'faq_q4'  : 'Ci sono modelli gratuiti e a pagamento?',
  'faq_a4'  : 'Sì. Una selezione di modelli professionali è disponibile gratuitamente. I modelli premium con design avanzati e palette di colori sono disponibili tramite acquisto unico o abbonamento.',
  'faq_q5'  : 'Come aggiungo o rimuovo sezioni?',
  'faq_a5'  : 'Nell\'editor del CV, scorri fino in fondo e tocca "Aggiungi Sezione" per includere elementi extra come Lingue, Certificazioni o Volontariato. Per rimuovere una sezione, tocca l\'intestazione della sezione e seleziona "Rimuovi."',
  'faq_q6'  : 'Come riordino le sezioni?',
  'faq_a6'  : 'Tieni premuto il pulsante di trascinamento (≡) accanto all\'intestazione di una sezione e trascinala nella posizione desiderata. Le modifiche vengono salvate automaticamente.',
  'faq_q7'  : 'Come esporto il mio CV come PDF?',
  'faq_a7'  : 'Apri il tuo CV e tocca il pulsante di esportazione (icona condivisione) nell\'angolo in alto a destra. Seleziona "Esporta come PDF." Puoi quindi salvarlo sul dispositivo, condividerlo via e-mail, WhatsApp o caricarlo direttamente sui portali di lavoro.',
  'faq_q8'  : 'Quali formati di file sono supportati?',
  'faq_a8'  : 'Attualmente l\'app supporta l\'esportazione del CV come PDF di alta qualità. Ulteriori formati potrebbero essere aggiunti in aggiornamenti futuri.',
  'faq_q9'  : 'Dove vengono archiviati i dati del mio CV?',
  'faq_a9'  : 'Tutti i dati del CV sono archiviati localmente sul tuo dispositivo. Non carichiamo le tue informazioni personali sui nostri server. Ciò significa che i tuoi dati rimangono privati e accessibili offline.',
  'faq_q10' : 'Come eseguo il backup dei miei CV?',
  'faq_a10' : 'I tuoi CV sono inclusi nel backup standard del dispositivo (backup su Google Drive su Android, iCloud su iOS) se hai il backup abilitato nelle impostazioni del dispositivo. Puoi anche esportare singoli CV come PDF per conservarne una copia.',
  'faq_q11' : 'L\'app è lenta. Cosa devo fare?',
  'faq_a11' : 'Prova a chiudere e riaprire l\'app. Se il problema persiste, riavvia il dispositivo. Assicurati di avere l\'ultima versione dell\'app installata dal Play Store / App Store.',
  'faq_q12' : 'Il mio CV non viene esportato correttamente. Cosa devo fare?',
  'faq_a12' : 'Assicurati di avere spazio di archiviazione sufficiente sul dispositivo. Prova a ridurre le immagini di grandi dimensioni nel tuo CV. Se il problema persiste, contatta il nostro team di supporto.',
  'faq_q13' : 'Ho dimenticato di salvare — ho perso il lavoro?',
  'faq_a13' : 'Assolutamente no! L\'app salva i tuoi progressi continuamente durante la modifica.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'La tua carriera, perfezionata',
  'header_tooltip_back'                 : 'Indietro',
  'header_tooltip_my_cvs'               : 'I Miei CV',
  'header_tooltip_settings'             : 'Impostazioni',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'I Miei CV',
  'saved_count_single'                  : '{n} documento',
  'saved_count_plural'                  : '{n} documenti',
  'saved_limit_reached'                 : 'Limite raggiunto',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Tutti',
  'saved_filter_draft'                  : 'Bozza',
  'saved_filter_complete'               : 'Completo',
  'saved_status_complete'               : 'Completo',
  'saved_status_saved'                  : 'Salvato',
  'saved_status_draft'                  : 'Bozza',
  'saved_empty_title'                   : 'Nessun CV ancora',
  'saved_empty_sub'                     : 'Inizia a creare il tuo primo CV sopra',
  'saved_search_empty_title'            : 'Nessun risultato trovato',
  'saved_search_empty_sub'              : 'Prova un termine di ricerca diverso',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Schema Colori',
  'custom_font_settings_title'          : 'Impostazioni Carattere',
  'custom_font_family_label'            : 'Famiglia di Caratteri',
  'custom_font_size_label'              : 'Dimensione Carattere: ',
  'custom_current_template_title'       : 'Modello Attuale',
  'custom_change_template_btn'          : 'Cambia Modello',
  'custom_tpl_modern'                   : 'Moderno',
  'custom_tpl_classic'                  : 'Classico',
  'custom_tpl_professional'             : 'Professionale',
  'custom_tpl_creative'                 : 'Creativo',
  'custom_tpl_minimal'                  : 'Minimalista',
  'custom_tpl_modern_desc'              : 'Design pulito e contemporaneo',
  'custom_tpl_classic_desc'             : 'Layout professionale tradizionale',
  'custom_tpl_professional_desc'        : 'Modello orientato al business',
  'custom_tpl_creative_desc'            : 'Distinguiti con un design unico',
  'custom_tpl_minimal_desc'             : 'Stile semplice ed elegante',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Scegli Modello',
  'swipe_photo_badge'                   : 'Foto',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vivace',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Lusso',
  'tpl_executive_tag'                   : 'Più Popolare',
  'tpl_nordic_tag'                      : 'Pulito',
  'tpl_vibrant_tag'                     : 'Creativo',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Audace e autorevole per ruoli senior',
  'tpl_nordic_desc'                     : 'Chiarezza minimalista apprezzata dalle migliori aziende',
  'tpl_vibrant_desc'                    : 'Distinguiti con energia e colore',
  'tpl_tech_dark_desc'                  : 'Estetica da terminale per sviluppatori',
  'tpl_luxury_desc'                     : 'Prestigio con accenti dorati su sfondo nero',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Modello',
  'detail_step_personal'                : 'Personale',
  'detail_step_experience'              : 'Esperienza',
  'detail_step_education'               : 'Istruzione',
  'detail_step_skills'                  : 'Competenze',
  'detail_step_additional'              : 'Aggiuntivo',
  'detail_step_references'              : 'Referenze',
  'detail_step_customize'               : 'Personalizza',
  'detail_banner_heading'               : 'Quasi fatto!',
  'detail_banner_btn'                   : 'Continua',
  'detail_banner_completion_label'      : 'Completamento',
  'detail_stat_created_label'           : 'Creato',
  'detail_stat_steps_label'             : 'Passi completati',
  'detail_section_template_style'       : 'Stile Modello',
  'detail_section_steps'                : 'Passi',
  'detail_steps_counter'                : '{done} di {total} completati',
  'detail_step_sub'                     : 'Passo {n} di {total}',
  'detail_section_activity'             : 'Attività',
  'detail_activity_created'             : 'Creato',
  'detail_activity_last_edited'         : 'Ultima Modifica',
  'detail_activity_template'            : 'Modello',
  'detail_btn_continue_editing'         : 'Continua la Modifica',
  'detail_btn_edit_cv'                  : 'Modifica CV',
  'detail_option_rename'                : 'Rinomina CV',
  'detail_option_delete'                : 'Elimina CV',
  'detail_rename_title'                 : 'Rinomina CV',
  'detail_rename_hint'                  : 'es. CV Ingegnere del Software',
  'detail_rename_error_empty'           : 'Il nome non può essere vuoto',
  'detail_rename_btn_cancel'            : 'Annulla',
  'detail_rename_btn_save'              : 'Salva',
  'detail_rename_snackbar'              : 'Rinominato in "{name}"',
  'detail_delete_title'                 : 'Eliminare il CV?',
  'detail_delete_body'                  : 'Questo eliminerà definitivamente "{name}". L\'azione non può essere annullata.',
  'detail_delete_btn_cancel'            : 'Annulla',
  'detail_delete_btn_confirm'           : 'Elimina',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Completato',
  'detail_check_tile_incomplete'        : 'Non ancora compilato',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Scegli il Modello',
  'chooser_subtitle'                    : 'Scorri per sfogliare  ·  Tocca per selezionare  ·  Tieni premuto per anteprima',
  'chooser_card_hold_hint'              : 'Tieni premuto per anteprima',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Selezionato',
  'chooser_modal_heading'               : 'Dai un Nome al Tuo CV',
  'chooser_modal_sub'                   : 'Assegnagli un nome per trovarlo facilmente nei Miei CV e nella Cronologia.',
  'chooser_modal_field_label'           : 'Nome CV',
  'chooser_modal_save_btn'              : 'Salva e Inizia a Creare',
  'chooser_modal_divider'               : 'oppure continua un CV esistente',
  'chooser_nav_selected_sub'            : 'Modello selezionato',
  'chooser_nav_cta'                     : 'Salva e Continua',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Numero Massimo di Voci Raggiunto',
  'editor_show_hide'                    : 'Mostra/Nascondi',
  'editor_editing_badge'                : 'In modifica',
  'editor_field_required'               : 'Obbligatorio',
  'editor_tooltip_edit'                 : 'Modifica',
  'editor_tooltip_delete'               : 'Elimina',
  'editor_date_start'                   : 'Data di Inizio *',
  'editor_date_end'                     : 'Data di Fine *',
  'editor_date_tap_hint'                : 'Tocca per selezionare',
  'editor_date_dialog_title'            : 'Seleziona Mese e Anno',
  'editor_date_confirm'                 : 'Conferma',
  'editor_panel_hide'                   : 'Nascondi',
  'editor_panel_show'                   : 'Mostra',
  'editor_validator_max_chars'          : 'Massimo {n} caratteri',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Crea il Tuo CV',
  'editor_header_step_sub'              : 'Passo {current} di {total} · {label}',
  'editor_step_template'                : 'Modello',
  'editor_step_personal'                : 'Personale',
  'editor_step_experience'              : 'Esperienza',
  'editor_step_education'               : 'Istruzione',
  'editor_step_skills'                  : 'Competenze',
  'editor_step_additional'              : 'Aggiuntivo',
  'editor_step_references'              : 'Referenze',
  'editor_step_customize'               : 'Personalizza',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personalizza',
  'customize_subtitle'                  : 'Rendi il tuo CV unico',
  'customize_smart_layout_btn'          : 'Layout Intelligente',
  'customize_back_to_top'               : 'Torna in Cima',
  'customize_done_title'                : 'Sei pronto!',
  'customize_done_sub'                  : 'Tocca Anteprima CV qui sotto per vedere il tuo CV finito',
  'customize_preview_btn'               : 'Anteprima CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Schema Colori',
  'color_black'                         : 'Nero',
  'color_blue'                          : 'Blu',
  'color_nordic_blue'                   : 'Blu Nordic',
  'color_indigo'                        : 'Indaco',
  'color_teal'                          : 'Verde Acqua',
  'color_green'                         : 'Verde',
  'color_purple'                        : 'Viola',
  'color_orange'                        : 'Arancione',
  'color_red'                           : 'Rosso',
  'color_executive_gold'                : 'Oro Executive',
  'color_vibrant_coral'                 : 'Corallo Vivace',
  'color_white'                         : 'Bianco',
  'color_white_bg'                      : 'Sfondo Bianco',
  'color_maroon'                        : 'Bordeaux',
  'color_brutalist_yellow'              : 'Giallo Brutalista',
  'color_neon_blue'                     : 'Blu Neon',
  'color_blueprint_navy'                : 'Blu Blueprint',
  'color_light_grey'                    : 'Grigio Chiaro',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Famiglia di Caratteri',
  'customize_font_picker_title'         : 'Scegli Carattere',
  'customize_font_picker_sub'           : 'Ogni carattere viene visualizzato nel proprio stile',
  'customize_font_preview_sample'       : 'La volpe veloce marrone',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Dimensione Carattere',
  'customize_font_size_label'           : 'Dimensione Testo',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Dimensione Immagine',
  'customize_image_size_label'          : 'Dimensione Immagine',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Anteprima in Tempo Reale',
  'preview_page_count_singular'         : '1 pagina',
  'preview_page_count_plural'           : '{n} pagine',
  'preview_page_of'                     : 'Pagina {page} di {total}',
  'preview_live_hint'                   : 'Le modifiche si applicano immediatamente',
  'preview_template_unregistered'       : 'Non ancora registrato in customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Preparazione del tuo CV…',
  'preview_bar_print'                   : 'Stampa',
  'preview_bar_save_pdf'                : 'Salva come PDF',
  'preview_bar_share'                   : 'Condividi',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Anteprima CV',
  'preview_screen_sub'                  : '{n} {unit} · esattamente come stampato',
  'preview_page_singular'               : 'pagina',
  'preview_page_plural'                 : 'pagine',
  'preview_pdf_filename'                : 'Il_mio_CV',
  'preview_share_subject'               : 'Il mio CV',
  'preview_snack_print_failed'          : 'Stampa non riuscita: {e}',
  'preview_snack_saved'                 : 'CV salvato nei Download ✓',
  'preview_snack_export_failed'         : 'Esportazione non riuscita: {e}',
  'preview_snack_share_failed'          : 'Condivisione non riuscita: {e}',
  'preview_template_not_registered'     : 'Modello non registrato',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Chiudi anteprima',
  'preview_modal_hint_photo'            : 'Supporta foto profilo  ·  Tocca una scheda per selezionare',
  'preview_modal_hint_no_photo'         : 'Tocca una scheda modello per selezionarla',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Il mio CV',
  'time_just_now'                       : 'Proprio ora',
  'time_minutes_ago'                    : '{n} min fa',
  'time_hours_ago'                      : '{n} ore fa',
  'time_yesterday'                      : 'Ieri',
  'time_days_ago'                       : '{n} giorni fa',
  'time_one_week_ago'                   : '1 settimana fa',
  'time_weeks_ago'                      : '{n} settimane fa',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegante',
  'tpl_tag_classic'                     : 'Classico',
  'tpl_tag_minimal'                     : 'Minimalista',
  'tpl_tag_creative'                    : 'Creativo',
  'tpl_tag_bold'                        : 'Audace',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradiente',
  'tpl_gradient_desc'                   : 'Schede con gradiente dal verde acqua al viola',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editoriale',
  'tpl_editorial_desc'                  : 'Stile magazine rosso e crema',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastello Soft',
  'tpl_pastel_soft_desc'                : 'Barra laterale lavanda, schede morbide',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalista',
  'tpl_brutalist_desc'                  : 'Griglia grezza, bordi spessi e giallo',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smeraldo',
  'tpl_emerald_desc'                    : 'Verde foresta con timeline',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografica',
  'tpl_infographic_desc'                : 'Sfondo scuro con grafici ad anello',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Déco',
  'tpl_art_deco_desc'                   : 'Lusso geometrico oro anni \'20',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Infografica scura con anelli',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Arancione',
  'tpl_rio_orange_desc'                 : 'Barra laterale scura con accento arancione',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Estate',
  'tpl_summer_desc'                     : 'Minimalista pulito, toni grigio chiaro',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Toni beige caldi ed eleganti',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Classico in bianco e nero netto',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Layout classico compatibile con ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Stile infografica arancione scuro',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Disegno tecnico su griglia',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Layout classico a due colonne con etichette',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Intestazioni ombreggiate con indicatori a rombo',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Intestazioni centrate, aziende in evidenza',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nome in grassetto, punti timeline e risultati',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informazioni Personali',
  'personal_subtitle'                   : 'Presentati ai datori di lavoro',
  'personal_profile_counter'            : '{n}/{max} profili',
  'personal_info_banner'                : 'Salva fino a 5 profili e selezionane uno per CV. La selezione viene ricordata per ogni CV separatamente.',
  'personal_snack_max'                  : 'Raggiunto il limite massimo di {n} profili.',
  'personal_add_btn'                    : 'Aggiungi Nuovo Profilo',
  'personal_library_title'              : 'Profili Salvati',
  'personal_selected_one'               : '1 selezionato',
  'personal_selected_none'              : 'nessuno selezionato',
  'personal_library_hint'               : 'Tocca una scheda per selezionarla solo per questo CV. Gli altri CV mantengono le proprie selezioni indipendenti.',
  'personal_empty_message'              : 'Nessun profilo salvato ancora',
  'personal_empty_sub'                  : 'Tocca sopra per aggiungere le tue informazioni personali',
  'personal_nav_next'                   : 'Salva e Continua',
  'personal_card_active_badge'          : 'Attivo per questo CV',
  'personal_sheet_title_add'            : 'Nuovo Profilo',
  'personal_sheet_title_edit'           : 'Modifica Profilo',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTA',
  'personal_sheet_brutalist_banner'     : 'Il modello Brutalista ha campi di contatto compatti. È preferibile usare valori brevi (es. solo città).',
  'personal_section_photo'              : 'Foto Profilo',
  'personal_section_basic'              : 'Dati di Base',
  'personal_section_contact'            : 'Contatto',
  'personal_section_online'             : 'Presenza Online',
  'personal_section_summary'            : 'Profilo Professionale',
  'personal_field_first_name'           : 'Nome *',
  'personal_field_last_name'            : 'Cognome',
  'personal_field_job_title'            : 'Titolo di Lavoro *',
  'personal_field_email'                : 'Indirizzo E-mail *',
  'personal_field_phone'                : 'Numero di Telefono *',
  'personal_field_location'             : 'Località',
  'personal_field_location_brut'        : 'Località (solo città)',
  'personal_field_website'              : 'Sito Web / Portfolio',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'es. Giulia',
  'personal_hint_last_name'             : 'es. Rossi',
  'personal_hint_job_title'             : 'es. Ingegnere Senior',
  'personal_hint_email'                 : 'es. giulia@esempio.it',
  'personal_hint_phone'                 : 'es. +39 02 1234567',
  'personal_hint_location'              : 'es. Milano, Italia',
  'personal_hint_location_brut'         : 'es. Milano, IT',
  'personal_hint_website'               : 'es. github.com/giuliarossi',
  'personal_hint_website_brut'          : 'es. github.com/giulia',
  'personal_hint_linkedin'              : 'es. linkedin.com/in/giuliarossi',
  'personal_hint_linkedin_brut'         : 'es. linkedin.com/in/giulia',
  'personal_summary_hint_label'         : 'Sii conciso — questo appare in cima al tuo CV.',
  'personal_hint_summary'               : 'Un breve riassunto di 2–3 frasi del tuo background e dei tuoi obiettivi...',
  'personal_validator_email'            : 'Inserisci un\'e-mail valida',
  'personal_field_char_limit_tooltip'   : 'Limite di caratteri raggiunto',
  'personal_sheet_btn_save'             : 'Salva Profilo',
  'personal_sheet_btn_update'           : 'Salva Modifiche',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Scegli Foto',
  'photo_option_gallery'                : 'Scegli dalla Galleria',
  'photo_option_camera'                 : 'Scatta una Foto',
  'photo_option_reposition'             : 'Riposiziona Foto',
  'photo_option_remove'                 : 'Rimuovi Foto',
  'photo_status_added'                  : 'Foto aggiunta ✓',
  'photo_status_empty'                  : 'Aggiungi una foto tessera professionale',
  'photo_chip_gallery'                  : 'Galleria',
  'photo_chip_camera'                   : 'Fotocamera',
  'photo_chip_reposition'               : 'Riposiziona',
  'photo_reposition_title'              : 'Riposiziona Foto',
  'photo_reposition_sub'                : 'Trascina la foto per regolare la posizione',
  'photo_reposition_reset'              : 'Reimposta al centro',
  'photo_reposition_apply'              : 'Applica',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Competenze',
  'skills_subtitle'                     : 'Metti in risalto le tue capacità principali',
  'skills_add_btn'                      : 'Aggiungi Nuova Competenza',
  'skills_snack_max_icons'              : 'Massimo 10 icone selezionate.',
  'skills_snack_max_skills'             : 'Raggiunto il limite massimo di 15 competenze.',
  'skills_library_title'                : 'Competenze Salvate',
  'skills_library_hint'                 : 'Le competenze selezionate sono incluse in questo CV. Le selezioni vengono salvate automaticamente.',
  'skills_nav_next'                     : 'Continua alle Informazioni Aggiuntive',
  'skills_wina_header_icon_bar'         : 'Barra Icone Intestazione',
  'skills_wina_on'                      : 'ON',
  'skills_wina_off'                     : 'OFF',
  'skills_wina_bar_on_sub'              : 'Cerchi icone colorati mostrati nell\'intestazione del CV.',
  'skills_wina_bar_off_sub'             : 'Riga icone nascosta — più spazio per le informazioni di contatto.',
  'skills_wina_palette_hint'            : 'Le icone appaiono come cerchi colorati nell\'ordine della palette.',
  'skills_wina_preview_label'           : 'Anteprima',
  'skills_wina_disabled_hint'           : 'Attiva la barra delle icone sopra per scegliere quali icone appaiono nell\'intestazione del CV.',
  'skills_sheet_title_add'              : 'Aggiungi Competenza',
  'skills_sheet_title_edit'             : 'Modifica Competenza',
  'skills_sheet_field_name'             : 'Nome Competenza *',
  'skills_sheet_hint_short'             : 'es. Flutter, Design',
  'skills_sheet_hint_long'              : 'es. Flutter, Project Management',
  'skills_sheet_validator_max'          : 'Massimo {n} caratteri',
  'skills_sheet_proficiency'            : 'Livello di Competenza',
  'skills_sheet_beginner'               : 'Principiante',
  'skills_sheet_expert'                 : 'Esperto',
  'skills_sheet_btn_save'               : 'Salva Competenza',
  'skills_sheet_btn_update'             : 'Aggiorna Competenza',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referenze Personali',
  'refs_subtitle'                       : 'Persone che possono garantire per te personalmente',
  'refs_add_btn'                        : 'Aggiungi Nuova Referenza Personale',
  'refs_snack_max_selected'             : 'È possibile selezionare un massimo di 4 referenze per un CV.',
  'refs_snack_max_saved'                : 'Raggiunto il limite massimo di 10 referenze salvate.',
  'refs_library_title'                  : 'Referenze Salvate',
  'refs_library_hint'                   : 'Le referenze selezionate sono incluse in questo CV. Massimo 4 per CV. Le selezioni vengono salvate automaticamente.',
  'refs_nav_next'                       : 'Continua alla Personalizzazione',
  'refs_sheet_title_add'                : 'Aggiungi Referenza Personale',
  'refs_sheet_title_edit'               : 'Modifica Referenza Personale',
  'refs_sheet_sub_add'                  : 'Qualcuno che può raccomandarti personalmente ai datori di lavoro.',
  'refs_sheet_sub_edit'                 : 'Aggiorna i dettagli di questa referenza qui sotto.',
  'refs_sheet_field_name'               : 'Nome Completo *',
  'refs_sheet_field_title'              : 'Titolo di Lavoro *',
  'refs_sheet_field_company'            : 'Azienda (opzionale)',
  'refs_sheet_field_email'              : 'Indirizzo E-mail *',
  'refs_sheet_field_phone'              : 'Numero di Telefono *',
  'refs_sheet_hint_name'                : 'es. Mario Bianchi',
  'refs_sheet_hint_title'               : 'es. Responsabile Ingegneria',
  'refs_sheet_hint_company'             : 'es. Acme S.r.l.',
  'refs_sheet_hint_email'               : 'es. mario@acme.it',
  'refs_sheet_hint_phone'               : 'es. +39 02 1234567',
  'refs_sheet_validator_email'          : 'Inserisci un indirizzo e-mail valido',
  'refs_sheet_btn_save'                 : 'Salva Referenza Personale',
  'refs_sheet_btn_update'               : 'Aggiorna Referenza Personale',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Esperienza Lavorativa',
  'exp_subtitle'                        : 'Aggiungi la tua storia lavorativa',
  'exp_banner_info'                     : 'Nel CV appariranno fino a {n} responsabilità per ruolo. Da 3 a 6 ruoli rientrano tipicamente in 1–2 pagine.',
  'exp_add_btn'                         : 'Aggiungi Nuova Esperienza',
  'exp_snack_max_selected'              : 'È possibile selezionare un massimo di 8 esperienze per un CV.',
  'exp_snack_max_saved'                 : 'Raggiunto il limite massimo di 12 esperienze salvate.',
  'exp_library_title'                   : 'Esperienze Salvate',
  'exp_library_hint'                    : 'Le voci selezionate sono incluse solo in questo CV. Gli altri CV mantengono le proprie selezioni indipendenti.',
  'exp_nav_next'                        : 'Continua all\'Istruzione',
  'exp_empty_message'                   : 'Nessuna esperienza aggiunta ancora',
  'exp_empty_sub'                       : 'Tocca sopra per aggiungere il tuo primo ruolo',
  'exp_card_resp_singular'              : 'responsabilità',
  'exp_card_resp_plural'                : 'responsabilità',
  'exp_card_resp_tooltip'               : 'Solo le prime 8 responsabilità appariranno nel CV',
  'exp_sheet_title_add'                 : 'Aggiungi Esperienza',
  'exp_sheet_title_edit'                : 'Modifica Esperienza',
  'exp_sheet_field_job_title'           : 'Titolo di Lavoro *',
  'exp_sheet_field_company'             : 'Azienda *',
  'exp_sheet_field_location'            : 'Località',
  'exp_sheet_section_responsibilities'  : 'Responsabilità Principali',
  'exp_sheet_resp_hint_info'            : 'Massimo 8 punti elenco · 200 caratteri ciascuno',
  'exp_sheet_resp_label'                : 'Responsabilità {n}',
  'exp_sheet_resp_hint'                 : 'es. Ho guidato un team di 5 ingegneri',
  'exp_sheet_resp_add_btn'              : 'Aggiungi Responsabilità',
  'exp_sheet_resp_max_info'             : 'Raggiunto il massimo di {n} responsabilità',
  'exp_sheet_resp_validator_max'        : 'Massimo 200 caratteri',
  'exp_sheet_hint_job_title'            : 'es. Sviluppatore Senior',
  'exp_sheet_hint_location'             : 'es. Roma, Italia',
  'exp_sheet_btn_save'                  : 'Salva Esperienza',
  'exp_sheet_btn_update'                : 'Salva Modifiche',
  'exp_date_present'                    : 'Presente / Ruolo Attuale',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Istruzione',
  'edu_subtitle'                        : 'Aggiungi il tuo background accademico',
  'edu_add_btn'                         : 'Aggiungi Nuova Istruzione',
  'edu_snack_max_selected'              : 'È possibile selezionare un massimo di 8 voci di istruzione per un CV.',
  'edu_snack_max_saved'                 : 'Raggiunto il limite massimo di 12 voci di istruzione salvate.',
  'edu_library_title'                   : 'Istruzione Salvata',
  'edu_library_hint'                    : 'Le voci selezionate sono incluse in questo CV. Le selezioni vengono salvate automaticamente.',
  'edu_nav_next'                        : 'Continua alle Competenze',
  'edu_empty_message'                   : 'Nessuna istruzione aggiunta ancora',
  'edu_empty_sub'                       : 'Tocca sopra per aggiungere le tue qualifiche',
  'edu_card_bullet_singular'            : 'punto elenco',
  'edu_card_bullet_plural'              : 'punti elenco',
  'edu_sheet_title_add'                 : 'Aggiungi Istruzione',
  'edu_sheet_title_edit'                : 'Modifica Istruzione',
  'edu_sheet_field_degree'              : 'Laurea / Qualifica *',
  'edu_sheet_field_institution'         : 'Istituto *',
  'edu_sheet_section_key_points'        : 'Punti Chiave',
  'edu_sheet_key_points_hint_info'      : 'Opzionale · 1 punto elenco · massimo 100 caratteri',
  'edu_sheet_point_label'               : 'Punto {n}',
  'edu_sheet_point_add_btn'             : 'Aggiungi Punto Elenco',
  'edu_sheet_point_max_info'            : 'Raggiunto il massimo di {n} punti elenco',
  'edu_sheet_point_validator_max'       : 'Massimo {n} caratteri',
  'edu_sheet_hint_degree'               : 'es. Laurea in Informatica',
  'edu_sheet_hint_institution'          : 'es. Università degli Studi di Milano',
  'edu_sheet_hint_bullet'               : 'es. Votazione 110 con lode',
  'edu_sheet_btn_save'                  : 'Salva Istruzione',
  'edu_sheet_btn_update'                : 'Salva Modifiche',
  'edu_date_present'                    : 'Presente / Studio in Corso',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Informazioni Aggiuntive',
  'additional_subtitle'                 : 'Certificazioni, lingue e altro',
  'additional_cert_section_title'       : 'Certificazioni',
  'additional_cert_counter'             : '{sel}/{total} selezionate · max {max}',
  'additional_cert_hide'                : 'Nascondi',
  'additional_cert_show'                : 'Mostra',
  'additional_cert_add_btn'             : 'Aggiungi',
  'additional_cert_snack_max'           : 'Raggiunto il limite massimo di {n} certificazioni.',
  'additional_cert_hint'                : 'Le voci selezionate sono incluse in questo CV. Le selezioni vengono salvate automaticamente.',
  'additional_cert_empty'               : 'Nessuna certificazione aggiunta ancora',
  'additional_lang_section_title'       : 'Lingue',
  'additional_lang_add_hint'            : 'es. Spagnolo',
  'additional_lang_snack_max'           : 'Raggiunto il limite massimo di {n} lingue.',
  'additional_lang_empty'               : 'Nessuna lingua aggiunta ancora',
  'additional_hobby_section_title'      : 'Hobby e Interessi',
  'additional_hobby_add_hint'           : 'es. Fotografia',
  'additional_hobby_snack_max'          : 'Raggiunto il limite massimo di {n} hobby.',
  'additional_hobby_empty'              : 'Nessun hobby aggiunto ancora',
  'additional_section_hint'             : 'Le voci selezionate sono incluse in questo CV. Le selezioni vengono salvate automaticamente.',
  'additional_nav_next'                 : 'Continua alle Referenze',
  'cert_sheet_title_add'                : 'Aggiungi Certificazione',
  'cert_sheet_title_edit'               : 'Modifica Certificazione',
  'cert_sheet_sub'                      : 'Aggiungi una qualifica, un certificato o una credenziale professionale.',
  'cert_sheet_field_name'               : 'Nome Certificazione *',
  'cert_sheet_field_issued_by'          : 'Rilasciata Da (opzionale)',
  'cert_sheet_field_short_desc'         : 'Breve Descrizione (opzionale)',
  'cert_sheet_hint_name'                : 'es. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'es. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'es. Conseguita nel 2024',
  'cert_sheet_btn_save'                 : 'Salva Certificazione',
  'cert_sheet_btn_update'               : 'Aggiorna Certificazione',
  'simple_sheet_title_add_language'     : 'Aggiungi Lingua',
  'simple_sheet_title_edit_language'    : 'Modifica Lingua',
  'simple_sheet_title_add_hobby'        : 'Aggiungi Hobby',
  'simple_sheet_title_edit_hobby'       : 'Modifica Hobby',
  'simple_sheet_btn_save'               : 'Salva',
  'simple_sheet_btn_update'             : 'Aggiorna',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contatti',
  'pdf_section_about_me'                : 'Chi Sono',
  'pdf_section_summary'                 : 'Profilo',
  'pdf_section_summary_short'           : 'Profilo',
  'pdf_section_profile'                 : 'Profilo',
  'pdf_section_experience'              : 'Esperienza',
  'pdf_section_experience_short'        : 'Esperienza',
  'pdf_section_education'               : 'Istruzione',
  'pdf_section_skills'                  : 'Competenze',
  'pdf_section_languages'               : 'Lingue',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefono',
  'pdf_label_location'                  : 'Località',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Limite CV raggiunto',
  'limit_dialog_body'                   : 'Hai raggiunto il massimo di 30 CV. Elimina un CV esistente prima di crearne uno nuovo.',
  'limit_dialog_go_to_my_cvs'           : 'Vai ai Miei CV',
  'limit_dialog_cancel'                 : 'Annulla',
  'refs_count_summary'                  : '{checked}/{maxChecked} selezionati · {saved}/{maxSaved} salvati',
  'refs_selected_badge'                 : '{n} selezionato/i',
  'refs_empty_message'                  : 'Nessun riferimento salvato',
  'refs_empty_sub'                      : 'Tocca sopra per aggiungere un riferimento personale',
};