// lib/language_keys/lang_tl_filipino.dart
//
// Filipino (Tagalog) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> tlFilipino = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Walang nahanap na wika',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Laktawan',
  'onboarding_next'                     : 'Susunod',
  'onboarding_get_started'              : 'Magsimula',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Maligayang pagdating',
  'ob1_title'                           : 'Gumawa ng CV na\nMagbubukas ng Pinto',
  'ob1_body'                            : 'Namumukod-tangi sa daan-daang aplikante. Gumawa ng maayos na CV sa loob ng ilang minuto — hindi kailangan ng kakayahan sa disenyo.',
  'ob1_pill_label'                      : 'Propesyonal na CV Builder',
  'ob1_chip_templates'                  : '24+ Mga Template',
  'ob1_chip_pdf'                        : 'PDF Export',
  'ob1_chip_free'                       : 'Libre Gamitin',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Mga Template',
  'ob2_title'                           : 'Bawat Industriya.\nBawat Ambisyon.',
  'ob2_body'                            : 'Mula sa mga layout na handang para sa boardroom hanggang sa matapang na malikhaing disenyo — isang template na magkukuwento ng iyong buhay.',
  'ob2_tap_hint'                        : 'I-tap ang anumang template para i-preview',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Makulay',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Korporasyon',
  'ob2_tag_creative'                    : 'Malikhain',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Moderno',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart Layout',
  'ob3_title'                           : 'Ang Iyong CV.\nPerfektong Nakaayos.',
  'ob3_body'                            : 'Inaayos ng Smart Layout ang iyong mga seksyon para sa pinakamataas na epekto — inilalagay ang iyong pinakamalakas na nilalaman kung saan unang titingnan ng mga recruiter.',
  'ob3_badge_smart_layout'              : 'Smart Layout',
  'ob3_badge_cv_ready'                  : 'Handa na ang CV!',
  'ob3_step1_label'                     : 'Pumili ng Template',
  'ob3_step1_desc'                      : 'Pumili mula sa 24+ kahanga-hangang disenyo.',
  'ob3_step2_label'                     : 'Punan ang Iyong Detalye',
  'ob3_step2_desc'                      : 'Mga guided na field para sa lahat ng seksyon.',
  'ob3_step3_label'                     : 'Smart Layout',
  'ob3_step3_desc'                      : 'Isang tap para maayos ang iyong CV.',
  'ob3_step4_label'                     : 'I-export bilang PDF',
  'ob3_step4_desc'                      : 'Pixel-perfect na PDF handang ipadala.',
  'ob3_section_work'                    : 'Karanasan sa Trabaho',
  'ob3_section_education'               : 'Edukasyon',
  'ob3_section_skills'                  : 'Mga Kasanayan',
  'ob3_section_references'              : 'Mga Sanggunian',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Handa na',
  'ob4_title'                           : 'Bakit Pinipili ng Mga\nNangungunang Kandidato ang CV Builder',
  'ob4_visual_headline'                 : 'Handa Ka Na!',
  'ob4_visual_subline'                  : 'Lahat ng kailangan mo para makuha ang trabaho.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Mga Template',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Max na CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Pribado',
  'ob4_hl1_title'                       : 'Pribado at Ligtas',
  'ob4_hl1_sub'                         : 'Nananatili ang data sa iyong device.',
  'ob4_hl2_title'                       : 'Auto-Save',
  'ob4_hl2_sub'                         : 'Bawat keystroke ay nai-save agad.',
  'ob4_hl3_title'                       : 'Hanggang 30 CV',
  'ob4_hl3_sub'                         : 'Natatanging CV para sa bawat papel.',
  'ob4_hl4_title'                       : 'One-Tap na Pagbabahagi',
  'ob4_hl4_sub'                         : 'Magpadala ng PDF nang hindi umaalis sa app.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Namumukod-tangi mula sa karamihan',
  'home_hero_title'                     : 'Gumawa ng Iyong\nPropesyonal na CV',
  'home_hero_sub'                       : 'Bumuo ng kahanga-hangang resume\nsa loob ng ilang minuto',
  'home_hero_cta'                       : 'Simulan ang Pagbuo',
  'home_premium_soon'                   : 'Mag-upgrade sa Pro malapit na!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Pinakabago',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Huling Na-edit',
  'history_sort_by_template'            : 'Ayon sa Template',
  'history_sort_sheet_title'            : 'Ayusin Ayon Sa',
  'history_sort_alphabetical_full'      : 'Alpabeto (A–Z)',
  'history_premium_soon'                : 'Mag-upgrade sa Pro malapit na!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Mga Setting',
  'settings_section_preferences'        : 'Mga Kagustuhan',
  'settings_section_support'            : 'Suporta',
  'settings_section_legal'              : 'Legal',
  'settings_section_about'              : 'Tungkol Sa',
  'settings_language_tile_title'        : 'Wika',
  'settings_dark_mode_title'            : 'Dark Mode',
  'settings_dark_mode_on'               : 'Naka-enable ang dark theme',
  'settings_dark_mode_off'              : 'Naka-enable ang light theme',
  'settings_help_faq_title'             : 'Tulong at FAQ',
  'settings_help_faq_sub'               : 'Mga karaniwang tanong na nasagot',
  'settings_contact_support_title'      : 'Makipag-ugnayan sa Suporta',
  'settings_rate_app_title'             : 'I-rate ang App',
  'settings_rate_app_sub'               : 'Nag-eenjoy sa app? Mag-iwan ng review!',
  'settings_privacy_policy_title'       : 'Patakaran sa Privacy',
  'settings_terms_title'                : 'Mga Tuntunin ng Serbisyo',
  'settings_app_version_title'          : 'Bersyon ng App',
  'settings_email_error'                : 'Hindi mabuksan ang email app. Mangyaring mag-email sa cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Preview ng CV',
  'preview_header_sub'                  : 'Handa na para i-export',
  'preview_generating'                  : 'Ginagawa ang iyong CV...',
  'preview_failed_title'                : 'Nabigo ang Preview',
  'preview_failed_error'                : 'Error: {error}',
  'preview_go_back'                     : 'Bumalik',
  'preview_no_data'                     : 'Walang available na data',
  'preview_btn_print'                   : 'I-print',
  'preview_btn_download'                : 'I-download at Ibahagi',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Tulong at FAQ',
  'faq_category_all'                    : 'Lahat',
  'faq_empty'                           : 'Walang nahanap na resulta',
  'faq_contact_headline'                : 'Kailangan pa rin ng tulong?',
  'faq_contact_sub'                     : 'Nandito ang aming koponan para sa iyo.',
  'faq_contact_btn'                     : 'Makipag-ugnayan',
  'faq_email_error'                     : 'Hindi mabuksan ang email app. Mangyaring mag-email sa cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Pagsisimula',
  'faq_cat_templates'                   : 'Mga Template',
  'faq_cat_editing'                     : 'Pag-edit',
  'faq_cat_exporting'                   : 'Pag-export',
  'faq_cat_data_privacy'                : 'Data at Privacy',
  'faq_cat_troubleshooting'             : 'Pag-aayos ng Problema',
  'faq_q1'  : 'Paano ako gagawa ng aking unang CV?',
  'faq_a1'  : 'I-tap ang "+" na button sa home screen para magsimula ng bagong CV. Pumili ng template na naaangkop sa iyong estilo, pagkatapos ay punan ang iyong personal na detalye, karanasan sa trabaho, edukasyon, at mga kasanayan hakbang-hakbang. Ang iyong pag-unlad ay awtomatikong nai-save.',
  'faq_q2'  : 'Maaari ba akong gumawa ng higit sa isang CV?',
  'faq_a2'  : 'Oo! Maaari kang gumawa ng maraming CV para sa iba\'t ibang papel o industriya. Ang bawat CV ay naka-save nang hiwalay, kaya maaari mong i-angkop ang mga ito sa mga partikular na aplikasyon sa trabaho.',
  'faq_q3'  : 'Paano ko babaguhin ang aking CV template?',
  'faq_a3'  : 'Buksan ang iyong CV, i-tap ang icon ng template sa tuktok ng screen, at i-browse ang mga available na template. I-tap ang anumang template para i-preview ito sa iyong kasalukuyang nilalaman. Kumpirmahin para ilapat ito.',
  'faq_q4'  : 'Mayroon bang libre at premium na mga template?',
  'faq_a4'  : 'Oo. Ang isang seleksyon ng mga propesyonal na template ay available nang libre. Ang mga premium na template na may advanced na disenyo at palette ng kulay ay available sa pamamagitan ng isang beses na pagbili o subscription.',
  'faq_q5'  : 'Paano ako magdaragdag o mag-aalis ng mga seksyon?',
  'faq_a5'  : 'Sa CV editor, mag-scroll sa ibaba ng screen at i-tap ang "Magdagdag ng Seksyon" para isama ang mga karagdagan tulad ng Mga Wika, Mga Sertipikasyon, o Volunteer Work. Para alisin ang isang seksyon, i-tap ang header ng seksyon at piliin ang "Alisin."',
  'faq_q6'  : 'Paano ko muling iaaayos ang mga seksyon?',
  'faq_a6'  : 'Pindutin nang matagal ang drag handle (≡) sa tabi ng anumang header ng seksyon at i-drag ito sa iyong gustong posisyon. Ang mga pagbabago ay awtomatikong nai-save.',
  'faq_q7'  : 'Paano ko ie-export ang aking CV bilang PDF?',
  'faq_a7'  : 'Buksan ang iyong CV at i-tap ang button ng export (icon ng pagbabahagi) sa kanang sulok sa itaas. Piliin ang "I-export bilang PDF." Maaari mo itong i-save sa iyong device, ibahagi sa pamamagitan ng email, WhatsApp, o direktang i-upload sa mga job board.',
  'faq_q8'  : 'Anong mga format ng file ang sinusuportahan?',
  'faq_a8'  : 'Sa kasalukuyan, sinusuportahan ng App ang pag-export ng iyong CV bilang isang mataas na kalidad na PDF. Ang mga karagdagang format ay maaaring idagdag sa mga susunod na update.',
  'faq_q9'  : 'Saan naka-store ang data ng aking CV?',
  'faq_a9'  : 'Ang lahat ng data ng iyong CV ay naka-store nang lokal sa iyong device. Hindi namin ina-upload ang iyong personal na impormasyon sa aming mga server. Ibig sabihin, nananatiling pribado ang iyong data at accessible offline.',
  'faq_q10' : 'Paano ko i-backup ang aking mga CV?',
  'faq_a10' : 'Ang iyong mga CV ay kasama sa karaniwang backup ng iyong device (Google Drive backup sa Android, iCloud sa iOS) kung naka-enable ang backup sa mga setting ng iyong device. Maaari ka ring mag-export ng mga indibidwal na CV bilang mga PDF para mapanatili ang isang kopya.',
  'faq_q11' : 'Mabagal ang app. Ano ang dapat kong gawin?',
  'faq_a11' : 'Subukang isara at muling buksan ang app. Kung nagpapatuloy ang problema, i-restart ang iyong device. Tiyaking naka-install ang pinakabagong bersyon ng app mula sa Play Store / App Store.',
  'faq_q12' : 'Hindi tama ang pag-export ng aking CV. Ano ang dapat kong gawin?',
  'faq_a12' : 'Tiyaking mayroon kang sapat na espasyo sa storage sa iyong device. Subukang bawasan ang malalaking larawan sa iyong CV. Kung nagpapatuloy ang problema, makipag-ugnayan sa aming koponan ng suporta.',
  'faq_q13' : 'Nakalimutan kong i-save — nawala ba ang aking trabaho?',
  'faq_a13' : 'Hindi! Awtomatikong nini-save ng app ang iyong pag-unlad habang ine-edit mo ito.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Ang iyong karera, pinerpekto',
  'header_tooltip_back'                 : 'Bumalik',
  'header_tooltip_my_cvs'               : 'Ang Aking mga CV',
  'header_tooltip_settings'             : 'Mga Setting',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Ang Aking mga CV',
  'saved_count_single'                  : '{n} dokumento',
  'saved_count_plural'                  : '{n} na mga dokumento',
  'saved_limit_reached'                 : 'Naabot na ang limitasyon',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Lahat',
  'saved_filter_draft'                  : 'Draft',
  'saved_filter_complete'               : 'Kumpleto',
  'saved_status_complete'               : 'Kumpleto',
  'saved_status_saved'                  : 'Nai-save',
  'saved_status_draft'                  : 'Draft',
  'saved_empty_title'                   : 'Wala pang CV dito',
  'saved_empty_sub'                     : 'Simulan ang pagbuo ng iyong unang CV sa itaas',
  'saved_search_empty_title'            : 'Walang nahanap na resulta',
  'saved_search_empty_sub'              : 'Subukan ang ibang term sa paghahanap',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Scheme ng Kulay',
  'custom_font_settings_title'          : 'Mga Setting ng Font',
  'custom_font_family_label'            : 'Pamilya ng Font',
  'custom_font_size_label'              : 'Laki ng Font: ',
  'custom_current_template_title'       : 'Kasalukuyang Template',
  'custom_change_template_btn'          : 'Baguhin ang Template',
  'custom_tpl_modern'                   : 'Moderno',
  'custom_tpl_classic'                  : 'Klasiko',
  'custom_tpl_professional'             : 'Propesyonal',
  'custom_tpl_creative'                 : 'Malikhain',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Malinis at kontemporanong disenyo',
  'custom_tpl_classic_desc'             : 'Tradisyonal na propesyonal na layout',
  'custom_tpl_professional_desc'        : 'Template na nakatuon sa negosyo',
  'custom_tpl_creative_desc'            : 'Namumukod-tangi sa natatanging disenyo',
  'custom_tpl_minimal_desc'             : 'Simple at eleganteng estilo',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Pumili ng Template',
  'swipe_photo_badge'                   : 'Larawan',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Makulay',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Pinaka-popular',
  'tpl_nordic_tag'                      : 'Malinis',
  'tpl_vibrant_tag'                     : 'Malikhain',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'Matapang at may awtoridad para sa mga senior na papel',
  'tpl_nordic_desc'                     : 'Minimal na kalinawan na pinagkakatiwalaan ng mga nangungunang kumpanya',
  'tpl_vibrant_desc'                    : 'Namumukod-tangi sa enerhiya at kulay',
  'tpl_tech_dark_desc'                  : 'Estilo ng terminal para sa mga developer',
  'tpl_luxury_desc'                     : 'Gold-accented na prestihiyo sa itim',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Template',
  'detail_step_personal'                : 'Personal',
  'detail_step_experience'              : 'Karanasan',
  'detail_step_education'               : 'Edukasyon',
  'detail_step_skills'                  : 'Mga Kasanayan',
  'detail_step_additional'              : 'Karagdagan',
  'detail_step_references'              : 'Mga Sanggunian',
  'detail_step_customize'               : 'I-customize',
  'detail_banner_heading'               : 'Malapit na!',
  'detail_banner_btn'                   : 'Ituloy',
  'detail_banner_completion_label'      : 'Pagkumpleto',
  'detail_stat_created_label'           : 'Nilikha',
  'detail_stat_steps_label'             : 'Mga hakbang na tapos',
  'detail_section_template_style'       : 'Estilo ng Template',
  'detail_section_steps'                : 'Mga Hakbang',
  'detail_steps_counter'                : '{done} ng {total} ang kumpleto',
  'detail_step_sub'                     : 'Hakbang {n} ng {total}',
  'detail_section_activity'             : 'Aktibidad',
  'detail_activity_created'             : 'Nilikha',
  'detail_activity_last_edited'         : 'Huling Na-edit',
  'detail_activity_template'            : 'Template',
  'detail_btn_continue_editing'         : 'Ituloy ang Pag-edit',
  'detail_btn_edit_cv'                  : 'I-edit ang CV',
  'detail_option_rename'                : 'Palitan ang Pangalan ng CV',
  'detail_option_delete'                : 'Burahin ang CV',
  'detail_rename_title'                 : 'Palitan ang Pangalan ng CV',
  'detail_rename_hint'                  : 'hal. Software Engineer CV',
  'detail_rename_error_empty'           : 'Hindi maaaring walang laman ang pangalan',
  'detail_rename_btn_cancel'            : 'Kanselahin',
  'detail_rename_btn_save'              : 'I-save',
  'detail_rename_snackbar'              : 'Pinalitan ng pangalan sa "{name}"',
  'detail_delete_title'                 : 'Burahin ang CV?',
  'detail_delete_body'                  : 'Permanenteng mabubura ang "{name}". Hindi maaaring bawiin ang aksyong ito.',
  'detail_delete_btn_cancel'            : 'Kanselahin',
  'detail_delete_btn_confirm'           : 'Burahin',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Nakumpleto',
  'detail_check_tile_incomplete'        : 'Hindi pa napupunan',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Pumili ng Iyong Template',
  'chooser_subtitle'                    : 'Mag-swipe para mag-browse  ·  I-tap para pumili  ·  Pindutin para i-preview',
  'chooser_card_hold_hint'              : 'Pindutin para i-preview',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Napili',
  'chooser_modal_heading'               : 'Pangalanan ang Iyong CV',
  'chooser_modal_sub'                   : 'Bigyan ito ng pangalan para madaling mahanap sa Aking mga CV at Kasaysayan.',
  'chooser_modal_field_label'           : 'Pangalan ng CV',
  'chooser_modal_save_btn'              : 'I-save at Simulan ang Pagbuo',
  'chooser_modal_divider'               : 'o magpatuloy sa isang kasalukuyang CV',
  'chooser_nav_selected_sub'            : 'Napiling template',
  'chooser_nav_cta'                     : 'I-save at Magpatuloy',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Naabot na ang Maximum na Mga Entry',
  'editor_show_hide'                    : 'Ipakita/Itago',
  'editor_editing_badge'                : 'Ine-edit',
  'editor_field_required'               : 'Kinakailangan',
  'editor_tooltip_edit'                 : 'I-edit',
  'editor_tooltip_delete'               : 'Burahin',
  'editor_date_start'                   : 'Petsa ng Simula *',
  'editor_date_end'                     : 'Petsa ng Pagtatapos *',
  'editor_date_tap_hint'                : 'I-tap para pumili',
  'editor_date_dialog_title'            : 'Pumili ng Buwan at Taon',
  'editor_date_confirm'                 : 'Kumpirmahin',
  'editor_panel_hide'                   : 'Itago',
  'editor_panel_show'                   : 'Ipakita',
  'editor_validator_max_chars'          : 'Max {n} na karakter',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Buuin ang Iyong CV',
  'editor_header_step_sub'              : 'Hakbang {current} ng {total} · {label}',
  'editor_step_template'                : 'Template',
  'editor_step_personal'                : 'Personal',
  'editor_step_experience'              : 'Karanasan',
  'editor_step_education'               : 'Edukasyon',
  'editor_step_skills'                  : 'Mga Kasanayan',
  'editor_step_additional'              : 'Karagdagan',
  'editor_step_references'              : 'Mga Sanggunian',
  'editor_step_customize'               : 'I-customize',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'I-customize',
  'customize_subtitle'                  : 'Gawing natatangi ang iyong CV',
  'customize_smart_layout_btn'          : 'Smart Layout',
  'customize_back_to_top'               : 'Bumalik sa Taas',
  'customize_done_title'                : 'Handa ka na!',
  'customize_done_sub'                  : 'I-tap ang Preview CV sa ibaba para makita ang iyong natapos na CV',
  'customize_preview_btn'               : 'I-preview ang CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Scheme ng Kulay',
  'color_black'                         : 'Itim',
  'color_blue'                          : 'Asul',
  'color_nordic_blue'                   : 'Nordic Blue',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Teal',
  'color_green'                         : 'Berde',
  'color_purple'                        : 'Lila',
  'color_orange'                        : 'Kahel',
  'color_red'                           : 'Pula',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'Puti',
  'color_white_bg'                      : 'Puting Background',
  'color_maroon'                        : 'Maroon',
  'color_brutalist_yellow'              : 'Brutalist Yellow',
  'color_neon_blue'                     : 'Neon Blue',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'Maliwanag na Kulay-abo',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Pamilya ng Font',
  'customize_font_picker_title'         : 'Pumili ng Font',
  'customize_font_picker_sub'           : 'Bawat font ay napi-preview sa sarili nitong typeface',
  'customize_font_preview_sample'       : 'Ang mabilis na kayumanggi na lobo',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Laki ng Font',
  'customize_font_size_label'           : 'Laki ng Teksto',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Laki ng Larawan',
  'customize_image_size_label'          : 'Laki ng Larawan',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Live Preview',
  'preview_page_count_singular'         : '1 pahina',
  'preview_page_count_plural'           : '{n} na pahina',
  'preview_page_of'                     : 'Pahina {page} ng {total}',
  'preview_live_hint'                   : 'Agad na inilalapat ang mga pagbabago',
  'preview_template_unregistered'       : 'Hindi pa nairehistro sa customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Inihahanda ang iyong CV…',
  'preview_bar_print'                   : 'I-print',
  'preview_bar_save_pdf'                : 'I-save bilang PDF',
  'preview_bar_share'                   : 'Ibahagi',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Preview ng CV',
  'preview_screen_sub'                  : '{n} {unit} · eksaktong tulad ng naka-print',
  'preview_page_singular'               : 'pahina',
  'preview_page_plural'                 : 'mga pahina',
  'preview_pdf_filename'                : 'Ang_Aking_CV',
  'preview_share_subject'               : 'Ang Aking CV',
  'preview_snack_print_failed'          : 'Nabigo ang pag-print: {e}',
  'preview_snack_saved'                 : 'Nai-save ang CV sa Downloads ✓',
  'preview_snack_export_failed'         : 'Nabigo ang pag-export: {e}',
  'preview_snack_share_failed'          : 'Nabigo ang pagbabahagi: {e}',
  'preview_template_not_registered'     : 'Hindi nairehistro ang template',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Isara ang preview',
  'preview_modal_hint_photo'            : 'Sinusuportahan ang profile photo  ·  I-tap ang card para pumili',
  'preview_modal_hint_no_photo'         : 'I-tap ang isang template card para piliin ito',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Ang Aking CV',
  'time_just_now'                       : 'Kailan lang',
  'time_minutes_ago'                    : '{n}m na ang nakalipas',
  'time_hours_ago'                      : '{n}h na ang nakalipas',
  'time_yesterday'                      : 'Kahapon',
  'time_days_ago'                       : '{n} araw na ang nakalipas',
  'time_one_week_ago'                   : '1 linggo na ang nakalipas',
  'time_weeks_ago'                      : '{n} linggo na ang nakalipas',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegante',
  'tpl_tag_classic'                     : 'Klasiko',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Malikhain',
  'tpl_tag_bold'                        : 'Matapang',

  // ─── preview_registry.dart — template names (IDs 6–24 + new 21–24) ──────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Mga card na teal hanggang violet gradient',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Estilo ng magazine na pula at cream',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Malambot',
  'tpl_pastel_soft_desc'                : 'Lavender sidebar, malambot na mga card',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Raw na grid, matapang na hangganan at dilaw',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Forest green na may timeline',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Dark na canvas na may mga ring chart',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Geometric na gintong luxury ng 1920s',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Dark na infographic na may mga ring',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Dark na sidebar na may orange na pop',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Malinis na minimal, malambot na grey na tono',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Mainit na beige na eleganteng tono',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Matalas na itim at puting klasiko',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klasikong layout na friendly sa ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Estilo ng dark orange na infographic',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Technical na drawing sa grid',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Klasikong two-column na layout ng label',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Mga shaded na header na may diamond leader',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Nakasentro na mga header, mga accent na kumpanya',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Matapang na pangalan, mga timeline dot at tagumpay',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Personal na Impormasyon',
  'personal_subtitle'                   : 'Sabihin sa mga employer kung sino ka',
  'personal_profile_counter'            : '{n}/{max} na profile',
  'personal_info_banner'                : 'Mag-save ng hanggang 5 profile at pumili ng isa bawat CV. Ang iyong seleksyon ay naaalala para sa bawat CV nang hiwalay.',
  'personal_snack_max'                  : 'Naabot na ang maximum na {n} profile.',
  'personal_add_btn'                    : 'Magdagdag ng Bagong Profile',
  'personal_library_title'              : 'Mga Naka-save na Profile',
  'personal_selected_one'               : '1 napili',
  'personal_selected_none'              : 'wala na napili',
  'personal_library_hint'               : 'I-tap ang isang card para piliin ito para sa CV na ito lamang. Ang ibang mga CV ay nagpapanatili ng sarili nilang mga independyenteng seleksyon.',
  'personal_empty_message'              : 'Wala pang naka-save na profile',
  'personal_empty_sub'                  : 'I-tap sa itaas para idagdag ang iyong personal na impormasyon',
  'personal_nav_next'                   : 'I-save at Magpatuloy',
  'personal_card_active_badge'          : 'Aktibo para sa CV na ito',
  'personal_sheet_title_add'            : 'Bagong Profile',
  'personal_sheet_title_edit'           : 'I-edit ang Profile',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Ang Brutalist template ay may compact na mga field ng contact. Mas maikling mga halaga (hal. lungsod lamang) ang mas magandang tingnan.',
  'personal_section_photo'              : 'Profile Photo',
  'personal_section_basic'              : 'Mga Pangunahing Detalye',
  'personal_section_contact'            : 'Pakikipag-ugnayan',
  'personal_section_online'             : 'Online na Presensya',
  'personal_section_summary'            : 'Propesyonal na Buod',
  'personal_field_first_name'           : 'Pangalan *',
  'personal_field_last_name'            : 'Apelyido',
  'personal_field_job_title'            : 'Titulo sa Trabaho *',
  'personal_field_email'                : 'Email Address *',
  'personal_field_phone'                : 'Numero ng Telepono *',
  'personal_field_location'             : 'Lokasyon',
  'personal_field_location_brut'        : 'Lokasyon (lungsod lamang)',
  'personal_field_website'              : 'Website / Portfolio',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'hal. Maria',
  'personal_hint_last_name'             : 'hal. Santos',
  'personal_hint_job_title'             : 'hal. Senior Engineer',
  'personal_hint_email'                 : 'hal. maria@halimbawa.com',
  'personal_hint_phone'                 : 'hal. +63 917 123 4567',
  'personal_hint_location'              : 'hal. Maynila, Pilipinas',
  'personal_hint_location_brut'         : 'hal. Maynila, PH',
  'personal_hint_website'               : 'hal. github.com/mariasantos',
  'personal_hint_website_brut'          : 'hal. github.com/maria',
  'personal_hint_linkedin'              : 'hal. linkedin.com/in/mariasantos',
  'personal_hint_linkedin_brut'         : 'hal. linkedin.com/in/maria',
  'personal_summary_hint_label'         : 'Panatilihing maikli — ito ay lilitaw sa tuktok ng iyong CV.',
  'personal_hint_summary'               : 'Isang maikling 2–3 pangungusap na buod ng iyong background at mga layunin...',
  'personal_validator_email'            : 'Magpasok ng valid na email',
  'personal_field_char_limit_tooltip'   : 'Naabot na ang limitasyon ng karakter',
  'personal_sheet_btn_save'             : 'I-save ang Profile',
  'personal_sheet_btn_update'           : 'I-save ang mga Pagbabago',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Pumili ng Larawan',
  'photo_option_gallery'                : 'Pumili mula sa Gallery',
  'photo_option_camera'                 : 'Kumuha ng Larawan',
  'photo_option_reposition'             : 'Muling iposisyon ang Larawan',
  'photo_option_remove'                 : 'Alisin ang Larawan',
  'photo_status_added'                  : 'Naidagdag ang larawan ✓',
  'photo_status_empty'                  : 'Magdagdag ng propesyonal na headshot',
  'photo_chip_gallery'                  : 'Gallery',
  'photo_chip_camera'                   : 'Camera',
  'photo_chip_reposition'               : 'Muling Iposisyon',
  'photo_reposition_title'              : 'Muling Iposisyon ang Larawan',
  'photo_reposition_sub'                : 'I-drag ang larawan para ayusin ang posisyon',
  'photo_reposition_reset'              : 'I-reset sa gitna',
  'photo_reposition_apply'              : 'Ilapat',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Mga Kasanayan',
  'skills_subtitle'                     : 'I-highlight ang iyong mga pangunahing kakayahan',
  'skills_add_btn'                      : 'Magdagdag ng Bagong Kasanayan',
  'skills_snack_max_icons'              : 'Maximum na 10 icon ang napili.',
  'skills_snack_max_skills'             : 'Naabot na ang maximum na 15 kasanayan.',
  'skills_library_title'                : 'Mga Naka-save na Kasanayan',
  'skills_library_hint'                 : 'Ang mga naka-check na kasanayan ay kasama sa CV na ito. Ang iyong mga seleksyon ay awtomatikong nai-save.',
  'skills_nav_next'                     : 'Magpatuloy sa Karagdagan',
  'skills_wina_header_icon_bar'         : 'Header Icon Bar',
  'skills_wina_on'                      : 'ON',
  'skills_wina_off'                     : 'OFF',
  'skills_wina_bar_on_sub'              : 'Mga may kulay na icon na bilog na ipinapakita sa header ng CV.',
  'skills_wina_bar_off_sub'             : 'Nakatago ang hanay ng icon — mas maraming espasyo para sa impormasyon ng contact.',
  'skills_wina_palette_hint'            : 'Ang mga icon ay lilitaw bilang mga may kulay na bilog sa pagkakasunod ng palette.',
  'skills_wina_preview_label'           : 'Preview',
  'skills_wina_disabled_hint'           : 'I-enable ang icon bar sa itaas para pumili kung aling mga icon ang lilitaw sa header ng CV.',
  'skills_sheet_title_add'              : 'Magdagdag ng Kasanayan',
  'skills_sheet_title_edit'             : 'I-edit ang Kasanayan',
  'skills_sheet_field_name'             : 'Pangalan ng Kasanayan *',
  'skills_sheet_hint_short'             : 'hal. Flutter, Disenyo',
  'skills_sheet_hint_long'              : 'hal. Flutter, Pamamahala ng Proyekto',
  'skills_sheet_validator_max'          : 'Max {n} na karakter',
  'skills_sheet_proficiency'            : 'Antas ng Kahusayan',
  'skills_sheet_beginner'               : 'Baguhan',
  'skills_sheet_expert'                 : 'Eksperto',
  'skills_sheet_btn_save'               : 'I-save ang Kasanayan',
  'skills_sheet_btn_update'             : 'I-update ang Kasanayan',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Mga Personal na Sanggunian',
  'refs_subtitle'                       : 'Mga taong maaaring personal na magtestigo para sa iyo',
  'refs_add_btn'                        : 'Magdagdag ng Bagong Personal na Sanggunian',
  'refs_snack_max_selected'             : 'Maximum na 4 sanggunian ang maaaring mapili para sa isang CV.',
  'refs_snack_max_saved'                : 'Naabot na ang maximum na 10 naka-save na sanggunian.',
  'refs_library_title'                  : 'Mga Naka-save na Sanggunian',
  'refs_library_hint'                   : 'Ang mga naka-check na sanggunian ay kasama sa CV na ito. Max 4 bawat CV. Ang iyong mga seleksyon ay awtomatikong nai-save.',
  'refs_nav_next'                       : 'Magpatuloy sa I-customize',
  'refs_sheet_title_add'                : 'Magdagdag ng Personal na Sanggunian',
  'refs_sheet_title_edit'               : 'I-edit ang Personal na Sanggunian',
  'refs_sheet_sub_add'                  : 'Isang taong maaaring personal na magrekomenda sa iyo sa mga employer.',
  'refs_sheet_sub_edit'                 : 'I-update ang mga detalye ng sangguniang ito sa ibaba.',
  'refs_sheet_field_name'               : 'Buong Pangalan *',
  'refs_sheet_field_title'              : 'Titulo sa Trabaho *',
  'refs_sheet_field_company'            : 'Kumpanya (opsyonal)',
  'refs_sheet_field_email'              : 'Email Address *',
  'refs_sheet_field_phone'              : 'Numero ng Telepono *',
  'refs_sheet_hint_name'                : 'hal. Jose Reyes',
  'refs_sheet_hint_title'               : 'hal. Engineering Manager',
  'refs_sheet_hint_company'             : 'hal. Acme Corp',
  'refs_sheet_hint_email'               : 'hal. jose@acme.com',
  'refs_sheet_hint_phone'               : 'hal. +63 917 123 4567',
  'refs_sheet_validator_email'          : 'Magpasok ng valid na email address',
  'refs_sheet_btn_save'                 : 'I-save ang Personal na Sanggunian',
  'refs_sheet_btn_update'               : 'I-update ang Personal na Sanggunian',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Karanasan sa Trabaho',
  'exp_subtitle'                        : 'Idagdag ang iyong kasaysayan sa trabaho',
  'exp_banner_info'                     : 'Hanggang {n} responsibilidad bawat papel ang lilitaw sa CV. Ang 3–6 na papel ay karaniwang kasya sa 1–2 pahina.',
  'exp_add_btn'                         : 'Magdagdag ng Bagong Karanasan',
  'exp_snack_max_selected'              : 'Maximum na 8 karanasan ang maaaring mapili para sa isang CV.',
  'exp_snack_max_saved'                 : 'Naabot na ang maximum na 12 naka-save na karanasan.',
  'exp_library_title'                   : 'Mga Naka-save na Karanasan',
  'exp_library_hint'                    : 'Ang mga naka-check na entry ay kasama sa CV na ito lamang. Ang ibang mga CV ay nagpapanatili ng sarili nilang mga independyenteng seleksyon.',
  'exp_nav_next'                        : 'Magpatuloy sa Edukasyon',
  'exp_empty_message'                   : 'Wala pang naidagdag na karanasan',
  'exp_empty_sub'                       : 'I-tap sa itaas para idagdag ang iyong unang papel',
  'exp_card_resp_singular'              : 'responsibilidad',
  'exp_card_resp_plural'                : 'mga responsibilidad',
  'exp_card_resp_tooltip'               : 'Ang unang 8 responsibilidad lamang ang lilitaw sa CV',
  'exp_sheet_title_add'                 : 'Magdagdag ng Karanasan',
  'exp_sheet_title_edit'                : 'I-edit ang Karanasan',
  'exp_sheet_field_job_title'           : 'Titulo sa Trabaho *',
  'exp_sheet_field_company'             : 'Kumpanya *',
  'exp_sheet_field_location'            : 'Lokasyon',
  'exp_sheet_section_responsibilities'  : 'Mga Pangunahing Responsibilidad',
  'exp_sheet_resp_hint_info'            : 'Max 8 na bullet point · 200 karakter bawat isa',
  'exp_sheet_resp_label'                : 'Responsibilidad {n}',
  'exp_sheet_resp_hint'                 : 'hal. Nanguna sa isang koponan ng 5 inhinyero',
  'exp_sheet_resp_add_btn'              : 'Magdagdag ng Responsibilidad',
  'exp_sheet_resp_max_info'             : 'Naabot na ang maximum na {n} responsibilidad',
  'exp_sheet_resp_validator_max'        : 'Max 200 na karakter',
  'exp_sheet_hint_job_title'            : 'hal. Senior Developer',
  'exp_sheet_hint_location'             : 'hal. Maynila, Pilipinas',
  'exp_sheet_btn_save'                  : 'I-save ang Karanasan',
  'exp_sheet_btn_update'                : 'I-save ang mga Pagbabago',
  'exp_date_present'                    : 'Kasalukuyan / Kasalukuyang Papel',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Edukasyon',
  'edu_subtitle'                        : 'Idagdag ang iyong akademikong background',
  'edu_add_btn'                         : 'Magdagdag ng Bagong Edukasyon',
  'edu_snack_max_selected'              : 'Maximum na 8 entry ng edukasyon ang maaaring mapili para sa isang CV.',
  'edu_snack_max_saved'                 : 'Naabot na ang maximum na 12 naka-save na entry ng edukasyon.',
  'edu_library_title'                   : 'Naka-save na Edukasyon',
  'edu_library_hint'                    : 'Ang mga naka-check na entry ay kasama sa CV na ito. Ang iyong mga seleksyon ay awtomatikong nai-save.',
  'edu_nav_next'                        : 'Magpatuloy sa Mga Kasanayan',
  'edu_empty_message'                   : 'Wala pang naidagdag na edukasyon',
  'edu_empty_sub'                       : 'I-tap sa itaas para idagdag ang iyong mga kwalipikasyon',
  'edu_card_bullet_singular'            : 'bullet point',
  'edu_card_bullet_plural'              : 'mga bullet point',
  'edu_sheet_title_add'                 : 'Magdagdag ng Edukasyon',
  'edu_sheet_title_edit'                : 'I-edit ang Edukasyon',
  'edu_sheet_field_degree'              : 'Degree / Kwalipikasyon *',
  'edu_sheet_field_institution'         : 'Institusyon *',
  'edu_sheet_section_key_points'        : 'Mga Pangunahing Punto',
  'edu_sheet_key_points_hint_info'      : 'Opsyonal · 1 bullet point · Max 100 karakter',
  'edu_sheet_point_label'               : 'Punto {n}',
  'edu_sheet_point_add_btn'             : 'Magdagdag ng Bullet Point',
  'edu_sheet_point_max_info'            : 'Naabot na ang maximum na {n} bullet point',
  'edu_sheet_point_validator_max'       : 'Max {n} na karakter',
  'edu_sheet_hint_degree'               : 'hal. BSc Computer Science',
  'edu_sheet_hint_institution'          : 'hal. Unibersidad ng Pilipinas',
  'edu_sheet_hint_bullet'               : 'hal. First Class Honours',
  'edu_sheet_btn_save'                  : 'I-save ang Edukasyon',
  'edu_sheet_btn_update'                : 'I-save ang mga Pagbabago',
  'edu_date_present'                    : 'Kasalukuyan / Kasalukuyang Pag-aaral',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Karagdagang Impormasyon',
  'additional_subtitle'                 : 'Mga sertipikasyon, wika at iba pa',
  'additional_cert_section_title'       : 'Mga Sertipikasyon',
  'additional_cert_counter'             : '{sel}/{total} napili · max {max}',
  'additional_cert_hide'                : 'Itago',
  'additional_cert_show'                : 'Ipakita',
  'additional_cert_add_btn'             : 'Magdagdag',
  'additional_cert_snack_max'           : 'Naabot na ang maximum na {n} entry ng sertipikasyon.',
  'additional_cert_hint'                : 'Ang mga naka-check na entry ay kasama sa CV na ito. Ang iyong mga seleksyon ay awtomatikong nai-save.',
  'additional_cert_empty'               : 'Wala pang naidagdag na sertipikasyon',
  'additional_lang_section_title'       : 'Mga Wika',
  'additional_lang_add_hint'            : 'hal. Espanyol',
  'additional_lang_snack_max'           : 'Naabot na ang maximum na {n} entry ng wika.',
  'additional_lang_empty'               : 'Wala pang naidagdag na wika',
  'additional_hobby_section_title'      : 'Mga Libangan at Interes',
  'additional_hobby_add_hint'           : 'hal. Litratista',
  'additional_hobby_snack_max'          : 'Naabot na ang maximum na {n} entry ng libangan.',
  'additional_hobby_empty'              : 'Wala pang naidagdag na libangan',
  'additional_section_hint'             : 'Ang mga naka-check na entry ay kasama sa CV na ito. Ang iyong mga seleksyon ay awtomatikong nai-save.',
  'additional_nav_next'                 : 'Magpatuloy sa mga Referee',
  'cert_sheet_title_add'                : 'Magdagdag ng Sertipikasyon',
  'cert_sheet_title_edit'               : 'I-edit ang Sertipikasyon',
  'cert_sheet_sub'                      : 'Magdagdag ng kwalipikasyon, sertipiko o propesyonal na kredensyal.',
  'cert_sheet_field_name'               : 'Pangalan ng Sertipikasyon *',
  'cert_sheet_field_issued_by'          : 'Inilabas ng (opsyonal)',
  'cert_sheet_field_short_desc'         : 'Maikling Paglalarawan (opsyonal)',
  'cert_sheet_hint_name'                : 'hal. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'hal. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'hal. Nakamit noong 2024',
  'cert_sheet_btn_save'                 : 'I-save ang Sertipikasyon',
  'cert_sheet_btn_update'               : 'I-update ang Sertipikasyon',
  'simple_sheet_title_add_language'     : 'Magdagdag ng Wika',
  'simple_sheet_title_edit_language'    : 'I-edit ang Wika',
  'simple_sheet_title_add_hobby'        : 'Magdagdag ng Libangan',
  'simple_sheet_title_edit_hobby'       : 'I-edit ang Libangan',
  'simple_sheet_btn_save'               : 'I-save',
  'simple_sheet_btn_update'             : 'I-update',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Pakikipag-ugnayan',
  'pdf_section_about_me'                : 'Tungkol sa Akin',
  'pdf_section_summary'                 : 'Buod',
  'pdf_section_summary_short'           : 'Buod',
  'pdf_section_profile'                 : 'Profile',
  'pdf_section_experience'              : 'Karanasan',
  'pdf_section_experience_short'        : 'Karanasan',
  'pdf_section_education'               : 'Edukasyon',
  'pdf_section_skills'                  : 'Mga Kasanayan',
  'pdf_section_languages'               : 'Mga Wika',
  'pdf_label_email'                     : 'Email',
  'pdf_label_phone'                     : 'Telepono',
  'pdf_label_location'                  : 'Lokasyon',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Naabot ang Limitasyon ng CV',
  'limit_dialog_body'                   : 'Naabot mo na ang maximum na 30 CV. Mangyaring magtanggal ng isang CV bago gumawa ng bago.',
  'limit_dialog_go_to_my_cvs'           : 'Pumunta sa Aking mga CV',
  'limit_dialog_cancel'                 : 'Kanselahin',
  'refs_count_summary'                  : '{checked}/{maxChecked} napili · {saved}/{maxSaved} nai-save',
  'refs_selected_badge'                 : '{n} napili',
  'refs_empty_message'                  : 'Wala pang naka-save na sanggunian',
  'refs_empty_sub'                      : 'I-tap sa itaas para magdagdag ng personal na sanggunian',
};