// lib/language_keys/lang_pl_polish.dart
//
// Polish — translation map.
// All user-visible strings matching lang_en_english.dart

const Map<String, String> plPolish = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nie znaleziono języków',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Pomiń',
  'onboarding_next'                     : 'Dalej',
  'onboarding_get_started'              : 'Zacznij',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Witaj',
  'ob1_title'                           : 'Stwórz CV, które\nOtwiera Drzwi',
  'ob1_body'                            : 'Wyróżnij się spośród setek kandydatów. Zbuduj dopracowane, skuteczne CV w kilka minut — bez znajomości grafiki.',
  'ob1_pill_label'                      : 'Profesjonalny kreator CV',
  'ob1_chip_templates'                  : '24+ szablony',
  'ob1_chip_pdf'                        : 'Eksport PDF',
  'ob1_chip_free'                       : 'Bezpłatne',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Szablony',
  'ob2_title'                           : 'Każda branża.\nKażda ambicja.',
  'ob2_body'                            : 'Od eleganckich układów po odważne projekty kreatywne — szablon, który opowie Twoją historię.',
  'ob2_tap_hint'                        : 'Stuknij szablon, aby podejrzeć',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'Korporacyjny',
  'ob2_tag_creative'                    : 'Kreatywny',
  'ob2_tag_minimal'                     : 'Minimalny',
  'ob2_tag_modern'                      : 'Nowoczesny',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Inteligentny układ',
  'ob3_title'                           : 'Twoje CV.\nPerfekt ułożone.',
  'ob3_body'                            : 'Inteligentny układ zmienia kolejność sekcji, aby uzyskać maksymalny efekt — umieszczając najsilniejsze treści tam, gdzie rekruterzy patrzą najpierw.',
  'ob3_badge_smart_layout'              : 'Inteligentny układ',
  'ob3_badge_cv_ready'                  : 'CV gotowe!',
  'ob3_step1_label'                     : 'Wybierz szablon',
  'ob3_step1_desc'                      : 'Wybierz spośród 24+ projektów.',
  'ob3_step2_label'                     : 'Uzupełnij dane',
  'ob3_step2_desc'                      : 'Prowadzone pola dla wszystkich sekcji.',
  'ob3_step3_label'                     : 'Inteligentny układ',
  'ob3_step3_desc'                      : 'Jedno stuknięcie — idealne CV.',
  'ob3_step4_label'                     : 'Eksportuj jako PDF',
  'ob3_step4_desc'                      : 'Perfekcyjny PDF gotowy do wysłania.',
  'ob3_section_work'                    : 'Doświadczenie zawodowe',
  'ob3_section_education'               : 'Edukacja',
  'ob3_section_skills'                  : 'Umiejętności',
  'ob3_section_references'              : 'Referencje',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Gotowe do działania',
  'ob4_title'                           : 'Dlaczego najlepsi kandydaci\nWybierają kreator CV',
  'ob4_visual_headline'                 : 'Wszystko gotowe!',
  'ob4_visual_subline'                  : 'Masz wszystko, czego potrzebujesz, by dostać pracę.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Szablony',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Maks. CV',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Eksport',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Prywatne',
  'ob4_hl1_title'                       : 'Prywatne i bezpieczne',
  'ob4_hl1_sub'                         : 'Dane pozostają na Twoim urządzeniu.',
  'ob4_hl2_title'                       : 'Automatyczny zapis',
  'ob4_hl2_sub'                         : 'Każde naciśnięcie klawisza zapisywane od razu.',
  'ob4_hl3_title'                       : 'Do 30 CV',
  'ob4_hl3_sub'                         : 'Unikalne CV dla każdej roli.',
  'ob4_hl4_title'                       : 'Udostępnianie jednym stuknięciem',
  'ob4_hl4_sub'                         : 'Wyślij PDF bez wychodzenia z aplikacji.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Wyróżnij się z tłumu',
  'home_hero_title'                     : 'Stwórz swoje\nprofesjonalne CV',
  'home_hero_sub'                       : 'Zbuduj imponujące CV\nw kilka minut',
  'home_hero_cta'                       : 'Zacznij tworzyć',
  'home_premium_soon'                   : 'Ulepszenie do Pro już wkrótce!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Najnowsze',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Ostatnio edytowane',
  'history_sort_by_template'            : 'Według szablonu',
  'history_sort_sheet_title'            : 'Sortuj według',
  'history_sort_alphabetical_full'      : 'Alfabetycznie (A–Z)',
  'history_premium_soon'                : 'Ulepszenie do Pro już wkrótce!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Ustawienia',
  'settings_section_preferences'        : 'Preferencje',
  'settings_section_support'            : 'Wsparcie',
  'settings_section_legal'              : 'Prawne',
  'settings_section_about'              : 'O aplikacji',
  'settings_language_tile_title'        : 'Język',
  'settings_dark_mode_title'            : 'Tryb ciemny',
  'settings_dark_mode_on'               : 'Włączono ciemny motyw',
  'settings_dark_mode_off'              : 'Włączono jasny motyw',
  'settings_help_faq_title'             : 'Pomoc i FAQ',
  'settings_help_faq_sub'               : 'Odpowiedzi na najczęstsze pytania',
  'settings_contact_support_title'      : 'Kontakt z pomocą techniczną',
  'settings_rate_app_title'             : 'Oceń aplikację',
  'settings_rate_app_sub'               : 'Podoba Ci się aplikacja? Zostaw opinię!',
  'settings_privacy_policy_title'       : 'Polityka prywatności',
  'settings_terms_title'                : 'Warunki korzystania',
  'settings_app_version_title'          : 'Wersja aplikacji',
  'settings_email_error'                : 'Nie można otworzyć aplikacji e-mail. Wyślij wiadomość na adres cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Podgląd CV',
  'preview_header_sub'                  : 'Gotowe do eksportu',
  'preview_generating'                  : 'Generowanie CV...',
  'preview_failed_title'                : 'Podgląd nie powiódł się',
  'preview_failed_error'                : 'Błąd: {error}',
  'preview_go_back'                     : 'Wróć',
  'preview_no_data'                     : 'Brak danych',
  'preview_btn_print'                   : 'Drukuj',
  'preview_btn_download'                : 'Pobierz i udostępnij',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Pomoc i FAQ',
  'faq_category_all'                    : 'Wszystkie',
  'faq_empty'                           : 'Nie znaleziono wyników',
  'faq_contact_headline'                : 'Nadal potrzebujesz pomocy?',
  'faq_contact_sub'                     : 'Nasz zespół jest do Twojej dyspozycji.',
  'faq_contact_btn'                     : 'Kontakt',
  'faq_email_error'                     : 'Nie można otworzyć aplikacji e-mail. Wyślij wiadomość na adres cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Pierwsze kroki',
  'faq_cat_templates'                   : 'Szablony',
  'faq_cat_editing'                     : 'Edycja',
  'faq_cat_exporting'                   : 'Eksport',
  'faq_cat_data_privacy'                : 'Dane i prywatność',
  'faq_cat_troubleshooting'             : 'Rozwiązywanie problemów',
  'faq_q1'  : 'Jak stworzyć swoje pierwsze CV?',
  'faq_a1'  : 'Stuknij przycisk "+" na ekranie głównym, aby rozpocząć nowe CV. Wybierz szablon odpowiadający Twojemu stylowi, a następnie krok po kroku uzupełnij dane osobowe, doświadczenie zawodowe, wykształcenie i umiejętności. Postęp jest zapisywany automatycznie.',
  'faq_q2'  : 'Czy mogę stworzyć więcej niż jedno CV?',
  'faq_a2'  : 'Tak! Możesz tworzyć wiele CV dla różnych stanowisk lub branż. Każde CV jest zapisywane osobno, dzięki czemu możesz dostosować je do konkretnych ofert pracy.',
  'faq_q3'  : 'Jak zmienić szablon CV?',
  'faq_a3'  : 'Otwórz CV, stuknij ikonę szablonu u góry ekranu i przeglądaj dostępne szablony. Stuknij dowolny szablon, aby zobaczyć podgląd z Twoimi danymi. Potwierdź, aby zastosować.',
  'faq_q4'  : 'Czy są szablony bezpłatne i premium?',
  'faq_a4'  : 'Tak. Wybór profesjonalnych szablonów jest dostępny bezpłatnie. Szablony premium z zaawansowanymi projektami i paletami kolorów są dostępne poprzez jednorazowy zakup lub subskrypcję.',
  'faq_q5'  : 'Jak dodać lub usunąć sekcje?',
  'faq_a5'  : 'W edytorze CV przewiń na dół ekranu i stuknij "Dodaj sekcję", aby dodać m.in. języki, certyfikaty lub wolontariat. Aby usunąć sekcję, stuknij nagłówek sekcji i wybierz "Usuń."',
  'faq_q6'  : 'Jak zmienić kolejność sekcji?',
  'faq_a6'  : 'Przytrzymaj uchwyt przeciągania (≡) obok nagłówka sekcji i przeciągnij go w wybrane miejsce. Zmiany są zapisywane automatycznie.',
  'faq_q7'  : 'Jak wyeksportować CV jako PDF?',
  'faq_a7'  : 'Otwórz CV i stuknij przycisk eksportu (ikona udostępniania) w prawym górnym rogu. Wybierz "Eksportuj jako PDF". Następnie możesz zapisać plik na urządzeniu, udostępnić go e-mailem, WhatsAppem lub przesłać bezpośrednio na portale pracy.',
  'faq_q8'  : 'Jakie formaty plików są obsługiwane?',
  'faq_a8'  : 'Aplikacja obsługuje eksport CV jako wysokiej jakości PDF. Dodatkowe formaty mogą zostać dodane w przyszłych aktualizacjach.',
  'faq_q9'  : 'Gdzie przechowywane są dane CV?',
  'faq_a9'  : 'Wszystkie dane CV są przechowywane lokalnie na Twoim urządzeniu. Nie przesyłamy Twoich danych osobowych na nasze serwery. Dzięki temu dane pozostają prywatne i dostępne offline.',
  'faq_q10' : 'Jak wykonać kopię zapasową CV?',
  'faq_a10' : 'Twoje CV jest uwzględniane w standardowej kopii zapasowej urządzenia (kopia zapasowa Google Drive na Androidzie, iCloud na iOS), jeśli masz włączoną kopię zapasową w ustawieniach urządzenia. Możesz też eksportować poszczególne CV jako pliki PDF.',
  'faq_q11' : 'Aplikacja działa powoli. Co mam zrobić?',
  'faq_a11' : 'Spróbuj zamknąć i ponownie otworzyć aplikację. Jeśli problem nadal występuje, uruchom ponownie urządzenie. Upewnij się, że masz zainstalowaną najnowszą wersję aplikacji ze Sklepu Play / App Store.',
  'faq_q12' : 'Moje CV nie eksportuje się poprawnie. Co mam zrobić?',
  'faq_a12' : 'Upewnij się, że masz wystarczającą ilość miejsca w pamięci urządzenia. Spróbuj zmniejszyć duże obrazy w CV. Jeśli problem nadal występuje, skontaktuj się z naszym zespołem wsparcia.',
  'faq_q13' : 'Zapomniałem/am zapisać — czy moja praca przepadła?',
  'faq_a13' : 'Nie martw się! Aplikacja zapisuje Twój postęp na bieżąco podczas edycji.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Twoja kariera, dopracowana',
  'header_tooltip_back'                 : 'Wstecz',
  'header_tooltip_my_cvs'               : 'Moje CV',
  'header_tooltip_settings'             : 'Ustawienia',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Moje CV',
  'saved_count_single'                  : '{n} dokument',
  'saved_count_plural'                  : '{n} dokumenty',
  'saved_limit_reached'                 : 'Osiągnięto limit',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'Wszystkie',
  'saved_filter_draft'                  : 'Szkic',
  'saved_filter_complete'               : 'Ukończone',
  'saved_status_complete'               : 'Ukończone',
  'saved_status_saved'                  : 'Zapisane',
  'saved_status_draft'                  : 'Szkic',
  'saved_empty_title'                   : 'Brak CV',
  'saved_empty_sub'                     : 'Zacznij tworzyć pierwsze CV powyżej',
  'saved_search_empty_title'            : 'Nie znaleziono wyników',
  'saved_search_empty_sub'              : 'Spróbuj innego wyszukiwanego hasła',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Schemat kolorów',
  'custom_font_settings_title'          : 'Ustawienia czcionki',
  'custom_font_family_label'            : 'Rodzina czcionek',
  'custom_font_size_label'              : 'Rozmiar czcionki: ',
  'custom_current_template_title'       : 'Aktualny szablon',
  'custom_change_template_btn'          : 'Zmień szablon',
  'custom_tpl_modern'                   : 'Nowoczesny',
  'custom_tpl_classic'                  : 'Klasyczny',
  'custom_tpl_professional'             : 'Profesjonalny',
  'custom_tpl_creative'                 : 'Kreatywny',
  'custom_tpl_minimal'                  : 'Minimalny',
  'custom_tpl_modern_desc'              : 'Czysty i współczesny design',
  'custom_tpl_classic_desc'             : 'Tradycyjny profesjonalny układ',
  'custom_tpl_professional_desc'        : 'Szablon zorientowany biznesowo',
  'custom_tpl_creative_desc'            : 'Wyróżnij się unikalnym projektem',
  'custom_tpl_minimal_desc'             : 'Prosty i elegancki styl',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Wybierz szablon',
  'swipe_photo_badge'                   : 'Zdjęcie',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'Najpopularniejszy',
  'tpl_nordic_tag'                      : 'Przejrzysty',
  'tpl_vibrant_tag'                     : 'Kreatywny',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elitarny',
  'tpl_executive_desc'                  : 'Wyrazisty i autorytatywny dla wyższych stanowisk',
  'tpl_nordic_desc'                     : 'Minimalna przejrzystość ceniona przez czołowe firmy',
  'tpl_vibrant_desc'                    : 'Wyróżnij się energią i kolorem',
  'tpl_tech_dark_desc'                  : 'Estetyka terminala dla deweloperów',
  'tpl_luxury_desc'                     : 'Złote akcenty prestiżu na czarnym tle',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Szablon',
  'detail_step_personal'                : 'Dane osobowe',
  'detail_step_experience'              : 'Doświadczenie',
  'detail_step_education'               : 'Edukacja',
  'detail_step_skills'                  : 'Umiejętności',
  'detail_step_additional'              : 'Dodatkowe',
  'detail_step_references'              : 'Referencje',
  'detail_step_customize'               : 'Dostosuj',
  'detail_banner_heading'               : 'Prawie gotowe!',
  'detail_banner_btn'                   : 'Kontynuuj',
  'detail_banner_completion_label'      : 'Ukończenie',
  'detail_stat_created_label'           : 'Utworzono',
  'detail_stat_steps_label'             : 'Wykonane kroki',
  'detail_section_template_style'       : 'Styl szablonu',
  'detail_section_steps'                : 'Kroki',
  'detail_steps_counter'                : '{done} z {total} ukończone',
  'detail_step_sub'                     : 'Krok {n} z {total}',
  'detail_section_activity'             : 'Aktywność',
  'detail_activity_created'             : 'Utworzono',
  'detail_activity_last_edited'         : 'Ostatnio edytowano',
  'detail_activity_template'            : 'Szablon',
  'detail_btn_continue_editing'         : 'Kontynuuj edycję',
  'detail_btn_edit_cv'                  : 'Edytuj CV',
  'detail_option_rename'                : 'Zmień nazwę CV',
  'detail_option_delete'                : 'Usuń CV',
  'detail_rename_title'                 : 'Zmień nazwę CV',
  'detail_rename_hint'                  : 'np. CV Inżynier oprogramowania',
  'detail_rename_error_empty'           : 'Nazwa nie może być pusta',
  'detail_rename_btn_cancel'            : 'Anuluj',
  'detail_rename_btn_save'              : 'Zapisz',
  'detail_rename_snackbar'              : 'Zmieniono nazwę na "{name}"',
  'detail_delete_title'                 : 'Usunąć CV?',
  'detail_delete_body'                  : 'Spowoduje to trwałe usunięcie "{name}". Tej czynności nie można cofnąć.',
  'detail_delete_btn_cancel'            : 'Anuluj',
  'detail_delete_btn_confirm'           : 'Usuń',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Ukończone',
  'detail_check_tile_incomplete'        : 'Jeszcze nie wypełnione',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Wybierz szablon',
  'chooser_subtitle'                    : 'Przesuń, aby przeglądać  ·  Stuknij, aby wybrać  ·  Przytrzymaj, aby podejrzeć',
  'chooser_card_hold_hint'              : 'Przytrzymaj, aby podejrzeć',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Wybrano',
  'chooser_modal_heading'               : 'Nadaj nazwę CV',
  'chooser_modal_sub'                   : 'Nadaj mu nazwę, aby łatwo je znaleźć w Moich CV i historii.',
  'chooser_modal_field_label'           : 'Nazwa CV',
  'chooser_modal_save_btn'              : 'Zapisz i zacznij tworzyć',
  'chooser_modal_divider'               : 'lub kontynuuj istniejące CV',
  'chooser_nav_selected_sub'            : 'Wybrany szablon',
  'chooser_nav_cta'                     : 'Zapisz i kontynuuj',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Osiągnięto maksymalną liczbę wpisów',
  'editor_show_hide'                    : 'Pokaż/ukryj',
  'editor_editing_badge'                : 'Edycja',
  'editor_field_required'               : 'Wymagane',
  'editor_tooltip_edit'                 : 'Edytuj',
  'editor_tooltip_delete'               : 'Usuń',
  'editor_date_start'                   : 'Data początkowa *',
  'editor_date_end'                     : 'Data końcowa *',
  'editor_date_tap_hint'                : 'Stuknij, aby wybrać',
  'editor_date_dialog_title'            : 'Wybierz miesiąc i rok',
  'editor_date_confirm'                 : 'Potwierdź',
  'editor_panel_hide'                   : 'Ukryj',
  'editor_panel_show'                   : 'Pokaż',
  'editor_validator_max_chars'          : 'Maks. {n} znaków',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Twórz CV',
  'editor_header_step_sub'              : 'Krok {current} z {total} · {label}',
  'editor_step_template'                : 'Szablon',
  'editor_step_personal'                : 'Dane osobowe',
  'editor_step_experience'              : 'Doświadczenie',
  'editor_step_education'               : 'Edukacja',
  'editor_step_skills'                  : 'Umiejętności',
  'editor_step_additional'              : 'Dodatkowe',
  'editor_step_references'              : 'Referencje',
  'editor_step_customize'               : 'Dostosuj',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Dostosuj',
  'customize_subtitle'                  : 'Spraw, by Twoje CV było wyjątkowe',
  'customize_smart_layout_btn'          : 'Inteligentny układ',
  'customize_back_to_top'               : 'Powrót na górę',
  'customize_done_title'                : 'Wszystko gotowe!',
  'customize_done_sub'                  : 'Stuknij Podgląd CV poniżej, aby zobaczyć gotowe CV',
  'customize_preview_btn'               : 'Podgląd CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Schemat kolorów',
  'color_black'                         : 'Czarny',
  'color_blue'                          : 'Niebieski',
  'color_nordic_blue'                   : 'Nordycki niebieski',
  'color_indigo'                        : 'Indygo',
  'color_teal'                          : 'Morski',
  'color_green'                         : 'Zielony',
  'color_purple'                        : 'Fioletowy',
  'color_orange'                        : 'Pomarańczowy',
  'color_red'                           : 'Czerwony',
  'color_executive_gold'                : 'Złoto executive',
  'color_vibrant_coral'                 : 'Koral vibrant',
  'color_white'                         : 'Biały',
  'color_white_bg'                      : 'Białe tło',
  'color_maroon'                        : 'Bordowy',
  'color_brutalist_yellow'              : 'Żółty brutalistyczny',
  'color_neon_blue'                     : 'Niebieski neon',
  'color_blueprint_navy'                : 'Granatowy blueprint',
  'color_light_grey'                    : 'Jasnoszary',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Rodzina czcionek',
  'customize_font_picker_title'         : 'Wybierz czcionkę',
  'customize_font_picker_sub'           : 'Każda czcionka jest wyświetlana we własnym kroju',
  'customize_font_preview_sample'       : 'Zażółć gęślą jaźń',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Rozmiar czcionki',
  'customize_font_size_label'           : 'Rozmiar tekstu',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Rozmiar obrazu',
  'customize_image_size_label'          : 'Rozmiar obrazu',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Podgląd na żywo',
  'preview_page_count_singular'         : '1 strona',
  'preview_page_count_plural'           : '{n} strony',
  'preview_page_of'                     : 'Strona {page} z {total}',
  'preview_live_hint'                   : 'Zmiany są stosowane natychmiast',
  'preview_template_unregistered'       : 'Nie zarejestrowano jeszcze w customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Przygotowywanie CV…',
  'preview_bar_print'                   : 'Drukuj',
  'preview_bar_save_pdf'                : 'Zapisz jako PDF',
  'preview_bar_share'                   : 'Udostępnij',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Podgląd CV',
  'preview_screen_sub'                  : '{n} {unit} · dokładnie jak wydrukowane',
  'preview_page_singular'               : 'strona',
  'preview_page_plural'                 : 'strony',
  'preview_pdf_filename'                : 'Moje_CV',
  'preview_share_subject'               : 'Moje CV',
  'preview_snack_print_failed'          : 'Drukowanie nie powiodło się: {e}',
  'preview_snack_saved'                 : 'CV zapisano w Pobrane ✓',
  'preview_snack_export_failed'         : 'Eksport nie powiódł się: {e}',
  'preview_snack_share_failed'          : 'Udostępnianie nie powiodło się: {e}',
  'preview_template_not_registered'     : 'Szablon nie jest zarejestrowany',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Zamknij podgląd',
  'preview_modal_hint_photo'            : 'Obsługuje zdjęcie profilowe  ·  Stuknij kartę, aby wybrać',
  'preview_modal_hint_no_photo'         : 'Stuknij kartę szablonu, aby ją wybrać',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Moje CV',
  'time_just_now'                       : 'Przed chwilą',
  'time_minutes_ago'                    : '{n} min temu',
  'time_hours_ago'                      : '{n} godz. temu',
  'time_yesterday'                      : 'Wczoraj',
  'time_days_ago'                       : '{n} dni temu',
  'time_one_week_ago'                   : '1 tydzień temu',
  'time_weeks_ago'                      : '{n} tygodnie temu',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegancki',
  'tpl_tag_classic'                     : 'Klasyczny',
  'tpl_tag_minimal'                     : 'Minimalny',
  'tpl_tag_creative'                    : 'Kreatywny',
  'tpl_tag_bold'                        : 'Wyrazisty',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Karty z gradientem od morskiego do fioletowego',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Styl magazynowy w czerwieni i kremie',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'Lawendowy pasek boczny, miękkie karty',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Surowa siatka, grube ramki i żółty',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'Leśna zieleń z osią czasu',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'Ciemne tło z okrągłymi wykresami',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Geometryczny złoty luksus lat 20.',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'Ciemna infografika z kołami',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'Ciemny pasek boczny z pomarańczowym akcentem',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'Czysty minimalny, miękkie odcienie szarości',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Ciepłe beżowe eleganckie tony',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Wyrazisty czarno-biały klasyk',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klasyczny układ przyjazny ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'Ciemny pomarańczowy styl infograficzny',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'Rysunek techniczny na siatce',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'Klasyczny dwukolumnowy układ z etykietami',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Zacienione nagłówki z rombowymi znacznikami',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Wyśrodkowane nagłówki, wyróżnione firmy',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Wyraziste imię, punkty osi czasu i osiągnięcia',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Dane osobowe',
  'personal_subtitle'                   : 'Przedstaw się pracodawcom',
  'personal_profile_counter'            : '{n}/{max} profili',
  'personal_info_banner'                : 'Zapisz do 5 profili i wybierz jeden dla każdego CV. Wybór jest zapamiętywany dla każdego CV osobno.',
  'personal_snack_max'                  : 'Osiągnięto maksymalną liczbę {n} profili.',
  'personal_add_btn'                    : 'Dodaj nowy profil',
  'personal_library_title'              : 'Zapisane profile',
  'personal_selected_one'               : '1 wybrany',
  'personal_selected_none'              : 'brak wybranego',
  'personal_library_hint'               : 'Stuknij kartę, aby wybrać ją tylko dla tego CV. Inne CV zachowują własne niezależne wybory.',
  'personal_empty_message'              : 'Brak zapisanych profili',
  'personal_empty_sub'                  : 'Stuknij powyżej, aby dodać dane osobowe',
  'personal_nav_next'                   : 'Zapisz i kontynuuj',
  'personal_card_active_badge'          : 'Aktywny dla tego CV',
  'personal_sheet_title_add'            : 'Nowy profil',
  'personal_sheet_title_edit'           : 'Edytuj profil',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Szablon Brutalist ma zwarte pola kontaktowe. Krótsze wartości (np. samo miasto) wyglądają najlepiej.',
  'personal_section_photo'              : 'Zdjęcie profilowe',
  'personal_section_basic'              : 'Podstawowe dane',
  'personal_section_contact'            : 'Kontakt',
  'personal_section_online'             : 'Obecność w sieci',
  'personal_section_summary'            : 'Podsumowanie zawodowe',
  'personal_field_first_name'           : 'Imię *',
  'personal_field_last_name'            : 'Nazwisko',
  'personal_field_job_title'            : 'Stanowisko *',
  'personal_field_email'                : 'Adres e-mail *',
  'personal_field_phone'                : 'Numer telefonu *',
  'personal_field_location'             : 'Lokalizacja',
  'personal_field_location_brut'        : 'Lokalizacja (tylko miasto)',
  'personal_field_website'              : 'Strona / Portfolio',
  'personal_field_linkedin'             : 'Adres LinkedIn',
  'personal_hint_first_name'            : 'np. Anna',
  'personal_hint_last_name'             : 'np. Kowalska',
  'personal_hint_job_title'             : 'np. Starszy inżynier',
  'personal_hint_email'                 : 'np. anna@przyklad.pl',
  'personal_hint_phone'                 : 'np. +48 123 456 789',
  'personal_hint_location'              : 'np. Warszawa, Polska',
  'personal_hint_location_brut'         : 'np. Warszawa',
  'personal_hint_website'               : 'np. github.com/annakowalska',
  'personal_hint_website_brut'          : 'np. github.com/anna',
  'personal_hint_linkedin'              : 'np. linkedin.com/in/annakowalska',
  'personal_hint_linkedin_brut'         : 'np. linkedin.com/in/anna',
  'personal_summary_hint_label'         : 'Zachowaj zwięzłość — pojawi się na górze CV.',
  'personal_hint_summary'               : 'Krótkie podsumowanie 2–3 zdań dotyczące Twojego doświadczenia i celów...',
  'personal_validator_email'            : 'Podaj prawidłowy adres e-mail',
  'personal_field_char_limit_tooltip'   : 'Osiągnięto limit znaków',
  'personal_sheet_btn_save'             : 'Zapisz profil',
  'personal_sheet_btn_update'           : 'Zapisz zmiany',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Wybierz zdjęcie',
  'photo_option_gallery'                : 'Wybierz z galerii',
  'photo_option_camera'                 : 'Zrób zdjęcie',
  'photo_option_reposition'             : 'Zmień położenie zdjęcia',
  'photo_option_remove'                 : 'Usuń zdjęcie',
  'photo_status_added'                  : 'Zdjęcie dodane ✓',
  'photo_status_empty'                  : 'Dodaj profesjonalne zdjęcie profilowe',
  'photo_chip_gallery'                  : 'Galeria',
  'photo_chip_camera'                   : 'Aparat',
  'photo_chip_reposition'               : 'Zmień położenie',
  'photo_reposition_title'              : 'Zmień położenie zdjęcia',
  'photo_reposition_sub'                : 'Przeciągnij zdjęcie, aby dostosować jego położenie',
  'photo_reposition_reset'              : 'Wyśrodkuj',
  'photo_reposition_apply'              : 'Zastosuj',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Umiejętności',
  'skills_subtitle'                     : 'Zaakcentuj swoje kluczowe kompetencje',
  'skills_add_btn'                      : 'Dodaj nową umiejętność',
  'skills_snack_max_icons'              : 'Wybrano maksymalnie 10 ikon.',
  'skills_snack_max_skills'             : 'Osiągnięto maksymalnie 15 umiejętności.',
  'skills_library_title'                : 'Zapisane umiejętności',
  'skills_library_hint'                 : 'Zaznaczone umiejętności są uwzględnione w tym CV. Wybory są zapisywane automatycznie.',
  'skills_nav_next'                     : 'Kontynuuj do Dodatkowych',
  'skills_wina_header_icon_bar'         : 'Pasek ikon nagłówka',
  'skills_wina_on'                      : 'WŁ.',
  'skills_wina_off'                     : 'WYŁ.',
  'skills_wina_bar_on_sub'              : 'Kolorowe kółka ikon wyświetlane w nagłówku CV.',
  'skills_wina_bar_off_sub'             : 'Rząd ikon ukryty — więcej miejsca na dane kontaktowe.',
  'skills_wina_palette_hint'            : 'Ikony pojawiają się jako kolorowe kółka w kolejności palety.',
  'skills_wina_preview_label'           : 'Podgląd',
  'skills_wina_disabled_hint'           : 'Włącz pasek ikon powyżej, aby wybrać, które ikony pojawią się w nagłówku CV.',
  'skills_sheet_title_add'              : 'Dodaj umiejętność',
  'skills_sheet_title_edit'             : 'Edytuj umiejętność',
  'skills_sheet_field_name'             : 'Nazwa umiejętności *',
  'skills_sheet_hint_short'             : 'np. Flutter, Design',
  'skills_sheet_hint_long'              : 'np. Flutter, Zarządzanie projektami',
  'skills_sheet_validator_max'          : 'Maks. {n} znaków',
  'skills_sheet_proficiency'            : 'Poziom zaawansowania',
  'skills_sheet_beginner'               : 'Początkujący',
  'skills_sheet_expert'                 : 'Ekspert',
  'skills_sheet_btn_save'               : 'Zapisz umiejętność',
  'skills_sheet_btn_update'             : 'Zaktualizuj umiejętność',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referencje osobiste',
  'refs_subtitle'                       : 'Osoby, które mogą Cię polecić',
  'refs_add_btn'                        : 'Dodaj nową referencję osobistą',
  'refs_snack_max_selected'             : 'Dla CV można wybrać maksymalnie 4 referencje.',
  'refs_snack_max_saved'                : 'Osiągnięto maksymalnie 10 zapisanych referencji.',
  'refs_library_title'                  : 'Zapisane referencje',
  'refs_library_hint'                   : 'Zaznaczone referencje są uwzględnione w tym CV. Maks. 4 na CV. Wybory są zapisywane automatycznie.',
  'refs_nav_next'                       : 'Kontynuuj do Dostosuj',
  'refs_sheet_title_add'                : 'Dodaj referencję osobistą',
  'refs_sheet_title_edit'               : 'Edytuj referencję osobistą',
  'refs_sheet_sub_add'                  : 'Osoba, która może Cię osobiście polecić pracodawcom.',
  'refs_sheet_sub_edit'                 : 'Zaktualizuj dane tej referencji poniżej.',
  'refs_sheet_field_name'               : 'Imię i nazwisko *',
  'refs_sheet_field_title'              : 'Stanowisko *',
  'refs_sheet_field_company'            : 'Firma (opcjonalnie)',
  'refs_sheet_field_email'              : 'Adres e-mail *',
  'refs_sheet_field_phone'              : 'Numer telefonu *',
  'refs_sheet_hint_name'                : 'np. Jan Kowalski',
  'refs_sheet_hint_title'               : 'np. Menedżer ds. inżynierii',
  'refs_sheet_hint_company'             : 'np. Acme Sp. z o.o.',
  'refs_sheet_hint_email'               : 'np. jan@acme.pl',
  'refs_sheet_hint_phone'               : 'np. +48 123 456 789',
  'refs_sheet_validator_email'          : 'Podaj prawidłowy adres e-mail',
  'refs_sheet_btn_save'                 : 'Zapisz referencję osobistą',
  'refs_sheet_btn_update'               : 'Zaktualizuj referencję osobistą',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Doświadczenie zawodowe',
  'exp_subtitle'                        : 'Dodaj historię zatrudnienia',
  'exp_banner_info'                     : 'Do {n} obowiązków na stanowisko pojawi się w CV. 3–6 stanowisk zazwyczaj mieści się na 1–2 stronach.',
  'exp_add_btn'                         : 'Dodaj nowe doświadczenie',
  'exp_snack_max_selected'              : 'Dla CV można wybrać maksymalnie 8 doświadczeń.',
  'exp_snack_max_saved'                 : 'Osiągnięto maksymalnie 12 zapisanych doświadczeń.',
  'exp_library_title'                   : 'Zapisane doświadczenia',
  'exp_library_hint'                    : 'Zaznaczone wpisy są uwzględnione tylko w tym CV. Inne CV zachowują własne niezależne wybory.',
  'exp_nav_next'                        : 'Kontynuuj do Edukacji',
  'exp_empty_message'                   : 'Nie dodano jeszcze doświadczenia',
  'exp_empty_sub'                       : 'Stuknij powyżej, aby dodać pierwszą rolę',
  'exp_card_resp_singular'              : 'obowiązek',
  'exp_card_resp_plural'                : 'obowiązki',
  'exp_card_resp_tooltip'               : 'W CV pojawi się tylko pierwszych 8 obowiązków',
  'exp_sheet_title_add'                 : 'Dodaj doświadczenie',
  'exp_sheet_title_edit'                : 'Edytuj doświadczenie',
  'exp_sheet_field_job_title'           : 'Stanowisko *',
  'exp_sheet_field_company'             : 'Firma *',
  'exp_sheet_field_location'            : 'Lokalizacja',
  'exp_sheet_section_responsibilities'  : 'Kluczowe obowiązki',
  'exp_sheet_resp_hint_info'            : 'Maks. 8 punktów · każdy do 200 znaków',
  'exp_sheet_resp_label'                : 'Obowiązek {n}',
  'exp_sheet_resp_hint'                 : 'np. Kierowałem/am zespołem 5 inżynierów',
  'exp_sheet_resp_add_btn'              : 'Dodaj obowiązek',
  'exp_sheet_resp_max_info'             : 'Osiągnięto maksymalnie {n} obowiązków',
  'exp_sheet_resp_validator_max'        : 'Maks. 200 znaków',
  'exp_sheet_hint_job_title'            : 'np. Starszy deweloper',
  'exp_sheet_hint_location'             : 'np. Warszawa, Polska',
  'exp_sheet_btn_save'                  : 'Zapisz doświadczenie',
  'exp_sheet_btn_update'                : 'Zapisz zmiany',
  'exp_date_present'                    : 'Obecnie / Aktualna rola',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Edukacja',
  'edu_subtitle'                        : 'Dodaj swoje wykształcenie',
  'edu_add_btn'                         : 'Dodaj nowe wykształcenie',
  'edu_snack_max_selected'              : 'Dla CV można wybrać maksymalnie 8 wpisów edukacyjnych.',
  'edu_snack_max_saved'                 : 'Osiągnięto maksymalnie 12 zapisanych wpisów edukacyjnych.',
  'edu_library_title'                   : 'Zapisane wykształcenie',
  'edu_library_hint'                    : 'Zaznaczone wpisy są uwzględnione w tym CV. Wybory są zapisywane automatycznie.',
  'edu_nav_next'                        : 'Kontynuuj do Umiejętności',
  'edu_empty_message'                   : 'Nie dodano jeszcze wykształcenia',
  'edu_empty_sub'                       : 'Stuknij powyżej, aby dodać kwalifikacje',
  'edu_card_bullet_singular'            : 'punkt',
  'edu_card_bullet_plural'              : 'punkty',
  'edu_sheet_title_add'                 : 'Dodaj wykształcenie',
  'edu_sheet_title_edit'                : 'Edytuj wykształcenie',
  'edu_sheet_field_degree'              : 'Stopień / Kwalifikacja *',
  'edu_sheet_field_institution'         : 'Uczelnia *',
  'edu_sheet_section_key_points'        : 'Kluczowe punkty',
  'edu_sheet_key_points_hint_info'      : 'Opcjonalnie · 1 punkt · maks. 100 znaków',
  'edu_sheet_point_label'               : 'Punkt {n}',
  'edu_sheet_point_add_btn'             : 'Dodaj punkt',
  'edu_sheet_point_max_info'            : 'Osiągnięto maksymalnie {n} punktów',
  'edu_sheet_point_validator_max'       : 'Maks. {n} znaków',
  'edu_sheet_hint_degree'               : 'np. Inżynier informatyki',
  'edu_sheet_hint_institution'          : 'np. Politechnika Warszawska',
  'edu_sheet_hint_bullet'               : 'np. Wyróżnienie z wynikiem bardzo dobrym',
  'edu_sheet_btn_save'                  : 'Zapisz wykształcenie',
  'edu_sheet_btn_update'                : 'Zapisz zmiany',
  'edu_date_present'                    : 'Obecnie / Trwające studia',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Dodatkowe informacje',
  'additional_subtitle'                 : 'Certyfikaty, języki i inne',
  'additional_cert_section_title'       : 'Certyfikaty',
  'additional_cert_counter'             : '{sel}/{total} wybranych · maks. {max}',
  'additional_cert_hide'                : 'Ukryj',
  'additional_cert_show'                : 'Pokaż',
  'additional_cert_add_btn'             : 'Dodaj',
  'additional_cert_snack_max'           : 'Osiągnięto maksymalnie {n} wpisów certyfikatów.',
  'additional_cert_hint'                : 'Zaznaczone wpisy są uwzględnione w tym CV. Wybory są zapisywane automatycznie.',
  'additional_cert_empty'               : 'Nie dodano jeszcze certyfikatów',
  'additional_lang_section_title'       : 'Języki',
  'additional_lang_add_hint'            : 'np. Angielski',
  'additional_lang_snack_max'           : 'Osiągnięto maksymalnie {n} wpisów językowych.',
  'additional_lang_empty'               : 'Nie dodano jeszcze języków',
  'additional_hobby_section_title'      : 'Hobby i zainteresowania',
  'additional_hobby_add_hint'           : 'np. Fotografia',
  'additional_hobby_snack_max'          : 'Osiągnięto maksymalnie {n} wpisów hobby.',
  'additional_hobby_empty'              : 'Nie dodano jeszcze hobby',
  'additional_section_hint'             : 'Zaznaczone wpisy są uwzględnione w tym CV. Wybory są zapisywane automatycznie.',
  'additional_nav_next'                 : 'Kontynuuj do Referencji',
  'cert_sheet_title_add'                : 'Dodaj certyfikat',
  'cert_sheet_title_edit'               : 'Edytuj certyfikat',
  'cert_sheet_sub'                      : 'Dodaj kwalifikację, certyfikat lub poświadczenie zawodowe.',
  'cert_sheet_field_name'               : 'Nazwa certyfikatu *',
  'cert_sheet_field_issued_by'          : 'Wydany przez (opcjonalnie)',
  'cert_sheet_field_short_desc'         : 'Krótki opis (opcjonalnie)',
  'cert_sheet_hint_name'                : 'np. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'np. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'np. Uzyskany w 2024 r.',
  'cert_sheet_btn_save'                 : 'Zapisz certyfikat',
  'cert_sheet_btn_update'               : 'Zaktualizuj certyfikat',
  'simple_sheet_title_add_language'     : 'Dodaj język',
  'simple_sheet_title_edit_language'    : 'Edytuj język',
  'simple_sheet_title_add_hobby'        : 'Dodaj hobby',
  'simple_sheet_title_edit_hobby'       : 'Edytuj hobby',
  'simple_sheet_btn_save'               : 'Zapisz',
  'simple_sheet_btn_update'             : 'Zaktualizuj',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Kontakt',
  'pdf_section_about_me'                : 'O mnie',
  'pdf_section_summary'                 : 'Podsumowanie',
  'pdf_section_summary_short'           : 'Podsumowanie',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Doświadczenie',
  'pdf_section_experience_short'        : 'Doświadczenie',
  'pdf_section_education'               : 'Edukacja',
  'pdf_section_skills'                  : 'Umiejętności',
  'pdf_section_languages'               : 'Języki',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Lokalizacja',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Osiągnięto limit CV',
  'limit_dialog_body'                   : 'Osiągnięto maksymalną liczbę 30 CV. Usuń istniejące CV przed utworzeniem nowego.',
  'limit_dialog_go_to_my_cvs'           : 'Przejdź do Moich CV',
  'limit_dialog_cancel'                 : 'Anuluj',
  'refs_count_summary'                  : '{checked}/{maxChecked} zaznaczonych · {saved}/{maxSaved} zapisanych',
  'refs_selected_badge'                 : '{n} zaznaczono',
  'refs_empty_message'                  : 'Brak zapisanych referencji',
  'refs_empty_sub'                      : 'Dotknij powyżej, aby dodać osobistą referencję',
};