// lib/language_keys/lang_ro_romanian.dart
//
// Romanian (Romania) translation map.
// Keys mirror lang_en_english.dart exactly.

const Map<String, String> roRomanian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nicio limbă găsită',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Sari peste',
  'onboarding_next'                     : 'Următorul',
  'onboarding_get_started'              : 'Începe',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Bun venit',
  'ob1_title'                           : 'Creează un CV care\nDeschide Uși',
  'ob1_body'                            : 'Ieși în evidență dintre sute de candidați. Construiește un CV îngrijit, câștigător în minute — fără abilități de design.',
  'ob1_pill_label'                      : 'Constructor profesional de CV',
  'ob1_chip_templates'                  : '24+ Șabloane',
  'ob1_chip_pdf'                        : 'Export PDF',
  'ob1_chip_free'                       : 'Gratuit',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Șabloane',
  'ob2_title'                           : 'Orice Industrie.\nOrice Ambiție.',
  'ob2_body'                            : 'De la machete pentru sala de consiliu până la design-uri creative îndrăznețe — un șablon care îți spune povestea.',
  'ob2_tap_hint'                        : 'Atinge orice șablon pentru previzualizare',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Întunecat',
  'ob2_tpl_luxury'                      : 'Lux',
  'ob2_tag_corporate'                   : 'Corporativ',
  'ob2_tag_creative'                    : 'Creativ',
  'ob2_tag_minimal'                     : 'Minimal',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Premium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Aspect inteligent',
  'ob3_title'                           : 'CV-ul tău.\nPerfect Aranjat.',
  'ob3_body'                            : 'Aspectul inteligent reordonează secțiunile pentru impact maxim — punând cel mai bun conținut acolo unde recrutorii privesc primul.',
  'ob3_badge_smart_layout'              : 'Aspect inteligent',
  'ob3_badge_cv_ready'                  : 'CV gata!',
  'ob3_step1_label'                     : 'Alege un Șablon',
  'ob3_step1_desc'                      : 'Alege din 24+ design-uri uimitoare.',
  'ob3_step2_label'                     : 'Completează detaliile',
  'ob3_step2_desc'                      : 'Câmpuri ghidate pentru toate secțiunile.',
  'ob3_step3_label'                     : 'Aspect inteligent',
  'ob3_step3_desc'                      : 'O singură atingere reface CV-ul perfect.',
  'ob3_step4_label'                     : 'Exportează ca PDF',
  'ob3_step4_desc'                      : 'PDF pixel-perfect gata de trimis.',
  'ob3_section_work'                    : 'Experiență profesională',
  'ob3_section_education'               : 'Educație',
  'ob3_section_skills'                  : 'Competențe',
  'ob3_section_references'              : 'Referințe',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Gata de Început',
  'ob4_title'                           : 'De ce Candidații de Top\nAleg CV Builder',
  'ob4_visual_headline'                 : 'Ești pregătit!',
  'ob4_visual_subline'                  : 'Tot ce ai nevoie pentru a obține jobul.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Șabloane',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'              : 'Max CV-uri',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Export',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privat',
  'ob4_hl1_title'                       : 'Privat și sigur',
  'ob4_hl1_sub'                         : 'Datele rămân pe dispozitivul tău.',
  'ob4_hl2_title'                       : 'Salvare automată',
  'ob4_hl2_sub'                         : 'Fiecare tastă salvată instant.',
  'ob4_hl3_title'                       : 'Până la 30 CV-uri',
  'ob4_hl3_sub'                         : 'CV unic pentru fiecare rol.',
  'ob4_hl4_title'                       : 'Partajare cu o atingere',
  'ob4_hl4_sub'                         : 'Trimite PDF fără să părăsești aplicația.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Ieși în evidență din mulțime',
  'home_hero_title'                     : 'Creează-ți\nCV-ul Profesional',
  'home_hero_sub'                       : 'Construiește un CV impresionant\nîn minute',
  'home_hero_cta'                       : 'Începe să construiești',
  'home_premium_soon'                   : 'Upgrade la Pro vine în curând!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Cele mai recente',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Ultima editare',
  'history_sort_by_template'            : 'După șablon',
  'history_sort_sheet_title'            : 'Sortează după',
  'history_sort_alphabetical_full'      : 'Alfabetic (A–Z)',
  'history_premium_soon'                : 'Upgrade la Pro vine în curând!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Setări',
  'settings_section_preferences'        : 'Preferințe',
  'settings_section_support'            : 'Asistență',
  'settings_section_legal'              : 'Legal',
  'settings_section_about'              : 'Despre',
  'settings_language_tile_title'        : 'Limbă',
  'settings_dark_mode_title'            : 'Mod Întunecat',
  'settings_dark_mode_on'               : 'Temă întunecată activată',
  'settings_dark_mode_off'              : 'Temă luminoasă activată',
  'settings_help_faq_title'             : 'Ajutor și FAQ',
  'settings_help_faq_sub'               : 'Întrebări frecvente cu răspunsuri',
  'settings_contact_support_title'      : 'Contactează asistența',
  'settings_rate_app_title'             : 'Evaluează aplicația',
  'settings_rate_app_sub'               : 'Îți place aplicația? Lasă o recenzie!',
  'settings_privacy_policy_title'       : 'Politica de confidențialitate',
  'settings_terms_title'                : 'Termeni și condiții',
  'settings_app_version_title'          : 'Versiunea aplicației',
  'settings_email_error'                : 'Nu s-a putut deschide aplicația de e-mail. Trimite un e-mail la cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Previzualizare CV',
  'preview_header_sub'                  : 'Gata de exportat',
  'preview_generating'                  : 'Se generează CV-ul tău...',
  'preview_failed_title'                : 'Previzualizare eșuată',
  'preview_failed_error'                : 'Eroare: {error}',
  'preview_go_back'                     : 'Înapoi',
  'preview_no_data'                     : 'Nu există date disponibile',
  'preview_btn_print'                   : 'Tipărește',
  'preview_btn_download'                : 'Descarcă și partajează',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Ajutor și FAQ',
  'faq_category_all'                    : 'Toate',
  'faq_empty'                           : 'Niciun rezultat găsit',
  'faq_contact_headline'                : 'Mai ai nevoie de ajutor?',
  'faq_contact_sub'                     : 'Echipa noastră este aici pentru tine.',
  'faq_contact_btn'                     : 'Contact',
  'faq_email_error'                     : 'Nu s-a putut deschide aplicația de e-mail. Trimite un e-mail la cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'Primii pași',
  'faq_cat_templates'                   : 'Șabloane',
  'faq_cat_editing'                     : 'Editare',
  'faq_cat_exporting'                   : 'Export',
  'faq_cat_data_privacy'                : 'Date și confidențialitate',
  'faq_cat_troubleshooting'             : 'Depanare',
  'faq_q1'  : 'Cum îmi creez primul CV?',
  'faq_a1'  : 'Atinge butonul „+" de pe ecranul principal pentru a începe un CV nou. Alege un șablon care se potrivește stilului tău, apoi completează pas cu pas datele personale, experiența profesională, educația și competențele. Progresul se salvează automat.',
  'faq_q2'  : 'Pot crea mai mult de un CV?',
  'faq_a2'  : 'Da! Poți crea mai multe CV-uri pentru roluri sau industrii diferite. Fiecare CV este salvat separat, astfel încât să le poți personaliza pentru aplicații specifice.',
  'faq_q3'  : 'Cum îmi schimb șablonul de CV?',
  'faq_a3'  : 'Deschide CV-ul, atinge pictograma șablon din partea de sus a ecranului și navighează prin șabloanele disponibile. Atinge orice șablon pentru a-l previzualiza cu conținutul tău existent. Confirmă pentru a-l aplica.',
  'faq_q4'  : 'Există șabloane gratuite și premium?',
  'faq_a4'  : 'Da. O selecție de șabloane profesionale este disponibilă gratuit. Șabloanele premium cu design-uri avansate și palete de culori sunt disponibile printr-o achiziție unică sau abonament.',
  'faq_q5'  : 'Cum adaug sau elimin secțiuni?',
  'faq_a5'  : 'În editorul de CV, derulează la baza ecranului și atinge „Adaugă secțiune" pentru a include extra-uri precum Limbi, Certificări sau Voluntariat. Pentru a elimina o secțiune, atinge antetul secțiunii și selectează „Elimină".',
  'faq_q6'  : 'Cum reordonez secțiunile?',
  'faq_a6'  : 'Ține apăsat mânerul de glisare (≡) de lângă orice antet de secțiune și trage-l în poziția dorită. Modificările se salvează automat.',
  'faq_q7'  : 'Cum export CV-ul meu ca PDF?',
  'faq_a7'  : 'Deschide CV-ul și atinge butonul de export (pictograma partajare) din colțul din dreapta sus. Selectează „Exportează ca PDF". Îl poți salva pe dispozitiv, partaja prin e-mail, WhatsApp sau îl poți încărca direct pe site-urile de joburi.',
  'faq_q8'  : 'Ce formate de fișiere sunt acceptate?',
  'faq_a8'  : 'În prezent aplicația acceptă exportul CV-ului ca PDF de înaltă calitate. Formate suplimentare pot fi adăugate în actualizările viitoare.',
  'faq_q9'  : 'Unde sunt stocate datele CV-ului meu?',
  'faq_a9'  : 'Toate datele CV-ului tău sunt stocate local pe dispozitivul tău. Nu încărcăm informațiile tale personale pe serverele noastre. Aceasta înseamnă că datele tale rămân private și accesibile offline.',
  'faq_q10' : 'Cum fac o copie de rezervă a CV-urilor mele?',
  'faq_a10' : 'CV-urile tale sunt incluse în copia de rezervă standard a dispozitivului (Google Drive pe Android, iCloud pe iOS) dacă ai activată copia de rezervă în setările dispozitivului. Poți exporta și CV-uri individuale ca PDF pentru a păstra o copie.',
  'faq_q11' : 'Aplicația funcționează lent. Ce ar trebui să fac?',
  'faq_a11' : 'Încearcă să închizi și să redeschizi aplicația. Dacă problema persistă, repornește dispozitivul. Asigură-te că ai instalată cea mai recentă versiune a aplicației din Play Store / App Store.',
  'faq_q12' : 'CV-ul meu nu se exportează corect. Ce ar trebui să fac?',
  'faq_a12' : 'Asigură-te că ai suficient spațiu de stocare pe dispozitiv. Încearcă să reduci imaginile mari din CV-ul tău. Dacă problema continuă, contactează echipa noastră de asistență.',
  'faq_q13' : 'Am uitat să salvez — am pierdut munca?',
  'faq_a13' : 'Deloc! Aplicația îți salvează progresul continuu pe măsură ce editezi.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Cariera ta, perfecționată',
  'header_tooltip_back'                 : 'Înapoi',
  'header_tooltip_my_cvs'               : 'CV-urile mele',
  'header_tooltip_settings'             : 'Setări',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV-urile mele',
  'saved_count_single'                  : '{n} document',
  'saved_count_plural'                  : '{n} documente',
  'saved_limit_reached'                 : 'Limită atinsă',
  'saved_footer_count'                  : '{n} / 30 CV-uri',
  'saved_filter_all'                    : 'Toate',
  'saved_filter_draft'                  : 'Ciornă',
  'saved_filter_complete'               : 'Complet',
  'saved_status_complete'               : 'Complet',
  'saved_status_saved'                  : 'Salvat',
  'saved_status_draft'                  : 'Ciornă',
  'saved_empty_title'                   : 'Niciun CV încă',
  'saved_empty_sub'                     : 'Începe să construiești primul tău CV mai sus',
  'saved_search_empty_title'            : 'Niciun rezultat găsit',
  'saved_search_empty_sub'              : 'Încearcă un alt termen de căutare',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Schemă de culori',
  'custom_font_settings_title'          : 'Setări font',
  'custom_font_family_label'            : 'Familie font',
  'custom_font_size_label'              : 'Dimensiune font: ',
  'custom_current_template_title'       : 'Șablon curent',
  'custom_change_template_btn'          : 'Schimbă șablonul',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Clasic',
  'custom_tpl_professional'             : 'Profesional',
  'custom_tpl_creative'                 : 'Creativ',
  'custom_tpl_minimal'                  : 'Minimal',
  'custom_tpl_modern_desc'              : 'Design curat și contemporan',
  'custom_tpl_classic_desc'             : 'Machetă profesională tradițională',
  'custom_tpl_professional_desc'        : 'Șablon orientat spre afaceri',
  'custom_tpl_creative_desc'            : 'Ieși în evidență cu un design unic',
  'custom_tpl_minimal_desc'             : 'Stil simplu și elegant',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Alege Șablonul',
  'swipe_photo_badge'                   : 'Fotografie',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Întunecat',
  'tpl_luxury_name'                     : 'Lux',
  'tpl_executive_tag'                   : 'Cel mai popular',
  'tpl_nordic_tag'                      : 'Curat',
  'tpl_vibrant_tag'                     : 'Creativ',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elit',
  'tpl_executive_desc'                  : 'Îndrăzneț și autoritar pentru roluri senior',
  'tpl_nordic_desc'                     : 'Claritate minimală, de încredere la firme de top',
  'tpl_vibrant_desc'                    : 'Ieși în evidență cu energie și culoare',
  'tpl_tech_dark_desc'                  : 'Estetic terminal pentru dezvoltatori',
  'tpl_luxury_desc'                     : 'Prestigiu cu accente aurii pe negru',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Șablon',
  'detail_step_personal'                : 'Personal',
  'detail_step_experience'              : 'Experiență',
  'detail_step_education'               : 'Educație',
  'detail_step_skills'                  : 'Competențe',
  'detail_step_additional'              : 'Suplimentar',
  'detail_step_references'              : 'Referințe',
  'detail_step_customize'               : 'Personalizare',
  'detail_banner_heading'               : 'Aproape gata!',
  'detail_banner_btn'                   : 'Continuă',
  'detail_banner_completion_label'      : 'Finalizare',
  'detail_stat_created_label'           : 'Creat',
  'detail_stat_steps_label'             : 'Pași finalizați',
  'detail_section_template_style'       : 'Stil șablon',
  'detail_section_steps'                : 'Pași',
  'detail_steps_counter'                : '{done} din {total} complete',
  'detail_step_sub'                     : 'Pasul {n} din {total}',
  'detail_section_activity'             : 'Activitate',
  'detail_activity_created'             : 'Creat',
  'detail_activity_last_edited'         : 'Ultima editare',
  'detail_activity_template'            : 'Șablon',
  'detail_btn_continue_editing'         : 'Continuă editarea',
  'detail_btn_edit_cv'                  : 'Editează CV-ul',
  'detail_option_rename'                : 'Redenumește CV-ul',
  'detail_option_delete'                : 'Șterge CV-ul',
  'detail_rename_title'                 : 'Redenumește CV-ul',
  'detail_rename_hint'                  : 'ex. CV Inginer Software',
  'detail_rename_error_empty'           : 'Numele nu poate fi gol',
  'detail_rename_btn_cancel'            : 'Anulează',
  'detail_rename_btn_save'              : 'Salvează',
  'detail_rename_snackbar'              : 'Redenumit în „{name}"',
  'detail_delete_title'                 : 'Ștergi CV-ul?',
  'detail_delete_body'                  : 'Aceasta va șterge permanent „{name}". Această acțiune nu poate fi anulată.',
  'detail_delete_btn_cancel'            : 'Anulează',
  'detail_delete_btn_confirm'           : 'Șterge',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Completat',
  'detail_check_tile_incomplete'        : 'Necompletat încă',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Alege șablonul tău',
  'chooser_subtitle'                    : 'Glisează pentru a naviga  ·  Atinge pentru a selecta  ·  Ține apăsat pentru previzualizare',
  'chooser_card_hold_hint'              : 'Ține apăsat pentru previzualizare',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Selectat',
  'chooser_modal_heading'               : 'Denumește CV-ul',
  'chooser_modal_sub'                   : 'Dă-i un nume pentru a-l găsi ușor în CV-urile mele și Istoric.',
  'chooser_modal_field_label'           : 'Nume CV',
  'chooser_modal_save_btn'              : 'Salvează și Începe',
  'chooser_modal_divider'               : 'sau continuă un CV existent',
  'chooser_nav_selected_sub'            : 'Șablon selectat',
  'chooser_nav_cta'                     : 'Salvează și continuă',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Număr maxim de intrări atins',
  'editor_show_hide'                    : 'Afișează/Ascunde',
  'editor_editing_badge'                : 'Editare',
  'editor_field_required'               : 'Obligatoriu',
  'editor_tooltip_edit'                 : 'Editează',
  'editor_tooltip_delete'               : 'Șterge',
  'editor_date_start'                   : 'Data de început *',
  'editor_date_end'                     : 'Data de sfârșit *',
  'editor_date_tap_hint'                : 'Atinge pentru a selecta',
  'editor_date_dialog_title'            : 'Selectează luna și anul',
  'editor_date_confirm'                 : 'Confirmă',
  'editor_panel_hide'                   : 'Ascunde',
  'editor_panel_show'                   : 'Afișează',
  'editor_validator_max_chars'          : 'Max {n} caractere',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Construiește CV-ul tău',
  'editor_header_step_sub'              : 'Pasul {current} din {total} · {label}',
  'editor_step_template'                : 'Șablon',
  'editor_step_personal'                : 'Personal',
  'editor_step_experience'              : 'Experiență',
  'editor_step_education'               : 'Educație',
  'editor_step_skills'                  : 'Competențe',
  'editor_step_additional'              : 'Suplimentar',
  'editor_step_references'              : 'Referințe',
  'editor_step_customize'               : 'Personalizare',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Personalizare',
  'customize_subtitle'                  : 'Fă-ți CV-ul unic al tău',
  'customize_smart_layout_btn'          : 'Aspect inteligent',
  'customize_back_to_top'               : 'Înapoi sus',
  'customize_done_title'                : 'Ești gata!',
  'customize_done_sub'                  : 'Atinge Previzualizare CV mai jos pentru a vedea CV-ul finalizat',
  'customize_preview_btn'               : 'Previzualizare CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Schemă de culori',
  'color_black'                         : 'Negru',
  'color_blue'                          : 'Albastru',
  'color_nordic_blue'                   : 'Albastru nordic',
  'color_indigo'                        : 'Indigo',
  'color_teal'                          : 'Turcoaz',
  'color_green'                         : 'Verde',
  'color_purple'                        : 'Violet',
  'color_orange'                        : 'Portocaliu',
  'color_red'                           : 'Roșu',
  'color_executive_gold'                : 'Auriu executive',
  'color_vibrant_coral'                 : 'Coral vibrant',
  'color_white'                         : 'Alb',
  'color_white_bg'                      : 'Fundal alb',
  'color_maroon'                        : 'Bordo',
  'color_brutalist_yellow'              : 'Galben brutalist',
  'color_neon_blue'                     : 'Albastru neon',
  'color_blueprint_navy'                : 'Bleumarin blueprint',
  'color_light_grey'                    : 'Gri deschis',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Familie font',
  'customize_font_picker_title'         : 'Alege fontul',
  'customize_font_picker_sub'           : 'Fiecare font este previzualizat în stilul său propriu',
  'customize_font_preview_sample'       : 'Vulpea rapidă maro',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Dimensiune font',
  'customize_font_size_label'           : 'Dimensiune text',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Dimensiune imagine',
  'customize_image_size_label'          : 'Dimensiune imagine',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Previzualizare live',
  'preview_page_count_singular'         : '1 pagină',
  'preview_page_count_plural'           : '{n} pagini',
  'preview_page_of'                     : 'Pagina {page} din {total}',
  'preview_live_hint'                   : 'Modificările se aplică instantaneu',
  'preview_template_unregistered'       : 'Neînregistrat încă în customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Se pregătește CV-ul tău…',
  'preview_bar_print'                   : 'Tipărește',
  'preview_bar_save_pdf'                : 'Salvează ca PDF',
  'preview_bar_share'                   : 'Partajează',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Previzualizare CV',
  'preview_screen_sub'                  : '{n} {unit} · exact ca la tipărire',
  'preview_page_singular'               : 'pagină',
  'preview_page_plural'                 : 'pagini',
  'preview_pdf_filename'                : 'CV_meu',
  'preview_share_subject'               : 'CV-ul meu',
  'preview_snack_print_failed'          : 'Tipărire eșuată: {e}',
  'preview_snack_saved'                 : 'CV salvat în Descărcări ✓',
  'preview_snack_export_failed'         : 'Export eșuat: {e}',
  'preview_snack_share_failed'          : 'Partajare eșuată: {e}',
  'preview_template_not_registered'     : 'Șablon neînregistrat',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Închide previzualizarea',
  'preview_modal_hint_photo'            : 'Acceptă fotografie de profil  ·  Atinge un card pentru a selecta',
  'preview_modal_hint_no_photo'         : 'Atinge un card de șablon pentru a-l selecta',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV-ul meu',
  'time_just_now'                       : 'Chiar acum',
  'time_minutes_ago'                    : 'acum {n} min',
  'time_hours_ago'                      : 'acum {n} ore',
  'time_yesterday'                      : 'Ieri',
  'time_days_ago'                       : 'acum {n} zile',
  'time_one_week_ago'                   : 'acum 1 săptămână',
  'time_weeks_ago'                      : 'acum {n} săptămâni',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegant',
  'tpl_tag_classic'                     : 'Clasic',
  'tpl_tag_minimal'                     : 'Minimal',
  'tpl_tag_creative'                    : 'Creativ',
  'tpl_tag_bold'                        : 'Îndrăzneț',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'Carduri cu gradient de la turcoaz la violet',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'Stil de revistă în roșu și crem',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pastel Moale',
  'tpl_pastel_soft_desc'                : 'Bară laterală lavandă, carduri moi',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'Grilă brută, borduri îndrăznețe și galben',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smarald',
  'tpl_emerald_desc'                    : 'Verde pădure cu cronologie',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografic',
  'tpl_infographic_desc'                : 'Canvas întunecat cu diagrame inelare',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'Lux geometric auriu din anii \'20',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina Întunecat',
  'tpl_wina_dark_desc'                  : 'Infografic întunecat cu inele',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio Portocaliu',
  'tpl_rio_orange_desc'                 : 'Bară laterală întunecată cu accent portocaliu',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Vară',
  'tpl_summer_desc'                     : 'Minimal curat, tonuri gri moi',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Tonuri elegante bej calde',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Clasic stark în alb și negru',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Machetă clasică compatibilă ATS',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony Întunecat',
  'tpl_tony_dark_desc'                  : 'Stil infografic portocaliu întunecat',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Modă',
  'tpl_fashion_desc'                    : 'Desen tehnic pe grilă',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Arhivist',
  'tpl_archivist_desc'                  : 'Machetă clasică cu etichete pe două coloane',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'Anteturi umbrite cu marcatori diamant',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'Anteturi centrate, companii cu accent',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'Nume îndrăzneț, puncte cronologie și realizări',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Informații personale',
  'personal_subtitle'                   : 'Spune angajatorilor cine ești',
  'personal_profile_counter'            : '{n}/{max} profiluri',
  'personal_info_banner'                : 'Salvează până la 5 profiluri și selectează unul per CV. Selecția ta este reținută pentru fiecare CV separat.',
  'personal_snack_max'                  : 'Numărul maxim de {n} profiluri a fost atins.',
  'personal_add_btn'                    : 'Adaugă profil nou',
  'personal_library_title'              : 'Profiluri salvate',
  'personal_selected_one'               : '1 selectat',
  'personal_selected_none'              : 'niciunul selectat',
  'personal_library_hint'               : 'Atinge un card pentru a-l selecta doar pentru acest CV. Alte CV-uri își păstrează propriile selecții independente.',
  'personal_empty_message'              : 'Niciun profil salvat încă',
  'personal_empty_sub'                  : 'Atinge mai sus pentru a adăuga informațiile personale',
  'personal_nav_next'                   : 'Salvează și continuă',
  'personal_card_active_badge'          : 'Activ pentru acest CV',
  'personal_sheet_title_add'            : 'Profil nou',
  'personal_sheet_title_edit'           : 'Editează profilul',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'Șablonul brutalist are câmpuri de contact compacte. Valorile mai scurte (ex. doar orașul) sunt afișate cel mai bine.',
  'personal_section_photo'              : 'Fotografie de profil',
  'personal_section_basic'              : 'Detalii de bază',
  'personal_section_contact'            : 'Contact',
  'personal_section_online'             : 'Prezență online',
  'personal_section_summary'            : 'Sumar profesional',
  'personal_field_first_name'           : 'Prenume *',
  'personal_field_last_name'            : 'Nume de familie',
  'personal_field_job_title'            : 'Titlu post *',
  'personal_field_email'                : 'Adresă e-mail *',
  'personal_field_phone'                : 'Număr de telefon *',
  'personal_field_location'             : 'Locație',
  'personal_field_location_brut'        : 'Locație (doar orașul)',
  'personal_field_website'              : 'Website / Portofoliu',
  'personal_field_linkedin'             : 'URL LinkedIn',
  'personal_hint_first_name'            : 'ex. Maria',
  'personal_hint_last_name'             : 'ex. Ionescu',
  'personal_hint_job_title'             : 'ex. Inginer Senior',
  'personal_hint_email'                 : 'ex. maria@exemplu.ro',
  'personal_hint_phone'                 : 'ex. +40 721 123 456',
  'personal_hint_location'              : 'ex. București, România',
  'personal_hint_location_brut'         : 'ex. București, RO',
  'personal_hint_website'               : 'ex. github.com/mariaionescu',
  'personal_hint_website_brut'          : 'ex. github.com/maria',
  'personal_hint_linkedin'              : 'ex. linkedin.com/in/mariaionescu',
  'personal_hint_linkedin_brut'         : 'ex. linkedin.com/in/maria',
  'personal_summary_hint_label'         : 'Fii concis — acesta apare în partea de sus a CV-ului tău.',
  'personal_hint_summary'               : 'Un scurt sumar de 2–3 propoziții despre experiența și obiectivele tale...',
  'personal_validator_email'            : 'Introduceți o adresă de e-mail validă',
  'personal_field_char_limit_tooltip'   : 'Limită de caractere atinsă',
  'personal_sheet_btn_save'             : 'Salvează profilul',
  'personal_sheet_btn_update'           : 'Salvează modificările',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Alege fotografia',
  'photo_option_gallery'                : 'Alege din galerie',
  'photo_option_camera'                 : 'Fă o fotografie',
  'photo_option_reposition'             : 'Repozitionează fotografia',
  'photo_option_remove'                 : 'Elimină fotografia',
  'photo_status_added'                  : 'Fotografie adăugată ✓',
  'photo_status_empty'                  : 'Adaugă o fotografie de profil profesională',
  'photo_chip_gallery'                  : 'Galerie',
  'photo_chip_camera'                   : 'Cameră',
  'photo_chip_reposition'               : 'Repozitionează',
  'photo_reposition_title'              : 'Repozitionează fotografia',
  'photo_reposition_sub'                : 'Trage fotografia pentru a ajusta poziția',
  'photo_reposition_reset'              : 'Resetează la centru',
  'photo_reposition_apply'              : 'Aplică',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Competențe',
  'skills_subtitle'                     : 'Evidențiază abilitățile tale cheie',
  'skills_add_btn'                      : 'Adaugă competență nouă',
  'skills_snack_max_icons'              : 'Numărul maxim de 10 pictograme selectate.',
  'skills_snack_max_skills'             : 'Numărul maxim de 15 competențe atins.',
  'skills_library_title'                : 'Competențe salvate',
  'skills_library_hint'                 : 'Competențele bifate sunt incluse în acest CV. Selecțiile tale sunt salvate automat.',
  'skills_nav_next'                     : 'Continuă la Suplimentar',
  'skills_wina_header_icon_bar'         : 'Bara de pictograme antet',
  'skills_wina_on'                      : 'PORNIT',
  'skills_wina_off'                     : 'OPRIT',
  'skills_wina_bar_on_sub'              : 'Cercuri colorate cu pictograme afișate în antetul CV-ului.',
  'skills_wina_bar_off_sub'             : 'Rândul de pictograme ascuns — mai mult spațiu pentru informații de contact.',
  'skills_wina_palette_hint'            : 'Pictogramele apar ca cercuri colorate în ordinea paletei.',
  'skills_wina_preview_label'           : 'Previzualizare',
  'skills_wina_disabled_hint'           : 'Activează bara de pictograme de mai sus pentru a alege ce pictograme apar în antetul CV-ului.',
  'skills_sheet_title_add'              : 'Adaugă competență',
  'skills_sheet_title_edit'             : 'Editează competența',
  'skills_sheet_field_name'             : 'Denumire competență *',
  'skills_sheet_hint_short'             : 'ex. Flutter, Design',
  'skills_sheet_hint_long'              : 'ex. Flutter, Management de proiect',
  'skills_sheet_validator_max'          : 'Max {n} caractere',
  'skills_sheet_proficiency'            : 'Nivel de competență',
  'skills_sheet_beginner'               : 'Începător',
  'skills_sheet_expert'                 : 'Expert',
  'skills_sheet_btn_save'               : 'Salvează competența',
  'skills_sheet_btn_update'             : 'Actualizează competența',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Referințe personale',
  'refs_subtitle'                       : 'Persoane care pot garanta personal pentru tine',
  'refs_add_btn'                        : 'Adaugă referință personală nouă',
  'refs_snack_max_selected'             : 'Maxim 4 referințe pot fi selectate pentru un CV.',
  'refs_snack_max_saved'                : 'Numărul maxim de 10 referințe salvate atins.',
  'refs_library_title'                  : 'Referințe salvate',
  'refs_library_hint'                   : 'Referințele bifate sunt incluse în acest CV. Max 4 per CV. Selecțiile tale sunt salvate automat.',
  'refs_nav_next'                       : 'Continuă la Personalizare',
  'refs_sheet_title_add'                : 'Adaugă referință personală',
  'refs_sheet_title_edit'               : 'Editează referința personală',
  'refs_sheet_sub_add'                  : 'Cineva care te poate recomanda personal angajatorilor.',
  'refs_sheet_sub_edit'                 : 'Actualizează detaliile acestei referințe mai jos.',
  'refs_sheet_field_name'               : 'Nume complet *',
  'refs_sheet_field_title'              : 'Titlu post *',
  'refs_sheet_field_company'            : 'Companie (opțional)',
  'refs_sheet_field_email'              : 'Adresă e-mail *',
  'refs_sheet_field_phone'              : 'Număr de telefon *',
  'refs_sheet_hint_name'                : 'ex. Ion Popescu',
  'refs_sheet_hint_title'               : 'ex. Manager Inginerie',
  'refs_sheet_hint_company'             : 'ex. Acme SRL',
  'refs_sheet_hint_email'               : 'ex. ion@acme.ro',
  'refs_sheet_hint_phone'               : 'ex. +40 721 123 456',
  'refs_sheet_validator_email'          : 'Introduceți o adresă de e-mail validă',
  'refs_sheet_btn_save'                 : 'Salvează referința personală',
  'refs_sheet_btn_update'               : 'Actualizează referința personală',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Experiență profesională',
  'exp_subtitle'                        : 'Adaugă istoricul tău de muncă',
  'exp_banner_info'                     : 'Până la {n} responsabilități per rol vor apărea pe CV. 3–6 roluri încap de obicei pe 1–2 pagini.',
  'exp_add_btn'                         : 'Adaugă experiență nouă',
  'exp_snack_max_selected'              : 'Maxim 8 experiențe pot fi selectate pentru un CV.',
  'exp_snack_max_saved'                 : 'Numărul maxim de 12 experiențe salvate atins.',
  'exp_library_title'                   : 'Experiențe salvate',
  'exp_library_hint'                    : 'Intrările bifate sunt incluse doar în acest CV. Alte CV-uri își păstrează propriile selecții independente.',
  'exp_nav_next'                        : 'Continuă la Educație',
  'exp_empty_message'                   : 'Nicio experiență adăugată încă',
  'exp_empty_sub'                       : 'Atinge mai sus pentru a adăuga primul tău rol',
  'exp_card_resp_singular'              : 'responsabilitate',
  'exp_card_resp_plural'                : 'responsabilități',
  'exp_card_resp_tooltip'               : 'Doar primele 8 responsabilități vor apărea pe CV',
  'exp_sheet_title_add'                 : 'Adaugă experiență',
  'exp_sheet_title_edit'                : 'Editează experiența',
  'exp_sheet_field_job_title'           : 'Titlu post *',
  'exp_sheet_field_company'             : 'Companie *',
  'exp_sheet_field_location'            : 'Locație',
  'exp_sheet_section_responsibilities'  : 'Responsabilități cheie',
  'exp_sheet_resp_hint_info'            : 'Max 8 puncte de listă · 200 caractere fiecare',
  'exp_sheet_resp_label'                : 'Responsabilitatea {n}',
  'exp_sheet_resp_hint'                 : 'ex. Am condus o echipă de 5 ingineri',
  'exp_sheet_resp_add_btn'              : 'Adaugă responsabilitate',
  'exp_sheet_resp_max_info'             : 'Numărul maxim de {n} responsabilități atins',
  'exp_sheet_resp_validator_max'        : 'Max 200 caractere',
  'exp_sheet_hint_job_title'            : 'ex. Dezvoltator Senior',
  'exp_sheet_hint_location'             : 'ex. București, România',
  'exp_sheet_btn_save'                  : 'Salvează experiența',
  'exp_sheet_btn_update'                : 'Salvează modificările',
  'exp_date_present'                    : 'Prezent / Rol curent',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Educație',
  'edu_subtitle'                        : 'Adaugă parcursul tău academic',
  'edu_add_btn'                         : 'Adaugă educație nouă',
  'edu_snack_max_selected'              : 'Maxim 8 intrări de educație pot fi selectate pentru un CV.',
  'edu_snack_max_saved'                 : 'Numărul maxim de 12 intrări de educație salvate atins.',
  'edu_library_title'                   : 'Educație salvată',
  'edu_library_hint'                    : 'Intrările bifate sunt incluse în acest CV. Selecțiile tale sunt salvate automat.',
  'edu_nav_next'                        : 'Continuă la Competențe',
  'edu_empty_message'                   : 'Nicio educație adăugată încă',
  'edu_empty_sub'                       : 'Atinge mai sus pentru a adăuga calificările tale',
  'edu_card_bullet_singular'            : 'punct de listă',
  'edu_card_bullet_plural'              : 'puncte de listă',
  'edu_sheet_title_add'                 : 'Adaugă educație',
  'edu_sheet_title_edit'                : 'Editează educația',
  'edu_sheet_field_degree'              : 'Diplomă / Calificare *',
  'edu_sheet_field_institution'         : 'Instituție *',
  'edu_sheet_section_key_points'        : 'Puncte cheie',
  'edu_sheet_key_points_hint_info'      : 'Opțional · 1 punct de listă · max 100 caractere',
  'edu_sheet_point_label'               : 'Punctul {n}',
  'edu_sheet_point_add_btn'             : 'Adaugă punct de listă',
  'edu_sheet_point_max_info'            : 'Numărul maxim de {n} puncte de listă atins',
  'edu_sheet_point_validator_max'       : 'Max {n} caractere',
  'edu_sheet_hint_degree'               : 'ex. Licență Informatică',
  'edu_sheet_hint_institution'          : 'ex. Universitatea din București',
  'edu_sheet_hint_bullet'               : 'ex. Absolvit cu mențiune',
  'edu_sheet_btn_save'                  : 'Salvează educația',
  'edu_sheet_btn_update'                : 'Salvează modificările',
  'edu_date_present'                    : 'Prezent / Studiu curent',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Informații suplimentare',
  'additional_subtitle'                 : 'Certificări, limbi și altele',
  'additional_cert_section_title'       : 'Certificări',
  'additional_cert_counter'             : '{sel}/{total} selectate · max {max}',
  'additional_cert_hide'                : 'Ascunde',
  'additional_cert_show'                : 'Afișează',
  'additional_cert_add_btn'             : 'Adaugă',
  'additional_cert_snack_max'           : 'Numărul maxim de {n} intrări de certificare atins.',
  'additional_cert_hint'                : 'Intrările bifate sunt incluse în acest CV. Selecțiile tale sunt salvate automat.',
  'additional_cert_empty'               : 'Nicio certificare adăugată încă',
  'additional_lang_section_title'       : 'Limbi',
  'additional_lang_add_hint'            : 'ex. Spaniolă',
  'additional_lang_snack_max'           : 'Numărul maxim de {n} intrări de limbă atins.',
  'additional_lang_empty'               : 'Nicio limbă adăugată încă',
  'additional_hobby_section_title'      : 'Hobby-uri și interese',
  'additional_hobby_add_hint'           : 'ex. Fotografie',
  'additional_hobby_snack_max'          : 'Numărul maxim de {n} intrări de hobby atins.',
  'additional_hobby_empty'              : 'Niciun hobby adăugat încă',
  'additional_section_hint'             : 'Intrările bifate sunt incluse în acest CV. Selecțiile tale sunt salvate automat.',
  'additional_nav_next'                 : 'Continuă la Referințe',
  'cert_sheet_title_add'                : 'Adaugă certificare',
  'cert_sheet_title_edit'               : 'Editează certificarea',
  'cert_sheet_sub'                      : 'Adaugă o calificare, certificat sau acreditare profesională.',
  'cert_sheet_field_name'               : 'Denumire certificare *',
  'cert_sheet_field_issued_by'          : 'Emis de (opțional)',
  'cert_sheet_field_short_desc'         : 'Descriere scurtă (opțional)',
  'cert_sheet_hint_name'                : 'ex. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'ex. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'ex. Obținut în 2024',
  'cert_sheet_btn_save'                 : 'Salvează certificarea',
  'cert_sheet_btn_update'               : 'Actualizează certificarea',
  'simple_sheet_title_add_language'     : 'Adaugă limbă',
  'simple_sheet_title_edit_language'    : 'Editează limba',
  'simple_sheet_title_add_hobby'        : 'Adaugă hobby',
  'simple_sheet_title_edit_hobby'       : 'Editează hobby-ul',
  'simple_sheet_btn_save'               : 'Salvează',
  'simple_sheet_btn_update'             : 'Actualizează',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Contact',
  'pdf_section_about_me'                : 'Despre mine',
  'pdf_section_summary'                 : 'Sumar',
  'pdf_section_summary_short'           : 'Sumar',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Experiență',
  'pdf_section_experience_short'        : 'Experiență',
  'pdf_section_education'               : 'Educație',
  'pdf_section_skills'                  : 'Competențe',
  'pdf_section_languages'               : 'Limbi',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Localizare',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Limita CV atinsă',
  'limit_dialog_body'                   : 'Ai atins maximul de 30 de CV-uri. Șterge un CV existent înainte de a crea unul nou.',
  'limit_dialog_go_to_my_cvs'           : 'Mergi la CV-urile mele',
  'limit_dialog_cancel'                 : 'Anulează',
  'refs_count_summary'                  : '{checked}/{maxChecked} selectate · {saved}/{maxSaved} salvate',
  'refs_selected_badge'                 : '{n} selectat(e)',
  'refs_empty_message'                  : 'Nicio referință salvată încă',
  'refs_empty_sub'                      : 'Apasă mai sus pentru a adăuga o referință personală',
};