// lib/language_keys/lang_ko_korean.dart
//
// Korean (한국어) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> koKorean = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : '언어를 찾을 수 없습니다',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : '건너뛰기',
  'onboarding_next'                     : '다음',
  'onboarding_get_started'              : '시작하기',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  환영합니다',
  'ob1_title'                           : '기회를 여는\n이력서 만들기',
  'ob1_body'                            : '수백 명의 지원자 중에서 돋보이세요. 디자인 지식 없이도 몇 분 만에 완성도 높은 이력서를 만들 수 있습니다.',
  'ob1_pill_label'                      : '전문 이력서 빌더',
  'ob1_chip_templates'                  : '24가지 이상의 템플릿',
  'ob1_chip_pdf'                        : 'PDF 내보내기',
  'ob1_chip_free'                       : '무료 사용',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  템플릿',
  'ob2_title'                           : '모든 업종.\n모든 목표.',
  'ob2_body'                            : '이사회 스타일의 레이아웃부터 대담한 크리에이티브 디자인까지 — 당신의 이야기를 담을 템플릿.',
  'ob2_tap_hint'                        : '템플릿을 탭하여 미리보기',
  'ob2_tpl_executive'                   : '이그제큐티브',
  'ob2_tpl_vibrant'                     : '바이브런트',
  'ob2_tpl_nordic'                      : '노르딕',
  'ob2_tpl_tech_dark'                   : '테크 다크',
  'ob2_tpl_luxury'                      : '럭셔리',
  'ob2_tag_corporate'                   : '기업용',
  'ob2_tag_creative'                    : '크리에이티브',
  'ob2_tag_minimal'                     : '미니멀',
  'ob2_tag_modern'                      : '모던',
  'ob2_tag_premium'                     : '프리미엄',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  스마트 레이아웃',
  'ob3_title'                           : '나만의 이력서.\n완벽하게 정렬.',
  'ob3_body'                            : '스마트 레이아웃이 섹션을 재배열하여 최대한의 임팩트를 주고, 채용 담당자가 가장 먼저 보는 곳에 핵심 내용을 배치합니다.',
  'ob3_badge_smart_layout'              : '스마트 레이아웃',
  'ob3_badge_cv_ready'                  : 'CV 완성!',
  'ob3_step1_label'                     : '템플릿 선택',
  'ob3_step1_desc'                      : '24가지 이상의 멋진 디자인 중에서 선택하세요.',
  'ob3_step2_label'                     : '정보 입력',
  'ob3_step2_desc'                      : '모든 섹션에 대한 안내 필드.',
  'ob3_step3_label'                     : '스마트 레이아웃',
  'ob3_step3_desc'                      : '탭 한 번으로 이력서를 완벽하게 재정렬.',
  'ob3_step4_label'                     : 'PDF로 내보내기',
  'ob3_step4_desc'                      : '픽셀 퍼펙트 PDF 바로 전송 가능.',
  'ob3_section_work'                    : '경력 사항',
  'ob3_section_education'               : '학력',
  'ob3_section_skills'                  : '기술',
  'ob3_section_references'              : '추천인',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  시작 준비 완료',
  'ob4_title'                           : '우수 지원자들이\nCV Builder를 선택하는 이유',
  'ob4_visual_headline'                 : '모든 준비가 완료되었습니다!',
  'ob4_visual_subline'                  : '취업에 필요한 모든 것을 갖추셨습니다.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : '템플릿',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : '최대 CV 수',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : '내보내기',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : '비공개',
  'ob4_hl1_title'                       : '비공개 및 보안',
  'ob4_hl1_sub'                         : '데이터는 기기에 안전하게 저장됩니다.',
  'ob4_hl2_title'                       : '자동 저장',
  'ob4_hl2_sub'                         : '모든 입력 내용이 즉시 저장됩니다.',
  'ob4_hl3_title'                       : '최대 30개 CV',
  'ob4_hl3_sub'                         : '모든 직무에 맞는 고유한 CV.',
  'ob4_hl4_title'                       : '원터치 공유',
  'ob4_hl4_sub'                         : '앱을 나가지 않고 PDF 전송 가능.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ 경쟁자들 사이에서 돋보이세요',
  'home_hero_title'                     : '전문적인 이력서\n지금 만들어보세요',
  'home_hero_sub'                       : '몇 분 만에 멋진\n이력서를 완성하세요',
  'home_hero_cta'                       : '이력서 만들기',
  'home_premium_soon'                   : '프로 업그레이드 기능이 곧 출시됩니다!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : '최신순',
  'history_sort_alphabetical'           : '가나다순',
  'history_sort_last_edited'            : '최근 편집순',
  'history_sort_by_template'            : '템플릿별',
  'history_sort_sheet_title'            : '정렬 기준',
  'history_sort_alphabetical_full'      : '알파벳순 (A–Z)',
  'history_premium_soon'                : '프로 업그레이드 기능이 곧 출시됩니다!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : '설정',
  'settings_section_preferences'        : '환경 설정',
  'settings_section_support'            : '지원',
  'settings_section_legal'              : '법적 고지',
  'settings_section_about'              : '앱 정보',
  'settings_language_tile_title'        : '언어',
  'settings_dark_mode_title'            : '다크 모드',
  'settings_dark_mode_on'               : '다크 테마 활성화됨',
  'settings_dark_mode_off'              : '라이트 테마 활성화됨',
  'settings_help_faq_title'             : '도움말 및 FAQ',
  'settings_help_faq_sub'               : '자주 묻는 질문에 대한 답변',
  'settings_contact_support_title'      : '고객 지원 문의',
  'settings_rate_app_title'             : '앱 평가하기',
  'settings_rate_app_sub'               : '앱이 마음에 드신다면 리뷰를 남겨주세요!',
  'settings_privacy_policy_title'       : '개인정보 처리방침',
  'settings_terms_title'                : '서비스 이용약관',
  'settings_app_version_title'          : '앱 버전',
  'settings_email_error'                : '이메일 앱을 열 수 없습니다. cyberinc101@gmail.com으로 직접 이메일을 보내주세요',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'CV 미리보기',
  'preview_header_sub'                  : '내보낼 준비 완료',
  'preview_generating'                  : 'CV를 생성하는 중...',
  'preview_failed_title'                : '미리보기 실패',
  'preview_failed_error'                : '오류: {error}',
  'preview_go_back'                     : '뒤로 가기',
  'preview_no_data'                     : '사용 가능한 데이터가 없습니다',
  'preview_btn_print'                   : '인쇄',
  'preview_btn_download'                : '다운로드 및 공유',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : '도움말 및 FAQ',
  'faq_category_all'                    : '전체',
  'faq_empty'                           : '검색 결과가 없습니다',
  'faq_contact_headline'                : '아직도 도움이 필요하신가요?',
  'faq_contact_sub'                     : '저희 팀이 도와드리겠습니다.',
  'faq_contact_btn'                     : '문의하기',
  'faq_email_error'                     : '이메일 앱을 열 수 없습니다. cyberinc101@gmail.com으로 직접 이메일을 보내주세요',
  'faq_cat_getting_started'             : '시작하기',
  'faq_cat_templates'                   : '템플릿',
  'faq_cat_editing'                     : '편집하기',
  'faq_cat_exporting'                   : '내보내기',
  'faq_cat_data_privacy'                : '데이터 및 개인정보',
  'faq_cat_troubleshooting'             : '문제 해결',
  'faq_q1'  : '첫 번째 CV를 어떻게 만드나요?',
  'faq_a1'  : '홈 화면의 "+" 버튼을 탭하여 새 CV를 시작하세요. 스타일에 맞는 템플릿을 선택한 후 개인 정보, 경력 사항, 학력, 기술을 단계별로 입력하세요. 진행 상황은 자동으로 저장됩니다.',
  'faq_q2'  : 'CV를 여러 개 만들 수 있나요?',
  'faq_a2'  : '네! 다양한 직무나 업종에 맞게 여러 CV를 만들 수 있습니다. 각 CV는 별도로 저장되므로 특정 채용 공고에 맞게 맞춤 설정할 수 있습니다.',
  'faq_q3'  : 'CV 템플릿을 어떻게 변경하나요?',
  'faq_a3'  : 'CV를 열고 화면 상단의 템플릿 아이콘을 탭한 후 사용 가능한 템플릿을 탐색하세요. 템플릿을 탭하면 기존 내용으로 미리볼 수 있습니다. 확인하여 적용하세요.',
  'faq_q4'  : '무료 템플릿과 유료 템플릿이 있나요?',
  'faq_a4'  : '네. 다양한 전문 템플릿을 무료로 이용할 수 있습니다. 고급 디자인과 색상 팔레트가 포함된 프리미엄 템플릿은 일회성 구매 또는 구독을 통해 이용할 수 있습니다.',
  'faq_q5'  : '섹션을 어떻게 추가하거나 제거하나요?',
  'faq_a5'  : 'CV 편집기에서 화면 아래로 스크롤하여 "섹션 추가"를 탭하면 언어, 자격증, 봉사활동 등을 추가할 수 있습니다. 섹션을 제거하려면 섹션 헤더를 탭하고 "제거"를 선택하세요.',
  'faq_q6'  : '섹션 순서를 어떻게 변경하나요?',
  'faq_a6'  : '섹션 헤더 옆의 드래그 핸들(≡)을 길게 누르고 원하는 위치로 드래그하세요. 변경 사항은 자동으로 저장됩니다.',
  'faq_q7'  : 'CV를 PDF로 내보내는 방법은 무엇인가요?',
  'faq_a7'  : 'CV를 열고 오른쪽 상단 모서리의 내보내기 버튼(공유 아이콘)을 탭하세요. "PDF로 내보내기"를 선택하면 기기에 저장하거나 이메일, WhatsApp으로 공유하거나 취업 게시판에 직접 업로드할 수 있습니다.',
  'faq_q8'  : '어떤 파일 형식이 지원되나요?',
  'faq_a8'  : '현재 앱은 고품질 PDF로 CV를 내보내는 기능을 지원합니다. 추가 형식은 향후 업데이트에서 추가될 수 있습니다.',
  'faq_q9'  : 'CV 데이터는 어디에 저장되나요?',
  'faq_a9'  : '모든 CV 데이터는 기기에 로컬로 저장됩니다. 개인 정보는 서버에 업로드되지 않습니다. 즉, 데이터가 비공개 상태로 유지되며 오프라인에서도 접근할 수 있습니다.',
  'faq_q10' : 'CV를 어떻게 백업하나요?',
  'faq_a10' : 'CV는 기기 설정에서 백업을 활성화한 경우 기기의 표준 백업(Android의 경우 Google Drive 백업, iOS의 경우 iCloud)에 포함됩니다. 개별 CV를 PDF로 내보내 사본을 보관할 수도 있습니다.',
  'faq_q11' : '앱이 느리게 실행됩니다. 어떻게 해야 하나요?',
  'faq_a11' : '앱을 닫았다가 다시 여세요. 문제가 계속되면 기기를 재시작하세요. Play Store / App Store에서 최신 버전의 앱이 설치되어 있는지 확인하세요.',
  'faq_q12' : 'CV가 올바르게 내보내지지 않습니다. 어떻게 해야 하나요?',
  'faq_a12' : '기기에 충분한 저장 공간이 있는지 확인하세요. CV의 큰 이미지를 줄여 보세요. 문제가 계속되면 고객 지원팀에 문의해 주세요.',
  'faq_q13' : '저장하지 않았는데 작업 내용이 사라졌나요?',
  'faq_a13' : '전혀 그렇지 않습니다! 앱은 편집하는 동안 지속적으로 진행 상황을 저장합니다.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : '당신의 커리어를 완성하세요',
  'header_tooltip_back'                 : '뒤로가기',
  'header_tooltip_my_cvs'               : '내 CV',
  'header_tooltip_settings'             : '설정',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : '내 CV',
  'saved_count_single'                  : '{n}개 문서',
  'saved_count_plural'                  : '{n}개 문서',
  'saved_limit_reached'                 : '한도 초과',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : '전체',
  'saved_filter_draft'                  : '초안',
  'saved_filter_complete'               : '완료',
  'saved_status_complete'               : '완료',
  'saved_status_saved'                  : '저장됨',
  'saved_status_draft'                  : '초안',
  'saved_empty_title'                   : 'CV가 아직 없습니다',
  'saved_empty_sub'                     : '위에서 첫 번째 CV 만들기를 시작하세요',
  'saved_search_empty_title'            : '검색 결과가 없습니다',
  'saved_search_empty_sub'              : '다른 검색어를 사용해 보세요',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : '색상 구성',
  'custom_font_settings_title'          : '글꼴 설정',
  'custom_font_family_label'            : '글꼴 종류',
  'custom_font_size_label'              : '글꼴 크기: ',
  'custom_current_template_title'       : '현재 템플릿',
  'custom_change_template_btn'          : '템플릿 변경',
  'custom_tpl_modern'                   : '모던',
  'custom_tpl_classic'                  : '클래식',
  'custom_tpl_professional'             : '프로페셔널',
  'custom_tpl_creative'                 : '크리에이티브',
  'custom_tpl_minimal'                  : '미니멀',
  'custom_tpl_modern_desc'              : '깔끔하고 현대적인 디자인',
  'custom_tpl_classic_desc'             : '전통적인 전문가 레이아웃',
  'custom_tpl_professional_desc'        : '비즈니스 중심 템플릿',
  'custom_tpl_creative_desc'            : '독특한 디자인으로 눈에 띄세요',
  'custom_tpl_minimal_desc'             : '간결하고 우아한 스타일',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : '템플릿 선택',
  'swipe_photo_badge'                   : '사진',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : '이그제큐티브',
  'tpl_nordic_name'                     : '노르딕',
  'tpl_vibrant_name'                    : '바이브런트',
  'tpl_tech_dark_name'                  : '테크 다크',
  'tpl_luxury_name'                     : '럭셔리',
  'tpl_executive_tag'                   : '가장 인기 있는',
  'tpl_nordic_tag'                      : '깔끔한',
  'tpl_vibrant_tag'                     : '크리에이티브',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : '엘리트',
  'tpl_executive_desc'                  : '시니어 직무를 위한 강렬하고 권위 있는 디자인',
  'tpl_nordic_desc'                     : '최고 기업들이 신뢰하는 미니멀 명료함',
  'tpl_vibrant_desc'                    : '활기와 색감으로 돋보이세요',
  'tpl_tech_dark_desc'                  : '개발자를 위한 터미널 스타일',
  'tpl_luxury_desc'                     : '검정 바탕에 금색 포인트의 프리미엄 디자인',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : '템플릿',
  'detail_step_personal'                : '개인 정보',
  'detail_step_experience'              : '경력',
  'detail_step_education'               : '학력',
  'detail_step_skills'                  : '기술',
  'detail_step_additional'              : '추가 정보',
  'detail_step_references'              : '추천인',
  'detail_step_customize'               : '커스터마이즈',
  'detail_banner_heading'               : '거의 다 왔습니다!',
  'detail_banner_btn'                   : '계속하기',
  'detail_banner_completion_label'      : '완료율',
  'detail_stat_created_label'           : '생성일',
  'detail_stat_steps_label'             : '완료된 단계',
  'detail_section_template_style'       : '템플릿 스타일',
  'detail_section_steps'                : '단계',
  'detail_steps_counter'                : '{total} 중 {done} 완료',
  'detail_step_sub'                     : '{total} 중 {n}단계',
  'detail_section_activity'             : '활동',
  'detail_activity_created'             : '생성됨',
  'detail_activity_last_edited'         : '마지막 편집',
  'detail_activity_template'            : '템플릿',
  'detail_btn_continue_editing'         : '편집 계속하기',
  'detail_btn_edit_cv'                  : 'CV 편집',
  'detail_option_rename'                : 'CV 이름 변경',
  'detail_option_delete'                : 'CV 삭제',
  'detail_rename_title'                 : 'CV 이름 변경',
  'detail_rename_hint'                  : '예: 소프트웨어 엔지니어 CV',
  'detail_rename_error_empty'           : '이름은 비워 둘 수 없습니다',
  'detail_rename_btn_cancel'            : '취소',
  'detail_rename_btn_save'              : '저장',
  'detail_rename_snackbar'              : '"{name}"(으)로 이름이 변경되었습니다',
  'detail_delete_title'                 : 'CV를 삭제하시겠습니까?',
  'detail_delete_body'                  : '"{name}"이(가) 영구적으로 삭제됩니다. 이 작업은 되돌릴 수 없습니다.',
  'detail_delete_btn_cancel'            : '취소',
  'detail_delete_btn_confirm'           : '삭제',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : '완료됨',
  'detail_check_tile_incomplete'        : '아직 입력되지 않음',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : '템플릿 선택',
  'chooser_subtitle'                    : '스와이프로 탐색  ·  탭으로 선택  ·  길게 눌러 미리보기',
  'chooser_card_hold_hint'              : '길게 눌러 미리보기',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : '선택됨',
  'chooser_modal_heading'               : 'CV 이름 짓기',
  'chooser_modal_sub'                   : '내 CV 및 기록에서 쉽게 찾을 수 있도록 이름을 지어주세요.',
  'chooser_modal_field_label'           : 'CV 이름',
  'chooser_modal_save_btn'              : '저장 및 작성 시작',
  'chooser_modal_divider'               : '또는 기존 CV를 계속 작성하세요',
  'chooser_nav_selected_sub'            : '선택된 템플릿',
  'chooser_nav_cta'                     : '저장 및 계속',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : '최대 항목 수에 도달했습니다',
  'editor_show_hide'                    : '표시/숨기기',
  'editor_editing_badge'                : '편집 중',
  'editor_field_required'               : '필수',
  'editor_tooltip_edit'                 : '편집',
  'editor_tooltip_delete'               : '삭제',
  'editor_date_start'                   : '시작일 *',
  'editor_date_end'                     : '종료일 *',
  'editor_date_tap_hint'                : '탭하여 선택',
  'editor_date_dialog_title'            : '월 및 연도 선택',
  'editor_date_confirm'                 : '확인',
  'editor_panel_hide'                   : '숨기기',
  'editor_panel_show'                   : '표시',
  'editor_validator_max_chars'          : '최대 {n}자',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'CV 작성하기',
  'editor_header_step_sub'              : '{total} 중 {current}단계 · {label}',
  'editor_step_template'                : '템플릿',
  'editor_step_personal'                : '개인 정보',
  'editor_step_experience'              : '경력',
  'editor_step_education'               : '학력',
  'editor_step_skills'                  : '기술',
  'editor_step_additional'              : '추가 정보',
  'editor_step_references'              : '추천인',
  'editor_step_customize'               : '커스터마이즈',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : '커스터마이즈',
  'customize_subtitle'                  : 'CV를 나만의 것으로 만들어보세요',
  'customize_smart_layout_btn'          : '스마트 레이아웃',
  'customize_back_to_top'               : '맨 위로',
  'customize_done_title'                : '모든 준비가 완료되었습니다!',
  'customize_done_sub'                  : '아래의 CV 미리보기를 탭하여 완성된 CV를 확인하세요',
  'customize_preview_btn'               : 'CV 미리보기',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : '색상 구성',
  'color_black'                         : '블랙',
  'color_blue'                          : '블루',
  'color_nordic_blue'                   : '노르딕 블루',
  'color_indigo'                        : '인디고',
  'color_teal'                          : '틸',
  'color_green'                         : '그린',
  'color_purple'                        : '퍼플',
  'color_orange'                        : '오렌지',
  'color_red'                           : '레드',
  'color_executive_gold'                : '이그제큐티브 골드',
  'color_vibrant_coral'                 : '바이브런트 코랄',
  'color_white'                         : '화이트',
  'color_white_bg'                      : '화이트 배경',
  'color_maroon'                        : '마룬',
  'color_brutalist_yellow'              : '브루탈리스트 옐로우',
  'color_neon_blue'                     : '네온 블루',
  'color_blueprint_navy'                : '블루프린트 네이비',
  'color_light_grey'                    : '라이트 그레이',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : '글꼴 종류',
  'customize_font_picker_title'         : '글꼴 선택',
  'customize_font_picker_sub'           : '각 글꼴은 해당 서체로 미리보기됩니다',
  'customize_font_preview_sample'       : '빠른 갈색 여우',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : '글꼴 크기',
  'customize_font_size_label'           : '텍스트 크기',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : '이미지 크기',
  'customize_image_size_label'          : '이미지 크기',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : '실시간 미리보기',
  'preview_page_count_singular'         : '1페이지',
  'preview_page_count_plural'           : '{n}페이지',
  'preview_page_of'                     : '{total}페이지 중 {page}페이지',
  'preview_live_hint'                   : '변경 사항이 즉시 적용됩니다',
  'preview_template_unregistered'       : 'customize_preview.dart에 아직 등록되지 않음',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'CV를 준비하는 중…',
  'preview_bar_print'                   : '인쇄',
  'preview_bar_save_pdf'                : 'PDF로 저장',
  'preview_bar_share'                   : '공유',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'CV 미리보기',
  'preview_screen_sub'                  : '{n} {unit} · 인쇄된 그대로',
  'preview_page_singular'               : '페이지',
  'preview_page_plural'                 : '페이지',
  'preview_pdf_filename'                : '나의_CV',
  'preview_share_subject'               : '나의 CV',
  'preview_snack_print_failed'          : '인쇄 실패: {e}',
  'preview_snack_saved'                 : 'CV가 다운로드 폴더에 저장되었습니다 ✓',
  'preview_snack_export_failed'         : '내보내기 실패: {e}',
  'preview_snack_share_failed'          : '공유 실패: {e}',
  'preview_template_not_registered'     : '등록되지 않은 템플릿입니다',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : '미리보기 닫기',
  'preview_modal_hint_photo'            : '프로필 사진 지원  ·  카드를 탭하여 선택',
  'preview_modal_hint_no_photo'         : '템플릿 카드를 탭하여 선택하세요',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : '나의 CV',
  'time_just_now'                       : '방금 전',
  'time_minutes_ago'                    : '{n}분 전',
  'time_hours_ago'                      : '{n}시간 전',
  'time_yesterday'                      : '어제',
  'time_days_ago'                       : '{n}일 전',
  'time_one_week_ago'                   : '1주일 전',
  'time_weeks_ago'                      : '{n}주일 전',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : '엘레강트',
  'tpl_tag_classic'                     : '클래식',
  'tpl_tag_minimal'                     : '미니멀',
  'tpl_tag_creative'                    : '크리에이티브',
  'tpl_tag_bold'                        : '볼드',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : '그라디언트',
  'tpl_gradient_desc'                   : '틸에서 바이올렛으로 이어지는 그라디언트 카드',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : '에디토리얼',
  'tpl_editorial_desc'                  : '잡지 스타일의 레드 & 크림 디자인',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : '파스텔 소프트',
  'tpl_pastel_soft_desc'                : '라벤더 사이드바, 부드러운 카드',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : '브루탈리스트',
  'tpl_brutalist_desc'                  : '거친 그리드, 굵은 테두리 & 옐로우',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : '에메랄드',
  'tpl_emerald_desc'                    : '타임라인이 있는 포레스트 그린',

  // ID 11 · Infographic
  'tpl_infographic_name'                : '인포그래픽',
  'tpl_infographic_desc'                : '링 차트가 있는 다크 캔버스',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : '아르 데코',
  'tpl_art_deco_desc'                   : '1920년대 기하학적 골드 럭셔리',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : '위나 다크',
  'tpl_wina_dark_desc'                  : '링이 있는 다크 인포그래픽',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : '리오 오렌지',
  'tpl_rio_orange_desc'                 : '오렌지 포인트의 다크 사이드바',

  // ID 15 · Summer
  'tpl_summer_name'                     : '썸머',
  'tpl_summer_desc'                     : '깔끔한 미니멀, 부드러운 그레이 톤',

  // ID 16 · Helene
  'tpl_helene_name'                     : '엘렌',
  'tpl_helene_desc'                     : '따뜻한 베이지 우아한 톤',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : '캔필드',
  'tpl_canfield_desc'                   : '강렬한 블랙 & 화이트 클래식',

  // ID 18 · Collins
  'tpl_collins_name'                    : '콜린스',
  'tpl_collins_desc'                    : 'ATS 친화적 클래식 레이아웃',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : '토니 다크',
  'tpl_tony_dark_desc'                  : '다크 오렌지 인포그래픽 스타일',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : '패션',
  'tpl_fashion_desc'                    : '그리드 위의 기술 도면 스타일',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : '아키비스트',
  'tpl_archivist_desc'                  : '클래식 2열 레이블 레이아웃',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : '디플로맷',
  'tpl_diplomat_desc'                   : '다이아몬드 리더가 있는 음영 헤더',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : '메리디안',
  'tpl_meridian_desc'                   : '가운데 정렬 헤더, 강조된 회사명',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : '모멘텀',
  'tpl_momentum_desc'                   : '굵은 이름, 타임라인 점 & 성과',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : '개인 정보',
  'personal_subtitle'                   : '채용 담당자에게 자신을 소개하세요',
  'personal_profile_counter'            : '{n}/{max}개 프로필',
  'personal_info_banner'                : '최대 5개의 프로필을 저장하고 CV당 하나를 선택할 수 있습니다. 각 CV마다 선택 사항이 별도로 저장됩니다.',
  'personal_snack_max'                  : '최대 {n}개의 프로필에 도달했습니다.',
  'personal_add_btn'                    : '새 프로필 추가',
  'personal_library_title'              : '저장된 프로필',
  'personal_selected_one'               : '1개 선택됨',
  'personal_selected_none'              : '선택된 항목 없음',
  'personal_library_hint'               : '카드를 탭하면 이 CV에만 선택됩니다. 다른 CV는 각각의 독립적인 선택을 유지합니다.',
  'personal_empty_message'              : '저장된 프로필이 없습니다',
  'personal_empty_sub'                  : '위를 탭하여 개인 정보를 추가하세요',
  'personal_nav_next'                   : '저장 및 계속',
  'personal_card_active_badge'          : '이 CV에 활성화됨',
  'personal_sheet_title_add'            : '새 프로필',
  'personal_sheet_title_edit'           : '프로필 편집',
  'personal_sheet_brutalist_badge'      : '브루탈리스트',
  'personal_sheet_brutalist_banner'     : '브루탈리스트 템플릿은 간결한 연락처 필드를 사용합니다. 짧은 값(예: 도시 이름만)이 가장 잘 표시됩니다.',
  'personal_section_photo'              : '프로필 사진',
  'personal_section_basic'              : '기본 정보',
  'personal_section_contact'            : '연락처',
  'personal_section_online'             : '온라인 정보',
  'personal_section_summary'            : '전문 요약',
  'personal_field_first_name'           : '이름 *',
  'personal_field_last_name'            : '성',
  'personal_field_job_title'            : '직함 *',
  'personal_field_email'                : '이메일 주소 *',
  'personal_field_phone'                : '전화번호 *',
  'personal_field_location'             : '위치',
  'personal_field_location_brut'        : '위치 (도시만)',
  'personal_field_website'              : '웹사이트 / 포트폴리오',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : '예: 지민',
  'personal_hint_last_name'             : '예: 박',
  'personal_hint_job_title'             : '예: 시니어 소프트웨어 엔지니어',
  'personal_hint_email'                 : '예: jimin@example.com',
  'personal_hint_phone'                 : '예: +82 10 1234 5678',
  'personal_hint_location'              : '예: 서울, 대한민국',
  'personal_hint_location_brut'         : '예: 서울, 한국',
  'personal_hint_website'               : '예: github.com/jiminpark',
  'personal_hint_website_brut'          : '예: github.com/jimin',
  'personal_hint_linkedin'              : '예: linkedin.com/in/jiminpark',
  'personal_hint_linkedin_brut'         : '예: linkedin.com/in/jimin',
  'personal_summary_hint_label'         : '간결하게 작성하세요 — 이 내용은 CV 상단에 표시됩니다.',
  'personal_hint_summary'               : '배경과 목표에 대한 간결한 2~3문장 요약...',
  'personal_validator_email'            : '유효한 이메일을 입력하세요',
  'personal_field_char_limit_tooltip'   : '글자 수 제한에 도달했습니다',
  'personal_sheet_btn_save'             : '프로필 저장',
  'personal_sheet_btn_update'           : '변경 사항 저장',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : '사진 선택',
  'photo_option_gallery'                : '갤러리에서 선택',
  'photo_option_camera'                 : '사진 촬영',
  'photo_option_reposition'             : '사진 위치 조정',
  'photo_option_remove'                 : '사진 제거',
  'photo_status_added'                  : '사진이 추가되었습니다 ✓',
  'photo_status_empty'                  : '전문적인 증명사진을 추가하세요',
  'photo_chip_gallery'                  : '갤러리',
  'photo_chip_camera'                   : '카메라',
  'photo_chip_reposition'               : '위치 조정',
  'photo_reposition_title'              : '사진 위치 조정',
  'photo_reposition_sub'                : '사진을 드래그하여 위치를 조정하세요',
  'photo_reposition_reset'              : '중앙으로 재설정',
  'photo_reposition_apply'              : '적용',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : '기술',
  'skills_subtitle'                     : '핵심 역량을 강조하세요',
  'skills_add_btn'                      : '새 기술 추가',
  'skills_snack_max_icons'              : '최대 10개의 아이콘이 선택되었습니다.',
  'skills_snack_max_skills'             : '최대 15개의 기술에 도달했습니다.',
  'skills_library_title'                : '저장된 기술',
  'skills_library_hint'                 : '체크된 기술이 이 CV에 포함됩니다. 선택 사항은 자동으로 저장됩니다.',
  'skills_nav_next'                     : '추가 정보로 계속',
  'skills_wina_header_icon_bar'         : '헤더 아이콘 바',
  'skills_wina_on'                      : '켜기',
  'skills_wina_off'                     : '끄기',
  'skills_wina_bar_on_sub'              : 'CV 헤더에 색상 아이콘 원이 표시됩니다.',
  'skills_wina_bar_off_sub'             : '아이콘 행이 숨겨져 연락처 정보를 위한 공간이 더 생깁니다.',
  'skills_wina_palette_hint'            : '아이콘은 팔레트 순서대로 색상 원으로 표시됩니다.',
  'skills_wina_preview_label'           : '미리보기',
  'skills_wina_disabled_hint'           : '위의 아이콘 바를 활성화하여 CV 헤더에 표시될 아이콘을 선택하세요.',
  'skills_sheet_title_add'              : '기술 추가',
  'skills_sheet_title_edit'             : '기술 편집',
  'skills_sheet_field_name'             : '기술 이름 *',
  'skills_sheet_hint_short'             : '예: Flutter, 디자인',
  'skills_sheet_hint_long'              : '예: Flutter, 프로젝트 관리',
  'skills_sheet_validator_max'          : '최대 {n}자',
  'skills_sheet_proficiency'            : '숙련도',
  'skills_sheet_beginner'               : '초보자',
  'skills_sheet_expert'                 : '전문가',
  'skills_sheet_btn_save'               : '기술 저장',
  'skills_sheet_btn_update'             : '기술 업데이트',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : '개인 추천인',
  'refs_subtitle'                       : '개인적으로 당신을 추천해 줄 수 있는 사람',
  'refs_add_btn'                        : '새 개인 추천인 추가',
  'refs_snack_max_selected'             : 'CV에 최대 4명의 추천인을 선택할 수 있습니다.',
  'refs_snack_max_saved'                : '저장된 추천인이 최대 10명에 도달했습니다.',
  'refs_library_title'                  : '저장된 추천인',
  'refs_library_hint'                   : '체크된 추천인이 이 CV에 포함됩니다. CV당 최대 4명. 선택 사항은 자동으로 저장됩니다.',
  'refs_nav_next'                       : '커스터마이즈로 계속',
  'refs_sheet_title_add'                : '개인 추천인 추가',
  'refs_sheet_title_edit'               : '개인 추천인 편집',
  'refs_sheet_sub_add'                  : '채용 담당자에게 개인적으로 추천해 줄 수 있는 사람.',
  'refs_sheet_sub_edit'                 : '아래에서 이 추천인의 정보를 업데이트하세요.',
  'refs_sheet_field_name'               : '성명 *',
  'refs_sheet_field_title'              : '직함 *',
  'refs_sheet_field_company'            : '회사 (선택)',
  'refs_sheet_field_email'              : '이메일 주소 *',
  'refs_sheet_field_phone'              : '전화번호 *',
  'refs_sheet_hint_name'                : '예: 김민준',
  'refs_sheet_hint_title'               : '예: 엔지니어링 매니저',
  'refs_sheet_hint_company'             : '예: 삼성전자',
  'refs_sheet_hint_email'               : '예: minjun@samsung.com',
  'refs_sheet_hint_phone'               : '예: +82 10 1234 5678',
  'refs_sheet_validator_email'          : '유효한 이메일 주소를 입력하세요',
  'refs_sheet_btn_save'                 : '개인 추천인 저장',
  'refs_sheet_btn_update'               : '개인 추천인 업데이트',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : '경력 사항',
  'exp_subtitle'                        : '업무 이력을 추가하세요',
  'exp_banner_info'                     : '역할당 최대 {n}개의 책임 사항이 CV에 표시됩니다. 3~6개 역할이 일반적으로 1~2페이지에 맞습니다.',
  'exp_add_btn'                         : '새 경력 추가',
  'exp_snack_max_selected'              : 'CV에 최대 8개의 경력을 선택할 수 있습니다.',
  'exp_snack_max_saved'                 : '저장된 경력이 최대 12개에 도달했습니다.',
  'exp_library_title'                   : '저장된 경력',
  'exp_library_hint'                    : '체크된 항목이 이 CV에만 포함됩니다. 다른 CV는 각각의 독립적인 선택을 유지합니다.',
  'exp_nav_next'                        : '학력으로 계속',
  'exp_empty_message'                   : '아직 경력이 추가되지 않았습니다',
  'exp_empty_sub'                       : '위를 탭하여 첫 번째 직무를 추가하세요',
  'exp_card_resp_singular'              : '책임 사항',
  'exp_card_resp_plural'                : '책임 사항',
  'exp_card_resp_tooltip'               : 'CV에는 처음 8개의 책임 사항만 표시됩니다',
  'exp_sheet_title_add'                 : '경력 추가',
  'exp_sheet_title_edit'                : '경력 편집',
  'exp_sheet_field_job_title'           : '직함 *',
  'exp_sheet_field_company'             : '회사 *',
  'exp_sheet_field_location'            : '위치',
  'exp_sheet_section_responsibilities'  : '주요 업무 및 책임',
  'exp_sheet_resp_hint_info'            : '최대 8개의 항목 · 각 200자',
  'exp_sheet_resp_label'                : '책임 사항 {n}',
  'exp_sheet_resp_hint'                 : '예: 5명의 엔지니어 팀 이끌기',
  'exp_sheet_resp_add_btn'              : '책임 사항 추가',
  'exp_sheet_resp_max_info'             : '최대 {n}개의 책임 사항에 도달했습니다',
  'exp_sheet_resp_validator_max'        : '최대 200자',
  'exp_sheet_hint_job_title'            : '예: 시니어 개발자',
  'exp_sheet_hint_location'             : '예: 서울, 대한민국',
  'exp_sheet_btn_save'                  : '경력 저장',
  'exp_sheet_btn_update'                : '변경 사항 저장',
  'exp_date_present'                    : '현재 / 재직 중',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : '학력',
  'edu_subtitle'                        : '학업 배경을 추가하세요',
  'edu_add_btn'                         : '새 학력 추가',
  'edu_snack_max_selected'              : 'CV에 최대 8개의 학력을 선택할 수 있습니다.',
  'edu_snack_max_saved'                 : '저장된 학력이 최대 12개에 도달했습니다.',
  'edu_library_title'                   : '저장된 학력',
  'edu_library_hint'                    : '체크된 항목이 이 CV에 포함됩니다. 선택 사항은 자동으로 저장됩니다.',
  'edu_nav_next'                        : '기술로 계속',
  'edu_empty_message'                   : '아직 학력이 추가되지 않았습니다',
  'edu_empty_sub'                       : '위를 탭하여 학력을 추가하세요',
  'edu_card_bullet_singular'            : '항목',
  'edu_card_bullet_plural'              : '항목',
  'edu_sheet_title_add'                 : '학력 추가',
  'edu_sheet_title_edit'                : '학력 편집',
  'edu_sheet_field_degree'              : '학위 / 자격 *',
  'edu_sheet_field_institution'         : '학교 *',
  'edu_sheet_section_key_points'        : '주요 사항',
  'edu_sheet_key_points_hint_info'      : '선택 사항 · 항목 1개 · 최대 100자',
  'edu_sheet_point_label'               : '사항 {n}',
  'edu_sheet_point_add_btn'             : '항목 추가',
  'edu_sheet_point_max_info'            : '최대 {n}개의 항목에 도달했습니다',
  'edu_sheet_point_validator_max'       : '최대 {n}자',
  'edu_sheet_hint_degree'               : '예: 컴퓨터공학 학사',
  'edu_sheet_hint_institution'          : '예: 서울대학교',
  'edu_sheet_hint_bullet'               : '예: 수석 졸업',
  'edu_sheet_btn_save'                  : '학력 저장',
  'edu_sheet_btn_update'                : '변경 사항 저장',
  'edu_date_present'                    : '현재 / 재학 중',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : '추가 정보',
  'additional_subtitle'                 : '자격증, 언어 등',
  'additional_cert_section_title'       : '자격증',
  'additional_cert_counter'             : '{sel}/{total} 선택됨 · 최대 {max}',
  'additional_cert_hide'                : '숨기기',
  'additional_cert_show'                : '표시',
  'additional_cert_add_btn'             : '추가',
  'additional_cert_snack_max'           : '최대 {n}개의 자격증 항목에 도달했습니다.',
  'additional_cert_hint'                : '체크된 항목이 이 CV에 포함됩니다. 선택 사항은 자동으로 저장됩니다.',
  'additional_cert_empty'               : '아직 자격증이 추가되지 않았습니다',
  'additional_lang_section_title'       : '언어',
  'additional_lang_add_hint'            : '예: 스페인어',
  'additional_lang_snack_max'           : '최대 {n}개의 언어 항목에 도달했습니다.',
  'additional_lang_empty'               : '아직 언어가 추가되지 않았습니다',
  'additional_hobby_section_title'      : '취미 및 관심사',
  'additional_hobby_add_hint'           : '예: 사진',
  'additional_hobby_snack_max'          : '최대 {n}개의 취미 항목에 도달했습니다.',
  'additional_hobby_empty'              : '아직 취미가 추가되지 않았습니다',
  'additional_section_hint'             : '체크된 항목이 이 CV에 포함됩니다. 선택 사항은 자동으로 저장됩니다.',
  'additional_nav_next'                 : '추천인으로 계속',
  'cert_sheet_title_add'                : '자격증 추가',
  'cert_sheet_title_edit'               : '자격증 편집',
  'cert_sheet_sub'                      : '자격, 인증서 또는 전문 자격 증명을 추가하세요.',
  'cert_sheet_field_name'               : '자격증 이름 *',
  'cert_sheet_field_issued_by'          : '발급 기관 (선택)',
  'cert_sheet_field_short_desc'         : '간단한 설명 (선택)',
  'cert_sheet_hint_name'                : '예: AWS 솔루션스 아키텍트',
  'cert_sheet_hint_issued_by'           : '예: Amazon Web Services',
  'cert_sheet_hint_short_desc'          : '예: 2024년 취득',
  'cert_sheet_btn_save'                 : '자격증 저장',
  'cert_sheet_btn_update'               : '자격증 업데이트',
  'simple_sheet_title_add_language'     : '언어 추가',
  'simple_sheet_title_edit_language'    : '언어 편집',
  'simple_sheet_title_add_hobby'        : '취미 추가',
  'simple_sheet_title_edit_hobby'       : '취미 편집',
  'simple_sheet_btn_save'               : '저장',
  'simple_sheet_btn_update'             : '업데이트',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : '연락처',
  'pdf_section_about_me'                : '자기소개',
  'pdf_section_summary'                 : '요약',
  'pdf_section_summary_short'           : '요약',
  'pdf_section_profile'                 : '프로필',
  'pdf_section_experience'              : '경력 사항',
  'pdf_section_experience_short'        : '경력',
  'pdf_section_education'               : '학력',
  'pdf_section_skills'                  : '기술',
  'pdf_section_languages'               : '언어',
  'pdf_label_email'                     : '이메일',
  'pdf_label_phone'                     : '전화',
  'pdf_label_location'                  : '위치',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'CV 한도 초과',
  'limit_dialog_body'                   : '최대 30개의 CV에 도달했습니다. 새 CV를 만들기 전에 기존 CV를 삭제해 주세요.',
  'limit_dialog_go_to_my_cvs'           : '내 CV로 이동',
  'limit_dialog_cancel'                 : '취소',
  'refs_count_summary'                  : '{checked}/{maxChecked} 선택됨 · {saved}/{maxSaved} 저장됨',
  'refs_selected_badge'                 : '{n}개 선택됨',
  'refs_empty_message'                  : '아직 저장된 추천인이 없습니다',
  'refs_empty_sub'                      : '위를 탭하여 개인 추천인을 추가하세요',
};