// lib/language_keys/lang_hu_hungarian.dart
//
// Hungarian (Hungary) — translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> huHungarian = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'Nem találhatók nyelvek',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'Kihagyás',
  'onboarding_next'                     : 'Következő',
  'onboarding_get_started'              : 'Kezdés',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  Üdvözöljük',
  'ob1_title'                           : 'Hozzon létre egy önéletrajzot,\nami ajtókat nyit',
  'ob1_body'                            : 'Tűnjön ki a sok jelölt közül. Készítsen csiszolt, állásnyerő önéletrajzot percek alatt — tervezési ismeretek nélkül.',
  'ob1_pill_label'                      : 'Professzionális önéletrajz-készítő',
  'ob1_chip_templates'                  : '24+ sablon',
  'ob1_chip_pdf'                        : 'PDF-exportálás',
  'ob1_chip_free'                       : 'Ingyenes',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  Sablonok',
  'ob2_title'                           : 'Minden iparág.\nMinden ambíció.',
  'ob2_body'                            : 'Az igazgatótanácsi elrendezésektől a bátor kreatív dizájnig — egy sablon, amely elmesíli az Ön történetét.',
  'ob2_tap_hint'                        : 'Koppintson bármelyik sablonra az előnézethez',
  'ob2_tpl_executive'                   : 'Vezető',
  'ob2_tpl_vibrant'                     : 'Élénk',
  'ob2_tpl_nordic'                      : 'Északi',
  'ob2_tpl_tech_dark'                   : 'Tech sötét',
  'ob2_tpl_luxury'                      : 'Luxus',
  'ob2_tag_corporate'                   : 'Vállalati',
  'ob2_tag_creative'                    : 'Kreatív',
  'ob2_tag_minimal'                     : 'Minimális',
  'ob2_tag_modern'                      : 'Modern',
  'ob2_tag_premium'                     : 'Prémium',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Okos elrendezés',
  'ob3_title'                           : 'Az Ön önéletrajza.\nTökéletesen elrendezve.',
  'ob3_body'                            : 'Az okos elrendezés átrendezi a szakaszokat a maximális hatás érdekében — a legerősebb tartalmat oda helyezi, ahol a toborzók először néznek.',
  'ob3_badge_smart_layout'              : 'Okos elrendezés',
  'ob3_badge_cv_ready'                  : 'Az önéletrajz kész!',
  'ob3_step1_label'                     : 'Válasszon sablont',
  'ob3_step1_desc'                      : 'Válasszon 24+ lenyűgöző dizájn közül.',
  'ob3_step2_label'                     : 'Töltse ki adatait',
  'ob3_step2_desc'                      : 'Irányított mezők minden szakaszhoz.',
  'ob3_step3_label'                     : 'Okos elrendezés',
  'ob3_step3_desc'                      : 'Egy érintéssel tökéletesen átrendezi az önéletrajzát.',
  'ob3_step4_label'                     : 'Exportálás PDF-ként',
  'ob3_step4_desc'                      : 'Pixel-tökéletes PDF készen áll a küldésre.',
  'ob3_section_work'                    : 'Munkatapasztalat',
  'ob3_section_education'               : 'Végzettség',
  'ob3_section_skills'                  : 'Készségek',
  'ob3_section_references'              : 'Referenciák',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  Készen áll',
  'ob4_title'                           : 'Miért választják a legjobb jelöltek\na CV Buildert',
  'ob4_visual_headline'                 : 'Minden készen áll!',
  'ob4_visual_subline'                  : 'Minden, amire szüksége van az állás megszerzéséhez.',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'Sablon',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'Max. önéletrajz',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'Exportálás',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'Privát',
  'ob4_hl1_title'                       : 'Privát és biztonságos',
  'ob4_hl1_sub'                         : 'Az adatok az eszközön maradnak.',
  'ob4_hl2_title'                       : 'Automatikus mentés',
  'ob4_hl2_sub'                         : 'Minden leütés azonnal mentésre kerül.',
  'ob4_hl3_title'                       : 'Akár 30 önéletrajz',
  'ob4_hl3_sub'                         : 'Egyedi önéletrajz minden pozícióhoz.',
  'ob4_hl4_title'                       : 'Egy érintéses megosztás',
  'ob4_hl4_sub'                         : 'PDF küldése az alkalmazás elhagyása nélkül.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ Tűnjön ki a tömegből',
  'home_hero_title'                     : 'Készítse el\nprofesszionális önéletrajzát',
  'home_hero_sub'                       : 'Készítsen lenyűgöző önéletrajzot\npercek alatt',
  'home_hero_cta'                       : 'Kezdés',
  'home_premium_soon'                   : 'A Pro-ra való frissítés hamarosan érkezik!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'Legújabb',
  'history_sort_alphabetical'           : 'A–Z',
  'history_sort_last_edited'            : 'Utoljára szerkesztett',
  'history_sort_by_template'            : 'Sablon szerint',
  'history_sort_sheet_title'            : 'Rendezés',
  'history_sort_alphabetical_full'      : 'Ábécé sorrendben (A–Z)',
  'history_premium_soon'                : 'A Pro-ra való frissítés hamarosan érkezik!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'Beállítások',
  'settings_section_preferences'        : 'Beállítások',
  'settings_section_support'            : 'Támogatás',
  'settings_section_legal'              : 'Jogi',
  'settings_section_about'              : 'Névjegy',
  'settings_language_tile_title'        : 'Nyelv',
  'settings_dark_mode_title'            : 'Sötét mód',
  'settings_dark_mode_on'               : 'Sötét téma engedélyezve',
  'settings_dark_mode_off'              : 'Világos téma engedélyezve',
  'settings_help_faq_title'             : 'Súgó és GYIK',
  'settings_help_faq_sub'               : 'Gyakori kérdések megválaszolva',
  'settings_contact_support_title'      : 'Kapcsolat a támogatással',
  'settings_rate_app_title'             : 'Értékelje az alkalmazást',
  'settings_rate_app_sub'               : 'Tetszik az alkalmazás? Írjon értékelést!',
  'settings_privacy_policy_title'       : 'Adatvédelmi irányelvek',
  'settings_terms_title'                : 'Felhasználási feltételek',
  'settings_app_version_title'          : 'Alkalmazásverzió',
  'settings_email_error'                : 'Nem sikerült megnyitni az e-mail alkalmazást. Kérjük, írjon a cyberinc101@gmail.com címre',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'Önéletrajz előnézete',
  'preview_header_sub'                  : 'Kész az exportálásra',
  'preview_generating'                  : 'Az önéletrajz létrehozása...',
  'preview_failed_title'                : 'Az előnézet sikertelen',
  'preview_failed_error'                : 'Hiba: {error}',
  'preview_go_back'                     : 'Vissza',
  'preview_no_data'                     : 'Nem áll rendelkezésre adat',
  'preview_btn_print'                   : 'Nyomtatás',
  'preview_btn_download'                : 'Letöltés és megosztás',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'Súgó és GYIK',
  'faq_category_all'                    : 'Összes',
  'faq_empty'                           : 'Nem találhatók eredmények',
  'faq_contact_headline'                : 'Még mindig segítségre van szüksége?',
  'faq_contact_sub'                     : 'Csapatunk rendelkezésére áll.',
  'faq_contact_btn'                     : 'Kapcsolatfelvétel',
  'faq_email_error'                     : 'Nem sikerült megnyitni az e-mail alkalmazást. Kérjük, írjon a cyberinc101@gmail.com címre',
  'faq_cat_getting_started'             : 'Első lépések',
  'faq_cat_templates'                   : 'Sablonok',
  'faq_cat_editing'                     : 'Szerkesztés',
  'faq_cat_exporting'                   : 'Exportálás',
  'faq_cat_data_privacy'                : 'Adatok és adatvédelem',
  'faq_cat_troubleshooting'             : 'Hibaelhárítás',
  'faq_q1'  : 'Hogyan hozzam létre az első önéletrajzomat?',
  'faq_a1'  : 'Koppintson a főképernyőn lévő "+" gombra egy új önéletrajz indításához. Válasszon a stílusához illő sablont, majd töltse ki személyes adatait, munkatapasztalatát, végzettségét és készségeit lépésről lépésre. A haladás automatikusan mentésre kerül.',
  'faq_q2'  : 'Létrehozhatok egynél több önéletrajzot?',
  'faq_a2'  : 'Igen! Több önéletrajzot is létrehozhat különböző pozíciókhoz vagy iparágakhoz. Minden önéletrajz külön kerül mentésre, így személyre szabhatja azokat az egyes állásjelentkezésekhez.',
  'faq_q3'  : 'Hogyan változtathatom meg az önéletrajz sablonját?',
  'faq_a3'  : 'Nyissa meg az önéletrajzát, koppintson a képernyő tetején lévő sablon ikonra, és böngésszen az elérhető sablonok között. Koppintson bármelyik sablonra a meglévő tartalmával való előnézethez. Erősítse meg az alkalmazáshoz.',
  'faq_q4'  : 'Vannak ingyenes és prémium sablonok?',
  'faq_a4'  : 'Igen. Ingyenesen elérhető egy professzionális sablonokból álló választék. A fejlett dizájnú és színpalettájú prémium sablonok egyszeri vásárláson vagy előfizetésen keresztül érhetők el.',
  'faq_q5'  : 'Hogyan adhatok hozzá vagy távolíthatok el szakaszokat?',
  'faq_a5'  : 'Az önéletrajz-szerkesztőben görgessen a képernyő aljára, és koppintson a "Szakasz hozzáadása" lehetőségre kiegészítők, például Nyelvek, Tanúsítványok vagy Önkéntes munka felvételéhez. A szakasz eltávolításához koppintson a szakasz fejlécére, és válassza az "Eltávolítás" lehetőséget.',
  'faq_q6'  : 'Hogyan rendezhetek át szakaszokat?',
  'faq_a6'  : 'Nyomja hosszan a húzófogantyút (≡) bármely szakasz fejléce mellett, és húzza a kívánt pozícióba. A változtatások automatikusan mentésre kerülnek.',
  'faq_q7'  : 'Hogyan exportálhatom az önéletrajzomat PDF-ként?',
  'faq_a7'  : 'Nyissa meg az önéletrajzát, és koppintson az exportálás gombra (megosztás ikon) a jobb felső sarokban. Válassza az "Exportálás PDF-ként" lehetőséget. Ezután mentheti az eszközre, megoszthatja e-mailben, WhatsAppon, vagy közvetlenül feltöltheti az állásbörzékre.',
  'faq_q8'  : 'Milyen fájlformátumok támogatottak?',
  'faq_a8'  : 'Jelenleg az alkalmazás támogatja az önéletrajz exportálását kiváló minőségű PDF-ként. További formátumok is bekerülhetnek a jövőbeli frissítésekbe.',
  'faq_q9'  : 'Hol tárolódnak az önéletrajzom adatai?',
  'faq_a9'  : 'Az önéletrajz összes adata helyileg tárolódik az eszközön. Nem töltjük fel személyes adatait a szervereinkre. Ez azt jelenti, hogy adatai privátok maradnak és offline elérhetők.',
  'faq_q10' : 'Hogyan készíthetek biztonsági másolatot az önéletrajzaimról?',
  'faq_a10' : 'Az önéletrajzai bekerülnek az eszköze szokásos biztonsági mentésébe (Google Drive biztonsági mentés Androidon, iCloud iOS-en), ha a biztonsági mentés engedélyezve van az eszközbeállításokban. Az egyes önéletrajzokat PDF-ként is exportálhatja másolat megőrzéséhez.',
  'faq_q11' : 'Az alkalmazás lassan fut. Mit tegyek?',
  'faq_a11' : 'Próbálja meg bezárni és újra megnyitni az alkalmazást. Ha a probléma továbbra is fennáll, indítsa újra az eszközt. Győződjön meg arról, hogy az alkalmazás legújabb verziója van telepítve a Play Store-ból / App Store-ból.',
  'faq_q12' : 'Az önéletrajzom nem exportálódik megfelelően. Mit tegyek?',
  'faq_a12' : 'Győződjön meg arról, hogy elegendő tárhely áll rendelkezésre az eszközön. Próbálja meg csökkenteni a nagy képeket az önéletrajzában. Ha a probléma folytatódik, kérjük, lépjen kapcsolatba a támogatói csapatunkkal.',
  'faq_q13' : 'Elfelejtettem menteni — elveszett a munkám?',
  'faq_a13' : 'Egyáltalán nem! Az alkalmazás folyamatosan menti a haladást szerkesztés közben.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'Az Ön karrierje, tökéletesítve',
  'header_tooltip_back'                 : 'Vissza',
  'header_tooltip_my_cvs'               : 'Önéletrajzaim',
  'header_tooltip_settings'             : 'Beállítások',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'Önéletrajzaim',
  'saved_count_single'                  : '{n} dokumentum',
  'saved_count_plural'                  : '{n} dokumentum',
  'saved_limit_reached'                 : 'Elérte a korlátot',
  'saved_footer_count'                  : '{n} / 30 önéletrajz',
  'saved_filter_all'                    : 'Összes',
  'saved_filter_draft'                  : 'Vázlat',
  'saved_filter_complete'               : 'Kész',
  'saved_status_complete'               : 'Kész',
  'saved_status_saved'                  : 'Mentve',
  'saved_status_draft'                  : 'Vázlat',
  'saved_empty_title'                   : 'Még nincsenek önéletrajzok',
  'saved_empty_sub'                     : 'Kezdje el az első önéletrajzát fent',
  'saved_search_empty_title'            : 'Nem találhatók eredmények',
  'saved_search_empty_sub'              : 'Próbáljon más keresési kifejezést',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'Színséma',
  'custom_font_settings_title'          : 'Betűtípus-beállítások',
  'custom_font_family_label'            : 'Betűcsalád',
  'custom_font_size_label'              : 'Betűméret: ',
  'custom_current_template_title'       : 'Jelenlegi sablon',
  'custom_change_template_btn'          : 'Sablon módosítása',
  'custom_tpl_modern'                   : 'Modern',
  'custom_tpl_classic'                  : 'Klasszikus',
  'custom_tpl_professional'             : 'Professzionális',
  'custom_tpl_creative'                 : 'Kreatív',
  'custom_tpl_minimal'                  : 'Minimális',
  'custom_tpl_modern_desc'              : 'Tiszta és kortárs dizájn',
  'custom_tpl_classic_desc'             : 'Hagyományos professzionális elrendezés',
  'custom_tpl_professional_desc'        : 'Üzleti fókuszú sablon',
  'custom_tpl_creative_desc'            : 'Tűnjön ki egyedi dizájnnal',
  'custom_tpl_minimal_desc'             : 'Egyszerű és elegáns stílus',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'Sablon kiválasztása',
  'swipe_photo_badge'                   : 'Fotó',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Vezető',
  'tpl_nordic_name'                     : 'Északi',
  'tpl_vibrant_name'                    : 'Élénk',
  'tpl_tech_dark_name'                  : 'Tech sötét',
  'tpl_luxury_name'                     : 'Luxus',
  'tpl_executive_tag'                   : 'Legnépszerűbb',
  'tpl_nordic_tag'                      : 'Letisztult',
  'tpl_vibrant_tag'                     : 'Kreatív',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elit',
  'tpl_executive_desc'                  : 'Határozott és tekintélyes vezető pozíciókhoz',
  'tpl_nordic_desc'                     : 'Minimális tisztaság, amelyet a legjobb cégek megbíznak',
  'tpl_vibrant_desc'                    : 'Tűnjön ki energiával és színekkel',
  'tpl_tech_dark_desc'                  : 'Terminál esztétika fejlesztőknek',
  'tpl_luxury_desc'                     : 'Arany akcentusú presztízs fekete alapon',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'Sablon',
  'detail_step_personal'                : 'Személyes',
  'detail_step_experience'              : 'Tapasztalat',
  'detail_step_education'               : 'Végzettség',
  'detail_step_skills'                  : 'Készségek',
  'detail_step_additional'              : 'Egyéb',
  'detail_step_references'              : 'Referenciák',
  'detail_step_customize'               : 'Testreszabás',
  'detail_banner_heading'               : 'Majdnem kész!',
  'detail_banner_btn'                   : 'Folytatás',
  'detail_banner_completion_label'      : 'Kitöltöttség',
  'detail_stat_created_label'           : 'Létrehozva',
  'detail_stat_steps_label'             : 'Elvégzett lépések',
  'detail_section_template_style'       : 'Sablon stílusa',
  'detail_section_steps'                : 'Lépések',
  'detail_steps_counter'                : '{done} / {total} elvégezve',
  'detail_step_sub'                     : '{n}. lépés / {total}',
  'detail_section_activity'             : 'Tevékenység',
  'detail_activity_created'             : 'Létrehozva',
  'detail_activity_last_edited'         : 'Utoljára szerkesztve',
  'detail_activity_template'            : 'Sablon',
  'detail_btn_continue_editing'         : 'Szerkesztés folytatása',
  'detail_btn_edit_cv'                  : 'Önéletrajz szerkesztése',
  'detail_option_rename'                : 'Önéletrajz átnevezése',
  'detail_option_delete'                : 'Önéletrajz törlése',
  'detail_rename_title'                 : 'Önéletrajz átnevezése',
  'detail_rename_hint'                  : 'pl. Szoftvermérnök önéletrajz',
  'detail_rename_error_empty'           : 'A név nem lehet üres',
  'detail_rename_btn_cancel'            : 'Mégse',
  'detail_rename_btn_save'              : 'Mentés',
  'detail_rename_snackbar'              : 'Átnevezve erre: "{name}"',
  'detail_delete_title'                 : 'Törli az önéletrajzot?',
  'detail_delete_body'                  : 'Ez véglegesen törli a(z) "{name}" önéletrajzot. Ez a művelet nem vonható vissza.',
  'detail_delete_btn_cancel'            : 'Mégse',
  'detail_delete_btn_confirm'           : 'Törlés',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'Kész',
  'detail_check_tile_incomplete'        : 'Még nincs kitöltve',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'Válassza ki a sablonját',
  'chooser_subtitle'                    : 'Húzza a böngészéshez  ·  Koppintson a kiválasztáshoz  ·  Tartsa az előnézethez',
  'chooser_card_hold_hint'              : 'Tartsa az előnézethez',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'Kiválasztva',
  'chooser_modal_heading'               : 'Nevezze el az önéletrajzát',
  'chooser_modal_sub'                   : 'Adjon nevet, hogy könnyen megtalálja az Önéletrajzaimnál és az Előzményeknél.',
  'chooser_modal_field_label'           : 'Önéletrajz neve',
  'chooser_modal_save_btn'              : 'Mentés és kezdés',
  'chooser_modal_divider'               : 'vagy folytasson egy meglévő önéletrajzot',
  'chooser_nav_selected_sub'            : 'Kiválasztott sablon',
  'chooser_nav_cta'                     : 'Mentés és folytatás',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'Elérte a bejegyzések maximális számát',
  'editor_show_hide'                    : 'Megjelenítés/Elrejtés',
  'editor_editing_badge'                : 'Szerkesztés alatt',
  'editor_field_required'               : 'Kötelező',
  'editor_tooltip_edit'                 : 'Szerkesztés',
  'editor_tooltip_delete'               : 'Törlés',
  'editor_date_start'                   : 'Kezdési dátum *',
  'editor_date_end'                     : 'Befejezési dátum *',
  'editor_date_tap_hint'                : 'Koppintson a kiválasztáshoz',
  'editor_date_dialog_title'            : 'Hónap és év kiválasztása',
  'editor_date_confirm'                 : 'Megerősítés',
  'editor_panel_hide'                   : 'Elrejtés',
  'editor_panel_show'                   : 'Megjelenítés',
  'editor_validator_max_chars'          : 'Maximum {n} karakter',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'Önéletrajz készítése',
  'editor_header_step_sub'              : '{current}. lépés / {total} · {label}',
  'editor_step_template'                : 'Sablon',
  'editor_step_personal'                : 'Személyes',
  'editor_step_experience'              : 'Tapasztalat',
  'editor_step_education'               : 'Végzettség',
  'editor_step_skills'                  : 'Készségek',
  'editor_step_additional'              : 'Egyéb',
  'editor_step_references'              : 'Referenciák',
  'editor_step_customize'               : 'Testreszabás',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'Testreszabás',
  'customize_subtitle'                  : 'Tegye az önéletrajzát egyedivé',
  'customize_smart_layout_btn'          : 'Okos elrendezés',
  'customize_back_to_top'               : 'Vissza a tetejére',
  'customize_done_title'                : 'Minden készen áll!',
  'customize_done_sub'                  : 'Koppintson az Önéletrajz előnézete gombra lent, hogy megtekintse a kész önéletrajzát',
  'customize_preview_btn'               : 'Önéletrajz előnézete',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'Színséma',
  'color_black'                         : 'Fekete',
  'color_blue'                          : 'Kék',
  'color_nordic_blue'                   : 'Északi kék',
  'color_indigo'                        : 'Indigó',
  'color_teal'                          : 'Zöldeskék',
  'color_green'                         : 'Zöld',
  'color_purple'                        : 'Lila',
  'color_orange'                        : 'Narancssárga',
  'color_red'                           : 'Piros',
  'color_executive_gold'                : 'Vezető arany',
  'color_vibrant_coral'                 : 'Élénk korall',
  'color_white'                         : 'Fehér',
  'color_white_bg'                      : 'Fehér háttér',
  'color_maroon'                        : 'Gesztenyebarna',
  'color_brutalist_yellow'              : 'Brutalista sárga',
  'color_neon_blue'                     : 'Neonkék',
  'color_blueprint_navy'                : 'Terv tengerészkék',
  'color_light_grey'                    : 'Világosszürke',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'Betűcsalád',
  'customize_font_picker_title'         : 'Betűtípus kiválasztása',
  'customize_font_picker_sub'           : 'Minden betűtípus saját írásképével jelenik meg az előnézetben',
  'customize_font_preview_sample'       : 'A gyors barna róka',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'Betűméret',
  'customize_font_size_label'           : 'Szövegméret',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'Képméret',
  'customize_image_size_label'          : 'Képméret',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'Élő előnézet',
  'preview_page_count_singular'         : '1 oldal',
  'preview_page_count_plural'           : '{n} oldal',
  'preview_page_of'                     : '{page}. oldal / {total}',
  'preview_live_hint'                   : 'A változások azonnal érvényesülnek',
  'preview_template_unregistered'       : 'Még nincs regisztrálva a customize_preview.dart fájlban',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'Az önéletrajz előkészítése…',
  'preview_bar_print'                   : 'Nyomtatás',
  'preview_bar_save_pdf'                : 'Mentés PDF-ként',
  'preview_bar_share'                   : 'Megosztás',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'Önéletrajz előnézete',
  'preview_screen_sub'                  : '{n} {unit} · pontosan ahogy kinyomtatva',
  'preview_page_singular'               : 'oldal',
  'preview_page_plural'                 : 'oldal',
  'preview_pdf_filename'                : 'Oneletrajzom',
  'preview_share_subject'               : 'Önéletrajzom',
  'preview_snack_print_failed'          : 'Nyomtatás sikertelen: {e}',
  'preview_snack_saved'                 : 'Önéletrajz mentve a Letöltések mappába ✓',
  'preview_snack_export_failed'         : 'Exportálás sikertelen: {e}',
  'preview_snack_share_failed'          : 'Megosztás sikertelen: {e}',
  'preview_template_not_registered'     : 'A sablon nincs regisztrálva',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'Előnézet bezárása',
  'preview_modal_hint_photo'            : 'Profilfotót támogat  ·  Koppintson egy kártyára a kiválasztáshoz',
  'preview_modal_hint_no_photo'         : 'Koppintson egy sablonkártyára a kiválasztáshoz',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'Önéletrajzom',
  'time_just_now'                       : 'Épp most',
  'time_minutes_ago'                    : '{n} perce',
  'time_hours_ago'                      : '{n} órája',
  'time_yesterday'                      : 'Tegnap',
  'time_days_ago'                       : '{n} napja',
  'time_one_week_ago'                   : '1 hete',
  'time_weeks_ago'                      : '{n} hete',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'Elegáns',
  'tpl_tag_classic'                     : 'Klasszikus',
  'tpl_tag_minimal'                     : 'Minimális',
  'tpl_tag_creative'                    : 'Kreatív',
  'tpl_tag_bold'                        : 'Merész',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────

  // ID 6 · Gradient
  'tpl_gradient_name'                   : 'Gradiens',
  'tpl_gradient_desc'                   : 'Zöldeskéktől ibolyáig gradiens kártyák',

  // ID 7 · Editorial
  'tpl_editorial_name'                  : 'Szerkesztőségi',
  'tpl_editorial_desc'                  : 'Folyóirat stílusú piros és krém',

  // ID 8 · Pastel Soft
  'tpl_pastel_soft_name'                : 'Pasztell lágy',
  'tpl_pastel_soft_desc'                : 'Levendula oldalsáv, lágy kártyák',

  // ID 9 · Brutalist
  'tpl_brutalist_name'                  : 'Brutalista',
  'tpl_brutalist_desc'                  : 'Nyers rács, merész szegélyek és sárga',

  // ID 10 · Emerald
  'tpl_emerald_name'                    : 'Smaragd',
  'tpl_emerald_desc'                    : 'Erdőzöld idővonallal',

  // ID 11 · Infographic
  'tpl_infographic_name'                : 'Infografika',
  'tpl_infographic_desc'                : 'Sötét vászon gyűrűs diagramokkal',

  // ID 12 · Art Deco
  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : '1920-as évek geometrikus arany luxusa',

  // ID 13 · Wina Dark
  'tpl_wina_dark_name'                  : 'Wina sötét',
  'tpl_wina_dark_desc'                  : 'Sötét infografika gyűrűkkel',

  // ID 14 · Rio Orange
  'tpl_rio_orange_name'                 : 'Rio narancs',
  'tpl_rio_orange_desc'                 : 'Sötét oldalsáv narancssárga akcentussal',

  // ID 15 · Summer
  'tpl_summer_name'                     : 'Nyár',
  'tpl_summer_desc'                     : 'Tiszta minimális, lágy szürke tónusok',

  // ID 16 · Helene
  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'Meleg bézs elegáns tónusok',

  // ID 17 · Canfield
  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'Éles fekete-fehér klasszikus',

  // ID 18 · Collins
  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'Klasszikus ATS-barát elrendezés',

  // ID 19 · Tony Dark
  'tpl_tony_dark_name'                  : 'Tony sötét',
  'tpl_tony_dark_desc'                  : 'Sötét narancssárga infografika stílus',

  // ID 20 · Fashion (Blueprint)
  'tpl_fashion_name'                    : 'Divat',
  'tpl_fashion_desc'                    : 'Műszaki rajz rácson',

  // ID 21 · Archivist
  'tpl_archivist_name'                  : 'Levéltáros',
  'tpl_archivist_desc'                  : 'Klasszikus kétoszlopos elrendezés',

  // ID 22 · Diplomat
  'tpl_diplomat_name'                   : 'Diplomata',
  'tpl_diplomat_desc'                   : 'Árnyékolt fejlécek gyémánt jelölőkkel',

  // ID 23 · Meridian
  'tpl_meridian_name'                   : 'Meridián',
  'tpl_meridian_desc'                   : 'Középre igazított fejlécek, kiemelt cégek',

  // ID 24 · Momentum
  'tpl_momentum_name'                   : 'Lendület',
  'tpl_momentum_desc'                   : 'Merész név, idővonal pontok és teljesítmények',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'Személyes adatok',
  'personal_subtitle'                   : 'Mutatkozzon be a munkáltatóknak',
  'personal_profile_counter'            : '{n}/{max} profil',
  'personal_info_banner'                : 'Mentsen el akár 5 profilt, és válasszon egyet önéletrajzonként. A kiválasztást minden önéletrajznál külön-külön megjegyzi a rendszer.',
  'personal_snack_max'                  : 'Elérte a maximum {n} profilt.',
  'personal_add_btn'                    : 'Új profil hozzáadása',
  'personal_library_title'              : 'Mentett profilok',
  'personal_selected_one'               : '1 kiválasztva',
  'personal_selected_none'              : 'nincs kiválasztva',
  'personal_library_hint'               : 'Koppintson egy kártyára, hogy csak ehhez az önéletrajzhoz válassza ki. A többi önéletrajz megőrzi saját kiválasztásait.',
  'personal_empty_message'              : 'Még nincsenek mentett profilok',
  'personal_empty_sub'                  : 'Koppintson fent személyes adatai hozzáadásához',
  'personal_nav_next'                   : 'Mentés és folytatás',
  'personal_card_active_badge'          : 'Aktív ennél az önéletrajznál',
  'personal_sheet_title_add'            : 'Új profil',
  'personal_sheet_title_edit'           : 'Profil szerkesztése',
  'personal_sheet_brutalist_badge'      : 'BRUTALISTA',
  'personal_sheet_brutalist_banner'     : 'A brutalista sablonnak kompakt elérhetőségi mezői vannak. A rövidebb értékek (pl. csak a város) a legjobban jelennek meg.',
  'personal_section_photo'              : 'Profilfotó',
  'personal_section_basic'              : 'Alapadatok',
  'personal_section_contact'            : 'Elérhetőség',
  'personal_section_online'             : 'Online jelenlét',
  'personal_section_summary'            : 'Szakmai összefoglaló',
  'personal_field_first_name'           : 'Keresztnév *',
  'personal_field_last_name'            : 'Vezetéknév',
  'personal_field_job_title'            : 'Pozíció *',
  'personal_field_email'                : 'E-mail cím *',
  'personal_field_phone'                : 'Telefonszám *',
  'personal_field_location'             : 'Helyszín',
  'personal_field_location_brut'        : 'Helyszín (csak város)',
  'personal_field_website'              : 'Weboldal / Portfólió',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'pl. Péter',
  'personal_hint_last_name'             : 'pl. Nagy',
  'personal_hint_job_title'             : 'pl. Senior mérnök',
  'personal_hint_email'                 : 'pl. peter@pelda.hu',
  'personal_hint_phone'                 : 'pl. +36 20 123 4567',
  'personal_hint_location'              : 'pl. Budapest, Magyarország',
  'personal_hint_location_brut'         : 'pl. Budapest',
  'personal_hint_website'               : 'pl. github.com/nagypeter',
  'personal_hint_website_brut'          : 'pl. github.com/peter',
  'personal_hint_linkedin'              : 'pl. linkedin.com/in/nagypeter',
  'personal_hint_linkedin_brut'         : 'pl. linkedin.com/in/peter',
  'personal_summary_hint_label'         : 'Legyen tömör — ez jelenik meg az önéletrajza tetején.',
  'personal_hint_summary'               : 'Rövid, 2–3 mondatos összefoglaló a hátteréről és céljairól...',
  'personal_validator_email'            : 'Adjon meg érvényes e-mail címet',
  'personal_field_char_limit_tooltip'   : 'Elérte a karakterkorlátot',
  'personal_sheet_btn_save'             : 'Profil mentése',
  'personal_sheet_btn_update'           : 'Változtatások mentése',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'Fotó kiválasztása',
  'photo_option_gallery'                : 'Kiválasztás a galériából',
  'photo_option_camera'                 : 'Fotó készítése',
  'photo_option_reposition'             : 'Fotó áthelyezése',
  'photo_option_remove'                 : 'Fotó eltávolítása',
  'photo_status_added'                  : 'Fotó hozzáadva ✓',
  'photo_status_empty'                  : 'Adjon hozzá professzionális fotót',
  'photo_chip_gallery'                  : 'Galéria',
  'photo_chip_camera'                   : 'Kamera',
  'photo_chip_reposition'               : 'Áthelyezés',
  'photo_reposition_title'              : 'Fotó áthelyezése',
  'photo_reposition_sub'                : 'Húzza a fotót a pozíció beállításához',
  'photo_reposition_reset'              : 'Visszaállítás középre',
  'photo_reposition_apply'              : 'Alkalmaz',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'Készségek',
  'skills_subtitle'                     : 'Emelje ki kulcskészségeit',
  'skills_add_btn'                      : 'Új készség hozzáadása',
  'skills_snack_max_icons'              : 'Maximum 10 ikon kiválasztva.',
  'skills_snack_max_skills'             : 'Elérte a maximum 15 készséget.',
  'skills_library_title'                : 'Mentett készségek',
  'skills_library_hint'                 : 'A bejelölt készségek bekerülnek ebbe az önéletrajzba. A kiválasztásai automatikusan mentésre kerülnek.',
  'skills_nav_next'                     : 'Folytatás az egyébhez',
  'skills_wina_header_icon_bar'         : 'Fejléc ikonsáv',
  'skills_wina_on'                      : 'BE',
  'skills_wina_off'                     : 'KI',
  'skills_wina_bar_on_sub'              : 'Színes ikonkörök láthatók az önéletrajz fejlécében.',
  'skills_wina_bar_off_sub'             : 'Ikonsor elrejtve — több hely az elérhetőségi adatoknak.',
  'skills_wina_palette_hint'            : 'Az ikonok palettarendben jelennek meg színes körökként.',
  'skills_wina_preview_label'           : 'Előnézet',
  'skills_wina_disabled_hint'           : 'Engedélyezze a fenti ikonsávot, hogy kiválassza, mely ikonok jelenjenek meg az önéletrajz fejlécében.',
  'skills_sheet_title_add'              : 'Készség hozzáadása',
  'skills_sheet_title_edit'             : 'Készség szerkesztése',
  'skills_sheet_field_name'             : 'Készség neve *',
  'skills_sheet_hint_short'             : 'pl. Flutter, Dizájn',
  'skills_sheet_hint_long'              : 'pl. Flutter, Projektmenedzsment',
  'skills_sheet_validator_max'          : 'Max. {n} karakter',
  'skills_sheet_proficiency'            : 'Tudásszint',
  'skills_sheet_beginner'               : 'Kezdő',
  'skills_sheet_expert'                 : 'Szakértő',
  'skills_sheet_btn_save'               : 'Készség mentése',
  'skills_sheet_btn_update'             : 'Készség frissítése',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'Személyes referenciák',
  'refs_subtitle'                       : 'Személyek, akik személyesen ajánlani tudják Önt',
  'refs_add_btn'                        : 'Új személyes referencia hozzáadása',
  'refs_snack_max_selected'             : 'Önéletrajzonként maximum 4 referencia választható ki.',
  'refs_snack_max_saved'                : 'Elérte a maximum 10 mentett referenciát.',
  'refs_library_title'                  : 'Mentett referenciák',
  'refs_library_hint'                   : 'A bejelölt referenciák bekerülnek ebbe az önéletrajzba. Maximum 4 önéletrajzonként. A kiválasztásai automatikusan mentésre kerülnek.',
  'refs_nav_next'                       : 'Folytatás a testreszabáshoz',
  'refs_sheet_title_add'                : 'Személyes referencia hozzáadása',
  'refs_sheet_title_edit'               : 'Személyes referencia szerkesztése',
  'refs_sheet_sub_add'                  : 'Valaki, aki személyesen tudja ajánlani Önt a munkáltatóknak.',
  'refs_sheet_sub_edit'                 : 'Frissítse az alábbi referencia adatait.',
  'refs_sheet_field_name'               : 'Teljes név *',
  'refs_sheet_field_title'              : 'Pozíció *',
  'refs_sheet_field_company'            : 'Cég (opcionális)',
  'refs_sheet_field_email'              : 'E-mail cím *',
  'refs_sheet_field_phone'              : 'Telefonszám *',
  'refs_sheet_hint_name'                : 'pl. Kovács János',
  'refs_sheet_hint_title'               : 'pl. Mérnöki vezető',
  'refs_sheet_hint_company'             : 'pl. Acme Kft.',
  'refs_sheet_hint_email'               : 'pl. kovacs@acme.hu',
  'refs_sheet_hint_phone'               : 'pl. +36 20 123 4567',
  'refs_sheet_validator_email'          : 'Adjon meg érvényes e-mail címet',
  'refs_sheet_btn_save'                 : 'Személyes referencia mentése',
  'refs_sheet_btn_update'               : 'Személyes referencia frissítése',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'Munkatapasztalat',
  'exp_subtitle'                        : 'Adja hozzá munkaelőzményeit',
  'exp_banner_info'                     : 'Pozíciónként legfeljebb {n} felelősség jelenik meg az önéletrajzon. 3–6 pozíció általában elfér 1–2 oldalon.',
  'exp_add_btn'                         : 'Új tapasztalat hozzáadása',
  'exp_snack_max_selected'              : 'Önéletrajzonként maximum 8 tapasztalat választható ki.',
  'exp_snack_max_saved'                 : 'Elérte a maximum 12 mentett tapasztalatot.',
  'exp_library_title'                   : 'Mentett tapasztalatok',
  'exp_library_hint'                    : 'A bejelölt bejegyzések csak ebbe az önéletrajzba kerülnek bele. A többi önéletrajz megőrzi saját kiválasztásait.',
  'exp_nav_next'                        : 'Folytatás a végzettséghez',
  'exp_empty_message'                   : 'Még nincs hozzáadott tapasztalat',
  'exp_empty_sub'                       : 'Koppintson fent az első pozíciója hozzáadásához',
  'exp_card_resp_singular'              : 'felelősség',
  'exp_card_resp_plural'                : 'felelősség',
  'exp_card_resp_tooltip'               : 'Csak az első 8 felelősség jelenik meg az önéletrajzon',
  'exp_sheet_title_add'                 : 'Tapasztalat hozzáadása',
  'exp_sheet_title_edit'                : 'Tapasztalat szerkesztése',
  'exp_sheet_field_job_title'           : 'Pozíció *',
  'exp_sheet_field_company'             : 'Cég *',
  'exp_sheet_field_location'            : 'Helyszín',
  'exp_sheet_section_responsibilities'  : 'Főbb felelősségek',
  'exp_sheet_resp_hint_info'            : 'Max. 8 felsorolás · 200 karakter egyenként',
  'exp_sheet_resp_label'                : '{n}. felelősség',
  'exp_sheet_resp_hint'                 : 'pl. 5 fős mérnöki csapatot vezetett',
  'exp_sheet_resp_add_btn'              : 'Felelősség hozzáadása',
  'exp_sheet_resp_max_info'             : 'Elérte a maximum {n} felelősséget',
  'exp_sheet_resp_validator_max'        : 'Max. 200 karakter',
  'exp_sheet_hint_job_title'            : 'pl. Senior fejlesztő',
  'exp_sheet_hint_location'             : 'pl. Budapest, Magyarország',
  'exp_sheet_btn_save'                  : 'Tapasztalat mentése',
  'exp_sheet_btn_update'                : 'Változtatások mentése',
  'exp_date_present'                    : 'Jelenlegi / Aktuális pozíció',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'Végzettség',
  'edu_subtitle'                        : 'Adja hozzá tanulmányi hátterét',
  'edu_add_btn'                         : 'Új végzettség hozzáadása',
  'edu_snack_max_selected'              : 'Önéletrajzonként maximum 8 végzettségi bejegyzés választható ki.',
  'edu_snack_max_saved'                 : 'Elérte a maximum 12 mentett végzettségi bejegyzést.',
  'edu_library_title'                   : 'Mentett végzettségek',
  'edu_library_hint'                    : 'A bejelölt bejegyzések bekerülnek ebbe az önéletrajzba. A kiválasztásai automatikusan mentésre kerülnek.',
  'edu_nav_next'                        : 'Folytatás a készségekhez',
  'edu_empty_message'                   : 'Még nincs hozzáadott végzettség',
  'edu_empty_sub'                       : 'Koppintson fent képesítéseinek hozzáadásához',
  'edu_card_bullet_singular'            : 'felsorolás',
  'edu_card_bullet_plural'              : 'felsorolás',
  'edu_sheet_title_add'                 : 'Végzettség hozzáadása',
  'edu_sheet_title_edit'                : 'Végzettség szerkesztése',
  'edu_sheet_field_degree'              : 'Fokozat / Képesítés *',
  'edu_sheet_field_institution'         : 'Intézmény *',
  'edu_sheet_section_key_points'        : 'Kulcspontok',
  'edu_sheet_key_points_hint_info'      : 'Opcionális · 1 felsorolás · max. 100 karakter',
  'edu_sheet_point_label'               : '{n}. pont',
  'edu_sheet_point_add_btn'             : 'Felsorolás hozzáadása',
  'edu_sheet_point_max_info'            : 'Elérte a maximum {n} felsorolást',
  'edu_sheet_point_validator_max'       : 'Max. {n} karakter',
  'edu_sheet_hint_degree'               : 'pl. BSc informatika',
  'edu_sheet_hint_institution'          : 'pl. Budapesti Műszaki Egyetem',
  'edu_sheet_hint_bullet'               : 'pl. Kitüntetéses diploma',
  'edu_sheet_btn_save'                  : 'Végzettség mentése',
  'edu_sheet_btn_update'                : 'Változtatások mentése',
  'edu_date_present'                    : 'Jelenlegi / Folyamatban lévő tanulmányok',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'Egyéb adatok',
  'additional_subtitle'                 : 'Tanúsítványok, nyelvek és más',
  'additional_cert_section_title'       : 'Tanúsítványok',
  'additional_cert_counter'             : '{sel}/{total} kiválasztva · max. {max}',
  'additional_cert_hide'                : 'Elrejtés',
  'additional_cert_show'                : 'Megjelenítés',
  'additional_cert_add_btn'             : 'Hozzáadás',
  'additional_cert_snack_max'           : 'Elérte a maximum {n} tanúsítványt.',
  'additional_cert_hint'                : 'A bejelölt bejegyzések bekerülnek ebbe az önéletrajzba. A kiválasztásai automatikusan mentésre kerülnek.',
  'additional_cert_empty'               : 'Még nincsenek tanúsítványok hozzáadva',
  'additional_lang_section_title'       : 'Nyelvek',
  'additional_lang_add_hint'            : 'pl. Angol',
  'additional_lang_snack_max'           : 'Elérte a maximum {n} nyelvet.',
  'additional_lang_empty'               : 'Még nincsenek nyelvek hozzáadva',
  'additional_hobby_section_title'      : 'Hobbik és érdeklődési körök',
  'additional_hobby_add_hint'           : 'pl. Fényképezés',
  'additional_hobby_snack_max'          : 'Elérte a maximum {n} hobbit.',
  'additional_hobby_empty'              : 'Még nincsenek hobbik hozzáadva',
  'additional_section_hint'             : 'A bejelölt bejegyzések bekerülnek ebbe az önéletrajzba. A kiválasztásai automatikusan mentésre kerülnek.',
  'additional_nav_next'                 : 'Folytatás a referenciákhoz',
  'cert_sheet_title_add'                : 'Tanúsítvány hozzáadása',
  'cert_sheet_title_edit'               : 'Tanúsítvány szerkesztése',
  'cert_sheet_sub'                      : 'Adjon hozzá képesítést, tanúsítványt vagy szakmai akkreditációt.',
  'cert_sheet_field_name'               : 'Tanúsítvány neve *',
  'cert_sheet_field_issued_by'          : 'Kibocsátó (opcionális)',
  'cert_sheet_field_short_desc'         : 'Rövid leírás (opcionális)',
  'cert_sheet_hint_name'                : 'pl. AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'pl. Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'pl. Megszerezte: 2024',
  'cert_sheet_btn_save'                 : 'Tanúsítvány mentése',
  'cert_sheet_btn_update'               : 'Tanúsítvány frissítése',
  'simple_sheet_title_add_language'     : 'Nyelv hozzáadása',
  'simple_sheet_title_edit_language'    : 'Nyelv szerkesztése',
  'simple_sheet_title_add_hobby'        : 'Hobby hozzáadása',
  'simple_sheet_title_edit_hobby'       : 'Hobby szerkesztése',
  'simple_sheet_btn_save'               : 'Mentés',
  'simple_sheet_btn_update'             : 'Frissítés',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'Elérhetőség',
  'pdf_section_about_me'                : 'Rólam',
  'pdf_section_summary'                 : 'Összefoglaló',
  'pdf_section_summary_short'           : 'Összefoglaló',
  'pdf_section_profile'                 : 'Profil',
  'pdf_section_experience'              : 'Tapasztalat',
  'pdf_section_experience_short'        : 'Tapasztalat',
  'pdf_section_education'               : 'Végzettség',
  'pdf_section_skills'                  : 'Készségek',
  'pdf_section_languages'               : 'Nyelvek',
  'pdf_label_email'                     : 'E-mail',
  'pdf_label_phone'                     : 'Telefon',
  'pdf_label_location'                  : 'Helyszín',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'Elérte a CV-korlátot',
  'limit_dialog_body'                   : 'Elérte a maximális 30 önéletrajzot. Új létrehozása előtt töröljön egy meglévőt.',
  'limit_dialog_go_to_my_cvs'           : 'Saját önéletrajzaimhoz',
  'limit_dialog_cancel'                 : 'Mégse',
  'refs_count_summary'                  : '{checked}/{maxChecked} kiválasztva · {saved}/{maxSaved} mentve',
  'refs_selected_badge'                 : '{n} kiválasztva',
  'refs_empty_message'                  : 'Még nincsenek mentett referenciák',
  'refs_empty_sub'                      : 'Koppintson fentebb személyes referencia hozzáadásához',
};