// lib/language_keys/lang_th_thai.dart
//
// Thai (ภาษาไทย) translation map.
// All user-visible strings from:
//   • language_ui_select.dart        • onboarding_flow.dart
//   • onboarding_screen_1–4.dart     • home_screen.dart
//   • history_screen.dart            • settings_screen.dart
//   • preview_screen.dart            • help_faq_screen.dart
//   • very_top_header.dart           • saved_cv_containers.dart
//   • customization_panel.dart       • swipable_cv_templates.dart
//   • template_data.dart             • saved_cv_detail_screen.dart
//   • cv_detail_widgets.dart         • step_template_chooser.dart
//   • step_skills.dart               • step_personal_reference.dart
//   • step_experience.dart           • step_education.dart
//   • step_additional.dart           • editor_screen.dart
//   • cv_edit_widgets.dart           • step_customize.dart
//   • smart_layout_option.dart       • step_personal_info.dart
//   • profile_photo_widget.dart      • customize_size_section.dart
//   • custom_image_sizer.dart        • customize_font_section.dart
//   • customize_color_section.dart   • customize_preview.dart
//   • cv_preview_bottom_bar.dart     • cv_full_preview_screen.dart
//   • preview_registry.dart          • template_full_preview_modal.dart

const Map<String, String> thThai = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'ไม่พบภาษา',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'ข้าม',
  'onboarding_next'                     : 'ถัดไป',
  'onboarding_get_started'              : 'เริ่มต้นใช้งาน',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  ยินดีต้อนรับ',
  'ob1_title'                           : 'สร้าง CV ที่\nเปิดประตูโอกาส',
  'ob1_body'                            : 'โดดเด่นกว่าผู้สมัครหลายร้อยคน สร้าง CV มืออาชีพในไม่กี่นาที — ไม่ต้องมีทักษะด้านการออกแบบ',
  'ob1_pill_label'                      : 'เครื่องมือสร้าง CV มืออาชีพ',
  'ob1_chip_templates'                  : '24+ แม่แบบ',
  'ob1_chip_pdf'                        : 'ส่งออก PDF',
  'ob1_chip_free'                       : 'ใช้งานฟรี',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  แม่แบบ',
  'ob2_title'                           : 'ทุกอุตสาหกรรม\nทุกความทะเยอทะยาน',
  'ob2_body'                            : 'จากเลย์เอาต์สำหรับห้องประชุมไปจนถึงดีไซน์สร้างสรรค์ — แม่แบบที่บอกเล่าเรื่องราวของคุณ',
  'ob2_tap_hint'                        : 'แตะแม่แบบเพื่อดูตัวอย่าง',
  'ob2_tpl_executive'                   : 'Executive',
  'ob2_tpl_vibrant'                     : 'Vibrant',
  'ob2_tpl_nordic'                      : 'Nordic',
  'ob2_tpl_tech_dark'                   : 'Tech Dark',
  'ob2_tpl_luxury'                      : 'Luxury',
  'ob2_tag_corporate'                   : 'องค์กร',
  'ob2_tag_creative'                    : 'สร้างสรรค์',
  'ob2_tag_minimal'                     : 'เรียบง่าย',
  'ob2_tag_modern'                      : 'ทันสมัย',
  'ob2_tag_premium'                     : 'พรีเมียม',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  Smart Layout',
  'ob3_title'                           : 'CV ของคุณ\nจัดวางอย่างสมบูรณ์แบบ',
  'ob3_body'                            : 'Smart Layout จัดเรียงส่วนต่างๆ ของคุณใหม่เพื่อผลกระทบสูงสุด — วางเนื้อหาที่แข็งแกร่งที่สุดของคุณในตำแหน่งที่ผู้รับสมัครมองก่อน',
  'ob3_badge_smart_layout'              : 'Smart Layout',
  'ob3_badge_cv_ready'                  : 'CV พร้อมแล้ว!',
  'ob3_step1_label'                     : 'เลือกแม่แบบ',
  'ob3_step1_desc'                      : 'เลือกจาก 24+ ดีไซน์สวยงาม',
  'ob3_step2_label'                     : 'กรอกข้อมูลของคุณ',
  'ob3_step2_desc'                      : 'ช่องกรอกข้อมูลแบบมีคำแนะนำสำหรับทุกส่วน',
  'ob3_step3_label'                     : 'Smart Layout',
  'ob3_step3_desc'                      : 'แตะครั้งเดียวจัด CV ได้อย่างสมบูรณ์แบบ',
  'ob3_step4_label'                     : 'ส่งออกเป็น PDF',
  'ob3_step4_desc'                      : 'PDF คุณภาพสูงพร้อมส่ง',
  'ob3_section_work'                    : 'ประสบการณ์การทำงาน',
  'ob3_section_education'               : 'การศึกษา',
  'ob3_section_skills'                  : 'ทักษะ',
  'ob3_section_references'              : 'ผู้อ้างอิง',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  พร้อมใช้งาน',
  'ob4_title'                           : 'ทำไมผู้สมัครชั้นนำ\nเลือก CV Builder',
  'ob4_visual_headline'                 : 'คุณพร้อมแล้ว!',
  'ob4_visual_subline'                  : 'ทุกสิ่งที่คุณต้องการเพื่อได้งาน',
  'ob4_stat_templates_value'            : '24+',
  'ob4_stat_templates_label'            : 'แม่แบบ',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'CV สูงสุด',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'ส่งออก',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'ส่วนตัว',
  'ob4_hl1_title'                       : 'ส่วนตัวและปลอดภัย',
  'ob4_hl1_sub'                         : 'ข้อมูลอยู่บนอุปกรณ์ของคุณ',
  'ob4_hl2_title'                       : 'บันทึกอัตโนมัติ',
  'ob4_hl2_sub'                         : 'บันทึกทุกการพิมพ์ทันที',
  'ob4_hl3_title'                       : 'สูงสุด 30 CV',
  'ob4_hl3_sub'                         : 'CV เฉพาะสำหรับทุกตำแหน่ง',
  'ob4_hl4_title'                       : 'แชร์ด้วยการแตะครั้งเดียว',
  'ob4_hl4_sub'                         : 'ส่ง PDF โดยไม่ต้องออกจากแอป',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ โดดเด่นกว่าคนอื่น',
  'home_hero_title'                     : 'สร้าง CV\nมืออาชีพของคุณ',
  'home_hero_sub'                       : 'สร้างเรซูเม่ที่สวยงาม\nในไม่กี่นาที',
  'home_hero_cta'                       : 'เริ่มสร้าง',
  'home_premium_soon'                   : 'อัปเกรดเป็น Pro เร็วๆ นี้!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'ล่าสุด',
  'history_sort_alphabetical'           : 'ก–ฮ',
  'history_sort_last_edited'            : 'แก้ไขล่าสุด',
  'history_sort_by_template'            : 'ตามแม่แบบ',
  'history_sort_sheet_title'            : 'เรียงตาม',
  'history_sort_alphabetical_full'      : 'เรียงตามตัวอักษร (ก–ฮ)',
  'history_premium_soon'                : 'อัปเกรดเป็น Pro เร็วๆ นี้!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'การตั้งค่า',
  'settings_section_preferences'        : 'การตั้งค่าส่วนตัว',
  'settings_section_support'            : 'ความช่วยเหลือ',
  'settings_section_legal'              : 'ข้อกฎหมาย',
  'settings_section_about'              : 'เกี่ยวกับ',
  'settings_language_tile_title'        : 'ภาษา',
  'settings_dark_mode_title'            : 'โหมดมืด',
  'settings_dark_mode_on'               : 'เปิดใช้ธีมสีเข้ม',
  'settings_dark_mode_off'              : 'เปิดใช้ธีมสีอ่อน',
  'settings_help_faq_title'             : 'ความช่วยเหลือและ FAQ',
  'settings_help_faq_sub'               : 'คำถามที่พบบ่อยได้รับการตอบแล้ว',
  'settings_contact_support_title'      : 'ติดต่อฝ่ายสนับสนุน',
  'settings_rate_app_title'             : 'ให้คะแนนแอป',
  'settings_rate_app_sub'               : 'ชอบแอปไหม? ฝากรีวิวด้วยนะ!',
  'settings_privacy_policy_title'       : 'นโยบายความเป็นส่วนตัว',
  'settings_terms_title'                : 'ข้อกำหนดการให้บริการ',
  'settings_app_version_title'          : 'เวอร์ชันแอป',
  'settings_email_error'                : 'ไม่สามารถเปิดแอปอีเมลได้ กรุณาส่งอีเมลมาที่ cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'ดูตัวอย่าง CV',
  'preview_header_sub'                  : 'พร้อมส่งออก',
  'preview_generating'                  : 'กำลังสร้าง CV ของคุณ...',
  'preview_failed_title'                : 'ดูตัวอย่างล้มเหลว',
  'preview_failed_error'                : 'ข้อผิดพลาด: {error}',
  'preview_go_back'                     : 'กลับ',
  'preview_no_data'                     : 'ไม่มีข้อมูล',
  'preview_btn_print'                   : 'พิมพ์',
  'preview_btn_download'                : 'ดาวน์โหลดและแชร์',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'ความช่วยเหลือและ FAQ',
  'faq_category_all'                    : 'ทั้งหมด',
  'faq_empty'                           : 'ไม่พบผลลัพธ์',
  'faq_contact_headline'                : 'ยังต้องการความช่วยเหลือ?',
  'faq_contact_sub'                     : 'ทีมงานของเราพร้อมช่วยเหลือคุณ',
  'faq_contact_btn'                     : 'ติดต่อ',
  'faq_email_error'                     : 'ไม่สามารถเปิดแอปอีเมลได้ กรุณาส่งอีเมลมาที่ cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'เริ่มต้นใช้งาน',
  'faq_cat_templates'                   : 'แม่แบบ',
  'faq_cat_editing'                     : 'การแก้ไข',
  'faq_cat_exporting'                   : 'การส่งออก',
  'faq_cat_data_privacy'                : 'ข้อมูลและความเป็นส่วนตัว',
  'faq_cat_troubleshooting'             : 'การแก้ปัญหา',
  'faq_q1'  : 'วิธีสร้าง CV แรกของฉันได้อย่างไร?',
  'faq_a1'  : 'แตะปุ่ม "+" บนหน้าจอหลักเพื่อเริ่ม CV ใหม่ เลือกแม่แบบที่เหมาะกับสไตล์ของคุณ จากนั้นกรอกข้อมูลส่วนตัว ประสบการณ์ทำงาน การศึกษา และทักษะทีละขั้นตอน ความคืบหน้าของคุณจะถูกบันทึกโดยอัตโนมัติ',
  'faq_q2'  : 'ฉันสามารถสร้าง CV มากกว่าหนึ่งฉบับได้ไหม?',
  'faq_a2'  : 'ได้เลย! คุณสามารถสร้าง CV หลายฉบับสำหรับตำแหน่งงานหรืออุตสาหกรรมต่างๆ CV แต่ละฉบับจะถูกบันทึกแยกกัน ดังนั้นคุณจึงสามารถปรับแต่งให้เหมาะกับการสมัครงานเฉพาะได้',
  'faq_q3'  : 'วิธีเปลี่ยนแม่แบบ CV ของฉันได้อย่างไร?',
  'faq_a3'  : 'เปิด CV ของคุณ แตะไอคอนแม่แบบที่ด้านบนของหน้าจอ และเรียกดูแม่แบบที่มีอยู่ แตะแม่แบบใดก็ได้เพื่อดูตัวอย่างพร้อมเนื้อหาที่มีอยู่ ยืนยันเพื่อนำไปใช้',
  'faq_q4'  : 'มีแม่แบบฟรีและพรีเมียมไหม?',
  'faq_a4'  : 'มี แม่แบบมืออาชีพบางส่วนมีให้ใช้งานฟรี แม่แบบพรีเมียมที่มีดีไซน์ขั้นสูงและจานสีต่างๆ สามารถซื้อแบบครั้งเดียวหรือสมัครสมาชิกได้',
  'faq_q5'  : 'วิธีเพิ่มหรือลบส่วนต่างๆ ได้อย่างไร?',
  'faq_a5'  : 'ในตัวแก้ไข CV เลื่อนลงไปที่ด้านล่างของหน้าจอและแตะ "เพิ่มส่วน" เพื่อเพิ่มส่วนพิเศษเช่น ภาษา ใบรับรอง หรืองานอาสาสมัคร เพื่อลบส่วน ให้แตะหัวข้อส่วนและเลือก "ลบ"',
  'faq_q6'  : 'วิธีจัดเรียงส่วนต่างๆ ใหม่ได้อย่างไร?',
  'faq_a6'  : 'กดค้างที่แฮนเดิลลาก (≡) ข้างหัวข้อส่วนใดก็ได้และลากไปยังตำแหน่งที่ต้องการ การเปลี่ยนแปลงจะถูกบันทึกโดยอัตโนมัติ',
  'faq_q7'  : 'วิธีส่งออก CV เป็น PDF ได้อย่างไร?',
  'faq_a7'  : 'เปิด CV ของคุณและแตะปุ่มส่งออก (ไอคอนแชร์) ที่มุมบนขวา เลือก "ส่งออกเป็น PDF" จากนั้นคุณสามารถบันทึกลงในอุปกรณ์ แชร์ผ่านอีเมล WhatsApp หรืออัปโหลดไปยังบอร์ดงานโดยตรง',
  'faq_q8'  : 'รองรับรูปแบบไฟล์อะไรบ้าง?',
  'faq_a8'  : 'ปัจจุบันแอปรองรับการส่งออก CV ของคุณเป็น PDF คุณภาพสูง อาจมีการเพิ่มรูปแบบเพิ่มเติมในการอัปเดตในอนาคต',
  'faq_q9'  : 'ข้อมูล CV ของฉันถูกจัดเก็บไว้ที่ไหน?',
  'faq_a9'  : 'ข้อมูล CV ทั้งหมดของคุณถูกจัดเก็บไว้ในอุปกรณ์ของคุณ เราไม่ได้อัปโหลดข้อมูลส่วนตัวของคุณไปยังเซิร์ฟเวอร์ของเรา ซึ่งหมายความว่าข้อมูลของคุณยังคงเป็นส่วนตัวและเข้าถึงได้แบบออฟไลน์',
  'faq_q10' : 'วิธีสำรองข้อมูล CV ของฉันได้อย่างไร?',
  'faq_a10' : 'CV ของคุณรวมอยู่ในการสำรองข้อมูลมาตรฐานของอุปกรณ์ (Google Drive บน Android, iCloud บน iOS) หากคุณเปิดใช้การสำรองข้อมูลในการตั้งค่าอุปกรณ์ คุณยังสามารถส่งออก CV แต่ละฉบับเป็น PDF เพื่อเก็บสำเนา',
  'faq_q11' : 'แอปทำงานช้า ฉันควรทำอะไร?',
  'faq_a11' : 'ลองปิดและเปิดแอปใหม่ หากปัญหายังคงอยู่ ให้รีสตาร์ทอุปกรณ์ของคุณ ตรวจสอบให้แน่ใจว่าคุณมีแอปเวอร์ชันล่าสุดที่ติดตั้งจาก Play Store / App Store',
  'faq_q12' : 'CV ของฉันส่งออกไม่ถูกต้อง ฉันควรทำอะไร?',
  'faq_a12' : 'ตรวจสอบให้แน่ใจว่าคุณมีพื้นที่จัดเก็บเพียงพอในอุปกรณ์ ลองลดขนาดรูปภาพขนาดใหญ่ใน CV หากปัญหายังคงอยู่ โปรดติดต่อทีมสนับสนุนของเรา',
  'faq_q13' : 'ฉันลืมบันทึก — งานของฉันหายไปไหม?',
  'faq_a13' : 'ไม่เลย! แอปบันทึกความคืบหน้าของคุณอย่างต่อเนื่องขณะที่คุณแก้ไข',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'CV Builder Pro',
  'header_app_subtitle'                 : 'อาชีพของคุณ สมบูรณ์แบบ',
  'header_tooltip_back'                 : 'กลับ',
  'header_tooltip_my_cvs'               : 'CV ของฉัน',
  'header_tooltip_settings'             : 'การตั้งค่า',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'CV ของฉัน',
  'saved_count_single'                  : '{n} เอกสาร',
  'saved_count_plural'                  : '{n} เอกสาร',
  'saved_limit_reached'                 : 'ถึงขีดจำกัดแล้ว',
  'saved_footer_count'                  : '{n} / 30 CV',
  'saved_filter_all'                    : 'ทั้งหมด',
  'saved_filter_draft'                  : 'ร่าง',
  'saved_filter_complete'               : 'เสร็จสมบูรณ์',
  'saved_status_complete'               : 'เสร็จสมบูรณ์',
  'saved_status_saved'                  : 'บันทึกแล้ว',
  'saved_status_draft'                  : 'ร่าง',
  'saved_empty_title'                   : 'ยังไม่มี CV ที่นี่',
  'saved_empty_sub'                     : 'เริ่มสร้าง CV แรกของคุณด้านบน',
  'saved_search_empty_title'            : 'ไม่พบผลลัพธ์',
  'saved_search_empty_sub'              : 'ลองค้นหาด้วยคำอื่น',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'ชุดสี',
  'custom_font_settings_title'          : 'การตั้งค่าฟอนต์',
  'custom_font_family_label'            : 'ฟอนต์',
  'custom_font_size_label'              : 'ขนาดฟอนต์: ',
  'custom_current_template_title'       : 'แม่แบบปัจจุบัน',
  'custom_change_template_btn'          : 'เปลี่ยนแม่แบบ',
  'custom_tpl_modern'                   : 'ทันสมัย',
  'custom_tpl_classic'                  : 'คลาสสิก',
  'custom_tpl_professional'             : 'มืออาชีพ',
  'custom_tpl_creative'                 : 'สร้างสรรค์',
  'custom_tpl_minimal'                  : 'เรียบง่าย',
  'custom_tpl_modern_desc'              : 'ดีไซน์สะอาดและร่วมสมัย',
  'custom_tpl_classic_desc'             : 'เลย์เอาต์มืออาชีพแบบดั้งเดิม',
  'custom_tpl_professional_desc'        : 'แม่แบบที่เน้นธุรกิจ',
  'custom_tpl_creative_desc'            : 'โดดเด่นด้วยดีไซน์ที่ไม่เหมือนใคร',
  'custom_tpl_minimal_desc'             : 'สไตล์เรียบง่ายและสง่างาม',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'เลือกแม่แบบ',
  'swipe_photo_badge'                   : 'รูปภาพ',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'Executive',
  'tpl_nordic_name'                     : 'Nordic',
  'tpl_vibrant_name'                    : 'Vibrant',
  'tpl_tech_dark_name'                  : 'Tech Dark',
  'tpl_luxury_name'                     : 'Luxury',
  'tpl_executive_tag'                   : 'ยอดนิยมที่สุด',
  'tpl_nordic_tag'                      : 'สะอาด',
  'tpl_vibrant_tag'                     : 'สร้างสรรค์',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'Elite',
  'tpl_executive_desc'                  : 'โดดเด่นและมีอำนาจสำหรับตำแหน่งระดับสูง',
  'tpl_nordic_desc'                     : 'ความชัดเจนเรียบง่ายที่บริษัทชั้นนำไว้วางใจ',
  'tpl_vibrant_desc'                    : 'โดดเด่นด้วยพลังงานและสีสัน',
  'tpl_tech_dark_desc'                  : 'สไตล์เทอร์มินัลสำหรับนักพัฒนา',
  'tpl_luxury_desc'                     : 'ความหรูหราสีทองบนพื้นดำ',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'แม่แบบ',
  'detail_step_personal'                : 'ส่วนตัว',
  'detail_step_experience'              : 'ประสบการณ์',
  'detail_step_education'               : 'การศึกษา',
  'detail_step_skills'                  : 'ทักษะ',
  'detail_step_additional'              : 'ข้อมูลเพิ่มเติม',
  'detail_step_references'              : 'ผู้อ้างอิง',
  'detail_step_customize'               : 'ปรับแต่ง',
  'detail_banner_heading'               : 'ใกล้เสร็จแล้ว!',
  'detail_banner_btn'                   : 'ดำเนินการต่อ',
  'detail_banner_completion_label'      : 'ความสมบูรณ์',
  'detail_stat_created_label'           : 'สร้างเมื่อ',
  'detail_stat_steps_label'             : 'ขั้นตอนที่ทำแล้ว',
  'detail_section_template_style'       : 'สไตล์แม่แบบ',
  'detail_section_steps'                : 'ขั้นตอน',
  'detail_steps_counter'                : '{done} จาก {total} เสร็จแล้ว',
  'detail_step_sub'                     : 'ขั้นตอน {n} จาก {total}',
  'detail_section_activity'             : 'กิจกรรม',
  'detail_activity_created'             : 'สร้างเมื่อ',
  'detail_activity_last_edited'         : 'แก้ไขล่าสุด',
  'detail_activity_template'            : 'แม่แบบ',
  'detail_btn_continue_editing'         : 'แก้ไขต่อ',
  'detail_btn_edit_cv'                  : 'แก้ไข CV',
  'detail_option_rename'                : 'เปลี่ยนชื่อ CV',
  'detail_option_delete'                : 'ลบ CV',
  'detail_rename_title'                 : 'เปลี่ยนชื่อ CV',
  'detail_rename_hint'                  : 'เช่น CV วิศวกรซอฟต์แวร์',
  'detail_rename_error_empty'           : 'ชื่อต้องไม่ว่างเปล่า',
  'detail_rename_btn_cancel'            : 'ยกเลิก',
  'detail_rename_btn_save'              : 'บันทึก',
  'detail_rename_snackbar'              : 'เปลี่ยนชื่อเป็น "{name}" แล้ว',
  'detail_delete_title'                 : 'ลบ CV?',
  'detail_delete_body'                  : 'การดำเนินการนี้จะลบ "{name}" อย่างถาวร ไม่สามารถเลิกทำได้',
  'detail_delete_btn_cancel'            : 'ยกเลิก',
  'detail_delete_btn_confirm'           : 'ลบ',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'เสร็จสมบูรณ์',
  'detail_check_tile_incomplete'        : 'ยังไม่ได้กรอก',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'เลือกแม่แบบของคุณ',
  'chooser_subtitle'                    : 'ปัดเพื่อเรียกดู  ·  แตะเพื่อเลือก  ·  กดค้างเพื่อดูตัวอย่าง',
  'chooser_card_hold_hint'              : 'กดค้างเพื่อดูตัวอย่าง',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'เลือกแล้ว',
  'chooser_modal_heading'               : 'ตั้งชื่อ CV ของคุณ',
  'chooser_modal_sub'                   : 'ตั้งชื่อเพื่อให้ค้นหาได้ง่ายใน CV ของฉันและประวัติ',
  'chooser_modal_field_label'           : 'ชื่อ CV',
  'chooser_modal_save_btn'              : 'บันทึกและเริ่มสร้าง',
  'chooser_modal_divider'               : 'หรือดำเนิน CV ที่มีอยู่ต่อ',
  'chooser_nav_selected_sub'            : 'แม่แบบที่เลือก',
  'chooser_nav_cta'                     : 'บันทึกและดำเนินการต่อ',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'ถึงจำนวนรายการสูงสุดแล้ว',
  'editor_show_hide'                    : 'แสดง/ซ่อน',
  'editor_editing_badge'                : 'กำลังแก้ไข',
  'editor_field_required'               : 'จำเป็น',
  'editor_tooltip_edit'                 : 'แก้ไข',
  'editor_tooltip_delete'               : 'ลบ',
  'editor_date_start'                   : 'วันที่เริ่มต้น *',
  'editor_date_end'                     : 'วันที่สิ้นสุด *',
  'editor_date_tap_hint'                : 'แตะเพื่อเลือก',
  'editor_date_dialog_title'            : 'เลือกเดือนและปี',
  'editor_date_confirm'                 : 'ยืนยัน',
  'editor_panel_hide'                   : 'ซ่อน',
  'editor_panel_show'                   : 'แสดง',
  'editor_validator_max_chars'          : 'สูงสุด {n} ตัวอักษร',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'สร้าง CV ของคุณ',
  'editor_header_step_sub'              : 'ขั้นตอน {current} จาก {total} · {label}',
  'editor_step_template'                : 'แม่แบบ',
  'editor_step_personal'                : 'ส่วนตัว',
  'editor_step_experience'              : 'ประสบการณ์',
  'editor_step_education'               : 'การศึกษา',
  'editor_step_skills'                  : 'ทักษะ',
  'editor_step_additional'              : 'ข้อมูลเพิ่มเติม',
  'editor_step_references'              : 'ผู้อ้างอิง',
  'editor_step_customize'               : 'ปรับแต่ง',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'ปรับแต่ง',
  'customize_subtitle'                  : 'ทำให้ CV ของคุณเป็นเอกลักษณ์',
  'customize_smart_layout_btn'          : 'Smart Layout',
  'customize_back_to_top'               : 'กลับขึ้นด้านบน',
  'customize_done_title'                : 'คุณพร้อมแล้ว!',
  'customize_done_sub'                  : 'แตะ ดูตัวอย่าง CV ด้านล่างเพื่อดู CV ที่เสร็จสมบูรณ์ของคุณ',
  'customize_preview_btn'               : 'ดูตัวอย่าง CV',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'ชุดสี',
  'color_black'                         : 'ดำ',
  'color_blue'                          : 'น้ำเงิน',
  'color_nordic_blue'                   : 'Nordic Blue',
  'color_indigo'                        : 'คราม',
  'color_teal'                          : 'เขียวอมฟ้า',
  'color_green'                         : 'เขียว',
  'color_purple'                        : 'ม่วง',
  'color_orange'                        : 'ส้ม',
  'color_red'                           : 'แดง',
  'color_executive_gold'                : 'Executive Gold',
  'color_vibrant_coral'                 : 'Vibrant Coral',
  'color_white'                         : 'ขาว',
  'color_white_bg'                      : 'พื้นหลังสีขาว',
  'color_maroon'                        : 'น้ำตาลแดง',
  'color_brutalist_yellow'              : 'Brutalist Yellow',
  'color_neon_blue'                     : 'Neon Blue',
  'color_blueprint_navy'                : 'Blueprint Navy',
  'color_light_grey'                    : 'เทาอ่อน',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'ฟอนต์',
  'customize_font_picker_title'         : 'เลือกฟอนต์',
  'customize_font_picker_sub'           : 'แต่ละฟอนต์แสดงตัวอย่างในแบบอักษรของตัวเอง',
  'customize_font_preview_sample'       : 'The quick brown fox',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'ขนาดฟอนต์',
  'customize_font_size_label'           : 'ขนาดตัวอักษร',
  'customize_font_size_value'           : '{n} pt',
  'customize_font_size_min'             : '10 pt',
  'customize_font_size_max'             : '16 pt',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'ขนาดรูปภาพ',
  'customize_image_size_label'          : 'ขนาดรูปภาพ',
  'customize_image_size_value'          : '{n} px',
  'customize_image_size_min'            : '10 px',
  'customize_image_size_max'            : '16 px',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'ดูตัวอย่างสด',
  'preview_page_count_singular'         : '1 หน้า',
  'preview_page_count_plural'           : '{n} หน้า',
  'preview_page_of'                     : 'หน้า {page} จาก {total}',
  'preview_live_hint'                   : 'การเปลี่ยนแปลงจะมีผลทันที',
  'preview_template_unregistered'       : 'ยังไม่ได้ลงทะเบียนใน customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'กำลังเตรียม CV ของคุณ…',
  'preview_bar_print'                   : 'พิมพ์',
  'preview_bar_save_pdf'                : 'บันทึกเป็น PDF',
  'preview_bar_share'                   : 'แชร์',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'ดูตัวอย่าง CV',
  'preview_screen_sub'                  : '{n} {unit} · เหมือนที่พิมพ์จริง',
  'preview_page_singular'               : 'หน้า',
  'preview_page_plural'                 : 'หน้า',
  'preview_pdf_filename'                : 'My_CV',
  'preview_share_subject'               : 'CV ของฉัน',
  'preview_snack_print_failed'          : 'พิมพ์ล้มเหลว: {e}',
  'preview_snack_saved'                 : 'บันทึก CV ไปยังดาวน์โหลดแล้ว ✓',
  'preview_snack_export_failed'         : 'ส่งออกล้มเหลว: {e}',
  'preview_snack_share_failed'          : 'แชร์ล้มเหลว: {e}',
  'preview_template_not_registered'     : 'ไม่ได้ลงทะเบียนแม่แบบ',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'ปิดตัวอย่าง',
  'preview_modal_hint_photo'            : 'รองรับรูปโปรไฟล์  ·  แตะการ์ดเพื่อเลือก',
  'preview_modal_hint_no_photo'         : 'แตะการ์ดแม่แบบเพื่อเลือก',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'CV ของฉัน',
  'time_just_now'                       : 'เมื่อกี้นี้',
  'time_minutes_ago'                    : '{n} นาทีที่แล้ว',
  'time_hours_ago'                      : '{n} ชั่วโมงที่แล้ว',
  'time_yesterday'                      : 'เมื่อวาน',
  'time_days_ago'                       : '{n} วันที่แล้ว',
  'time_one_week_ago'                   : '1 สัปดาห์ที่แล้ว',
  'time_weeks_ago'                      : '{n} สัปดาห์ที่แล้ว',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'หรูหรา',
  'tpl_tag_classic'                     : 'คลาสสิก',
  'tpl_tag_minimal'                     : 'เรียบง่าย',
  'tpl_tag_creative'                    : 'สร้างสรรค์',
  'tpl_tag_bold'                        : 'โดดเด่น',

  // ─── preview_registry.dart — template names (IDs 6–24) ──────────────────
  'tpl_gradient_name'                   : 'Gradient',
  'tpl_gradient_desc'                   : 'การ์ดไล่สีจากฟ้าครามเป็นม่วง',

  'tpl_editorial_name'                  : 'Editorial',
  'tpl_editorial_desc'                  : 'สไตล์นิตยสารสีแดงและครีม',

  'tpl_pastel_soft_name'                : 'Pastel Soft',
  'tpl_pastel_soft_desc'                : 'แถบข้างสีลาเวนเดอร์ การ์ดนุ่มนวล',

  'tpl_brutalist_name'                  : 'Brutalist',
  'tpl_brutalist_desc'                  : 'กริดดิบ เส้นขอบหนา และสีเหลือง',

  'tpl_emerald_name'                    : 'Emerald',
  'tpl_emerald_desc'                    : 'สีเขียวป่าพร้อมไทม์ไลน์',

  'tpl_infographic_name'                : 'Infographic',
  'tpl_infographic_desc'                : 'พื้นหลังเข้มพร้อมแผนภูมิวงกลม',

  'tpl_art_deco_name'                   : 'Art Deco',
  'tpl_art_deco_desc'                   : 'ความหรูหราทองคำทรงเรขาคณิตยุค 1920',

  'tpl_wina_dark_name'                  : 'Wina Dark',
  'tpl_wina_dark_desc'                  : 'อินโฟกราฟิกมืดพร้อมวงแหวน',

  'tpl_rio_orange_name'                 : 'Rio Orange',
  'tpl_rio_orange_desc'                 : 'แถบข้างมืดพร้อมสีส้มสด',

  'tpl_summer_name'                     : 'Summer',
  'tpl_summer_desc'                     : 'เรียบง่ายสะอาด โทนเทาอ่อน',

  'tpl_helene_name'                     : 'Helene',
  'tpl_helene_desc'                     : 'โทนเบจอบอุ่นสง่างาม',

  'tpl_canfield_name'                   : 'Canfield',
  'tpl_canfield_desc'                   : 'ขาวดำคลาสสิกตัดกันชัดเจน',

  'tpl_collins_name'                    : 'Collins',
  'tpl_collins_desc'                    : 'เลย์เอาต์คลาสสิกเหมาะกับ ATS',

  'tpl_tony_dark_name'                  : 'Tony Dark',
  'tpl_tony_dark_desc'                  : 'สไตล์อินโฟกราฟิกสีส้มมืด',

  'tpl_fashion_name'                    : 'Fashion',
  'tpl_fashion_desc'                    : 'รูปวาดทางเทคนิคบนกริด',

  'tpl_archivist_name'                  : 'Archivist',
  'tpl_archivist_desc'                  : 'เลย์เอาต์สองคอลัมน์สไตล์คลาสสิก',

  'tpl_diplomat_name'                   : 'Diplomat',
  'tpl_diplomat_desc'                   : 'หัวข้อมีเงาพร้อมสัญลักษณ์เพชร',

  'tpl_meridian_name'                   : 'Meridian',
  'tpl_meridian_desc'                   : 'หัวข้อกึ่งกลาง ชื่อบริษัทเน้นสี',

  'tpl_momentum_name'                   : 'Momentum',
  'tpl_momentum_desc'                   : 'ชื่อตัวหนา จุดไทม์ไลน์ และผลงาน',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'ข้อมูลส่วนตัว',
  'personal_subtitle'                   : 'แนะนำตัวเองกับนายจ้าง',
  'personal_profile_counter'            : '{n}/{max} โปรไฟล์',
  'personal_info_banner'                : 'บันทึกได้สูงสุด 5 โปรไฟล์และเลือกหนึ่งโปรไฟล์ต่อ CV การเลือกของคุณจะถูกจดจำสำหรับแต่ละ CV แยกกัน',
  'personal_snack_max'                  : 'ถึงจำนวนโปรไฟล์สูงสุด {n} แล้ว',
  'personal_add_btn'                    : 'เพิ่มโปรไฟล์ใหม่',
  'personal_library_title'              : 'โปรไฟล์ที่บันทึกไว้',
  'personal_selected_one'               : 'เลือก 1 รายการ',
  'personal_selected_none'              : 'ไม่ได้เลือก',
  'personal_library_hint'               : 'แตะการ์ดเพื่อเลือกสำหรับ CV นี้เท่านั้น CV อื่นๆ จะรักษาการเลือกของตัวเองไว้',
  'personal_empty_message'              : 'ยังไม่ได้บันทึกโปรไฟล์',
  'personal_empty_sub'                  : 'แตะด้านบนเพื่อเพิ่มข้อมูลส่วนตัวของคุณ',
  'personal_nav_next'                   : 'บันทึกและดำเนินการต่อ',
  'personal_card_active_badge'          : 'ใช้งานสำหรับ CV นี้',
  'personal_sheet_title_add'            : 'โปรไฟล์ใหม่',
  'personal_sheet_title_edit'           : 'แก้ไขโปรไฟล์',
  'personal_sheet_brutalist_badge'      : 'BRUTALIST',
  'personal_sheet_brutalist_banner'     : 'แม่แบบ Brutalist มีช่องติดต่อที่กระชับ ค่าสั้นๆ (เช่น ชื่อเมืองเท่านั้น) จะแสดงผลได้ดีที่สุด',
  'personal_section_photo'              : 'รูปโปรไฟล์',
  'personal_section_basic'              : 'ข้อมูลพื้นฐาน',
  'personal_section_contact'            : 'ข้อมูลติดต่อ',
  'personal_section_online'             : 'ตัวตนออนไลน์',
  'personal_section_summary'            : 'สรุปมืออาชีพ',
  'personal_field_first_name'           : 'ชื่อ *',
  'personal_field_last_name'            : 'นามสกุล',
  'personal_field_job_title'            : 'ตำแหน่งงาน *',
  'personal_field_email'                : 'อีเมล *',
  'personal_field_phone'                : 'เบอร์โทรศัพท์ *',
  'personal_field_location'             : 'ที่อยู่',
  'personal_field_location_brut'        : 'ที่อยู่ (เฉพาะเมือง)',
  'personal_field_website'              : 'เว็บไซต์ / พอร์ตโฟลิโอ',
  'personal_field_linkedin'             : 'LinkedIn URL',
  'personal_hint_first_name'            : 'เช่น สมชาย',
  'personal_hint_last_name'             : 'เช่น ใจดี',
  'personal_hint_job_title'             : 'เช่น วิศวกรอาวุโส',
  'personal_hint_email'                 : 'เช่น somchai@example.com',
  'personal_hint_phone'                 : 'เช่น +66 81 234 5678',
  'personal_hint_location'              : 'เช่น กรุงเทพมหานคร ประเทศไทย',
  'personal_hint_location_brut'         : 'เช่น กรุงเทพฯ ไทย',
  'personal_hint_website'               : 'เช่น github.com/somchai',
  'personal_hint_website_brut'          : 'เช่น github.com/som',
  'personal_hint_linkedin'              : 'เช่น linkedin.com/in/somchai',
  'personal_hint_linkedin_brut'         : 'เช่น linkedin.com/in/som',
  'personal_summary_hint_label'         : 'กระชับ — ส่วนนี้จะปรากฏที่ด้านบนของ CV ของคุณ',
  'personal_hint_summary'               : 'สรุปภูมิหลังและเป้าหมายของคุณสั้นๆ 2–3 ประโยค...',
  'personal_validator_email'            : 'กรุณากรอกอีเมลที่ถูกต้อง',
  'personal_field_char_limit_tooltip'   : 'ถึงขีดจำกัดตัวอักษรแล้ว',
  'personal_sheet_btn_save'             : 'บันทึกโปรไฟล์',
  'personal_sheet_btn_update'           : 'บันทึกการเปลี่ยนแปลง',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'เลือกรูปภาพ',
  'photo_option_gallery'                : 'เลือกจากแกลเลอรี่',
  'photo_option_camera'                 : 'ถ่ายรูป',
  'photo_option_reposition'             : 'จัดตำแหน่งรูปภาพใหม่',
  'photo_option_remove'                 : 'ลบรูปภาพ',
  'photo_status_added'                  : 'เพิ่มรูปภาพแล้ว ✓',
  'photo_status_empty'                  : 'เพิ่มรูปหัวมืออาชีพ',
  'photo_chip_gallery'                  : 'แกลเลอรี่',
  'photo_chip_camera'                   : 'กล้อง',
  'photo_chip_reposition'               : 'จัดตำแหน่งใหม่',
  'photo_reposition_title'              : 'จัดตำแหน่งรูปภาพใหม่',
  'photo_reposition_sub'                : 'ลากรูปภาพเพื่อปรับตำแหน่ง',
  'photo_reposition_reset'              : 'รีเซ็ตไปที่กึ่งกลาง',
  'photo_reposition_apply'              : 'ใช้งาน',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'ทักษะ',
  'skills_subtitle'                     : 'เน้นความสามารถหลักของคุณ',
  'skills_add_btn'                      : 'เพิ่มทักษะใหม่',
  'skills_snack_max_icons'              : 'เลือกไอคอนสูงสุด 10 อัน',
  'skills_snack_max_skills'             : 'ถึงจำนวนทักษะสูงสุด 15 ทักษะแล้ว',
  'skills_library_title'                : 'ทักษะที่บันทึกไว้',
  'skills_library_hint'                 : 'ทักษะที่เลือกจะรวมอยู่ใน CV นี้ การเลือกของคุณจะถูกบันทึกโดยอัตโนมัติ',
  'skills_nav_next'                     : 'ดำเนินการต่อไปยังข้อมูลเพิ่มเติม',
  'skills_wina_header_icon_bar'         : 'แถบไอคอนหัวข้อ',
  'skills_wina_on'                      : 'เปิด',
  'skills_wina_off'                     : 'ปิด',
  'skills_wina_bar_on_sub'              : 'แสดงวงกลมไอคอนสีในหัว CV',
  'skills_wina_bar_off_sub'             : 'ซ่อนแถบไอคอน — มีพื้นที่มากขึ้นสำหรับข้อมูลติดต่อ',
  'skills_wina_palette_hint'            : 'ไอคอนจะปรากฏเป็นวงกลมสีตามลำดับจานสี',
  'skills_wina_preview_label'           : 'ตัวอย่าง',
  'skills_wina_disabled_hint'           : 'เปิดใช้แถบไอคอนด้านบนเพื่อเลือกไอคอนที่จะปรากฏในหัว CV',
  'skills_sheet_title_add'              : 'เพิ่มทักษะ',
  'skills_sheet_title_edit'             : 'แก้ไขทักษะ',
  'skills_sheet_field_name'             : 'ชื่อทักษะ *',
  'skills_sheet_hint_short'             : 'เช่น Flutter, ออกแบบ',
  'skills_sheet_hint_long'              : 'เช่น Flutter, การจัดการโครงการ',
  'skills_sheet_validator_max'          : 'สูงสุด {n} ตัวอักษร',
  'skills_sheet_proficiency'            : 'ระดับความเชี่ยวชาญ',
  'skills_sheet_beginner'               : 'เริ่มต้น',
  'skills_sheet_expert'                 : 'เชี่ยวชาญ',
  'skills_sheet_btn_save'               : 'บันทึกทักษะ',
  'skills_sheet_btn_update'             : 'อัปเดตทักษะ',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'ผู้อ้างอิงส่วนตัว',
  'refs_subtitle'                       : 'คนที่สามารถรับรองตัวคุณได้เป็นการส่วนตัว',
  'refs_add_btn'                        : 'เพิ่มผู้อ้างอิงส่วนตัวใหม่',
  'refs_snack_max_selected'             : 'สามารถเลือกผู้อ้างอิงได้สูงสุด 4 คนต่อ CV',
  'refs_snack_max_saved'                : 'ถึงจำนวนผู้อ้างอิงที่บันทึกไว้สูงสุด 10 คนแล้ว',
  'refs_library_title'                  : 'ผู้อ้างอิงที่บันทึกไว้',
  'refs_library_hint'                   : 'ผู้อ้างอิงที่เลือกจะรวมอยู่ใน CV นี้ สูงสุด 4 คนต่อ CV การเลือกจะถูกบันทึกโดยอัตโนมัติ',
  'refs_nav_next'                       : 'ดำเนินการต่อไปยังการปรับแต่ง',
  'refs_sheet_title_add'                : 'เพิ่มผู้อ้างอิงส่วนตัว',
  'refs_sheet_title_edit'               : 'แก้ไขผู้อ้างอิงส่วนตัว',
  'refs_sheet_sub_add'                  : 'คนที่สามารถแนะนำคุณต่อนายจ้างได้เป็นการส่วนตัว',
  'refs_sheet_sub_edit'                 : 'อัปเดตรายละเอียดของผู้อ้างอิงนี้ด้านล่าง',
  'refs_sheet_field_name'               : 'ชื่อเต็ม *',
  'refs_sheet_field_title'              : 'ตำแหน่งงาน *',
  'refs_sheet_field_company'            : 'บริษัท (ไม่บังคับ)',
  'refs_sheet_field_email'              : 'อีเมล *',
  'refs_sheet_field_phone'              : 'เบอร์โทรศัพท์ *',
  'refs_sheet_hint_name'                : 'เช่น สมชาย ใจดี',
  'refs_sheet_hint_title'               : 'เช่น ผู้จัดการฝ่ายวิศวกรรม',
  'refs_sheet_hint_company'             : 'เช่น บริษัท Acme',
  'refs_sheet_hint_email'               : 'เช่น somchai@acme.com',
  'refs_sheet_hint_phone'               : 'เช่น +66 81 234 5678',
  'refs_sheet_validator_email'          : 'กรุณากรอกอีเมลที่ถูกต้อง',
  'refs_sheet_btn_save'                 : 'บันทึกผู้อ้างอิงส่วนตัว',
  'refs_sheet_btn_update'               : 'อัปเดตผู้อ้างอิงส่วนตัว',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'ประสบการณ์การทำงาน',
  'exp_subtitle'                        : 'เพิ่มประวัติการทำงานของคุณ',
  'exp_banner_info'                     : 'ความรับผิดชอบสูงสุด {n} รายการต่อตำแหน่งจะปรากฏใน CV โดยทั่วไป 3–6 ตำแหน่งจะพอดีกับ 1–2 หน้า',
  'exp_add_btn'                         : 'เพิ่มประสบการณ์ใหม่',
  'exp_snack_max_selected'              : 'สามารถเลือกประสบการณ์ได้สูงสุด 8 รายการต่อ CV',
  'exp_snack_max_saved'                 : 'ถึงจำนวนประสบการณ์ที่บันทึกไว้สูงสุด 12 รายการแล้ว',
  'exp_library_title'                   : 'ประสบการณ์ที่บันทึกไว้',
  'exp_library_hint'                    : 'รายการที่เลือกจะรวมอยู่ใน CV นี้เท่านั้น CV อื่นๆ จะรักษาการเลือกของตัวเองไว้',
  'exp_nav_next'                        : 'ดำเนินการต่อไปยังการศึกษา',
  'exp_empty_message'                   : 'ยังไม่ได้เพิ่มประสบการณ์',
  'exp_empty_sub'                       : 'แตะด้านบนเพื่อเพิ่มตำแหน่งแรกของคุณ',
  'exp_card_resp_singular'              : 'ความรับผิดชอบ',
  'exp_card_resp_plural'                : 'ความรับผิดชอบ',
  'exp_card_resp_tooltip'               : 'จะแสดงเฉพาะ 8 ความรับผิดชอบแรกใน CV',
  'exp_sheet_title_add'                 : 'เพิ่มประสบการณ์',
  'exp_sheet_title_edit'                : 'แก้ไขประสบการณ์',
  'exp_sheet_field_job_title'           : 'ตำแหน่งงาน *',
  'exp_sheet_field_company'             : 'บริษัท *',
  'exp_sheet_field_location'            : 'ที่ตั้ง',
  'exp_sheet_section_responsibilities'  : 'ความรับผิดชอบหลัก',
  'exp_sheet_resp_hint_info'            : 'สูงสุด 8 หัวข้อย่อย · 200 ตัวอักษรต่อข้อ',
  'exp_sheet_resp_label'                : 'ความรับผิดชอบ {n}',
  'exp_sheet_resp_hint'                 : 'เช่น นำทีมวิศวกร 5 คน',
  'exp_sheet_resp_add_btn'              : 'เพิ่มความรับผิดชอบ',
  'exp_sheet_resp_max_info'             : 'ถึงจำนวนความรับผิดชอบสูงสุด {n} รายการแล้ว',
  'exp_sheet_resp_validator_max'        : 'สูงสุด 200 ตัวอักษร',
  'exp_sheet_hint_job_title'            : 'เช่น นักพัฒนาอาวุโส',
  'exp_sheet_hint_location'             : 'เช่น กรุงเทพมหานคร ประเทศไทย',
  'exp_sheet_btn_save'                  : 'บันทึกประสบการณ์',
  'exp_sheet_btn_update'                : 'บันทึกการเปลี่ยนแปลง',
  'exp_date_present'                    : 'ปัจจุบัน / ตำแหน่งงานปัจจุบัน',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'การศึกษา',
  'edu_subtitle'                        : 'เพิ่มพื้นฐานทางวิชาการของคุณ',
  'edu_add_btn'                         : 'เพิ่มการศึกษาใหม่',
  'edu_snack_max_selected'              : 'สามารถเลือกรายการการศึกษาได้สูงสุด 8 รายการต่อ CV',
  'edu_snack_max_saved'                 : 'ถึงจำนวนการศึกษาที่บันทึกไว้สูงสุด 12 รายการแล้ว',
  'edu_library_title'                   : 'การศึกษาที่บันทึกไว้',
  'edu_library_hint'                    : 'รายการที่เลือกจะรวมอยู่ใน CV นี้ การเลือกของคุณจะถูกบันทึกโดยอัตโนมัติ',
  'edu_nav_next'                        : 'ดำเนินการต่อไปยังทักษะ',
  'edu_empty_message'                   : 'ยังไม่ได้เพิ่มการศึกษา',
  'edu_empty_sub'                       : 'แตะด้านบนเพื่อเพิ่มคุณวุฒิของคุณ',
  'edu_card_bullet_singular'            : 'หัวข้อย่อย',
  'edu_card_bullet_plural'              : 'หัวข้อย่อย',
  'edu_sheet_title_add'                 : 'เพิ่มการศึกษา',
  'edu_sheet_title_edit'                : 'แก้ไขการศึกษา',
  'edu_sheet_field_degree'              : 'ปริญญา / คุณวุฒิ *',
  'edu_sheet_field_institution'         : 'สถาบัน *',
  'edu_sheet_section_key_points'        : 'จุดเด่น',
  'edu_sheet_key_points_hint_info'      : 'ไม่บังคับ · 1 หัวข้อย่อย · สูงสุด 100 ตัวอักษร',
  'edu_sheet_point_label'               : 'จุดที่ {n}',
  'edu_sheet_point_add_btn'             : 'เพิ่มหัวข้อย่อย',
  'edu_sheet_point_max_info'            : 'ถึงจำนวนหัวข้อย่อยสูงสุด {n} รายการแล้ว',
  'edu_sheet_point_validator_max'       : 'สูงสุด {n} ตัวอักษร',
  'edu_sheet_hint_degree'               : 'เช่น วิทยาศาสตรบัณฑิต วิทยาการคอมพิวเตอร์',
  'edu_sheet_hint_institution'          : 'เช่น จุฬาลงกรณ์มหาวิทยาลัย',
  'edu_sheet_hint_bullet'               : 'เช่น เกียรตินิยมอันดับหนึ่ง',
  'edu_sheet_btn_save'                  : 'บันทึกการศึกษา',
  'edu_sheet_btn_update'                : 'บันทึกการเปลี่ยนแปลง',
  'edu_date_present'                    : 'ปัจจุบัน / กำลังศึกษาอยู่',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'ข้อมูลเพิ่มเติม',
  'additional_subtitle'                 : 'ใบรับรอง ภาษา และอื่นๆ',
  'additional_cert_section_title'       : 'ใบรับรอง',
  'additional_cert_counter'             : '{sel}/{total} เลือกแล้ว · สูงสุด {max}',
  'additional_cert_hide'                : 'ซ่อน',
  'additional_cert_show'                : 'แสดง',
  'additional_cert_add_btn'             : 'เพิ่ม',
  'additional_cert_snack_max'           : 'ถึงจำนวนใบรับรองสูงสุด {n} รายการแล้ว',
  'additional_cert_hint'                : 'รายการที่เลือกจะรวมอยู่ใน CV นี้ การเลือกของคุณจะถูกบันทึกโดยอัตโนมัติ',
  'additional_cert_empty'               : 'ยังไม่ได้เพิ่มใบรับรอง',
  'additional_lang_section_title'       : 'ภาษา',
  'additional_lang_add_hint'            : 'เช่น ภาษาสเปน',
  'additional_lang_snack_max'           : 'ถึงจำนวนภาษาสูงสุด {n} รายการแล้ว',
  'additional_lang_empty'               : 'ยังไม่ได้เพิ่มภาษา',
  'additional_hobby_section_title'      : 'งานอดิเรกและความสนใจ',
  'additional_hobby_add_hint'           : 'เช่น การถ่ายภาพ',
  'additional_hobby_snack_max'          : 'ถึงจำนวนงานอดิเรกสูงสุด {n} รายการแล้ว',
  'additional_hobby_empty'              : 'ยังไม่ได้เพิ่มงานอดิเรก',
  'additional_section_hint'             : 'รายการที่เลือกจะรวมอยู่ใน CV นี้ การเลือกของคุณจะถูกบันทึกโดยอัตโนมัติ',
  'additional_nav_next'                 : 'ดำเนินการต่อไปยังผู้อ้างอิง',
  'cert_sheet_title_add'                : 'เพิ่มใบรับรอง',
  'cert_sheet_title_edit'               : 'แก้ไขใบรับรอง',
  'cert_sheet_sub'                      : 'เพิ่มคุณวุฒิ ใบรับรอง หรือข้อมูลประจำตัวมืออาชีพ',
  'cert_sheet_field_name'               : 'ชื่อใบรับรอง *',
  'cert_sheet_field_issued_by'          : 'ออกโดย (ไม่บังคับ)',
  'cert_sheet_field_short_desc'         : 'คำอธิบายสั้น (ไม่บังคับ)',
  'cert_sheet_hint_name'                : 'เช่น AWS Solutions Architect',
  'cert_sheet_hint_issued_by'           : 'เช่น Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'เช่น ได้รับในปี 2567',
  'cert_sheet_btn_save'                 : 'บันทึกใบรับรอง',
  'cert_sheet_btn_update'               : 'อัปเดตใบรับรอง',
  'simple_sheet_title_add_language'     : 'เพิ่มภาษา',
  'simple_sheet_title_edit_language'    : 'แก้ไขภาษา',
  'simple_sheet_title_add_hobby'        : 'เพิ่มงานอดิเรก',
  'simple_sheet_title_edit_hobby'       : 'แก้ไขงานอดิเรก',
  'simple_sheet_btn_save'               : 'บันทึก',
  'simple_sheet_btn_update'             : 'อัปเดต',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'ข้อมูลติดต่อ',
  'pdf_section_about_me'                : 'เกี่ยวกับฉัน',
  'pdf_section_summary'                 : 'สรุป',
  'pdf_section_summary_short'           : 'สรุป',
  'pdf_section_profile'                 : 'โปรไฟล์',
  'pdf_section_experience'              : 'ประสบการณ์',
  'pdf_section_experience_short'        : 'ประสบการณ์',
  'pdf_section_education'               : 'การศึกษา',
  'pdf_section_skills'                  : 'ทักษะ',
  'pdf_section_languages'               : 'ภาษา',
  'pdf_label_email'                     : 'อีเมล',
  'pdf_label_phone'                     : 'โทรศัพท์',
  'pdf_label_location'                  : 'Localisation',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'ถึงขีดจำกัด CV แล้ว',
  'limit_dialog_body'                   : 'คุณถึงจำนวน CV สูงสุด 30 ฉบับแล้ว กรุณาลบ CV ที่มีอยู่ก่อนสร้างฉบับใหม่',
  'limit_dialog_go_to_my_cvs'           : 'ไปที่ CV ของฉัน',
  'limit_dialog_cancel'                 : 'ยกเลิก',
  'refs_count_summary'                  : '{checked}/{maxChecked} เลือกแล้ว · {saved}/{maxSaved} บันทึกแล้ว',
  'refs_selected_badge'                 : 'เลือก {n} รายการ',
  'refs_empty_message'                  : 'ยังไม่ได้บันทึกผู้อ้างอิง',
  'refs_empty_sub'                      : 'แตะด้านบนเพื่อเพิ่มผู้อ้างอิงส่วนตัว',
};