// lib/language_keys/lang_ar_arabic.dart
//
// Arabic (العربية) translation map.
// Translated from lang_en_english.dart.
// RTL language — ensure MaterialApp uses Directionality.rtl.

const Map<String, String> arArabic = {

  // ─── language_ui_select.dart ────────────────────────────────────────────
  'lang_select_no_results'              : 'لم يتم العثور على لغات',

  // ─── onboarding_flow.dart ───────────────────────────────────────────────
  'onboarding_page_counter'             : '{current} / {total}',
  'onboarding_skip'                     : 'تخطي',
  'onboarding_next'                     : 'التالي',
  'onboarding_get_started'              : 'ابدأ الآن',

  // ─── onboarding_screen_1.dart ───────────────────────────────────────────
  'ob1_tag'                             : '✦  مرحباً',
  'ob1_title'                           : 'أنشئ سيرة ذاتية\nتفتح الأبواب',
  'ob1_body'                            : 'تميّز من بين مئات المتقدمين. ابنِ سيرة ذاتية احترافية في دقائق — دون الحاجة لمهارات تصميم.',
  'ob1_pill_label'                      : 'منشئ السيرة الذاتية الاحترافية',
  'ob1_chip_templates'                  : '+24 قالب',
  'ob1_chip_pdf'                        : 'تصدير PDF',
  'ob1_chip_free'                       : 'مجاني',

  // ─── onboarding_screen_2.dart ───────────────────────────────────────────
  'ob2_tag'                             : '✦  القوالب',
  'ob2_title'                           : 'كل صناعة.\nكل طموح.',
  'ob2_body'                            : 'من تصاميم احترافية إلى تصاميم إبداعية جريئة — قالب يروي قصتك.',
  'ob2_tap_hint'                        : 'اضغط على أي قالب للمعاينة',
  'ob2_tpl_executive'                   : 'تنفيذي',
  'ob2_tpl_vibrant'                     : 'نابض',
  'ob2_tpl_nordic'                      : 'نوردي',
  'ob2_tpl_tech_dark'                   : 'تقني داكن',
  'ob2_tpl_luxury'                      : 'فاخر',
  'ob2_tag_corporate'                   : 'مؤسسي',
  'ob2_tag_creative'                    : 'إبداعي',
  'ob2_tag_minimal'                     : 'بسيط',
  'ob2_tag_modern'                      : 'عصري',
  'ob2_tag_premium'                     : 'مميز',

  // ─── onboarding_screen_3.dart ───────────────────────────────────────────
  'ob3_tag'                             : '✦  التخطيط الذكي',
  'ob3_title'                           : 'سيرتك الذاتية.\nمرتبة بإتقان.',
  'ob3_body'                            : 'يعيد التخطيط الذكي ترتيب أقسامك لأقصى تأثير — بوضع أقوى محتواك في المكان الذي يبحث عنه المسؤولون أولاً.',
  'ob3_badge_smart_layout'              : 'التخطيط الذكي',
  'ob3_badge_cv_ready'                  : 'السيرة جاهزة!',
  'ob3_step1_label'                     : 'اختر قالباً',
  'ob3_step1_desc'                      : 'اختر من بين أكثر من 24 تصميماً رائعاً.',
  'ob3_step2_label'                     : 'أدخل بياناتك',
  'ob3_step2_desc'                      : 'حقول موجّهة لجميع الأقسام.',
  'ob3_step3_label'                     : 'التخطيط الذكي',
  'ob3_step3_desc'                      : 'ضغطة واحدة تعيد ترتيب سيرتك بشكل مثالي.',
  'ob3_step4_label'                     : 'تصدير PDF',
  'ob3_step4_desc'                      : 'ملف PDF عالي الجودة جاهز للإرسال.',
  'ob3_section_work'                    : 'الخبرة العملية',
  'ob3_section_education'               : 'التعليم',
  'ob3_section_skills'                  : 'المهارات',
  'ob3_section_references'              : 'المراجع',

  // ─── onboarding_screen_4.dart ───────────────────────────────────────────
  'ob4_tag'                             : '✦  جاهز للانطلاق',
  'ob4_title'                           : 'لماذا يختار أفضل المرشحين\nمنشئ السيرة الذاتية',
  'ob4_visual_headline'                 : 'أنت مستعد تماماً!',
  'ob4_visual_subline'                  : 'كل ما تحتاجه للحصول على الوظيفة.',
  'ob4_stat_templates_value'            : '+24',
  'ob4_stat_templates_label'            : 'قالب',
  'ob4_stat_max_cvs_value'              : '30',
  'ob4_stat_max_cvs_label'             : 'حد السير الذاتية',
  'ob4_stat_export_value'               : 'PDF',
  'ob4_stat_export_label'               : 'تصدير',
  'ob4_stat_private_value'              : '🔒',
  'ob4_stat_private_label'              : 'خاص',
  'ob4_hl1_title'                       : 'خاص وآمن',
  'ob4_hl1_sub'                         : 'تبقى بياناتك على جهازك.',
  'ob4_hl2_title'                       : 'حفظ تلقائي',
  'ob4_hl2_sub'                         : 'كل ضغطة مفتاح تُحفظ فوراً.',
  'ob4_hl3_title'                       : 'حتى 30 سيرة ذاتية',
  'ob4_hl3_sub'                         : 'سيرة فريدة لكل وظيفة.',
  'ob4_hl4_title'                       : 'مشاركة بضغطة واحدة',
  'ob4_hl4_sub'                         : 'أرسل PDF دون مغادرة التطبيق.',

  // ─── home_screen.dart ───────────────────────────────────────────────────
  'home_hero_badge'                     : '✨ تميّز من بين الحشود',
  'home_hero_title'                     : 'أنشئ سيرتك\nالذاتية الاحترافية',
  'home_hero_sub'                       : 'ابنِ سيرة ذاتية مذهلة\nفي دقائق',
  'home_hero_cta'                       : 'ابدأ البناء',
  'home_premium_soon'                   : 'الترقية إلى Pro قريباً!',

  // ─── history_screen.dart ────────────────────────────────────────────────
  'history_sort_most_recent'            : 'الأحدث',
  'history_sort_alphabetical'           : 'أ–ي',
  'history_sort_last_edited'            : 'آخر تعديل',
  'history_sort_by_template'            : 'حسب القالب',
  'history_sort_sheet_title'            : 'ترتيب حسب',
  'history_sort_alphabetical_full'      : 'أبجدي (أ–ي)',
  'history_premium_soon'                : 'الترقية إلى Pro قريباً!',

  // ─── settings_screen.dart ───────────────────────────────────────────────
  'settings_title'                      : 'الإعدادات',
  'settings_section_preferences'        : 'التفضيلات',
  'settings_section_support'            : 'الدعم',
  'settings_section_legal'              : 'القانونية',
  'settings_section_about'              : 'حول التطبيق',
  'settings_language_tile_title'        : 'اللغة',
  'settings_dark_mode_title'            : 'الوضع الداكن',
  'settings_dark_mode_on'               : 'المظهر الداكن مفعّل',
  'settings_dark_mode_off'              : 'المظهر الفاتح مفعّل',
  'settings_help_faq_title'             : 'المساعدة والأسئلة الشائعة',
  'settings_help_faq_sub'               : 'إجابات للأسئلة الشائعة',
  'settings_contact_support_title'      : 'تواصل مع الدعم',
  'settings_rate_app_title'             : 'قيّم التطبيق',
  'settings_rate_app_sub'               : 'تستمتع بالتطبيق؟ اترك تقييماً!',
  'settings_privacy_policy_title'       : 'سياسة الخصوصية',
  'settings_terms_title'                : 'شروط الخدمة',
  'settings_app_version_title'          : 'إصدار التطبيق',
  'settings_email_error'                : 'تعذر فتح تطبيق البريد. يرجى مراسلتنا على cyberinc101@gmail.com',

  // ─── preview_screen.dart ────────────────────────────────────────────────
  'preview_header_title'                : 'معاينة السيرة الذاتية',
  'preview_header_sub'                  : 'جاهزة للتصدير',
  'preview_generating'                  : 'جارٍ إنشاء سيرتك الذاتية...',
  'preview_failed_title'                : 'فشلت المعاينة',
  'preview_failed_error'                : 'خطأ: {error}',
  'preview_go_back'                     : 'رجوع',
  'preview_no_data'                     : 'لا توجد بيانات متاحة',
  'preview_btn_print'                   : 'طباعة',
  'preview_btn_download'                : 'تنزيل ومشاركة',

  // ─── help_faq_screen.dart ───────────────────────────────────────────────
  'faq_title'                           : 'المساعدة والأسئلة الشائعة',
  'faq_category_all'                    : 'الكل',
  'faq_empty'                           : 'لا توجد نتائج',
  'faq_contact_headline'                : 'هل لا تزال بحاجة إلى مساعدة؟',
  'faq_contact_sub'                     : 'فريقنا هنا من أجلك.',
  'faq_contact_btn'                     : 'تواصل',
  'faq_email_error'                     : 'تعذر فتح تطبيق البريد. يرجى مراسلتنا على cyberinc101@gmail.com',
  'faq_cat_getting_started'             : 'البداية',
  'faq_cat_templates'                   : 'القوالب',
  'faq_cat_editing'                     : 'التعديل',
  'faq_cat_exporting'                   : 'التصدير',
  'faq_cat_data_privacy'                : 'البيانات والخصوصية',
  'faq_cat_troubleshooting'             : 'حل المشكلات',
  'faq_q1'  : 'كيف أنشئ سيرتي الذاتية الأولى؟',
  'faq_a1'  : 'اضغط على زر "+" في الشاشة الرئيسية لبدء سيرة ذاتية جديدة. اختر قالباً يناسب أسلوبك، ثم أدخل بياناتك الشخصية وخبرتك العملية وتعليمك ومهاراتك خطوة بخطوة. يتم حفظ تقدمك تلقائياً.',
  'faq_a2'  : 'نعم! يمكنك إنشاء سير ذاتية متعددة لأدوار أو صناعات مختلفة. يتم حفظ كل سيرة ذاتية بشكل منفصل، حتى تتمكن من تخصيصها لطلبات توظيف محددة.',
  'faq_q2'  : 'هل يمكنني إنشاء أكثر من سيرة ذاتية واحدة؟',
  'faq_q3'  : 'كيف أغير قالب سيرتي الذاتية؟',
  'faq_a3'  : 'افتح سيرتك الذاتية، اضغط على أيقونة القالب في أعلى الشاشة، وتصفح القوالب المتاحة. اضغط على أي قالب لمعاينته مع محتواك الحالي. ثم أكد التطبيق.',
  'faq_q4'  : 'هل هناك قوالب مجانية ومميزة؟',
  'faq_a4'  : 'نعم. مجموعة من القوالب الاحترافية متاحة مجاناً. القوالب المميزة ذات التصاميم المتقدمة ولوحات الألوان متاحة عبر شراء لمرة واحدة أو اشتراك.',
  'faq_q5'  : 'كيف أضيف أقساماً أو أحذفها؟',
  'faq_a5'  : 'في محرر السيرة الذاتية، مرر للأسفل واضغط على "إضافة قسم" لإضافة أقسام إضافية مثل اللغات أو الشهادات أو العمل التطوعي. لحذف قسم، اضغط على عنوان القسم واختر "حذف".',
  'faq_q6'  : 'كيف أعيد ترتيب الأقسام؟',
  'faq_a6'  : 'اضغط مطولاً على مقبض السحب (≡) بجانب عنوان أي قسم واسحبه إلى الموضع المفضل. يتم حفظ التغييرات تلقائياً.',
  'faq_q7'  : 'كيف أصدّر سيرتي الذاتية كـ PDF؟',
  'faq_a7'  : 'افتح سيرتك الذاتية واضغط على زر التصدير (أيقونة المشاركة) في الزاوية العلوية اليمنى. اختر "تصدير كـ PDF". يمكنك بعد ذلك حفظه على جهازك أو مشاركته عبر البريد الإلكتروني أو واتساب أو رفعه مباشرة إلى لوحات الوظائف.',
  'faq_q8'  : 'ما صيغ الملفات المدعومة؟',
  'faq_a8'  : 'يدعم التطبيق حالياً تصدير سيرتك الذاتية كـ PDF عالي الجودة. قد تُضاف صيغ إضافية في التحديثات المستقبلية.',
  'faq_q9'  : 'أين يتم تخزين بيانات سيرتي الذاتية؟',
  'faq_a9'  : 'يتم تخزين جميع بيانات سيرتك الذاتية محلياً على جهازك. لا نرفع معلوماتك الشخصية إلى خوادمنا. وهذا يعني أن بياناتك تبقى خاصة ومتاحة بدون اتصال بالإنترنت.',
  'faq_q10' : 'كيف أحتفظ بنسخة احتياطية من سيري الذاتية؟',
  'faq_a10' : 'يتم تضمين سيرك الذاتية في النسخ الاحتياطية القياسية لجهازك (Google Drive على Android، iCloud على iOS) إذا كانت النسخ الاحتياطية مفعّلة في إعدادات جهازك. يمكنك أيضاً تصدير سير ذاتية فردية كـ PDF للاحتفاظ بنسخة.',
  'faq_q11' : 'التطبيق يعمل ببطء. ماذا أفعل؟',
  'faq_a11' : 'جرب إغلاق التطبيق وإعادة فتحه. إذا استمرت المشكلة، أعد تشغيل جهازك. تأكد من أنك تستخدم أحدث إصدار من التطبيق من Play Store / App Store.',
  'faq_q12' : 'سيرتي الذاتية لا تُصدَّر بشكل صحيح. ماذا أفعل؟',
  'faq_a12' : 'تأكد من توفر مساحة كافية على جهازك. جرب تقليل حجم الصور في سيرتك الذاتية. إذا استمرت المشكلة، يرجى التواصل مع فريق الدعم.',
  'faq_q13' : 'نسيت الحفظ — هل فقدت عملي؟',
  'faq_a13' : 'أبداً! يحفظ التطبيق تقدمك باستمرار أثناء التعديل.',

  // ─── very_top_header.dart ───────────────────────────────────────────────
  'header_app_title'                    : 'منشئ السيرة الذاتية',
  'header_app_subtitle'                 : 'مسيرتك، في أفضل صورة',
  'header_tooltip_back'                 : 'رجوع',
  'header_tooltip_my_cvs'               : 'سيري الذاتية',
  'header_tooltip_settings'             : 'الإعدادات',

  // ─── saved_cv_containers.dart ───────────────────────────────────────────
  'saved_section_title'                 : 'سيري الذاتية',
  'saved_count_single'                  : 'مستند واحد',
  'saved_count_plural'                  : '{n} مستندات',
  'saved_limit_reached'                 : 'تم الوصول إلى الحد',
  'saved_footer_count'                  : '{n} / 30 سيرة',
  'saved_filter_all'                    : 'الكل',
  'saved_filter_draft'                  : 'مسودة',
  'saved_filter_complete'               : 'مكتملة',
  'saved_status_complete'               : 'مكتملة',
  'saved_status_saved'                  : 'محفوظة',
  'saved_status_draft'                  : 'مسودة',
  'saved_empty_title'                   : 'لا توجد سير ذاتية بعد',
  'saved_empty_sub'                     : 'ابدأ ببناء سيرتك الذاتية الأولى أعلاه',
  'saved_search_empty_title'            : 'لا توجد نتائج',
  'saved_search_empty_sub'              : 'جرب مصطلح بحث مختلف',

  // ─── customization_panel.dart ───────────────────────────────────────────
  'custom_color_scheme_title'           : 'نظام الألوان',
  'custom_font_settings_title'          : 'إعدادات الخط',
  'custom_font_family_label'            : 'عائلة الخط',
  'custom_font_size_label'              : 'حجم الخط: ',
  'custom_current_template_title'       : 'القالب الحالي',
  'custom_change_template_btn'          : 'تغيير القالب',
  'custom_tpl_modern'                   : 'عصري',
  'custom_tpl_classic'                  : 'كلاسيكي',
  'custom_tpl_professional'             : 'احترافي',
  'custom_tpl_creative'                 : 'إبداعي',
  'custom_tpl_minimal'                  : 'بسيط',
  'custom_tpl_modern_desc'              : 'تصميم نظيف ومعاصر',
  'custom_tpl_classic_desc'             : 'تخطيط احترافي تقليدي',
  'custom_tpl_professional_desc'        : 'قالب موجّه للأعمال',
  'custom_tpl_creative_desc'            : 'تميّز بتصميم فريد',
  'custom_tpl_minimal_desc'             : 'أسلوب بسيط وأنيق',

  // ─── swipable_cv_templates.dart ─────────────────────────────────────────
  'swipe_section_title'                 : 'اختر القالب',
  'swipe_photo_badge'                   : 'صورة',

  // ─── template_data.dart ─────────────────────────────────────────────────
  'tpl_executive_name'                  : 'تنفيذي',
  'tpl_nordic_name'                     : 'نوردي',
  'tpl_vibrant_name'                    : 'نابض',
  'tpl_tech_dark_name'                  : 'تقني داكن',
  'tpl_luxury_name'                     : 'فاخر',
  'tpl_executive_tag'                   : 'الأكثر شعبية',
  'tpl_nordic_tag'                      : 'نظيف',
  'tpl_vibrant_tag'                     : 'إبداعي',
  'tpl_tech_dark_tag'                   : 'PRO',
  'tpl_luxury_tag'                      : 'نخبة',
  'tpl_executive_desc'                  : 'جريء وموثوق للمناصب العليا',
  'tpl_nordic_desc'                     : 'وضوح بسيط تثق به الشركات الكبرى',
  'tpl_vibrant_desc'                    : 'تميّز بالطاقة والألوان',
  'tpl_tech_dark_desc'                  : 'جماليات طرفية للمطورين',
  'tpl_luxury_desc'                     : 'رقي مذهّب على خلفية سوداء',

  // ─── saved_cv_detail_screen.dart ────────────────────────────────────────
  'detail_step_template'                : 'القالب',
  'detail_step_personal'                : 'شخصي',
  'detail_step_experience'              : 'الخبرة',
  'detail_step_education'               : 'التعليم',
  'detail_step_skills'                  : 'المهارات',
  'detail_step_additional'              : 'إضافي',
  'detail_step_references'              : 'المراجع',
  'detail_step_customize'               : 'تخصيص',
  'detail_banner_heading'               : 'أوشكت على الانتهاء!',
  'detail_banner_btn'                   : 'متابعة',
  'detail_banner_completion_label'      : 'نسبة الإكمال',
  'detail_stat_created_label'           : 'تاريخ الإنشاء',
  'detail_stat_steps_label'             : 'الخطوات المنجزة',
  'detail_section_template_style'       : 'نمط القالب',
  'detail_section_steps'                : 'الخطوات',
  'detail_steps_counter'                : '{done} من {total} مكتملة',
  'detail_step_sub'                     : 'الخطوة {n} من {total}',
  'detail_section_activity'             : 'النشاط',
  'detail_activity_created'             : 'تاريخ الإنشاء',
  'detail_activity_last_edited'         : 'آخر تعديل',
  'detail_activity_template'            : 'القالب',
  'detail_btn_continue_editing'         : 'متابعة التعديل',
  'detail_btn_edit_cv'                  : 'تعديل السيرة',
  'detail_option_rename'                : 'إعادة تسمية السيرة',
  'detail_option_delete'                : 'حذف السيرة',
  'detail_rename_title'                 : 'إعادة تسمية السيرة',
  'detail_rename_hint'                  : 'مثال: سيرة مهندس برمجيات',
  'detail_rename_error_empty'           : 'لا يمكن أن يكون الاسم فارغاً',
  'detail_rename_btn_cancel'            : 'إلغاء',
  'detail_rename_btn_save'              : 'حفظ',
  'detail_rename_snackbar'              : 'تمت إعادة التسمية إلى "{name}"',
  'detail_delete_title'                 : 'حذف السيرة الذاتية؟',
  'detail_delete_body'                  : 'سيؤدي هذا إلى حذف "{name}" نهائياً. لا يمكن التراجع عن هذا الإجراء.',
  'detail_delete_btn_cancel'            : 'إلغاء',
  'detail_delete_btn_confirm'           : 'حذف',

  // ─── cv_detail_widgets.dart ─────────────────────────────────────────────
  'detail_check_tile_complete'          : 'مكتمل',
  'detail_check_tile_incomplete'        : 'لم يتم ملؤه بعد',

  // ─── step_template_chooser.dart ─────────────────────────────────────────
  'chooser_title'                       : 'اختر قالبك',
  'chooser_subtitle'                    : 'اسحب للتصفح  ·  اضغط للاختيار  ·  اضغط مطولاً للمعاينة',
  'chooser_card_hold_hint'              : 'اضغط مطولاً للمعاينة',
  'chooser_card_pro_badge'              : 'PRO',
  'chooser_card_selected_badge'         : 'محدد',
  'chooser_modal_heading'               : 'سمّ سيرتك الذاتية',
  'chooser_modal_sub'                   : 'أعطها اسماً لتتمكن من إيجادها بسهولة في سيري الذاتية والسجل.',
  'chooser_modal_field_label'           : 'اسم السيرة الذاتية',
  'chooser_modal_save_btn'              : 'حفظ والبدء بالبناء',
  'chooser_modal_divider'               : 'أو متابعة سيرة موجودة',
  'chooser_nav_selected_sub'            : 'القالب المحدد',
  'chooser_nav_cta'                     : 'حفظ والمتابعة',

  // ─── Shared editor strings ───────────────────────────────────────────────
  'editor_max_entries_reached'          : 'تم الوصول إلى الحد الأقصى للمدخلات',
  'editor_show_hide'                    : 'إظهار/إخفاء',
  'editor_editing_badge'                : 'تعديل',
  'editor_field_required'               : 'مطلوب',
  'editor_tooltip_edit'                 : 'تعديل',
  'editor_tooltip_delete'               : 'حذف',
  'editor_date_start'                   : 'تاريخ البداية *',
  'editor_date_end'                     : 'تاريخ الانتهاء *',
  'editor_date_tap_hint'                : 'اضغط للاختيار',
  'editor_date_dialog_title'            : 'اختر الشهر والسنة',
  'editor_date_confirm'                 : 'تأكيد',
  'editor_panel_hide'                   : 'إخفاء',
  'editor_panel_show'                   : 'إظهار',
  'editor_validator_max_chars'          : 'الحد الأقصى {n} حرف',

  // ─── editor_screen.dart ─────────────────────────────────────────────────
  'editor_header_title'                 : 'ابنِ سيرتك الذاتية',
  'editor_header_step_sub'              : 'الخطوة {current} من {total} · {label}',
  'editor_step_template'                : 'القالب',
  'editor_step_personal'                : 'شخصي',
  'editor_step_experience'              : 'الخبرة',
  'editor_step_education'               : 'التعليم',
  'editor_step_skills'                  : 'المهارات',
  'editor_step_additional'              : 'إضافي',
  'editor_step_references'              : 'المراجع',
  'editor_step_customize'               : 'تخصيص',

  // ─── step_customize.dart + smart_layout_option.dart ─────────────────────
  'customize_title'                     : 'تخصيص',
  'customize_subtitle'                  : 'اجعل سيرتك الذاتية فريدة',
  'customize_smart_layout_btn'          : 'التخطيط الذكي',
  'customize_back_to_top'               : 'العودة إلى الأعلى',
  'customize_done_title'                : 'أنت جاهز تماماً!',
  'customize_done_sub'                  : 'اضغط على معاينة السيرة أدناه لرؤية سيرتك المكتملة',
  'customize_preview_btn'               : 'معاينة السيرة',

  // ─── customize_color_section.dart ───────────────────────────────────────
  'customize_color_section_title'       : 'نظام الألوان',
  'color_black'                         : 'أسود',
  'color_blue'                          : 'أزرق',
  'color_nordic_blue'                   : 'أزرق نوردي',
  'color_indigo'                        : 'نيلي',
  'color_teal'                          : 'أزرق مخضر',
  'color_green'                         : 'أخضر',
  'color_purple'                        : 'بنفسجي',
  'color_orange'                        : 'برتقالي',
  'color_red'                           : 'أحمر',
  'color_executive_gold'                : 'ذهبي تنفيذي',
  'color_vibrant_coral'                 : 'مرجاني نابض',
  'color_white'                         : 'أبيض',
  'color_white_bg'                      : 'خلفية بيضاء',
  'color_maroon'                        : 'كستنائي',
  'color_brutalist_yellow'              : 'أصفر خام',
  'color_neon_blue'                     : 'أزرق نيون',
  'color_blueprint_navy'                : 'كحلي',
  'color_light_grey'                    : 'رمادي فاتح',

  // ─── customize_font_section.dart ────────────────────────────────────────
  'customize_font_family_title'         : 'عائلة الخط',
  'customize_font_picker_title'         : 'اختر الخط',
  'customize_font_picker_sub'           : 'كل خط يظهر بتصميمه الخاص',
  'customize_font_preview_sample'       : 'الثعلب البني السريع',

  // ─── customize_size_section.dart ────────────────────────────────────────
  'customize_font_size_title'           : 'حجم الخط',
  'customize_font_size_label'           : 'حجم النص',
  'customize_font_size_value'           : '{n} نقطة',
  'customize_font_size_min'             : '10 نقاط',
  'customize_font_size_max'             : '16 نقطة',

  // ─── custom_image_sizer.dart ────────────────────────────────────────────
  'customize_image_size_title'          : 'حجم الصورة',
  'customize_image_size_label'          : 'حجم الصورة',
  'customize_image_size_value'          : '{n} بكسل',
  'customize_image_size_min'            : '10 بكسل',
  'customize_image_size_max'            : '16 بكسل',

  // ─── customize_preview.dart ─────────────────────────────────────────────
  'preview_live_label'                  : 'معاينة مباشرة',
  'preview_page_count_singular'         : 'صفحة واحدة',
  'preview_page_count_plural'           : '{n} صفحات',
  'preview_page_of'                     : 'صفحة {page} من {total}',
  'preview_live_hint'                   : 'التغييرات تُطبّق فوراً',
  'preview_template_unregistered'       : 'غير مسجّل في customize_preview.dart',

  // ─── cv_preview_bottom_bar.dart ─────────────────────────────────────────
  'preview_bar_preparing'               : 'جارٍ تحضير سيرتك الذاتية…',
  'preview_bar_print'                   : 'طباعة',
  'preview_bar_save_pdf'                : 'حفظ كـ PDF',
  'preview_bar_share'                   : 'مشاركة',

  // ─── cv_full_preview_screen.dart ────────────────────────────────────────
  'preview_screen_title'                : 'معاينة السيرة الذاتية',
  'preview_screen_sub'                  : '{n} {unit} · كما ستُطبع',
  'preview_page_singular'               : 'صفحة',
  'preview_page_plural'                 : 'صفحات',
  'preview_pdf_filename'                : 'سيرتي_الذاتية',
  'preview_share_subject'               : 'سيرتي الذاتية',
  'preview_snack_print_failed'          : 'فشلت الطباعة: {e}',
  'preview_snack_saved'                 : 'تم حفظ السيرة في التنزيلات ✓',
  'preview_snack_export_failed'         : 'فشل التصدير: {e}',
  'preview_snack_share_failed'          : 'فشلت المشاركة: {e}',
  'preview_template_not_registered'     : 'القالب غير مسجّل',

  // ─── template_full_preview_modal.dart ───────────────────────────────────
  'preview_modal_barrier_label'         : 'إغلاق المعاينة',
  'preview_modal_hint_photo'            : 'يدعم صورة الملف الشخصي  ·  اضغط على بطاقة للاختيار',
  'preview_modal_hint_no_photo'         : 'اضغط على بطاقة القالب لاختياره',

  // ─── cv_provider.dart ───────────────────────────────────────────────────
  'cv_default_title'                    : 'سيرتي الذاتية',
  'time_just_now'                       : 'الآن',
  'time_minutes_ago'                    : 'منذ {n} دقيقة',
  'time_hours_ago'                      : 'منذ {n} ساعة',
  'time_yesterday'                      : 'أمس',
  'time_days_ago'                       : 'منذ {n} أيام',
  'time_one_week_ago'                   : 'منذ أسبوع',
  'time_weeks_ago'                      : 'منذ {n} أسابيع',

  // ─── preview_registry.dart — TemplateCardInfo shared tag labels ──────────
  'tpl_tag_elegant'                     : 'أنيق',
  'tpl_tag_classic'                     : 'كلاسيكي',
  'tpl_tag_minimal'                     : 'بسيط',
  'tpl_tag_creative'                    : 'إبداعي',
  'tpl_tag_bold'                        : 'جريء',

  // ─── preview_registry.dart — template names ──────────────────────────────
  'tpl_gradient_name'                   : 'متدرج',
  'tpl_gradient_desc'                   : 'بطاقات بتدرج من اللون الأزرق المخضر إلى البنفسجي',
  'tpl_editorial_name'                  : 'تحريري',
  'tpl_editorial_desc'                  : 'أسلوب مجلة بالأحمر والكريمي',
  'tpl_pastel_soft_name'                : 'باستيل ناعم',
  'tpl_pastel_soft_desc'                : 'شريط جانبي لافندر وبطاقات ناعمة',
  'tpl_brutalist_name'                  : 'خام',
  'tpl_brutalist_desc'                  : 'شبكة خام وحدود جريئة وأصفر',
  'tpl_emerald_name'                    : 'زمردي',
  'tpl_emerald_desc'                    : 'أخضر غابي مع خط زمني',
  'tpl_infographic_name'                : 'إنفوغرافيك',
  'tpl_infographic_desc'                : 'لوحة داكنة مع مخططات دائرية',
  'tpl_art_deco_name'                   : 'آرت ديكو',
  'tpl_art_deco_desc'                   : 'فخامة هندسية ذهبية من عشرينيات القرن الماضي',
  'tpl_wina_dark_name'                  : 'وينا داكن',
  'tpl_wina_dark_desc'                  : 'إنفوغرافيك داكن مع حلقات',
  'tpl_rio_orange_name'                 : 'ريو برتقالي',
  'tpl_rio_orange_desc'                 : 'شريط جانبي داكن مع لمسة برتقالية',
  'tpl_summer_name'                     : 'صيفي',
  'tpl_summer_desc'                     : 'بسيط ونظيف بأتون رمادية ناعمة',
  'tpl_helene_name'                     : 'هيلين',
  'tpl_helene_desc'                     : 'ألوان بيج دافئة وأنيقة',
  'tpl_canfield_name'                   : 'كانفيلد',
  'tpl_canfield_desc'                   : 'كلاسيكي صارم بالأسود والأبيض',
  'tpl_collins_name'                    : 'كولينز',
  'tpl_collins_desc'                    : 'تخطيط كلاسيكي متوافق مع ATS',
  'tpl_tony_dark_name'                  : 'توني داكن',
  'tpl_tony_dark_desc'                  : 'أسلوب إنفوغرافيك برتقالي داكن',
  'tpl_fashion_name'                    : 'أزياء',
  'tpl_fashion_desc'                    : 'رسم تقني على شبكة',
  'tpl_archivist_name'                  : 'أرشيفي',
  'tpl_archivist_desc'                  : 'تخطيط كلاسيكي بعمودين مع تسميات',
  'tpl_diplomat_name'                   : 'دبلوماسي',
  'tpl_diplomat_desc'                   : 'رؤوس مظللة مع قيادات معينية',
  'tpl_meridian_name'                   : 'ميريديان',
  'tpl_meridian_desc'                   : 'رؤوس متمركزة وشركات بارزة',
  'tpl_momentum_name'                   : 'زخم',
  'tpl_momentum_desc'                   : 'اسم جريء ونقاط زمنية وإنجازات',

  // ─── step_personal_info.dart ────────────────────────────────────────────
  'personal_title'                      : 'المعلومات الشخصية',
  'personal_subtitle'                   : 'عرّف أصحاب العمل بنفسك',
  'personal_profile_counter'            : '{n}/{max} ملفات شخصية',
  'personal_info_banner'                : 'احفظ حتى 5 ملفات شخصية وحدد واحداً لكل سيرة ذاتية. يتم حفظ اختيارك لكل سيرة بشكل مستقل.',
  'personal_snack_max'                  : 'تم الوصول إلى الحد الأقصى وهو {n} ملفات شخصية.',
  'personal_add_btn'                    : 'إضافة ملف شخصي جديد',
  'personal_library_title'              : 'الملفات الشخصية المحفوظة',
  'personal_selected_one'               : '1 محدد',
  'personal_selected_none'              : 'لا يوجد محدد',
  'personal_library_hint'               : 'اضغط على بطاقة لتحديدها لهذه السيرة فقط. تحتفظ السير الأخرى بتحديداتها المستقلة.',
  'personal_empty_message'              : 'لا توجد ملفات شخصية محفوظة بعد',
  'personal_empty_sub'                  : 'اضغط أعلاه لإضافة معلوماتك الشخصية',
  'personal_nav_next'                   : 'حفظ والمتابعة',
  'personal_card_active_badge'          : 'نشط لهذه السيرة',
  'personal_sheet_title_add'            : 'ملف شخصي جديد',
  'personal_sheet_title_edit'           : 'تعديل الملف الشخصي',
  'personal_sheet_brutalist_badge'      : 'خام',
  'personal_sheet_brutalist_banner'     : 'قالب Brutalist يحتوي على حقول اتصال مدمجة. تظهر القيم الأقصر (مثل المدينة فقط) بشكل أفضل.',
  'personal_section_photo'              : 'صورة الملف الشخصي',
  'personal_section_basic'              : 'البيانات الأساسية',
  'personal_section_contact'            : 'التواصل',
  'personal_section_online'             : 'الحضور الرقمي',
  'personal_section_summary'            : 'الملخص المهني',
  'personal_field_first_name'           : 'الاسم الأول *',
  'personal_field_last_name'            : 'اسم العائلة',
  'personal_field_job_title'            : 'المسمى الوظيفي *',
  'personal_field_email'                : 'البريد الإلكتروني *',
  'personal_field_phone'                : 'رقم الهاتف *',
  'personal_field_location'             : 'الموقع',
  'personal_field_location_brut'        : 'الموقع (المدينة فقط)',
  'personal_field_website'              : 'الموقع / المحفظة',
  'personal_field_linkedin'             : 'رابط LinkedIn',
  'personal_hint_first_name'            : 'مثال: محمد',
  'personal_hint_last_name'             : 'مثال: العلي',
  'personal_hint_job_title'             : 'مثال: مهندس أول',
  'personal_hint_email'                 : 'مثال: mohammed@example.com',
  'personal_hint_phone'                 : 'مثال: +966 50 123 4567',
  'personal_hint_location'              : 'مثال: الرياض، المملكة العربية السعودية',
  'personal_hint_location_brut'         : 'مثال: الرياض',
  'personal_hint_website'               : 'مثال: github.com/mohammed',
  'personal_hint_website_brut'          : 'مثال: github.com/mo',
  'personal_hint_linkedin'              : 'مثال: linkedin.com/in/mohammed',
  'personal_hint_linkedin_brut'         : 'مثال: linkedin.com/in/mo',
  'personal_summary_hint_label'         : 'اجعله موجزاً — يظهر هذا في أعلى سيرتك الذاتية.',
  'personal_hint_summary'               : 'ملخص موجز من 2-3 جمل عن خلفيتك وأهدافك...',
  'personal_validator_email'            : 'أدخل بريداً إلكترونياً صحيحاً',
  'personal_field_char_limit_tooltip'   : 'تم الوصول إلى حد الأحرف',
  'personal_sheet_btn_save'             : 'حفظ الملف الشخصي',
  'personal_sheet_btn_update'           : 'حفظ التغييرات',

  // ─── profile_photo_widget.dart ──────────────────────────────────────────
  'photo_sheet_title'                   : 'اختر صورة',
  'photo_option_gallery'                : 'الاختيار من المعرض',
  'photo_option_camera'                 : 'التقاط صورة',
  'photo_option_reposition'             : 'إعادة وضع الصورة',
  'photo_option_remove'                 : 'حذف الصورة',
  'photo_status_added'                  : 'تمت إضافة الصورة ✓',
  'photo_status_empty'                  : 'أضف صورة شخصية احترافية',
  'photo_chip_gallery'                  : 'المعرض',
  'photo_chip_camera'                   : 'الكاميرا',
  'photo_chip_reposition'               : 'إعادة الوضع',
  'photo_reposition_title'              : 'إعادة وضع الصورة',
  'photo_reposition_sub'                : 'اسحب الصورة لضبط موضعها',
  'photo_reposition_reset'              : 'إعادة ضبط إلى المنتصف',
  'photo_reposition_apply'              : 'تطبيق',

  // ─── step_skills.dart ───────────────────────────────────────────────────
  'skills_title'                        : 'المهارات',
  'skills_subtitle'                     : 'أبرز قدراتك الرئيسية',
  'skills_add_btn'                      : 'إضافة مهارة جديدة',
  'skills_snack_max_icons'              : 'تم الوصول إلى الحد الأقصى وهو 10 أيقونات.',
  'skills_snack_max_skills'             : 'تم الوصول إلى الحد الأقصى وهو 15 مهارة.',
  'skills_library_title'                : 'المهارات المحفوظة',
  'skills_library_hint'                 : 'المهارات المحددة مدرجة في هذه السيرة. يتم حفظ تحديداتك تلقائياً.',
  'skills_nav_next'                     : 'المتابعة إلى المعلومات الإضافية',
  'skills_wina_header_icon_bar'         : 'شريط أيقونات الرأس',
  'skills_wina_on'                      : 'مفعّل',
  'skills_wina_off'                     : 'معطّل',
  'skills_wina_bar_on_sub'              : 'تظهر دوائر الأيقونات الملونة في رأس السيرة الذاتية.',
  'skills_wina_bar_off_sub'             : 'صف الأيقونات مخفي — مزيد من المساحة لمعلومات التواصل.',
  'skills_wina_palette_hint'            : 'تظهر الأيقونات كدوائر ملونة بترتيب اللوحة.',
  'skills_wina_preview_label'           : 'معاينة',
  'skills_wina_disabled_hint'           : 'فعّل شريط الأيقونات أعلاه لاختيار الأيقونات التي تظهر في رأس السيرة.',
  'skills_sheet_title_add'              : 'إضافة مهارة',
  'skills_sheet_title_edit'             : 'تعديل المهارة',
  'skills_sheet_field_name'             : 'اسم المهارة *',
  'skills_sheet_hint_short'             : 'مثال: Flutter، تصميم',
  'skills_sheet_hint_long'              : 'مثال: Flutter، إدارة المشاريع',
  'skills_sheet_validator_max'          : 'الحد الأقصى {n} حرف',
  'skills_sheet_proficiency'            : 'مستوى الإتقان',
  'skills_sheet_beginner'               : 'مبتدئ',
  'skills_sheet_expert'                 : 'خبير',
  'skills_sheet_btn_save'               : 'حفظ المهارة',
  'skills_sheet_btn_update'             : 'تحديث المهارة',

  // ─── step_personal_reference.dart ───────────────────────────────────────
  'refs_title'                          : 'المراجع الشخصية',
  'refs_subtitle'                       : 'أشخاص يزكّونك شخصياً',
  'refs_add_btn'                        : 'إضافة مرجع شخصي جديد',
  'refs_snack_max_selected'             : 'يمكن تحديد 4 مراجع كحد أقصى للسيرة الواحدة.',
  'refs_snack_max_saved'                : 'تم الوصول إلى الحد الأقصى وهو 10 مراجع محفوظة.',
  'refs_library_title'                  : 'المراجع المحفوظة',
  'refs_library_hint'                   : 'المراجع المحددة مدرجة في هذه السيرة. الحد الأقصى 4 لكل سيرة. يتم حفظ تحديداتك تلقائياً.',
  'refs_nav_next'                       : 'المتابعة إلى التخصيص',
  'refs_sheet_title_add'                : 'إضافة مرجع شخصي',
  'refs_sheet_title_edit'               : 'تعديل المرجع الشخصي',
  'refs_sheet_sub_add'                  : 'شخص يستطيع أن يوصي بك لأصحاب العمل شخصياً.',
  'refs_sheet_sub_edit'                 : 'حدّث بيانات هذا المرجع أدناه.',
  'refs_sheet_field_name'               : 'الاسم الكامل *',
  'refs_sheet_field_title'              : 'المسمى الوظيفي *',
  'refs_sheet_field_company'            : 'الشركة (اختياري)',
  'refs_sheet_field_email'              : 'البريد الإلكتروني *',
  'refs_sheet_field_phone'              : 'رقم الهاتف *',
  'refs_sheet_hint_name'                : 'مثال: أحمد الخالد',
  'refs_sheet_hint_title'               : 'مثال: مدير هندسة',
  'refs_sheet_hint_company'             : 'مثال: شركة أكمي',
  'refs_sheet_hint_email'               : 'مثال: ahmed@acme.com',
  'refs_sheet_hint_phone'               : 'مثال: +966 50 123 4567',
  'refs_sheet_validator_email'          : 'أدخل عنوان بريد إلكتروني صحيح',
  'refs_sheet_btn_save'                 : 'حفظ المرجع الشخصي',
  'refs_sheet_btn_update'               : 'تحديث المرجع الشخصي',

  // ─── step_experience.dart ───────────────────────────────────────────────
  'exp_title'                           : 'الخبرة العملية',
  'exp_subtitle'                        : 'أضف سجلك المهني',
  'exp_banner_info'                     : 'ستظهر حتى {n} مسؤوليات لكل دور في السيرة. 3-6 أدوار عادةً تناسب 1-2 صفحة.',
  'exp_add_btn'                         : 'إضافة خبرة جديدة',
  'exp_snack_max_selected'              : 'يمكن تحديد 8 خبرات كحد أقصى للسيرة الواحدة.',
  'exp_snack_max_saved'                 : 'تم الوصول إلى الحد الأقصى وهو 12 خبرة محفوظة.',
  'exp_library_title'                   : 'الخبرات المحفوظة',
  'exp_library_hint'                    : 'المدخلات المحددة مدرجة في هذه السيرة فقط. تحتفظ السير الأخرى بتحديداتها المستقلة.',
  'exp_nav_next'                        : 'المتابعة إلى التعليم',
  'exp_empty_message'                   : 'لم تتم إضافة خبرة بعد',
  'exp_empty_sub'                       : 'اضغط أعلاه لإضافة دورك الأول',
  'exp_card_resp_singular'              : 'مسؤولية',
  'exp_card_resp_plural'                : 'مسؤوليات',
  'exp_card_resp_tooltip'               : 'ستظهر أول 8 مسؤوليات فقط في السيرة',
  'exp_sheet_title_add'                 : 'إضافة خبرة',
  'exp_sheet_title_edit'                : 'تعديل الخبرة',
  'exp_sheet_field_job_title'           : 'المسمى الوظيفي *',
  'exp_sheet_field_company'             : 'الشركة *',
  'exp_sheet_field_location'            : 'الموقع',
  'exp_sheet_section_responsibilities'  : 'المسؤوليات الرئيسية',
  'exp_sheet_resp_hint_info'            : 'الحد الأقصى 8 نقاط · 200 حرف لكل منها',
  'exp_sheet_resp_label'                : 'المسؤولية {n}',
  'exp_sheet_resp_hint'                 : 'مثال: قاد فريقاً من 5 مهندسين',
  'exp_sheet_resp_add_btn'              : 'إضافة مسؤولية',
  'exp_sheet_resp_max_info'             : 'تم الوصول إلى الحد الأقصى {n} مسؤولية',
  'exp_sheet_resp_validator_max'        : 'الحد الأقصى 200 حرف',
  'exp_sheet_hint_job_title'            : 'مثال: مطور أول',
  'exp_sheet_hint_location'             : 'مثال: الرياض، المملكة العربية السعودية',
  'exp_sheet_btn_save'                  : 'حفظ الخبرة',
  'exp_sheet_btn_update'                : 'حفظ التغييرات',
  'exp_date_present'                    : 'حاضر / الدور الحالي',

  // ─── step_education.dart ────────────────────────────────────────────────
  'edu_title'                           : 'التعليم',
  'edu_subtitle'                        : 'أضف خلفيتك الأكاديمية',
  'edu_add_btn'                         : 'إضافة تعليم جديد',
  'edu_snack_max_selected'              : 'يمكن تحديد 8 مدخلات تعليمية كحد أقصى للسيرة الواحدة.',
  'edu_snack_max_saved'                 : 'تم الوصول إلى الحد الأقصى وهو 12 مدخلاً تعليمياً محفوظاً.',
  'edu_library_title'                   : 'التعليم المحفوظ',
  'edu_library_hint'                    : 'المدخلات المحددة مدرجة في هذه السيرة. يتم حفظ تحديداتك تلقائياً.',
  'edu_nav_next'                        : 'المتابعة إلى المهارات',
  'edu_empty_message'                   : 'لم يتم إضافة تعليم بعد',
  'edu_empty_sub'                       : 'اضغط أعلاه لإضافة مؤهلاتك',
  'edu_card_bullet_singular'            : 'نقطة',
  'edu_card_bullet_plural'              : 'نقاط',
  'edu_sheet_title_add'                 : 'إضافة تعليم',
  'edu_sheet_title_edit'                : 'تعديل التعليم',
  'edu_sheet_field_degree'              : 'الدرجة العلمية / المؤهل *',
  'edu_sheet_field_institution'         : 'المؤسسة التعليمية *',
  'edu_sheet_section_key_points'        : 'النقاط الرئيسية',
  'edu_sheet_key_points_hint_info'      : 'اختياري · نقطة واحدة · 100 حرف كحد أقصى',
  'edu_sheet_point_label'               : 'النقطة {n}',
  'edu_sheet_point_add_btn'             : 'إضافة نقطة',
  'edu_sheet_point_max_info'            : 'تم الوصول إلى الحد الأقصى {n} نقاط',
  'edu_sheet_point_validator_max'       : 'الحد الأقصى {n} حرف',
  'edu_sheet_hint_degree'               : 'مثال: بكالوريوس علوم الحاسب',
  'edu_sheet_hint_institution'          : 'مثال: جامعة الملك سعود',
  'edu_sheet_hint_bullet'               : 'مثال: مرتبة الشرف الأولى',
  'edu_sheet_btn_save'                  : 'حفظ التعليم',
  'edu_sheet_btn_update'                : 'حفظ التغييرات',
  'edu_date_present'                    : 'حاضر / الدراسة الحالية',

  // ─── step_additional.dart ───────────────────────────────────────────────
  'additional_title'                    : 'معلومات إضافية',
  'additional_subtitle'                 : 'شهادات ولغات والمزيد',
  'additional_cert_section_title'       : 'الشهادات',
  'additional_cert_counter'             : '{sel}/{total} محدد · الحد الأقصى {max}',
  'additional_cert_hide'                : 'إخفاء',
  'additional_cert_show'                : 'إظهار',
  'additional_cert_add_btn'             : 'إضافة',
  'additional_cert_snack_max'           : 'تم الوصول إلى الحد الأقصى وهو {n} شهادات.',
  'additional_cert_hint'                : 'المدخلات المحددة مدرجة في هذه السيرة. يتم حفظ تحديداتك تلقائياً.',
  'additional_cert_empty'               : 'لم تتم إضافة شهادات بعد',
  'additional_lang_section_title'       : 'اللغات',
  'additional_lang_add_hint'            : 'مثال: الإسبانية',
  'additional_lang_snack_max'           : 'تم الوصول إلى الحد الأقصى وهو {n} لغات.',
  'additional_lang_empty'               : 'لم تتم إضافة لغات بعد',
  'additional_hobby_section_title'      : 'الهوايات والاهتمامات',
  'additional_hobby_add_hint'           : 'مثال: التصوير',
  'additional_hobby_snack_max'          : 'تم الوصول إلى الحد الأقصى وهو {n} هوايات.',
  'additional_hobby_empty'              : 'لم تتم إضافة هوايات بعد',
  'additional_section_hint'             : 'المدخلات المحددة مدرجة في هذه السيرة. يتم حفظ تحديداتك تلقائياً.',
  'additional_nav_next'                 : 'المتابعة إلى المراجع',
  'cert_sheet_title_add'                : 'إضافة شهادة',
  'cert_sheet_title_edit'               : 'تعديل الشهادة',
  'cert_sheet_sub'                      : 'أضف مؤهلاً أو شهادة أو اعتماداً مهنياً.',
  'cert_sheet_field_name'               : 'اسم الشهادة *',
  'cert_sheet_field_issued_by'          : 'جهة الإصدار (اختياري)',
  'cert_sheet_field_short_desc'         : 'وصف مختصر (اختياري)',
  'cert_sheet_hint_name'                : 'مثال: مهندس حلول AWS',
  'cert_sheet_hint_issued_by'           : 'مثال: Amazon Web Services',
  'cert_sheet_hint_short_desc'          : 'مثال: تم الحصول عليها 2024',
  'cert_sheet_btn_save'                 : 'حفظ الشهادة',
  'cert_sheet_btn_update'               : 'تحديث الشهادة',
  'simple_sheet_title_add_language'     : 'إضافة لغة',
  'simple_sheet_title_edit_language'    : 'تعديل اللغة',
  'simple_sheet_title_add_hobby'        : 'إضافة هواية',
  'simple_sheet_title_edit_hobby'       : 'تعديل الهواية',
  'simple_sheet_btn_save'               : 'حفظ',
  'simple_sheet_btn_update'             : 'تحديث',

  // ─── pdf_generator.dart / pdf_service.dart ──────────────────────────────
  'pdf_section_contact'                 : 'التواصل',
  'pdf_section_about_me'                : 'نبذة عني',
  'pdf_section_summary'                 : 'الملخص',
  'pdf_section_summary_short'           : 'الملخص',
  'pdf_section_profile'                 : 'الملف الشخصي',
  'pdf_section_experience'              : 'الخبرة العملية',
  'pdf_section_experience_short'        : 'الخبرة',
  'pdf_section_education'               : 'التعليم',
  'pdf_section_skills'                  : 'المهارات',
  'pdf_section_languages'               : 'اللغات',
  'pdf_label_email'                     : 'البريد الإلكتروني',
  'pdf_label_phone'                     : 'الهاتف',
  'pdf_label_location'                  : 'الموقع',

  // ─── cv_limit_dialog ────────────────────────────────────────────────────
  'limit_dialog_title'                  : 'تم الوصول إلى حد السير الذاتية',
  'limit_dialog_body'                   : 'لقد وصلت إلى الحد الأقصى وهو 30 سيرة ذاتية. يرجى حذف سيرة موجودة قبل إنشاء سيرة جديدة.',
  'limit_dialog_go_to_my_cvs'           : 'الذهاب إلى سيري الذاتية',
  'limit_dialog_cancel'                 : 'إلغاء',
  'refs_count_summary'                  : '{checked}/{maxChecked} محدد · {saved}/{maxSaved} محفوظ',
  'refs_selected_badge'                 : '{n} محدد',
  'refs_empty_message'                  : 'لا توجد مراجع محفوظة بعد',
  'refs_empty_sub'                      : 'اضغط أعلاه لإضافة مرجع شخصي',
};