// lib/services/qr_service.dart
//
// Defines a small, versioned JSON payload the app puts into its own QR
// codes (e.g. "share this expense" from ExpenseScreen) and can then read
// back on ScanScreen. This only recognizes codes generated by this app —
// scanning an arbitrary/unrelated QR code will fail cleanly via
// QrDecodeResult.error rather than throwing.
//
// REFERENCE NUMBER PASS (this update): the payload now carries
// referenceNumber (defaults to '' when the expense doesn't have one).
// This is what lets expense_screen.dart's scan flow tell "open the
// existing local expense" apart from "prefill a new one" — after decode,
// it calls ExpenseProvider.findByReferenceNumber(draft.referenceNumber),
// a plain local list scan. No server round-trip, no database — the QR
// itself is the only data source.
//
// Payload shape:
//   { "app": "invoice_quote_builder", "type": "expense", "v": 1,
//     "vendor": "...", "amount": 42.5, "currency": "NZD",
//     "categoryId": "travel", "date": "2026-07-29T00:00:00.000",
//     "notes": "...", "referenceNumber": "..." }

import 'dart:convert';

const String _kAppTag = 'invoice_quote_builder';
const int _kPayloadVersion = 1;

class ScannedExpenseDraft {
  final String vendor;
  final double amount;
  final String currency;
  final String categoryId;
  final DateTime date;
  final String notes;
  final String referenceNumber;

  const ScannedExpenseDraft({
    required this.vendor,
    required this.amount,
    required this.currency,
    required this.categoryId,
    required this.date,
    required this.notes,
    this.referenceNumber = '',
  });
}

class QrDecodeResult {
  final ScannedExpenseDraft? draft;
  final String? error;
  const QrDecodeResult._({this.draft, this.error});

  factory QrDecodeResult.success(ScannedExpenseDraft draft) =>
      QrDecodeResult._(draft: draft);
  factory QrDecodeResult.failure(String error) =>
      QrDecodeResult._(error: error);

  bool get isSuccess => draft != null;
}

class QrService {
  /// Builds the string to feed into QrImageView for an expense.
  static String encodeExpense({
    required String vendor,
    required double amount,
    required String currency,
    required String categoryId,
    required DateTime date,
    String notes = '',
    String referenceNumber = '',
  }) {
    return jsonEncode({
      'app': _kAppTag,
      'type': 'expense',
      'v': _kPayloadVersion,
      'vendor': vendor,
      'amount': amount,
      'currency': currency,
      'categoryId': categoryId,
      'date': date.toIso8601String(),
      'notes': notes,
      'referenceNumber': referenceNumber,
    });
  }

  /// Parses a raw scanned string (from camera or gallery image) back into
  /// a draft the Add Expense screen can pre-fill. Never throws — always
  /// returns a QrDecodeResult, success or failure.
  ///
  /// Error copy (this pass): made explicit that this scanner only
  /// recognizes codes generated by this app itself, and points the person
  /// toward generating a compatible code (or getting the app) rather than
  /// a generic "invalid code" message.
  static QrDecodeResult decode(String raw) {
    Map<String, dynamic> data;
    try {
      data = jsonDecode(raw) as Map<String, dynamic>;
    } catch (_) {
      return QrDecodeResult.failure(
        'This scanner only reads QR codes generated within Invoice & Quote '
        'Generator Pro — for example, from the "Share as QR" option on an '
        'expense. Please scan a code created by the app.',
      );
    }

    if (data['app'] != _kAppTag || data['type'] != 'expense') {
      return QrDecodeResult.failure(
        "This code wasn't generated by Invoice & Quote Generator Pro. "
        'To use this scanner, share the code from within the app first — '
        'via "Share as QR" on an invoice, quote, receipt, or expense — '
        "then scan that. If you don't have the app yet, search "
        '"Invoice & Quote Generator Pro" on the Play Store.',
      );
    }

    try {
      return QrDecodeResult.success(ScannedExpenseDraft(
        vendor: data['vendor'] as String? ?? '',
        amount: (data['amount'] as num?)?.toDouble() ?? 0.0,
        currency: data['currency'] as String? ?? '',
        categoryId: data['categoryId'] as String? ?? 'other',
        date: DateTime.tryParse(data['date'] as String? ?? '') ?? DateTime.now(),
        notes: data['notes'] as String? ?? '',
        referenceNumber: data['referenceNumber'] as String? ?? '',
      ));
    } catch (_) {
      return QrDecodeResult.failure(
        'This code was generated by Invoice & Quote Generator Pro but is '
        'missing some expected details — it may be damaged, cropped, or '
        'from an older version of the app.',
      );
    }
  }
}
