// lib/services/qr_service.dart
//
// Defines a small, versioned JSON payload the app puts into its own QR
// codes (e.g. "share this expense" from ExpenseScreen) and can then read
// back on ScanScreen. This only recognizes codes generated by this app —
// scanning an arbitrary/unrelated QR code will fail cleanly via
// QrDecodeResult.error rather than throwing.
//
// Payload shape:
//   { "app": "invoice_quote_builder", "type": "expense", "v": 1,
//     "vendor": "...", "amount": 42.5, "currency": "NZD",
//     "categoryId": "travel", "date": "2026-07-29T00:00:00.000",
//     "notes": "..." }

import 'dart:convert';

const String _kAppTag = 'invoice_quote_builder';
const int _kPayloadVersion = 1;

class ScannedExpenseDraft {
  final String vendor;
  final double amount;
  final String currency;
  final String categoryId;
  final DateTime date;
  final String notes;

  const ScannedExpenseDraft({
    required this.vendor,
    required this.amount,
    required this.currency,
    required this.categoryId,
    required this.date,
    required this.notes,
  });
}

class QrDecodeResult {
  final ScannedExpenseDraft? draft;
  final String? error;
  const QrDecodeResult._({this.draft, this.error});

  factory QrDecodeResult.success(ScannedExpenseDraft draft) =>
      QrDecodeResult._(draft: draft);
  factory QrDecodeResult.failure(String error) =>
      QrDecodeResult._(error: error);

  bool get isSuccess => draft != null;
}

class QrService {
  /// Builds the string to feed into QrImageView for an expense.
  static String encodeExpense({
    required String vendor,
    required double amount,
    required String currency,
    required String categoryId,
    required DateTime date,
    String notes = '',
  }) {
    return jsonEncode({
      'app': _kAppTag,
      'type': 'expense',
      'v': _kPayloadVersion,
      'vendor': vendor,
      'amount': amount,
      'currency': currency,
      'categoryId': categoryId,
      'date': date.toIso8601String(),
      'notes': notes,
    });
  }

  /// Parses a raw scanned string (from camera or gallery image) back into
  /// a draft the Add Expense screen can pre-fill. Never throws — always
  /// returns a QrDecodeResult, success or failure.
  static QrDecodeResult decode(String raw) {
    Map<String, dynamic> data;
    try {
      data = jsonDecode(raw) as Map<String, dynamic>;
    } catch (_) {
      return QrDecodeResult.failure(
        "That code isn't in a format this app recognizes.",
      );
    }

    if (data['app'] != _kAppTag || data['type'] != 'expense') {
      return QrDecodeResult.failure(
        "That code doesn't look like an expense code from this app.",
      );
    }

    try {
      return QrDecodeResult.success(ScannedExpenseDraft(
        vendor: data['vendor'] as String? ?? '',
        amount: (data['amount'] as num?)?.toDouble() ?? 0.0,
        currency: data['currency'] as String? ?? '',
        categoryId: data['categoryId'] as String? ?? 'other',
        date: DateTime.tryParse(data['date'] as String? ?? '') ?? DateTime.now(),
        notes: data['notes'] as String? ?? '',
      ));
    } catch (_) {
      return QrDecodeResult.failure('That code is missing some expected fields.');
    }
  }
}
